ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler Class Reference
Public Member Functions
__construct (Gateway $objectStateGateway, Mapper $objectStateMapper)
createGroup (InputStruct $input)
loadGroup ($groupId)
loadGroupByIdentifier ($identifier)
loadAllGroups ($offset=0, $limit=-1)
loadObjectStates ($groupId)
updateGroup ($groupId, InputStruct $input)
deleteGroup ($groupId)
create ($groupId, InputStruct $input)
load ($stateId)
loadByIdentifier ($identifier, $groupId)
update ($stateId, InputStruct $input)
setPriority ($stateId, $priority)
delete ($stateId)
setContentState ($contentId, $groupId, $stateId)
getContentState ($contentId, $stateGroupId)
getContentCount ($stateId)
Protected Attributes
$objectStateGateway
$objectStateMapper
Detailed Description
The Object State Handler class provides managing of object states and groups
Definition at line 19 of file Handler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::__construct (Gateway $objectStateGateway, Mapper $objectStateMapper)
Creates a new ObjectState Handler
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway $objectStateGateway
\eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Mapper $objectStateMapper
Definition at line 41 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler\$objectStateGateway, and eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler\$objectStateMapper.
    {
        $this->objectStateGateway = $objectStateGateway;
        $this->objectStateMapper = $objectStateMapper;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::create ($groupId, InputStruct $input)
Creates a new object state in the given group. The new state gets the last priority. Note: in current kernel: If it is the first state all content objects will set to this state.
Parameters
mixed $groupId
\eZ\Publish\SPI\Persistence\Content\ObjectState\InputStruct $input
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 177 of file Handler.php.
    {
        $objectState = $this->objectStateMapper->createObjectStateFromInputStruct( $input );
        $this->objectStateGateway->insertObjectState( $objectState, $groupId );
        return $objectState;
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::createGroup (InputStruct $input)
Creates a new object state group
Parameters
\eZ\Publish\SPI\Persistence\Content\ObjectState\InputStruct $input
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 54 of file Handler.php.
    {
        $objectStateGroup = $this->objectStateMapper->createObjectStateGroupFromInputStruct( $input );
        $this->objectStateGateway->insertObjectStateGroup( $objectStateGroup );
        return $objectStateGroup;
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::delete ($stateId)
Deletes a object state. The state of the content objects is reset to the first object state in the group.
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If state with $stateId doesn't exist
Parameters
mixed $stateId
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 280 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler\load(), and eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler\loadObjectStates().
    {
        // Get the object state first as we need group ID
        // to reorder the priorities and reassign content to another state in the group
        $objectState = $this->load( $stateId );
        $this->objectStateGateway->deleteObjectState( $objectState->id );
        $remainingStates = $this->loadObjectStates( $objectState->groupId );
        if ( empty( $remainingStates ) )
        {
            // If there are no more states in the group, just remove the state links
            $this->objectStateGateway->deleteObjectStateLinks( $objectState->id );
            return;
        }
        $priority = 0;
        foreach ( $remainingStates as $remainingState )
        {
            $this->objectStateGateway->updateObjectStatePriority( $remainingState->id, $priority );
            $priority++;
        }
        $remainingStates = $this->loadObjectStates( $objectState->groupId );
        $this->objectStateGateway->updateObjectStateLinks( $objectState->id, current( $remainingStates )->id );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::deleteGroup ($groupId)
Deletes a object state group including all states and links to content
Parameters
mixed $groupId
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 154 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler\loadObjectStates().
    {
        $objectStates = $this->loadObjectStates( $groupId );
        foreach ( $objectStates as $objectState )
        {
            $this->objectStateGateway->deleteObjectStateLinks( $objectState->id );
            $this->objectStateGateway->deleteObjectState( $objectState->id );
        }
        $this->objectStateGateway->deleteObjectStateGroup( $groupId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::getContentCount ($stateId)
Returns the number of objects which are in this state
Parameters
mixed $stateId
Returns
int
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 353 of file Handler.php.
    {
        return $this->objectStateGateway->getContentCount( $stateId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::getContentState ($contentId, $stateGroupId)
Gets the object-state of object identified by $contentId.
The $state is the id of the state within one group.
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If no state is found
Parameters
mixed $contentId
mixed $stateGroupId
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 334 of file Handler.php.
    {
        $data = $this->objectStateGateway->loadObjectStateDataForContent( $contentId, $stateGroupId );
        if ( empty( $data ) )
        {
            throw new NotFoundException( "ObjectState", array( "groupId" => $stateGroupId ) );
        }
        return $this->objectStateMapper->createObjectStateFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::load ($stateId)
Loads an object state
Parameters
mixed $stateId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the state was not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 194 of file Handler.php.
    {
        $data = $this->objectStateGateway->loadObjectStateData( $stateId );
        if ( empty( $data ) )
        {
            throw new NotFoundException( "ObjectState", $stateId );
        }
        return $this->objectStateMapper->createObjectStateFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::loadAllGroups ($offset = 0, $limit = -1)
Loads all object state groups
Parameters
int $offset
int $limit
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 112 of file Handler.php.
    {
        $data = $this->objectStateGateway->loadObjectStateGroupListData( $offset, $limit );
        return $this->objectStateMapper->createObjectStateGroupListFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::loadByIdentifier ($identifier, $groupId)
Loads an object state by identifier and group it belongs to
Parameters
string $identifier
mixed $groupId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the state was not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 216 of file Handler.php.
    {
        $data = $this->objectStateGateway->loadObjectStateDataByIdentifier( $identifier, $groupId );
        if ( empty( $data ) )
        {
            throw new NotFoundException( "ObjectState", array( 'identifier' => $identifier, 'groupId' => $groupId ) );
        }
        return $this->objectStateMapper->createObjectStateFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::loadGroup ($groupId)
Loads an object state group
Parameters
mixed $groupId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the group was not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 71 of file Handler.php.
    {
        $data = $this->objectStateGateway->loadObjectStateGroupData( $groupId );
        if ( empty( $data ) )
        {
            throw new NotFoundException( "ObjectStateGroup", $groupId );
        }
        return $this->objectStateMapper->createObjectStateGroupFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::loadGroupByIdentifier ($identifier)
Loads a object state group by identifier
Parameters
string $identifier
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the group was not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 92 of file Handler.php.
    {
        $data = $this->objectStateGateway->loadObjectStateGroupDataByIdentifier( $identifier );
        if ( empty( $data ) )
        {
            throw new NotFoundException( "ObjectStateGroup", $identifier );
        }
        return $this->objectStateMapper->createObjectStateGroupFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::loadObjectStates ($groupId)
This method returns the ordered list of object states of a group
Parameters
mixed $groupId
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 125 of file Handler.php.
    {
        $data = $this->objectStateGateway->loadObjectStateListData( $groupId );
        return $this->objectStateMapper->createObjectStateListFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::setContentState ($contentId, $groupId, $stateId)
Sets the object-state of a state group to $stateId for the given content.
Parameters
mixed $contentId
mixed $groupId
mixed $stateId
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 316 of file Handler.php.
    {
        $this->objectStateGateway->setContentState( $contentId, $groupId, $stateId );
        return true;
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::setPriority ($stateId, $priority)
Changes the priority of the state
Parameters
mixed $stateId
int $priority
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 252 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler\load(), and eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler\loadObjectStates().
    {
        $objectState = $this->load( $stateId );
        $groupStates = $this->loadObjectStates( $objectState->groupId );
        $priorityList = array();
        foreach ( $groupStates as $index => $groupState )
        {
            $priorityList[$groupState->id] = $index;
        }
        $priorityList[$objectState->id] = (int)$priority;
        asort( $priorityList );
        foreach ( array_keys( $priorityList ) as $objectStatePriority => $objectStateId )
        {
            $this->objectStateGateway->updateObjectStatePriority( $objectStateId, $objectStatePriority );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::update ($stateId, InputStruct $input)
Updates an object state
Parameters
mixed $stateId
\eZ\Publish\SPI\Persistence\Content\ObjectState\InputStruct $input
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 236 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler\load().
    {
        $objectState = $this->objectStateMapper->createObjectStateFromInputStruct( $input );
        $objectState->id = (int)$stateId;
        $this->objectStateGateway->updateObjectState( $objectState );
        return $this->load( $objectState->id );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::updateGroup ($groupId, InputStruct $input)
Updates an object state group
Parameters
mixed $groupId
\eZ\Publish\SPI\Persistence\Content\ObjectState\InputStruct $input
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 139 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler\loadGroup().
    {
        $objectStateGroup = $this->objectStateMapper->createObjectStateGroupFromInputStruct( $input );
        $objectStateGroup->id = (int)$groupId;
        $this->objectStateGateway->updateObjectStateGroup( $objectStateGroup );
        return $this->loadGroup( $objectStateGroup->id );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::$objectStateGateway protected
Definition at line 26 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Handler::$objectStateMapper protected
Definition at line 33 of file Handler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/ObjectState/Handler.php