ezp-next: eZ\Publish\Core\Repository\TrashService Class Reference
eZ\Publish\Core\Repository\TrashService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, Handler $handler, array $settings=array())
loadTrashItem ($trashItemId)
trash (Location $location)
recover (APITrashItem $trashItem, Location $newParentLocation=null)
emptyTrash ()
deleteTrashItem (APITrashItem $trashItem)
findTrashItems (Query $query)
Public Member Functions inherited from eZ\Publish\API\Repository\TrashService
recover (TrashItem $trashItem, Location $newParentLocation=null)
deleteTrashItem (TrashItem $trashItem)
Protected Member Functions
buildDomainTrashItemObject (Trashed $spiTrashItem)
getDateTime ($timestamp)
Protected Attributes
$repository
$persistenceHandler
$settings
Detailed Description
Definition at line 33 of file TrashService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\TrashService::__construct (RepositoryInterface $repository, Handler $handler, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\API\Repository\Repository $repository
\eZ\Publish\SPI\Persistence\Handler $handler
array $settings
Definition at line 57 of file TrashService.php.
References eZ\Publish\Core\Repository\TrashService\$repository, and eZ\Publish\Core\Repository\TrashService\$settings.
    {
        $this->repository = $repository;
        $this->persistenceHandler = $handler;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            //'defaultSetting' => array(),
        );
    }
Member Function Documentation
eZ\Publish\Core\Repository\TrashService::buildDomainTrashItemObject (Trashed $spiTrashItem) protected
Builds the domain TrashItem object from provided persistence trash item
Parameters
\eZ\Publish\SPI\Persistence\Content\Location\Trashed $spiTrashItem
Returns
Definition at line 310 of file TrashService.php.
    {
        return new TrashItem(
            array(
                'contentInfo' => $this->repository->getContentService()->loadContentInfo( $spiTrashItem->contentId ),
                'id' => (int)$spiTrashItem->id,
                'priority' => (int)$spiTrashItem->priority,
                'hidden' => (bool)$spiTrashItem->hidden,
                'invisible' => (bool)$spiTrashItem->invisible,
                'remoteId' => $spiTrashItem->remoteId,
                'parentLocationId' => (int)$spiTrashItem->parentId,
                'pathString' => $spiTrashItem->pathString,
                'depth' => (int)$spiTrashItem->depth,
                'sortField' => (int)$spiTrashItem->sortField,
                'sortOrder' => (int)$spiTrashItem->sortOrder,
            )
        );
    }
eZ\Publish\Core\Repository\TrashService::deleteTrashItem (APITrashItem $trashItem)
Deletes a trash item.
The corresponding content object will be removed
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to delete this trash item
Parameters
\eZ\Publish\API\Repository\Values\Content\TrashItem $trashItem
Definition at line 229 of file TrashService.php.
    {
        if ( $this->repository->hasAccess( 'content', 'cleantrash' ) !== true )
            throw new UnauthorizedException( 'content', 'cleantrash' );
        if ( !is_numeric( $trashItem->id ) )
            throw new InvalidArgumentValue( "id", $trashItem->id, "TrashItem" );
        $this->repository->beginTransaction();
        try
        {
            $this->persistenceHandler->trashHandler()->deleteTrashItem( $trashItem->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\TrashService::emptyTrash ()
Empties trash.
All locations contained in the trash will be removed. Content objects will be removed if all locations of the content are gone.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to empty the trash
Implements eZ\Publish\API\Repository\TrashService.
Definition at line 201 of file TrashService.php.
    {
        if ( $this->repository->hasAccess( 'content', 'cleantrash' ) !== true )
            throw new UnauthorizedException( 'content', 'cleantrash' );
        $this->repository->beginTransaction();
        try
        {
            // Persistence layer takes care of deleting content objects
            $this->persistenceHandler->trashHandler()->emptyTrash();
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\TrashService::findTrashItems (Query $query)
Returns a collection of Trashed locations contained in the trash.
$query allows to filter/sort the elements to be contained in the collection.
Parameters
\eZ\Publish\API\Repository\Values\Content\Query $query
Returns
Implements eZ\Publish\API\Repository\TrashService.
Definition at line 259 of file TrashService.php.
References eZ\Publish\Core\Repository\TrashService\buildDomainTrashItemObject().
    {
        if ( $query->criterion !== null && !$query->criterion instanceof Criterion )
            throw new InvalidArgumentValue( "query->criterion", $query->criterion, "Query" );
        if ( $query->sortClauses !== null )
        {
            if ( !is_array( $query->sortClauses ) )
                throw new InvalidArgumentValue( "query->sortClauses", $query->sortClauses, "Query" );
            foreach ( $query->sortClauses as $sortClause )
            {
                if ( !$sortClause instanceof SortClause )
                    throw new InvalidArgumentValue( "query->sortClauses", "only instances of SortClause class are allowed" );
            }
        }
        if ( $query->offset !== null && !is_numeric( $query->offset ) )
            throw new InvalidArgumentValue( "query->offset", $query->offset, "Query" );
        if ( $query->limit !== null && !is_numeric( $query->limit ) )
            throw new InvalidArgumentValue( "query->limit", $query->limit, "Query" );
        $spiTrashItems = $this->persistenceHandler->trashHandler()->findTrashItems(
            $query->criterion !== null ? $query->criterion : null,
            $query->offset !== null && $query->offset > 0 ? (int)$query->offset : 0,
            $query->limit !== null && $query->limit >= 1 ? (int)$query->limit : null,
            $query->sortClauses !== null ? $query->sortClauses : null
        );
        $trashItems = array();
        foreach ( $spiTrashItems as $spiTrashItem )
        {
            $trashItems[] = $this->buildDomainTrashItemObject( $spiTrashItem );
        }
        $searchResult = new SearchResult();
        $searchResult->count = count( $trashItems );
        $searchResult->items = $trashItems;
        $searchResult->query = $query;
        return $searchResult;
    }
eZ\Publish\Core\Repository\TrashService::getDateTime ($timestamp) protected
Parameters
int $timestamp
Returns
Definition at line 334 of file TrashService.php.
    {
        $dateTime = new DateTime();
        $dateTime->setTimestamp( $timestamp );
        return $dateTime;
    }
eZ\Publish\Core\Repository\TrashService::loadTrashItem ($trashItemId)
Loads a trashed location object from its $id.
Note that $id is identical to original location, which has been previously trashed
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to read the trashed location
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the location with the given id does not exist
Parameters
int $trashItemId
Returns
Implements eZ\Publish\API\Repository\TrashService.
Definition at line 79 of file TrashService.php.
References eZ\Publish\Core\Repository\TrashService\buildDomainTrashItemObject().
    {
        if ( !is_numeric( $trashItemId ) )
            throw new InvalidArgumentValue( "trashItemId", $trashItemId );
        if ( $this->repository->hasAccess( 'content', 'restore' ) !== true )
            throw new UnauthorizedException( 'content', 'restore' );
        $spiTrashItem = $this->persistenceHandler->trashHandler()->loadTrashItem( $trashItemId );
        $trash = $this->buildDomainTrashItemObject( $spiTrashItem );
        if ( !$this->repository->canUser( 'content', 'read', $trash->getContentInfo() ) )
            throw new UnauthorizedException( 'content', 'read' );
        return $trash;
    }
eZ\Publish\Core\Repository\TrashService::recover (APITrashItem $trashItem, Location $newParentLocation = null)
Recovers the $trashedLocation at its original place if possible.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to recover the trash item at the parent location location
If $newParentLocation is provided, $trashedLocation will be restored under it.
Parameters
\eZ\Publish\API\Repository\Values\Content\TrashItem $trashItem
\eZ\Publish\API\Repository\Values\Content\Location $newParentLocation
Returns
the newly created or recovered location
Definition at line 144 of file TrashService.php.
    {
        if ( !is_numeric( $trashItem->id ) )
            throw new InvalidArgumentValue( "id", $trashItem->id, "TrashItem" );
        if ( $newParentLocation === null && !is_numeric( $trashItem->parentLocationId ) )
            throw new InvalidArgumentValue( "parentLocationId", $trashItem->parentLocationId, "TrashItem" );
        if ( $newParentLocation !== null && !is_numeric( $newParentLocation->id ) )
            throw new InvalidArgumentValue( "parentLocationId", $newParentLocation->id, "Location" );
        if ( $this->repository->hasAccess( 'content', 'restore' ) !== true )
            throw new UnauthorizedException( 'content', 'restore' );
        $this->repository->beginTransaction();
        try
        {
            $newParentLocationId = $newParentLocation ? $newParentLocation->id : $trashItem->parentLocationId;
            $newLocationId = $this->persistenceHandler->trashHandler()->recover(
                $trashItem->id,
                $newParentLocationId
            );
            $content = $this->repository->getContentService()->loadContent( $trashItem->contentId );
            $urlAliasNames = $this->repository->getNameSchemaService()->resolveUrlAliasSchema( $content );
            // Publish URL aliases for recovered location
            foreach ( $urlAliasNames as $languageCode => $name )
            {
                $this->persistenceHandler->urlAliasHandler()->publishUrlAliasForLocation(
                    $newLocationId,
                    $newParentLocationId,
                    $name,
                    $languageCode,
                    $content->contentInfo->alwaysAvailable
                );
            }
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->repository->getLocationService()->loadLocation( $newLocationId );
    }
eZ\Publish\Core\Repository\TrashService::trash (Location $location)
Sends $location and all its children to trash and returns the corresponding trash item.
Content is left untouched.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to trash the given location
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location
Returns
null| null if location was deleted, otherwise TrashItem
Implements eZ\Publish\API\Repository\TrashService.
Definition at line 106 of file TrashService.php.
References eZ\Publish\Core\Repository\TrashService\buildDomainTrashItemObject(), and eZ\Publish\API\Repository\Values\Content\Location\getContentInfo().
    {
        if ( !is_numeric( $location->id ) )
            throw new InvalidArgumentValue( "id", $location->id, "Location" );
        if ( $this->repository->canUser( 'content', 'manage_locations', $location->getContentInfo(), $location ) !== true )
            throw new UnauthorizedException( 'content', 'manage_locations' );
        $this->repository->beginTransaction();
        try
        {
            $spiTrashItem = $this->persistenceHandler->trashHandler()->trashSubtree( $location->id );
            $this->persistenceHandler->urlAliasHandler()->locationDeleted( $location->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return isset( $spiTrashItem )
            ? $this->buildDomainTrashItemObject( $spiTrashItem )
            : null;
    }
Member Data Documentation
eZ\Publish\Core\Repository\TrashService::$persistenceHandler protected
Definition at line 43 of file TrashService.php.
eZ\Publish\Core\Repository\TrashService::$repository protected
Definition at line 38 of file TrashService.php.
eZ\Publish\Core\Repository\TrashService::$settings protected
Definition at line 48 of file TrashService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/TrashService.php