ezp-next: eZ\Publish\Core\Repository\NameSchemaService Class Reference
eZ\Publish\Core\Repository\NameSchemaService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, array $settings=array())
resolveUrlAliasSchema (Content $content)
resolveNameSchema (Content $content, array $fieldMap=array(), array $languageCodes=array())
resolve ($nameSchema, ContentType $contentType, array $fieldMap, array $languageCodes)
Public Attributes
const META_STRING = 'EZMETAGROUP_'
Protected Member Functions
mergeFieldMap (Content $content, array $fieldMap, array $languageCodes)
getFieldTitles (array $schemaIdentifiers, ContentType $contentType, array $fieldMap, $languageCode)
extractTokens ($nameSchema)
resolveToken ($token, $titles, $groupLookupTable)
isTokenGroup ($identifier)
tokenParts ($token)
filterNameSchema ($nameSchema)
getIdentifiers ($schemaString)
Protected Attributes
$repository
$settings
Detailed Description
NameSchemaService is internal service for resolving content name and url alias patterns. This code supports content name pattern groups.
Syntax: <attribute_identifier> <attribute_identifier> <2nd-identifier> User text <attribute_identifier>|(<2nd-identifier><3rd-identifier>)
Example: <nickname|(<firstname> <lastname>)>
Tokens are looked up from left to right. If a match is found for the leftmost token, the 2nd token will not be used. Tokens are representations of fields. So a match means that that the current field has data.
Tokens are the field definition identifiers which are used in the class edit-interface.
Definition at line 40 of file NameSchemaService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\NameSchemaService::__construct (RepositoryInterface $repository, array $settings = array())
Constructs a object to resolve $nameSchema with $contentVersion fields values
Parameters
\eZ\Publish\API\Repository\Repository $repository
array $settings
Returns
Definition at line 67 of file NameSchemaService.php.
References eZ\Publish\Core\Repository\NameSchemaService\$repository, and eZ\Publish\Core\Repository\NameSchemaService\$settings.
    {
        $this->repository = $repository;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            'limit' => 150,
            'sequence' => '...',
        );
    }
Member Function Documentation
eZ\Publish\Core\Repository\NameSchemaService::extractTokens ($nameSchema) protected
Extract all tokens from $namePattern
Example: Text <token> more text ==> <token>
Parameters
string $nameSchema
Returns
array
Definition at line 240 of file NameSchemaService.php.
    {
        preg_match_all(
            "|<([^>]+)>|U",
            $nameSchema,
            $tokenArray
        );
        return $tokenArray[0];
    }
eZ\Publish\Core\Repository\NameSchemaService::filterNameSchema ($nameSchema) protected
Builds a lookup / translation table for groups in the $namePattern. The groups are referenced with a generated meta-token in the original name pattern.
Returns intermediate name pattern where groups are replaced with meta- tokens.
Parameters
string $nameSchema
Returns
string
Definition at line 356 of file NameSchemaService.php.
    {
        $retNamePattern = "";
        $foundGroups = preg_match_all( "/[<|\\|](\\(.+\\))[\\||>]/U", $nameSchema, $groupArray );
        $groupLookupTable = array();
        if ( $foundGroups )
        {
            $i = 0;
            foreach ( $groupArray[1] as $group )
            {
                // Create meta-token for group
                $metaToken = self::META_STRING . $i;
                // Insert the group with its placeholder token
                $retNamePattern = str_replace( $group, $metaToken, $nameSchema );
                // Remove the pattern "(" ")" from the tokens
                $group = str_replace( array( '(', ')' ), '', $group );
                $groupLookupTable[$metaToken] = $group;
                ++$i;
            }
            $nameSchema = $retNamePattern;
        }
        return array( $nameSchema, $groupLookupTable );
    }
eZ\Publish\Core\Repository\NameSchemaService::getFieldTitles (array $schemaIdentifiers, ContentType $contentType, array $fieldMap, $languageCode) protected
Fetches the list of available Field identifiers in the token and returns an array of their current title value.
See Also
::getName()
Parameters
string[] $schemaIdentifiers
\eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType $fieldDefinitions
array $fieldMap
string $languageCode
Returns
string[] Key is the field identifier, value is the title value
Definition at line 207 of file NameSchemaService.php.
References eZ\Publish\API\Repository\Values\ContentType\ContentType\getFieldDefinition().
    {
        $fieldTitles = array();
        foreach ( $schemaIdentifiers as $fieldDefinitionIdentifier )
        {
            if ( isset( $fieldMap[$fieldDefinitionIdentifier][$languageCode] ) )
            {
                $fieldDefinition = $contentType->getFieldDefinition( $fieldDefinitionIdentifier );
                $fieldType = $this->repository->getFieldTypeService()->getFieldType(
                    $fieldDefinition->fieldTypeIdentifier
                );
                $fieldTitles[$fieldDefinitionIdentifier] = $fieldType->getName(
                    $fieldMap[$fieldDefinitionIdentifier][$languageCode]
                );
            }
        }
        return $fieldTitles;
    }
eZ\Publish\Core\Repository\NameSchemaService::getIdentifiers ($schemaString) protected
Returns all identifiers from all tokens in the name schema.
Parameters
string $schemaString
Returns
array
Definition at line 392 of file NameSchemaService.php.
    {
        $allTokens = '#<(.*)>#U';
        $identifiers = '#\\W#';
        $tmpArray = array();
        preg_match_all( $allTokens, $schemaString, $matches );
        foreach ( $matches[1] as $match )
        {
            $tmpArray[] = preg_split( $identifiers, $match, -1, PREG_SPLIT_NO_EMPTY );
        }
        $retArray = array();
        foreach ( $tmpArray as $matchGroup )
        {
            if ( is_array( $matchGroup ) )
            {
                foreach ( $matchGroup as $item )
                {
                    $retArray[] = $item;
                }
            }
            else
            {
                $retArray[] = $matchGroup;
            }
        }
        return $retArray;
    }
eZ\Publish\Core\Repository\NameSchemaService::isTokenGroup ($identifier) protected
Checks whether $identifier is a placeholder for a token group.
Parameters
string $identifier
Returns
boolean
Definition at line 315 of file NameSchemaService.php.
    {
        if ( strpos( $identifier, self::META_STRING ) === false )
        {
            return false;
        }
        return true;
    }
eZ\Publish\Core\Repository\NameSchemaService::mergeFieldMap (Content $content, array $fieldMap, array $languageCodes) protected
Convenience method for resolving name schema
Parameters
\eZ\Publish\API\Repository\Values\Content\Content $content
array $fieldMap
array $languageCodes
Returns
array
Definition at line 129 of file NameSchemaService.php.
    {
        if ( empty( $fieldMap ) )
        {
            return $content->fields;
        }
        $mergedFieldMap = array();
        foreach ( $content->fields as $fieldIdentifier => $fieldLanguageMap )
        {
            foreach ( $languageCodes as $languageCode )
            {
                $mergedFieldMap[$fieldIdentifier][$languageCode] = isset( $fieldMap[$fieldIdentifier][$languageCode] )
                    ? $fieldMap[$fieldIdentifier][$languageCode]
                    : $fieldLanguageMap[$languageCode];
            }
        }
        return $mergedFieldMap;
    }
eZ\Publish\Core\Repository\NameSchemaService::resolve ($nameSchema, ContentType $contentType, array $fieldMap, array $languageCodes)
Returns the real name for a content name pattern
Parameters
string $nameSchema
\eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType
array $fieldMap
array $languageCodes
Returns
string
Definition at line 161 of file NameSchemaService.php.
References eZ\Publish\Core\Repository\NameSchemaService\extractTokens(), eZ\Publish\Core\Repository\NameSchemaService\filterNameSchema(), eZ\Publish\Core\Repository\NameSchemaService\getFieldTitles(), eZ\Publish\Core\Repository\NameSchemaService\getIdentifiers(), and eZ\Publish\Core\Repository\NameSchemaService\resolveToken().
    {
        list( $filteredNameSchema, $groupLookupTable ) = $this->filterNameSchema( $nameSchema );
        $tokens = $this->extractTokens( $filteredNameSchema );
        $schemaIdentifiers = $this->getIdentifiers( $nameSchema );
        $names = array();
        foreach ( $languageCodes as $languageCode )
        {
            // Fetch titles for language code
            $titles = $this->getFieldTitles( $schemaIdentifiers, $contentType, $fieldMap, $languageCode );
            $name = $filteredNameSchema;
            // Replace tokens with real values
            foreach ( $tokens as $token )
            {
                $string = $this->resolveToken( $token, $titles, $groupLookupTable );
                $name = str_replace( $token, $string, $name );
            }
            // Make sure length is not longer then $limit unless it's 0
            if ( $this->settings["limit"] && strlen( $name ) > $this->settings["limit"] )
            {
                $name = rtrim( substr( $name, 0, $this->settings["limit"] - strlen( $this->settings["sequence"] ) ) ) . $this->settings["sequence"];
            }
            $names[$languageCode] = $name;
        }
        return $names;
    }
eZ\Publish\Core\Repository\NameSchemaService::resolveNameSchema (Content $content, array $fieldMap = array(), array $languageCodes = array())
Convenience method for resolving name schema
Parameters
\eZ\Publish\API\Repository\Values\Content\Content $content
array $fieldMap
array $languageCodes
Returns
array
Definition at line 105 of file NameSchemaService.php.
References eZ\Publish\Core\Repository\NameSchemaService\resolve().
    {
        $languageCodes = $languageCodes ?: $content->versionInfo->languageCodes;
        return $this->resolve(
            $content->contentType->nameSchema,
            $content->contentType,
            $this->mergeFieldMap(
                $content,
                $fieldMap,
                $languageCodes
            ),
            $languageCodes
        );
    }
eZ\Publish\Core\Repository\NameSchemaService::resolveToken ($token, $titles, $groupLookupTable) protected
Looks up the value $token should be replaced with and returns this as a string. Meta strings denoting token groups are automatically inferred.
Parameters
string $token
array $titles
array $groupLookupTable
Returns
string
Definition at line 263 of file NameSchemaService.php.
References eZ\Publish\Core\Repository\NameSchemaService\extractTokens(), eZ\Publish\Core\Repository\NameSchemaService\isTokenGroup(), and eZ\Publish\Core\Repository\NameSchemaService\tokenParts().
    {
        $replaceString = "";
        $tokenParts = $this->tokenParts( $token );
        foreach ( $tokenParts as $tokenPart )
        {
            if ( $this->isTokenGroup( $tokenPart ) )
            {
                $replaceString = $groupLookupTable[$tokenPart];
                $groupTokenArray = $this->extractTokens( $replaceString );
                foreach ( $groupTokenArray as $groupToken )
                {
                    $replaceString = str_replace(
                        $groupToken,
                        $this->resolveToken(
                            $groupToken,
                            $titles,
                            $groupLookupTable
                        ),
                        $replaceString
                    );
                }
                // We want to stop after the first matching token part / identifier is found
                // <id1|id2> if id1 has a value, id2 will not be used.
                // In this case id1 or id1 is a token group.
                break;
            }
            else
            {
                if ( array_key_exists( $tokenPart, $titles ) && $titles[$tokenPart] !== '' && $titles[$tokenPart] !== null )
                {
                    $replaceString = $titles[$tokenPart];
                    // We want to stop after the first matching token part / identifier is found
                    // <id1|id2> if id1 has a value, id2 will not be used.
                    break;
                }
            }
        }
        return $replaceString;
    }
eZ\Publish\Core\Repository\NameSchemaService::resolveUrlAliasSchema (Content $content)
Convenience method for resolving URL alias schema
Parameters
\eZ\Publish\API\Repository\Values\Content\Content $content
Returns
array
Definition at line 84 of file NameSchemaService.php.
References eZ\Publish\Core\Repository\NameSchemaService\resolve().
    {
        return $this->resolve(
            strlen( $content->contentType->urlAliasSchema ) === 0 ?
                $content->contentType->nameSchema :
                $content->contentType->urlAliasSchema,
            $content->contentType,
            $content->fields,
            $content->versionInfo->languageCodes
        );
    }
eZ\Publish\Core\Repository\NameSchemaService::tokenParts ($token) protected
Returns the different constituents of $token in an array. The normal case here is that the different identifiers within one token will be tokenized and returned.
Example: "&lt;title|text&gt;" ==> array('title', 'text')
Parameters
string $token
Returns
array
Definition at line 339 of file NameSchemaService.php.
    {
        return preg_split( '#\\W#', $token, -1, PREG_SPLIT_NO_EMPTY );
    }
Member Data Documentation
eZ\Publish\Core\Repository\NameSchemaService::$repository protected
Definition at line 52 of file NameSchemaService.php.
eZ\Publish\Core\Repository\NameSchemaService::$settings protected
Definition at line 57 of file NameSchemaService.php.
const eZ\Publish\Core\Repository\NameSchemaService::META_STRING = 'EZMETAGROUP_'
Definition at line 47 of file NameSchemaService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/NameSchemaService.php