ezp-next: eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension Class Reference
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension Class Reference
Public Member Functions
__construct (ContainerInterface $container, ConfigResolverInterface $resolver)
initRuntime (Twig_Environment $environment)
getFunctions ()
getFilters ()
getName ()
renderField (Content $content, $fieldIdentifier, array $params=array())
xmltextToHtml5 ($xmlData)
getImageVariation (Field $field, VersionInfo $versionInfo, $variationName)
Protected Member Functions
getRenderFieldBlockParameters (Content $content, Field $field, array $params=array())
getXmlTextConverter ()
searchBlock ($blockName, Twig_Template $tpl)
getBlocksByField (Content $content, Field $field, $localTemplate=null)
getFieldBlockName (Content $content, Field $field)
getFieldTypeIdentifier (Content $content, Field $field)
Protected Attributes
$resources
$template
$environment
$blocks
$xmlTextConverter
$fieldTypeIdentifiers = array()
$imageVariationService
$container
Detailed Description
Twig content extension for eZ Publish specific usage. Exposes helpers to play with public API objects.
Definition at line 30 of file ContentExtension.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::__construct (ContainerInterface $container, ConfigResolverInterface $resolver)
Definition at line 86 of file ContentExtension.php.
References eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\$container, and eZ\Publish\Core\MVC\ConfigResolverInterface\getParameter().
    {
        $this->resources = $resolver->getParameter( 'field_templates' );
        usort(
            $this->resources,
            function ( $a, $b )
            {
                return $b['priority'] - $a['priority'];
            }
        );
        $this->blocks = new SplObjectStorage();
        $this->container = $container;
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::getBlocksByField (Content $content, Field $field, $localTemplate = null) protected
Returns template blocks for $field. First check in the $localTemplate if it's provided. Template block convention name is <fieldTypeIdentifier>_field Example: 'ezstring_field' will be relevant for a full view of ezstring field type
Parameters
Content $content
Field $field
null | string $localTemplate a file where to look for the block first
Exceptions
\LogicException If no template block can be found for $field
Returns
array
Definition at line 328 of file ContentExtension.php.
References eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\$blocks, eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\$template, eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\getFieldBlockName(), and eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\searchBlock().
    {
        $fieldBlockName = $this->getFieldBlockName( $content, $field );
        if ( $localTemplate !== null )
        {
            $tpl = $this->environment->loadTemplate( $localTemplate );
            $block = $this->searchBlock( $fieldBlockName, $tpl );
            if ( $block !== null )
            {
                return array( $fieldBlockName => $block );
            }
        }
        if ( $this->blocks->contains( $field ) )
            return $this->blocks[$field];
        // Looping against available resources to find template blocks for $field
        $blocks = array();
        foreach ( $this->resources as &$template )
        {
            if ( !$template instanceof Twig_Template )
                $template = $this->environment->loadTemplate( $template['template'] );
            $tpl = $template;
            $block = $this->searchBlock( $fieldBlockName, $tpl );
            if ( $block !== null )
            {
                $blocks[$fieldBlockName] = $block;
                break;
            }
        }
        if ( empty( $blocks ) )
            throw new LogicException( "Cannot find '$fieldBlockName' template block field type." );
        $this->blocks->attach( $field, $blocks );
        return $blocks;
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::getFieldBlockName (Content $content, Field $field) protected
Returns expected block name for $field, attached in $content.
Parameters
\eZ\Publish\Core\Repository\Values\Content\Content $content
\eZ\Publish\API\Repository\Values\Content\Field $field
Returns
string
Definition at line 377 of file ContentExtension.php.
References eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\getFieldTypeIdentifier().
    {
        return $this->getFieldTypeIdentifier( $content, $field ) . '_field';
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::getFieldTypeIdentifier (Content $content, Field $field) protected
Returns the field type identifier for $field
Parameters
\eZ\Publish\Core\Repository\Values\Content\Content $content
\eZ\Publish\API\Repository\Values\Content\Field $field
Returns
string
Definition at line 390 of file ContentExtension.php.
References eZ\Publish\Core\Repository\Values\Content\Content\getVersionInfo().
    {
        if ( !isset( $this->fieldTypeIdentifiers[$field->fieldDefIdentifier] ) )
        {
            $this->fieldTypeIdentifiers[$field->fieldDefIdentifier] = $content
                ->getVersionInfo()
                ->getContentInfo()
                ->getContentType()
                ->getFieldDefinition( $field->fieldDefIdentifier )
                ->fieldTypeIdentifier;
        }
        return $this->fieldTypeIdentifiers[$field->fieldDefIdentifier];
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::getFilters ()
Returns a list of filters to add to the existing list
Returns
array
Definition at line 133 of file ContentExtension.php.
    {
        return array(
            'xmltext_to_html5' => new Twig_Filter_Method( $this, 'xmltextToHtml5' ),
        );
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::getFunctions ()
Returns a list of functions to add to the existing list.
Returns
array
Definition at line 116 of file ContentExtension.php.
    {
        return array(
            'ez_render_field' => new Twig_Function_Method(
                $this,
                'renderField',
                array( 'is_safe' => array( 'html' ) )
            ),
            'ez_image_alias' => new Twig_Function_Method( $this, 'getImageVariation' )
        );
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::getImageVariation (Field $field, VersionInfo $versionInfo, $variationName)
Returns the image variant object for $field/$versionInfo
Parameters
\eZ\Publish\API\Repository\Values\Content\Field $field
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
string $variationName
Returns
Definition at line 278 of file ContentExtension.php.
    {
        if ( !isset( $this->imageVariationService ) )
            $this->imageVariationService = $this->container->get( 'ezpublish.fieldType.ezimage.variation_service' );
        return $this->imageVariationService->getVariation( $field, $versionInfo, $variationName );
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::getName ()
Returns the name of the extension.
Returns
string The extension name
Definition at line 145 of file ContentExtension.php.
    {
        return 'ezpublish.content';
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::getRenderFieldBlockParameters (Content $content, Field $field, array $params = array()) protected
Generates the array of parameter to pass to the field template.
Parameters
\eZ\Publish\Core\Repository\Values\Content\Content $content
\eZ\Publish\Core\Repository\Values\Content\Field $field the Field to display
array $params An array of parameters to pass to the field view
Returns
array
Definition at line 159 of file ContentExtension.php.
References eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\getFieldTypeIdentifier(), and eZ\Publish\Core\Repository\Values\Content\Content\getVersionInfo().
    {
        // Merging passed parameters to default ones
        $params += array(
            'parameters' => array(), // parameters dedicated to template processing
            'attr' => array() // attributes to add on the enclosing HTML tags
        );
        $versionInfo = $content->getVersionInfo();
        $contentInfo = $versionInfo->getContentInfo();
        $contentType = $contentInfo->getContentType();
        // Adding Field, FieldSettings and ContentInfo objects to
        // parameters to be passed to the template
        $params += array(
            'field' => $field,
            'contentInfo' => $contentInfo,
            'versionInfo' => $versionInfo,
            'fieldSettings' => $contentType
                ->getFieldDefinition( $field->fieldDefIdentifier )
                ->getFieldSettings()
        );
        // make sure we can easily add class="<fieldtypeidentifier>-field" to the
        // generated HTML
        if ( isset( $params['attr']['class'] ) )
        {
            $params['attr']['class'] .= ' ' . $this->getFieldTypeIdentifier( $content, $field ) . '-field';
        }
        else
        {
            $params['attr']['class'] = $this->getFieldTypeIdentifier( $content, $field ) . '-field';
        }
        return $params;
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::getXmlTextConverter () protected
Returns
Definition at line 249 of file ContentExtension.php.
References eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\$xmlTextConverter.
    {
        if ( !isset( $this->xmlTextConverter ) )
            $this->xmlTextConverter = $this->container->get( "ezpublish.fieldType.ezxmltext.converter.html5" );
        return $this->xmlTextConverter;
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::initRuntime (Twig_Environment $environment)
Initializes the template runtime (aka Twig environment).
Parameters
\Twig_Environment $environment
Definition at line 106 of file ContentExtension.php.
References eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\$environment.
    {
        $this->environment = $environment;
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::renderField (Content $content, $fieldIdentifier, array $params = array())
Renders the HTML for a given field.
Parameters
\eZ\Publish\Core\Repository\Values\Content\Content $content
string $fieldIdentifier Identifier for the field we want to render
array $params An array of parameters to pass to the field view
Exceptions
\InvalidArgumentException If $fieldIdentifier is invalid in $content
Returns
string The HTML markup
Definition at line 205 of file ContentExtension.php.
References eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\getBlocksByField(), eZ\Publish\Core\Repository\Values\Content\Content\getField(), eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\getFieldBlockName(), and eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\getRenderFieldBlockParameters().
    {
        $lang = null;
        if ( isset( $params['lang'] ) )
        {
            $lang = $params['lang'];
            unset( $params['lang'] );
        }
        $field = $content->getField( $fieldIdentifier, $lang );
        if ( !$field instanceof Field )
        {
            throw new InvalidArgumentException(
                "Invalid field identifier '$fieldIdentifier' for content #{$content->contentInfo->id}"
            );
        }
        $localTemplate = null;
        if ( isset( $params['template'] ) )
        {
            // local override of the template
            // this template is put on the top the templates stack
            $localTemplate = $params['template'];
            unset( $params['template'] );
        }
        $params = $this->getRenderFieldBlockParameters( $content, $field, $params );
        // Getting instance of Twig_Template that will be used to render blocks
        if ( !$this->template instanceof Twig_Template )
        {
            $tpl = reset( $this->resources );
            $this->template = $this->environment->loadTemplate( $tpl['template'] );
        }
        return $this->template->renderBlock(
            $this->getFieldBlockName( $content, $field ),
            $params,
            $this->getBlocksByField( $content, $field, $localTemplate )
        );
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::searchBlock ($blockName, Twig_Template $tpl) protected
Returns the block named $blockName in the given template. If it's not found, returns null.
Parameters
string $blockName
\Twig_Template $tpl
Returns
array|null
Definition at line 295 of file ContentExtension.php.
    {
        // Current template might have parents, so we need to loop against
        // them to find a matching block
        do
        {
            foreach ( $tpl->getBlocks() as $name => $block )
            {
                if ( $name === $blockName )
                {
                    return $block;
                }
            }
        }
        while ( ( $tpl = $tpl->getParent( array() ) ) instanceof Twig_Template );
        return null;
    }
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::xmltextToHtml5 ($xmlData)
Implements the "xmltext_to_html5" filter
Parameters
string $xmlData
Returns
string
Definition at line 264 of file ContentExtension.php.
References eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension\getXmlTextConverter().
    {
        return $this->getXmlTextConverter()->convert( $xmlData );
    }
Member Data Documentation
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::$blocks protected
Definition at line 60 of file ContentExtension.php.
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::$container protected
Definition at line 84 of file ContentExtension.php.
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::$environment protected
Definition at line 53 of file ContentExtension.php.
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::$fieldTypeIdentifiers = array() protected
Definition at line 74 of file ContentExtension.php.
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::$imageVariationService protected
Definition at line 79 of file ContentExtension.php.
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::$resources protected
Definition at line 39 of file ContentExtension.php.
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::$template protected
Definition at line 46 of file ContentExtension.php.
eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension::$xmlTextConverter protected
Definition at line 67 of file ContentExtension.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/ContentExtension.php