ezp-next: eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\FieldTemplates Class Reference
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\FieldTemplates Class Reference
Public Member Functions
addSemanticConfig (NodeBuilder $nodeBuilder)
registerInternalConfig (array $config, ContainerBuilder $container)
Public Member Functions inherited from eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser
setBaseKey ($key)
Additional Inherited Members
Public Attributes inherited from eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser
const UNIQUE = 1
const MERGE_FROM_SECOND_LEVEL = 2
Protected Member Functions inherited from eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser
getContainerParameter (ContainerBuilder $container, $id, $default=null)
groupsArraySetting (array $groups, $id, array $config, $options=0)
registerGlobalConfigArray ($id, array $config, ContainerBuilder $container)
registerInternalConfigArray ($id, array $config, ContainerBuilder $container, $options=0)
Protected Attributes inherited from eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser
$baseKey = 'system'
Detailed Description
Definition at line 16 of file FieldTemplates.php.
Member Function Documentation
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\FieldTemplates::addSemanticConfig (NodeBuilder $nodeBuilder)
Adds semantic configuration definition.
Parameters
\Symfony\Component\Config\Definition\Builder\NodeBuilder $nodeBuilder Node just under ezpublish.system.<siteaccess>
Returns
void
Implements eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser.
Definition at line 25 of file FieldTemplates.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\FieldTemplates\addSemanticConfig().
    {
        $nodeBuilder
            ->arrayNode( 'field_templates' )
                ->info( 'Template settings for fields rendered by ez_render_field() Twig function' )
                ->prototype( 'array' )
                    ->children()
                        ->scalarNode( 'template' )
                            ->info( 'Template file where to find block definition to display fields' )
                            ->isRequired()
                        ->end()
                        ->scalarNode( 'priority' )
                            ->defaultValue( 0 )
                        ->end()
                    ->end()
                ->end()
            ->end();
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\FieldTemplates::registerInternalConfig (array $config, ContainerBuilder $container)
Translates parsed semantic config values from $config to internal key/value pairs.;
Parameters
array $config
\Symfony\Component\DependencyInjection\ContainerBuilder $container
Returns
void
Implements eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser.
Definition at line 52 of file FieldTemplates.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\FieldTemplates\registerInternalConfig(), and eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser\registerInternalConfigArray().
    {
        foreach ( $config['siteaccess']['groups'] as $group => $saArray )
        {
            if ( isset( $config[$this->baseKey][$group]['field_templates'] ) )
            {
                $container->setParameter(
                    "ezsettings.$group.field_templates",
                    $config[$this->baseKey][$group]['field_templates']
                );
            }
        };
        $this->registerInternalConfigArray(
            'field_templates', $config, $container
        );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/FieldTemplates.php