ezp-next: eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage Class Reference
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage Class Reference
Public Member Functions
setConnection ($dbHandler)
storeFileReference (VersionInfo $versionInfo, Field $field)
removeMimeFromPath ($path)
getFileReferenceData ($fieldId, $versionNo)
prependMimeToPath ($path, $mimeType)
removeFileReferences (array $fieldIds, $versionNo)
removeFileReference ($fieldId, $versionNo)
getReferencedFiles (array $fieldIds, $versionNo)
countFileReferences (array $files)
Protected Member Functions
getStorageTable ()
getPropertyMapping ()
setFetchColumns (\ezcQuerySelect $selectQuery, $fieldId, $versionNo)
setInsertColumns (\ezcQueryInsert $insertQuery, VersionInfo $versionInfo, Field $field)
getConnection ()
toPropertyName ($columnName)
castToPropertyValue ($value, $columnName)
Protected Attributes
$dbHandler
Detailed Description
Definition at line 16 of file LegacyStorage.php.
Member Function Documentation
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::castToPropertyValue ($value, $columnName) protected
Returns $value casted as specified by getPropertyMapping().
Parameters
mixed $value
string $columnName
Returns
mixed
Definition at line 271 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\castToPropertyValue(), and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getPropertyMapping().
    {
        $propertyMap = $this->getPropertyMapping();
        $castFunction = $propertyMap[$columnName]['cast'];
        return $castFunction( $value );
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::countFileReferences (array $files)
Returns a map with the number of references each file from $files has
Parameters
array $files
Returns
array
Reimplemented from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway.
Definition at line 405 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\countFileReferences(), eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\prependMimeToPath().
    {
        $connection = $this->getConnection();
        $selectQuery = $connection->createSelectQuery();
        $selectQuery->select(
            $connection->quoteColumn( 'filename' ),
            $connection->quoteColumn( 'mime_type' ),
            $selectQuery->alias(
                $selectQuery->expr->count( $connection->quoteColumn( 'contentobject_attribute_id' ) ),
                'count'
            )
        )->from(
            $connection->quoteTable( $this->getStorageTable() )
        )->where(
            $selectQuery->expr->in(
                $connection->quoteColumn( 'filename' ),
                array_map(
                    array( $this, 'removeMimeFromPath' ),
                    $files
                )
            )
        )->groupBy( $connection->quoteColumn( 'filename' ) );
        $statement = $selectQuery->prepare();
        $statement->execute();
        $countMap = array();
        foreach ( $statement->fetchAll( \PDO::FETCH_ASSOC ) as $row )
        {
            $path = $this->prependMimeToPath( $row['filename'], $row['mime_type'] );
            $countMap[$path] = (int)$row['count'];
        }
        // Complete counts
        foreach ( $files as $path )
        {
            // This is already the correct path
            if ( !isset( $countMap[$path] ) )
            {
                $countMap[$path] = 0;
            }
        }
        return $countMap;
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::getConnection () protected
Returns the active connection
Exceptions
\RuntimeException if no connection has been set, yet.
Returns
Definition at line 146 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getConnection().
    {
        if ( $this->dbHandler === null )
        {
            throw new \RuntimeException( "Missing database connection." );
        }
        return $this->dbHandler;
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::getFileReferenceData ($fieldId, $versionNo)
Returns the file reference data for the given $fieldId in $versionNo
Parameters
mixed $fieldId
int $versionNo
Returns
array|void
Reimplemented from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway.
Definition at line 202 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\castToPropertyValue(), eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getConnection(), eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getFileReferenceData(), eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getPropertyMapping(), eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\prependMimeToPath(), eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\setFetchColumns(), and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\toPropertyName().
    {
        $connection = $this->getConnection();
        $selectQuery = $connection->createSelectQuery();
        $this->setFetchColumns( $selectQuery, $fieldId, $versionNo );
        $selectQuery->from(
            $connection->quoteTable( $this->getStorageTable() )
        )->where(
            $selectQuery->expr->lAnd(
                $selectQuery->expr->eq(
                    $connection->quoteColumn( 'contentobject_attribute_id' ),
                    $selectQuery->bindValue( $fieldId, null, \PDO::PARAM_INT )
                ),
                $selectQuery->expr->eq(
                    $connection->quoteColumn( 'version' ),
                    $selectQuery->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $selectQuery->prepare();
        $statement->execute();
        $result = $statement->fetchAll( \PDO::FETCH_ASSOC );
        if ( count( $result ) < 1 )
        {
            return null;
        }
        $propertyMap = $this->getPropertyMapping();
        $convertedResult = array();
        foreach ( reset( $result ) as $column => $value )
        {
            $convertedResult[$this->toPropertyName( $column )] = $this->castToPropertyValue( $value, $column );
        }
        $convertedResult['path'] = $this->prependMimeToPath(
            $convertedResult['path'],
            $convertedResult['mimeType']
        );
        return $convertedResult;
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::getPropertyMapping () protected
Returns a column to property mapping for the storage table.
Returns
void
Reimplemented in eZ\Publish\Core\FieldType\BinaryFile\BinaryFileStorage\Gateway\LegacyStorage, and eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage.
Definition at line 37 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getPropertyMapping().
    {
        return array(
            'filename' => array(
                'name' => 'path',
                'cast' => 'strval',
            ),
            'mime_type' => array(
                'name' => 'mimeType',
                'cast' => 'strval',
            ),
            'original_filename' => array(
                'name' => 'fileName',
                'cast' => 'strval',
            )
        );
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::getReferencedFiles (array $fieldIds, $versionNo)
Returns a set o file references, referenced by the given $fieldIds.
Parameters
array $fieldIds
Returns
array
Reimplemented from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway.
Definition at line 362 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getReferencedFiles().
    {
        $connection = $this->getConnection();
        $selectQuery = $connection->createSelectQuery();
        $selectQuery->select(
            $connection->quoteColumn( 'filename' ),
            $connection->quoteColumn( 'mime_type' )
        )->from(
            $connection->quoteTable( $this->getStorageTable() )
        )->where(
            $selectQuery->expr->lAnd(
                $selectQuery->expr->in(
                    $connection->quoteColumn( 'contentobject_attribute_id' ),
                    $fieldIds
                ),
                $selectQuery->expr->eq(
                    $connection->quoteColumn( 'version' ),
                    $selectQuery->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $selectQuery->prepare();
        $statement->execute();
        $gateway = $this;
        return array_map(
            function ( $row ) use ( $gateway )
            {
                return $gateway->prependMimeToPath( $row['filename'], $row['mime_type'] );
            },
            $statement->fetchAll( \PDO::FETCH_ASSOC )
        );
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::getStorageTable () abstract protected
Returns the table name to store data in.
Returns
string
Reimplemented in eZ\Publish\Core\FieldType\BinaryFile\BinaryFileStorage\Gateway\LegacyStorage, and eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage.
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::prependMimeToPath ($path, $mimeType)
Prepends $path with the first part of the given $mimeType.
Parameters
string $path
string $mimeType
Returns
string
Definition at line 288 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\prependMimeToPath().
    {
        $res = substr( $mimeType, 0, strpos( $mimeType, '/' ) ) . '/' . $path;
        return $res;
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::removeFileReference ($fieldId, $versionNo)
Removes a specific file reference for $fieldId and $versionId
Parameters
mixed $fieldId
int $versionNo
Returns
void
Reimplemented from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway.
Definition at line 332 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\removeFileReference().
    {
        $connection = $this->getConnection();
        $deleteQuery = $connection->createDeleteQuery();
        $deleteQuery->deleteFrom(
            $connection->quoteTable( $this->getStorageTable() )
        )->where(
            $deleteQuery->expr->lAnd(
                $deleteQuery->expr->eq(
                    $connection->quoteColumn( 'contentobject_attribute_id' ),
                    $deleteQuery->bindValue( $fieldId, null, \PDO::PARAM_INT )
                ),
                $deleteQuery->expr->eq(
                    $connection->quoteColumn( 'version' ),
                    $deleteQuery->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            )
        );
        $deleteQuery->prepare()->execute();
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::removeFileReferences (array $fieldIds, $versionNo)
Removes all file references for the given $fieldIds
Parameters
array $fieldIds
Returns
void
Reimplemented from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway.
Definition at line 301 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\removeFileReferences().
    {
        $connection = $this->getConnection();
        $deleteQuery = $connection->createDeleteQuery();
        $deleteQuery->deleteFrom(
            $connection->quoteTable( $this->getStorageTable() )
        )->where(
            $deleteQuery->expr->lAnd(
                $deleteQuery->expr->in(
                    $connection->quoteColumn( 'contentobject_attribute_id' ),
                    $fieldIds
                ),
                $deleteQuery->expr->eq(
                    $connection->quoteColumn( 'version' ),
                    $deleteQuery->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            )
        );
        $deleteQuery->prepare()->execute();
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::removeMimeFromPath ($path)
Removes the prepended mime-type directory from $path for legacy storage.
Parameters
string $path
Returns
string
Definition at line 188 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\removeMimeFromPath().
    {
        $res = substr( $path, strpos( $path, '/' ) + 1 );
        return $res;
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::setConnection ($dbHandler)
Set database handler for this gateway
Parameters
mixed $dbHandler
Returns
void
Exceptions
\RuntimeException if $dbHandler is not an instance of eZ\Publish\Core\Persistence\Legacy\EzcDbHandler
Reimplemented from eZ\Publish\Core\FieldType\StorageGateway.
Definition at line 125 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\$dbHandler, and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\setConnection().
    {
        // This obviously violates the Liskov substitution Principle, but with
        // the given class design there is no sane other option. Actually the
        // dbHandler *should* be passed to the constructor, and there should
        // not be the need to post-inject it.
        if ( !$dbHandler instanceof \eZ\Publish\Core\Persistence\Legacy\EzcDbHandler )
        {
            throw new \RuntimeException( "Invalid dbHandler passed" );
        }
        $this->dbHandler = $dbHandler;
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::setFetchColumns (\ezcQuerySelect $selectQuery, $fieldId, $versionNo) protected
Set columns to be fetched from the database
This method is intended to be overwritten by derived classes in order to add additional columns to be fetched from the database. Please do not forget to call the parent when overwriting this method.
Parameters
\ezcQuerySelect $selectQuery
int $fieldId
int $versionNo
Returns
void
Reimplemented in eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage, and eZ\Publish\Core\FieldType\BinaryFile\BinaryFileStorage\Gateway\LegacyStorage.
Definition at line 68 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\setFetchColumns().
    {
        $connection = $this->getConnection();
        $selectQuery->select(
            $connection->quoteColumn( 'filename' ),
            $connection->quoteColumn( 'mime_type' ),
            $connection->quoteColumn( 'original_filename' )
        );
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::setInsertColumns (\ezcQueryInsert $insertQuery, VersionInfo $versionInfo, Field $field) protected
Sets the required insert columns to $selectQuery.
This method is intended to be overwritten by derived classes in order to add additional columns to be set in the database. Please do not forget to call the parent when overwriting this method.
Parameters
\ezcQueryInsert $insertQuery
VersionInfo $versionInfo
Field $field
Returns
void
Reimplemented in eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage, and eZ\Publish\Core\FieldType\BinaryFile\BinaryFileStorage\Gateway\LegacyStorage.
Definition at line 92 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getConnection(), eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\removeMimeFromPath(), and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\setInsertColumns().
    {
        $connection = $this->getConnection();
        $insertQuery->set(
            $connection->quoteColumn( 'contentobject_attribute_id' ),
            $insertQuery->bindValue( $field->id, null, \PDO::PARAM_INT )
        )->set(
            $connection->quoteColumn( 'filename' ),
            $insertQuery->bindValue(
                $this->removeMimeFromPath( $field->value->externalData['path'] )
            )
        )->set(
            $connection->quoteColumn( 'mime_type' ),
            $insertQuery->bindValue( $field->value->externalData['mimeType'] )
        )->set(
            $connection->quoteColumn( 'original_filename' ),
            $insertQuery->bindValue( $field->value->externalData['fileName'] )
        )->set(
            $connection->quoteColumn( 'version' ),
            $insertQuery->bindValue( $versionInfo->versionNo, null, \PDO::PARAM_INT )
        );
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::storeFileReference (VersionInfo $versionInfo, Field $field)
Stores the file reference in $field for $versionNo
Parameters
VersionInfo $versionInfo
Field $field
Returns
void
Reimplemented from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway.
Definition at line 163 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getConnection(), eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\setInsertColumns(), and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\storeFileReference().
    {
        $connection = $this->getConnection();
        $insertQuery = $connection->createInsertQuery();
        $insertQuery->insertInto(
            $connection->quoteTable( $this->getStorageTable() )
        );
        $this->setInsertColumns( $insertQuery, $versionInfo, $field );
        $insertQuery->prepare()->execute();
        return false;
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::toPropertyName ($columnName) protected
Returns the property name for the given $columnName
Parameters
string $columnName
Returns
string
Definition at line 257 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getPropertyMapping(), and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\toPropertyName().
    {
        $propertyMap = $this->getPropertyMapping();
        return ( $propertyMap[$columnName]['name'] );
    }
Member Data Documentation
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage::$dbHandler protected
Definition at line 23 of file LegacyStorage.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage/Gateway/LegacyStorage.php