ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler Class Reference
Public Member Functions
__construct (Utf8Converter $converter)
compile (array $ast)
Protected Member Functions
compileRule (array $rule)
compileMap (array $rule)
compileReplace (array $rule)
compileTranspose (array $rule)
compileTransposeModulo (array $rule)
getModuloCharRange ($start, $end, $modulo)
getTransposeClosure ($operator, $value)
compileTargetCharacter ($char)
compileCharacter ($char)
Protected Attributes
$converter
Detailed Description
Compiles the AST of parsed transformation rules into a set of PCRE replace regular expressions.
Definition at line 20 of file PcreCompiler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::__construct (Utf8Converter $converter)
Construct from UTF8Converter
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\Search\Utf8Converter $converter
Definition at line 34 of file PcreCompiler.php.
    {
        $this->converter = $converter;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::compile (array $ast)
Compile AST into a set of regular expressions
The returned array contains a set of regular expressions and their replacement callbacks. The regular expressions can then be applied to strings to executed the transformations.
Parameters
array $ast
Returns
array
Definition at line 50 of file PcreCompiler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compile(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileRule().
    {
        $transformations = array();
        foreach ( $ast as $section => $rules )
        {
            foreach ( $rules as $rule )
            {
                $transformations[$section][] = $this->compileRule( $rule );
            }
        }
        return $transformations;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::compileCharacter ($char) protected
Compile a single source character definition into a plain UTF-8 character
Handles the two formats from the possible character definitions:
U+xxxx : Unicode value in hexadecimal
xx: Ascii value in hexadecimal
Parameters
string $char
Returns
string
Definition at line 275 of file PcreCompiler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileCharacter().
    {
        switch ( true )
        {
            case preg_match( '(^U\\+[0-9a-fA-F]{4}$)', $char ):
                return $this->converter->toUTF8Character( hexdec( substr( $char, 2 ) ) );
            case preg_match( '(^[0-9a-fA-F]{2}$)', $char ):
                return chr( hexdec( $char ) );
            default:
                throw new RuntimeException( "Invalid character definition: $char" );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::compileMap (array $rule) protected
Compile map rule
Parameters
array $rule
Returns
array
Definition at line 100 of file PcreCompiler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileCharacter(), eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileMap(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileTargetCharacter().
    {
        return array(
            'regexp' => '(' . preg_quote( $this->compileCharacter( $rule['data']['src'] ) ) . ')us',
            'callback' => $this->compileTargetCharacter( $rule['data']['dest'] ),
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::compileReplace (array $rule) protected
Compile replace rule
Parameters
array $rule
Returns
array
Definition at line 115 of file PcreCompiler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileCharacter(), eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileReplace(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileTargetCharacter().
    {
        return array(
            'regexp' =>
                '([' .
                preg_quote( $this->compileCharacter( $rule['data']['srcStart'] ) ) . '-' .
                preg_quote( $this->compileCharacter( $rule['data']['srcEnd'] ) ) .
                '])us',
            'callback' => $this->compileTargetCharacter( $rule['data']['dest'] ),
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::compileRule (array $rule) protected
Compiles a single rule
Parameters
array $rule
Returns
array
Definition at line 72 of file PcreCompiler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileMap(), eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileReplace(), eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileRule(), eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileTranspose(), eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileTransposeModulo(), eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_MAP, eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_REPLACE, eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_TRANSPOSE, and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_TRANSPOSE_MODULO.
    {
        switch ( $rule['type'] )
        {
            case TransformationProcessor::T_MAP:
                return $this->compileMap( $rule );
            case TransformationProcessor::T_REPLACE:
                return $this->compileReplace( $rule );
            case TransformationProcessor::T_TRANSPOSE:
                return $this->compileTranspose( $rule );
            case TransformationProcessor::T_TRANSPOSE_MODULO:
                return $this->compileTransposeModulo( $rule );
            default:
                throw new RuntimeException( "Unknown rule type: " . $rule['type'] );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::compileTargetCharacter ($char) protected
Compile target into a closure, which can be used by preg_replace_callback
Parameters
string $char
Returns
callback
Definition at line 227 of file PcreCompiler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileCharacter(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileTargetCharacter().
    {
        switch ( true )
        {
            case ( $char === 'remove' ):
                return function( $matches )
                {
                    return '';
                };
            case ( $char === 'keep' ):
                return function( $matches )
                {
                    return $matches[0];
                };
            case preg_match( '("(?:[^\\\\"]+|\\\\\\\\|\\\\\'|\\\\")*?")', $char );
                $string = str_replace(
                    array( '\\\\', '\\"', "\\'" ),
                    array( '\\', '"', "'" ),
                    substr( $char, 1, -1 )
                );
                return function( $matches ) use ( $string )
                {
                    return $string;
                };
            default:
                $char = $this->compileCharacter( $char );
                return function( $matches ) use ( $char )
                {
                    return $char;
                };
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::compileTranspose (array $rule) protected
Compile transpose rule
Parameters
array $rule
Returns
array
Definition at line 134 of file PcreCompiler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileCharacter(), eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileTranspose(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\getTransposeClosure().
    {
        return array(
            'regexp' =>
                '([' .
                preg_quote( $this->compileCharacter( $rule['data']['srcStart'] ) ) . '-' .
                preg_quote( $this->compileCharacter( $rule['data']['srcEnd'] ) ) .
                '])us',
            'callback' => $this->getTransposeClosure( $rule['data']['op'], $rule['data']['dest'] ),
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::compileTransposeModulo (array $rule) protected
Compile transpose modulo rule
Parameters
array $rule
Returns
array
Definition at line 153 of file PcreCompiler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileCharacter(), eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\compileTransposeModulo(), eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\getModuloCharRange(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\getTransposeClosure().
    {
        return array(
            'regexp' =>
                '([' .
                preg_quote(
                    $this->getModuloCharRange(
                        $this->compileCharacter( $rule['data']['srcStart'] ),
                        $this->compileCharacter( $rule['data']['srcEnd'] ),
                        $rule['data']['modulo']
                    )
                ) .
                '])us',
            'callback' => $this->getTransposeClosure( $rule['data']['op'], $rule['data']['dest'] ),
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::getModuloCharRange ($start, $end, $modulo) protected
Get string with all characters defined by parameters
Returns a string containing all UTF-8 characters starting with the specified $start character up to the $end character with the step size defined in $modulo.
Parameters
string $start
string $end
string $modulo
Returns
string
Definition at line 183 of file PcreCompiler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\getModuloCharRange().
    {
        $start = $this->converter->toUnicodeCodepoint( $start );
        $end = $this->converter->toUnicodeCodepoint( $end );
        $modulo = hexdec( $modulo );
        $chars = '';
        for ( $start; $start <= $end; $start += $modulo )
        {
            $chars .= $this->converter->toUTF8Character( $start );
        }
        return $chars;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::getTransposeClosure ($operator, $value) protected
Returns a closure which modifies the provided character by the given value
Parameters
string $operator
string $value
Returns
callback
Definition at line 207 of file PcreCompiler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\$converter, and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler\getTransposeClosure().
    {
        $value = hexdec( $value ) * ( $operator === '-' ? -1 : 1 );
        $converter = $this->converter;
        return function ( $matches ) use ( $value, $converter )
        {
            return $converter->toUTF8Character(
                $converter->toUnicodeCodepoint( $matches[0] ) + $value
            );
        };
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\PcreCompiler::$converter protected
Definition at line 27 of file PcreCompiler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Search/TransformationProcessor/PcreCompiler.php