ezp-next: eZ\Publish\Core\MVC\Legacy\View\Provider\Location Class Reference
eZ\Publish\Core\MVC\Legacy\View\Provider\Location Class Reference
Public Member Functions
setRequest (Request $request)
getView (APILocation $location, $viewType)
Public Member Functions inherited from eZ\Publish\Core\MVC\Legacy\View\Provider
__construct (Closure $legacyKernelClosure, TwigContentViewLayoutDecorator $decorator, LoggerInterface $logger=null)
Public Member Functions inherited from eZ\Publish\Core\MVC\Symfony\View\Provider\Location
getView (APIContentLocation $location, $viewType)
Protected Attributes
$request
Protected Attributes inherited from eZ\Publish\Core\MVC\Legacy\View\Provider
$logger
$decorator
Additional Inherited Members
Protected Member Functions inherited from eZ\Publish\Core\MVC\Legacy\View\Provider
getLegacyKernel ()
Detailed Description
Definition at line 19 of file Location.php.
Member Function Documentation
eZ\Publish\Core\MVC\Legacy\View\Provider\Location::getView (APILocation $location, $viewType)
Returns a ContentView object corresponding to $location. Will basically run content/view legacy module with appropriate parameters.
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location
string $viewType Variation of display for your content.
Returns
|void
Definition at line 40 of file Location.php.
References eZ\Publish\Core\MVC\Legacy\View\Provider\$decorator, eZ\Publish\Core\MVC\Legacy\View\Provider\$logger, eZ\Publish\Core\MVC\Legacy\View\Provider\getLegacyKernel(), and eZ\Publish\Core\MVC\Legacy\View\Provider\Location\getView().
    {
        $legacyKernel = $this->getLegacyKernel();
        $logger = $this->logger;
        $viewParameters = array();
        if ( isset( $this->request ) )
            $viewParameters = $this->request->attributes->get( 'viewParameters', array() );
        $legacyContentClosure = function ( array $params ) use ( $location, $viewType, $legacyKernel, $logger, $viewParameters )
        {
            // Additional parameters (aka user parameters in legacy) are expected to be scalar
            foreach ( $params as $paramName => $param )
            {
                if ( !is_scalar( $param ) )
                {
                    unset( $params[$paramName] );
                    if ( isset( $logger ) )
                        $logger->notice(
                            "'$paramName' is not scalar, cannot pass it to legacy content module. Skipping.",
                            array( __METHOD__ )
                        );
                }
            }
            // viewbaseLayout is useless in legacy views
            unset( $params['viewbaseLayout'] );
            $params += $viewParameters;
            return $legacyKernel->runCallback(
                function () use ( $location, $viewType, $params )
                {
                    $contentViewModule = eZModule::findModule( 'content' );
                    $moduleResult = $contentViewModule->run(
                        'view',
                        array( $viewType, $location->id ),
                        false,
                        $params
                    );
                    // @todo: What about persistent variable & css/js added from ezjscore ? We ideally want to handle that as well
                    return $moduleResult['content'];
                },
                false
            );
        };
        $this->decorator->setContentView(
            new ContentView( $legacyContentClosure )
        );
        return $this->decorator;
    }
eZ\Publish\Core\MVC\Legacy\View\Provider\Location::setRequest (Request $request)
Definition at line 26 of file Location.php.
References eZ\Publish\Core\MVC\Legacy\View\Provider\Location\setRequest().
    {
        $this->request = $request;
    }
Member Data Documentation
eZ\Publish\Core\MVC\Legacy\View\Provider\Location::$request protected
Definition at line 24 of file Location.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Legacy/View/Provider/Location.php