ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler Class Reference
Public Member Functions
__construct (BaseContentTypeHandler $handler)
createGroup (GroupCreateStruct $createStruct)
updateGroup (GroupUpdateStruct $struct)
deleteGroup ($groupId)
loadGroup ($groupId)
loadGroupByIdentifier ($identifier)
loadAllGroups ()
loadContentTypes ($groupId, $status=0)
load ($contentTypeId, $status=Type::STATUS_DEFINED)
loadByIdentifier ($identifier)
loadByRemoteId ($remoteId)
create (CreateStruct $createStruct)
update ($typeId, $status, UpdateStruct $contentType)
delete ($contentTypeId, $status)
createDraft ($modifierId, $contentTypeId)
copy ($userId, $contentTypeId, $status)
unlink ($groupId, $contentTypeId, $status)
link ($groupId, $contentTypeId, $status)
getFieldDefinition ($id, $status)
addFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
removeFieldDefinition ($contentTypeId, $status, $fieldDefinitionId)
updateFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
publish ($contentTypeId)
clearCache ()
Public Member Functions inherited from eZ\Publish\SPI\Persistence\Content\Type\Handler
create (CreateStruct $contentType)
update ($contentTypeId, $status, UpdateStruct $contentType)
Protected Member Functions
loadFromRows (array $rows, $typeIdentifier, $status)
Protected Attributes
$innerHandler
$groups
$contentTypes
$fieldDefinitions
Detailed Description
Definition at line 23 of file MemoryCachingHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::__construct (BaseContentTypeHandler $handler)
Creates a new content type handler.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Handler $handler
Definition at line 58 of file MemoryCachingHandler.php.
    {
        $this->innerHandler = $handler;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::addFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
Adds a new field definition to an existing Type.
This method creates a new status of the Type with the $fieldDefinition added. It does not update existing content objects depending on the field (default) values.
Parameters
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 346 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->addFieldDefinition( $contentTypeId, $status, $fieldDefinition );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::clearCache ()
Clear internal caches
Returns
void
Definition at line 411 of file MemoryCachingHandler.php.
    {
        $this->groups = $this->contentTypes = $this->fieldDefinitions = array();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::copy ($userId, $contentTypeId, $status)
Parameters
mixed $userId
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Returns
Type
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 275 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->copy( $userId, $contentTypeId, $status );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::create (CreateStruct $createStruct)
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\CreateStruct $createStruct
Returns
Definition at line 218 of file MemoryCachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->create( $createStruct );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::createDraft ($modifierId, $contentTypeId)
Creates a draft of existing defined content type
Updates modified date, sets $modifierId and status to Type::STATUS_DRAFT on the new returned draft.
Parameters
mixed $modifierId
mixed $contentTypeId
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type with defined status is not found
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 263 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$modifierId, and eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->createDraft( $modifierId, $contentTypeId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::createGroup (GroupCreateStruct $createStruct)
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group\CreateStruct $createStruct
Returns
Group
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 67 of file MemoryCachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->createGroup( $createStruct );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::delete ($contentTypeId, $status)
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException If type is defined and still has content
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type is not found
Parameters
mixed $contentTypeId
int $status
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 247 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->delete( $contentTypeId, $status );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::deleteGroup ($groupId)
Parameters
mixed $groupId
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException If type group contains types
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type group with id is not found
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 88 of file MemoryCachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->deleteGroup( $groupId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::getFieldDefinition ($id, $status)
Returns field definition for the given field definition id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If field definition is not found
Parameters
mixed $id
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 323 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$id, and eZ\Publish\SPI\Persistence\Content\Type\$status.
    {
        if ( isset( $this->fieldDefinitions[$id][$status] ) )
        {
            return $this->fieldDefinitions[$id][$status];
        }
        return $this->fieldDefinitions[$id][$status] =
            $this->innerHandler->getFieldDefinition( $id, $status );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::link ($groupId, $contentTypeId, $status)
Link a content type group with a content type
Parameters
mixed $groupId
mixed $contentTypeId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If group or type with provided status is not found
\eZ\Publish\API\Repository\Exceptions\BadStateException If type is already part of group
Todo:
Above throws are not implemented
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 307 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->link( $groupId, $contentTypeId, $status );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::load ($contentTypeId, $status = Type::STATUS_DEFINED)
Parameters
int $contentTypeId
int $status
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 147 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status.
    {
        if ( isset( $this->contentTypes[$contentTypeId][$status] ) )
        {
            return $this->contentTypes[$contentTypeId][$status];
        }
        return $this->contentTypes[$contentTypeId][$status] =
            $this->innerHandler->load( $contentTypeId, $status );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::loadAllGroups ()
Returns
Group[]
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 127 of file MemoryCachingHandler.php.
    {
        return $this->innerHandler->loadAllGroups();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::loadByIdentifier ($identifier)
Load a (defined) content type by identifier
Parameters
string $identifier
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If defined type is not found
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 165 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$identifier.
    {
        if ( isset( $this->contentTypes['identifier'][$identifier] ) )
        {
            return $this->contentTypes['identifier'][$identifier];
        }
        return $this->contentTypes['identifier'][$identifier] =
            $this->innerHandler->loadByIdentifier( $identifier );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::loadByRemoteId ($remoteId)
Load a (defined) content type by remote id
Parameters
mixed $remoteId
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If defined type is not found
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 183 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$remoteId.
    {
        if ( isset( $this->contentTypes['remoteId'][$remoteId] ) )
        {
            return $this->contentTypes['remoteId'][$remoteId];
        }
        return $this->contentTypes['remoteId'][$remoteId] =
            $this->innerHandler->loadByRemoteId( $remoteId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::loadContentTypes ($groupId, $status = 0)
Parameters
mixed $groupId
int $status
Returns
Type[]
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 137 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status.
    {
        return $this->innerHandler->loadContentTypes( $groupId, $status );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::loadFromRows (array $rows, $typeIdentifier, $status) protected
Loads a single Type from $rows
Parameters
array $rows
mixed $typeIdentifier
int $status
Returns
Definition at line 202 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status.
    {
        $types = $this->mapper->extractTypesFromRows( $rows );
        if ( !isset( $types[0] ) )
        {
            throw new Exception\TypeNotFound( $typeIdentifier, $status );
        }
        return $types[0];
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::loadGroup ($groupId)
Parameters
mixed $groupId
Returns
Group
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type group with $groupId is not found
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 99 of file MemoryCachingHandler.php.
    {
        if ( isset( $this->groups[$groupId] ) )
        {
            return $this->groups[$groupId];
        }
        return $this->groups[$groupId] = $this->innerHandler->loadGroup( $groupId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::loadGroupByIdentifier ($identifier)
Parameters
string $identifier
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type group with $identifier is not found
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 114 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$identifier.
    {
        if ( isset( $this->groups[$identifier] ) )
        {
            return $this->groups[$identifier];
        }
        return $this->groups[$identifier] = $this->innerHandler->loadGroupByIdentifier( $identifier );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::publish ($contentTypeId)
Update content objects
Updates content objects, depending on the changed field definitions.
A content type has a state which tells if its content objects yet have been adapted.
Flags the content type as updated.
Parameters
mixed $contentTypeId
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 400 of file MemoryCachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->publish( $contentTypeId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::removeFieldDefinition ($contentTypeId, $status, $fieldDefinitionId)
Removes a field definition from an existing Type.
This method creates a new status of the Type with the field definition referred to by $fieldDefinitionId removed. It does not update existing content objects depending on the field (default) values.
Parameters
mixed $contentTypeId
mixed $fieldDefinitionId
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 363 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->removeFieldDefinition( $contentTypeId, $status, $fieldDefinitionId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::unlink ($groupId, $contentTypeId, $status)
Unlink a content type group from a content type
Parameters
mixed $groupId
mixed $contentTypeId
int $status
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If group or type with provided status is not found
\eZ\Publish\API\Repository\Exceptions\BadStateException If $groupId is last group on $contentTypeId or not a group assigned to type
Todo:
Add throws for NotFound and BadState when group is not assigned to type
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 292 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->unlink( $groupId, $contentTypeId, $status );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::update ($typeId, $status, UpdateStruct $contentType)
Parameters
mixed $typeId
int $status
\eZ\Publish\SPI\Persistence\Content\Type\UpdateStruct $contentType
Returns
Type
Definition at line 230 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->update( $typeId, $status, $contentType );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::updateFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
This method updates the given $fieldDefinition on a Type.
This method creates a new status of the Type with the updated $fieldDefinition. It does not update existing content objects depending on the field (default) values.
Parameters
mixed $contentTypeId
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 381 of file MemoryCachingHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->updateFieldDefinition( $contentTypeId, $status, $fieldDefinition );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::updateGroup (GroupUpdateStruct $struct)
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group\UpdateStruct $struct
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 77 of file MemoryCachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler\clearCache().
    {
        $this->clearCache();
        return $this->innerHandler->updateGroup( $struct );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::$contentTypes protected
Definition at line 44 of file MemoryCachingHandler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::$fieldDefinitions protected
Definition at line 51 of file MemoryCachingHandler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::$groups protected
Definition at line 37 of file MemoryCachingHandler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Type\MemoryCachingHandler::$innerHandler protected
Definition at line 30 of file MemoryCachingHandler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Type/MemoryCachingHandler.php