ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase Class Reference
Public Member Functions
__construct (EzcDbHandler $db, QueryBuilder $queryBuilder, LanguageHandler $languageHandler, LanguageMaskGenerator $languageMaskGenerator)
getContext ()
insertContentObject (CreateStruct $struct, $currentVersionNo=1)
updateContent ($contentId, MetadataUpdateStruct $struct)
updateVersion ($contentId, $versionNo, UpdateStruct $struct)
setStatus ($contentId, $version, $status)
insertNewField (Content $content, Field $field, StorageFieldValue $value)
insertExistingField (Content $content, Field $field, StorageFieldValue $value)
updateField (Field $field, StorageFieldValue $value)
updateNonTranslatableField (Field $field, StorageFieldValue $value, $contentId)
load ($contentId, $version, $translations=null)
loadLatestPublishedData ($contentId)
loadVersionInfo ($contentId, $versionNo)
listVersionsForUser ($userId, $status=VersionInfo::STATUS_DRAFT)
listVersions ($contentId)
getLastVersionNumber ($contentId)
getAllLocationIds ($contentId)
getFieldIdsByType ($contentId, $versionNo=null)
deleteRelations ($contentId, $versionNo=null)
deleteField ($fieldId, $version)
deleteFields ($contentId, $versionNo=null)
deleteVersions ($contentId, $versionNo=null)
deleteNames ($contentId, $versionNo=null)
setName ($contentId, $version, $name, $language)
deleteContent ($contentId)
loadRelations ($contentId, $contentVersionNo=null, $relationType=null)
loadReverseRelations ($toContentId, $relationType=null)
insertRelation (RelationCreateStruct $createStruct)
deleteRelation ($relationId)
Public Member Functions inherited from eZ\Publish\Core\Persistence\Legacy\Content\Gateway
insertVersion (VersionInfo $versionInfo, array $fields)
updateVersion ($contentId, $versionNo, UpdateStruct $struct)
updateAlwaysAvailableFlag ($contentId, $newAlwaysAvailable)
loadContentInfo ($contentId)
Protected Member Functions
generateLanguageMask (array $fields, $alwaysAvailable)
setInsertFieldValues (\ezcQueryInsert $q, Content $content, Field $field, StorageFieldValue $value)
setFieldUpdateValues (ezcQueryUpdate $q, StorageFieldValue $value)
Protected Attributes
$dbHandler
$queryBuilder
$languageHandler
$languageMaskGenerator
Detailed Description
ezcDatabase based content gateway
Definition at line 33 of file EzcDatabase.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::__construct (EzcDbHandler $db, QueryBuilder $queryBuilder, LanguageHandler $languageHandler, LanguageMaskGenerator $languageMaskGenerator)
Creates a new gateway based on $db
Parameters
\eZ\Publish\Core\Persistence\Legacy\EzcDbHandler $db
\eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase\QueryBuilder $queryBuilder
\eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler $languageHandler
\eZ\Publish\Core\Persistence\Legacy\Content\Language\MaskGenerator $languageMaskGenerator
Definition at line 71 of file EzcDatabase.php.
    {
        $this->dbHandler = $db;
        $this->queryBuilder = $queryBuilder;
        $this->languageHandler = $languageHandler;
        $this->languageMaskGenerator = $languageMaskGenerator;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::deleteContent ($contentId)
Deletes the actual content object referred to by $contentId
Parameters
int $contentId
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1305 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom( 'ezcontentobject' )
            ->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'id' ),
                    $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::deleteField ($fieldId, $version)
Deletes the field with the given $fieldId
Parameters
int $fieldId
int $version
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1105 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcontentobject_attribute' )
        )->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'id' ),
                    $query->bindValue( $fieldId, null, \PDO::PARAM_INT )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $query->bindValue( $version, null, \PDO::PARAM_INT )
                )
            )
        );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::deleteFields ($contentId, $versionNo = null)
Deletes all fields of $contentId in all versions. If $versionNo is set only fields for that version are deleted.
Parameters
int $contentId
int | null $versionNo
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1135 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom( 'ezcontentobject_attribute' )
            ->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentobject_id' ),
                    $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                )
            );
        if ( isset( $versionNo ) )
        {
            $query->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $query->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            );
        }
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::deleteNames ($contentId, $versionNo = null)
Deletes all names of $contentId. If $versionNo is set only names for that version are deleted.
Parameters
int $contentId
int | null $versionNo
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1201 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom( 'ezcontentobject_name' )
            ->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentobject_id' ),
                    $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                )
            );
        if ( isset( $versionNo ) )
        {
            $query->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'content_version' ),
                    $query->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            );
        }
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::deleteRelation ($relationId)
Deletes the relation with the given $relationId
Parameters
int $relationId
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1483 of file EzcDatabase.php.
    {
        $q = $this->dbHandler->createDeleteQuery();
        $q->deleteFrom( 'ezcontentobject_link' )
        ->where(
            $q->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $q->bindValue( $relationId, null, \PDO::PARAM_INT )
            )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::deleteRelations ($contentId, $versionNo = null)
Deletes relations to and from $contentId. If $versionNo is set only relations for that version are deleted.
Parameters
int $contentId
int | null $versionNo
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1056 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcontentobject_link' )
        );
        if ( isset( $versionNo ) )
        {
            $query->where(
                $query->expr->lAnd(
                    $query->expr->eq(
                        $this->dbHandler->quoteColumn( 'from_contentobject_id' ),
                        $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                    ),
                    $query->expr->eq(
                        $this->dbHandler->quoteColumn( 'from_contentobject_version' ),
                        $query->bindValue( $versionNo, null, \PDO::PARAM_INT )
                    )
                )
            );
        }
        else
        {
            $query->where(
                $query->expr->lOr(
                    $query->expr->eq(
                        $this->dbHandler->quoteColumn( 'from_contentobject_id' ),
                        $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                    ),
                    $query->expr->eq(
                        $this->dbHandler->quoteColumn( 'to_contentobject_id' ),
                        $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                    )
                )
            );
        }
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::deleteVersions ($contentId, $versionNo = null)
Deletes all versions of $contentId. If $versionNo is set only that version is deleted.
Parameters
int $contentId
int | null $versionNo
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1168 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom( 'ezcontentobject_version' )
            ->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentobject_id' ),
                    $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                )
            );
        if ( isset( $versionNo ) )
        {
            $query->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $query->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            );
        }
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::generateLanguageMask (array $fields, $alwaysAvailable) protected
Generates a language mask for $version
Parameters
\eZ\Publish\SPI\Persistence\Content\Field[] $fields
boolean $alwaysAvailable
Returns
int
Definition at line 178 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase\generateLanguageMask().
    {
        $languages = array();
        foreach ( $fields as $field )
        {
            if ( isset( $languages[$field->languageCode] ) )
                continue;
            $languages[$field->languageCode] = true;
        }
        if ( $alwaysAvailable )
        {
            $languages['always-available'] = true;
        }
        return $this->languageMaskGenerator->generateLanguageMask( $languages );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::getAllLocationIds ($contentId)
Returns all IDs for locations that refer to $contentId
Parameters
int $contentId
Returns
int[]
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 978 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $this->dbHandler->quoteColumn( 'node_id' )
        )->from(
            $this->dbHandler->quoteTable( 'ezcontentobject_tree' )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'contentobject_id' ),
                $query->bindValue( $contentId, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_COLUMN );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::getContext ()
Get context definition for external storage layers
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 88 of file EzcDatabase.php.
    {
        return array(
            'identifier' => 'LegacyStorage',
            'connection' => $this->dbHandler,
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::getFieldIdsByType ($contentId, $versionNo = null)
Returns all field IDs of $contentId grouped by their type. If $versionNo is set only field IDs for that version are returned.
Parameters
int $contentId
int | null $versionNo
Returns
int[][]
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1007 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $this->dbHandler->quoteColumn( 'id' ),
            $this->dbHandler->quoteColumn( 'data_type_string' )
        )->from(
            $this->dbHandler->quoteTable( 'ezcontentobject_attribute' )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'contentobject_id' ),
                $query->bindValue( $contentId, null, \PDO::PARAM_INT )
            )
        );
        if ( isset( $versionNo ) )
        {
            $query->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $query->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            );
        }
        $statement = $query->prepare();
        $statement->execute();
        $result = array();
        foreach ( $statement->fetchAll() as $row )
        {
            if ( !isset( $result[$row['data_type_string']] ) )
            {
                $result[$row['data_type_string']] = array();
            }
            $result[$row['data_type_string']][] = (int)$row['id'];
        }
        return $result;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::getLastVersionNumber ($contentId)
Returns last version number for content identified by $contentId
Parameters
int $contentId
Returns
int
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 951 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->expr->max( $this->dbHandler->quoteColumn( 'version' ) )
        )->from(
            $this->dbHandler->quoteTable( 'ezcontentobject_version' )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'contentobject_id' ),
                $query->bindValue( $contentId, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return (int)$statement->fetchColumn();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::insertContentObject (CreateStruct $struct, $currentVersionNo = 1)
Inserts a new content object.
Parameters
\eZ\Publish\SPI\Persistence\Content\CreateStruct $struct
mixed $currentVersionNo
Returns
int ID
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 104 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase\generateLanguageMask(), and eZ\Publish\SPI\Persistence\Content\ContentInfo\STATUS_DRAFT.
    {
        $initialLanguageCode = $this->languageHandler->load( $struct->initialLanguageId )->languageCode;
        if ( isset( $struct->name[$initialLanguageCode] ) )
        {
            $name = $struct->name[$initialLanguageCode];
        }
        else
        {
            $name = '';
        }
        $q = $this->dbHandler->createInsertQuery();
        $q->insertInto(
            $this->dbHandler->quoteTable( 'ezcontentobject' )
        )->set(
            $this->dbHandler->quoteColumn( 'id' ),
            $this->dbHandler->getAutoIncrementValue( 'ezcontentobject', 'id' )
        )->set(
            $this->dbHandler->quoteColumn( 'current_version' ),
            $q->bindValue( $currentVersionNo, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'name' ),
            $q->bindValue( $name, null, \PDO::PARAM_STR )
        )->set(
            $this->dbHandler->quoteColumn( 'contentclass_id' ),
            $q->bindValue( $struct->typeId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'section_id' ),
            $q->bindValue( $struct->sectionId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'owner_id' ),
            $q->bindValue( $struct->ownerId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'initial_language_id' ),
            $q->bindValue( $struct->initialLanguageId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'remote_id' ),
            $q->bindValue( $struct->remoteId, null, \PDO::PARAM_STR )
        )->set(
            $this->dbHandler->quoteColumn( 'modified' ),
            $q->bindValue( 0, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'published' ),
            $q->bindValue( 0, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'status' ),
            $q->bindValue( ContentInfo::STATUS_DRAFT, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'language_mask' ),
            $q->bindValue(
                $this->generateLanguageMask(
                    $struct->fields, $struct->alwaysAvailable
                ),
                null,
                \PDO::PARAM_INT
            )
        );
        $q->prepare()->execute();
        return $this->dbHandler->lastInsertId(
            $this->dbHandler->getSequenceName( 'ezcontentobject', 'id' )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::insertExistingField (Content $content, Field $field, StorageFieldValue $value)
Inserts an existing field.
Used to insert a field with an exsting ID but a new version number.
Parameters
Content $content
Field $field
StorageFieldValue $value
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 575 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase\setInsertFieldValues().
    {
        $q = $this->dbHandler->createInsertQuery();
        $this->setInsertFieldValues( $q, $content, $field, $value );
        $q->set(
            $this->dbHandler->quoteColumn( 'id' ),
            $q->bindValue( $field->id, null, \PDO::PARAM_INT )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::insertNewField (Content $content, Field $field, StorageFieldValue $value)
Inserts a new field.
Only used when a new field is created (i.e. a new object or a field in a new language!). After that, field IDs need to stay the same, only the version number changes.
Parameters
\eZ\Publish\SPI\Persistence\Content $content
\eZ\Publish\SPI\Persistence\Content\Field $field
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldValue $value
Returns
int ID
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 545 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase\setInsertFieldValues().
    {
        $q = $this->dbHandler->createInsertQuery();
        $this->setInsertFieldValues( $q, $content, $field, $value );
        // Insert with auto increment ID
        $q->set(
            $this->dbHandler->quoteColumn( 'id' ),
            $this->dbHandler->getAutoIncrementValue( 'ezcontentobject_attribute', 'id' )
        );
        $q->prepare()->execute();
        return $this->dbHandler->lastInsertId(
            $this->dbHandler->getSequenceName( 'ezcontentobject_attribute', 'id' )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::insertRelation (RelationCreateStruct $createStruct)
Inserts a new relation database record
Parameters
\eZ\Publish\SPI\Persistence\Content\Relation\CreateStruct $createStruct
Returns
int ID the inserted ID
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1444 of file EzcDatabase.php.
    {
        $q = $this->dbHandler->createInsertQuery();
        $q->insertInto(
            $this->dbHandler->quoteTable( 'ezcontentobject_link' )
        )->set(
            $this->dbHandler->quoteColumn( 'id' ),
            $this->dbHandler->getAutoIncrementValue( 'ezcontentobject_link', 'id' )
        )->set(
            $this->dbHandler->quoteColumn( 'contentclassattribute_id' ),
            $q->bindValue( (int)$createStruct->sourceFieldDefinitionId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'from_contentobject_id' ),
            $q->bindValue( $createStruct->sourceContentId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'from_contentobject_version' ),
            $q->bindValue( $createStruct->sourceContentVersionNo, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'relation_type' ),
            $q->bindValue( $createStruct->type, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'to_contentobject_id' ),
            $q->bindValue( $createStruct->destinationContentId, null, \PDO::PARAM_INT )
        );
        $q->prepare()->execute();
        return $this->dbHandler->lastInsertId(
            $this->dbHandler->getSequenceName( 'ezcontentobject_link', 'id' )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::listVersions ($contentId)
Returns all version data for the given $contentId
Parameters
mixed $contentId
Returns
string[][]
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 926 of file EzcDatabase.php.
    {
        $query = $this->queryBuilder->createVersionInfoFindQuery();
        $query->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'contentobject_id', 'ezcontentobject_version' ),
                $query->bindValue( $contentId, null, \PDO::PARAM_INT )
            )
        )->groupBy(
            $this->dbHandler->quoteColumn( 'id', 'ezcontentobject_version' )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::listVersionsForUser ($userId, $status = VersionInfo::STATUS_DRAFT)
Returns data for all versions with given status created by the given $userId
Parameters
int $userId
int $status
Returns
string[][]
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 895 of file EzcDatabase.php.
    {
        $query = $this->queryBuilder->createVersionInfoFindQuery();
        $query->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'status', 'ezcontentobject_version' ),
                    $query->bindValue( $status, null, \PDO::PARAM_INT )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'creator_id', 'ezcontentobject_version' ),
                    $query->bindValue( $userId, null, \PDO::PARAM_INT )
                )
            )
        )->groupBy(
            $this->dbHandler->quoteColumn( 'id', 'ezcontentobject_version' )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::load ($contentId, $version, $translations = null)
Loads data for a content object
Returns an array with the relevant data.
Parameters
mixed $contentId
mixed $version
string[] $translations
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 753 of file EzcDatabase.php.
    {
        $query = $this->queryBuilder->createFindQuery( $translations );
        $query->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'id', 'ezcontentobject' ),
                    $query->bindValue( $contentId )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'version', 'ezcontentobject_version' ),
                    $query->bindValue( $version )
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::loadLatestPublishedData ($contentId)
Loads data for the latest published version of the content identified by $contentId
Parameters
mixed $contentId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 782 of file EzcDatabase.php.
    {
        $query = $this->queryBuilder->createFindQuery();
        $query->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'id', 'ezcontentobject' ),
                    $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'version', 'ezcontentobject_version' ),
                    $this->dbHandler->quoteColumn( 'current_version', 'ezcontentobject' )
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::loadRelations ($contentId, $contentVersionNo = null, $relationType = null)
Loads relations from $contentId to published content, optionally only from $contentVersionNo.
$relationType can also be filtered.
Parameters
int $contentId
int $contentVersionNo
int $relationType
Returns
string[][] array of relation data
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1330 of file EzcDatabase.php.
    {
        $query = $this->queryBuilder->createRelationFindQuery();
        $query->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'from_contentobject_id', 'ezcontentobject_link' ),
                $query->bindValue( $contentId, null, \PDO::PARAM_INT )
            )
        );
        // source version number
        if ( isset( $contentVersionNo ) )
        {
            $query->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'from_contentobject_version', 'ezcontentobject_link' ),
                    $query->bindValue( $contentVersionNo, null, \PDO::PARAM_INT  )
                )
            );
        }
        // from published version only
        else
        {
            $query->from(
                $this->dbHandler->quoteTable( 'ezcontentobject' )
            )->where(
                $query->expr->lAnd(
                    $query->expr->eq(
                        $this->dbHandler->quoteColumn( 'id', 'ezcontentobject' ),
                        $this->dbHandler->quoteColumn( 'from_contentobject_id', 'ezcontentobject_link' )
                    ),
                    $query->expr->eq(
                        $this->dbHandler->quoteColumn( 'current_version', 'ezcontentobject' ),
                        $this->dbHandler->quoteColumn( 'from_contentobject_version', 'ezcontentobject_link' )
                    )
                )
            );
        }
        // relation type
        if ( isset( $relationType ) )
        {
            $query->where(
                $query->expr->bitAnd(
                    $this->dbHandler->quoteColumn( 'relation_type', 'ezcontentobject_link' ),
                    $query->bindValue( $relationType, null, \PDO::PARAM_INT )
                )
            );
        }
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::loadReverseRelations ($toContentId, $relationType = null)
Loads data that related to $toContentId
Parameters
int $toContentId
int $relationType
Returns
mixed[][] Content data, array structured like {
See Also
::load()}
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1394 of file EzcDatabase.php.
    {
        $query = $this->queryBuilder->createRelationFindQuery();
        $query->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'to_contentobject_id', 'ezcontentobject_link' ),
                $query->bindValue( $toContentId, null, \PDO::PARAM_INT )
            )
        );
        // ezcontentobject join
        $query->from(
            $this->dbHandler->quoteTable( 'ezcontentobject' )
        )->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'id', 'ezcontentobject' ),
                    $this->dbHandler->quoteColumn( 'from_contentobject_id', 'ezcontentobject_link' )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'current_version', 'ezcontentobject' ),
                    $this->dbHandler->quoteColumn( 'from_contentobject_version', 'ezcontentobject_link' )
                )
            )
        );
        // relation type
        if ( isset( $relationType ) )
        {
            $query->where(
                $query->expr->bitAnd(
                    $this->dbHandler->quoteColumn( 'relation_type', 'ezcontentobject_link' ),
                    $query->bindValue( $relationType, null, \PDO::PARAM_INT )
                )
            );
        }
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::loadVersionInfo ($contentId, $versionNo)
Loads version info for content identified by $contentId and $versionNo. Will basically return a hash containing all field values from ezcontentobject_version table plus following keys:
names => Hash of content object names. Key is the language code, value is the name.
languages => Hash of language ids. Key is the language code (e.g. "eng-GB"), value is the language numeric id without the always available bit.
initial_language_code => Language code for initial language in this version.
Parameters
int $contentId
int $versionNo
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 866 of file EzcDatabase.php.
    {
        $query = $this->queryBuilder->createVersionInfoFindQuery();
        $query->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentobject_id', 'ezcontentobject_version' ),
                    $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'version', 'ezcontentobject_version' ),
                    $query->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::setFieldUpdateValues (ezcQueryUpdate $q, StorageFieldValue $value) protected
Sets update fields for $value on $q
Parameters
\ezcQueryUpdate $q
StorageFieldValue $value
Returns
void
Definition at line 683 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase\setFieldUpdateValues().
    {
        $q->update(
            $this->dbHandler->quoteTable( 'ezcontentobject_attribute' )
        )->set(
            $this->dbHandler->quoteColumn( 'data_float' ),
            $q->bindValue( $value->dataFloat )
        )->set(
            $this->dbHandler->quoteColumn( 'data_int' ),
            $q->bindValue( $value->dataInt, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'data_text' ),
            $q->bindValue( $value->dataText )
        )->set(
            $this->dbHandler->quoteColumn( 'sort_key_int' ),
            $q->bindValue( $value->sortKeyInt, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'sort_key_string' ),
            $q->bindValue( $value->sortKeyString )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::setInsertFieldValues (\ezcQueryInsert $q, Content $content, Field $field, StorageFieldValue $value) protected
Inserts $field with $newFieldId or not
Parameters
Content $content
Field $field
StorageFieldValue $value
mixed $newFieldId
Returns
int|null Maybe a new field ID
Definition at line 599 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase\setInsertFieldValues().
    {
        $q->insertInto(
            $this->dbHandler->quoteTable( 'ezcontentobject_attribute' )
        )->set(
            $this->dbHandler->quoteColumn( 'contentobject_id' ),
            $q->bindValue( $content->versionInfo->contentInfo->id, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'contentclassattribute_id' ),
            $q->bindValue( $field->fieldDefinitionId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'data_type_string' ),
            $q->bindValue( $field->type )
        )->set(
            $this->dbHandler->quoteColumn( 'language_code' ),
            $q->bindValue( $field->languageCode )
        )->set(
            $this->dbHandler->quoteColumn( 'version' ),
            $q->bindValue( $field->versionNo )
        )->set(
            $this->dbHandler->quoteColumn( 'data_float' ),
            $q->bindValue( $value->dataFloat )
        )->set(
            $this->dbHandler->quoteColumn( 'data_int' ),
            $q->bindValue( $value->dataInt )
        )->set(
            $this->dbHandler->quoteColumn( 'data_text' ),
            $q->bindValue( $value->dataText )
        )->set(
            $this->dbHandler->quoteColumn( 'sort_key_int' ),
            $q->bindValue( $value->sortKeyInt )
        )->set(
            $this->dbHandler->quoteColumn( 'sort_key_string' ),
            $q->bindValue( $value->sortKeyString )
        )->set(
            $this->dbHandler->quoteColumn( 'language_id' ),
            $q->bindValue(
                $this->languageMaskGenerator->generateLanguageIndicator(
                    $field->languageCode,
                    $content->versionInfo->contentInfo->alwaysAvailable
                ),
                null,
                \PDO::PARAM_INT
            )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::setName ($contentId, $version, $name, $language)
Sets the name for Content $contentId in version $version to $name in $language
Parameters
int $contentId
int $version
string $name
string $language
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 1235 of file EzcDatabase.php.
    {
        $language = $this->languageHandler->loadByLanguageCode( $language );
        // Is it an insert or an update ?
        $qSelect = $this->dbHandler->createSelectQuery();
        $qSelect
            ->select(
                $qSelect->alias( $qSelect->expr->count( '*' ), 'count' )
            )
            ->from( $this->dbHandler->quoteTable( 'ezcontentobject_name' ) )
            ->where(
                $qSelect->expr->lAnd(
                    $qSelect->expr->eq( $this->dbHandler->quoteColumn( 'contentobject_id' ), $qSelect->bindValue( $contentId ) ),
                    $qSelect->expr->eq( $this->dbHandler->quoteColumn( 'content_version' ), $qSelect->bindValue( $version ) ),
                    $qSelect->expr->eq( $this->dbHandler->quoteColumn( 'content_translation' ), $qSelect->bindValue( $language->languageCode ) )
                )
            );
        $stmt = $qSelect->prepare();
        $stmt->execute();
        $res = $stmt->fetchAll( \PDO::FETCH_ASSOC );
        $insert = $res[0]['count'] == 0;
        if ( $insert )
        {
            $q = $this->dbHandler->createInsertQuery();
            $q->insertInto( $this->dbHandler->quoteTable( 'ezcontentobject_name' ) );
        }
        else
        {
            $q = $this->dbHandler->createUpdateQuery();
            $q->update( $this->dbHandler->quoteTable( 'ezcontentobject_name' ) )
                ->where(
                    $q->expr->lAnd(
                        $q->expr->eq( $this->dbHandler->quoteColumn( 'contentobject_id' ), $q->bindValue( $contentId ) ),
                        $q->expr->eq( $this->dbHandler->quoteColumn( 'content_version' ), $q->bindValue( $version ) ),
                        $q->expr->eq( $this->dbHandler->quoteColumn( 'content_translation' ), $q->bindValue( $language->languageCode ) )
                    )
                );
        }
        $q->set(
            $this->dbHandler->quoteColumn( 'contentobject_id' ),
            $q->bindValue( $contentId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'content_version' ),
            $q->bindValue( $version, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'language_id' ),
            $q->bindValue( $language->id, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'content_translation' ),
            $q->bindValue( $language->languageCode )
        )->set(
            $this->dbHandler->quoteColumn( 'real_translation' ),
            $q->bindValue( $language->languageCode )
        )->set(
            $this->dbHandler->quoteColumn( 'name' ),
            $q->bindValue( $name )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::setStatus ($contentId, $version, $status)
Sets the status of the version identified by $contentId and $version to $status.
The $status can be one of STATUS_DRAFT, STATUS_PUBLISHED, STATUS_ARCHIVED
Parameters
int $contentId
int $version
int $status
Returns
boolean
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 476 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\ContentInfo\STATUS_PUBLISHED.
    {
        $q = $this->dbHandler->createUpdateQuery();
        $q->update(
            $this->dbHandler->quoteTable( 'ezcontentobject_version' )
        )->set(
            $this->dbHandler->quoteColumn( 'status' ),
            $q->bindValue( $status, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'modified' ),
            $q->bindValue( time(), null, \PDO::PARAM_INT )
        )->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentobject_id' ),
                    $q->bindValue( $contentId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $q->bindValue( $version, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $q->prepare();
        $statement->execute();
        if ( (bool)$statement->rowCount() === false )
            return false;
        if ( $status !== APIVersionInfo::STATUS_PUBLISHED )
        {
            return true;
        }
        // If the version's status is PUBLISHED, we set the content to published status as well
        $q = $this->dbHandler->createUpdateQuery();
        $q->update(
            $this->dbHandler->quoteTable( 'ezcontentobject' )
        )->set(
            $this->dbHandler->quoteColumn( 'status' ),
            $q->bindValue( ContentInfo::STATUS_PUBLISHED, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'current_version' ),
            $q->bindValue( $version, null, \PDO::PARAM_INT )
        )->where(
            $q->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $q->bindValue( $contentId, null, \PDO::PARAM_INT )
            )
        );
        $statement = $q->prepare();
        $statement->execute();
        return (bool)$statement->rowCount();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::updateContent ($contentId, MetadataUpdateStruct $struct)
Updates an existing content identified by $contentId in respect to $struct
Parameters
int $contentId
\eZ\Publish\SPI\Persistence\Content\MetadataUpdateStruct $struct
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 264 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Gateway\updateAlwaysAvailableFlag().
    {
        $q = $this->dbHandler->createUpdateQuery();
        $q->update( $this->dbHandler->quoteTable( 'ezcontentobject' ) );
        if ( isset( $struct->name ) )
        {
            $q->set(
                $this->dbHandler->quoteColumn( 'name' ),
                $q->bindValue( $struct->name, null, \PDO::PARAM_STR )
            );
        }
        if ( isset( $struct->mainLanguageId ) )
        {
            $q->set(
                $this->dbHandler->quoteColumn( 'initial_language_id' ),
                $q->bindValue( $struct->mainLanguageId, null, \PDO::PARAM_INT )
            );
        }
        if ( isset( $struct->modificationDate ) )
        {
            $q->set(
                $this->dbHandler->quoteColumn( 'modified' ),
                $q->bindValue( $struct->modificationDate, null, \PDO::PARAM_INT )
            );
        }
        if ( isset( $struct->ownerId ) )
        {
            $q->set(
                $this->dbHandler->quoteColumn( 'owner_id' ),
                $q->bindValue( $struct->ownerId, null, \PDO::PARAM_INT )
            );
        }
        if ( isset( $struct->publicationDate ) )
        {
            $q->set(
                $this->dbHandler->quoteColumn( 'published' ),
                $q->bindValue( $struct->publicationDate, null, \PDO::PARAM_INT )
            );
        }
        if ( isset( $struct->remoteId ) )
        {
            $q->set(
                $this->dbHandler->quoteColumn( 'remote_id' ),
                $q->bindValue( $struct->remoteId, null, \PDO::PARAM_STR )
            );
        }
        $q->where(
            $q->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $q->bindValue( $contentId, null, \PDO::PARAM_INT )
            )
        );
        $q->prepare()->execute();
        // Handle alwaysAvailable flag update separately as it's a more complex task and has impact on several tables
        if ( isset( $struct->alwaysAvailable ) )
        {
            $this->updateAlwaysAvailableFlag( $contentId, $struct->alwaysAvailable );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::updateField (Field $field, StorageFieldValue $value)
Updates an existing field
Parameters
Field $field
StorageFieldValue $value
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 654 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase\setFieldUpdateValues().
    {
        // Note, no need to care for language_id here, since Content->$alwaysAvailable
        // cannot change on update
        $q = $this->dbHandler->createUpdateQuery();
        $this->setFieldUpdateValues( $q, $value );
        $q->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'id' ),
                    $q->bindValue( $field->id, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $q->bindValue( $field->versionNo, null, \PDO::PARAM_INT )
                )
            )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::updateNonTranslatableField (Field $field, StorageFieldValue $value, $contentId)
Updates an existing, non-translatable field
Parameters
\eZ\Publish\SPI\Persistence\Content\Field $field
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldValue $value
int $contentId
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Gateway.
Definition at line 714 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase\setFieldUpdateValues().
    {
        // Note, no need to care for language_id here, since Content->$alwaysAvailable
        // cannot change on update
        $q = $this->dbHandler->createUpdateQuery();
        $this->setFieldUpdateValues( $q, $value );
        $q->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclassattribute_id' ),
                    $q->bindValue( $field->fieldDefinitionId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentobject_id' ),
                    $q->bindValue( $contentId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $q->bindValue( $field->versionNo, null, \PDO::PARAM_INT )
                )
            )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::updateVersion ($contentId, $versionNo, UpdateStruct $struct)
Updates version $versionNo for content identified by $contentId, in respect to $struct
Parameters
int $contentId
int $versionNo
\eZ\Publish\SPI\Persistence\Content\UpdateStruct $struct
Returns
void
Definition at line 336 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase\generateLanguageMask().
    {
        $q = $this->dbHandler->createUpdateQuery();
        $q->update(
            $this->dbHandler->quoteTable( 'ezcontentobject_version' )
        )->set(
            $this->dbHandler->quoteColumn( 'creator_id' ),
            $q->bindValue( $struct->creatorId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'modified' ),
            $q->bindValue( $struct->modificationDate, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'initial_language_id' ),
            $q->bindValue( $struct->initialLanguageId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'language_mask' ),
            $q->expr->bitOr(
                $this->dbHandler->quoteColumn( 'language_mask' ),
                $q->bindValue( $this->generateLanguageMask( $struct->fields, false ), null, \PDO::PARAM_INT )
            )
        )->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentobject_id' ),
                    $q->bindValue( $contentId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $q->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            )
        );
        $q->prepare()->execute();
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::$dbHandler protected
Definition at line 40 of file EzcDatabase.php.
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::$languageHandler protected
Definition at line 54 of file EzcDatabase.php.
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::$languageMaskGenerator protected
Definition at line 61 of file EzcDatabase.php.
eZ\Publish\Core\Persistence\Legacy\Content\Gateway\EzcDatabase::$queryBuilder protected
Definition at line 47 of file EzcDatabase.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Gateway/EzcDatabase.php