ezp-next: eZ\Publish\Core\MVC\Symfony\Controller\Controller Class Reference
eZ\Publish\Core\MVC\Symfony\Controller\Controller Class Reference
Public Member Functions
getParameter ($parameterName, $defaultValue=null)
hasParameter ($parameterName)
getConfigResolver ()
render ($view, array $parameters=array(), Response $response=null)
getTemplateEngine ()
getLogger ()
getRepository ()
getRequest ()
getEventDispatcher ()
isGranted (AuthorizationAttribute $attribute)
Detailed Description
Definition at line 17 of file Controller.php.
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\Controller\Controller::getConfigResolver ()
Returns
Definition at line 50 of file Controller.php.
    {
        return $this->container->get( 'ezpublish.config.resolver' );
    }
eZ\Publish\Core\MVC\Symfony\Controller\Controller::getEventDispatcher ()
Returns
Definition at line 110 of file Controller.php.
    {
        return $this->container->get( 'event_dispatcher' );
    }
eZ\Publish\Core\MVC\Symfony\Controller\Controller::getLogger ()
Returns
|null
Definition at line 86 of file Controller.php.
    {
        return $this->container->get( 'logger', ContainerInterface::NULL_ON_INVALID_REFERENCE );
    }
eZ\Publish\Core\MVC\Symfony\Controller\Controller::getParameter ($parameterName, $defaultValue = null)
Returns value for $parameterName and fallbacks to $defaultValue if not defined
Parameters
string $parameterName
mixed $defaultValue
Returns
mixed
Definition at line 27 of file Controller.php.
References eZ\Publish\Core\MVC\Symfony\Controller\Controller\getConfigResolver(), and eZ\Publish\Core\MVC\Symfony\Controller\Controller\hasParameter().
    {
        if ( $this->getConfigResolver()->hasParameter( $parameterName ) )
            return $this->getConfigResolver()->getParameter( $parameterName );
        return $defaultValue;
    }
eZ\Publish\Core\MVC\Symfony\Controller\Controller::getRepository ()
Returns
Definition at line 94 of file Controller.php.
    {
        return $this->container->get( 'ezpublish.api.repository' );
    }
eZ\Publish\Core\MVC\Symfony\Controller\Controller::getRequest ()
Returns
Definition at line 102 of file Controller.php.
    {
        return $this->container->get( 'request' );
    }
eZ\Publish\Core\MVC\Symfony\Controller\Controller::getTemplateEngine ()
Returns
Definition at line 78 of file Controller.php.
    {
        return $this->container->get( 'templating' );
    }
eZ\Publish\Core\MVC\Symfony\Controller\Controller::hasParameter ($parameterName)
Checks if $parameterName is defined
Parameters
string $parameterName
Returns
boolean
Definition at line 42 of file Controller.php.
References eZ\Publish\Core\MVC\Symfony\Controller\Controller\getConfigResolver().
    {
        return $this->getConfigResolver()->hasParameter( $parameterName );
    }
eZ\Publish\Core\MVC\Symfony\Controller\Controller::isGranted (AuthorizationAttribute $attribute)
Checks if current user has granted access to provided attribute
Parameters
\eZ\Publish\Core\MVC\Symfony\Security\Authorization\Attribute $attribute
Returns
boolean
Definition at line 122 of file Controller.php.
    {
        return $this->container->get( 'security.context' )->isGranted( $attribute );
    }
eZ\Publish\Core\MVC\Symfony\Controller\Controller::render ($view, array $parameters = array(), Response $response = null)
Renders a view.
Parameters
string $view The view name
array $parameters An array of parameters to pass to the view
\Symfony\Component\HttpFoundation\Response $response
Returns
Definition at line 64 of file Controller.php.
References eZ\Publish\Core\MVC\Symfony\Controller\Controller\getTemplateEngine().
    {
        if ( !isset( $response ) )
        {
            $response = new Response();
        }
        $response->setContent( $this->getTemplateEngine()->render( $view, $parameters ) );
        return $response;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/Controller/Controller.php