ezp-next: eZ\Publish\Core\FieldType\Image\ImageStorage Class Reference
eZ\Publish\Core\FieldType\Image\ImageStorage Class Reference
Public Member Functions
__construct (array $gateways, IOService $IOService, PathGenerator $pathGenerator, MetadataHandler $imageSizeMetadataHandler)
storeFieldData (VersionInfo $versionInfo, Field $field, array $context)
getFieldData (VersionInfo $versionInfo, Field $field, array $context)
deleteFieldData (VersionInfo $versionInfo, array $fieldIds, array $context)
hasFieldData ()
getIndexData (VersionInfo $versionInfo, Field $field, array $context)
Public Member Functions inherited from eZ\Publish\Core\FieldType\GatewayBasedStorage
__construct (array $gateways=array())
addGateway ($identifier, StorageGateway $gateway)
copyLegacyField (VersionInfo $versionInfo, Field $field, Field $originalField, array $context)
Protected Member Functions
getFieldPath ($fieldId, $versionNo, $languageCode, $nodePathString)
Protected Member Functions inherited from eZ\Publish\Core\FieldType\GatewayBasedStorage
getGateway (array $context)
Protected Attributes
$IOService
$pathGenerator
$imageSizeMetadataHandler
Protected Attributes inherited from eZ\Publish\Core\FieldType\GatewayBasedStorage
$gateways
Detailed Description
Converter for Image field type external storage
The keyword storage ships a list (array) of keywords in $field->value->externalData. $field->value->data is simply empty, because no internal data is store.
Definition at line 26 of file ImageStorage.php.
Constructor & Destructor Documentation
eZ\Publish\Core\FieldType\Image\ImageStorage::__construct (array $gateways, IOService $IOService, PathGenerator $pathGenerator, MetadataHandler $imageSizeMetadataHandler)
Construct from gateways
Parameters
\eZ\Publish\Core\FieldType\StorageGateway[] $gateways
IOService $IOService
PathGenerator $imageSizeMetadataHandler
MetadataHandler $pathGenerator
Definition at line 53 of file ImageStorage.php.
References eZ\Publish\Core\FieldType\Image\ImageStorage\$imageSizeMetadataHandler, eZ\Publish\Core\FieldType\Image\ImageStorage\$IOService, and eZ\Publish\Core\FieldType\Image\ImageStorage\$pathGenerator.
    {
        parent::__construct( $gateways );
        $this->IOService = $IOService;
        $this->pathGenerator = $pathGenerator;
        $this->imageSizeMetadataHandler = $imageSizeMetadataHandler;
    }
Member Function Documentation
eZ\Publish\Core\FieldType\Image\ImageStorage::deleteFieldData (VersionInfo $versionInfo, array $fieldIds, array $context)
Parameters
array $fieldIds
array $context
Returns
boolean
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 218 of file ImageStorage.php.
References eZ\Publish\Core\IO\IOService\deleteBinaryFile(), eZ\Publish\Core\IO\IOService\getExternalPath(), eZ\Publish\Core\FieldType\GatewayBasedStorage\getGateway(), and eZ\Publish\Core\IO\IOService\loadBinaryFile().
    {
        $gateway = $this->getGateway( $context );
        $fieldXmls = $gateway->getXmlForImages( $versionInfo->versionNo, $fieldIds );
        foreach ( $fieldXmls as $fieldId => $xml )
        {
            $storedFiles = $this->extractFiles( $xml );
            if ( $storedFiles === null )
            {
                continue;
            }
            foreach ( $storedFiles as $storedFilePath )
            {
                $gateway->removeImageReferences( $storedFilePath, $versionInfo->versionNo, $fieldId );
                if ( $gateway->countImageReferences( $storedFilePath ) === 0 )
                {
                    $localPath = $this->IOService->getExternalPath( $storedFilePath );
                    $binaryFile = $this->IOService->loadBinaryFile( $localPath );
                    $this->IOService->deleteBinaryFile( $binaryFile );
                }
            }
        }
    }
eZ\Publish\Core\FieldType\Image\ImageStorage::getFieldData (VersionInfo $versionInfo, Field $field, array $context)
Populates $field value property based on the external data. $field->value is a eZ object. This value holds the data as a eZ based object, according to the field type (e.g. for TextLine, it will be a eZ object).
Parameters
\eZ\Publish\SPI\Persistence\Content\VersionInfo $versionInfo
\eZ\Publish\SPI\Persistence\Content\Field $field
array $context
Exceptions
NotFoundException If the stored image path couldn't be retrieved by the IOService
Returns
void
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 198 of file ImageStorage.php.
References eZ\Publish\Core\IO\IOService\getExternalPath(), and eZ\Publish\Core\IO\IOService\loadBinaryFile().
    {
        if ( $field->value->data !== null )
        {
            $path = $this->IOService->getExternalPath( $field->value->data['path'] );
            if ( ( $binaryFile = $this->IOService->loadBinaryFile( $path ) ) === false )
            {
                throw new NotFoundException( '$field->value->data[path]', $path );
            }
            $field->value->data['fileSize'] = $binaryFile->size;
        }
    }
eZ\Publish\Core\FieldType\Image\ImageStorage::getFieldPath ($fieldId, $versionNo, $languageCode, $nodePathString) protected
Returns the path where images for the defined $fieldId are stored
Parameters
mixed $fieldId
int $versionNo
string $languageCode
string $nodePathString
Returns
string
Definition at line 174 of file ImageStorage.php.
    {
        return $this->pathGenerator->getStoragePathForField(
            $fieldId,
            $versionNo,
            $languageCode,
            $nodePathString
        );
    }
eZ\Publish\Core\FieldType\Image\ImageStorage::getIndexData (VersionInfo $versionInfo, Field $field, array $context)
Parameters
\eZ\Publish\SPI\Persistence\Content\Field $field
array $context
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 299 of file ImageStorage.php.
    {
        // @todo: Correct?
        return null;
    }
eZ\Publish\Core\FieldType\Image\ImageStorage::hasFieldData ()
Checks if field type has external data to deal with
Returns
boolean
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 290 of file ImageStorage.php.
    {
        return true;
    }
eZ\Publish\Core\FieldType\Image\ImageStorage::storeFieldData (VersionInfo $versionInfo, Field $field, array $context)
See Also
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 96 of file ImageStorage.php.
References eZ\Publish\Core\IO\IOService\createBinaryFile(), eZ\Publish\Core\IO\IOService\getExternalPath(), eZ\Publish\Core\FieldType\Image\ImageStorage\getFieldPath(), eZ\Publish\Core\FieldType\GatewayBasedStorage\getGateway(), eZ\Publish\Core\IO\IOService\getInternalPath(), eZ\Publish\Core\IO\IOService\loadBinaryFile(), and eZ\Publish\Core\IO\IOService\newBinaryCreateStructFromLocalFile().
    {
        /*$storedValue = isset( $field->value->externalData )
            // New image
            ? $field->value->externalData
            // Copied / updated image
            : $field->value->data;*/
        $contentMetaData = array(
            'fieldId' => $field->id,
            'versionNo' => $versionInfo->versionNo,
            'languageCode' => $field->languageCode,
        );
        // new image
        if ( isset( $field->value->externalData ) )
        {
            $targetPath = $this->getFieldPath(
                $field->id,
                $versionInfo->versionNo,
                $field->languageCode,
                $this->getGateway( $context )->getNodePathString( $versionInfo, $field->id )
            ) . '/' . $field->value->externalData['fileName'];
            if ( !$binaryFile = $this->IOService->loadBinaryFile( $targetPath ) )
            {
                $binaryFileCreateStruct = $this->IOService->newBinaryCreateStructFromLocalFile(
                    $field->value->externalData['path']
                );
                $binaryFileCreateStruct->uri = $targetPath;
                $binaryFile = $this->IOService->createBinaryFile( $binaryFileCreateStruct );
            }
            $field->value->externalData['path'] = $this->IOService->getInternalPath( $binaryFile->uri );
            $field->value->externalData['mimeType'] = $binaryFile->mimeType;
            $field->value->data = array_merge(
                $field->value->externalData,
                $this->IOService->getMetadata( $this->imageSizeMetadataHandler, $binaryFile ),
                $contentMetaData
            );
            $field->value->externalData = null;
        }
        // existing image
        else
        {
            if ( $field->value->data === null )
            {
                // Store empty value only with content meta data
                $field->value->data = $contentMetaData;
                return true;
            }
            $binaryFile = $this->IOService->loadBinaryFile( $this->IOService->getExternalPath( $field->value->data['path'] ) );
            $field->value->data = array_merge(
                $field->value->data,
                $this->IOService->getMetadata( $this->imageSizeMetadataHandler, $binaryFile ),
                $contentMetaData
            );
            $field->value->externalData = null;
        }
        $this->getGateway( $context )->storeImageReference( $field->value->data['path'], $field->id );
        // Data has been updated and needs to be stored!
        return true;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\Image\ImageStorage::$imageSizeMetadataHandler protected
Definition at line 43 of file ImageStorage.php.
eZ\Publish\Core\FieldType\Image\ImageStorage::$IOService protected
Definition at line 33 of file ImageStorage.php.
eZ\Publish\Core\FieldType\Image\ImageStorage::$pathGenerator protected
Definition at line 40 of file ImageStorage.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Image/ImageStorage.php