ezp-next: eZ\Publish\Core\Persistence\Legacy\User\Mapper Class Reference
eZ\Publish\Core\Persistence\Legacy\User\Mapper Class Reference
Public Member Functions
mapUser (array $data)
mapUsers (array $data)
mapRole (array $data)
mapRoles (array $data, $indexById=false)
mapRoleAssignments (array $data, array $roleData)
Detailed Description
mapper for User related objects
Definition at line 19 of file Mapper.php.
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\User\Mapper::mapRole (array $data)
Map role data to a role
Parameters
array $data
Returns
Definition at line 119 of file Mapper.php.
    {
        $role = new Role();
        foreach ( $data as $row )
        {
            if ( empty( $role->id ) )
            {
                $role->id = (int)$row['ezrole_id'];
                $role->identifier = $row['ezrole_name'];
                // skip name and description as they don't exist in legacy
            }
            $role->groupIds[] = $row['ezuser_role_contentobject_id'];
        }
        // Remove duplicates and sanitize arrays
        $role->groupIds = array_values( array_unique( array_filter( $role->groupIds ) ) );
        $role->policies = $this->mapPolicies( $data );
        return $role;
    }
eZ\Publish\Core\Persistence\Legacy\User\Mapper::mapRoleAssignments (array $data, array $roleData)
Map data for a set of role assignments
Parameters
array $data
Returns
[]
Definition at line 177 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\User\Mapper\mapRoles().
    {
        $roles = $this->mapRoles( $roleData, true );
        $roleAssignmentData = array();
        foreach ( $data as $row )
        {
            $roleId = (int)$row['role_id'];
            $contentId = (int)$row['contentobject_id'];
             // if user already have full access to a role, continue
            if ( isset( $roleAssignmentData[$roleId][$contentId] )
              && $roleAssignmentData[$roleId][$contentId] instanceof RoleAssignment )
                continue;
            $limitIdentifier = $row['limit_identifier'];
            if ( !empty( $limitIdentifier ) )
            {
                if ( !isset( $roleAssignmentData[$roleId][$contentId][$limitIdentifier] ) )
                {
                    $roleAssignmentData[$roleId][$contentId][$limitIdentifier] = new RoleAssignment(
                        array(
                            'role' => $roles[$roleId],
                            'contentId' => $contentId,
                            'limitationIdentifier' => $limitIdentifier,
                            'values' => array( $row['limit_value'] )
                        )
                    );
                }
                else
                {
                    $roleAssignmentData[$roleId][$contentId][$limitIdentifier]->values[] = $row['limit_value'];
                }
            }
            else
            {
                $roleAssignmentData[$roleId][$contentId] = new RoleAssignment(
                    array(
                        'role' => $roles[$roleId],
                        'contentId' => $contentId
                    )
                );
            }
        }
        $roleAssignments = array();
        array_walk_recursive(
            $roleAssignmentData,
            function( $roleAssignment ) use ( &$roleAssignments )
            {
                $roleAssignments[] = $roleAssignment;
            }
        );
        return $roleAssignments;
    }
eZ\Publish\Core\Persistence\Legacy\User\Mapper::mapRoles (array $data, $indexById = false)
Map data for a set of roles
Parameters
array $data
boolean $indexById
Returns
[]
Definition at line 150 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\User\Mapper\mapRole().
    {
        $roleData = array();
        foreach ( $data as $row )
        {
            $roleData[$row['ezrole_id']][] = $row;
        }
        $roles = array();
        foreach ( $roleData as $id => $data )
        {
            if ( $indexById )
                $roles[$id] = $this->mapRole( $data );
            else
                $roles[] = $this->mapRole( $data );
        }
        return $roles;
    }
eZ\Publish\Core\Persistence\Legacy\User\Mapper::mapUser (array $data)
Map user data into user object
Parameters
array $data
Returns
Definition at line 28 of file Mapper.php.
    {
        $user = new User();
        $user->id = $data['contentobject_id'];
        $user->login = $data['login'];
        $user->email = $data['email'];
        $user->passwordHash = $data['password_hash'];
        $user->hashAlgorithm = $data['password_hash_type'];
        $user->isEnabled = (bool)$data['is_enabled'];
        $user->maxLogin = $data['max_login'];
        return $user;
    }
eZ\Publish\Core\Persistence\Legacy\User\Mapper::mapUsers (array $data)
Map data for a set of user data
Parameters
array $data
Returns
[]
Definition at line 49 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\User\Mapper\mapUser().
    {
        $users = array();
        foreach ( $data as $row )
        {
            $users[] = $this->mapUser( $row );
        }
        return $users;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/User/Mapper.php