ezp-next: eZ\Publish\Core\FieldType\FileService\LocalFileService Class Reference
eZ\Publish\Core\FieldType\FileService\LocalFileService Class Reference
Public Member Functions
__construct ($installDir, $storageDir, $identifierPrefix= '')
storeFile ($sourcePath, $storageIdentifier)
remove ($storageIdentifier, $recursive=false)
getStorageIdentifier ($path)
getMetaData ($storageIdentifier)
getFileSize ($storageIdentifier)
exists ($storageIdentifier)
Protected Member Functions
getFullPath ($path, $allowLocal=false)
removePathInternal ($path, $recursive)
createDirectoryRecursive ($directory)
Protected Attributes
$installDir
$storageDir
$identifierPrefix
Detailed Description
Definition at line 15 of file LocalFileService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\FieldType\FileService\LocalFileService::__construct ($installDir, $storageDir, $identifierPrefix = '')
Parameters
string $installDir
string $siteName
Definition at line 43 of file LocalFileService.php.
References eZ\Publish\Core\FieldType\FileService\LocalFileService\$identifierPrefix, eZ\Publish\Core\FieldType\FileService\LocalFileService\$installDir, eZ\Publish\Core\FieldType\FileService\LocalFileService\$storageDir, and eZ\Publish\Core\FieldType\FileService\LocalFileService\__construct().
    {
        $this->installDir = $installDir;
        $this->storageDir = $storageDir;
        $this->identifierPrefix = $identifierPrefix;
    }
Member Function Documentation
eZ\Publish\Core\FieldType\FileService\LocalFileService::createDirectoryRecursive ($directory) protected
Creates the given directory recursively
Parameters
string $directory
Exceptions
RuntimeException if the $directory could not be created
Returns
void
Definition at line 275 of file LocalFileService.php.
References eZ\Publish\Core\FieldType\FileService\LocalFileService\createDirectoryRecursive().
    {
        if ( is_dir( $directory ) )
        {
            return;
        }
        if ( $directory === '' )
        {
            throw new RuntimeException( "Unable to create empty directory!" );
        }
        $this->createDirectoryRecursive( dirname( $directory ) );
        $result = @mkdir( $directory, 0775 );
        if ( false === $result )
        {
            throw new RuntimeException( "Could not create directory '{$directory}'." );
        }
        $chmodResult = @chmod( $directory, 0775 );
        if ( false === $chmodResult )
        {
            throw new RuntimeException(
                "Could not set permissions 0775 on directory '{$directory}'."
            );
        }
    }
eZ\Publish\Core\FieldType\FileService\LocalFileService::exists ($storageIdentifier)
Returns is a file/directory with the given $storageIdentifier exists
Parameters
string $storageIdentifier
Returns
boolean
Implements eZ\Publish\Core\FieldType\FileService.
Definition at line 261 of file LocalFileService.php.
References eZ\Publish\Core\FieldType\FileService\LocalFileService\getFullPath().
    {
        return file_exists( $this->getFullPath( $storageIdentifier ) );
    }
eZ\Publish\Core\FieldType\FileService\LocalFileService::getFileSize ($storageIdentifier)
Returns the file size of the file identified by $storageIdentifier
Parameters
string $storageIdentifier
Returns
int
Implements eZ\Publish\Core\FieldType\FileService.
Definition at line 247 of file LocalFileService.php.
References eZ\Publish\Core\FieldType\FileService\LocalFileService\getFullPath().
    {
        return filesize(
            $this->getFullPath( $storageIdentifier )
        );
    }
eZ\Publish\Core\FieldType\FileService\LocalFileService::getFullPath ($path, $allowLocal = false) protected
Returns the full path for $path
Parameters
string $path
Returns
string
Definition at line 57 of file LocalFileService.php.
References eZ\Publish\Core\FieldType\FileService\LocalFileService\getFullPath().
    {
        if ( $allowLocal && substr( $path, 0, 1 ) === '/' )
        {
            return $path;
        }
        return $this->installDir . '/' . ( !empty( $this->storageDir ) ? $this->storageDir . '/' : '' ) . $path;
    }
eZ\Publish\Core\FieldType\FileService\LocalFileService::getMetaData ($storageIdentifier)
Returns a hash of meta data
array('width' => <int>, 'height' => <int>, 'mime' => <string>,);
Parameters
string $storageIdentifier
Returns
array
Implements eZ\Publish\Core\FieldType\FileService.
Definition at line 228 of file LocalFileService.php.
References eZ\Publish\Core\FieldType\FileService\LocalFileService\getFullPath().
    {
        // Does not depend on GD
        $metaData = getimagesize( $this->getFullPath( $storageIdentifier ) );
        return array(
            'width' => $metaData[0],
            'height' => $metaData[1],
            'mime' => $metaData['mime'],
        );
    }
eZ\Publish\Core\FieldType\FileService\LocalFileService::getStorageIdentifier ($path)
Returns a storage identifier for the given $path
The storage identifier is used to identify $path inside the storage encapsulated by the file service.
Parameters
string $path
Returns
string
Implements eZ\Publish\Core\FieldType\FileService.
Definition at line 208 of file LocalFileService.php.
    {
        return ( !empty( $this->identifierPrefix )
            ? $this->identifierPrefix . '/'
            : '' ) . $path;
    }
eZ\Publish\Core\FieldType\FileService\LocalFileService::remove ($storageIdentifier, $recursive = false)
Removes the path identified by $storageIdentifier, potentially $recursive.
Attempts to removed the path identified by $storageIdentifier. If $storageIdentifier is a directory which is not empty and $recursive is set to false, an exception is thrown. Attempting to remove a non existing $storageIdentifier is silently ignored.
Parameters
string $storageIdentifier
boolean $recursive
Returns
void
Exceptions
\RuntimeException if children of $storageIdentifier exist and $recursive is false
\RuntimeException if $storageIdentifier could not be removed (most likely permission issues)
Implements eZ\Publish\Core\FieldType\FileService.
Definition at line 137 of file LocalFileService.php.
References eZ\Publish\Core\FieldType\FileService\LocalFileService\getFullPath(), and eZ\Publish\Core\FieldType\FileService\LocalFileService\removePathInternal().
    {
        $fullPath = $this->getFullPath( $storageIdentifier );
        $this->removePathInternal( $fullPath, $recursive );
    }
eZ\Publish\Core\FieldType\FileService\LocalFileService::removePathInternal ($path, $recursive) protected
Deletes $path, $recursive or not
Parameters
string $path
boolean $recursive
Returns
void
Exceptions
RuntimeException if $path is a non-empty directory and $recursive is false
RuntimeException if error occurs during removal
Definition at line 155 of file LocalFileService.php.
References eZ\Publish\Core\FieldType\FileService\LocalFileService\removePathInternal().
    {
        if ( is_dir( $path ) )
        {
            $iterator = new \FilesystemIterator(
                $path,
                \FilesystemIterator::CURRENT_AS_FILEINFO | \FilesystemIterator::KEY_AS_PATHNAME | \FileSystemIterator::SKIP_DOTS
            );
            foreach ( $iterator as $childPath => $fileInfo )
            {
                if ( !$recursive )
                {
                    throw new RuntimeException(
                        sprintf(
                            'Cannot remove "%s", because directory is not empty.',
                            $path
                        )
                    );
                }
                $this->removePathInternal( $childPath, $recursive );
            }
            $rmdirResult = @rmdir( $path );
            if ( false === $rmdirResult )
            {
                throw new RuntimeException(
                    sprintf( 'Could not remove directory "%s"', $path )
                );
            }
        }
        else if ( is_file( $path ) )
        {
            $unlinkResult = @unlink( $path );
            if ( false === $unlinkResult )
            {
                throw new RuntimeException(
                    sprintf( 'Could not remove file "%s"', $path )
                );
            }
        }
        // If target does not exist, ignore it
    }
eZ\Publish\Core\FieldType\FileService\LocalFileService::storeFile ($sourcePath, $storageIdentifier)
Store the local file identified by $sourcePath in a location that corresponds to $storageIdentifier. Returns an $storageIdentifier again.
Parameters
string $sourcePath
string $storageIdentifier
Returns
string
Implements eZ\Publish\Core\FieldType\FileService.
Definition at line 75 of file LocalFileService.php.
References eZ\Publish\Core\FieldType\FileService\LocalFileService\createDirectoryRecursive(), and eZ\Publish\Core\FieldType\FileService\LocalFileService\getFullPath().
    {
        $fullSourcePath = $this->getFullPath( $sourcePath, true );
        $fullTargetPath = $this->getFullPath( $storageIdentifier );
        if ( $fullSourcePath == $fullTargetPath )
        {
            // Updating the field, no copy needed
            return $storageIdentifier;
        }
        $this->createDirectoryRecursive(
            dirname( $fullTargetPath )
        );
        $copyResult = copy( $fullSourcePath, $fullTargetPath );
        if ( false === $copyResult )
        {
            throw new RuntimeException(
                sprintf(
                    'Could not copy "%s" to "%s"',
                    $fullSourcePath,
                    $fullTargetPath
                )
            );
        }
        $chmodResult = chmod( $fullTargetPath, 0664 );
        if ( false === $chmodResult )
        {
            throw new RuntimeException(
                sprintf(
                    'Could not change permissions of "%s" to "%s"',
                    $fullTargetPath,
                    '0644'
                )
            );
        }
        return $storageIdentifier;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\FileService\LocalFileService::$identifierPrefix protected
Definition at line 37 of file LocalFileService.php.
eZ\Publish\Core\FieldType\FileService\LocalFileService::$installDir protected
Definition at line 22 of file LocalFileService.php.
eZ\Publish\Core\FieldType\FileService\LocalFileService::$storageDir protected
Definition at line 29 of file LocalFileService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/FileService/LocalFileService.php