ezp-next: eZ\Publish\Core\REST\Server\Controller\ContentType Class Reference
eZ\Publish\Core\REST\Server\Controller\ContentType Class Reference
Public Member Functions
__construct (ContentTypeService $contentTypeService)
createContentTypeGroup ()
updateContentTypeGroup ()
deleteContentTypeGroup ()
listContentTypesForGroup ()
loadContentTypeGroupList ()
loadContentTypeGroup ()
loadContentType ()
listContentTypes ()
loadContentTypeByIdentifier ()
loadContentTypeByRemoteId ()
createContentType ()
copyContentType ()
createContentTypeDraft ()
loadContentTypeDraft ()
updateContentTypeDraft ()
addFieldDefinition ()
loadFieldDefinitionList ()
loadFieldDefinition ()
loadDraftFieldDefinitionList ()
loadDraftFieldDefinition ()
updateFieldDefinition ()
removeFieldDefinition ()
publishContentTypeDraft ()
deleteContentType ()
deleteContentTypeDraft ()
loadGroupsOfContentType ()
linkContentTypeToGroup ()
unlinkContentTypeFromGroup ()
Public Member Functions inherited from eZ\Publish\Core\REST\Server\Controller
setInputDispatcher (InputDispatcher $inputDispatcher)
setUrlHandler (UrlHandler $urlHandler)
setRequest (HttpRequest $request)
setContainer (Container $container)
Protected Attributes
$contentTypeService
Protected Attributes inherited from eZ\Publish\Core\REST\Server\Controller
$request
$inputDispatcher
$urlHandler
$container
Detailed Description
ContentType controller
Definition at line 29 of file ContentType.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Server\Controller\ContentType::__construct (ContentTypeService $contentTypeService)
Construct controller
Parameters
\eZ\Publish\API\Repository\ContentTypeService $contentTypeService
Definition at line 43 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\__construct().
    {
        $this->contentTypeService = $contentTypeService;
    }
Member Function Documentation
eZ\Publish\Core\REST\Server\Controller\ContentType::addFieldDefinition ()
Creates a new field definition for the given content type
Returns
Definition at line 438 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\addFieldDefinition().
    {
        $urlValues = $this->urlHandler->parse( 'typeFieldDefinitionsDraft', $this->request->path );
        $contentTypeDraft = $this->contentTypeService->loadContentTypeDraft( $urlValues['type'] );
        $fieldDefinitionCreate = $this->inputDispatcher->parse(
            new Message(
                array(
                    'Content-Type' => $this->request->contentType,
                ),
                $this->request->body
            )
        );
        try
        {
            $this->contentTypeService->addFieldDefinition(
                $contentTypeDraft,
                $fieldDefinitionCreate
            );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        $updatedDraft = $this->contentTypeService->loadContentTypeDraft( $urlValues['type'] );
        foreach ( $updatedDraft->getFieldDefinitions() as $fieldDefinition )
        {
            if ( $fieldDefinition->identifier == $fieldDefinitionCreate->identifier )
            {
                return new Values\CreatedFieldDefinition(
                    array(
                        'fieldDefinition' => new Values\RestFieldDefinition(
                            $updatedDraft, $fieldDefinition
                        )
                    )
                );
            }
        }
        throw new Exceptions\NotFoundException( "Field definition not found: '{$this->request->path}'." );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::copyContentType ()
Copies a content type. The identifier of the copy is changed to copy_of_<identifier> and a new remoteId is generated.
Returns
Definition at line 310 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\copyContentType().
    {
        $urlValues = $this->urlHandler->parse( 'type', $this->request->path );
        $copiedContentType = $this->contentTypeService->copyContentType(
            $this->contentTypeService->loadContentType( $urlValues['type'] )
        );
        return new Values\ResourceCreated(
            $this->urlHandler->generate( 'type', array( 'type' => $copiedContentType->id ) )
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::createContentType ()
Creates a new content type draft in the given content type group
Returns
Definition at line 250 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\createContentType().
    {
        $questionMarkPosition = strpos( $this->request->path, '?' );
        $urlValues = $this->urlHandler->parse(
            'grouptypes',
            $questionMarkPosition !== false ? substr( $this->request->path, 0, $questionMarkPosition ) : $this->request->path
        );
        $contentTypeGroup = $this->contentTypeService->loadContentTypeGroup( $urlValues['typegroup'] );
        try
        {
            $contentTypeDraft = $this->contentTypeService->createContentType(
                $this->inputDispatcher->parse(
                    new Message(
                        array(
                            'Content-Type' => $this->request->contentType,
                        ),
                        $this->request->body
                    )
                ),
                array( $contentTypeGroup )
            );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        if ( isset( $this->request->variables['publish'] ) && $this->request->variables['publish'] === 'true' )
        {
            $this->contentTypeService->publishContentTypeDraft( $contentTypeDraft, 'bla' );
            $contentType = $this->contentTypeService->loadContentType( $contentTypeDraft->id );
            return new Values\CreatedContentType(
                array(
                    'contentType' => new Values\RestContentType(
                        $contentType,
                        $contentType->getFieldDefinitions()
                    )
                )
            );
        }
        return new Values\CreatedContentType(
            array(
                'contentType' => new Values\RestContentType(
                    $contentTypeDraft,
                    $contentTypeDraft->getFieldDefinitions()
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::createContentTypeDraft ()
Creates a draft and updates it with the given data
Returns
Definition at line 328 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\createContentTypeDraft().
    {
        $urlValues = $this->urlHandler->parse( 'type', $this->request->path );
        $contentType = $this->contentTypeService->loadContentType( $urlValues['type'] );
        try
        {
            $contentTypeDraft = $this->contentTypeService->createContentTypeDraft(
                $contentType
            );
        }
        catch ( BadStateException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        $contentTypeUpdateStruct = $this->inputDispatcher->parse(
            new Message(
                array(
                    'Content-Type' => $this->request->contentType,
                ),
                $this->request->body
            )
        );
        try
        {
            $this->contentTypeService->updateContentTypeDraft(
                $contentTypeDraft,
                $contentTypeUpdateStruct
            );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        return new Values\CreatedContentType(
            array(
                'contentType' => new Values\RestContentType(
                    // Reload the content type draft to get the updated values
                    $this->contentTypeService->loadContentTypeDraft(
                        $contentTypeDraft->id
                    )
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::createContentTypeGroup ()
Creates a new content type group
Returns
Definition at line 53 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\createContentTypeGroup().
    {
        $createStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        try
        {
            return new Values\CreatedContentTypeGroup(
                array(
                    'contentTypeGroup' => $this->contentTypeService->createContentTypeGroup( $createStruct )
                )
            );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::deleteContentType ()
The given content type is deleted
Returns
Definition at line 690 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\deleteContentType().
    {
        $urlValues = $this->urlHandler->parse( 'type', $this->request->path );
        $contentType = $this->contentTypeService->loadContentType( $urlValues['type'] );
        try
        {
            $this->contentTypeService->deleteContentType( $contentType );
        }
        catch ( BadStateException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::deleteContentTypeDraft ()
The given content type draft is deleted
Returns
Definition at line 713 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\deleteContentTypeDraft().
    {
        $urlValues = $this->urlHandler->parse( 'typeDraft', $this->request->path );
        $contentTypeDraft = $this->contentTypeService->loadContentTypeDraft( $urlValues['type'] );
        $this->contentTypeService->deleteContentType( $contentTypeDraft );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::deleteContentTypeGroup ()
The given content type group is deleted
Returns
Definition at line 112 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\deleteContentTypeGroup().
    {
        $urlValues = $this->urlHandler->parse( 'typegroup', $this->request->path );
        $contentTypeGroup = $this->contentTypeService->loadContentTypeGroup( $urlValues['typegroup'] );
        $contentTypes = $this->contentTypeService->loadContentTypes( $contentTypeGroup );
        if ( !empty( $contentTypes ) )
        {
            throw new ForbiddenException( 'Only empty content type groups can be deleted' );
        }
        $this->contentTypeService->deleteContentTypeGroup( $contentTypeGroup );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::linkContentTypeToGroup ()
Links a content type group to the content type and returns the updated group list
Returns
Definition at line 744 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\linkContentTypeToGroup().
    {
        $questionMarkPosition = strpos( $this->request->path, '?' );
        $urlValues = $this->urlHandler->parse(
            'groupsOfType',
            $questionMarkPosition !== false ? substr( $this->request->path, 0, $questionMarkPosition ) : $this->request->path
        );
        $contentType = $this->contentTypeService->loadContentType( $urlValues['type'] );
        try
        {
            $groupValues = $this->urlHandler->parse( 'typegroup', $this->request->variables['group'] );
        }
        catch ( Exceptions\InvalidArgumentException $e )
        {
            // Group URI does not match the required value
            throw new BadRequestException( $e->getMessage() );
        }
        $contentTypeGroup = $this->contentTypeService->loadContentTypeGroup( $groupValues['typegroup'] );
        $existingContentTypeGroups = $contentType->getContentTypeGroups();
        $contentTypeInGroup = false;
        foreach ( $existingContentTypeGroups as $existingGroup )
        {
            if ( $existingGroup->id == $contentTypeGroup->id )
            {
                $contentTypeInGroup = true;
                break;
            }
        }
        if ( $contentTypeInGroup )
        {
            throw new ForbiddenException( 'Content type is already linked to provided group' );
        }
        $this->contentTypeService->assignContentTypeGroup(
            $contentType,
            $contentTypeGroup
        );
        $existingContentTypeGroups[] = $contentTypeGroup;
        return new Values\ContentTypeGroupRefList(
            $contentType,
            $existingContentTypeGroups
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::listContentTypes ()
Returns a list of content types
Returns
|
Definition at line 196 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\listContentTypes(), eZ\Publish\Core\REST\Server\Controller\ContentType\loadContentTypeByIdentifier(), and eZ\Publish\Core\REST\Server\Controller\ContentType\loadContentTypeByRemoteId().
    {
        $contentTypes = array();
        if ( isset( $this->request->variables['identifier'] ) )
        {
            $contentTypes = array(
                $this->loadContentTypeByIdentifier()
            );
        }
        else if ( isset( $this->request->variables['remoteId'] ) )
        {
            $contentTypes = array(
                $this->loadContentTypeByRemoteId()
            );
        }
        if ( $this->getMediaType( $this->request ) == 'application/vnd.ez.api.contenttypelist' )
        {
            return new Values\ContentTypeList( $contentTypes, $this->request->path );
        }
        return new Values\ContentTypeInfoList( $contentTypes, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::listContentTypesForGroup ()
Returns a list of content types of the group
Returns
|
Definition at line 134 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\listContentTypesForGroup().
    {
        $urlValues = $this->urlHandler->parse( 'grouptypes', $this->request->path );
        $contentTypes = $this->contentTypeService->loadContentTypes(
            $this->contentTypeService->loadContentTypeGroup( $urlValues['typegroup'] )
        );
        if ( $this->getMediaType( $this->request ) == 'application/vnd.ez.api.contenttypelist' )
        {
            return new Values\ContentTypeList( $contentTypes, $this->request->path );
        }
        return new Values\ContentTypeInfoList( $contentTypes, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::loadContentType ()
Loads a content type
Returns
Definition at line 179 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\loadContentType().
    {
        $urlValues = $this->urlHandler->parse( 'type', $this->request->path );
        $contentType = $this->contentTypeService->loadContentType( $urlValues['type'] );
        return new Values\RestContentType(
            $contentType,
            $contentType->getFieldDefinitions()
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::loadContentTypeByIdentifier ()
Loads a content type by its identifier
Returns
Definition at line 226 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\loadContentTypeByIdentifier().
    {
        return $this->contentTypeService->loadContentTypeByIdentifier(
            $this->request->variables['identifier']
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::loadContentTypeByRemoteId ()
Loads a content type by its remote ID
Returns
Definition at line 238 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\loadContentTypeByRemoteId().
    {
        return $this->contentTypeService->loadContentTypeByRemoteId(
            $this->request->variables['remoteId']
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::loadContentTypeDraft ()
Loads a content type draft
Returns
Definition at line 382 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\loadContentTypeDraft().
    {
        $urlValues = $this->urlHandler->parse( 'typeDraft', $this->request->path );
        $contentTypeDraft = $this->contentTypeService->loadContentTypeDraft( $urlValues['type'] );
        return new Values\RestContentType(
            $contentTypeDraft,
            $contentTypeDraft->getFieldDefinitions()
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::loadContentTypeGroup ()
Returns the content type group given by id
Returns
Definition at line 167 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\loadContentTypeGroup().
    {
        $urlValues = $this->urlHandler->parse( 'typegroup', $this->request->path );
        return $this->contentTypeService->loadContentTypeGroup( $urlValues['typegroup'] );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::loadContentTypeGroupList ()
Returns a list of all content type groups
Returns
Definition at line 155 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\loadContentTypeGroupList().
    {
        return new Values\ContentTypeGroupList(
            $this->contentTypeService->loadContentTypeGroups()
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::loadDraftFieldDefinition ()
Returns the draft field definition given by id
Returns
Definition at line 546 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\loadDraftFieldDefinition().
    {
        $urlValues = $this->urlHandler->parse( 'typeFieldDefinitionDraft', $this->request->path );
        $contentTypeDraft = $this->contentTypeService->loadContentTypeDraft( $urlValues['type'] );
        foreach ( $contentTypeDraft->getFieldDefinitions() as $fieldDefinition )
        {
            if ( $fieldDefinition->id == $urlValues['fieldDefinition'] )
            {
                return new Values\RestFieldDefinition(
                    $contentTypeDraft,
                    $fieldDefinition
                );
            }
        }
        throw new Exceptions\NotFoundException( "Field definition not found: '{$this->request->path}'." );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::loadDraftFieldDefinitionList ()
Loads field definitions for a given content type draft
Returns
Definition at line 529 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\loadDraftFieldDefinitionList().
    {
        $urlValues = $this->urlHandler->parse( 'typeFieldDefinitionsDraft', $this->request->path );
        $contentTypeDraft = $this->contentTypeService->loadContentTypeDraft( $urlValues['type'] );
        return new Values\FieldDefinitionList(
            $contentTypeDraft,
            $contentTypeDraft->getFieldDefinitions()
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::loadFieldDefinition ()
Returns the field definition given by id
Returns
Definition at line 504 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\loadFieldDefinition().
    {
        $urlValues = $this->urlHandler->parse( 'typeFieldDefinition', $this->request->path );
        $contentType = $this->contentTypeService->loadContentType( $urlValues['type'] );
        foreach ( $contentType->getFieldDefinitions() as $fieldDefinition )
        {
            if ( $fieldDefinition->id == $urlValues['fieldDefinition'] )
            {
                return new Values\RestFieldDefinition(
                    $contentType,
                    $fieldDefinition
                );
            }
        }
        throw new Exceptions\NotFoundException( "Field definition not found: '{$this->request->path}'." );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::loadFieldDefinitionList ()
Loads field definitions for a given content type
Returns
Definition at line 487 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\loadFieldDefinitionList().
    {
        $urlValues = $this->urlHandler->parse( 'typeFieldDefinitions', $this->request->path );
        $contentType = $this->contentTypeService->loadContentType( $urlValues['type'] );
        return new Values\FieldDefinitionList(
            $contentType,
            $contentType->getFieldDefinitions()
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::loadGroupsOfContentType ()
Returns the content type groups the content type belongs to
Returns
Definition at line 728 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\loadGroupsOfContentType().
    {
        $urlValues = $this->urlHandler->parse( 'groupsOfType', $this->request->path );
        $contentType = $this->contentTypeService->loadContentType( $urlValues['type'] );
        return new Values\ContentTypeGroupRefList(
            $contentType,
            $contentType->getContentTypeGroups()
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::publishContentTypeDraft ()
Publishes a content type draft
Returns
Definition at line 664 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\publishContentTypeDraft().
    {
        $urlValues = $this->urlHandler->parse( 'typeDraft', $this->request->path );
        $contentTypeDraft = $this->contentTypeService->loadContentTypeDraft( $urlValues['type'] );
        $fieldDefinitions = $contentTypeDraft->getFieldDefinitions();
        if ( empty( $fieldDefinitions ) )
        {
            throw new ForbiddenException( 'Empty content type draft cannot be published' );
        }
        $this->contentTypeService->publishContentTypeDraft( $contentTypeDraft );
        $publishedContentType = $this->contentTypeService->loadContentType( $contentTypeDraft->id );
        return new Values\RestContentType(
            $publishedContentType,
            $publishedContentType->getFieldDefinitions()
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::removeFieldDefinition ()
The given field definition is deleted
Returns
Definition at line 631 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\removeFieldDefinition().
    {
        $urlValues = $this->urlHandler->parse( 'typeFieldDefinitionDraft', $this->request->path );
        $contentTypeDraft = $this->contentTypeService->loadContentTypeDraft( $urlValues['type'] );
        $fieldDefinition = null;
        foreach ( $contentTypeDraft->getFieldDefinitions() as $fieldDef )
        {
            if ( $fieldDef->id == $urlValues['fieldDefinition'] )
            {
                $fieldDefinition = $fieldDef;
            }
        }
        if ( $fieldDefinition === null )
        {
            throw new Exceptions\NotFoundException( "Field definition not found: '{$this->request->path}'." );
        }
        $this->contentTypeService->removeFieldDefinition(
            $contentTypeDraft,
            $fieldDefinition
        );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::unlinkContentTypeFromGroup ()
Removes the given group from the content type and returns the updated group list
Returns
Definition at line 799 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\unlinkContentTypeFromGroup().
    {
        $urlValues = $this->urlHandler->parse( 'groupOfType', $this->request->path );
        $contentType = $this->contentTypeService->loadContentType( $urlValues['type'] );
        $contentTypeGroup = $this->contentTypeService->loadContentTypeGroup( $urlValues['group'] );
        $existingContentTypeGroups = $contentType->getContentTypeGroups();
        $contentTypeInGroup = false;
        foreach ( $existingContentTypeGroups as $existingGroup )
        {
            if ( $existingGroup->id == $contentTypeGroup->id )
            {
                $contentTypeInGroup = true;
                break;
            }
        }
        if ( !$contentTypeInGroup )
        {
            throw new Exceptions\NotFoundException( 'Content type is not in the given group' );
        }
        if ( count( $existingContentTypeGroups ) == 1 )
        {
            throw new ForbiddenException( 'Content type cannot be unlinked from the only remaining group' );
        }
        $this->contentTypeService->unassignContentTypeGroup(
            $contentType,
            $contentTypeGroup
        );
        $contentType = $this->contentTypeService->loadContentType( $urlValues['type'] );
        return new Values\ContentTypeGroupRefList(
            $contentType,
            $contentType->getContentTypeGroups()
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::updateContentTypeDraft ()
Updates meta data of a draft. This method does not handle field definitions
Returns
Definition at line 399 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\updateContentTypeDraft().
    {
        $urlValues = $this->urlHandler->parse( 'typeDraft', $this->request->path );
        $contentTypeDraft = $this->contentTypeService->loadContentTypeDraft( $urlValues['type'] );
        $contentTypeUpdateStruct = $this->inputDispatcher->parse(
            new Message(
                array(
                    'Content-Type' => $this->request->contentType,
                ),
                $this->request->body
            )
        );
        try
        {
            $this->contentTypeService->updateContentTypeDraft(
                $contentTypeDraft,
                $contentTypeUpdateStruct
            );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        return new Values\RestContentType(
            // Reload the content type draft to get the updated values
            $this->contentTypeService->loadContentTypeDraft(
                $contentTypeDraft->id
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::updateContentTypeGroup ()
Updates a content type group
Returns
Definition at line 81 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\updateContentTypeGroup().
    {
        $urlValues = $this->urlHandler->parse( 'typegroup', $this->request->path );
        $createStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        try
        {
            $this->contentTypeService->updateContentTypeGroup(
                $this->contentTypeService->loadContentTypeGroup( $urlValues['typegroup'] ),
                $this->mapToGroupUpdateStruct( $createStruct )
            );
            return $this->contentTypeService->loadContentTypeGroup( $urlValues['typegroup'] );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
    }
eZ\Publish\Core\REST\Server\Controller\ContentType::updateFieldDefinition ()
Updates the attributes of a field definition
Returns
Definition at line 571 of file ContentType.php.
References eZ\Publish\Core\REST\Server\Controller\ContentType\updateFieldDefinition().
    {
        $urlValues = $this->urlHandler->parse( 'typeFieldDefinitionDraft', $this->request->path );
        $contentTypeDraft = $this->contentTypeService->loadContentTypeDraft( $urlValues['type'] );
        $fieldDefinitionUpdate = $this->inputDispatcher->parse(
            new Message(
                array(
                    'Content-Type' => $this->request->contentType,
                ),
                $this->request->body
            )
        );
        $fieldDefinition = null;
        foreach ( $contentTypeDraft->getFieldDefinitions() as $fieldDef )
        {
            if ( $fieldDef->id == $urlValues['fieldDefinition'] )
            {
                $fieldDefinition = $fieldDef;
            }
        }
        if ( $fieldDefinition === null )
        {
            throw new Exceptions\NotFoundException( "Field definition not found: '{$this->request->path}'." );
        }
        try
        {
            $this->contentTypeService->updateFieldDefinition(
                $contentTypeDraft,
                $fieldDefinition,
                $fieldDefinitionUpdate
            );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        $updatedDraft = $this->contentTypeService->loadContentTypeDraft( $urlValues['type'] );
        foreach ( $updatedDraft->getFieldDefinitions() as $fieldDef )
        {
            if ( $fieldDef->id == $urlValues['fieldDefinition'] )
            {
                return new Values\RestFieldDefinition(
                    $updatedDraft, $fieldDef
                );
            }
        }
        throw new Exceptions\NotFoundException( "Field definition not found: '{$this->request->path}'." );
    }
Member Data Documentation
eZ\Publish\Core\REST\Server\Controller\ContentType::$contentTypeService protected
Definition at line 36 of file ContentType.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Controller/ContentType.php