ezp-next: eZ\Publish\Core\REST\Common\UrlHandler\Prefixed Class Reference
eZ\Publish\Core\REST\Common\UrlHandler\Prefixed Class Reference
Public Member Functions
__construct ($prefix= '', array $map=array())
generate ($type, array $values=array())
parse ($type, $url)
Protected Attributes
$prefix
Protected Attributes inherited from eZ\Publish\Core\REST\Common\UrlHandler\eZPublish
$map
Protected Attributes inherited from eZ\Publish\Core\REST\Common\UrlHandler\Pattern
$map = array()
$compileCache = array()
Additional Inherited Members
Public Attributes inherited from eZ\Publish\Core\REST\Common\UrlHandler\Pattern
const STANDARD_VARIABLE_REGEX = '\{([A-Za-z-_]+)\}'
const SLASHES_VARIABLE_REGEX = '\{(?:\&\s*)([A-Za-z-_]+)\}'
Protected Member Functions inherited from eZ\Publish\Core\REST\Common\UrlHandler\Pattern
compile ($pattern)
Detailed Description
Definition at line 13 of file Prefixed.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Common\UrlHandler\Prefixed::__construct ($prefix = '', array $map = array())
Definition at line 20 of file Prefixed.php.
References eZ\Publish\Core\REST\Common\UrlHandler\eZPublish\$map, eZ\Publish\Core\REST\Common\UrlHandler\Prefixed\$prefix, and eZ\Publish\Core\REST\Common\UrlHandler\Prefixed\__construct().
    {
        $this->prefix = $prefix;
        parent::__construct( $map );
    }
Member Function Documentation
eZ\Publish\Core\REST\Common\UrlHandler\Prefixed::generate ($type, array $values = array())
Generate a URL of the given type from the specified values
Parameters
string $type
array $values
Returns
string
Reimplemented from eZ\Publish\Core\REST\Common\UrlHandler\Pattern.
Definition at line 26 of file Prefixed.php.
References eZ\Publish\Core\REST\Common\UrlHandler\generate().
    {
        return $this->prefix . parent::generate( $type, $values );
    }
eZ\Publish\Core\REST\Common\UrlHandler\Prefixed::parse ($type, $url)
Parse URL and return the IDs contained in the URL
Parameters
string $type
string $url
Returns
array
Reimplemented from eZ\Publish\Core\REST\Common\UrlHandler\Pattern.
Definition at line 31 of file Prefixed.php.
References eZ\Publish\Core\REST\Common\UrlHandler\parse().
    {
        if ( strpos( $url, $this->prefix ) === 0 )
        {
            $url = substr( $url, strlen( $this->prefix ) );
        }
        return parent::parse( $type, $url );
    }
Member Data Documentation
eZ\Publish\Core\REST\Common\UrlHandler\Prefixed::$prefix protected
Definition at line 18 of file Prefixed.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/UrlHandler/Prefixed.php