ezp-next: eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver Class Reference
eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver Class Reference
Public Member Functions
__construct (\Closure $legacyKernelClosure, $defaultNamespace)
getParameter ($paramName, $namespace=null, $scope=null)
getGroup ($groupName, $namespace=null, $scope=null)
hasParameter ($paramName, $namespace=null, $scope=null)
setDefaultNamespace ($defaultNamespace)
getDefaultNamespace ()
Protected Member Functions
getLegacyKernel ()
Protected Attributes
$legacyKernelClosure
$defaultNamespace
Detailed Description
Configuration resolver for eZ Publish legacy. Will help you get settings from the legacy kernel (old ini files).
// From a controller $legacyResolver = $this->container->get('ezpublish_legacy.config.resolver'); // Get [DebugSettings].DebugOutput from site.ini $debugOutput = $legacyResolver->getParameter('DebugSettings.DebugOutput'); // Get [ImageMagick].ExecutablePath from image.ini $imageMagickPath = $legacyResolver->getParameter('ImageMagick.ExecutablePath', 'image'); // Get [DatabaseSettings].Database from site.ini, for ezdemo_site_admin siteaccess $databaseName = $legacyResolver->getParameter('DatabaseSettings.Database', 'site', 'ezdemo_site_admin');
// Note that the examples above are also applicable for hasParameter().
Definition at line 33 of file LegacyConfigResolver.php.
Constructor & Destructor Documentation
eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver::__construct (\Closure $legacyKernelClosure, $defaultNamespace)
Definition at line 45 of file LegacyConfigResolver.php.
References eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\$defaultNamespace, and eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\__construct().
    {
        $this->legacyKernelClosure = $legacyKernelClosure;
        $this->defaultNamespace = $defaultNamespace;
    }
Member Function Documentation
eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver::getDefaultNamespace ()
Returns the current default namespace.
Returns
string
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 186 of file LegacyConfigResolver.php.
References eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\getDefaultNamespace().
    {
        return $this->defaultNamespace;
    }
eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver::getGroup ($groupName, $namespace = null, $scope = null)
Returns values for $groupName, in $namespace.
Parameters
string $groupName String containing an INI group name.
string $namespace The legacy INI file name, without the suffix (i.e. without ".ini").
string $scope A specific siteaccess to look into. Defaults to the current siteaccess.
Exceptions
\eZ\Publish\Core\MVC\Exception\ParameterNotFoundException
Todo:
Implement in ConfigResolver interface
Returns
array
Definition at line 112 of file LegacyConfigResolver.php.
References eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\getGroup(), and eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\getLegacyKernel().
    {
        $namespace = $namespace ?: $this->defaultNamespace;
        $namespace = str_replace( '.ini', '', $namespace );
        return $this->getLegacyKernel()->runCallback(
            function () use ( $groupName, $namespace, $scope )
            {
                if ( isset( $scope ) )
                {
                    $ini = eZINI::getSiteAccessIni( $scope, "$namespace.ini" );
                }
                else
                {
                    $ini = eZINI::instance( "$namespace.ini" );
                }
                if ( !$ini->hasGroup( $groupName ) )
                    throw new ParameterNotFoundException( $groupName, "$namespace.ini" );
                return $ini->group( $groupName );
            },
            false
        );
    }
eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver::getLegacyKernel () protected
Returns
Definition at line 54 of file LegacyConfigResolver.php.
References eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\getLegacyKernel().
    {
        $kernelClosure = $this->legacyKernelClosure;
        return $kernelClosure();
    }
eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver::getParameter ($paramName, $namespace = null, $scope = null)
Returns value for $paramName, in $namespace.
Parameters
string $paramName String containing dot separated INI group name and param name. Must follow the following format: <iniGroupName>.<paramName>
string $namespace The legacy INI file name, without the suffix (i.e. without ".ini").
string $scope A specific siteaccess to look into. Defaults to the current siteaccess.
Exceptions
\eZ\Publish\Core\MVC\Exception\ParameterNotFoundException
Returns
mixed
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 72 of file LegacyConfigResolver.php.
References eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\getLegacyKernel(), and eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\getParameter().
    {
        $namespace = $namespace ?: $this->defaultNamespace;
        $namespace = str_replace( '.ini', '', $namespace );
        list( $iniGroup, $paramName ) = explode( '.', $paramName, 2 );
        return $this->getLegacyKernel()->runCallback(
            function () use ( $iniGroup, $paramName, $namespace, $scope )
            {
                if ( isset( $scope ) )
                {
                    $ini = eZINI::getSiteAccessIni( $scope, "$namespace.ini" );
                }
                else
                {
                    $ini = eZINI::instance( "$namespace.ini" );
                }
                if ( !$ini->hasVariable( $iniGroup, $paramName ) )
                    throw new ParameterNotFoundException( $paramName, "$namespace.ini" );
                return $ini->variable( $iniGroup, $paramName );
            },
            false
        );
    }
eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver::hasParameter ($paramName, $namespace = null, $scope = null)
Checks if $paramName exists in $namespace
Parameters
string $paramName
string $namespace If null, the default namespace should be used.
string $scope The scope you need $paramName value for.
Returns
boolean
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 147 of file LegacyConfigResolver.php.
References eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\getLegacyKernel(), and eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\hasParameter().
    {
        $namespace = $namespace ?: $this->defaultNamespace;
        $namespace = str_replace( '.ini', '', $namespace );
        list( $iniGroup, $paramName ) = explode( '.', $paramName, 2 );
        return $this->getLegacyKernel()->runCallback(
            function () use ( $iniGroup, $paramName, $namespace, $scope )
            {
                if ( isset( $scope ) )
                {
                    $ini = eZINI::getSiteAccessIni( $scope, "$namespace.ini" );
                }
                else
                {
                    $ini = eZINI::instance( "$namespace.ini" );
                }
                return $ini->hasVariable( $iniGroup, $paramName );
            },
            false
        );
    }
eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver::setDefaultNamespace ($defaultNamespace)
Changes the default namespace to look parameter into.
Parameters
string $defaultNamespace
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 176 of file LegacyConfigResolver.php.
References eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\$defaultNamespace, and eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver\setDefaultNamespace().
    {
        $this->defaultNamespace = $defaultNamespace;
    }
Member Data Documentation
eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver::$defaultNamespace protected
Definition at line 43 of file LegacyConfigResolver.php.
eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver::$legacyKernelClosure protected
Definition at line 38 of file LegacyConfigResolver.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Bundle/EzPublishLegacyBundle/DependencyInjection/Configuration/LegacyConfigResolver.php