ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser Class Reference
Public Member Functions
__construct ($installDir)
parse ($file)
parseString ($string)
Protected Member Functions
tokenize ($string)
filterValues (array $data)
Protected Attributes
$tokenSpecifications = null
$installDir
Detailed Description
Parser for transformation specifications
The transformation specifications look like:
CF = CF... : Map from one char to one or more chars (map) CF - CF = CF... : Map range of chars to one or more chars (replace) CF - CF +- xx : Transpose several chars by value xx (transpose) CF - CF % yy +- xx : Transpose several chars by value xx, yy denotes skip value yy equal to 1 is the same as 'transpose' (transpose-modulo) TI[,TI...] :
CF = Character Format TI = Transform Identifier
Character formats: U+xxxx : Unicode value in hexadecimal xx: Ascii value in hexadecimal remove : Remove character from result, can only be used in destination keep : Keep character as it is, can only be used in destination "xxxx" : Multiple characters as a string, can only be used in destination, \ means \ and " means "
Definition at line 37 of file Parser.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser::__construct ($installDir)
Construct
Parameters
string $installDir Base dir for rule loading
Returns
void
Definition at line 63 of file Parser.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser\$installDir, eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_COMMENT, eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_MAP, eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_REPLACE, eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_SECTION, eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_TRANSPOSE, eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_TRANSPOSE_MODULO, and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_WHITESPACE.
    {
        $this->installDir = $installDir;
        $character = '(?:U\\+[0-9a-fA-F]{4}|remove|keep|[0-9a-fA-F]+|"(?:[^\\\\"]+|\\\\\\\\|\\\\\'|\\\\")*?")';
        $this->tokenSpecifications = array(
            TransformationProcessor::T_COMMENT => '(\\A#(?P<comment>.*)$)m',
            TransformationProcessor::T_WHITESPACE => '(\\A\\s+)',
            TransformationProcessor::T_SECTION => '(\\A(?P<section>[a-z0-9_-]+):\s*$)m',
            TransformationProcessor::T_MAP => '(\\A(?P<src>' . $character . ')\\s*=\\s*(?P<dest>' .  $character . '))',
            TransformationProcessor::T_REPLACE =>
                '(\\A(?P<srcStart>' . $character . ')\\s*-\\s*' .
                '(?P<srcEnd>'   . $character . ')\\s*=\\s*' .
                '(?P<dest>'    .  $character . '))',
            TransformationProcessor::T_TRANSPOSE =>
                '(\\A(?P<srcStart>' . $character . ')\\s*-\\s*' .
                '(?P<srcEnd>'   . $character . ')\\s*' .
                '(?P<op>[+-])\\s*' .
                '(?P<dest>' .     $character . '))',
            TransformationProcessor::T_TRANSPOSE_MODULO =>
                '(\\A(?P<srcStart>' . $character . ')\\s*-\\s*' .
                '(?P<srcEnd>'   . $character . ')\\s*%\\s*' .
                '(?P<modulo>'   . $character . ')\\s*' .
                '(?P<op>[+-])\\s*' .
                '(?P<dest>' . $character . '))',
        );
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser::filterValues (array $data) protected
Filter out numeric array keys
Parameters
array $data
Returns
array
Definition at line 200 of file Parser.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser\filterValues().
    {
        foreach ( $data as $key => $value )
        {
            if ( is_int( $key ) )
            {
                unset( $data[$key] );
            }
        }
        return $data;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser::parse ($file)
Parse the specified transformation file into an AST
Parameters
string $file
Returns
array
Definition at line 99 of file Parser.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser\parse(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser\parseString().
    {
        return $this->parseString(
            file_get_contents(
                $this->installDir . '/' . $file
            )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser::parseString ($string)
Parse the given string into an AST
Parameters
string $string
Returns
array
Definition at line 115 of file Parser.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser\parseString(), eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_COMMENT, eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_SECTION, eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\T_WHITESPACE, and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser\tokenize().
    {
        $tokens = $this->tokenize( $string );
        $tokens = array_filter(
            $tokens,
            function ( $token )
            {
                return !( $token['type'] === TransformationProcessor::T_WHITESPACE ||
                          $token['type'] === TransformationProcessor::T_COMMENT );
            }
        );
        $ast = array();
        $section = null;
        while ( $token = array_shift( $tokens ) )
        {
            if ( $token['type'] === TransformationProcessor::T_SECTION )
            {
                $section = $token['data']['section'];
                continue;
            }
            if ( $section === null )
            {
                throw new RuntimeException( "Expected section." );
            }
            $ast[$section][] = $token;
        }
        return $ast;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser::tokenize ($string) protected
Tokenize transformation input file
Returns an array of tokens
Parameters
string $string
Returns
array
Definition at line 158 of file Parser.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser\filterValues(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser\tokenize().
    {
        $string = preg_replace( '(\\r\\n|\\r)', "\n", $string );
        $tokens = array();
        $line = 1;
        while ( strlen( $string ) )
        {
            foreach ( $this->tokenSpecifications as $token => $regexp )
            {
                if ( !preg_match( $regexp, $string, $matches ) )
                {
                    continue;
                }
                // Remove matched string
                $string = substr( $string, strlen( $matches[0] ) );
                $line += substr_count( $matches[0], "\n" );
                // Append token to list
                $tokens[] = array(
                    'type' => $token,
                    'data' => $this->filterValues( $matches ),
                );
                // Continue with outer loop
                continue 2;
            }
            throw new RuntimeException( "Parse error in line $line: " . substr( $string, 0, 100 ) );
        }
        return $tokens;
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser::$installDir protected
Definition at line 54 of file Parser.php.
eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor\DefinitionBased\Parser::$tokenSpecifications = null protected
Definition at line 47 of file Parser.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Search/TransformationProcessor/DefinitionBased/Parser.php