ezp-next: eZ\Publish\Core\REST\Client\FieldTypeService Class Reference
eZ\Publish\Core\REST\Client\FieldTypeService Class Reference
Public Member Functions
__construct (array $fieldTypes=array())
addFieldType (FieldType $fieldType)
getFieldTypes ()
getFieldType ($identifier)
hasFieldType ($identifier)
Protected Attributes
$fieldTypes = array()
Detailed Description
Definition at line 15 of file FieldTypeService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Client\FieldTypeService::__construct (array $fieldTypes = array())
Parameters
\eZ\Publish\Core\REST\Client\FieldType[] $fieldTypes
Returns
void
Definition at line 29 of file FieldTypeService.php.
References eZ\Publish\Core\REST\Client\FieldTypeService\$fieldTypes, and eZ\Publish\Core\REST\Client\FieldTypeService\addFieldType().
    {
        foreach ( $fieldTypes as $fieldType )
        {
            $this->addFieldType( $fieldType );
        }
    }
Member Function Documentation
eZ\Publish\Core\REST\Client\FieldTypeService::addFieldType (FieldType $fieldType)
Adds the given $fieldType
Note, this is not an API method and not meant to be used directly!
Parameters
FieldType $fieldType protected
Returns
void
Definition at line 48 of file FieldTypeService.php.
References eZ\Publish\Core\REST\Client\FieldType\getFieldTypeIdentifier().
    {
        $this->fieldTypes[$fieldType->getFieldTypeIdentifier()] = $fieldType;
    }
eZ\Publish\Core\REST\Client\FieldTypeService::getFieldType ($identifier)
Returns the FieldType registered with the given identifier
Parameters
string $identifier
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if there is no FieldType registered with $identifier
Implements eZ\Publish\API\Repository\FieldTypeService.
Definition at line 72 of file FieldTypeService.php.
References eZ\Publish\Core\REST\Client\FieldTypeService\hasFieldType().
    {
        if ( $this->hasFieldType( $identifier ) )
        {
            return $this->fieldTypes[$identifier];
        }
        throw new Exceptions\NotFoundException(
            sprintf(
                'FieldType with identifier "%s" not found.',
                $identifier
            )
        );
    }
eZ\Publish\Core\REST\Client\FieldTypeService::getFieldTypes ()
Returns a list of all field types.
Returns
[]
Implements eZ\Publish\API\Repository\FieldTypeService.
Definition at line 58 of file FieldTypeService.php.
    {
        return array_values( $this->fieldTypes );
    }
eZ\Publish\Core\REST\Client\FieldTypeService::hasFieldType ($identifier)
Returns if there is a FieldType registered under $identifier
Parameters
string $identifier
Returns
boolean
Implements eZ\Publish\API\Repository\FieldTypeService.
Definition at line 94 of file FieldTypeService.php.
    {
        return isset( $this->fieldTypes[$identifier] );
    }
Member Data Documentation
eZ\Publish\Core\REST\Client\FieldTypeService::$fieldTypes = array() protected
Definition at line 22 of file FieldTypeService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Client/FieldTypeService.php