ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter Class Reference
Public Member Functions
__construct (array $handlers=array())
applySelect (ezcQuerySelect $query, array $sortClauses)
applyJoin (ezcQuerySelect $query, array $sortClauses)
applyOrderBy (ezcQuerySelect $query, array $sortClauses)
Protected Attributes
$handlers
$sortColumns = array()
Detailed Description
Converter manager for sort clauses
Definition at line 18 of file SortClauseConverter.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter::__construct (array $handlers = array())
Construct from an optional array of sort clause handlers
Parameters
array $handlers
Returns
void
Definition at line 41 of file SortClauseConverter.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter\$handlers.
    {
        $this->handlers = $handlers;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter::applyJoin (ezcQuerySelect $query, array $sortClauses)
Apply join parts of sort clauses to query
Parameters
\ezcQuerySelect $query
array $sortClauses
Returns
void
Definition at line 83 of file SortClauseConverter.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter\applyJoin().
    {
        foreach ( $sortClauses as $nr => $sortClause )
        {
            foreach ( $this->handlers as $handler )
            {
                if ( $handler->accept( $sortClause ) )
                {
                    $handler->applyJoin( $query, $sortClause, $nr );
                    continue 2;
                }
            }
            throw new RuntimeException( 'No handler available for sort clause: ' . get_class( $sortClause ) );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter::applyOrderBy (ezcQuerySelect $query, array $sortClauses)
Apply order by parts of sort clauses to query
Parameters
\ezcQuerySelect $query
array $sortClauses
Returns
void
Definition at line 108 of file SortClauseConverter.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter\applyOrderBy(), and eZ\Publish\API\Repository\Values\Content\Query\SORT_ASC.
    {
        foreach ( $this->sortColumns as $column => $direction )
        {
            $query->orderBy(
                $column,
                $direction === Query::SORT_ASC ? ezcQuerySelect::ASC : ezcQuerySelect::DESC
            );
        }
        // @todo Review needed
        // The following line was added because without it, loading sub user groups through the Public API
        // fails with the database error "Unknown column sort_column_0". The change does not break any
        // integration tests or legacy persistence tests, but it can break something else, so review is needed
        // Discussion: https://github.com/ezsystems/ezp-next/commit/8749d0977307858c3e2a7d82f3be90fa21973357#L1R102
        $this->sortColumns = array();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter::applySelect (ezcQuerySelect $query, array $sortClauses)
Apply select parts of sort clauses to query
Parameters
\ezcQuerySelect $query
array $sortClauses
Returns
void
Definition at line 54 of file SortClauseConverter.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter\applySelect().
    {
        $sortColumn = array();
        foreach ( $sortClauses as $nr => $sortClause )
        {
            foreach ( $this->handlers as $handler )
            {
                if ( $handler->accept( $sortClause ) )
                {
                    foreach ( (array)$handler->applySelect( $query, $sortClause, $nr ) as $column )
                    {
                        $this->sortColumns[$column] = $sortClause->direction;
                    }
                    continue 2;
                }
            }
            throw new RuntimeException( 'No handler available for sort clause: ' . get_class( $sortClause ) );
        }
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter::$handlers protected
Definition at line 25 of file SortClauseConverter.php.
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseConverter::$sortColumns = array() protected
Definition at line 32 of file SortClauseConverter.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Search/Gateway/SortClauseConverter.php