ezp-next: eZ\Publish\Core\FieldType\MapLocation\Type Class Reference
eZ\Publish\Core\FieldType\MapLocation\Type Class Reference
Public Member Functions
getFieldTypeIdentifier ()
getName ($value)
getEmptyValue ()
isEmptyValue ($value)
fromHash ($hash)
toHash ($value)
isSearchable ()
getIndexData ($value)
toPersistenceValue ($value)
fromPersistenceValue (FieldValue $fieldValue)
Public Member Functions inherited from eZ\Publish\Core\FieldType\FieldType
getSettingsSchema ()
getValidatorConfigurationSchema ()
validate (FieldDefinition $fieldDefinition, $fieldValue)
validateValidatorConfiguration ($validatorConfiguration)
validateFieldSettings ($fieldSettings)
acceptValue ($inputValue)
fieldSettingsToHash ($fieldSettings)
fieldSettingsFromHash ($fieldSettingsHash)
validatorConfigurationToHash ($validatorConfiguration)
validatorConfigurationFromHash ($validatorConfigurationHash)
Protected Member Functions
internalAcceptValue ($inputValue)
getSortInfo ($value)
Additional Inherited Members
Protected Attributes inherited from eZ\Publish\Core\FieldType\FieldType
$settingsSchema = array()
$validatorConfigurationSchema = array()
Detailed Description
MapLocation field types
Represents keywords.
Definition at line 21 of file Type.php.
Member Function Documentation
eZ\Publish\Core\FieldType\MapLocation\Type::fromHash ($hash)
Converts an $hash to the Value defined by the field type
Parameters
mixed $hash
Returns
$value
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 146 of file Type.php.
    {
        if ( $hash === null )
        {
            return null;
        }
        return new Value( $hash );
    }
eZ\Publish\Core\FieldType\MapLocation\Type::fromPersistenceValue (FieldValue $fieldValue)
Converts a persistence $fieldValue to a Value
Parameters
\eZ\Publish\SPI\Persistence\Content\FieldValue $fieldValue
Returns
mixed
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 222 of file Type.php.
References eZ\Publish\Core\FieldType\MapLocation\Type\fromHash().
    {
        if ( $fieldValue->externalData === null )
        {
            return null;
        }
        return $this->fromHash( $fieldValue->externalData );
    }
eZ\Publish\Core\FieldType\MapLocation\Type::getEmptyValue ()
Returns the fallback default value of field type when no such default value is provided in the field definition in content types.
Returns
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 59 of file Type.php.
    {
        return new Value;
    }
eZ\Publish\Core\FieldType\MapLocation\Type::getFieldTypeIdentifier ()
Returns the field type identifier for this field type
Returns
string
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 28 of file Type.php.
    {
        return "ezgmaplocation";
    }
eZ\Publish\Core\FieldType\MapLocation\Type::getIndexData ($value)
Get index data for field data for search backend
Parameters
mixed $value
Returns
[]
Definition at line 192 of file Type.php.
    {
        throw new \RuntimeException( '@todo: Implement' );
    }
eZ\Publish\Core\FieldType\MapLocation\Type::getName ($value)
Returns the name of the given field value.
It will be used to generate content name and url alias if current field is designated to be used in the content name/urlAlias pattern.
Parameters
mixed $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 43 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\acceptValue().
    {
        $value = $this->acceptValue( $value );
        if ( $value !== null )
        {
            return $value->address;
        }
    }
eZ\Publish\Core\FieldType\MapLocation\Type::getSortInfo ($value) protected
Returns information for FieldValue->$sortKey relevant to the field type.
Returns
string
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 131 of file Type.php.
    {
        if ( $value !== null )
        {
            return $value->address;
        }
    }
eZ\Publish\Core\FieldType\MapLocation\Type::internalAcceptValue ($inputValue) protected
Implements the core of {
See Also
acceptValue()}.
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 83 of file Type.php.
    {
        if ( is_array( $inputValue ) )
        {
            $inputValue = new Value( $inputValue );
        }
        else if ( !$inputValue instanceof Value )
        {
            throw new InvalidArgumentType(
                '$inputValue',
                'eZ\\Publish\\Core\\FieldType\\MapLocation\\Value',
                $inputValue
            );
        }
        if ( !is_float( $inputValue->latitude ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->latitude',
                'float',
                $inputValue->latitude
            );
        }
        if ( !is_float( $inputValue->longitude ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->longitude',
                'float',
                $inputValue->longitude
            );
        }
        if ( !is_string( $inputValue->address ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->address',
                'string',
                $inputValue->address
            );
        }
        return $inputValue;
    }
eZ\Publish\Core\FieldType\MapLocation\Type::isEmptyValue ($value)
Returns if the given $value is considered empty by the field type
Parameters
mixed $value
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 71 of file Type.php.
    {
        return $value === null || $value->latitude === null || $value->longitude === null;
    }
eZ\Publish\Core\FieldType\MapLocation\Type::isSearchable ()
Returns whether the field type is searchable
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 180 of file Type.php.
    {
        return true;
    }
eZ\Publish\Core\FieldType\MapLocation\Type::toHash ($value)
Converts a $Value to a hash
Parameters
\eZ\Publish\Core\FieldType\MapLocation\Value $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 162 of file Type.php.
References eZ\Publish\Core\FieldType\MapLocation\Type\isEmptyValue().
    {
        if ( $this->isEmptyValue( $value ) )
        {
            return null;
        }
        return array(
            'latitude' => $value->latitude,
            'longitude' => $value->longitude,
            'address' => $value->address,
        );
    }
eZ\Publish\Core\FieldType\MapLocation\Type::toPersistenceValue ($value)
Converts a $value to a persistence value
Parameters
mixed $value
Returns
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 204 of file Type.php.
References eZ\Publish\Core\FieldType\MapLocation\Type\getSortInfo(), and eZ\Publish\Core\FieldType\MapLocation\Type\toHash().
    {
        return new FieldValue(
            array(
                "data" => null,
                "externalData" => $this->toHash( $value ),
                "sortKey" => $this->getSortInfo( $value ),
            )
        );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/MapLocation/Type.php