ezp-next: eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage Class Reference
eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage Class Reference
Public Member Functions
setConnection ($dbHandler)
getFieldData ($fieldId, $userId=null)
Protected Member Functions
getPropertyMap ()
convertColumnsToProperties (array $databaseValues)
fetchUserId ($fieldId)
fetchUserData ($userId)
fetchUserSettings ($userId)
Protected Attributes
$dbHandler
$defaultValues
Detailed Description
Definition at line 14 of file LegacyStorage.php.
Member Function Documentation
eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage::convertColumnsToProperties (array $databaseValues) protected
Converts the given database values to properties
Parameters
array $databaseValues
Returns
array
Definition at line 159 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\convertColumnsToProperties(), and eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\getPropertyMap().
    {
        $propertyValues = array();
        $propertyMap = $this->getPropertyMap();
        foreach ( $databaseValues as $columnName => $value )
        {
            $conversionFunction = $propertyMap[$columnName]['cast'];
            $propertyValues[$propertyMap[$columnName]['name']] = $conversionFunction( $value );
        }
        return $propertyValues;
    }
eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage::fetchUserData ($userId) protected
Fetch user data
Parameters
mixed $userId
Returns
array
Definition at line 209 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\convertColumnsToProperties(), and eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\fetchUserData().
    {
        $query = $this->dbHandler->createSelectQuery();
        $query
            ->select(
                $this->dbHandler->quoteColumn( 'contentobject_id', 'ezuser' ),
                $this->dbHandler->quoteColumn( 'login', 'ezuser' ),
                $this->dbHandler->quoteColumn( 'email', 'ezuser' ),
                $this->dbHandler->quoteColumn( 'password_hash', 'ezuser' ),
                $this->dbHandler->quoteColumn( 'password_hash_type', 'ezuser' )
            )
            ->from( $this->dbHandler->quoteTable( 'ezuser' ) )
            ->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentobject_id', 'ezuser' ),
                    $query->bindValue( $userId )
                )
            );
        $stmt = $query->prepare();
        $stmt->execute();
        $rows = $stmt->fetchAll( \PDO::FETCH_ASSOC );
        return isset( $rows[0] ) ? $this->convertColumnsToProperties( $rows[0] ) : array();
    }
eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage::fetchUserId ($fieldId) protected
Fetch basic user data
Parameters
mixed $fieldId
Returns
array
Definition at line 181 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\fetchUserId().
    {
        $query = $this->dbHandler->createSelectQuery();
        $query
            ->select(
                $this->dbHandler->quoteColumn( 'contentobject_id' )
            )
            ->from( $this->dbHandler->quoteTable( 'ezcontentobject_attribute' ) )
            ->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'id', 'ezcontentobject_attribute' ),
                    $query->bindValue( $fieldId )
                )
            );
        $stmt = $query->prepare();
        $stmt->execute();
        return $stmt->fetchColumn();
    }
eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage::fetchUserSettings ($userId) protected
Fetch user settings
Naturally this would be a RIGHT OUTER JOIN, but this is not supported by ezcDatabase nor by databases like SQLite
Parameters
mixed $userId
Returns
array
Definition at line 245 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\convertColumnsToProperties(), and eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\fetchUserSettings().
    {
        $query = $this->dbHandler->createSelectQuery();
        $query
            ->select(
                $this->dbHandler->quoteColumn( 'is_enabled', 'ezuser_setting' ),
                $this->dbHandler->quoteColumn( 'max_login', 'ezuser_setting' )
            )
            ->from( $this->dbHandler->quoteTable( 'ezuser_setting' ) )
            ->where(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'user_id', 'ezuser_setting' ),
                    $query->bindValue( $userId )
                )
            );
        $stmt = $query->prepare();
        $stmt->execute();
        $rows = $stmt->fetchAll( \PDO::FETCH_ASSOC );
        return isset( $rows[0] ) ? $this->convertColumnsToProperties( $rows[0] ) : array();
    }
eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage::getFieldData ($fieldId, $userId = null)
Get field data
The User storage handles the following attributes, following the user field type in eZ Publish 4:
hasStoredLogin
contentobjectId
login
email
passwordHash
passwordHashType
isEnabled
maxLogin
Parameters
mixed $fieldId
mixed $userId
Returns
array
Reimplemented from eZ\Publish\Core\FieldType\User\UserStorage\Gateway.
Definition at line 130 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\fetchUserData(), eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\fetchUserId(), and eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\fetchUserSettings().
    {
        $userId   = $userId ?: $this->fetchUserId( $fieldId );
        $userData = $this->fetchUserData( $userId );
        if ( !isset( $userData['login'] ) )
        {
            return $this->defaultValues;
        }
        $result = array_merge(
            $this->defaultValues,
            array(
                'hasStoredLogin' => true,
            ),
            $userData,
            $this->fetchUserSettings( $userId )
        );
        return $result;
    }
eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage::getPropertyMap () protected
Definition at line 44 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\getPropertyMap().
    {
        return array(
            'has_stored_login' => array(
                'name' => 'hasStoredlogin',
                'cast' =>
                    function ( $input )
                    {
                        return ( $input == "1" );
                    },
            ),
            'contentobject_id' => array(
                'name' => 'contentId',
                'cast' => 'intval'
            ),
            'login' => array(
                'name' => 'login',
                'cast' => 'strval'
            ),
            'email' => array(
                'name' => 'email',
                'cast' => 'strval'
            ),
            'password_hash' => array(
                'name' => 'passwordHash',
                'cast' => 'strval'
            ),
            'password_hash_type' => array(
                'name' => 'passwordHashType',
                'cast' => 'strval'
            ),
            'is_enabled' => array(
                'name' => 'enabled',
                'cast' =>
                    function ( $input )
                    {
                        return ( $input == "1" );
                    }
            ),
            'max_login' => array(
                'name' => 'maxLogin',
                'cast' => 'intval'
            ),
        );
    }
eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage::setConnection ($dbHandler)
Set dbHandler for gateway
Parameters
mixed $dbHandler
Returns
void
Reimplemented from eZ\Publish\Core\FieldType\StorageGateway.
Definition at line 97 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\$dbHandler, and eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage\setConnection().
    {
        // This obviously violates the Liskov substitution Principle, but with
        // the given class design there is no sane other option. Actually the
        // dbHandler *should* be passed to the constructor, and there should
        // not be the need to post-inject it.
        if ( !$dbHandler instanceof \eZ\Publish\Core\Persistence\Legacy\EzcDbHandler )
        {
            throw new \RuntimeException( "Invalid dbHandler passed" );
        }
        $this->dbHandler = $dbHandler;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage::$dbHandler protected
Definition at line 21 of file LegacyStorage.php.
eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage::$defaultValues protected
Initial value:
 array(
        'hasStoredLogin'   => false,
        'contentId'   => null,
        'login'              => null,
        'email'              => null,
        'passwordHash'      => null,
        'passwordHashType' => null,
        'enabled'         => false,
        'maxLogin'          => null,
    )
Definition at line 28 of file LegacyStorage.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/User/UserStorage/Gateway/LegacyStorage.php