ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler Class Reference
Public Member Functions
__construct (LocationGateway $locationGateway, LocationMapper $locationMapper, ContentHandler $contentHandler, ContentMapper $contentMapper)
load ($locationId)
loadByRemoteId ($remoteId)
loadLocationsByContent ($contentId, $rootLocationId=null)
copySubtree ($sourceId, $destinationParentId)
move ($sourceId, $destinationParentId)
markSubtreeModified ($locationId, $timestamp=null)
hide ($id)
unHide ($id)
swap ($locationId1, $locationId2)
update (UpdateStruct $location, $locationId)
create (CreateStruct $createStruct)
removeSubtree ($locationId)
setSectionForSubtree ($locationId, $sectionId)
changeMainLocation ($contentId, $locationId)
Protected Member Functions
getParentPathString ($pathString)
Protected Attributes
$locationGateway
$locationMapper
$contentHandler
$contentMapper
Detailed Description
The Location Handler interface defines operations on Location elements in the storage engine.
Definition at line 26 of file Handler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::__construct (LocationGateway $locationGateway, LocationMapper $locationMapper, ContentHandler $contentHandler, ContentMapper $contentMapper)
Construct from userGateway
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway $locationGateway
\eZ\Publish\Core\Persistence\Legacy\Content\Location\Mapper $locationMapper
\eZ\Publish\Core\Persistence\Legacy\Content\Handler $contentHandler
\eZ\Publish\Core\Persistence\Legacy\Content\Mapper $contentMapper
Returns
Definition at line 66 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler\$contentHandler, eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler\$contentMapper, eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler\$locationGateway, and eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler\$locationMapper.
    {
        $this->locationGateway = $locationGateway;
        $this->locationMapper = $locationMapper;
        $this->contentHandler = $contentHandler;
        $this->contentMapper = $contentMapper;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::changeMainLocation ($contentId, $locationId)
Changes main location of content identified by given $contentId to location identified by given $locationId
Updates ezcontentobject_tree and eznode_assignment tables (eznode_assignment for content current version number).
Parameters
mixed $contentId
mixed $locationId
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 463 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Location\$contentId, eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler\load(), and eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler\setSectionForSubtree().
    {
        $parentLocationId = $this->load( $locationId )->parentId;
        // Update ezcontentobject_tree and eznode_assignment tables
        $this->locationGateway->changeMainLocation(
            $contentId,
            $locationId,
            $this->contentHandler->loadContentInfo( $contentId )->currentVersionNo,
            $parentLocationId
        );
        // Update subtree section to the one of the new main location parent location content
        $this->setSectionForSubtree(
            $locationId,
            $this->contentHandler->loadContentInfo( $this->load( $parentLocationId )->contentId )->sectionId
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::copySubtree ($sourceId, $destinationParentId)
Copy location object identified by $sourceId, into destination identified by $destinationParentId.
Performs a deep copy of the location identified by $sourceId and all of its child locations, copying the most recent published content object for each location to a new content object without any additional version information. Relations are not copied. URLs are not touched at all.
Todo:
update subtree modification time, optionally retain dates and set creator
Parameters
mixed $sourceId
mixed $destinationParentId
Returns
Location the newly created Location.
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 149 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Location\$contentId, eZ\Publish\SPI\Persistence\Content\Location\$pathString, eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler\changeMainLocation(), eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler\create(), and eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler\setSectionForSubtree().
    {
        $children = $this->locationGateway->getSubtreeContent( $sourceId );
        $destinationParentData = $this->locationGateway->getBasicNodeData( $destinationParentId );
        $contentMap = array();
        $locationMap = array(
            $children[0]["parent_node_id"] => array(
                "id" => $destinationParentId,
                "hidden" => (boolean)$destinationParentData["is_hidden"],
                "invisible" => (boolean)$destinationParentData["is_invisible"],
                "path_identification_string" => $destinationParentData["path_identification_string"]
            )
        );
        $locations = array();
        foreach ( $children as $child )
        {
            $locations[$child["contentobject_id"]][$child["node_id"]] = true;
        }
        $time = time();
        $mainLocations = array();
        $mainLocationsUpdate = array();
        foreach ( $children as $index => $child )
        {
            // Copy content
            if ( !isset( $contentMap[$child["contentobject_id"]] ) )
            {
                $content = $this->contentHandler->copy(
                    $child["contentobject_id"],
                    $child["contentobject_version"]
                );
                $content = $this->contentHandler->publish(
                    $content->versionInfo->contentInfo->id,
                    $content->versionInfo->contentInfo->currentVersionNo,
                    new MetadataUpdateStruct(
                        array(
                            "publicationDate" => $time,
                            "modificationDate" => $time
                        )
                    )
                );
                $contentMap[$child["contentobject_id"]] = $content->versionInfo->contentInfo->id;
            }
            $createStruct = $this->locationMapper->getLocationCreateStruct( $child );
            $createStruct->contentId = $contentMap[$child["contentobject_id"]];
            $parentData = $locationMap[$child["parent_node_id"]];
            $createStruct->parentId = $parentData["id"];
            $createStruct->invisible = $createStruct->hidden || $parentData["hidden"] || $parentData["invisible"];
            $pathString = explode( "/", $child["path_identification_string"] );
            $pathString = end( $pathString );
            $createStruct->pathIdentificationString = strlen( $pathString ) > 0
                ? $parentData["path_identification_string"] . "/" . $pathString
                : null;
            // Use content main location if already set, otherwise create location as main
            if ( isset( $mainLocations[$child["contentobject_id"]] ) )
            {
                $createStruct->mainLocationId = $locationMap[$mainLocations[$child["contentobject_id"]]]["id"];
            }
            else
            {
                $createStruct->mainLocationId = true;
                $mainLocations[$child["contentobject_id"]] = $child["node_id"];
                // If needed mark for update
                if (
                    isset( $locations[$child["contentobject_id"]][$child["main_node_id"]] ) &&
                    count( $locations[$child["contentobject_id"]] ) > 1 &&
                    $child["node_id"] !== $child["main_node_id"]
                )
                {
                    $mainLocationsUpdate[$child["contentobject_id"]] = $child["main_node_id"];
                }
            }
            $newLocation = $this->create( $createStruct );
            $locationMap[$child["node_id"]] = array(
                "id" => $newLocation->id,
                "hidden" => $newLocation->hidden,
                "invisible" => $newLocation->invisible,
                "path_identification_string" => $newLocation->pathIdentificationString
            );
            if ( $index === 0 )
            {
                $copiedSubtreeRootLocation = $newLocation;
            }
        }
        // Update main locations
        foreach ( $mainLocationsUpdate as $contentId => $mainLocationId )
        {
            $this->changeMainLocation(
                $contentMap[$contentId],
                $locationMap[$mainLocationId]["id"]
            );
        }
        // If subtree root is main location for its content, update subtree section to the one of the
        // parent location content
        $subtreeRootContentInfo = $this->contentHandler->loadContentInfo( $copiedSubtreeRootLocation->contentId );
        if ( $subtreeRootContentInfo->mainLocationId === $copiedSubtreeRootLocation->id )
        {
            $this->setSectionForSubtree(
                $copiedSubtreeRootLocation->id,
                $this->contentHandler->loadContentInfo( $this->load( $destinationParentId )->contentId )->sectionId
            );
        }
        return $copiedSubtreeRootLocation;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::create (CreateStruct $createStruct)
Creates a new location rooted at $location->parentId.
Parameters
\eZ\Publish\SPI\Persistence\Content\Location\CreateStruct $createStruct
Returns
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 374 of file Handler.php.
    {
        $parentNodeData = $this->locationGateway->getBasicNodeData( $createStruct->parentId );
        $locationStruct = $this->locationGateway->create( $createStruct, $parentNodeData );
        $this->locationGateway->createNodeAssignment(
            $createStruct,
            $parentNodeData['node_id'],
            LocationGateway::NODE_ASSIGNMENT_OP_CODE_CREATE_NOP
        );
        return $locationStruct;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::getParentPathString ($pathString) protected
Returns parent path string for a path string
Parameters
string $pathString
Returns
string
Definition at line 86 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Location\$pathString.
    {
        return implode( '/', array_slice( explode( '/', $pathString ), 0, -2 ) ) . '/';
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::hide ($id)
Sets a location to be hidden, and it self + all children to invisible.
Parameters
mixed $id Location ID
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 318 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Location\$id.
    {
        $sourceNodeData = $this->locationGateway->getBasicNodeData( $id );
        $this->locationGateway->hideSubtree( $sourceNodeData['path_string'] );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::load ($locationId)
Loads the data for the location identified by $locationId.
Parameters
int $locationId
Returns
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 98 of file Handler.php.
    {
        $data = $this->locationGateway->getBasicNodeData( $locationId );
        return $this->locationMapper->createLocationFromRow( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::loadByRemoteId ($remoteId)
Loads the data for the location identified by $remoteId.
Parameters
string $remoteId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException
Returns
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 113 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Location\$remoteId.
    {
        $data = $this->locationGateway->getBasicNodeDataByRemoteId( $remoteId );
        return $this->locationMapper->createLocationFromRow( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::loadLocationsByContent ($contentId, $rootLocationId = null)
Loads all locations for $contentId, optionally limited to a sub tree identified by $rootLocationId
Parameters
int $contentId
int $rootLocationId
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 128 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Location\$contentId.
    {
        $rows = $this->locationGateway->loadLocationDataByContent( $contentId, $rootLocationId );
        return $this->locationMapper->createLocationsFromRows( $rows );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::markSubtreeModified ($locationId, $timestamp = null)
Marks the given nodes and all ancestors as modified
Optionally a time stamp with the modification date may be specified, otherwise the current time is used.
Parameters
int | string $locationId
int $timestamp
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 306 of file Handler.php.
    {
        $nodeData = $this->locationGateway->getBasicNodeData( $locationId );
        $timestamp = $timestamp ?: time();
        $this->locationGateway->updateSubtreeModificationTime( $nodeData['path_string'], $timestamp );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::move ($sourceId, $destinationParentId)
Moves location identified by $sourceId into new parent identified by $destinationParentId.
Performs a full move of the location identified by $sourceId to a new destination, identified by $destinationParentId. Relations do not need to be updated, since they refer to Content. URLs are not touched.
Parameters
mixed $sourceId
mixed $destinationParentId
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 277 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\NODE_ASSIGNMENT_OP_CODE_MOVE.
    {
        $sourceNodeData = $this->locationGateway->getBasicNodeData( $sourceId );
        $destinationNodeData = $this->locationGateway->getBasicNodeData( $destinationParentId );
        $this->locationGateway->moveSubtreeNodes(
            $sourceNodeData,
            $destinationNodeData
        );
        $this->locationGateway->updateNodeAssignment(
            $sourceNodeData['contentobject_id'],
            $sourceNodeData['parent_node_id'],
            $destinationParentId,
            Gateway::NODE_ASSIGNMENT_OP_CODE_MOVE
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::removeSubtree ($locationId)
Removes all Locations under and including $locationId.
Performs a recursive delete on the location identified by $locationId, including all of its child locations. Content which is not referred to by any other location is automatically removed. Content which looses its main Location will get the first of its other Locations assigned as the new main Location.
Parameters
mixed $locationId
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 400 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Location\$contentId, and eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler\changeMainLocation().
    {
        $locationRow = $this->locationGateway->getBasicNodeData( $locationId );
        $contentId = $locationRow["contentobject_id"];
        $mainLocationId = $locationRow["main_node_id"];
        $subLocations = $this->locationGateway->getChildren( $locationId );
        foreach ( $subLocations as $subLocation )
        {
            $this->removeSubtree( $subLocation["node_id"] );
        }
        if ( $locationId == $mainLocationId )
        {
            if ( 1 == $this->locationGateway->countLocationsByContentId( $contentId ) )
            {
                $this->contentHandler->removeRawContent( $contentId );
            }
            else
            {
                $newMainLocationRow = $this->locationGateway->getFallbackMainNodeData(
                    $contentId,
                    $locationId
                );
                $this->changeMainLocation(
                    $contentId,
                    $newMainLocationRow["node_id"],
                    $newMainLocationRow["contentobject_version"],
                    $newMainLocationRow["parent_node_id"]
                );
            }
        }
        $this->locationGateway->removeLocation( $locationId );
        $this->locationGateway->deleteNodeAssignment( $contentId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::setSectionForSubtree ($locationId, $sectionId)
Set section on all content objects in the subtree
Parameters
mixed $locationId
mixed $sectionId
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 446 of file Handler.php.
    {
        $nodeData = $this->locationGateway->getBasicNodeData( $locationId );
        $this->locationGateway->setSectionForSubtree( $nodeData['path_string'], $sectionId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::swap ($locationId1, $locationId2)
Swaps the content object being pointed to by a location object.
Make the location identified by $locationId1 refer to the Content referred to by $locationId2 and vice versa.
Parameters
mixed $locationId1
mixed $locationId2
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 349 of file Handler.php.
    {
        $this->locationGateway->swap( $locationId1, $locationId2 );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::unHide ($id)
Sets a location to be unhidden, and self + children to visible unless a parent is hiding the tree. If not make sure only children down to first hidden node is marked visible.
Parameters
mixed $id
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 331 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Location\$id.
    {
        $sourceNodeData = $this->locationGateway->getBasicNodeData( $id );
        $this->locationGateway->unhideSubtree( $sourceNodeData['path_string'] );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::update (UpdateStruct $location, $locationId)
Updates an existing location.
Parameters
\eZ\Publish\SPI\Persistence\Content\Location\UpdateStruct $location
int $locationId
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 362 of file Handler.php.
    {
        $this->locationGateway->update( $location, $locationId );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::$contentHandler protected
Definition at line 47 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::$contentMapper protected
Definition at line 54 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::$locationGateway protected
Definition at line 33 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler::$locationMapper protected
Definition at line 40 of file Handler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php