ezp-next: eZ\Publish\Core\MVC\Legacy\Kernel Class Reference
eZ\Publish\Core\MVC\Legacy\Kernel Class Reference
Public Member Functions
__construct (ezpKernelHandler $kernelHandler, $legacyRootDir, $webRootDir)
enterLegacyRootDir ()
leaveLegacyRootDir ()
run ()
runCallback (\Closure $callback, $postReinitialize=true)
Detailed Description
Class wrapping the legacy kernel
Definition at line 18 of file Kernel.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Legacy\Kernel::__construct (ezpKernelHandler $kernelHandler, $legacyRootDir, $webRootDir)
Parameters
\ezpKernelHandler $kernelHandler
string $legacyRootDir Must be a absolute dir
string $webRootDir Must be a absolute dir
Definition at line 39 of file Kernel.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\enterLegacyRootDir(), and eZ\Publish\Core\MVC\Legacy\Kernel\leaveLegacyRootDir().
    {
        $this->legacyRootDir = $legacyRootDir;
        $this->webRootDir = $webRootDir;
        $this->enterLegacyRootDir();
        parent::__construct( $kernelHandler );
        $this->leaveLegacyRootDir();
        $this->setUseExceptions( true );
    }
Member Function Documentation
eZ\Publish\Core\MVC\Legacy\Kernel::enterLegacyRootDir ()
Changes the current working directory to the legacy root dir. Calling this method is mandatory to use legacy kernel since a lot of resources in eZ Publish 4.x relatively defined.
Definition at line 54 of file Kernel.php.
    {
        chdir( $this->legacyRootDir );
    }
eZ\Publish\Core\MVC\Legacy\Kernel::leaveLegacyRootDir ()
Leaves the legacy root dir and switches back to the initial webroot dir.
Definition at line 62 of file Kernel.php.
    {
        chdir( $this->webRootDir );
    }
eZ\Publish\Core\MVC\Legacy\Kernel::run ()
Runs current request through legacy kernel.
Returns
array
Definition at line 72 of file Kernel.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\enterLegacyRootDir(), and eZ\Publish\Core\MVC\Legacy\Kernel\leaveLegacyRootDir().
    {
        $this->enterLegacyRootDir();
        $return = parent::run();
        $this->leaveLegacyRootDir();
        return $return;
    }
eZ\Publish\Core\MVC\Legacy\Kernel::runCallback (\Closure $callback, $postReinitialize = true)
Runs a callback function in the legacy kernel environment. This is useful to run eZ Publish 4.x code from a non-related context (like eZ Publish 5)
Parameters
\Closure $callback
boolean $postReinitialize Default is true. If set to false, the kernel environment will not be reinitialized. This can be useful to optimize several calls to the kernel within the same context.
Returns
mixed The result of the callback
Definition at line 90 of file Kernel.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\enterLegacyRootDir(), and eZ\Publish\Core\MVC\Legacy\Kernel\leaveLegacyRootDir().
    {
        $this->enterLegacyRootDir();
        $return = parent::runCallback( $callback, $postReinitialize );
        $this->leaveLegacyRootDir();
        return $return;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Legacy/Kernel.php