ezp-next: eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage Class Reference
eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage Class Reference
Protected Member Functions
getStorageTable ()
getPropertyMapping ()
setFetchColumns (\ezcQuerySelect $selectQuery, $fieldId, $versionNo)
setInsertColumns (\ezcQueryInsert $insertQuery, VersionInfo $versionInfo, Field $field)
Protected Member Functions inherited from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage
getConnection ()
toPropertyName ($columnName)
castToPropertyValue ($value, $columnName)
Additional Inherited Members
Public Member Functions inherited from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage
setConnection ($dbHandler)
storeFileReference (VersionInfo $versionInfo, Field $field)
removeMimeFromPath ($path)
getFileReferenceData ($fieldId, $versionNo)
prependMimeToPath ($path, $mimeType)
removeFileReferences (array $fieldIds, $versionNo)
removeFileReference ($fieldId, $versionNo)
getReferencedFiles (array $fieldIds, $versionNo)
countFileReferences (array $files)
Protected Attributes inherited from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage
$dbHandler
Detailed Description
Definition at line 16 of file LegacyStorage.php.
Member Function Documentation
eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage::getPropertyMapping () protected
Returns a column to property mapping for the storage table.
Returns
void
Reimplemented from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage.
Definition at line 33 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage\getPropertyMapping().
    {
        $propertyMap = parent::getPropertyMapping();
        $propertyMap['has_controller'] = array(
            'name' => 'hasController',
            'cast' =>
                function ( $val )
                {
                    return (bool)$val;
                },
        );
        $propertyMap['is_autoplay'] = array(
            'name' => 'autoplay',
            'cast' =>
                function ( $val )
                {
                    return (bool)$val;
                },
        );
        $propertyMap['is_loop'] = array(
            'name' => 'loop',
            'cast' =>
                function ( $val )
                {
                    return (bool)$val;
                },
        );
        $propertyMap['width'] = array(
            'name' => 'width',
            'cast' => 'intval',
        );
        $propertyMap['height'] = array(
            'name' => 'height',
            'cast' => 'intval',
        );
        return $propertyMap;
    }
eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage::getStorageTable () protected
Returns the table name to store data in.
Returns
string
Reimplemented from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage.
Definition at line 23 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage\getStorageTable().
    {
        return 'ezmedia';
    }
eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage::setFetchColumns (\ezcQuerySelect $selectQuery, $fieldId, $versionNo) protected
Set columns to be fetched from the database
This method is intended to be overwritten by derived classes in order to add additional columns to be fetched from the database. Please do not forget to call the parent when overwriting this method.
Parameters
\ezcQuerySelect $selectQuery
int $fieldId
int $versionNo
Returns
void
Reimplemented from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage.
Definition at line 84 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage\setFetchColumns().
    {
        $connection = $this->getConnection();
        parent::setFetchColumns( $selectQuery, $fieldId, $versionNo );
        $selectQuery->select(
            $connection->quoteColumn( 'has_controller' ),
            $connection->quoteColumn( 'is_autoplay' ),
            $connection->quoteColumn( 'is_loop' ),
            $connection->quoteColumn( 'width' ),
            $connection->quoteColumn( 'height' )
        );
    }
eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage::setInsertColumns (\ezcQueryInsert $insertQuery, VersionInfo $versionInfo, Field $field) protected
Sets the required insert columns to $selectQuery.
This method is intended to be overwritten by derived classes in order to add additional columns to be set in the database. Please do not forget to call the parent when overwriting this method.
Parameters
\ezcQueryInsert $insertQuery
VersionInfo $versionInfo
Field $field
Returns
void
Reimplemented from eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage.
Definition at line 111 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage\setInsertColumns().
    {
        $connection = $this->getConnection();
        parent::setInsertColumns( $insertQuery, $versionInfo, $field );
        $insertQuery->set(
            $connection->quoteColumn( 'controls' ),
            $insertQuery->bindValue( '' )
        )->set(
            $connection->quoteColumn( 'has_controller' ),
            $insertQuery->bindValue( (int)$field->value->externalData['hasController'], null, \PDO::PARAM_INT )
        )->set(
            $connection->quoteColumn( 'height' ),
            $insertQuery->bindValue( (int)$field->value->externalData['height'], null, \PDO::PARAM_INT )
        )->set(
            $connection->quoteColumn( 'is_autoplay' ),
            $insertQuery->bindValue( (int)$field->value->externalData['autoplay'], null, \PDO::PARAM_INT )
        )->set(
            $connection->quoteColumn( 'is_loop' ),
            $insertQuery->bindValue( (int)$field->value->externalData['loop'], null, \PDO::PARAM_INT )
        )->set(
            $connection->quoteColumn( 'pluginspage' ),
            $insertQuery->bindValue( '' )
        )->set(
            $connection->quoteColumn( 'quality' ),
            $insertQuery->bindValue( 'high' )
        )->set(
            $connection->quoteColumn( 'width' ),
            $insertQuery->bindValue( (int)$field->value->externalData['width'], null, \PDO::PARAM_INT )
        );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Media/MediaStorage/Gateway/LegacyStorage.php