ezp-next: eZ\Publish\Core\FieldType\FieldType Class Reference
eZ\Publish\Core\FieldType\FieldType Class Reference
Public Member Functions
getSettingsSchema ()
getValidatorConfigurationSchema ()
validate (FieldDefinition $fieldDefinition, $fieldValue)
validateValidatorConfiguration ($validatorConfiguration)
validateFieldSettings ($fieldSettings)
toPersistenceValue ($value)
fromPersistenceValue (FieldValue $fieldValue)
isSearchable ()
isEmptyValue ($value)
acceptValue ($inputValue)
fieldSettingsToHash ($fieldSettings)
fieldSettingsFromHash ($fieldSettingsHash)
validatorConfigurationToHash ($validatorConfiguration)
validatorConfigurationFromHash ($validatorConfigurationHash)
Public Member Functions inherited from eZ\Publish\API\Repository\FieldType
getFieldTypeIdentifier ()
getName ($value)
getEmptyValue ()
fromHash ($hash)
toHash ($value)
Protected Member Functions
getSortInfo ($value)
internalAcceptValue ($inputValue)
Protected Attributes
$settingsSchema = array()
$validatorConfigurationSchema = array()
Detailed Description
Base class for field types, the most basic storage unit of data inside eZ Publish.
All other field types extend FieldType providing the specific functionality desired in each case.
The capabilities supported by each individual field type is decided by which interfaces the field type implements support for. These individual capabilities can also be checked via the supports*() methods.
Field types are the base building blocks of Content Types, and serve as data containers for Content objects. Therefore, while field types can be used independently, they are designed to be used as a part of a Content object.
Field types are primed and pre-configured with the Field Definitions found in Content Types.
Definition at line 32 of file FieldType.php.
Member Function Documentation
eZ\Publish\Core\FieldType\FieldType::acceptValue ($inputValue) final
Potentially builds and checks the type and structure of the $inputValue.
This method first inspects $inputValue and convert it into a dedicated value object.
After that, the value is checked for structural validity. Note that this does not include validation after the rules from validators, but only plausibility checks for the general data format.
Note that this method must also cope with the empty value for the field type as e.g. returned by getEmptyValue().
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the parameter is not of the supported value sub type
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the value does not match the expected structure
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Definition at line 276 of file FieldType.php.
References eZ\Publish\API\Repository\FieldType\getEmptyValue(), and eZ\Publish\Core\FieldType\FieldType\internalAcceptValue().
    {
        if ( $inputValue === null )
        {
            return $this->getEmptyValue();
        }
        return $this->internalAcceptValue( $inputValue );
    }
eZ\Publish\Core\FieldType\FieldType::fieldSettingsFromHash ($fieldSettingsHash)
Converts the given $fieldSettingsHash to field settings of the type
This is the reverse operation of fieldSettingsToHash().
This is the default implementation, which just returns the given $fieldSettingsHash, assuming the supported field settings are already in a hash format. Overwrite this in your specific implementation, if neccessary.
Parameters
array | hash | scalar | null $fieldSettingsHash
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Reimplemented in eZ\Publish\Core\FieldType\DateAndTime\Type.
Definition at line 325 of file FieldType.php.
    {
        return $fieldSettingsHash;
    }
eZ\Publish\Core\FieldType\FieldType::fieldSettingsToHash ($fieldSettings)
Converts the given $fieldSettings to a simple hash format
This is the default implementation, which just returns the given $fieldSettings, assuming they are already in a hash format. Overwrite this in your specific implementation, if neccessary.
Parameters
mixed $fieldSettings
Returns
array|hash|scalar|null
Implements eZ\Publish\API\Repository\FieldType.
Reimplemented in eZ\Publish\Core\FieldType\DateAndTime\Type.
Definition at line 306 of file FieldType.php.
    {
        return $fieldSettings;
    }
eZ\Publish\Core\FieldType\FieldType::fromPersistenceValue (FieldValue $fieldValue)
Converts a persistence $fieldValue to a Value
Parameters
\eZ\Publish\SPI\Persistence\Content\FieldValue $fieldValue
Returns
mixed
Reimplemented in eZ\Publish\Core\FieldType\Image\Type, eZ\Publish\Core\FieldType\BinaryBase\Type, eZ\Publish\Core\FieldType\Media\Type, eZ\Publish\Core\FieldType\MapLocation\Type, eZ\Publish\Core\FieldType\XmlText\Type, eZ\Publish\Core\FieldType\Url\Type, eZ\Publish\Core\FieldType\Keyword\Type, eZ\Publish\Core\FieldType\User\Type, eZ\Publish\Core\FieldType\Page\Type, and eZ\Publish\Core\FieldType\BinaryFile\Type.
Definition at line 224 of file FieldType.php.
References eZ\Publish\API\Repository\FieldType\fromHash().
    {
        return $this->fromHash( $fieldValue->data );
    }
eZ\Publish\Core\FieldType\FieldType::getSettingsSchema ()
Returns a schema for the settings expected by the FieldType
This implementation returns an array. where the key is the setting name, and the value is the default value for given setting and set to null if no particular default should be set.
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 66 of file FieldType.php.
References eZ\Publish\Core\FieldType\FieldType\$settingsSchema.
    {
        return $this->settingsSchema;
    }
eZ\Publish\Core\FieldType\FieldType::getSortInfo ($value) protected
Returns information for FieldValue->$sortKey relevant to the field type.
Return value is mixed. It should be something which is sensible for sorting.
It is up to the persistence implementation to handle those values. Common string and integer values are safe.
For the legacy storage it is up to the field converters to set this value in either sort_key_string or sort_key_int.
Parameters
mixed $value
Returns
mixed
Reimplemented in eZ\Publish\Core\FieldType\Image\Type, eZ\Publish\Core\FieldType\TextLine\Type, eZ\Publish\Core\FieldType\Float\Type, eZ\Publish\Core\FieldType\Selection\Type, eZ\Publish\Core\FieldType\Integer\Type, eZ\Publish\Core\FieldType\Page\Type, eZ\Publish\Core\FieldType\RelationList\Type, eZ\Publish\Core\FieldType\BinaryBase\Type, eZ\Publish\Core\FieldType\Country\Type, eZ\Publish\Core\FieldType\Relation\Type, eZ\Publish\Core\FieldType\EmailAddress\Type, eZ\Publish\Core\FieldType\XmlText\Type, eZ\Publish\Core\FieldType\DateAndTime\Type, eZ\Publish\Core\FieldType\TextBlock\Type, eZ\Publish\Core\FieldType\MapLocation\Type, eZ\Publish\Core\FieldType\Null\Type, eZ\Publish\Core\FieldType\Rating\Type, eZ\Publish\Core\FieldType\Url\Type, eZ\Publish\Core\FieldType\Keyword\Type, eZ\Publish\Core\FieldType\Author\Type, eZ\Publish\Core\FieldType\Checkbox\Type, and eZ\Publish\Core\FieldType\User\Type.
Definition at line 191 of file FieldType.php.
    {
        throw new \RuntimeException( "Not implemented, yet." );
    }
eZ\Publish\Core\FieldType\FieldType::getValidatorConfigurationSchema ()
Returns a schema for the validator configuration expected by the FieldType
See Also
FieldTypeInterface::getValidatorConfigurationSchema()
This implementation returns a three dimensional map containing for each validator configuration referenced by identifier a map of supported parameters which are defined by a type and a default value (see example).
array('stringLength' => array('minStringLength' => array('type' => 'int', 'default' => 0,), 'maxStringLength' => array('type' => 'int' 'default' => null,)),);
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 97 of file FieldType.php.
References eZ\Publish\Core\FieldType\FieldType\$validatorConfigurationSchema.
    {
        return $this->validatorConfigurationSchema;
    }
eZ\Publish\Core\FieldType\FieldType::internalAcceptValue ($inputValue) abstract protected
Implements the core of {
See Also
acceptValue()}.
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Reimplemented in eZ\Publish\Core\FieldType\Page\Type, eZ\Publish\Core\FieldType\TextLine\Type, eZ\Publish\Core\FieldType\Float\Type, eZ\Publish\Core\FieldType\Integer\Type, eZ\Publish\Core\FieldType\Selection\Type, eZ\Publish\Core\FieldType\RelationList\Type, eZ\Publish\Core\FieldType\Media\Type, eZ\Publish\Core\FieldType\EmailAddress\Type, eZ\Publish\Core\FieldType\XmlText\Type, eZ\Publish\Core\FieldType\Relation\Type, eZ\Publish\Core\FieldType\Null\Type, eZ\Publish\Core\FieldType\Image\Type, eZ\Publish\Core\FieldType\Country\Type, eZ\Publish\Core\FieldType\BinaryBase\Type, eZ\Publish\Core\FieldType\DateAndTime\Type, eZ\Publish\Core\FieldType\TextBlock\Type, eZ\Publish\Core\FieldType\MapLocation\Type, eZ\Publish\Core\FieldType\Rating\Type, eZ\Publish\Core\FieldType\Author\Type, eZ\Publish\Core\FieldType\Keyword\Type, eZ\Publish\Core\FieldType\User\Type, eZ\Publish\Core\FieldType\Checkbox\Type, eZ\Publish\Core\FieldType\Url\Type, and eZ\Publish\Core\FieldType\BinaryFile\Type.
eZ\Publish\Core\FieldType\FieldType::isEmptyValue ($value)
Returns if the given $value is considered empty by the field type
Default implementation, which performs a "==" check with the value returned by getEmptyValue(). Overwrite in the specific field type, if necessary.
Parameters
mixed $value
Returns
boolean
Reimplemented in eZ\Publish\Core\FieldType\TextLine\Type, eZ\Publish\Core\FieldType\Float\Type, eZ\Publish\Core\FieldType\Integer\Type, eZ\Publish\Core\FieldType\Image\Type, eZ\Publish\Core\FieldType\XmlText\Type, eZ\Publish\Core\FieldType\TextBlock\Type, eZ\Publish\Core\FieldType\MapLocation\Type, and eZ\Publish\Core\FieldType\Rating\Type.
Definition at line 250 of file FieldType.php.
References eZ\Publish\API\Repository\FieldType\getEmptyValue().
    {
        return $value === null || $value == $this->getEmptyValue();
    }
eZ\Publish\Core\FieldType\FieldType::isSearchable ()
Returns whether the field type is searchable
Returns
boolean
Implements eZ\Publish\API\Repository\FieldType.
Reimplemented in eZ\Publish\Core\FieldType\BinaryBase\Type, eZ\Publish\Core\FieldType\TextLine\Type, eZ\Publish\Core\FieldType\Integer\Type, eZ\Publish\Core\FieldType\Selection\Type, eZ\Publish\Core\FieldType\Country\Type, eZ\Publish\Core\FieldType\XmlText\Type, eZ\Publish\Core\FieldType\RelationList\Type, eZ\Publish\Core\FieldType\EmailAddress\Type, eZ\Publish\Core\FieldType\Relation\Type, eZ\Publish\Core\FieldType\DateAndTime\Type, eZ\Publish\Core\FieldType\MapLocation\Type, eZ\Publish\Core\FieldType\TextBlock\Type, eZ\Publish\Core\FieldType\Null\Type, eZ\Publish\Core\FieldType\Author\Type, eZ\Publish\Core\FieldType\Rating\Type, eZ\Publish\Core\FieldType\Keyword\Type, and eZ\Publish\Core\FieldType\Checkbox\Type.
Definition at line 234 of file FieldType.php.
    {
        return false;
    }
eZ\Publish\Core\FieldType\FieldType::toPersistenceValue ($value)
Converts a $value to a persistence value
Parameters
mixed $value
Returns
Reimplemented in eZ\Publish\Core\FieldType\Image\Type, eZ\Publish\Core\FieldType\BinaryBase\Type, eZ\Publish\Core\FieldType\XmlText\Type, eZ\Publish\Core\FieldType\MapLocation\Type, eZ\Publish\Core\FieldType\Url\Type, eZ\Publish\Core\FieldType\Page\Type, eZ\Publish\Core\FieldType\Keyword\Type, and eZ\Publish\Core\FieldType\User\Type.
Definition at line 203 of file FieldType.php.
References eZ\Publish\Core\FieldType\FieldType\getSortInfo(), and eZ\Publish\API\Repository\FieldType\toHash().
    {
        // @todo Evaluate if creating the sortKey in every case is really needed
        //       Couldn't this be retrieved with a method, which would initialize
        //       that info on request only?
        return new FieldValue(
            array(
                "data" => $this->toHash( $value ),
                "externalData" => null,
                "sortKey" => $this->getSortInfo( $value ),
            )
        );
    }
eZ\Publish\Core\FieldType\FieldType::validate (FieldDefinition $fieldDefinition, $fieldValue)
Validates a field based on the validators in the field definition
This is a base implementation, returning an empty array() that indicates that no validation errors occurred. Overwrite in derived types, if validation is supported.
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException
Parameters
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition The field definition of the field
\eZ\Publish\Core\FieldType\Value $fieldValue The field for which an action is performed
Returns
[]
Reimplemented in eZ\Publish\Core\FieldType\BinaryBase\Type, eZ\Publish\Core\FieldType\Image\Type, eZ\Publish\Core\FieldType\Selection\Type, eZ\Publish\Core\FieldType\Country\Type, eZ\Publish\Core\FieldType\Float\Type, eZ\Publish\Core\FieldType\Integer\Type, eZ\Publish\Core\FieldType\TextLine\Type, and eZ\Publish\Core\FieldType\EmailAddress\Type.
Definition at line 116 of file FieldType.php.
    {
        return array();
    }
eZ\Publish\Core\FieldType\FieldType::validateFieldSettings ($fieldSettings)
Validates the fieldSettings of a FieldDefinitionCreateStruct or FieldDefinitionUpdateStruct
Parameters
mixed $fieldSettings
Returns
[]
Reimplemented in eZ\Publish\Core\FieldType\Country\Type, eZ\Publish\Core\FieldType\XmlText\Type, eZ\Publish\Core\FieldType\DateAndTime\Type, eZ\Publish\Core\FieldType\TextBlock\Type, eZ\Publish\Core\FieldType\Media\Type, eZ\Publish\Core\FieldType\Page\Type, eZ\Publish\Core\FieldType\RelationList\Type, eZ\Publish\Core\FieldType\Selection\Type, and eZ\Publish\Core\FieldType\Relation\Type.
Definition at line 157 of file FieldType.php.
References eZ\Publish\API\Repository\FieldType\getFieldTypeIdentifier().
    {
        if ( !empty( $fieldSettings ) )
        {
            return array(
                new ValidationError(
                    "FieldType '%fieldType%' does not accept settings",
                    null,
                    array(
                        "fieldType" => $this->getFieldTypeIdentifier()
                    )
                )
            );
        }
        return array();
    }
eZ\Publish\Core\FieldType\FieldType::validateValidatorConfiguration ($validatorConfiguration)
Validates the validatorConfiguration of a FieldDefinitionCreateStruct or FieldDefinitionUpdateStruct
This is a base implementation, returning a validation error for each specified validator, since by default no validators are supported. Overwrite in derived types, if validation is supported.
Parameters
mixed $validatorConfiguration
Returns
[]
Reimplemented in eZ\Publish\Core\FieldType\BinaryBase\Type, eZ\Publish\Core\FieldType\Image\Type, eZ\Publish\Core\FieldType\Float\Type, eZ\Publish\Core\FieldType\Integer\Type, eZ\Publish\Core\FieldType\TextLine\Type, and eZ\Publish\Core\FieldType\EmailAddress\Type.
Definition at line 132 of file FieldType.php.
    {
        $validationErrors = array();
        foreach ( (array)$validatorConfiguration as $validatorIdentifier => $constraints )
        {
            $validationErrors[] = new ValidationError(
                "Validator '%validator%' is unknown",
                null,
                array(
                    "validator" => $validatorIdentifier
                )
            );
        }
        return $validationErrors;
    }
eZ\Publish\Core\FieldType\FieldType::validatorConfigurationFromHash ($validatorConfigurationHash)
Converts the given $validatorConfigurationHash to a validator configuration of the type
Default implementation, which just returns the given $validatorConfigurationHash, since the validator configuration is by convention an array for all internal field types. Overwrite this method, if necessary.
Parameters
array | hash | scalar | null $validatorConfigurationHash
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 359 of file FieldType.php.
    {
        return $validatorConfigurationHash;
    }
eZ\Publish\Core\FieldType\FieldType::validatorConfigurationToHash ($validatorConfiguration)
Converts the given $validatorConfiguration to a simple hash format
Default implementation, which just returns the given $validatorConfiguration, which is by convention an array for all internal field types. Overwrite this method, if necessary.
Parameters
mixed $validatorConfiguration
Returns
array|hash|scalar|null
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 341 of file FieldType.php.
    {
        return $validatorConfiguration;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\FieldType::$settingsSchema = array() protected
Definition at line 42 of file FieldType.php.
eZ\Publish\Core\FieldType\FieldType::$validatorConfigurationSchema = array() protected
Definition at line 55 of file FieldType.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/FieldType.php