ezp-next: eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\HttpClient\Stream Class Reference
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\HttpClient\Stream Class Reference
Public Member Functions
__construct ($server)
request ($method, $path, Message $message=null)
Protected Member Functions
getRequestHeaders (array $headers)
Detailed Description
Simple PHP stream based HTTP client.
Definition at line 18 of file Stream.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\HttpClient\Stream::__construct ($server)
Constructs a new REST client instance for the given $server.
Parameters
string $server Remote server location. Must include the used protocol.
Definition at line 39 of file Stream.php.
References eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\HttpClient\Stream\__construct().
    {
        $url = parse_url( rtrim( $server, '/' ) );
        $url += array(
            'scheme' => 'http',
            'host'   => null,
            'port'   => null,
            'user'   => null,
            'pass'   => null,
            'path'   => null,
        );
        if ( $url['user'] || $url['pass'] )
        {
            $this->headers['Authorization'] = 'Basic ' . base64_encode( "{$url['user']}:{$url['pass']}" );
        }
        $this->server = $url['scheme'] . '://' . $url['host'];
        if ( $url['port'] )
        {
            $this->server .= ':' . $url['port'];
        }
        $this->server .= $url['path'];
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\HttpClient\Stream::getRequestHeaders (array $headers) protected
Get formatted request headers
Merged with the default values.
Parameters
array $headers
Returns
string
Definition at line 149 of file Stream.php.
References eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\HttpClient\Stream\getRequestHeaders().
    {
        $requestHeaders = '';
        foreach ( $this->headers as $name => $value )
        {
            if ( !isset( $headers[$name] ) )
            {
                $requestHeaders .= "$name: $value\r\n";
            }
        }
        foreach ( $headers as $name => $value )
        {
            $requestHeaders .= "$name: $value\r\n";
        }
        return $requestHeaders;
    }
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\HttpClient\Stream::request ($method, $path, Message $message = null)
Execute a HTTP request to the remote server
Returns the result from the remote server.
Parameters
string $method
string $path
Message $message
Returns
Message
Implements eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\HttpClient.
Definition at line 75 of file Stream.php.
References eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\HttpClient\Stream\getRequestHeaders(), and eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\HttpClient\Stream\request().
    {
        $message = $message ?: new Message();
        $requestHeaders = $this->getRequestHeaders( $message->headers );
        $url = $this->server . $path;
        $contextOptions = array(
            'http' => array(
                'method'        => $method,
                'content'       => $message->body,
                'ignore_errors' => true,
                'header'        => $requestHeaders,
            ),
        );
        $httpFilePointer = @fopen(
            $url,
            'r',
            false,
            stream_context_create( $contextOptions )
        );
        // Check if connection has been established successfully
        if ( $httpFilePointer === false )
        {
            throw new ConnectionException( $this->server, $path, $method );
        }
        // Read request body
        $body = '';
        while ( !feof( $httpFilePointer ) )
        {
            $body .= fgets( $httpFilePointer );
        }
        $metaData   = stream_get_meta_data( $httpFilePointer );
        // This depends on PHP compiled with or without --curl-enable-streamwrappers
        $rawHeaders = isset( $metaData['wrapper_data']['headers'] ) ?
            $metaData['wrapper_data']['headers'] :
            $metaData['wrapper_data'];
        $headers    = array();
        foreach ( $rawHeaders as $lineContent )
        {
            // Extract header values
            if ( preg_match( '(^HTTP/(?P<version>\d+\.\d+)\s+(?P<status>\d+))S', $lineContent, $match ) )
            {
                $headers['version'] = $match['version'];
                $headers['status']  = (int)$match['status'];
            }
            else
            {
                list( $key, $value ) = explode( ':', $lineContent, 2 );
                $headers[$key] = ltrim( $value );
            }
        }
        return new Message(
            $headers,
            $body
        );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Solr/Content/Search/Gateway/HttpClient/Stream.php