ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime Class Reference
Public Member Functions
toStorageValue (FieldValue $value, StorageFieldValue $storageFieldValue)
toFieldValue (StorageFieldValue $value, FieldValue $fieldValue)
toStorageFieldDefinition (FieldDefinition $fieldDef, StorageFieldDefinition $storageDef)
toFieldDefinition (StorageFieldDefinition $storageDef, FieldDefinition $fieldDef)
getIndexColumn ()
Static Public Member Functions
static create ()
Protected Member Functions
generateDateIntervalXML (DateInterval $dateInterval)
getDateIntervalFromXML ($xmlText)
Detailed Description
Definition at line 24 of file DateAndTime.php.
Member Function Documentation
static eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime::create () static
Factory for current class
Note
Class should instead be configured as service if it gains dependencies.
Returns
DateAndTime
Definition at line 33 of file DateAndTime.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime\create().
    {
        return new self;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime::generateDateIntervalXML (DateInterval $dateInterval) protected
Generates the internal XML structure for $dateInterval, used for date adjustment
Parameters
\DateInterval $dateInterval
Returns
string The generated XML string
Definition at line 161 of file DateAndTime.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime\generateDateIntervalXML().
    {
        // Constructing XML structure
        $doc = new DOMDocument( '1.0', 'utf-8' );
        $root = $doc->createElement( 'adjustment' );
        $year = $doc->createElement( 'year' );
        $year->setAttribute( 'value', $dateInterval->format( '%y' ) );
        $root->appendChild( $year );
        unset( $year );
        $month = $doc->createElement( 'month' );
        $month->setAttribute( 'value', $dateInterval->format( '%m' ) );
        $root->appendChild( $month );
        unset( $month );
        $day = $doc->createElement( 'day' );
        $day->setAttribute( 'value', $dateInterval->format( '%d' ) );
        $root->appendChild( $day );
        unset( $day );
        $hour = $doc->createElement( 'hour' );
        $hour->setAttribute( 'value', $dateInterval->format( '%h' ) );
        $root->appendChild( $hour );
        unset( $hour );
        $minute = $doc->createElement( 'minute' );
        $minute->setAttribute( 'value', $dateInterval->format( '%i' ) );
        $root->appendChild( $minute );
        unset( $minute );
        $second = $doc->createElement( 'second' );
        $second->setAttribute( 'value', $dateInterval->format( '%s' ) );
        $root->appendChild( $second );
        unset( $second );
        $doc->appendChild( $root );
        return $doc->saveXML();
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime::getDateIntervalFromXML ($xmlText) protected
Generates a DateInterval object from $xmlText
Parameters
string $xmlText
Returns
Definition at line 208 of file DateAndTime.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime\getDateIntervalFromXML().
    {
        if ( empty( $xmlText ) )
            return;
        $xml = new SimpleXMLElement( $xmlText );
        $aIntervalString = array(
            (int)$xml->year['value'] . ' years',
            (int)$xml->month['value'] . ' months',
            (int)$xml->day['value'] . ' days',
            (int)$xml->hour['value'] . ' hours',
            (int)$xml->minute['value'] . ' minutes',
            (int)$xml->second['value'] . ' seconds',
        );
        return DateInterval::createFromDateString( implode( ', ', $aIntervalString ) );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime::getIndexColumn ()
Returns the name of the index column in the attribute table
Returns the name of the index column the datatype uses, which is either "sort_key_int" or "sort_key_string". This column is then used for filtering and sorting for this type.
Returns
string
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 149 of file DateAndTime.php.
    {
        return 'sort_key_int';
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime::toFieldDefinition (StorageFieldDefinition $storageDef, FieldDefinition $fieldDef)
Converts field definition data in $storageDef into $fieldDef
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageDef
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDef
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 97 of file DateAndTime.php.
References eZ\Publish\SPI\Persistence\Content\FieldValue\$data.
    {
        $useSeconds = (bool)$storageDef->dataInt2;
        $dateInterval = $this->getDateIntervalFromXML( $storageDef->dataText5 );
        $fieldDef->fieldTypeConstraints->fieldSettings = new FieldSettings(
            array(
                'defaultType' => $storageDef->dataInt1,
                'useSeconds' => $useSeconds,
                'dateInterval' => $dateInterval
            )
        );
        // Building default value
        switch ( $fieldDef->fieldTypeConstraints->fieldSettings['defaultType'] )
        {
            case DateAndTimeType::DEFAULT_CURRENT_DATE:
                $data = array(
                    'rfc850' => null,
                    'timestamp' => time(),
                );
                break;
            case DateAndTimeType::DEFAULT_CURRENT_DATE_ADJUSTED:
                if ( !$useSeconds )
                {
                    $dateInterval->s = 0;
                }
                $date = new DateTime;
                $date->add( $dateInterval );
                $data = array(
                    'rfc850' => null,
                    'timestamp' => $date->getTimestamp(),
                );
                break;
            default:
                $data = null;
        }
        $fieldDef->defaultValue->data = $data;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime::toFieldValue (StorageFieldValue $value, FieldValue $fieldValue)
Converts data from $value to $fieldValue
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldValue $value
\eZ\Publish\SPI\Persistence\Content\FieldValue $fieldValue
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 58 of file DateAndTime.php.
    {
        if ( $value->dataInt === null )
        {
            return;
        }
        $fieldValue->data = array(
            'rfc850' => null,
            'timestamp' => $value->dataInt,
        );
        $fieldValue->sortKey = $value->sortKeyInt;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime::toStorageFieldDefinition (FieldDefinition $fieldDef, StorageFieldDefinition $storageDef)
Converts field definition data in $fieldDef into $storageFieldDef
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDef
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageDef
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 78 of file DateAndTime.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime\generateDateIntervalXML().
    {
        $storageDef->dataInt2 = $fieldDef->fieldTypeConstraints->fieldSettings['useSeconds'] ? 1 : 0;
        $storageDef->dataInt1 = $fieldDef->fieldTypeConstraints->fieldSettings['defaultType'];
        if ( $fieldDef->fieldTypeConstraints->fieldSettings['defaultType'] === DateAndTimeType::DEFAULT_CURRENT_DATE_ADJUSTED )
        {
            $storageDef->dataText5 = $this->generateDateIntervalXML(
                $fieldDef->fieldTypeConstraints->fieldSettings['dateInterval']
            );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\DateAndTime::toStorageValue (FieldValue $value, StorageFieldValue $storageFieldValue)
Converts data from $value to $storageFieldValue
Parameters
\eZ\Publish\SPI\Persistence\Content\FieldValue $value
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldValue $storageFieldValue
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 44 of file DateAndTime.php.
    {
        // @todo: One should additionally store the timezone here. This could
        // be done in a backwards compatible way, I think…
        $storageFieldValue->dataInt = ( $value->data !== null ? $value->data['timestamp'] : null );
        $storageFieldValue->sortKeyInt = $value->sortKey;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/DateAndTime.php