ezp-next: eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler Class Reference
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler Class Reference
Public Member Functions
__construct (Handler $handler, Backend $backend)
createGroup (GroupCreateStruct $group)
updateGroup (GroupUpdateStruct $group)
deleteGroup ($groupId)
loadGroup ($groupId)
loadGroupByIdentifier ($identifier)
loadAllGroups ()
loadContentTypes ($groupId, $status=Type::STATUS_DEFINED)
load ($contentTypeId, $status=Type::STATUS_DEFINED)
loadByIdentifier ($identifier)
loadByRemoteId ($remoteId)
create (CreateStruct $contentType)
update ($typeId, $status, UpdateStruct $contentType)
delete ($contentTypeId, $status)
createDraft ($modifierId, $contentTypeId)
copy ($userId, $contentTypeId, $status)
unlink ($groupId, $contentTypeId, $status)
link ($groupId, $contentTypeId, $status)
getFieldDefinition ($id, $status)
addFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
removeFieldDefinition ($contentTypeId, $status, $fieldDefinitionId)
updateFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
publish ($contentTypeId)
Public Member Functions inherited from eZ\Publish\SPI\Persistence\Content\Type\Handler
create (CreateStruct $contentType)
Protected Attributes
$handler
$backend
Detailed Description
See Also
Todo:
Validate $status arguments
Definition at line 27 of file ContentTypeHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::__construct (Handler $handler, Backend $backend)
Setups current handler instance with reference to Handler object that created it.
Parameters
Handler $handler
Backend $backend The storage engine backend
Definition at line 45 of file ContentTypeHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler\$backend, and eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler\$handler.
    {
        $this->handler = $handler;
        $this->backend = $backend;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::addFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
Adds a new field definition to an existing Type.
This method creates a new version of the Type with the $fieldDefinition added. It does not update existing content objects depending on the field (default) values.
Parameters
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type is not found
Todo:
Add FieldDefintion?
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 466 of file ContentTypeHandler.php.
    {
        $list = $this->backend->find( 'Content\\Type', array( 'id' => $contentTypeId, 'status' => $status ) );
        if ( !isset( $list[0] ) )
            throw new NotFound( 'Content\\Type', "{$contentTypeId}' and status '{$status}" );
        $fieldDefinitionArr = (array)$fieldDefinition;
        $fieldDefinitionArr['_typeId'] = $contentTypeId;
        $fieldDefinitionArr['_status'] = $status;
        return $this->backend->create( 'Content\\Type\\FieldDefinition', $fieldDefinitionArr );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::copy ($userId, $contentTypeId, $status)
Copy a Type incl fields and group-relations from a given status to a new Type with status Type::STATUS_DRAFT
New Content Type will have $userId as creator / modifier, created / modified should be updated, new remoteId and identifier should be appended with '_' and new remoteId or another unique number.
Parameters
mixed $userId
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If user or type with provided status is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 338 of file ContentTypeHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler\create(), and eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler\load().
    {
        $type = $this->load( $contentTypeId, $status );
        // @todo Validate $userId
        $struct = new CreateStruct();
        foreach ( $struct as $property => $value )
        {
            $struct->$property = $type->$property;
        }
        $struct->created = $struct->modified = time();
        $struct->creatorId = $struct->modifierId = $userId;
        $struct->status = $status;
        $struct->identifier .= '_' . ( $struct->remoteId = md5( uniqid( get_class( $struct ), true ) ) );
        return $this->create( $struct );// this takes care of resetting _typeId and _status on fields
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::create (CreateStruct $contentType)
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\CreateStruct $contentType
Returns
Definition at line 232 of file ContentTypeHandler.php.
    {
        $contentTypeArr = (array)$contentType;
        unset( $contentTypeArr['fieldDefinitions'] );
        $contentTypeObj = $this->backend->create( 'Content\\Type', $contentTypeArr );
        foreach ( $contentType->fieldDefinitions as $field )
        {
            $contentTypeObj->fieldDefinitions[] = $this->backend->create(
                'Content\\Type\\FieldDefinition',
                array( '_typeId' => $contentTypeObj->id, '_status' => $contentTypeObj->status ) + (array)$field
            );
        }
        return $contentTypeObj;
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::createDraft ($modifierId, $contentTypeId)
Creates a draft of existing defined content type
Updates modified date, sets $modifierId and status to Type::STATUS_DRAFT on the new returned draft.
Parameters
mixed $modifierId
mixed $contentTypeId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type with defined status is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 299 of file ContentTypeHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler\load(), and eZ\Publish\SPI\Persistence\Content\Type\STATUS_DRAFT.
    {
        $contentType = $this->load( $contentTypeId );
        $contentType->modified = time();
        $contentType->modifierId = $modifierId;
        $contentType->status = Type::STATUS_DRAFT;
        $contentTypeArr = (array)$contentType;
        unset( $contentTypeArr['fieldDefinitions'] );
        $contentTypeObj = $this->backend->create( 'Content\\Type', $contentTypeArr, false );
        foreach ( $contentType->fieldDefinitions as $field )
        {
            $contentTypeObj->fieldDefinitions[] = $this->backend->create(
                'Content\\Type\\FieldDefinition',
                array(
                    '_typeId' => $contentTypeObj->id,
                    '_status' => $contentTypeObj->status
                ) + (array)$field,
                false
            );
        }
        return $contentTypeObj;
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::createGroup (GroupCreateStruct $group)
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group\CreateStruct $group
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 56 of file ContentTypeHandler.php.
    {
        $groupArr = (array)$group;
        return $this->backend->create( 'Content\\Type\\Group', $groupArr );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::delete ($contentTypeId, $status)
Parameters
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException If type is defined and still has content
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type is not found
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 269 of file ContentTypeHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\STATUS_DEFINED.
    {
        if ( Type::STATUS_DEFINED === $status && $this->backend->count( 'Content\\ContentInfo', array( 'contentTypeId' => $contentTypeId ) ) )
        {
            throw new BadStateException( '$contentTypeId', "Content of Type {$contentTypeId} still exists, can not delete" );
        }
        // This will throw if none are found
        $this->backend->deleteByMatch(
            'Content\\Type',
            array( 'id' => $contentTypeId, 'status' => $status )
        );
        // So will this, which means you can not delete types with no fields (fix?)
        $this->backend->deleteByMatch(
            'Content\\Type\\FieldDefinition',
            array( '_typeId' => $contentTypeId, '_status' => $status )
        );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::deleteGroup ($groupId)
Parameters
mixed $groupId
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException If type group contains types
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type group with id is not found
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 77 of file ContentTypeHandler.php.
    {
        if ( $this->backend->count( 'Content\\Type', array( 'groupIds' => $groupId ) ) )
        {
            throw new BadStateException( '$groupId', "Group {$groupId} still contains Types and can not be deleted" );
        }
        $this->backend->delete( 'Content\\Type\\Group', $groupId );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::getFieldDefinition ($id, $status)
Returns field definition for the given field definition id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If field definition is not found
Parameters
mixed $id
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 432 of file ContentTypeHandler.php.
    {
        $fieldDefinition = $this->backend->find(
            "Content\\Type\\FieldDefinition",
            array( "id" => $id, "_status" => $status )
        );
        if ( !isset( $fieldDefinition[0] ) )
            throw new NotFound(
                "Content\\Type\\FieldDefinition",
                array(
                    "id" => $id,
                    "status" => $status
                )
            );
        return $fieldDefinition[0];
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::link ($groupId, $contentTypeId, $status)
Link a content type group with a content type
Parameters
mixed $groupId
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If group or type with provided status is not found
\eZ\Publish\API\Repository\Exceptions\BadStateException If type is already part of group
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 402 of file ContentTypeHandler.php.
    {
        $list = $this->backend->find( 'Content\\Type', array( 'id' => $contentTypeId, 'status' => $status ) );
        if ( !isset( $list[0] ) )
            throw new NotFound( 'Content\\Type', "{$contentTypeId}' and status '{$status}" );
        $type = $list[0];
        if ( in_array( $groupId, $type->groupIds ) )
            throw new BadStateException( '$groupId', "Group {$groupId} is already linked to Type {$contentTypeId}" );
        if ( !$this->backend->load( 'Content\\Type\\Group', $groupId ) )
            throw new NotFound( 'Content\\Type\\Group', $groupId );
        $this->backend->updateByMatch(
            'Content\\Type',
            array( 'id' => $contentTypeId, 'status' => $status ),
            array( 'groupIds' => array_merge( $type->groupIds, array( $groupId ) ) )
        );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::load ($contentTypeId, $status = Type::STATUS_DEFINED)
Loads a content type by id and status
Parameters
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type with provided status is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 152 of file ContentTypeHandler.php.
    {
        $type = $this->backend->find(
            'Content\\Type',
            array( 'id' => $contentTypeId, 'status' => $status ),
            array(
                'fieldDefinitions' => array(
                    'type' => 'Content\\Type\\FieldDefinition',
                    'match' => array( '_typeId' => 'id', '_status' => 'status' )
                )
            )
        );
        if ( !$type )
            throw new NotFound( 'Content\\Type', "{$contentTypeId}' and status '{$status}" );
        return $type[0];
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::loadAllGroups ()
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 117 of file ContentTypeHandler.php.
    {
        return $this->backend->find( 'Content\\Type\\Group', array() );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::loadByIdentifier ($identifier)
Loads a (defined) content type by identifier
Parameters
string $identifier
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If defined type is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 180 of file ContentTypeHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\STATUS_DEFINED.
    {
        $type = $this->backend->find(
            'Content\\Type',
            array( 'identifier' => $identifier, 'status' => Type::STATUS_DEFINED ),
            array(
                'fieldDefinitions' => array(
                    'type' => 'Content\\Type\\FieldDefinition',
                    'match' => array( '_typeId' => 'id', '_status' => 'status' )
                )
            )
        );
        if ( !$type )
            throw new NotFound( 'Content\\Type', "{$identifier}' and status '" . Type::STATUS_DEFINED );
        return $type[0];
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::loadByRemoteId ($remoteId)
Loads a (defined) content type by remote id
Parameters
mixed $remoteId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If defined type is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 208 of file ContentTypeHandler.php.
References eZ\Publish\SPI\Persistence\Content\Type\STATUS_DEFINED.
    {
        $type = $this->backend->find(
            'Content\\Type',
            array( 'remoteId' => $remoteId, 'status' => Type::STATUS_DEFINED ),
            array(
                'fieldDefinitions' => array(
                    'type' => 'Content\\Type\\FieldDefinition',
                    'match' => array( '_typeId' => 'id', '_status' => 'status' )
                )
            )
        );
        if ( !$type )
            throw new NotFound( 'Content\\Type', "{$remoteId}' and status '" . Type::STATUS_DEFINED );
        return $type[0];
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::loadContentTypes ($groupId, $status = Type::STATUS_DEFINED)
Parameters
mixed $groupId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 128 of file ContentTypeHandler.php.
    {
        return $this->backend->find(
            'Content\\Type',
            array( 'groupIds' => $groupId, 'status' => $status ),
            array(
                'fieldDefinitions' => array(
                    'type' => 'Content\\Type\\FieldDefinition',
                    'match' => array( '_typeId' => 'id', '_status' => 'status' )
                )
            )
        );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::loadGroup ($groupId)
Parameters
mixed $groupId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type group with id is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 93 of file ContentTypeHandler.php.
    {
        return $this->backend->load( 'Content\\Type\\Group', $groupId );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::loadGroupByIdentifier ($identifier)
Parameters
string $identifier
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type group with id is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 105 of file ContentTypeHandler.php.
    {
        $group = $this->backend->find( 'Content\\Type\\Group', array( 'identifier' => $identifier ) );
        if ( !$group )
            throw new NotFound( 'Content\\Type\\Group', $identifier );
        return $group[0];
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::publish ($contentTypeId)
Update content objects
Updates content objects, depending on the changed field definitions.
A content type has a state which tells if its content objects yet have been adapted.
Flags the content type as updated.
Parameters
mixed $contentTypeId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type with $contentTypeId and Type::STATUS_DRAFT is not found
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 554 of file ContentTypeHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler\load(), eZ\Publish\SPI\Persistence\Content\Type\STATUS_DEFINED, and eZ\Publish\SPI\Persistence\Content\Type\STATUS_DRAFT.
    {
        $draftType = $this->load( $contentTypeId, Type::STATUS_DRAFT );
        try
        {
            $publishedType = $this->load( $contentTypeId );
        }
        catch ( NotFound $e )
        {
            // No published version of type, jump to last section where draft is promoted to defined
            GOTO updateType;
        }
        // @todo update content based on new type data change (field/scheme changes from $publishedType to $draftType)
        $this->backend->deleteByMatch(
            'Content\\Type',
            array( 'id' => $contentTypeId, 'status' => Type::STATUS_DEFINED )
        );
        $this->backend->deleteByMatch(
            'Content\\Type\\FieldDefinition',
            array( '_typeId' => $contentTypeId, '_status' => Type::STATUS_DEFINED )
        );
        updateType:
        {
            $this->backend->updateByMatch(
                'Content\\Type',
                array( 'id' => $contentTypeId, 'status' => Type::STATUS_DRAFT ),
                array( 'status' => Type::STATUS_DEFINED )
            );
            $this->backend->updateByMatch(
                'Content\\Type\\FieldDefinition',
                array(
                    '_typeId' => $contentTypeId,
                    '_status' => Type::STATUS_DRAFT,
                ),
                array( '_status' => Type::STATUS_DEFINED )
            );
        }
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::removeFieldDefinition ($contentTypeId, $status, $fieldDefinitionId)
Removes a field definition from an existing Type.
This method creates a new version of the Type with the field definition referred to by $fieldDefinitionId removed. It does not update existing content objects depending on the field (default) values.
Parameters
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
mixed $fieldDefinitionId
Returns
void
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If field is not found
Todo:
Add FieldDefinition?
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 494 of file ContentTypeHandler.php.
    {
        $this->backend->deleteByMatch(
            'Content\\Type\\FieldDefinition',
            array(
                '_typeId' => $contentTypeId,
                '_status' => $status,
                'id' => $fieldDefinitionId,
            )
        );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::unlink ($groupId, $contentTypeId, $status)
Unlink a content type group from a content type
Parameters
mixed $groupId
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If group or type with provided status is not found
\eZ\Publish\API\Repository\Exceptions\BadStateException If $groupId is last group on $contentTypeId or not a group assigned to type
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 366 of file ContentTypeHandler.php.
    {
        $list = $this->backend->find( 'Content\\Type', array( 'id' => $contentTypeId, 'status' => $status ) );
        if ( !isset( $list[0] ) )
            throw new NotFound( 'Content\\Type', "{$contentTypeId}' and status '{$status}" );
        $type = $list[0];
        if ( !in_array( $groupId, $type->groupIds ) )
            throw new BadStateException( '$groupId', "Group {$groupId} is not a group on Type {$contentTypeId}" );
        if ( !isset( $type->groupIds[1] ) )
            throw new BadStateException(
                '$groupId',
                "Group {$groupId} is last on Type {$contentTypeId}, delete type or add another group before unlinking"
            );
        if ( !$this->backend->load( 'Content\\Type\\Group', $groupId ) )
            throw new NotFound( 'Content\\Type\\Group', $groupId );
        $this->backend->updateByMatch(
            'Content\\Type',
            array( 'id' => $contentTypeId, 'status' => $status ),
            array( 'groupIds' => array_values( array_diff( $type->groupIds, array( $groupId ) ) ) )
        );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::update ($typeId, $status, UpdateStruct $contentType)
Parameters
mixed $typeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
\eZ\Publish\SPI\Persistence\Content\Type\UpdateStruct $contentType
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 252 of file ContentTypeHandler.php.
    {
        $contentTypeArr = (array)$contentType;
        $this->backend->updateByMatch(
            'Content\\Type',
            array( 'id' => $typeId, 'status' => $status ),
            $contentTypeArr
        );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::updateFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
This method updates the given $fieldDefinition on a Type.
This method creates a new version of the Type with the updated $fieldDefinition. It does not update existing content objects depending on the field (default) values.
Parameters
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If field is not found
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 522 of file ContentTypeHandler.php.
    {
        $fieldDefinitionArr = (array)$fieldDefinition;
        $updated = $this->backend->updateByMatch(
            'Content\\Type\\FieldDefinition',
            array(
                '_typeId' => $contentTypeId,
                '_status' => $status,
                'id' => $fieldDefinition->id,
            ),
            $fieldDefinitionArr
        );
        if ( !$updated )
            throw new NotFound( 'Content\\Type\\FieldDefinition', $fieldDefinition->id );
    }
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::updateGroup (GroupUpdateStruct $group)
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group\UpdateStruct $group
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 65 of file ContentTypeHandler.php.
    {
        $groupArr = (array)$group;
        $this->backend->update( 'Content\\Type\\Group', $groupArr['id'], $groupArr );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::$backend protected
Definition at line 37 of file ContentTypeHandler.php.
eZ\Publish\Core\Persistence\InMemory\ContentTypeHandler::$handler protected
Definition at line 32 of file ContentTypeHandler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/InMemory/ContentTypeHandler.php