ezp-next: eZ\Publish\Core\IO\Handler\Legacy Class Reference
eZ\Publish\Core\IO\Handler\Legacy Class Reference
Public Member Functions
__construct ($storageDirectory, LegacyKernel $legacyKernel=null)
setLegacyKernelClosure (\Closure $kernelClosure)
setLegacyKernel (LegacyKernel $kernel)
create (BinaryFileCreateStruct $createStruct)
delete ($path)
update ($path, BinaryFileUpdateStruct $updateFileStruct)
exists ($path)
load ($path)
getFileResource ($path)
getFileContents ($path)
getInternalPath ($path)
getExternalPath ($path)
Public Member Functions inherited from eZ\Publish\Core\IO\Handler
create (BinaryFileCreateStruct $createStruct)
getMetadata (MetadataHandler $metadataHandler, $path)
Protected Member Functions
getLegacyKernel ()
getDatatype ($mimeType)
getScope ($path)
getMimeTypeFromLocalFile ($path)
getStoragePath ($path)
removeStoragePath ($path)
Detailed Description
Legacy Io/Storage handler, based on eZ Cluster
Due to the legacy API, this handler has a few limitations:
ctime is not really supported, and will always have the same value as mtime
mtime can not be modified, and will always automatically be set depending on the server time upon each write operation
Definition at line 32 of file Legacy.php.
Constructor & Destructor Documentation
eZ\Publish\Core\IO\Handler\Legacy::__construct ($storageDirectory, LegacyKernel $legacyKernel = null)
Created Legacy handler instance
Parameters
string $storageDirectory
\eZ\Publish\Core\MVC\Legacy\Kernel $legacyKernel
Definition at line 65 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\Legacy\__construct().
    {
        if ( $legacyKernel )
        {
            $this->legacyKernel = $legacyKernel;
        }
        $this->storageDirectory = $storageDirectory;
    }
Member Function Documentation
eZ\Publish\Core\IO\Handler\Legacy::create (BinaryFileCreateStruct $createStruct)
Creates and stores a new BinaryFile based on the BinaryFileCreateStruct $file
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException If the target path already exists
Parameters
\eZ\Publish\SPI\IO\BinaryFileCreateStruct $createStruct
Returns
The newly created BinaryFile object
Definition at line 101 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\exists(), eZ\Publish\Core\IO\Handler\Legacy\getDatatype(), eZ\Publish\SPI\IO\BinaryFileCreateStruct\getInputStream(), eZ\Publish\Core\IO\Handler\Legacy\getLegacyKernel(), eZ\Publish\Core\IO\Handler\Legacy\getScope(), eZ\Publish\Core\IO\Handler\Legacy\getStoragePath(), and eZ\Publish\Core\IO\Handler\load().
    {
        if ( $this->exists( $createStruct->uri ) )
        {
            throw new InvalidArgumentException(
                "\$createFilestruct->uri",
                "file '" . $this->getStoragePath( $createStruct->uri ). "' already exists"
            );
        }
        $storagePath = $this->getStoragePath( $createStruct->uri );
        $scope = $this->getScope( $storagePath );
        $datatype = $this->getDatatype( $createStruct->mimeType );
        $clusterHandler = $this->getClusterHandler();
        $this->getLegacyKernel()->runCallback(
            function () use ( $createStruct, $storagePath, $datatype, $scope, $clusterHandler )
            {
                $clusterHandler->fileStoreContents(
                    $storagePath,
                    fread( $createStruct->getInputStream(), $createStruct->size ),
                    $scope,
                    $datatype
                );
            },
            false
        );
        return $this->load( $createStruct->uri );
    }
eZ\Publish\Core\IO\Handler\Legacy::delete ($path)
Deletes the existing BinaryFile with path $path
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If the file doesn't exist
Parameters
string $path
Implements eZ\Publish\Core\IO\Handler.
Definition at line 184 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\exists(), eZ\Publish\Core\IO\Handler\Legacy\getLegacyKernel(), and eZ\Publish\Core\IO\Handler\Legacy\getStoragePath().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        $storagePath = $this->getStoragePath( $path );
        $clusterHandler = $this->getClusterHandler();
        $this->getLegacyKernel()->runCallback(
            function () use ( $storagePath, $clusterHandler )
            {
                $clusterHandler->fileDelete( $storagePath );
            },
            false
        );
    }
eZ\Publish\Core\IO\Handler\Legacy::exists ($path)
Checks if the BinaryFile with path $path exists
Parameters
string $path
Returns
boolean
Implements eZ\Publish\Core\IO\Handler.
Definition at line 276 of file Legacy.php.
    {
        $path = $this->getStoragePath( $path );
        $clusterHandler = $this->getClusterHandler();
        return $this->getLegacyKernel()->runCallback(
            function () use ( $clusterHandler, $path )
            {
                return $clusterHandler->fileExists( $path );
            },
            false
        );
    }
eZ\Publish\Core\IO\Handler\Legacy::getDatatype ($mimeType) protected
Definition at line 132 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\Legacy\getDatatype().
    {
        return substr( $mimeType, 0, strpos( $mimeType, '/' ) );
    }
eZ\Publish\Core\IO\Handler\Legacy::getExternalPath ($path)
Removes the internal storage path from $path
Parameters
string $path
Returns
string
Implements eZ\Publish\Core\IO\Handler.
Definition at line 383 of file Legacy.php.
    {
        return $this->removeStoragePath( $path );
    }
eZ\Publish\Core\IO\Handler\Legacy::getFileContents ($path)
Returns the contents of the BinaryFile identified by $path
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException if the file couldn't be found
Parameters
string $path
Returns
string
Implements eZ\Publish\Core\IO\Handler.
Definition at line 360 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\exists().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        $storagePath = $this->getStoragePath( $path );
        $clusterHandler = $this->getClusterHandler();
        return $this->getLegacyKernel()->runCallback(
            function () use ( $storagePath, $clusterHandler )
            {
                return $clusterHandler->fileFetchContents( $storagePath );
            },
            false
        );
    }
eZ\Publish\Core\IO\Handler\Legacy::getFileResource ($path)
Returns a file resource to the BinaryFile identified by $path
Parameters
string $path
Exceptions
NotFoundException if $path doesn't exist
Returns
resource
Implements eZ\Publish\Core\IO\Handler.
Definition at line 342 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\exists().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( "BinaryFile", $path );
        }
        return $this->getFileResourceProvider()->getResource( $this->getStoragePath( $path ) );
    }
eZ\Publish\Core\IO\Handler\Legacy::getInternalPath ($path)
Returns the internal, handler level path for $path
Parameters
string $path
Returns
string
Implements eZ\Publish\Core\IO\Handler.
Definition at line 378 of file Legacy.php.
    {
        return $this->getStoragePath( $path );
    }
eZ\Publish\Core\IO\Handler\Legacy::getLegacyKernel () protected
Returns
LegacyKernel
Definition at line 87 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\Legacy\getLegacyKernel().
    {
        return $this->legacyKernel;
    }
eZ\Publish\Core\IO\Handler\Legacy::getMimeTypeFromLocalFile ($path) protected
Returns a mimeType from a local file, using fileinfo
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If file does not exist
Todo:
If legacy path is made available then this function can use that to skip executing legacy kernel
Parameters
string $path
Returns
string
Definition at line 475 of file Legacy.php.
    {
        $returnValue = $this->getLegacyKernel()->runCallback(
            function () use ( $path )
            {
                if ( !is_file( $path ) )
                    return null;
                $fileInfo = new finfo( FILEINFO_MIME_TYPE );
                return $fileInfo->file( $path );
            },
            false
        );
        if ( $returnValue === null )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        return $returnValue;
    }
eZ\Publish\Core\IO\Handler\Legacy::getScope ($path) protected
Maps a URI to a scope.
Note that mediafile & binaryfile can't be distinguished from each other using the path alone, since they're stored in the same directory. We consider that a file of mimetype media will be a mediafile, and other binary files will be scoped binaryfile
Exceptions
InvalidArgumentException If $path isn't a legacy compatible storage path
Parameters
string $path
Returns
string|false The scope, defaulting to UNKNOWN_SCOPE
Definition at line 148 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\Legacy\getScope().
    {
        $pathArray = explode( DIRECTORY_SEPARATOR, $path );
        if ( count( $pathArray ) < 5 )
            throw new InvalidArgumentException( "\$path", "'$path' isn't a Legacy compatible storage path" );
        $storagePrefix = $pathArray[3];
        $mimeType = $pathArray[4];
        if ( $storagePrefix === 'images' )
        {
            return 'images';
        }
        if ( $storagePrefix === 'original' )
        {
            if ( $mimeType === 'video' || $mimeType === 'audio' )
            {
                return 'mediafile';
            }
            else
            {
                return 'binaryfile';
            }
        }
        return 'UNKNOWN_SCOPE';
    }
eZ\Publish\Core\IO\Handler\Legacy::getStoragePath ($path) protected
Transforms a path in a storage path using the $storageDirectory
Parameters
string $path
Returns
string
Definition at line 502 of file Legacy.php.
    {
        if ( $this->storageDirectory )
            $path = $this->storageDirectory . DIRECTORY_SEPARATOR . $path;
        return $path;
    }
eZ\Publish\Core\IO\Handler\Legacy::load ($path)
Loads the BinaryFile identified by $path
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If no file identified by $path exists
Parameters
string $path
Returns
Implements eZ\Publish\Core\IO\Handler.
Definition at line 298 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\exists().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        $storagePath = $this->getStoragePath( $path );
        $metaData = $this->getLegacyKernel()->runCallback(
            function () use ( $storagePath )
            {
                $clusterFile = eZClusterFileHandler::instance( $storagePath );
                return $clusterFile->metaData;
            },
            false
        );
        $file = new BinaryFile();
        $file->uri = $path;
        $file->mtime = new DateTime();
        $file->mtime->setTimestamp( $metaData['mtime'] );
        $file->size = $metaData['size'];
        // will only work with some ClusterFileHandlers (DB based ones, not with FS ones)
        if ( isset( $metaData['datatype'] ) )
        {
            $file->mimeType = $metaData['datatype'];
        }
        $file->uri = $file->uri;
        return $file;
    }
eZ\Publish\Core\IO\Handler\Legacy::removeStoragePath ($path) protected
Definition at line 509 of file Legacy.php.
    {
        if ( !$this->storageDirectory )
        {
            return $path;
        }
        if ( strpos( $path, $this->storageDirectory . DIRECTORY_SEPARATOR ) !== 0 )
        {
            throw new InvalidArgumentException( '$path', "Storage directory not found in $path" );
        }
        return substr( $path, strlen( $this->storageDirectory ) + 1 );
    }
eZ\Publish\Core\IO\Handler\Legacy::setLegacyKernel (LegacyKernel $kernel)
Definition at line 79 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\Legacy\setLegacyKernel().
    {
        $this->legacyKernel = $kernel;
    }
eZ\Publish\Core\IO\Handler\Legacy::setLegacyKernelClosure (\Closure $kernelClosure)
Definition at line 74 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\Legacy\setLegacyKernelClosure().
    {
        $this->legacyKernel = $kernelClosure();
    }
eZ\Publish\Core\IO\Handler\Legacy::update ($path, BinaryFileUpdateStruct $updateFileStruct)
Updates the file identified by $path with data from $updateFile
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If the source path doesn't exist
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException If the target path already exists
Parameters
string $path
\eZ\Publish\SPI\IO\BinaryFileUpdateStruct $updateFileStruct
Returns
The updated BinaryFile
Implements eZ\Publish\Core\IO\Handler.
Definition at line 212 of file Legacy.php.
References eZ\Publish\Core\IO\Handler\exists(), eZ\Publish\SPI\IO\BinaryFileUpdateStruct\getInputStream(), eZ\Publish\Core\IO\Handler\Legacy\getLegacyKernel(), and eZ\Publish\Core\IO\Handler\Legacy\getStoragePath().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        $destinationPath = $updateFileStruct->uri;
        if ( isset( $updateFileStruct->uri ) && $updateFileStruct->uri !== $path )
        {
            if ( $this->exists( $updateFileStruct->uri ) )
            {
                throw new InvalidArgumentException(
                    "\$updateFileStruct->uri",
                    "File '" . $this->getStoragePath( $updateFileStruct->uri ). "' already exists"
                );
            }
            $updateFileStruct->uri = $this->getStoragePath( $updateFileStruct->uri );
        }
        $storagePath = $this->getStoragePath( $path );
        $clusterHandler = $this->getClusterHandler();
        $this->getLegacyKernel()->runCallback(
            function () use ( $storagePath, $updateFileStruct, $clusterHandler )
            {
                // path
                if ( $updateFileStruct->uri !== null && $updateFileStruct->uri != $storagePath )
                {
                    $clusterHandler->fileMove( $storagePath, $updateFileStruct->uri );
                    $storagePath = $updateFileStruct->uri;
                }
                $resource = $updateFileStruct->getInputStream();
                if ( $resource !== null )
                {
                    $binaryUpdateData = fread( $resource, $updateFileStruct->size );
                    $clusterFile = eZClusterFileHandler::instance( $storagePath );
                    $metaData = $clusterFile->metaData;
                    $scope = isset( $metaData['scope'] ) ? $metaData['scope'] : false;
                    $datatype = isset( $metaData['datatype'] ) ? $metaData['datatype'] : false;
                    $clusterFile->storeContents( $binaryUpdateData, $scope, $datatype );
                    // Unfortunately required due to insufficient handly of in memory cache in eZDFSFileHandler...
                    if ( isset( $GLOBALS['eZClusterInfo'][$storagePath] ) )
                    {
                        unset( $GLOBALS['eZClusterInfo'][$storagePath] );
                    }
                }
            },
            false
        );
        return $this->load( $destinationPath );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/IO/Handler/Legacy.php