ezp-next: eZ\Publish\Core\Persistence\InMemory\LocationHandler Class Reference
eZ\Publish\Core\Persistence\InMemory\LocationHandler Class Reference
Public Member Functions
__construct (Handler $handler, Backend $backend)
load ($locationId)
loadLocationsByContent ($contentId, $rootLocationId=null)
loadByRemoteId ($remoteId)
copySubtree ($sourceId, $destinationParentId)
move ($sourceId, $destinationParentId)
markSubtreeModified ($locationId, $timestamp=null)
hide ($id)
unHide ($id)
swap ($locationId1, $locationId2)
update (UpdateStruct $location, $locationId)
create (CreateStruct $locationStruct)
removeSubtree ($locationId)
setSectionForSubtree ($locationId, $sectionId)
storeUrlAliasPath ($path, $locationId, $languageCode=null, $alwaysAvailable=false)
createCustomUrlAlias ($alias, $locationId, $forwarding=false, $languageCode=null, $alwaysAvailable=false)
createUrlHistoryEntry ($historicUrl, $locationId)
listUrlsForLocation ($locationId, $urlType)
removeUrlsForLocation ($locationId, array $urlIdentifier)
getPath ($locationId, $language)
delete ($locationId)
loadByParentId ($locationId)
changeMainLocation ($contentId, $locationId)
Public Member Functions inherited from eZ\Publish\SPI\Persistence\Content\Location\Handler
create (CreateStruct $location)
Public Attributes
const CHARS_ACCENT = 'ÀÁÂÃÄÅàáâãäåÒÓÔÕÖØòóôõöøÈÉÊËéèêëÇçÌÍÎÏìíîïÙÚÛÜùúûüÿÑñ'
const CHARS_NOACCENT = 'AAAAAAaaaaaaOOOOOOooooooEEEEeeeeCcIIIIiiiiUUUUuuuuyNn'
Protected Member Functions
getSubtreeLocations ($location, &$locations=array())
Protected Attributes
$handler
$backend
Detailed Description
See Also
eZ
Definition at line 22 of file LocationHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\InMemory\LocationHandler::__construct (Handler $handler, Backend $backend)
Setups current handler instance with reference to Handler object that created it.
Parameters
Handler $handler
Backend $backend The storage engine backend
Definition at line 44 of file LocationHandler.php.
References eZ\Publish\Core\Persistence\InMemory\LocationHandler\$backend, and eZ\Publish\Core\Persistence\InMemory\LocationHandler\$handler.
    {
        $this->handler = $handler;
        $this->backend = $backend;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\InMemory\LocationHandler::changeMainLocation ($contentId, $locationId)
Changes main location of content identified by given $contentId to location identified by given $locationId
Parameters
mixed $contentId
mixed $locationId
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 591 of file LocationHandler.php.
References eZ\Publish\Core\Persistence\InMemory\LocationHandler\setSectionForSubtree().
    {
        $this->backend->updateByMatch(
            "Content\\Location",
            array( "contentId" => $contentId ),
            array( "mainLocationId" => $locationId )
        );
        $parentLocation = $this->backend->load(
            "Content\\Location",
            $this->backend->load( "Content\\Location", $locationId )->parentId
        );
        $parentContent = $this->backend->load(
            "Content\\ContentInfo",
            $parentLocation->contentId
        );
        $this->setSectionForSubtree( $locationId, $parentContent->sectionId );
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::copySubtree ($sourceId, $destinationParentId)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 139 of file LocationHandler.php.
References eZ\Publish\Core\Persistence\InMemory\LocationHandler\changeMainLocation(), eZ\Publish\Core\Persistence\InMemory\LocationHandler\create(), eZ\Publish\Core\Persistence\InMemory\LocationHandler\getSubtreeLocations(), eZ\Publish\Core\Persistence\InMemory\LocationHandler\load(), and eZ\Publish\Core\Persistence\InMemory\LocationHandler\setSectionForSubtree().
    {
        $sourceLocation = $this->load( $sourceId );
        $children = $this->getSubtreeLocations( $sourceLocation );
        $parentLocation = $this->load( $destinationParentId );
        $contentMap = array();
        $locationMap = array(
            $children[0]->parentId => array(
                "id" => $destinationParentId,
                "hidden" => $parentLocation->hidden,
                "invisible" => $parentLocation->invisible
            )
        );
        $locations = array();
        foreach ( $children as $child )
        {
            $locations[$child->contentId][] = $child->id;
        }
        $time = time();
        $mainLocations = array();
        $mainLocationsUpdate = array();
        foreach ( $children as $index => $child )
        {
            $originalContentInfo = $this->handler->contentHandler()->loadContentInfo( $child->contentId );
            if ( !isset( $contentMap[$child->contentId] ) )
            {
                $content = $this->handler->contentHandler()->copy(
                    $child->contentId,
                    $originalContentInfo->currentVersionNo
                );
                $newContentId = $content->versionInfo->contentInfo->id;
                $content = $this->handler->contentHandler()->publish(
                    $newContentId,
                    $content->versionInfo->versionNo,
                    new MetadataUpdateStruct(
                        array(
                            "publicationDate" => $time,
                            "modificationDate" => $time
                        )
                    )
                );
                $contentMap[$child->contentId] = $newContentId;
            }
            $createStruct = new CreateStruct();
            $createStruct->contentVersion = $originalContentInfo->currentVersionNo;
            $createStruct->hidden = $child->hidden;
            $createStruct->pathIdentificationString = $child->pathIdentificationString;
            $createStruct->priority = $child->priority;
            $createStruct->remoteId = md5( uniqid( get_class( $this ), true ) );
            $createStruct->sortField = $child->sortField;
            $createStruct->sortOrder = $child->sortOrder;
            $createStruct->contentId = $contentMap[$child->contentId];
            $createStruct->parentId = $locationMap[$child->parentId]["id"];
            $createStruct->invisible = $createStruct->hidden ||
                $locationMap[$child->parentId]["hidden"] ||
                $locationMap[$child->parentId]["invisible"];
            // Use content main node if already set, otherwise use this node as main
            if ( isset( $mainLocations[$child->contentId] ) )
            {
                $createStruct->mainLocationId = $locationMap[$mainLocations[$child->contentId]]["id"];
            }
            else
            {
                $createStruct->mainLocationId = true;
                $mainLocations[$child->contentId] = $child->id;
                // If needed mark for later update
                if (
                    in_array( $child->mainLocationId, $locations[$child->contentId] ) &&
                    count( $locations[$child->contentId] ) > 1 &&
                    $child->id !== $child->mainLocationId
                )
                {
                    $mainLocationsUpdate[$child->contentId] = $child->mainLocationId;
                }
            }
            $newLocation = $this->create( $createStruct );
            $locationMap[$child->id] = array(
                "id" => $newLocation->id,
                "hidden" => $newLocation->hidden,
                "invisible" => $newLocation->invisible
            );
            if ( $index === 0 ) $copiedSubtreeRootLocation = $newLocation;
        }
        // Update main locations
        foreach ( $mainLocationsUpdate as $contentId => $mainLocationId )
        {
            $this->changeMainLocation(
                $contentMap[$contentId],
                $locationMap[$mainLocationId]["id"]
            );
        }
        // If subtree root is main location for its content, update subtree section to the one of the
        // parent location content
        if ( $copiedSubtreeRootLocation->mainLocationId === $copiedSubtreeRootLocation->id )
        {
            $this->setSectionForSubtree(
                $copiedSubtreeRootLocation->id,
                $this->handler->contentHandler()->loadContentInfo( $this->load( $destinationParentId )->contentId )->sectionId
            );
        }
        return $copiedSubtreeRootLocation;
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::create (CreateStruct $locationStruct)
See Also
eZ
Definition at line 403 of file LocationHandler.php.
References eZ\Publish\Core\Persistence\InMemory\LocationHandler\load().
    {
        $parentId = $locationStruct->parentId;
        $parent = $this->load( $parentId );
        $params = (array)$locationStruct;
        $params['parentId'] = $parentId;
        $params['depth'] = $parent->depth + 1;
        $params['hidden'] = (bool)$locationStruct->hidden;
        if ( !isset( $params['remoteId'] ) )
        {
            $params['remoteId'] = md5( uniqid( 'Content\\Location', true ) );
        }
        // Creation, then update for pathString/pathIdentificationString/mainLocationId
        $mainLocationId = null;
        $otherLocationsForContent = $this->backend->find( 'Content\\Location', array( 'contentId' => $locationStruct->contentId ) );
        if ( !empty( $otherLocationsForContent ) )
        {
            $mainLocationId = $otherLocationsForContent[0]->id;
        }
        $vo = $this->backend->create( 'Content\\Location', $params );
        $pathString = $parent->pathString . $vo->id . '/';
        $this->backend->update(
            'Content\\Location',
            $vo->id,
            array(
                'pathString' => $pathString,
                'pathIdentificationString' => $this->getPathIdentificationString( $vo ),
                'mainLocationId' => isset( $mainLocationId ) ? $mainLocationId : $vo->id
            )
        );
        return $this->load( $vo->id );
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::createCustomUrlAlias ($alias, $locationId, $forwarding = false, $languageCode = null, $alwaysAvailable = false)
See Also
eZ
Definition at line 492 of file LocationHandler.php.
    {
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::createUrlHistoryEntry ($historicUrl, $locationId)
See Also
eZ
Definition at line 499 of file LocationHandler.php.
    {
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::delete ($locationId)
Removes a location from its $locationId (but not its descendants) Content which looses its main Location will get the first of its other Locations assigned as the new main Location. If content has no location left, it's removed from backend
Parameters
mixed $locationId
Definition at line 532 of file LocationHandler.php.
References eZ\Publish\Core\Persistence\InMemory\LocationHandler\load().
    {
        $location = $this->load( $locationId );
        $this->backend->delete( 'Content\\Location', $locationId );
        $remainingLocations = $this->backend->find( 'Content\\Location', array( 'contentId' => $location->contentId ) );
        // If no remaining location for associated content, remove the content as well
        // Else, update the mainLocationId if needed
        if ( empty( $remainingLocations ) )
        {
            try
            {
                $this->handler->contentHandler()->deleteContent( $location->contentId );
            }
            // Ignoring a NotFound exception since the content handler also takes care of removing itself and locations
            catch ( NotFound $e )
            {
            }
        }
        else
        {
            $this->backend->updateByMatch(
                'Content\\Location',
                array( 'contentId' => $location->contentId ),
                array( 'mainLocationId' => $remainingLocations[0]->id )
            );
        }
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::getPath ($locationId, $language)
See Also
eZ
Definition at line 520 of file LocationHandler.php.
    {
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::getSubtreeLocations ($location, & $locations = array()) protected
Get all subtree locations for the given location (including), sorted by path string
Parameters
\eZ\Publish\SPI\Persistence\Content\Location $location
array $locations
Returns
array
Definition at line 115 of file LocationHandler.php.
    {
        if ( empty( $locations ) ) $locations[] = $location;
        $subLocations = $this->backend->find( "Content\\Location", array( "parentId" => $location->id ) );
        usort(
            $subLocations,
            function ( $subLocationA, $subLocationB )
            {
                return strnatcmp( $subLocationA->pathString, $subLocationB->pathString );
            }
        );
        foreach ( $subLocations as $subLocation )
        {
            $locations[] = $subLocation;
            $this->getSubtreeLocations( $subLocation, $locations );
        }
        return $locations;
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::hide ($id)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 305 of file LocationHandler.php.
    {
        $this->backend->update( 'Content\\Location', $id, array( 'hidden' => true, 'invisible' => true ) );
        $locationVO = $this->backend->load( 'Content\\Location', $id );
        $this->backend->updateByMatch(
            "Content\\Location",
            array( "pathString" => "{$locationVO->pathString}%" ),
            array( "invisible" => true )
        );
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::listUrlsForLocation ($locationId, $urlType)
See Also
eZ
Definition at line 506 of file LocationHandler.php.
    {
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::load ($locationId)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 53 of file LocationHandler.php.
    {
        return $this->backend->load( 'Content\\Location', $locationId );
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::loadByParentId ($locationId)
Returns locations given a parent $locationId.
Todo:
Requires approbation
Parameters
mixed $locationId
Returns
[]
Definition at line 568 of file LocationHandler.php.
References eZ\Publish\Core\Persistence\InMemory\LocationHandler\load().
    {
        $result = $this->backend->find( "Content\\Location", array( "parentId" => $locationId ) );
        // If no result is found this might be caused by an unexisting location ID.
        // We call load() to trigger a NotFound exception in such case for consistencies
        // across the API.
        if ( empty( $result ) )
        {
            $this->load( $locationId );
        }
        return $result;
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::loadByRemoteId ($remoteId)
Loads the data for the location identified by $remoteId.
Parameters
string $remoteId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException
Returns
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 92 of file LocationHandler.php.
    {
        $locations = $this->backend->find(
            'Content\\Location',
            array( 'remoteId' => $remoteId )
        );
        if ( empty( $locations ) )
            throw new NotFound( 'Location by remote id', $remoteId );
        else if ( isset( $locations[1] ) )
            throw new \RuntimeException( "Several Locations found with same remote id: {$remoteId}" );
        return $locations[0];
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::loadLocationsByContent ($contentId, $rootLocationId = null)
Loads all locations for $contentId, optionally limited to a sub tree identified by $rootLocationId
Parameters
int $contentId
int $rootLocationId
Todo:
Add support for $rootLocationId when not child of node 1
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 69 of file LocationHandler.php.
    {
        if ( $rootLocationId )
            return $this->backend->find(
                'Content\\Location',
                array( 'contentId' => $contentId, 'pathString' => "%/{$rootLocationId}/%" )
            );
        return $this->backend->find(
            'Content\\Location',
            array( 'contentId' => $contentId )
        );
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::markSubtreeModified ($locationId, $timestamp = null)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 298 of file LocationHandler.php.
    {
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::move ($sourceId, $destinationParentId)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 258 of file LocationHandler.php.
References eZ\Publish\Core\Persistence\InMemory\LocationHandler\load().
    {
        $vo = $this->load( $sourceId );
        $newParentVO = $this->load( $destinationParentId );
        $oldPathString = $vo->pathString;
        $newPathString = $newParentVO->pathString . $sourceId . '/';
        $oldPathIdentificationString = $vo->pathIdentificationString;
        $newPathIdentificationString = '';
        if ( $newParentVO->parentId == 1 )
            $newPathIdentificationString = $this->getStrippedContentName( $vo );
        else
            $newPathIdentificationString = $this->getPathIdentificationString( $newParentVO ) . '/' . $this->getStrippedContentName( $vo );
        $this->backend->update(
            'Content\\Location',
            $sourceId,
            array(
                'parentId' => $destinationParentId,
                'pathString' => $newPathString,
                'pathIdentificationString' => $newPathIdentificationString
            )
        );
        $children = $this->backend->find( 'Content\\Location', array( 'pathString' => "$vo->pathString%" ) );
        foreach ( $children as $child )
        {
            $this->backend->update(
                'Content\\Location',
                $child->id,
                array(
                    'pathString' => str_replace( $oldPathString, $newPathString, $child->pathString ),
                    'pathIdentificationString' => str_replace( $oldPathIdentificationString, $newPathIdentificationString, $child->pathIdentificationString )
                )
            );
        }
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::removeSubtree ($locationId)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 440 of file LocationHandler.php.
References eZ\Publish\Core\Persistence\InMemory\LocationHandler\load().
    {
        $location = $this->load( $locationId );
        // Begin recursive call on children, if any
        $directChildren = $this->backend->find( 'Content\\Location', array( 'parentId' => $locationId ) );
        if ( !empty( $directChildren ) )
        {
            foreach ( $directChildren as $child )
            {
                $this->removeSubtree( $child->id );
            }
        }
        $this->delete( $locationId );
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::removeUrlsForLocation ($locationId, array $urlIdentifier)
See Also
eZ
Definition at line 513 of file LocationHandler.php.
    {
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::setSectionForSubtree ($locationId, $sectionId)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 460 of file LocationHandler.php.
References eZ\Publish\Core\Persistence\InMemory\LocationHandler\load().
    {
        $location = $this->load( $locationId );
        $aContentIds = array( $location->contentId );
        $children = $this->backend->find( 'Content\\Location', array( 'pathString' => "$location->pathString%" ) );
        foreach ( $children as $child )
        {
            // Only get main locations
            if ( $child->mainLocationId == $child->id )
            {
                $aContentIds[] = $child->contentId;
            }
        }
        $this->backend->updateByMatch(
            'Content\\ContentInfo',
            array( 'id' => $aContentIds ),
            array( 'sectionId' => $sectionId ),
            true
        );
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::storeUrlAliasPath ($path, $locationId, $languageCode = null, $alwaysAvailable = false)
See Also
eZ
Definition at line 485 of file LocationHandler.php.
    {
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::swap ($locationId1, $locationId2)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 364 of file LocationHandler.php.
    {
        $location1 = $this->backend->load( 'Content\\Location', $locationId1 );
        $content1 = $this->backend->load( 'Content', $location1->contentId );
        $location2 = $this->backend->load( 'Content\\Location', $locationId2 );
        $content2 = $this->backend->load( 'Content', $location2->contentId );
        $this->backend->update(
            'Content\\Location',
            $locationId1,
            array(
                'contentId' => $location2->contentId,
            )
        );
        $this->backend->update(
            'Content\\Location',
            $locationId2,
            array(
                'contentId' => $location1->contentId,
            )
        );
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::unHide ($id)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 320 of file LocationHandler.php.
    {
        $this->backend->update( 'Content\\Location', $id, array( 'hidden' => false, 'invisible' => false ) );
        $locationVO = $this->backend->load( 'Content\\Location', $id );
        $hiddenLocations = $this->backend->find(
            "Content\\Location",
            array(
                "pathString" => "{$locationVO->pathString}%",
                "hidden" => true
            )
        );
        $invisibleLocations = $this->backend->find(
            "Content\\Location",
            array(
                "pathString" => "{$locationVO->pathString}%",
                "invisible" => true,
                "hidden" => false
            )
        );
        $locationsToUnhide = array();
        // Loop against all invisible locations and figure out
        // if they are under a hidden one.
        // If this is the case, the location won't be made visible
        foreach ( $invisibleLocations as $loc )
        {
            foreach ( $hiddenLocations as $hiddenLoc )
            {
                if ( strpos( $loc->pathString, $hiddenLoc->pathString ) === 0 )
                {
                    continue 2;
                }
            }
            $locationsToUnhide[] = $loc->id;
        }
        $this->backend->updateByMatch( 'Content\\Location', array( 'id' => $locationsToUnhide ), array( 'invisible' => false ) );
    }
eZ\Publish\Core\Persistence\InMemory\LocationHandler::update (UpdateStruct $location, $locationId)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Handler.
Definition at line 391 of file LocationHandler.php.
    {
        return $this->backend->update(
            'Content\\Location',
            $locationId,
            (array)$location
        );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\InMemory\LocationHandler::$backend protected
Definition at line 36 of file LocationHandler.php.
eZ\Publish\Core\Persistence\InMemory\LocationHandler::$handler protected
Definition at line 31 of file LocationHandler.php.
const eZ\Publish\Core\Persistence\InMemory\LocationHandler::CHARS_ACCENT = 'ÀÁÂÃÄÅàáâãäåÒÓÔÕÖØòóôõöøÈÉÊËéèêëÇçÌÍÎÏìíîïÙÚÛÜùúûüÿÑñ'
Definition at line 24 of file LocationHandler.php.
const eZ\Publish\Core\Persistence\InMemory\LocationHandler::CHARS_NOACCENT = 'AAAAAAaaaaaaOOOOOOooooooEEEEeeeeCcIIIIiiiiUUUUuuuuyNn'
Definition at line 26 of file LocationHandler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/InMemory/LocationHandler.php