ezp-next: eZ\Publish\Core\Repository\RoleService Class Reference
eZ\Publish\Core\Repository\RoleService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, Handler $userHandler, array $settings=array())
createRole (APIRoleCreateStruct $roleCreateStruct)
updateRole (APIRole $role, RoleUpdateStruct $roleUpdateStruct)
addPolicy (APIRole $role, APIPolicyCreateStruct $policyCreateStruct)
removePolicy (APIRole $role, APIPolicy $policy)
updatePolicy (APIPolicy $policy, APIPolicyUpdateStruct $policyUpdateStruct)
loadRole ($id)
loadRoleByIdentifier ($identifier)
loadRoles ()
deleteRole (APIRole $role)
loadPoliciesByUserId ($userId)
assignRoleToUserGroup (APIRole $role, UserGroup $userGroup, RoleLimitation $roleLimitation=null)
unassignRoleFromUserGroup (APIRole $role, UserGroup $userGroup)
assignRoleToUser (APIRole $role, User $user, RoleLimitation $roleLimitation=null)
unassignRoleFromUser (APIRole $role, User $user)
getRoleAssignments (APIRole $role)
getRoleAssignmentsForUser (User $user, $inherited=false)
getRoleAssignmentsForUserGroup (UserGroup $userGroup)
newRoleCreateStruct ($name)
newPolicyCreateStruct ($module, $function)
newPolicyUpdateStruct ()
newRoleUpdateStruct ()
buildDomainPolicyObject (SPIPolicy $policy, SPIRole $role=null)
buildDomainUserRoleAssignmentObject (SPIRoleAssignment $spiRoleAssignment, User $user=null, APIRole $role=null)
buildDomainUserGroupRoleAssignmentObject (SPIRoleAssignment $spiRoleAssignment, UserGroup $userGroup=null, APIRole $role=null)
getLimitationType ($identifier)
getLimitationTypesByModuleFunction ($module, $function)
Public Member Functions inherited from eZ\Publish\API\Repository\RoleService
createRole (RoleCreateStruct $roleCreateStruct)
updateRole (Role $role, RoleUpdateStruct $roleUpdateStruct)
addPolicy (Role $role, PolicyCreateStruct $policyCreateStruct)
removePolicy (Role $role, Policy $policy)
updatePolicy (Policy $policy, PolicyUpdateStruct $policyUpdateStruct)
deleteRole (Role $role)
assignRoleToUserGroup (Role $role, UserGroup $userGroup, RoleLimitation $roleLimitation=null)
unassignRoleFromUserGroup (Role $role, UserGroup $userGroup)
assignRoleToUser (Role $role, User $user, RoleLimitation $roleLimitation=null)
unassignRoleFromUser (Role $role, User $user)
getRoleAssignments (Role $role)
getRoleAssignmentsForUser (User $user)
Protected Member Functions
buildDomainRoleObject (SPIRole $role)
buildPersistenceRoleObject (APIRoleCreateStruct $roleCreateStruct)
buildPersistencePolicyObject ($module, $function, array $limitations)
Protected Attributes
$repository
$userHandler
$settings
Detailed Description
Definition at line 46 of file RoleService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\RoleService::__construct (RepositoryInterface $repository, Handler $userHandler, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\API\Repository\Repository $repository
\eZ\Publish\SPI\Persistence\User\Handler $userHandler
array $settings
Definition at line 70 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\$repository, eZ\Publish\Core\Repository\RoleService\$settings, and eZ\Publish\Core\Repository\RoleService\$userHandler.
    {
        $this->repository = $repository;
        $this->userHandler = $userHandler;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            'limitationTypes' => array(),
            'limitationMap' => array(),
        );
    }
Member Function Documentation
eZ\Publish\Core\Repository\RoleService::addPolicy (APIRole $role, APIPolicyCreateStruct $policyCreateStruct)
Adds a new policy to the role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to add a policy
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\PolicyCreateStruct $policyCreateStruct
Returns
Definition at line 197 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildPersistencePolicyObject(), and eZ\Publish\Core\Repository\RoleService\loadRole().
    {
        if ( !is_numeric( $role->id ) )
            throw new InvalidArgumentValue( "id", $role->id, "Role" );
        if ( !is_string( $policyCreateStruct->module ) || empty( $policyCreateStruct->module ) )
            throw new InvalidArgumentValue( "module", $policyCreateStruct->module, "PolicyCreateStruct" );
        if ( !is_string( $policyCreateStruct->function ) || empty( $policyCreateStruct->function ) )
            throw new InvalidArgumentValue( "function", $policyCreateStruct->function, "PolicyCreateStruct" );
        if ( $policyCreateStruct->module === '*' && $policyCreateStruct->function !== '*' )
            throw new InvalidArgumentValue( "module", $policyCreateStruct->module, "PolicyCreateStruct" );
        if ( $this->repository->hasAccess( 'role', 'update' ) !== true )
            throw new UnauthorizedException( 'role', 'update' );
        $loadedRole = $this->loadRole( $role->id );
        $spiPolicy = $this->buildPersistencePolicyObject(
            $policyCreateStruct->module,
            $policyCreateStruct->function,
            $policyCreateStruct->getLimitations()
        );
        $this->repository->beginTransaction();
        try
        {
            $this->userHandler->addPolicy( $loadedRole->id, $spiPolicy );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->loadRole( $loadedRole->id );
    }
eZ\Publish\Core\Repository\RoleService::assignRoleToUser (APIRole $role, User $user, RoleLimitation $roleLimitation = null)
Assigns a role to the given user
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to assign a role
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\User $user
\eZ\Publish\API\Repository\Values\User\Limitation\RoleLimitation $roleLimitation an optional role limitation (which is either a subtree limitation or section limitation)
Definition at line 539 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\loadRole().
    {
        if ( !is_numeric( $role->id ) )
            throw new InvalidArgumentValue( "id", $role->id, "Role" );
        if ( !is_numeric( $user->id ) )
            throw new InvalidArgumentValue( "id", $user->id, "User" );
        if ( $this->repository->canUser( 'role', 'assign', $user, $role ) !== true )
            throw new UnauthorizedException( 'role', 'assign' );
        $loadedRole = $this->loadRole( $role->id );
        $loadedUser = $this->repository->getUserService()->loadUser( $user->id );
        $this->repository->beginTransaction();
        try
        {
            $this->userHandler->assignRole(
                $loadedUser->id,
                $loadedRole->id,
                $roleLimitation ? array( $roleLimitation->getIdentifier() => $roleLimitation->limitationValues ) : null
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\RoleService::assignRoleToUserGroup (APIRole $role, UserGroup $userGroup, RoleLimitation $roleLimitation = null)
Assigns a role to the given user group
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to assign a role
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
\eZ\Publish\API\Repository\Values\User\Limitation\RoleLimitation $roleLimitation an optional role limitation (which is either a subtree limitation or section limitation)
Definition at line 461 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\loadRole().
    {
        if ( !is_numeric( $role->id ) )
            throw new InvalidArgumentValue( "id", $role->id, "Role" );
        if ( !is_numeric( $userGroup->id ) )
            throw new InvalidArgumentValue( "id", $userGroup->id, "UserGroup" );
        if ( $this->repository->canUser( 'role', 'assign', $userGroup, $role ) !== true )
            throw new UnauthorizedException( 'role', 'assign' );
        $loadedRole = $this->loadRole( $role->id );
        $loadedUserGroup = $this->repository->getUserService()->loadUserGroup( $userGroup->id );
        $this->repository->beginTransaction();
        try
        {
            $this->userHandler->assignRole(
                $loadedUserGroup->id,
                $loadedRole->id,
                $roleLimitation ? array( $roleLimitation->getIdentifier() => $roleLimitation->limitationValues ) : null
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\RoleService::buildDomainPolicyObject (SPIPolicy $policy, SPIRole $role = null)
Maps provided SPI Policy value object to API Policy value object
private Only accessible for other services and the internals of the repository
Parameters
\eZ\Publish\SPI\Persistence\User\Policy $policy
\eZ\Publish\SPI\Persistence\User\Role | null $role
Returns
Definition at line 833 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\getLimitationType().
    {
        $policyLimitations = array();
        if ( $policy->module !== '*' && $policy->function !== '*' && $policy->limitations !== '*' )
        {
            foreach ( $policy->limitations as $identifier => $values )
            {
                $policyLimitations[] = $this->getLimitationType( $identifier )->buildValue( $values );
            }
        }
        return new Policy(
            array(
                'id' => (int)$policy->id,
                'roleId' => $role !== null ? (int)$role->id : (int)$policy->roleId,
                'module' => $policy->module,
                'function' => $policy->function,
                'limitations' => $policyLimitations
            )
        );
    }
eZ\Publish\Core\Repository\RoleService::buildDomainRoleObject (SPIRole $role) protected
Maps provided SPI Role value object to API Role value object
Parameters
\eZ\Publish\SPI\Persistence\User\Role $role
Returns
Definition at line 807 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildDomainPolicyObject().
    {
        $rolePolicies = array();
        foreach ( $role->policies as $spiPolicy )
        {
            $rolePolicies[] = $this->buildDomainPolicyObject( $spiPolicy, $role );
        }
        return new Role(
            array(
                'id' => (int)$role->id,
                'identifier' => $role->identifier,
                'policies' => $rolePolicies
            )
        );
    }
eZ\Publish\Core\Repository\RoleService::buildDomainUserGroupRoleAssignmentObject (SPIRoleAssignment $spiRoleAssignment, UserGroup $userGroup = null, APIRole $role = null)
Builds the API UserGroupRoleAssignment object from provided SPI RoleAssignment object
Parameters
\eZ\Publish\SPI\Persistence\User\RoleAssignment $spiRoleAssignment
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
\eZ\Publish\API\Repository\Values\User\Role $role
Returns
Definition at line 895 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildDomainRoleObject().
    {
        $limitation = null;
        if ( !empty( $spiRoleAssignment->limitationIdentifier ) )
        {
            $limitation = $this
                ->getLimitationType( $spiRoleAssignment->limitationIdentifier )
                ->buildValue( $spiRoleAssignment->values );
        }
        $userGroup = $userGroup ?: $this->repository->getUserService()->loadUserGroup( $spiRoleAssignment->contentId );
        $role = $role ?: $this->buildDomainRoleObject( $spiRoleAssignment->role );
        return new UserGroupRoleAssignment(
            array(
                'limitation' => $limitation,
                'role' => $role,
                'userGroup' => $userGroup
            )
        );
    }
eZ\Publish\Core\Repository\RoleService::buildDomainUserRoleAssignmentObject (SPIRoleAssignment $spiRoleAssignment, User $user = null, APIRole $role = null)
Builds the API UserRoleAssignment object from provided SPI RoleAssignment object
Parameters
\eZ\Publish\SPI\Persistence\User\RoleAssignment $spiRoleAssignment
\eZ\Publish\API\Repository\Values\User\User $user
\eZ\Publish\API\Repository\Values\User\Role $role
Returns
Definition at line 864 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildDomainRoleObject().
    {
        $limitation = null;
        if ( !empty( $spiRoleAssignment->limitationIdentifier ) )
        {
            $limitation = $this
                ->getLimitationType( $spiRoleAssignment->limitationIdentifier )
                ->buildValue( $spiRoleAssignment->values );
        }
        $user = $user ?: $this->repository->getUserService()->loadUser( $spiRoleAssignment->contentId );
        $role = $role ?: $this->buildDomainRoleObject( $spiRoleAssignment->role );
        return new UserRoleAssignment(
            array(
                'limitation' => $limitation,
                'role' => $role,
                'user' => $user
            )
        );
    }
eZ\Publish\Core\Repository\RoleService::buildPersistencePolicyObject ($module, $function, array $limitations) protected
Creates SPI Policy value object from provided module, function and limitations
Parameters
string $module
string $function
\eZ\Publish\API\Repository\Values\User\Limitation[] $limitations
Returns
Definition at line 1008 of file RoleService.php.
    {
        $limitationsToCreate = '*';
        if ( $module !== '*' && $function !== '*' && !empty( $limitations ) )
        {
            $limitationsToCreate = array();
            foreach ( $limitations as $limitation )
            {
                $limitationsToCreate[$limitation->getIdentifier()] = $limitation->limitationValues;
            }
        }
        return new SPIPolicy(
            array(
                'module' => $module,
                'function' => $function,
                'limitations' => $limitationsToCreate
            )
        );
    }
eZ\Publish\Core\Repository\RoleService::buildPersistenceRoleObject (APIRoleCreateStruct $roleCreateStruct) protected
Creates SPI Role value object from provided API role create struct
Parameters
\eZ\Publish\API\Repository\Values\User\RoleCreateStruct $roleCreateStruct
Returns
Definition at line 979 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildPersistencePolicyObject().
    {
        $policiesToCreate = array();
        foreach ( $roleCreateStruct->getPolicies() as $policyCreateStruct )
        {
            $policiesToCreate[] = $this->buildPersistencePolicyObject(
                $policyCreateStruct->module,
                $policyCreateStruct->function,
                $policyCreateStruct->getLimitations()
            );
        }
        return new SPIRole(
            array(
                'identifier' => $roleCreateStruct->identifier,
                'policies' => $policiesToCreate
            )
        );
    }
eZ\Publish\Core\Repository\RoleService::createRole (APIRoleCreateStruct $roleCreateStruct)
Creates a new Role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to create a role
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the name of the role already exists
Parameters
\eZ\Publish\API\Repository\Values\User\RoleCreateStruct $roleCreateStruct
Returns
Definition at line 91 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildDomainRoleObject(), eZ\Publish\Core\Repository\RoleService\buildPersistenceRoleObject(), and eZ\Publish\Core\Repository\RoleService\loadRoleByIdentifier().
    {
        if ( !is_string( $roleCreateStruct->identifier ) || empty( $roleCreateStruct->identifier ) )
            throw new InvalidArgumentValue( "identifier", $roleCreateStruct->identifier, "RoleCreateStruct" );
        if ( $this->repository->hasAccess( 'role', 'create' ) !== true )
            throw new UnauthorizedException( 'role', 'create' );
        try
        {
            $existingRole = $this->loadRoleByIdentifier( $roleCreateStruct->identifier );
            if ( $existingRole !== null )
                throw new InvalidArgumentException( "roleCreateStruct", "role with specified identifier already exists" );
        }
        catch ( APINotFoundException $e )
        {
            // Do nothing
        }
        $spiRole = $this->buildPersistenceRoleObject( $roleCreateStruct );
        $this->repository->beginTransaction();
        try
        {
            $createdRole = $this->userHandler->createRole( $spiRole );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainRoleObject( $createdRole );
    }
eZ\Publish\Core\Repository\RoleService::deleteRole (APIRole $role)
Deletes the given role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to delete this role
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
Definition at line 401 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\loadRole().
    {
        if ( !is_numeric( $role->id ) )
            throw new InvalidArgumentValue( "id", $role->id, "Role" );
        if ( $this->repository->hasAccess( 'role', 'delete' ) !== true )
            throw new UnauthorizedException( 'role', 'delete' );
        $loadedRole = $this->loadRole( $role->id );
        $this->repository->beginTransaction();
        try
        {
            $this->userHandler->deleteRole( $loadedRole->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\RoleService::getLimitationType ($identifier)
Returns the LimitationType registered with the given identifier
Returns the correct implementation of API Limitation value object based on provided identifier
Parameters
string $identifier
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if there is no LimitationType with $identifier
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 929 of file RoleService.php.
    {
        if ( !isset( $this->settings['limitationTypes'][$identifier] ) )
            throw new NotFoundException( 'Limitation', $identifier );
        return $this->settings['limitationTypes'][$identifier];
    }
eZ\Publish\Core\Repository\RoleService::getLimitationTypesByModuleFunction ($module, $function)
Returns the LimitationType's assigned to a given module/function
Typically used for:
Internal validation limitation value use on Policies
Role admin gui for editing policy limitations incl list limitation options via valueSchema()
Parameters
string $module Legacy name of "controller", it's a unique identifier like "content"
string $function Legacy name of a controller "action", it's a unique within the controller like "read"
Returns
[]
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException If module/function to limitation type mapping refers to a non existing identifier.
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 952 of file RoleService.php.
    {
        if ( empty( $this->settings['limitationMap'][$module][$function] ) )
            return array();
        $types = array();
        foreach ( $this->settings['limitationMap'][$module][$function] as $identifier )
        {
            if ( !isset( $this->settings['limitationTypes'][$identifier] ) )
            {
                throw new \eZ\Publish\Core\Base\Exceptions\BadStateException(
                    '$identifier',
                    "'{$identifier}' does not exists but was configured as limitation on {$module}/{$function}"
                );
            }
            $types[$identifier] = $this->settings['limitationTypes'][$identifier];
        }
        return $types;
    }
eZ\Publish\Core\Repository\RoleService::getRoleAssignments (APIRole $role)
Returns the assigned user and user groups to this role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read a role
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
Returns
[]
Definition at line 617 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\$userHandler, eZ\Publish\Core\Repository\RoleService\buildDomainUserGroupRoleAssignmentObject(), and eZ\Publish\Core\Repository\RoleService\buildDomainUserRoleAssignmentObject().
    {
        if ( !is_numeric( $role->id ) )
            throw new InvalidArgumentValue( "id", $role->id, "Role" );
        if ( $this->repository->hasAccess( 'role', 'read' ) !== true )
            throw new UnauthorizedException( 'role', 'read' );
        $userHandler = $this->userHandler;
        $spiRole = $userHandler->loadRole( $role->id );
        $userService = $this->repository->getUserService();
        $roleAssignments = array();
        foreach ( $spiRole->groupIds as $groupId )
        {
            // $spiRole->groupIds can contain both group and user IDs
            // We'll check if the ID belongs to group, if not, see if it belongs to user
            try
            {
                $userGroup = $userService->loadUserGroup( $groupId );
                $spiRoleAssignments = $userHandler->loadRoleAssignmentsByGroupId( $userGroup->id );
                foreach ( $spiRoleAssignments as $spiRoleAssignment )
                {
                    if ( $spiRoleAssignment->role->id == $role->id )
                    {
                        $roleAssignments[] = $this->buildDomainUserGroupRoleAssignmentObject(
                            $spiRoleAssignment,
                            $userGroup,
                            $role
                        );
                    }
                }
            }
            catch ( APINotFoundException $e )
            {
                try
                {
                    $user = $userService->loadUser( $groupId );
                    $spiRoleAssignments = $userHandler->loadRoleAssignmentsByGroupId( $user->id );
                    foreach ( $spiRoleAssignments as $spiRoleAssignment )
                    {
                        if ( $spiRoleAssignment->role->id == $role->id )
{
                            $roleAssignments[] = $this->buildDomainUserRoleAssignmentObject(
                                $spiRoleAssignment,
                                $user,
                                $role
                            );
                        }
                    }
                }
                catch ( APINotFoundException $e )
                {
                    // Do nothing
                }
            }
        }
        return $roleAssignments;
    }
eZ\Publish\Core\Repository\RoleService::getRoleAssignmentsForUser (User $user, $inherited = false)
Returns the roles assigned to the given user
Parameters
\eZ\Publish\API\Repository\Values\User\User $user
boolean $inherited
Exceptions
\eZ\Publish\Core\Base\Exceptions\UnauthorizedException If the current user is not allowed to read a role
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentValue On invalid User object
Returns
[]
Definition at line 692 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildDomainUserGroupRoleAssignmentObject(), and eZ\Publish\Core\Repository\RoleService\buildDomainUserRoleAssignmentObject().
    {
        if ( !is_numeric( $user->id ) )
            throw new InvalidArgumentValue( "id", $user->id, "User" );
        if ( $this->repository->hasAccess( 'role', 'read' ) !== true )
            throw new UnauthorizedException( 'role', 'read' );
        $roleAssignments = array();
        $spiRoleAssignments = $this->userHandler->loadRoleAssignmentsByGroupId( $user->id, $inherited );
        foreach ( $spiRoleAssignments as $spiRoleAssignment )
        {
            if ( !$inherited || $spiRoleAssignment->contentId == $user->id )
                $roleAssignments[] = $this->buildDomainUserRoleAssignmentObject( $spiRoleAssignment, $user );
            else
                $roleAssignments[] = $this->buildDomainUserGroupRoleAssignmentObject( $spiRoleAssignment );
        }
        return $roleAssignments;
    }
eZ\Publish\Core\Repository\RoleService::getRoleAssignmentsForUserGroup (UserGroup $userGroup)
Returns the roles assigned to the given user group
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read a role
Parameters
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
Returns
[]
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 722 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildDomainUserGroupRoleAssignmentObject().
    {
        if ( !is_numeric( $userGroup->id ) )
            throw new InvalidArgumentValue( "id", $userGroup->id, "UserGroup" );
        if ( $this->repository->hasAccess( 'role', 'read' ) !== true )
            throw new UnauthorizedException( 'role', 'read' );
        $roleAssignments = array();
        $spiRoleAssignments = $this->userHandler->loadRoleAssignmentsByGroupId( $userGroup->id );
        foreach ( $spiRoleAssignments as $spiRoleAssignment )
        {
            $roleAssignments[] = $this->buildDomainUserGroupRoleAssignmentObject( $spiRoleAssignment, $userGroup );
        }
        return $roleAssignments;
    }
eZ\Publish\Core\Repository\RoleService::loadPoliciesByUserId ($userId)
Loads all policies from roles which are assigned to a user or to user groups to which the user belongs
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if a user with the given id was not found
Parameters
int $userId
Returns
[]
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 433 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildDomainPolicyObject().
    {
        if ( !is_numeric( $userId ) )
            throw new InvalidArgumentValue( "userId", $userId );
        $spiPolicies = $this->userHandler->loadPoliciesByUserId( $userId );
        $policies = array();
        foreach ( $spiPolicies as $spiPolicy )
        {
            $policies[] = $this->buildDomainPolicyObject( $spiPolicy );
        }
        if ( empty( $policies ) )
            $this->userHandler->load( $userId );// For NotFoundException in case userId is invalid
        return $policies;
    }
eZ\Publish\Core\Repository\RoleService::loadRole ($id)
Loads a role for the given id
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read this role
\eZ\Publish\API\Repository\Exceptions\NotFoundException if a role with the given id was not found
Parameters
mixed $id
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 337 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildDomainRoleObject().
    {
        if ( !is_numeric( $id ) )
            throw new InvalidArgumentValue( "id", $id );
        if ( $this->repository->hasAccess( 'role', 'read' ) !== true )
            throw new UnauthorizedException( 'role', 'read' );
        $spiRole = $this->userHandler->loadRole( $id );
        return $this->buildDomainRoleObject( $spiRole );
    }
eZ\Publish\Core\Repository\RoleService::loadRoleByIdentifier ($identifier)
Loads a role for the given identifier
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read this role
\eZ\Publish\API\Repository\Exceptions\NotFoundException if a role with the given name was not found
Parameters
string $identifier
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 359 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildDomainRoleObject().
    {
        if ( !is_string( $identifier ) )
            throw new InvalidArgumentValue( "identifier", $identifier );
        if ( $this->repository->hasAccess( 'role', 'read' ) !== true )
            throw new UnauthorizedException( 'role', 'read' );
        $spiRole = $this->userHandler->loadRoleByIdentifier( $identifier );
        return $this->buildDomainRoleObject( $spiRole );
    }
eZ\Publish\Core\Repository\RoleService::loadRoles ()
Loads all roles
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read the roles
Returns
[]
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 378 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildDomainRoleObject().
    {
        if ( $this->repository->hasAccess( 'role', 'read' ) !== true )
            throw new UnauthorizedException( 'role', 'read' );
        $spiRoles = $this->userHandler->loadRoles();
        $roles = array();
        foreach ( $spiRoles as $spiRole )
        {
            $roles[] = $this->buildDomainRoleObject( $spiRole );
        }
        return $roles;
    }
eZ\Publish\Core\Repository\RoleService::newPolicyCreateStruct ($module, $function)
Instantiates a policy create class
Parameters
string $module
string $function
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 765 of file RoleService.php.
    {
        return new PolicyCreateStruct(
            array(
                'module' => $module,
                'function' => $function,
                'limitations' => array()
            )
        );
    }
eZ\Publish\Core\Repository\RoleService::newPolicyUpdateStruct ()
Instantiates a policy update class
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 781 of file RoleService.php.
    {
        return new PolicyUpdateStruct(
            array(
                'limitations' => array()
            )
        );
    }
eZ\Publish\Core\Repository\RoleService::newRoleCreateStruct ($name)
Instantiates a role create class
Parameters
string $name
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 747 of file RoleService.php.
    {
        return new RoleCreateStruct(
            array(
                'identifier' => $name,
                'policies' => array()
            )
        );
    }
eZ\Publish\Core\Repository\RoleService::newRoleUpdateStruct ()
Instantiates a policy update class
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 795 of file RoleService.php.
    {
        return new RoleUpdateStruct();
    }
eZ\Publish\Core\Repository\RoleService::removePolicy (APIRole $role, APIPolicy $policy)
removes a policy from the role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to remove a policy
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\Policy $policy the policy to remove from the role
Returns
the updated role
Definition at line 247 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\loadRole().
    {
        if ( !is_numeric( $role->id ) )
            throw new InvalidArgumentValue( "id", $role->id, "Role" );
        if ( !is_numeric( $policy->id ) )
            throw new InvalidArgumentValue( "id", $policy->id, "Policy" );
        if ( $this->repository->hasAccess( 'role', 'update' ) !== true )
            throw new UnauthorizedException( 'role', 'update' );
        $loadedRole = $this->loadRole( $role->id );
        $this->repository->beginTransaction();
        try
        {
            $this->userHandler->removePolicy( $loadedRole->id, $policy->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->loadRole( $loadedRole->id );
    }
eZ\Publish\Core\Repository\RoleService::unassignRoleFromUser (APIRole $role, User $user)
removes a role from the given user.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to remove a role
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the role is not assigned to the user
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\User $user
Definition at line 579 of file RoleService.php.
    {
        if ( !is_numeric( $role->id ) )
            throw new InvalidArgumentValue( "id", $role->id, "Role" );
        if ( !is_numeric( $user->id ) )
            throw new InvalidArgumentValue( "id", $user->id, "User" );
        if ( $this->repository->canUser( 'role', 'assign', $user, $role ) !== true )
            throw new UnauthorizedException( 'role', 'assign' );
        $spiRole = $this->userHandler->loadRole( $role->id );
        if ( !in_array( $user->id, $spiRole->groupIds ) )
            throw new InvalidArgumentException( "user", "role is not assigned to the user" );
        $this->repository->beginTransaction();
        try
        {
            $this->userHandler->unAssignRole( $user->id, $role->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\RoleService::unassignRoleFromUserGroup (APIRole $role, UserGroup $userGroup)
removes a role from the given user group.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to remove a role
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the role is not assigned to the given user group
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
Definition at line 501 of file RoleService.php.
    {
        if ( !is_numeric( $role->id ) )
            throw new InvalidArgumentValue( "id", $role->id, "Role" );
        if ( !is_numeric( $userGroup->id ) )
            throw new InvalidArgumentValue( "id", $userGroup->id, "UserGroup" );
        if ( $this->repository->canUser( 'role', 'assign', $userGroup, $role ) !== true )
            throw new UnauthorizedException( 'role', 'assign' );
        $spiRole = $this->userHandler->loadRole( $role->id );
        if ( !in_array( $userGroup->id, $spiRole->groupIds ) )
            throw new InvalidArgumentException( "userGroup", "role is not assigned to the user group" );
        $this->repository->beginTransaction();
        try
        {
            $this->userHandler->unAssignRole( $userGroup->id, $role->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\RoleService::updatePolicy (APIPolicy $policy, APIPolicyUpdateStruct $policyUpdateStruct)
Updates the limitations of a policy. The module and function cannot be changed and the limitations are replaced by the ones in $roleUpdateStruct
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to update a policy
Parameters
\eZ\Publish\API\Repository\Values\User\PolicyUpdateStruct $policyUpdateStruct
\eZ\Publish\API\Repository\Values\User\Policy $policy
Returns
Definition at line 286 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\buildDomainPolicyObject(), and eZ\Publish\Core\Repository\RoleService\buildPersistencePolicyObject().
    {
        if ( !is_numeric( $policy->id ) )
            throw new InvalidArgumentValue( "id", $policy->id, "Policy" );
        if ( !is_numeric( $policy->roleId ) )
            throw new InvalidArgumentValue( "roleId", $policy->roleId, "Policy" );
        if ( !is_string( $policy->module ) )
            throw new InvalidArgumentValue( "module", $policy->module, "Policy" );
        if ( !is_string( $policy->function ) )
            throw new InvalidArgumentValue( "function", $policy->function, "Policy" );
        if ( $this->repository->hasAccess( 'role', 'update' ) !== true )
            throw new UnauthorizedException( 'role', 'update' );
        $spiPolicy = $this->buildPersistencePolicyObject(
            $policy->module,
            $policy->function,
            $policyUpdateStruct->getLimitations()
        );
        $spiPolicy->id = $policy->id;
        $spiPolicy->roleId = $policy->roleId;
        $this->repository->beginTransaction();
        try
        {
            $this->userHandler->updatePolicy( $spiPolicy );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainPolicyObject( $spiPolicy );
    }
eZ\Publish\Core\Repository\RoleService::updateRole (APIRole $role, RoleUpdateStruct $roleUpdateStruct)
Updates the name of the role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to update a role
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the name of the role already exists
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\RoleUpdateStruct $roleUpdateStruct
Returns
Definition at line 138 of file RoleService.php.
References eZ\Publish\Core\Repository\RoleService\loadRole(), and eZ\Publish\Core\Repository\RoleService\loadRoleByIdentifier().
    {
        if ( !is_numeric( $role->id ) )
            throw new InvalidArgumentValue( "id", $role->id, "Role" );
        if ( $roleUpdateStruct->identifier !== null && !is_string( $roleUpdateStruct->identifier ) )
            throw new InvalidArgumentValue( "identifier", $roleUpdateStruct->identifier, "RoleUpdateStruct" );
        if ( $this->repository->hasAccess( 'role', 'update' ) !== true )
            throw new UnauthorizedException( 'role', 'update' );
        if ( $roleUpdateStruct->identifier !== null )
        {
            try
            {
                $existingRole = $this->loadRoleByIdentifier( $roleUpdateStruct->identifier );
                if ( $existingRole !== null )
                    throw new InvalidArgumentException( "roleUpdateStruct", "role with specified identifier already exists" );
            }
            catch ( APINotFoundException $e )
            {
                // Do nothing
            }
        }
        $loadedRole = $this->loadRole( $role->id );
        $this->repository->beginTransaction();
        try
        {
            $this->userHandler->updateRole(
                new SPIRoleUpdateStruct(
                    array(
                        'id' => $loadedRole->id,
                        'identifier' => $roleUpdateStruct->identifier ?: $role->identifier
                    )
                )
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->loadRole( $loadedRole->id );
    }
Member Data Documentation
eZ\Publish\Core\Repository\RoleService::$repository protected
Definition at line 51 of file RoleService.php.
eZ\Publish\Core\Repository\RoleService::$settings protected
Definition at line 61 of file RoleService.php.
eZ\Publish\Core\Repository\RoleService::$userHandler protected
Definition at line 56 of file RoleService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/RoleService.php