ezp-next: eZ\Publish\Core\REST\Common\UrlHandler\Pattern Class Reference
eZ\Publish\Core\REST\Common\UrlHandler\Pattern Class Reference
Public Member Functions
__construct (array $map=array())
addPattern ($type, $pattern)
parse ($type, $url)
generate ($type, array $values=array())
Public Attributes
const STANDARD_VARIABLE_REGEX = '\{([A-Za-z-_]+)\}'
const SLASHES_VARIABLE_REGEX = '\{(?:\&\s*)([A-Za-z-_]+)\}'
Protected Member Functions
compile ($pattern)
Protected Attributes
$map = array()
$compileCache = array()
Detailed Description
Pattern based URL Handler
Handles 2 types of patterns to be used in an URL:
{foo} matches anything but a slash and is used to match the typical URL variable (e.g. an ID)
{&foo} matches the slash, too, and is used to match only those URL variables, which may have a slash
Definition at line 25 of file Pattern.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Common\UrlHandler\Pattern::__construct (array $map = array())
Construct from optional initial map
Parameters
array $map
Definition at line 56 of file Pattern.php.
References eZ\Publish\Core\REST\Common\UrlHandler\Pattern\$map, eZ\Publish\Core\REST\Common\UrlHandler\Pattern\__construct(), and eZ\Publish\Core\REST\Common\UrlHandler\Pattern\addPattern().
    {
        foreach ( $map as $type => $pattern )
        {
            $this->addPattern( $type, $pattern );
        }
    }
Member Function Documentation
eZ\Publish\Core\REST\Common\UrlHandler\Pattern::addPattern ($type, $pattern)
Adds a pattern for a type
Parameters
string $type
string $pattern
Definition at line 70 of file Pattern.php.
References eZ\Publish\Core\REST\Common\UrlHandler\Pattern\addPattern().
    {
        $this->map[$type] = $pattern;
        unset( $this->compileCache[$type] );
    }
eZ\Publish\Core\REST\Common\UrlHandler\Pattern::compile ($pattern) protected
Compiles a given pattern to a PCRE regular expression
Parameters
string $pattern
Returns
string
Definition at line 115 of file Pattern.php.
References eZ\Publish\Core\REST\Common\UrlHandler\Pattern\compile().
    {
        if ( isset( $this->compileCache[$pattern] ) )
        {
            return $this->compileCache[$pattern];
        }
        $pcre = '(^';
        do
        {
            switch ( true )
            {
                case preg_match( '(^[^{]+)', $pattern, $match ):
                    $pattern = substr( $pattern, strlen( $match[0] ) );
                    $pcre   .= preg_quote( $match[0] );
                    break;
                case preg_match( '(^' . self::STANDARD_VARIABLE_REGEX . ')', $pattern, $match ):
                    $pattern = substr( $pattern, strlen( $match[0] ) );
                    $pcre   .= "(?P<" . $match[1] . ">[^/]+)";
                    break;
                case preg_match( '(^' . self::SLASHES_VARIABLE_REGEX . ')', $pattern, $match ):
                    $pattern = substr( $pattern, strlen( $match[0] ) );
                    $pcre   .= "(?P<" . $match[1] . ">.+)";
                    break;
                default:
                    throw new Exceptions\InvalidArgumentException( "Invalid pattern part: '$pattern'." );
            }
        }
        while ( $pattern );
        $pcre .= '$)S';
        $this->compileCache[$pattern] = $pcre;
        return $pcre;
    }
eZ\Publish\Core\REST\Common\UrlHandler\Pattern::generate ($type, array $values = array())
Generate a URL of the given type from the specified values
Parameters
string $type
array $values
Returns
string
Implements eZ\Publish\Core\REST\Common\UrlHandler.
Reimplemented in eZ\Publish\Core\REST\Common\UrlHandler\Prefixed.
Definition at line 163 of file Pattern.php.
    {
        if ( !isset( $this->map[$type] ) )
        {
            throw new Exceptions\InvalidArgumentException( "No URL for type '$type' available." );
        }
        $url = $this->map[$type];
        preg_match_all(
            '(' . self::STANDARD_VARIABLE_REGEX . '|' . self::SLASHES_VARIABLE_REGEX . ')',
            $url,
            $matches,
            PREG_SET_ORDER
        );
        foreach ( $matches as $matchSet )
        {
            $variableName = empty( $matchSet[1] ) ? $matchSet[2] : $matchSet[1];
            if ( !isset( $values[$variableName] ) )
            {
                throw new Exceptions\InvalidArgumentException( "No value provided for '{$variableName}'." );
            }
            $url = str_replace( $matchSet[0], $values[$variableName], $url );
            unset( $values[$variableName] );
        }
        if ( count( $values ) )
        {
            throw new Exceptions\InvalidArgumentException( "Unused values in values array: '" . implode( "', '", array_keys( $values ) ) . "'." );
        }
        return $url;
    }
eZ\Publish\Core\REST\Common\UrlHandler\Pattern::parse ($type, $url)
Parse URL and return the IDs contained in the URL
Parameters
string $type
string $url
Returns
array
Implements eZ\Publish\Core\REST\Common\UrlHandler.
Reimplemented in eZ\Publish\Core\REST\Common\UrlHandler\Prefixed.
Definition at line 84 of file Pattern.php.
References eZ\Publish\Core\REST\Common\UrlHandler\Pattern\compile().
    {
        if ( !isset( $this->map[$type] ) )
        {
            throw new Exceptions\InvalidArgumentException( "No URL for type '$type' available." );
        }
        $pattern = $this->compile( $this->map[$type] );
        if ( !preg_match( $pattern, $url, $match ) )
        {
            throw new Exceptions\InvalidArgumentException( "URL '$url' did not match $pattern." );
        }
        foreach ( $match as $key => $value )
        {
            if ( is_numeric( $key ) )
            {
                unset( $match[$key] );
            }
        }
        return $match;
    }
Member Data Documentation
eZ\Publish\Core\REST\Common\UrlHandler\Pattern::$compileCache = array() protected
Definition at line 39 of file Pattern.php.
eZ\Publish\Core\REST\Common\UrlHandler\Pattern::$map = array() protected
Definition at line 32 of file Pattern.php.
const eZ\Publish\Core\REST\Common\UrlHandler\Pattern::SLASHES_VARIABLE_REGEX = '\{(?:\&\s*)([A-Za-z-_]+)\}'
Pattern regular sub-expression that might contain slashes
Definition at line 49 of file Pattern.php.
const eZ\Publish\Core\REST\Common\UrlHandler\Pattern::STANDARD_VARIABLE_REGEX = '\{([A-Za-z-_]+)\}'
Pattern regular sub-expression
Definition at line 44 of file Pattern.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/UrlHandler/Pattern.php