ezp-next: eZ\Publish\Core\Persistence\Factory Class Reference
eZ\Publish\Core\Persistence\Factory Class Reference
Public Member Functions
__construct (ContainerInterface $container, $persistenceId)
getPersistenceHandler ()
getContentHandler ()
getSearchHandler ()
getContentTypeHandler ()
getContentLanguageHandler ()
getLocationHandler ()
getObjectStateHandler ()
getTrashHandler ()
getUserHandler ()
getSectionHandler ()
getUrlAliasHandler ()
getUrlWildcardHandler ()
Detailed Description
A reusable factory for all the "storage engine" handlers
This class is kept in Core as it is a temporary one until Legacy and InMemory is refactored to provide all handlers as decoupled services.
Tests? See Cache\Tests\FactoryTests.php
Definition at line 23 of file Factory.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Factory::__construct (ContainerInterface $container, $persistenceId)
Parameters
\Symfony\Component\DependencyInjection\ContainerInterface $container
string $persistenceId
Definition at line 39 of file Factory.php.
    {
        $this->container = $container;
        $this->persistenceId = $persistenceId;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Factory::getContentHandler ()
Returns
Definition at line 56 of file Factory.php.
References eZ\Publish\Core\Persistence\Factory\getPersistenceHandler().
    {
        return $this->getPersistenceHandler()->contentHandler();
    }
eZ\Publish\Core\Persistence\Factory::getContentLanguageHandler ()
Returns
Definition at line 80 of file Factory.php.
References eZ\Publish\Core\Persistence\Factory\getPersistenceHandler().
    {
        return $this->getPersistenceHandler()->contentLanguageHandler();
    }
eZ\Publish\Core\Persistence\Factory::getContentTypeHandler ()
Returns
Definition at line 72 of file Factory.php.
References eZ\Publish\Core\Persistence\Factory\getPersistenceHandler().
    {
        return $this->getPersistenceHandler()->contentTypeHandler();
    }
eZ\Publish\Core\Persistence\Factory::getLocationHandler ()
Returns
Definition at line 88 of file Factory.php.
References eZ\Publish\Core\Persistence\Factory\getPersistenceHandler().
    {
        return $this->getPersistenceHandler()->locationHandler();
    }
eZ\Publish\Core\Persistence\Factory::getObjectStateHandler ()
Returns
Definition at line 96 of file Factory.php.
References eZ\Publish\Core\Persistence\Factory\getPersistenceHandler().
    {
        return $this->getPersistenceHandler()->objectStateHandler();
    }
eZ\Publish\Core\Persistence\Factory::getPersistenceHandler ()
Returns
Definition at line 48 of file Factory.php.
    {
        return $this->container->get( $this->persistenceId );
    }
eZ\Publish\Core\Persistence\Factory::getSearchHandler ()
Returns
Definition at line 64 of file Factory.php.
References eZ\Publish\Core\Persistence\Factory\getPersistenceHandler().
    {
        return $this->getPersistenceHandler()->searchHandler();
    }
eZ\Publish\Core\Persistence\Factory::getSectionHandler ()
Returns
Definition at line 120 of file Factory.php.
References eZ\Publish\Core\Persistence\Factory\getPersistenceHandler().
    {
        return $this->getPersistenceHandler()->sectionHandler();
    }
eZ\Publish\Core\Persistence\Factory::getTrashHandler ()
Returns
Definition at line 104 of file Factory.php.
References eZ\Publish\Core\Persistence\Factory\getPersistenceHandler().
    {
        return $this->getPersistenceHandler()->trashHandler();
    }
eZ\Publish\Core\Persistence\Factory::getUrlAliasHandler ()
Returns
Definition at line 128 of file Factory.php.
References eZ\Publish\Core\Persistence\Factory\getPersistenceHandler().
    {
        return $this->getPersistenceHandler()->urlAliasHandler();
    }
eZ\Publish\Core\Persistence\Factory::getUrlWildcardHandler ()
Returns
Definition at line 136 of file Factory.php.
References eZ\Publish\Core\Persistence\Factory\getPersistenceHandler().
    {
        return $this->getPersistenceHandler()->urlWildcardHandler();
    }
eZ\Publish\Core\Persistence\Factory::getUserHandler ()
Returns
Definition at line 112 of file Factory.php.
References eZ\Publish\Core\Persistence\Factory\getPersistenceHandler().
    {
        return $this->getPersistenceHandler()->userHandler();
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Factory.php