ezp-next: eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\Page Class Reference
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\Page Class Reference
Public Member Functions
addSemanticConfig (NodeBuilder $nodeBuilder)
registerInternalConfig (array $config, ContainerBuilder $container)
Public Member Functions inherited from eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser
setBaseKey ($key)
Additional Inherited Members
Public Attributes inherited from eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser
const UNIQUE = 1
const MERGE_FROM_SECOND_LEVEL = 2
Protected Member Functions inherited from eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser
getContainerParameter (ContainerBuilder $container, $id, $default=null)
groupsArraySetting (array $groups, $id, array $config, $options=0)
registerGlobalConfigArray ($id, array $config, ContainerBuilder $container)
registerInternalConfigArray ($id, array $config, ContainerBuilder $container, $options=0)
Protected Attributes inherited from eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser
$baseKey = 'system'
Detailed Description
Configuration parser handling all basic configuration (aka "Image")
Definition at line 20 of file Page.php.
Member Function Documentation
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\Page::addSemanticConfig (NodeBuilder $nodeBuilder)
Adds semantic configuration definition.
Parameters
\Symfony\Component\Config\Definition\Builder\NodeBuilder $nodeBuilder Node just under ezpublish.system.<siteaccess>
Implements eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser.
Definition at line 27 of file Page.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\Page\addSemanticConfig().
    {
        $nodeBuilder
            ->arrayNode( 'ezpage' )
                ->children()
                    ->arrayNode( 'enabledLayouts' )
                        ->prototype( 'scalar' )
                        ->end()
                        ->info( 'List of enabled layout identifiers' )
                    ->end()
                    ->arrayNode( 'enabledBlocks' )
                        ->prototype( 'scalar' )
                        ->end()
                        ->info( 'List of enabled block identifiers' )
                    ->end()
                    ->arrayNode( 'layouts' )
                        ->info( 'List of registered layouts, the key is the identifier of the layout' )
                        ->useAttributeAsKey( 'key' )
                        ->normalizeKeys( false )
                        ->prototype( 'array' )
                            ->children()
                                ->scalarNode( 'name' )->isRequired()->info( 'Name of the zone type' )->end()
                                ->scalarNode( 'template' )->isRequired()->info( 'Template to use to render this layout' )->end()
                            ->end()
                        ->end()
                    ->end()
                    ->arrayNode( 'blocks' )
                        ->info( 'List of available blocks, the key is the identifier of the block' )
                        ->useAttributeAsKey( 'key' )
                        ->normalizeKeys( false )
                        ->prototype( 'array' )
                            ->children()
                                ->scalarNode( 'name' )->isRequired()->info( 'Name of the block' )->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\Page::registerInternalConfig (array $config, ContainerBuilder $container)
Translates parsed semantic config values from $config to internal key/value pairs.
Parameters
array $config
\Symfony\Component\DependencyInjection\ContainerBuilder $container
Implements eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser.
Definition at line 74 of file Page.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser\Page\registerInternalConfig(), and eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser\registerInternalConfigArray().
    {
        $defaultConfig = array(
            'layouts' => $container->getParameter( 'ezpublish.ezpage.layouts' ),
            'blocks' => $container->getParameter( 'ezpublish.ezpage.blocks' ),
            'enabledLayouts' => $container->getParameter( 'ezpublish.ezpage.enabledLayouts' ),
            'enabledBlocks' => $container->getParameter( 'ezpublish.ezpage.enabledBlocks' ),
        );
        $container->setParameter(
            'ezsettings.' . ConfigResolver::SCOPE_DEFAULT . '.ezpage',
            $defaultConfig
        );
        $this->registerInternalConfigArray(
            'ezpage', $config, $container, self::MERGE_FROM_SECOND_LEVEL
        );
        // filters blocks and layouts for each siteaccess to keep only
        // the enabled ones for this sa
        foreach ( $config['siteaccess']['list'] as $sa )
        {
            $ezpageSettings = $container->getParameter( "ezsettings.$sa.ezpage" );
            foreach ( array( 'layouts', 'blocks' ) as $type )
            {
                $enabledKey = 'enabled' . ucfirst( $type );
                if ( empty( $ezpageSettings[$enabledKey] ) )
                {
                    $ezpageSettings[$type] = array();
                    continue;
                }
                $ezpageSettings[$type] = array_intersect_key(
                    $ezpageSettings[$type],
                    array_flip( $ezpageSettings[$enabledKey] )
                );
            }
            $container->setParameter( "ezsettings.$sa.ezpage", $ezpageSettings );
        }
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Page.php