ezp-next: eZ\Publish\Core\Persistence\InMemory\Backend Class Reference
eZ\Publish\Core\Persistence\InMemory\Backend Class Reference
Public Member Functions
__construct (array $data)
create ($type, array $data, $autoIncrement=true, $idColumn= 'id')
load ($type, $id, $idColumn= 'id')
find ($type, array $match=array(), array $joinInfo=array())
update ($type, $id, array $data, $union=true, $idColumn= 'id')
updateByMatch ($type, array $match, array $data, $union=true, $idColumn= 'id')
delete ($type, $id, $idColumn= 'id')
deleteByMatch ($type, array $match)
count ($type, array $match=array(), array $joinInfo=array())
beginTransaction ()
commit ()
rollback ()
Protected Member Functions
rawFind ($type, array $match=array(), array $joinInfo=array())
getFieldTypeNamespace ($obj)
Protected Attributes
$data = array()
$transactionDataStack = array()
Detailed Description
The Storage Engine backend for in memory storage Reads input from js files in provided directory and fills in memory db store.
The in memory db store and also json representation have a one to one mapping to defined value objects. But only their plain properties, associations are not handled and all data is stored in separate "buckets" similar to how it would be in a RDBMS servers.
Definition at line 26 of file Backend.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\InMemory\Backend::__construct (array $data)
Construct backend and assign data
Use: new Backend(json_decode(file_get_contents(DIR . '/data.json'), true));
Parameters
array $data Data where key is type like "Content" or "Content\\Type" which then have to map to Value objects in eZ*, data is an array of hash values with same structure as the corresponding value object. Foreign keys: In some cases value objects does not contain these as they are internal, so this needs to be handled in InMemory handlers by assigning keys like "_typeId" on Type hash values for instance. These will be stored and can be matched with find(), but will not be returned as part of VO so purely internal.
Definition at line 56 of file Backend.php.
References eZ\Publish\Core\Persistence\InMemory\Backend\$data.
    {
        $this->data = $data + $this->data;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\InMemory\Backend::beginTransaction ()
Begin transaction
Begins an transaction, make sure you'll call commit or rollback when done, otherwise work will be lost.
Definition at line 315 of file Backend.php.
References eZ\Publish\Core\Persistence\InMemory\Backend\$data.
    {
        // copy current data to transaction stack
        $this->transactionDataStack[] = $this->data;
    }
eZ\Publish\Core\Persistence\InMemory\Backend::commit ()
Commit transaction
Commit transaction, or throw exceptions if no transactions has been started.
Exceptions
\RuntimeException If no transaction has been started
Definition at line 328 of file Backend.php.
    {
        if ( empty( $this->transactionDataStack ) )
            throw new \RuntimeException( "No transactions in progress" );
        // remove one level of data from transaction stack
        array_pop( $this->transactionDataStack );
    }
eZ\Publish\Core\Persistence\InMemory\Backend::count ($type, array $match = array(), array $joinInfo = array())
Find count of objects of a given type matching a simple $match (empty array will match all)
Note does not support joins, so only properties on $type is matched.
Parameters
string $type
array $match A flat array with property => value to match against
array $joinInfo See find()
rawFind()
Returns
int
Definition at line 304 of file Backend.php.
References eZ\Publish\Core\Persistence\InMemory\Backend\rawFind().
    {
        return count( $this->rawFind( $type, $match, $joinInfo ) );
    }
eZ\Publish\Core\Persistence\InMemory\Backend::create ($type, array $data, $autoIncrement = true, $idColumn = 'id')
Creates data in in memory store
Parameters
string $type
array $data
boolean $autoIncrement
string $idColumn By default, id column is 'id', but this can be customized here (e.g. for 'contentId')
Returns
object
Exceptions
InvalidArgumentValue On invalid $type
LogicException If $autoIncrement is false but $data does not include an id
LogicException If provided id already exists (and if defined, data contain same status property value)
Definition at line 74 of file Backend.php.
References eZ\Publish\Core\Persistence\InMemory\Backend\$data.
    {
        if ( !is_scalar( $type ) || !isset( $this->data[$type] ) )
            throw new InvalidArgumentValue( 'type', $type );
        if ( $autoIncrement )
        {
            $data[$idColumn] = $this->getNextId( $type, $idColumn );
        }
        else if ( !$data[$idColumn] )
        {
            throw new LogicException( '\'create\' logic error, $autoIncrement is false but no id is provided' );
        }
        foreach ( $this->data[$type] as $item )
        {
            if (
                // Same identifier
                $item[$idColumn] == $data[$idColumn] &&
                (
                    // and "status" matches
                    ( isset( $item['status'] ) && $item['status'] == $data['status'] ) ||
                    // or "_status" matches
                    ( isset( $item['_status'] ) && $item['_status'] == $data['_status'] ) ||
                    // or no status available
                    !( isset( $item['status'] ) || isset( $item['_status'] ) )
                )
            )
                throw new LogicException( "'create' logic error, provided id already exist" );
        }
        /*foreach ( $data as $prop => $value )
        {
            if ( $value === null )
                throw new InvalidArgumentValue( 'data', "'$prop' on '$type' was of value NULL" );
        }*/
        $this->data[$type][] = $data;
        return $this->toValue( $type, $data );
    }
eZ\Publish\Core\Persistence\InMemory\Backend::delete ($type, $id, $idColumn = 'id')
Deletes data in in memory store
Parameters
string $type
int | string $id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If data does not exist deleteByMatch()
Definition at line 255 of file Backend.php.
References eZ\Publish\Core\Persistence\InMemory\Backend\deleteByMatch().
    {
        $this->deleteByMatch( $type, array( $idColumn => $id ) );
    }
eZ\Publish\Core\Persistence\InMemory\Backend::deleteByMatch ($type, array $match)
Deletes data in in memory store
Useful in cases where a specific state of an object should be updated, Type with version=0 for instance.
Parameters
string $type
array $match A flat array with property => value to match against
Exceptions
InvalidArgumentValue On invalid $type
\eZ\Publish\API\Repository\Exceptions\NotFoundException If no data to delete have been found
Definition at line 272 of file Backend.php.
    {
        if ( !is_scalar( $type ) || !isset( $this->data[$type] ) )
            throw new InvalidArgumentValue( 'type', $type );
        $found = false;
        foreach ( $this->data[$type] as $key => $item )
        {
            if ( $this->match( $item, $match ) )
            {
                unset( $this->data[$type][$key] );
                $found = true;
            }
        }
        if ( !$found )
            throw new NotFound( $type, $match );
    }
eZ\Publish\Core\Persistence\InMemory\Backend::find ($type, array $match = array(), array $joinInfo = array())
Find data from in memory store for a specific type that matches $match (empty array will match all)
Note does not support joins, so only properties on $type is matched.
Parameters
string $type
array $match A multi level array with property => value to match against
array $joinInfo Optional info on how to join in other objects to become part of a aggregate where $type is root. Format: array('<property>' => array('type' => '<foreign-type>', 'match' => array('<foreign-key-property>' => '<key-property>')), ['sub' => < $joininfo>="">]) Example (joining Location when finding Content): array('locations' => array('type' => 'Content\Location', 'match' => array('contentId' => 'id'))) Value of 'sub' follows exactly same format as $joinInfo allowing recursive joining. rawFind()
Returns
object[]
Definition at line 176 of file Backend.php.
References eZ\Publish\Core\Persistence\InMemory\Backend\rawFind().
    {
        $items = $this->rawFind( $type, $match, $joinInfo );
        foreach ( $items as $key => $item )
            $items[$key] = $this->toValue( $type, $item, $joinInfo );
        return $items;
    }
eZ\Publish\Core\Persistence\InMemory\Backend::getFieldTypeNamespace ($obj) protected
Parameters
\eZ\Publish\SPI\Persistence\ValueObject $obj
Returns
string
Definition at line 615 of file Backend.php.
    {
        if ( isset( $this->tempFieldTypeMapping[ $obj->type ] ) )
            return $this->tempFieldTypeMapping[ $obj->type ];
        throw new \Exception( "Following FieldType is not supported by InMemory storage {$obj->type}" );
    }
eZ\Publish\Core\Persistence\InMemory\Backend::load ($type, $id, $idColumn = 'id')
Reads data from in memory store
Parameters
string $type
int | string $id
string $idColumn
Returns
object
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentValue On invalid $type
\eZ\Publish\API\Repository\Exceptions\NotFoundException If data does not exist
LogicException If several items exists with same id
Definition at line 127 of file Backend.php.
    {
        if ( !is_scalar( $type ) || !isset( $this->data[$type] ) )
            throw new InvalidArgumentValue( 'type', $type );
        $return = null;
        $found = false;
        foreach ( $this->data[$type] as $item )
        {
            if ( $item[$idColumn] != $id )
                continue;
            if ( $return )
                throw new LogicException( "Logic error, more than one item exist with id: {$id}" );
            $return = $this->toValue( $type, $item );
            $found = true;
        }
        if ( !$found )
            throw new NotFound( $type, $id );
        return $return;
    }
eZ\Publish\Core\Persistence\InMemory\Backend::rawFind ($type, array $match = array(), array $joinInfo = array()) protected
Find data from in memory store for a specific type that matches $match (empty array will match all)
Note does not support joins, so only properties on $type is matched.
Parameters
string $type
array $match A multi level array with property => value to match against
array $joinInfo See find()
Returns
array[]
Exceptions
InvalidArgumentValue On invalid $type
LogicException When there is a collision between match rules in $joinInfo and $match
Definition at line 366 of file Backend.php.
    {
        if ( !is_scalar( $type ) || !isset( $this->data[$type] ) )
            throw new InvalidArgumentValue( 'type', $type );
        $items = array();
        foreach ( $this->data[$type] as $item )
        {
            foreach ( $joinInfo as $joinProperty => $joinItem )
            {
                foreach ( $joinItem['match'] as $joinMatchKey => $joinMatchProperty )
                {
                    $joinItem['match'][$joinMatchKey] = $item[$joinMatchProperty];
                    if ( isset( $match[$joinProperty][$joinMatchKey] ) )
                        throw new LogicException( "\$match[$joinProperty][$joinMatchKey] logic error, collision with match in \$joinInfo" );
                }
                $item[$joinProperty] = $this->rawFind(
                    $joinItem['type'],
                    $joinItem['match'],
                    ( isset( $joinItem['sub'] ) ? $joinItem['sub'] : array() )
                );
            }
            if ( $this->match( $item, $match ) )
                $items[] = $item;
        }
        return $items;
    }
eZ\Publish\Core\Persistence\InMemory\Backend::rollback ()
Rollback transaction
Rollback transaction, or throw exceptions if no transactions has been started.
Exceptions
\RuntimeException If no transaction has been started
Definition at line 344 of file Backend.php.
    {
        if ( empty( $this->transactionDataStack ) )
            throw new \RuntimeException( "No transactions in progress" );
        // pop last data set from transaction stack back to live $data set to wipe out changes
        $this->data = array_pop( $this->transactionDataStack );
    }
eZ\Publish\Core\Persistence\InMemory\Backend::update ($type, $id, array $data, $union = true, $idColumn = 'id')
Updates data in in memory store
Parameters
string $type
int | string $id
array $data
boolean $union Specifies if data should be merged with existing data or not
updateByMatch()
Returns
boolean False if data does not exist and can not be updated
Definition at line 197 of file Backend.php.
References eZ\Publish\Core\Persistence\InMemory\Backend\updateByMatch().
    {
        return $this->updateByMatch( $type, array( $idColumn => $id ), $data, $union, $idColumn );
    }
eZ\Publish\Core\Persistence\InMemory\Backend::updateByMatch ($type, array $match, array $data, $union = true, $idColumn = 'id')
Updates data in in memory store by match
Useful in cases where a specific state of an object should be updated, Type with version=0 for instance.
Parameters
string $type
array $match A flat array with property => value to match against
array $data
boolean $union Specifies if data should be merged with existing data or not
Exceptions
InvalidArgumentValue On invalid $type
Returns
boolean False if data does not exist and can not be updated
Definition at line 217 of file Backend.php.
References eZ\Publish\Core\Persistence\InMemory\Backend\$data.
    {
        if ( !is_scalar( $type ) || !isset( $this->data[$type] ) )
            throw new InvalidArgumentValue( 'type', $type );
        // Make sure id isn't changed
        unset( $data[$idColumn] );
        /*foreach ( $data as $prop => $value )
        {
            if ( $value === null )
                throw new InvalidArgumentValue( 'data', "'$prop' on '$type' was of value NULL" );
        }*/
        $return = false;
        foreach ( $this->data[$type] as $key => $item )
        {
            if ( $this->match( $item, $match ) )
            {
                if ( $union )
                    $this->data[$type][$key] = $data + $this->data[$type][$key];
                else
                    $this->data[$type][$key] = $data;
                $return = true;
            }
        }
        return $return;
    }
Member Data Documentation
eZ\Publish\Core\Persistence\InMemory\Backend::$data = array() protected
Definition at line 31 of file Backend.php.
eZ\Publish\Core\Persistence\InMemory\Backend::$transactionDataStack = array() protected
Definition at line 40 of file Backend.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/InMemory/Backend.php