ezp-next: eZ\Publish\Core\REST\Common\Output\Visitor Class Reference
eZ\Publish\Core\REST\Common\Output\Visitor Class Reference
Public Member Functions
__construct (Generator $generator, array $visitors)
addVisitor ($class, ValueObjectVisitor $visitor)
setHeader ($name, $value)
setStatus ($statusCode)
visit ($data)
visitValueObject ($data)
getMediaType ($type)
Static Public Attributes
static $statusMap
Protected Attributes
$visitors = array()
$generator
$headers = array()
Detailed Description
Visitor for view models
Definition at line 17 of file Visitor.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Common\Output\Visitor::__construct (Generator $generator, array $visitors)
Construct from Generator and an array of concrete view model visitors
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator $generator
array $visitors
Definition at line 115 of file Visitor.php.
References eZ\Publish\Core\REST\Common\Output\Visitor\$generator, and eZ\Publish\Core\REST\Common\Output\Visitor\addVisitor().
    {
        $this->generator = $generator;
        foreach ( $visitors as $class => $visitor )
        {
            $this->addVisitor( $class, $visitor );
        }
    }
Member Function Documentation
eZ\Publish\Core\REST\Common\Output\Visitor::addVisitor ($class, ValueObjectVisitor $visitor)
Adds a new visitor for the given class
Parameters
string $class
\eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor $visitor
Definition at line 130 of file Visitor.php.
    {
        if ( $class[0] === '\\' )
        {
            $class = substr( $class, 1 );
        }
        $this->visitors[$class] = $visitor;
    }
eZ\Publish\Core\REST\Common\Output\Visitor::getMediaType ($type)
Generates a media type for $type based on the used generator.
Parameters
string $type
See Also
::getMediaType()
Returns
string
Definition at line 262 of file Visitor.php.
    {
        return $this->generator->getMediaType( $type );
    }
eZ\Publish\Core\REST\Common\Output\Visitor::setHeader ($name, $value)
Set HTTP response header
Does not allow overwriting of response headers. The first definition of a header will be used.
Parameters
string $name
string $value
Definition at line 149 of file Visitor.php.
    {
        if ( !isset( $this->headers[$name] ) )
        {
            $this->headers[$name] = $value;
        }
    }
eZ\Publish\Core\REST\Common\Output\Visitor::setStatus ($statusCode)
Sets the given status code in the corresponding header.
Note that headers are generally not overwritten!
Parameters
int $statusCode
Definition at line 164 of file Visitor.php.
References eZ\Publish\Core\REST\Common\Output\Visitor\setHeader().
    {
        $status = sprintf(
            '%s %s',
            $statusCode,
            ( isset( self::$statusMap[$statusCode] )
                ? self::$statusMap[$statusCode]
                : 'Unknown' )
        );
        $this->setHeader( 'Status', $status );
    }
eZ\Publish\Core\REST\Common\Output\Visitor::visit ($data)
Visit struct returned by controllers
Parameters
mixed $data
Returns
Definition at line 184 of file Visitor.php.
References eZ\Publish\Core\REST\Common\Output\Visitor\visitValueObject().
    {
        $this->generator->reset();
        $this->generator->startDocument( $data );
        $this->visitValueObject( $data );
        //@todo Needs refactoring!
        // A hackish solution to enable outer visitors to disable setting
        // of certain headers in inner visitors, for example Accept-Patch header
        // which is valid in GET/POST/PATCH for a resource, but must not appear
        // in the list of resources
        $filteredHeaders = array();
        foreach ( $this->headers as $headerName => $headerValue )
        {
            if ( $headerValue !== false )
            {
                $filteredHeaders[$headerName] = $headerValue;
            }
        }
        $statusCode = 200;
        if ( isset( $this->headers['Status'] ) )
        {
            $statusCode = sscanf( $this->headers['Status'], '%s %s' );
            $statusCode = (int)$statusCode[0];
        }
        $result = new Message(
            $filteredHeaders,
            ( $this->generator->isEmpty()
                ? null
                : $this->generator->endDocument( $data ) ),
            $statusCode
        );
        $this->headers = array();
        return $result;
    }
eZ\Publish\Core\REST\Common\Output\Visitor::visitValueObject ($data)
Visit struct returned by controllers
Should be called from sub-visitors to visit nested objects.
Parameters
mixed $data
Definition at line 231 of file Visitor.php.
    {
        if ( !is_object( $data ) )
        {
            throw new Exceptions\InvalidTypeException( $data );
        }
        $checkedClassNames = array();
        $classname = get_class( $data );
        do
        {
            $checkedClassNames[] = $classname;
            if ( isset( $this->visitors[$classname] ) )
            {
                return $this->visitors[$classname]->visit( $this, $this->generator, $data );
            }
        }
        while ( $classname = get_parent_class( $classname ) );
        throw new Exceptions\NoVisitorFoundException( $checkedClassNames );
    }
Member Data Documentation
eZ\Publish\Core\REST\Common\Output\Visitor::$generator protected
Definition at line 38 of file Visitor.php.
eZ\Publish\Core\REST\Common\Output\Visitor::$headers = array() protected
Definition at line 45 of file Visitor.php.
eZ\Publish\Core\REST\Common\Output\Visitor::$statusMap static
Definition at line 51 of file Visitor.php.
eZ\Publish\Core\REST\Common\Output\Visitor::$visitors = array() protected
Definition at line 31 of file Visitor.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/Output/Visitor.php