ezp-next: eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentObjectStates Class Reference
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentObjectStates Class Reference
Public Member Functions
visit (Visitor $visitor, Generator $generator, $data)
Public Member Functions inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
__construct (UrlHandler $urlHandler)
Additional Inherited Members
Protected Member Functions inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
serializeBool ($boolValue)
visitNamesList (Generator $generator, array $names)
visitDescriptionsList (Generator $generator, array $descriptions)
visitTranslatedList (Generator $generator, array $translatedElements, $listName)
visitLimitation (Generator $generator, Limitation $limitation)
serializeSortField ($sortField)
serializeSortOrder ($sortOrder)
Protected Attributes inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
$urlHandler
Detailed Description
ContentObjectStates value object visitor
Definition at line 19 of file ContentObjectStates.php.
Member Function Documentation
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentObjectStates::visit (Visitor $visitor, Generator $generator, $data)
Visit struct returned by controllers
Parameters
\eZ\Publish\Core\REST\Common\Output\Visitor $visitor
\eZ\Publish\Core\REST\Common\Output\Generator $generator
\eZ\Publish\Core\REST\Common\Values\ContentObjectStates $data
Reimplemented from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor.
Definition at line 28 of file ContentObjectStates.php.
References eZ\Publish\Core\REST\Common\Output\Generator\endAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\endList(), eZ\Publish\Core\REST\Common\Output\Generator\endObjectElement(), eZ\Publish\Core\REST\Common\Output\Generator\getMediaType(), eZ\Publish\Core\REST\Common\Output\Visitor\setHeader(), eZ\Publish\Core\REST\Common\Output\Generator\startAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\startList(), and eZ\Publish\Core\REST\Common\Output\Generator\startObjectElement().
    {
        $generator->startObjectElement( 'ContentObjectStates' );
        $visitor->setHeader( 'Content-Type', $generator->getMediaType( 'ContentObjectStates' ) );
        $visitor->setHeader( 'Accept-Patch', $generator->getMediaType( 'ContentObjectStates' ) );
        $generator->startList( 'ObjectState' );
        foreach ( $data->states as $state )
        {
            $generator->startObjectElement( 'ObjectState' );
            $generator->startAttribute(
                'href',
                $this->urlHandler->generate(
                    'objectstate',
                    array(
                        'objectstategroup' => $state->groupId,
                        'objectstate' => $state->objectState->id
                    )
                )
            );
            $generator->endAttribute( 'href' );
            $generator->endObjectElement( 'ObjectState' );
        }
        $generator->endList( 'ObjectState' );
        $generator->endObjectElement( 'ContentObjectStates' );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/ContentObjectStates.php