ezp-next: eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator Class Reference
eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator Class Reference
Public Member Functions
__construct (HttpClient $innerClient, $userId=14)
request ($method, $path, Message $message=null)
setUserId ($userId)
setSession ($id)
Protected Attributes
$innerClient
$userId
$sessionId
Detailed Description
Authenticator used in integration tests.
Note: DO NOT USE THIS IN PRODUCTION.
Definition at line 21 of file IntegrationTestAuthenticator.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator::__construct (HttpClient $innerClient, $userId = 14)
Creates a new Integration Test Authenticator
Parameters
\eZ\Publish\Core\REST\Client\HttpClient $innerClient
mixed $userId
Definition at line 50 of file IntegrationTestAuthenticator.php.
References eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator\$userId, and eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator\__construct().
    {
        $this->innerClient = $innerClient;
        $this->userId      = $userId;
    }
Member Function Documentation
eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator::request ($method, $path, Message $message = null)
Execute a HTTP request to the remote server
Returns the result from the remote server. The client sets the correct headers for Basic Auth into the $message transmitted to the inner client.
Parameters
string $method
string $path
\eZ\Publish\Core\REST\Common\Message $message
Returns
Implements eZ\Publish\Core\REST\Client\HttpClient.
Definition at line 69 of file IntegrationTestAuthenticator.php.
    {
        $message = $message ?: new Message();
        $message->headers['X-Test-User'] = $this->userId;
        if ( $this->sessionId !== null && !isset( $message->headers['X-Test-Session'] ) )
        {
            $message->headers['X-Test-Session'] = $this->sessionId;
        }
        return $this->innerClient->request( $method, $path, $message );
    }
eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator::setSession ($id)
Set the session ID to use
Parameters
string $id
Implements eZ\Publish\Core\REST\Client\Sessionable.
Definition at line 98 of file IntegrationTestAuthenticator.php.
References eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator\setSession().
    {
        $this->sessionId = $id;
    }
eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator::setUserId ($userId)
Sets the user ID submitted to the server.
Parameters
mixed $userId
Definition at line 88 of file IntegrationTestAuthenticator.php.
References eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator\$userId, and eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator\setUserId().
    {
        $this->userId = $userId;
    }
Member Data Documentation
eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator::$innerClient protected
Definition at line 28 of file IntegrationTestAuthenticator.php.
eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator::$sessionId protected
Definition at line 42 of file IntegrationTestAuthenticator.php.
eZ\Publish\Core\REST\Client\HttpClient\Authentication\IntegrationTestAuthenticator::$userId protected
Definition at line 35 of file IntegrationTestAuthenticator.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Client/HttpClient/Authentication/IntegrationTestAuthenticator.php