ezp-next: eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\Host Class Reference
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\Host Class Reference
Public Member Functions
__construct (array $siteAccessesConfiguration)
getName ()
setRequest (SimplifiedRequest $request)
Public Member Functions inherited from eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map
setMapKey ($key)
match ()
Additional Inherited Members
Protected Attributes inherited from eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map
$key
$map
Detailed Description
Definition at line 16 of file Host.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\Host::__construct (array $siteAccessesConfiguration)
Constructor.
Parameters
array $siteAccessesConfiguration SiteAccesses configuration.
Reimplemented from eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map.
Definition at line 23 of file Host.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\__construct().
    {
        parent::__construct( $siteAccessesConfiguration );
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\Host::getName ()
Returns the matcher's name. This information will be stored in the SiteAccess object itself to quickly be able to identify the matcher type.
Returns
string
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 28 of file Host.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\Host\getName().
    {
        return 'host:map';
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\Host::setRequest (SimplifiedRequest $request)
Injects the request object to match against.
Parameters
\eZ\Publish\Core\MVC\Symfony\Routing\SimplifiedRequest $request
Returns
void
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 40 of file Host.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\setMapKey(), and eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\Host\setRequest().
    {
        $this->setMapKey( $request->host );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Map/Host.php