ezp-next: eZ\Publish\Core\Persistence\InMemory\TrashHandler Class Reference
eZ\Publish\Core\Persistence\InMemory\TrashHandler Class Reference
Public Member Functions
__construct (Handler $handler, Backend $backend)
loadTrashItem ($id)
trashSubtree ($locationId)
recover ($trashedId, $newParentId)
findTrashItems (Criterion $criterion=null, $offset=0, $limit=null, array $sort=null)
emptyTrash ()
deleteTrashItem ($trashedId)
Protected Attributes
$handler
$backend
Detailed Description
See Also
eZ
Definition at line 19 of file TrashHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\InMemory\TrashHandler::__construct (Handler $handler, Backend $backend)
Setups current handler instance with reference to Handler object that created it.
Parameters
Handler $handler
Backend $backend The storage engine backend
Definition at line 37 of file TrashHandler.php.
References eZ\Publish\Core\Persistence\InMemory\TrashHandler\$backend, and eZ\Publish\Core\Persistence\InMemory\TrashHandler\$handler.
    {
        $this->handler = $handler;
        $this->backend = $backend;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\InMemory\TrashHandler::deleteTrashItem ($trashedId)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 165 of file TrashHandler.php.
References eZ\Publish\Core\Persistence\InMemory\TrashHandler\loadTrashItem().
    {
        $vo = $this->loadTrashItem( $trashedId );
        $this->handler->contentHandler()->deleteContent( $vo->contentId );
        $this->backend->delete( 'Content\\Location\\Trashed', $trashedId );
    }
eZ\Publish\Core\Persistence\InMemory\TrashHandler::emptyTrash ()
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 139 of file TrashHandler.php.
    {
        $trashedIds = array();
        $contentIds = array();
        foreach ( $this->backend->find( 'Content\\Location\\Trashed' ) as $trashed )
        {
            $trashedIds[] = $trashed->id;
            $contentIds[] = $trashed->contentId;
        }
        if ( !empty( $trashedIds ) )
        {
            // Remove associated content for trashed locations
            foreach ( $contentIds as $contentId )
            {
                $this->handler->contentHandler()->deleteContent( $contentId );
            }
            // Remove trashed locations
            $this->backend->deleteByMatch( 'Content\\Location\\Trashed', array( 'id' => $trashedIds ) );
        }
    }
eZ\Publish\Core\Persistence\InMemory\TrashHandler::findTrashItems (Criterion $criterion = null, $offset = 0, $limit = null, array $sort = null)
Limited implementation (no criterion/sort support). Will return all trashed locations, regardless criterion filter or sort clauses provided. Offset/Limit is however supported
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 127 of file TrashHandler.php.
    {
        return array_slice(
            $this->backend->find( 'Content\\Location\\Trashed' ),
            $offset,
            $limit
        );
    }
eZ\Publish\Core\Persistence\InMemory\TrashHandler::loadTrashItem ($id)
See Also
eZ
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 46 of file TrashHandler.php.
    {
        return $this->backend->load( 'Content\\Location\\Trashed', $id );
    }
eZ\Publish\Core\Persistence\InMemory\TrashHandler::recover ($trashedId, $newParentId)
See Also
eZ
Todo:
Handle field types actions
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 101 of file TrashHandler.php.
References eZ\Publish\Core\Persistence\InMemory\TrashHandler\loadTrashItem().
    {
        $trashedLocation = $this->loadTrashItem( $trashedId );
        $newParent = $this->handler->locationHandler()->load( $newParentId );
        // Restore location under $newParent
        $struct = new CreateStruct;
        foreach ( $struct as $property => $value )
        {
            if ( isset( $trashedLocation->$property ) )
            {
                $struct->$property = $trashedLocation->$property;
            }
        }
        $struct->parentId = $newParent->id;
        return $this->handler->locationHandler()->create( $struct )->id;
    }
eZ\Publish\Core\Persistence\InMemory\TrashHandler::trashSubtree ($locationId)
See Also
eZ
Todo:
Handle field types actions
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 55 of file TrashHandler.php.
References eZ\Publish\Core\Persistence\InMemory\TrashHandler\loadTrashItem().
    {
        $location = $this->handler->locationHandler()->load( $locationId );
        $subtreeLocations = $this->backend->find(
            'Content\\Location',
            array( 'pathString' => $location->pathString . '%' )
        );
        $isLocationRemoved = false;
        $parentLocationId = null;
        $subtreeLocations[] = $location;
        foreach ( $subtreeLocations as $location )
        {
            if ( $location->id == $locationId )
            {
                $parentLocationId = $location->parentId;
            }
            if ( count( $this->backend->find( 'Content\\Location', array( 'contentId' => $location->contentId ) ) ) == 1 )
            {
                $this->backend->delete( 'Content\\Location', $location->id );
                $this->backend->create( 'Content\\Location\\Trashed', (array)$location, false );
            }
            else
            {
                if ( $location->id == $locationId )
                {
                    $isLocationRemoved = true;
                }
                $this->backend->delete( 'Content\\Location', $location->id );
                $remainingLocations = $this->backend->find( 'Content\\Location', array( 'contentId' => $location->contentId ) );
                $this->backend->updateByMatch(
                    'Content\\Location',
                    array( 'contentId' => $location->contentId ),
                    array( 'mainLocationId' => $remainingLocations[0]->id )
                );
            }
        }
        return $isLocationRemoved ? null : $this->loadTrashItem( $locationId );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\InMemory\TrashHandler::$backend protected
Definition at line 29 of file TrashHandler.php.
eZ\Publish\Core\Persistence\InMemory\TrashHandler::$handler protected
Definition at line 24 of file TrashHandler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/InMemory/TrashHandler.php