ezp-next: eZ\Publish\Core\REST\Server\Controller\Trash Class Reference
eZ\Publish\Core\REST\Server\Controller\Trash Class Reference
Public Member Functions
__construct (TrashService $trashService, LocationService $locationService)
loadTrashItems ()
loadTrashItem ()
emptyTrash ()
deleteTrashItem ()
restoreTrashItem ()
Public Member Functions inherited from eZ\Publish\Core\REST\Server\Controller
setInputDispatcher (InputDispatcher $inputDispatcher)
setUrlHandler (UrlHandler $urlHandler)
setRequest (HttpRequest $request)
setContainer (Container $container)
Protected Attributes
$trashService
$locationService
Protected Attributes inherited from eZ\Publish\Core\REST\Server\Controller
$request
$inputDispatcher
$urlHandler
$container
Detailed Description
Trash controller
Definition at line 27 of file Trash.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Server\Controller\Trash::__construct (TrashService $trashService, LocationService $locationService)
Construct controller
Parameters
\eZ\Publish\API\Repository\TrashService $trashService
\eZ\Publish\API\Repository\LocationService $locationService
Definition at line 49 of file Trash.php.
References eZ\Publish\Core\REST\Server\Controller\Trash\__construct().
    {
        $this->trashService = $trashService;
        $this->locationService = $locationService;
    }
Member Function Documentation
eZ\Publish\Core\REST\Server\Controller\Trash::deleteTrashItem ()
Deletes the given trash item
Returns
Definition at line 122 of file Trash.php.
References eZ\Publish\Core\REST\Server\Controller\Trash\deleteTrashItem().
    {
        $values = $this->urlHandler->parse( 'trash', $this->request->path );
        $this->trashService->deleteTrashItem(
            $this->trashService->loadTrashItem( $values['trash'] )
        );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\Trash::emptyTrash ()
Empties the trash
Returns
Definition at line 110 of file Trash.php.
References eZ\Publish\Core\REST\Server\Controller\Trash\emptyTrash().
    {
        $this->trashService->emptyTrash();
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\Trash::loadTrashItem ()
Returns the trash item given by id
Returns
Definition at line 96 of file Trash.php.
References eZ\Publish\Core\REST\Server\Controller\Trash\loadTrashItem().
    {
        $values = $this->urlHandler->parse( 'trash', $this->request->path );
        return new Values\RestTrashItem(
            $trashItem = $this->trashService->loadTrashItem( $values['trash'] ),
            $this->locationService->getLocationChildCount( $trashItem )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Trash::loadTrashItems ()
Returns a list of all trash items
Returns
Definition at line 60 of file Trash.php.
References eZ\Publish\Core\REST\Server\Controller\Trash\loadTrashItems().
    {
        $offset = isset( $this->request->variables['offset'] ) ? (int)$this->request->variables['offset'] : 0;
        $limit = isset( $this->request->variables['limit'] ) ? (int)$this->request->variables['limit'] : -1;
        $query = new Query();
        $query->offset = $offset >= 0 ? $offset : null;
        $query->limit = $limit >= 0 ? $limit : null;
        $trashItems = array();
        foreach (
            $this->trashService->findTrashItems(
                $query
            )->items as $trashItem
        )
        {
            $trashItems[] = new Values\RestTrashItem(
                $trashItem,
                $this->locationService->getLocationChildCount( $trashItem )
            );
        }
        return new Values\Trash(
            $trashItems,
            $this->request->path
        );
    }
eZ\Publish\Core\REST\Server\Controller\Trash::restoreTrashItem ()
Restores a trashItem
Returns
Definition at line 137 of file Trash.php.
References eZ\Publish\Core\REST\Server\Controller\Trash\restoreTrashItem().
    {
        $requestDestination = null;
        try
        {
            $requestDestination = $this->request->destination;
        }
        catch ( InvalidArgumentException $e )
        {
            // No Destination header
        }
        $parentLocation = null;
        if ( $requestDestination !== null )
        {
            $destinationValues = $this->urlHandler->parse( 'location', $requestDestination );
            $locationPath = $destinationValues['location'];
            $locationPathParts = explode( '/', $locationPath );
            try
            {
                $parentLocation = $this->locationService->loadLocation( array_pop( $locationPathParts ) );
            }
            catch ( NotFoundException $e )
            {
                throw new ForbiddenException( $e->getMessage() );
            }
        }
        $values = $this->urlHandler->parse( 'trash', $this->request->path );
        $trashItem = $this->trashService->loadTrashItem( $values['trash'] );
        if ( $requestDestination === null )
        {
            // If we're recovering under the original location
            // check if it exists, to return "403 Forbidden" in case it does not
            try
            {
                $this->locationService->loadLocation( $trashItem->parentLocationId );
            }
            catch ( NotFoundException $e )
            {
                throw new ForbiddenException( $e->getMessage() );
            }
        }
        $location = $this->trashService->recover( $trashItem, $parentLocation );
        return new Values\ResourceCreated(
            $this->urlHandler->generate(
                'location',
                array(
                    'location' => rtrim( $location->pathString, '/' ),
                )
            )
        );
    }
Member Data Documentation
eZ\Publish\Core\REST\Server\Controller\Trash::$locationService protected
Definition at line 41 of file Trash.php.
eZ\Publish\Core\REST\Server\Controller\Trash::$trashService protected
Definition at line 34 of file Trash.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Controller/Trash.php