ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler Class Reference
Public Member Functions
__construct (LocationHandler $locationHandler, LocationGateway $locationGateway, LocationMapper $locationMapper, ContentHandler $contentHandler)
loadTrashItem ($id)
trashSubtree ($locationId)
recover ($trashedId, $newParentId)
findTrashItems (Criterion $criterion=null, $offset=0, $limit=null, array $sort=null)
emptyTrash ()
deleteTrashItem ($trashedId)
Protected Member Functions
delete (Trashed $trashItem)
Protected Attributes
$locationHandler
$locationGateway
$locationMapper
$contentHandler
Detailed Description
The Location Handler interface defines operations on Location elements in the storage engine.
Definition at line 23 of file Handler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::__construct (LocationHandler $locationHandler, LocationGateway $locationGateway, LocationMapper $locationMapper, ContentHandler $contentHandler)
Construct from userGateway
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\Location\Handler $locationHandler
\eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway $locationGateway
\eZ\Publish\Core\Persistence\Legacy\Content\Location\Mapper $locationMapper
\eZ\Publish\Core\Persistence\Legacy\Content\Handler $contentHandler
Returns
Definition at line 63 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler\$contentHandler, eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler\$locationGateway, eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler\$locationHandler, and eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler\$locationMapper.
    {
        $this->locationHandler = $locationHandler;
        $this->locationGateway = $locationGateway;
        $this->locationMapper = $locationMapper;
        $this->contentHandler = $contentHandler;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::delete (Trashed $trashItem) protected
Triggers delete operations for $trashItem. If there is no more locations for corresponding content, then it will be deleted as well.
Parameters
\eZ\Publish\SPI\Persistence\Content\Location\Trashed $trashItem
Returns
void
Definition at line 240 of file Handler.php.
    {
        $this->locationGateway->removeElementFromTrash( $trashItem->id );
        if ( $this->locationGateway->countLocationsByContentId( $trashItem->contentId ) < 1 )
            $this->contentHandler->deleteContent( $trashItem->contentId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::deleteTrashItem ($trashedId)
Removes a trashed location identified by $trashedLocationId from trash Associated content has to be deleted
Parameters
int $trashedId
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 227 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler\loadTrashItem().
    {
        $this->delete( $this->loadTrashItem( $trashedId ) );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::emptyTrash ()
Empties the trash Everything contained in the trash must be removed
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 208 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler\findTrashItems().
    {
        $trashedItems = $this->findTrashItems();
        foreach ( $trashedItems as $item )
        {
            $this->delete( $item );
        }
        $this->locationGateway->cleanupTrash();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::findTrashItems (Criterion $criterion = null, $offset = 0, $limit = null, array $sort = null)
Returns an array of all trashed locations satisfying the $criterion (if provided), sorted with SortClause objects contained in $sort (if any). If no criterion is provided (null), no filter is applied
Parameters
\eZ\Publish\API\Repository\Values\Content\Query\Criterion $criterion
int $offset Offset to start listing from, 0 by default
int $limit Limit for the listing. Null by default (no limit)
\eZ\Publish\API\Repository\Values\Content\Query\SortClause[] $sort
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 188 of file Handler.php.
    {
        // CBA: Ignore criterion for now.
        $rows = $this->locationGateway->listTrashed( $offset, $limit, $sort );
        $items = array();
        foreach ( $rows as $row )
        {
            $items[] = $this->locationMapper->createLocationFromRow( $row, null, new Trashed() );
        }
        return $items;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::loadTrashItem ($id)
Loads the data for the trashed location identified by $id. $id is the same as original location (which has been previously trashed)
Parameters
int $id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException
Returns
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 86 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Location\$id.
    {
        $data = $this->locationGateway->loadTrashByLocation( $id );
        return $this->locationMapper->createLocationFromRow( $data, null, new Trashed() );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::recover ($trashedId, $newParentId)
Returns a trashed location to normal state.
Recreates the originally trashed location in the new position. If this is not possible (because the old location does not exist any more), a ParentNotFound exception is thrown.
Returns newly restored location Id.
Parameters
mixed $trashedId
mixed $newParentId
Returns
int Newly restored location id
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If $newParentId is invalid
Todo:
Handle field types actions
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 171 of file Handler.php.
    {
        return $this->locationGateway->untrashLocation( $trashedId, $newParentId )->id;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::trashSubtree ($locationId)
Sends a subtree starting to $locationId to the trash and returns a Trashed object corresponding to $locationId.
Moves all locations in the subtree to the Trash. The associated content objects are left untouched.
Parameters
mixed $locationId
Todo:
Handle field types actions
Returns
null| null if location was deleted, otherwise Trashed object
Implements eZ\Publish\SPI\Persistence\Content\Location\Trash\Handler.
Definition at line 105 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler\loadTrashItem().
    {
        $locationRows = $this->locationGateway->getSubtreeContent( $locationId );
        $isLocationRemoved = false;
        $parentLocationId = null;
        foreach ( $locationRows as $locationRow )
        {
            if ( $locationRow["node_id"] == $locationId )
            {
                $parentLocationId = $locationRow["parent_node_id"];
            }
            if ( $this->locationGateway->countLocationsByContentId( $locationRow["contentobject_id"] ) == 1 )
            {
                $this->locationGateway->trashLocation( $locationRow["node_id"] );
            }
            else
            {
                if ( $locationRow["node_id"] == $locationId )
                {
                    $isLocationRemoved = true;
                }
                $this->locationGateway->removeLocation( $locationRow["node_id"] );
                if ( $locationRow["node_id"] == $locationRow["main_node_id"] )
                {
                    $newMainLocationRow = $this->locationGateway->getFallbackMainNodeData(
                        $locationRow["contentobject_id"],
                        $locationRow["node_id"]
                    );
                    $this->locationHandler->changeMainLocation(
                        $locationRow["contentobject_id"],
                        $newMainLocationRow["node_id"],
                        $newMainLocationRow["contentobject_version"],
                        $newMainLocationRow["parent_node_id"]
                    );
                }
            }
        }
        if ( isset( $parentLocationId ) )
        {
            $this->locationHandler->markSubtreeModified( $parentLocationId, time() );
        }
        return $isLocationRemoved ? null : $this->loadTrashItem( $locationId );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::$contentHandler protected
Definition at line 51 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::$locationGateway protected
Definition at line 37 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::$locationHandler protected
Definition at line 30 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Location\Trash\Handler::$locationMapper protected
Definition at line 44 of file Handler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Location/Trash/Handler.php