ezp-next: eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler Class Reference
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler Class Reference
Public Member Functions
__construct (Handler $handler, Backend $backend)
createGroup (InputStruct $input)
loadGroup ($groupId)
loadGroupByIdentifier ($identifier)
loadAllGroups ($offset=0, $limit=-1)
loadObjectStates ($groupId)
updateGroup ($groupId, InputStruct $input)
deleteGroup ($groupId)
create ($groupId, InputStruct $input)
load ($stateId)
loadByIdentifier ($identifier, $groupId)
update ($stateId, InputStruct $input)
setPriority ($stateId, $priority)
delete ($stateId)
setContentState ($contentId, $groupId, $stateId)
getContentState ($contentId, $stateGroupId)
getContentCount ($stateId)
Protected Member Functions
getInputData (InputStruct $input)
getContentToStateMap ()
getObjectStateContentList ($stateId)
getGroupStateList ($groupId)
Protected Attributes
$handler
$backend
Detailed Description
The Object State Handler class provides managing of object states and groups
Definition at line 21 of file ObjectStateHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::__construct (Handler $handler, Backend $backend)
Setups current handler instance with reference to Handler object that created it.
Parameters
Handler $handler
Backend $backend The storage engine backend
Definition at line 39 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\$backend, and eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\$handler.
    {
        $this->handler = $handler;
        $this->backend = $backend;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::create ($groupId, InputStruct $input)
Creates a new object state in the given group. The new state gets the last priority. Note: in current kernel: If it is the first state all content objects will set to this state.
Parameters
mixed $groupId
\eZ\Publish\SPI\Persistence\Content\ObjectState\InputStruct $input
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 170 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getInputData(), and eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\loadObjectStates().
    {
        $inputData = $this->getInputData( $input );
        $newPriority = 0;
        $objectStates = $this->loadObjectStates( $groupId );
        if ( !empty( $objectStates ) )
        {
            $newPriority = $objectStates[count( $objectStates ) - 1]->priority + 1;
        }
        $inputData["groupId"] = (int)$groupId;
        $inputData["priority"] = $newPriority;
        $createdState = $this->backend->create( 'Content\\ObjectState', $inputData );
        if ( $newPriority == 0 )
        {
            $allContentInfos = $this->backend->find( "Content\\ContentInfo" );
            $allContentIds = array_map(
                function( ContentInfo $contentInfo )
                {
                    return $contentInfo->id;
                },
                $allContentInfos
            );
            $this->backend->update( "Content\\ObjectState", $createdState->id, array( "_contentId" => $allContentIds ) );
        }
        return $createdState;
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::createGroup (InputStruct $input)
Creates a new object state group
Parameters
\eZ\Publish\SPI\Persistence\Content\ObjectState\InputStruct $input
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 52 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getInputData().
    {
        return $this->backend->create( 'Content\\ObjectState\\Group', $this->getInputData( $input ) );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::delete ($stateId)
Deletes a object state. The state of the content objects is reset to the first object state in the group.
Parameters
mixed $stateId
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 291 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getObjectStateContentList(), eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\load(), and eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\loadObjectStates().
    {
        // We need to load the object state as we need $groupId
        $objectState = $this->load( $stateId );
        // Find all content for the current $stateId
        $contentList = $this->getObjectStateContentList( $stateId );
        // Delete the state
        $this->backend->delete( 'Content\\ObjectState', $stateId );
        // Update the priorities of the group states if there are any more states in the group
        $groupStates = $this->loadObjectStates( $objectState->groupId );
        if ( empty( $groupStates ) )
            return;
        $priority = 0;
        foreach ( $groupStates as $groupState )
        {
            $this->backend->update( 'Content\\ObjectState', $groupState->id, array( "priority" => $priority ) );
            $priority++;
        }
        // Now reassign content from old state to the first state in the group
        $firstObjectState = current( $this->backend->find( "Content\\ObjectState", array( "priority" => 0 ) ) );
        $existingContent = $this->getObjectStateContentList( $firstObjectState->id ) + $contentList;
        $existingContent = array_values( array_unique( $existingContent ) );
        $this->backend->update( 'Content\\ObjectState', $firstObjectState->id, array( "_contentId" => $existingContent ) );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::deleteGroup ($groupId)
Deletes a object state group including all states and links to content
Parameters
mixed $groupId
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 153 of file ObjectStateHandler.php.
    {
        $this->backend->deleteByMatch( 'Content\\ObjectState', array( 'groupId' => $groupId ) );
        $this->backend->delete( 'Content\\ObjectState\\Group', $groupId );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::getContentCount ($stateId)
Returns the number of objects which are in this state
Parameters
mixed $stateId
Returns
int
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 398 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getObjectStateContentList().
    {
        return count( $this->getObjectStateContentList( $stateId ) );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::getContentState ($contentId, $stateGroupId)
Gets the object-state of object identified by $contentId.
The $state is the id of the state within one group.
Parameters
mixed $contentId
mixed $stateGroupId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if no state is found
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 372 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getContentToStateMap(), eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getGroupStateList(), and eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\load().
    {
        $groupStateIds = $this->getGroupStateList( $stateGroupId );
        if ( empty( $groupStateIds ) )
            throw new NotFound( "Content\\ObjectState", array( "groupId" => $stateGroupId ) );
        $contentId = (int)$contentId;
        $contentToStateMap = $this->getContentToStateMap();
        if ( !isset( $contentToStateMap[$contentId] ) )
            throw new NotFound( "Content\\ObjectState", array( "groupId" => $stateGroupId ) );
        $foundStates = array_values( array_intersect( $groupStateIds, $contentToStateMap[$contentId] ) );
        if ( empty( $foundStates ) )
            throw new NotFound( "Content\\ObjectState", array( "groupId" => $stateGroupId ) );
        return $this->load( $foundStates[0] );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::getContentToStateMap () protected
Gets a mapping array of all content and states they belong to
This method serves as a hack because InMemory storage is unable to store M:N relations between content and object states as there's no value object for the link
Returns
array
Definition at line 426 of file ObjectStateHandler.php.
    {
        $contentToStateMap = array();
        $contentInfoArray = $this->backend->find( "Content\\ContentInfo" );
        foreach ( $contentInfoArray as $contentInfo )
        {
            $objectStates = $this->backend->find( "Content\\ObjectState", array( "_contentId" => $contentInfo->id ) );
            foreach ( $objectStates as $objectState )
            {
                $contentToStateMap[$contentInfo->id][] = $objectState->id;
            }
        }
        return $contentToStateMap;
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::getGroupStateList ($groupId) protected
Returns all state IDs that belong to $groupId
Parameters
int $groupId
Returns
array
Definition at line 469 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\loadObjectStates().
    {
        $groupStates = $this->loadObjectStates( $groupId );
        return array_map(
            function ( ObjectState $objectState )
            {
                return $objectState->id;
            },
            $groupStates
        );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::getInputData (InputStruct $input) protected
Converts InputStruct to array and adds missing languageCodes array into it
Parameters
\eZ\Publish\SPI\Persistence\Content\ObjectState\InputStruct $input
Returns
array
Definition at line 410 of file ObjectStateHandler.php.
    {
        $inputData = (array)$input;
        $inputData["languageCodes"] = array_keys( $input->name );
        return $inputData;
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::getObjectStateContentList ($stateId) protected
Returns all content IDs that belong to $stateId
Parameters
int $stateId
Returns
array
Definition at line 450 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getContentToStateMap().
    {
        $contentList = array();
        foreach ( $this->getContentToStateMap() as $contentId => $stateList )
        {
            if ( in_array( $stateId, $stateList ) )
                $contentList[] = $contentId;
        }
        return $contentList;
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::load ($stateId)
Loads an object state
Parameters
mixed $stateId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the state was not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 212 of file ObjectStateHandler.php.
    {
        return $this->backend->load( 'Content\\ObjectState', $stateId );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::loadAllGroups ($offset = 0, $limit = -1)
Loads all object state groups
Parameters
int $offset
int $limit
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 99 of file ObjectStateHandler.php.
    {
        $objectStateGroups = array();
        foreach ( $this->backend->find( 'Content\\ObjectState\\Group', array() ) as $objectStateGroup )
        {
            $objectStateGroups[] = $objectStateGroup;
        }
        return array_slice( $objectStateGroups, $offset, $limit >= 0 ? $limit : null );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::loadByIdentifier ($identifier, $groupId)
Loads an object state by identifier and group it belongs to
Parameters
string $identifier
mixed $groupId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the state was not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 227 of file ObjectStateHandler.php.
    {
        $objectStates = $this->backend->find(
            'Content\\ObjectState',
            array(
                'identifier' => $identifier,
                'groupId' => $groupId
            )
        );
        if ( empty( $objectStates ) )
        {
            throw new NotFound( "Content\\ObjectState", array( "identifier" => $identifier, "groupId" => $groupId ) );
        }
        return reset( $objectStates );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::loadGroup ($groupId)
Loads a object state group
Parameters
mixed $groupId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the group was not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 66 of file ObjectStateHandler.php.
    {
        return $this->backend->load( 'Content\\ObjectState\\Group', $groupId );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::loadGroupByIdentifier ($identifier)
Loads a object state group by identifier
Parameters
string $identifier
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the group was not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 80 of file ObjectStateHandler.php.
    {
        $objectStateGroups = $this->backend->find( 'Content\\ObjectState\\Group', array( 'identifier' => $identifier ) );
        if ( empty( $objectStateGroups ) )
        {
            throw new NotFound( "Content\\ObjectState\\Group", array( "identifier" => $identifier ) );
        }
        return reset( $objectStateGroups );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::loadObjectStates ($groupId)
This method returns the ordered list of object states of a group
Parameters
mixed $groupId
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 116 of file ObjectStateHandler.php.
    {
        $objectStates = $this->backend->find( 'Content\\ObjectState', array( 'groupId' => $groupId ) );
        usort(
            $objectStates,
            function( ObjectState $first, ObjectState $second )
            {
                if ( $first->priority == $second->priority )
                    return 0;
                return $first->priority > $second->priority ? 1 : -1;
            }
        );
        return $objectStates;
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::setContentState ($contentId, $groupId, $stateId)
Sets the object-state of a state group to $stateId for the given content.
Parameters
mixed $contentId
mixed $groupId
mixed $stateId
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 332 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getContentToStateMap(), eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getGroupStateList(), and eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getObjectStateContentList().
    {
        $groupStateIds = $this->getGroupStateList( $groupId );
        if ( empty( $groupStateIds ) || !in_array( $stateId, $groupStateIds ) )
            return false;
        $contentToStateMap = $this->getContentToStateMap();
        // If the content was in one of the group states,
        // find all content for the old state and update the old state with excluded $contentId
        $existingStateIds = array_values( array_intersect( $groupStateIds, $contentToStateMap[(int)$contentId] ) );
        if ( !empty( $existingStateIds ) )
        {
            $oldStateContentList = $this->getObjectStateContentList( $existingStateIds[0] );
            $oldStateContentList = array_values( array_diff( $oldStateContentList, array( $contentId ) ) );
            $this->backend->update( "Content\\ObjectState", $existingStateIds[0], array( "_contentId" => $oldStateContentList ) );
        }
        // Find all content for the new state and update the new state with added $contentId
        $newStateContentList = $this->getObjectStateContentList( $stateId );
        $newStateContentList[] = $contentId;
        $this->backend->update( "Content\\ObjectState", $stateId, array( "_contentId" => $newStateContentList ) );
        return true;
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::setPriority ($stateId, $priority)
Changes the priority of the state
Parameters
mixed $stateId
int $priority
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 265 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\load(), and eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\loadObjectStates().
    {
        $objectState = $this->load( $stateId );
        $groupStates = $this->loadObjectStates( $objectState->groupId );
        $priorityList = array();
        foreach ( $groupStates as $index => $groupState )
        {
            $priorityList[$groupState->id] = $index;
        }
        $priorityList[$objectState->id] = (int)$priority;
        asort( $priorityList );
        foreach ( array_keys( $priorityList ) as $objectStatePriority => $objectStateId )
        {
            $this->backend->update( 'Content\\ObjectState', $objectStateId, array( "priority" => $objectStatePriority ) );
        }
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::update ($stateId, InputStruct $input)
Updates an object state
Parameters
mixed $stateId
\eZ\Publish\SPI\Persistence\Content\ObjectState\InputStruct $input
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 253 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getInputData(), and eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\load().
    {
        $this->backend->update( 'Content\\ObjectState', $stateId, $this->getInputData( $input ) );
        return $this->load( $stateId );
    }
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::updateGroup ($groupId, InputStruct $input)
Updates an object state group
Parameters
mixed $groupId
\eZ\Publish\SPI\Persistence\Content\ObjectState\InputStruct $input
Returns
Implements eZ\Publish\SPI\Persistence\Content\ObjectState\Handler.
Definition at line 142 of file ObjectStateHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\getInputData(), and eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler\loadGroup().
    {
        $this->backend->update( 'Content\\ObjectState\\Group', $groupId, $this->getInputData( $input ) );
        return $this->loadGroup( $groupId );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::$backend protected
Definition at line 31 of file ObjectStateHandler.php.
eZ\Publish\Core\Persistence\InMemory\ObjectStateHandler::$handler protected
Definition at line 26 of file ObjectStateHandler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/InMemory/ObjectStateHandler.php