ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\ContentId Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\ContentId Class Reference
Public Member Functions
accept (SortClause $sortClause)
applySelect (ezcQuerySelect $query, SortClause $sortClause, $number)
Public Member Functions inherited from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler
__construct (EzcDbHandler $dbHandler)
applyJoin (ezcQuerySelect $query, SortClause $sortClause, $number)
Additional Inherited Members
Protected Member Functions inherited from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler
getSortColumnName ($number)
getSortTableName ($number)
Protected Attributes inherited from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler
$dbHandler
Detailed Description
Content locator gateway implementation using the zeta database component.
Definition at line 19 of file ContentId.php.
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\ContentId::accept (SortClause $sortClause)
Check if this sort clause handler accepts to handle the given sort clause.
Parameters
\eZ\Publish\API\Repository\Values\Content\Query\SortClause $sortClause
Returns
boolean
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler.
Definition at line 28 of file ContentId.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\ContentId\accept().
    {
        return $sortClause instanceof SortClause\ContentId;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\ContentId::applySelect (ezcQuerySelect $query, SortClause $sortClause, $number)
Apply selects to the query
Returns the name of the (aliased) column, which information should be used for sorting.
Parameters
\ezcQuerySelect $query
\eZ\Publish\API\Repository\Values\Content\Query\SortClause $sortClause
int $number
Returns
string
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler.
Definition at line 45 of file ContentId.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\ContentId\applySelect(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\getSortColumnName().
    {
        $query
            ->select(
                $query->alias(
                    $this->dbHandler->quoteColumn(
                        "id",
                        "ezcontentobject"
                    ),
                    $column = $this->getSortColumnName( $number )
                )
            );
        return $column;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Search/Gateway/SortClauseHandler/ContentId.php