ezp-next: eZ\Publish\Core\FieldType\Image\Type Class Reference
eZ\Publish\Core\FieldType\Image\Type Class Reference
Public Member Functions
__construct (FileService $fileService)
getFieldTypeIdentifier ()
getName ($value)
getEmptyValue ()
isEmptyValue ($value)
validate (FieldDefinition $fieldDefinition, $fieldValue)
validateValidatorConfiguration ($validatorConfiguration)
fromHash ($hash)
toHash ($value)
toPersistenceValue ($value)
fromPersistenceValue (FieldValue $fieldValue)
Public Member Functions inherited from eZ\Publish\Core\FieldType\FieldType
getSettingsSchema ()
getValidatorConfigurationSchema ()
validateFieldSettings ($fieldSettings)
isSearchable ()
acceptValue ($inputValue)
fieldSettingsToHash ($fieldSettings)
fieldSettingsFromHash ($fieldSettingsHash)
validatorConfigurationToHash ($validatorConfiguration)
validatorConfigurationFromHash ($validatorConfigurationHash)
Protected Member Functions
internalAcceptValue ($inputValue)
fileExists ($path)
getSortInfo ($value)
Protected Attributes
$validatorConfigurationSchema
$fileService
Protected Attributes inherited from eZ\Publish\Core\FieldType\FieldType
$settingsSchema = array()
$validatorConfigurationSchema = array()
Detailed Description
The Image field type
Definition at line 22 of file Type.php.
Constructor & Destructor Documentation
eZ\Publish\Core\FieldType\Image\Type::__construct (FileService $fileService)
Creates a new Image FieldType
Parameters
FileService $fileService
Definition at line 48 of file Type.php.
References eZ\Publish\Core\FieldType\Image\Type\$fileService.
    {
        $this->fileService = $fileService;
    }
Member Function Documentation
eZ\Publish\Core\FieldType\Image\Type::fileExists ($path) protected
Returns if the given $path exists on the local disc or in the file storage
Parameters
string $path
Returns
boolean
Definition at line 182 of file Type.php.
    {
        return (
            ( substr( $path, 0, 1 ) === '/' && file_exists( $path ) )
            || $this->fileService->exists( $path )
        );
    }
eZ\Publish\Core\FieldType\Image\Type::fromHash ($hash)
Converts an $hash to the Value defined by the field type
Parameters
mixed $hash
Returns
$value
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 303 of file Type.php.
    {
        if ( $hash === null )
        {
            // empty value
            return null;
        }
        return new Value( $hash );
    }
eZ\Publish\Core\FieldType\Image\Type::fromPersistenceValue (FieldValue $fieldValue)
Converts a persistence $fieldValue to a Value
Parameters
\eZ\Publish\SPI\Persistence\Content\FieldValue $fieldValue
Returns
mixed
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 362 of file Type.php.
References eZ\Publish\Core\FieldType\Image\Type\fromHash().
    {
        if ( $fieldValue->data === null )
        {
            // empty value
            return null;
        }
        // Restored data comes in $data, since it has already been processed
        // there might be more data in the persistence value than needed here
        $result = $this->fromHash(
            array(
                'alternativeText' => ( isset( $fieldValue->data['alternativeText'] )
                    ? $fieldValue->data['alternativeText']
                    : null ),
                'fileName' => ( isset( $fieldValue->data['fileName'] )
                    ? $fieldValue->data['fileName']
                    : null ),
                'fileSize' => ( isset( $fieldValue->data['fileSize'] )
                    ? $fieldValue->data['fileSize']
                    : null ),
                'path' => ( isset( $fieldValue->data['path'] )
                    ? $fieldValue->data['path']
                    : null ),
            )
        );
        return $result;
    }
eZ\Publish\Core\FieldType\Image\Type::getEmptyValue ()
Returns the fallback default value of field type when no such default value is provided in the field definition in content types.
Returns
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 86 of file Type.php.
    {
        return new Value;
    }
eZ\Publish\Core\FieldType\Image\Type::getFieldTypeIdentifier ()
Returns the field type identifier for this field type
Returns
string
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 58 of file Type.php.
    {
        return 'ezimage';
    }
eZ\Publish\Core\FieldType\Image\Type::getName ($value)
Returns the name of the given field value.
It will be used to generate content name and url alias if current field is designated to be used in the content name/urlAlias pattern.
Parameters
mixed $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 73 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\acceptValue().
    {
        $value = $this->acceptValue( $value );
        return !empty( $value->alternativeText ) ? $value->alternativeText : $value->originalFilename;
    }
eZ\Publish\Core\FieldType\Image\Type::getSortInfo ($value) protected
See Also
::getSortInfo()
Todo:
Correct?
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 291 of file Type.php.
    {
        return false;
    }
eZ\Publish\Core\FieldType\Image\Type::internalAcceptValue ($inputValue) protected
Implements the core of {
See Also
acceptValue()}.
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 98 of file Type.php.
References eZ\Publish\Core\FieldType\Image\Value\fromString().
    {
        // default construction from array
        if ( is_array( $inputValue ) )
        {
            $inputValue = new Value( $inputValue );
        }
        // just given the file path as a string
        else if ( is_string( $inputValue ) )
        {
            $inputValue = Value::fromString( $inputValue );
        }
        if ( !$inputValue instanceof Value )
        {
            throw new InvalidArgumentType(
                '$inputValue',
                'eZ\\Publish\\Core\\FieldType\\Image\\Value',
                $inputValue
            );
        }
        // Required parameter $path
        if ( !isset( $inputValue->path ) || !$this->fileExists( $inputValue->path ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->path',
                'Existing fileName',
                $inputValue->path
            );
        }
        // Required parameter $fileName
        if ( !isset( $inputValue->fileName ) || !is_string( $inputValue->fileName ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->fileName',
                'string',
                $inputValue->fileName
            );
        }
        // Required parameter $fileSize
        if ( !isset( $inputValue->fileSize ) || !is_int( $inputValue->fileSize ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->fileSize',
                'string',
                $inputValue->fileSize
            );
        }
        // Optional parameter $alternativeText
        if ( isset( $inputValue->alternativeText ) && !is_string( $inputValue->alternativeText ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->alternativeText',
                'string',
                $inputValue->alternativeText
            );
        }
        return $inputValue;
    }
eZ\Publish\Core\FieldType\Image\Type::isEmptyValue ($value)
Returns if the given $value is considered empty by the field type
Parameters
mixed $value
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 169 of file Type.php.
    {
        return $value === null || $value->fileName === null;
    }
eZ\Publish\Core\FieldType\Image\Type::toHash ($value)
Converts a $Value to a hash
Parameters
\eZ\Publish\Core\FieldType\Image\Value $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 321 of file Type.php.
References eZ\Publish\Core\FieldType\Image\Type\isEmptyValue().
    {
        if ( $this->isEmptyValue( $value ) )
        {
            return null;
        }
        return array(
            'alternativeText' => $value->alternativeText,
            'fileName' => $value->fileName,
            'fileSize' => $value->fileSize,
            'path' => $value->path,
        );
    }
eZ\Publish\Core\FieldType\Image\Type::toPersistenceValue ($value)
Converts a $value to a persistence value
Parameters
mixed $value
Returns
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 343 of file Type.php.
References eZ\Publish\Core\FieldType\Image\Type\getSortInfo(), and eZ\Publish\Core\FieldType\Image\Type\toHash().
    {
        // Store original data as external (to indicate they need to be stored)
        return new FieldValue(
            array(
                "data" => null,
                "externalData" => $this->toHash( $value ),
                "sortKey" => $this->getSortInfo( $value ),
            )
        );
    }
eZ\Publish\Core\FieldType\Image\Type::validate (FieldDefinition $fieldDefinition, $fieldValue)
Validates a field based on the validators in the field definition
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException
Parameters
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition The field definition of the field
\eZ\Publish\Core\FieldType\Value $fieldValue The field for which an action is performed
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 200 of file Type.php.
References eZ\Publish\API\Repository\Values\ContentType\FieldDefinition\getValidatorConfiguration().
    {
        $errors = array();
        foreach ( (array)$fieldDefinition->getValidatorConfiguration() as $validatorIdentifier => $parameters )
        {
            switch ( $validatorIdentifier )
            {
                case 'FileSizeValidator':
                    if ( !isset( $parameters['maxFileSize'] ) || $parameters['maxFileSize'] == false )
                    {
                        // No file size limit
                        break;
                    }
                    // Database stores maxFileSize in MB
                    if ( $fieldValue !== null && ( $parameters['maxFileSize'] * 1024 * 1024 ) < $fieldValue->fileSize )
                    {
                        $errors[] = new ValidationError(
                            "The file size cannot exceed %size% byte.",
                            "The file size cannot exceed %size% bytes.",
                            array(
                                "size" => $parameters['maxFileSize'],
                            )
                        );
                    }
                    break;
            }
        }
        return $errors;
    }
eZ\Publish\Core\FieldType\Image\Type::validateValidatorConfiguration ($validatorConfiguration)
Validates the validatorConfiguration of a FieldDefinitionCreateStruct or FieldDefinitionUpdateStruct
Parameters
mixed $validatorConfiguration
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 237 of file Type.php.
    {
        $validationErrors = array();
        foreach ( $validatorConfiguration as $validatorIdentifier => $parameters )
        {
            switch ( $validatorIdentifier )
            {
                case 'FileSizeValidator':
                    if ( !isset( $parameters['maxFileSize'] ) )
                    {
                        $validationErrors[] = new ValidationError(
                            "Validator %validator% expects parameter %parameter% to be set.",
                            null,
                            array(
                                "validator" => $validatorIdentifier,
                                "parameter" => 'maxFileSize',
                            )
                        );
                        break;
                    }
                    if ( !is_int( $parameters['maxFileSize'] ) && !is_bool( $parameters['maxFileSize'] ) )
                    {
                        $validationErrors[] = new ValidationError(
                            "Validator %validator% expects parameter %parameter% to be of %type%.",
                            null,
                            array(
                                "validator" => $validatorIdentifier,
                                "parameter" => 'maxFileSize',
                                "type" => 'integer',
                            )
                        );
                    }
                    break;
                default:
                    $validationErrors[] = new ValidationError(
                        "Validator '%validator%' is unknown",
                        null,
                        array(
                            "validator" => $validatorIdentifier
                        )
                    );
            }
        }
        return $validationErrors;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\Image\Type::$fileService protected
Definition at line 41 of file Type.php.
eZ\Publish\Core\FieldType\Image\Type::$validatorConfigurationSchema protected
Initial value:
 array(
        "FileSizeValidator" => array(
            'maxFileSize' => array(
                'type' => 'int',
                'default' => false,
            )
        )
    )
See Also
eZ::$validatorConfigurationSchema
Definition at line 27 of file Type.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Image/Type.php