ezp-next: eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage Class Reference
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage Class Reference
Public Member Functions
__construct (array $gateways, IOService $IOService, PathGenerator $pathGenerator, MimeTypeDetector $mimeTypeDetector)
storeFieldData (VersionInfo $versionInfo, Field $field, array $context)
copyLegacyField (VersionInfo $versionInfo, Field $field, Field $originalField, array $context)
getFieldData (VersionInfo $versionInfo, Field $field, array $context)
deleteFieldData (VersionInfo $versionInfo, array $fieldIds, array $context)
hasFieldData ()
getIndexData (VersionInfo $versionInfo, Field $field, array $context)
Public Member Functions inherited from eZ\Publish\Core\FieldType\GatewayBasedStorage
__construct (array $gateways=array())
addGateway ($identifier, StorageGateway $gateway)
Protected Member Functions
removeOldFile ($fieldId, $versionNo, array $context)
Protected Member Functions inherited from eZ\Publish\Core\FieldType\GatewayBasedStorage
getGateway (array $context)
Protected Attributes
$IOService
$pathGenerator
$mimeTypeDetector
Protected Attributes inherited from eZ\Publish\Core\FieldType\GatewayBasedStorage
$gateways
Detailed Description
Storage for binary files
Definition at line 22 of file BinaryBaseStorage.php.
Constructor & Destructor Documentation
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage::__construct (array $gateways, IOService $IOService, PathGenerator $pathGenerator, MimeTypeDetector $mimeTypeDetector)
Construct from gateways
Parameters
\eZ\Publish\Core\FieldType\StorageGateway[] $gateways
IOService $IOService
PathGenerator $pathGenerator
Definition at line 46 of file BinaryBaseStorage.php.
References eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\$IOService, eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\$mimeTypeDetector, and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\$pathGenerator.
    {
        parent::__construct( $gateways );
        $this->IOService = $IOService;
        $this->pathGenerator = $pathGenerator;
        $this->mimeTypeDetector = $mimeTypeDetector;
    }
Member Function Documentation
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage::copyLegacyField (VersionInfo $versionInfo, Field $field, Field $originalField, array $context)
This method is used exclusively by Legacy Storage to copy external data of existing field in main language to the untranslatable field not passed in create or update struct, but created implicitly in storage layer.
By default the method falls back to the eZ\Publish\SPI\FieldType\FieldStorage::storeFieldData().Externalstoragesimplementthismethodasneeded.@param\eZ\Publish\SPI\Persistence\Content\VersionInfo$versionInfo@param\eZ\Publish\SPI\Persistence\Content\Field$field@param\eZ\Publish\SPI\Persistence\Content\Field$originalField@paramarray$context@returnnull|booleanSameas@link\eZ\Publish\SPI\FieldType\FieldStorage::storeFieldData().
Reimplemented from eZ\Publish\Core\FieldType\GatewayBasedStorage.
Definition at line 121 of file BinaryBaseStorage.php.
References eZ\Publish\Core\FieldType\GatewayBasedStorage\getGateway().
    {
        if ( $originalField->value->data === null )
            return false;
        // field translations have their own file reference, but to the original file
        $originalField->value->externalData['path'];
        return $this->getGateway( $context )->storeFileReference( $versionInfo, $field );
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage::deleteFieldData (VersionInfo $versionInfo, array $fieldIds, array $context)
Deletes all referenced external data
Parameters
VersionInfo $versionInfo
array $fieldIds
array $context
Returns
boolean
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 202 of file BinaryBaseStorage.php.
References eZ\Publish\Core\IO\IOService\deleteBinaryFile(), eZ\Publish\Core\FieldType\GatewayBasedStorage\getGateway(), and eZ\Publish\Core\IO\IOService\loadBinaryFile().
    {
        $gateway = $this->getGateway( $context );
        $referencedFiles = $gateway->getReferencedFiles( $fieldIds, $versionInfo->versionNo );
        $gateway->removeFileReferences( $fieldIds, $versionInfo->versionNo );
        $referenceCountMap = $gateway->countFileReferences( $referencedFiles );
        foreach ( $referenceCountMap as $filePath => $count )
        {
            if ( $count === 0 )
            {
                $this->IOService->deleteBinaryFile(
                    $this->IOService->loadBinaryFile( $filePath )
                );
            }
        }
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage::getFieldData (VersionInfo $versionInfo, Field $field, array $context)
Populates $field value property based on the external data. $field->value is a eZ object. This value holds the data as a eZ based object, according to the field type (e.g. for TextLine, it will be a eZ object).
Parameters
\eZ\Publish\SPI\Persistence\Content\VersionInfo $versionInfo
\eZ\Publish\SPI\Persistence\Content\Field $field
array $context
Returns
void
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 177 of file BinaryBaseStorage.php.
References eZ\Publish\Core\FieldType\GatewayBasedStorage\getGateway(), and eZ\Publish\Core\IO\IOService\loadBinaryFile().
    {
        $field->value->externalData = $this->getGateway( $context )->getFileReferenceData( $field->id, $versionInfo->versionNo );
        if ( $field->value->externalData !== null )
        {
            if ( ( $binaryFile = $this->IOService->loadBinaryFile( $field->value->externalData['path'] ) ) !== false )
            {
                $field->value->externalData['fileSize'] = $binaryFile->size;
            }
            else
            {
                throw new \RuntimeException( "Failed loading binary file {$field->value->externalData['path']}" );
            }
        }
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage::getIndexData (VersionInfo $versionInfo, Field $field, array $context)
Parameters
\eZ\Publish\SPI\Persistence\Content\VersionInfo $versionInfo
\eZ\Publish\SPI\Persistence\Content\Field $field
array $context
Returns
void
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 240 of file BinaryBaseStorage.php.
    {
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage::hasFieldData ()
Checks if field type has external data to deal with
Returns
boolean
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 228 of file BinaryBaseStorage.php.
    {
        return true;
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage::removeOldFile ($fieldId, $versionNo, array $context) protected
Removes the old file referenced by $fieldId in $versionNo, if not referenced else where
Parameters
mixed $fieldId
string $versionNo
array $context
Returns
void
Definition at line 142 of file BinaryBaseStorage.php.
References eZ\Publish\Core\IO\IOService\deleteBinaryFile(), eZ\Publish\Core\FieldType\GatewayBasedStorage\getGateway(), and eZ\Publish\Core\IO\IOService\loadBinaryFile().
    {
        $gateway = $this->getGateway( $context );
        $fileReference = $gateway->getFileReferenceData( $fieldId, $versionNo );
        if ( $fileReference === null )
        {
            // No previous file
            return;
        }
        $gateway->removeFileReference( $fieldId, $versionNo );
        $fileCounts = $gateway->countFileReferences( array( $fileReference['path'] ) );
        if ( $fileCounts[$fileReference['path']] === 0 )
        {
            $this->IOService->deleteBinaryFile(
                $this->IOService->loadBinaryFile( $fileReference['path'] )
            );
        }
    }
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage::storeFieldData (VersionInfo $versionInfo, Field $field, array $context)
Allows custom field types to store data in an external source (e.g. another DB table).
Stores value for $field in an external data source. The whole eZ ValueObject is passed and its value is accessible through the eZ 'value' property. This value holds the data filled by the user as a eZ based object, according to the field type (e.g. for TextLine, it will be a eZ object).
$field->id = unique ID from the attribute tables (needs to be generated by database back end on create, before the external data source may be called from storing).
The context array provides some context for the field handler about the currently used storage engine. The array should at least define 2 keys :
identifier (connection identifier)
connection (the connection handler) For example, using Legacy storage engine, $context will be:
identifier = 'LegacyStorage'
connection = eZ\Publish\Core\Persistence\Legacy\EzcDbHandlerobjecthandler(forDBconnection),tobeusedaccordinglyto@linkhttp://incubator.apache.org/zetacomponents/documentation/trunk/Database/tutorial.htmlezcDatabaseusage@param\eZ\Publish\SPI\Persistence\Content\VersionInfo$versionInfo@param\eZ\Publish\SPI\Persistence\Content\Field$field@paramarray$context@returnvoid
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 84 of file BinaryBaseStorage.php.
References eZ\Publish\Core\IO\IOService\createBinaryFile(), eZ\Publish\Core\FieldType\GatewayBasedStorage\getGateway(), eZ\Publish\Core\IO\IOService\loadBinaryFile(), eZ\Publish\Core\IO\IOService\newBinaryCreateStructFromLocalFile(), and eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage\removeOldFile().
    {
        if ( $field->value->externalData === null )
        {
            // Nothing to store
            return false;
        }
        // no mimeType means we are dealing with an input, local file
        if ( !isset( $field->value->externalData['mimeType'] ) )
        {
            $field->value->externalData['mimeType'] = $this->mimeTypeDetector->getFromPath( $field->value->externalData['path'] );
        }
        $storedValue = $field->value->externalData;
        $storagePath = $this->pathGenerator->getStoragePathForField( $field, $versionInfo );
        // The file referenced in externalData MAY be an existing IOService file which we can use
        if ( ( $this->IOService->loadBinaryFile( $storedValue['path'] ) === false ) &&
             ( $this->IOService->loadBinaryFile( $storagePath ) === false ) )
        {
            $createStruct = $this->IOService->newBinaryCreateStructFromLocalFile(
                $storedValue['path']
            );
            $createStruct->uri = $storagePath;
            $this->IOService->createBinaryFile( $createStruct );
            $storedValue['path'] = $createStruct->uri;
            $storedValue['mimeType'] = $createStruct->mimeType;
        }
        $field->value->externalData = $storedValue;
        $this->removeOldFile( $field->id, $versionInfo->versionNo, $context );
        return $this->getGateway( $context )->storeFileReference( $versionInfo, $field );
    }
Member Data Documentation
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage::$IOService protected
Definition at line 29 of file BinaryBaseStorage.php.
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage::$mimeTypeDetector protected
Definition at line 37 of file BinaryBaseStorage.php.
eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage::$pathGenerator protected
Definition at line 32 of file BinaryBaseStorage.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage.php