ezp-next: eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor Class Reference
eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor Class Reference
Inherited by eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\ContentObjectStates, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\Limitation, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\LocationCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\LocationUpdateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\ObjectStateCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\ObjectStateGroupCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\ObjectStateGroupUpdateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\ObjectStateUpdateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\PolicyCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\PolicyUpdateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\RoleAssignment, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\RoleCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\RoleUpdateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\SectionCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\SectionIncludingContentMetadataUpdateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\SectionUpdateStruct, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentObjectStates, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentTypeGroup, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentTypeGroupList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentTypeGroupRefList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentTypeInfoList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentTypeList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Exception, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\LocationList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\NoContent, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ObjectStateGroup, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ObjectStateGroupList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ObjectStateList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\PermanentRedirect, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Policy, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\PolicyList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RelationList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ResourceCreated, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestContent, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestContentTypeBase, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestExecutedView, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestLocation, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestObjectState, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestRelation, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestTrashItem, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestUser, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestUserGroup, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestUserGroupRoleAssignment, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestUserRoleAssignment, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Role, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RoleAssignmentList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RoleList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Root, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Section, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\SectionList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\TemporaryRedirect, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Trash, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLAlias, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLAliasList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLAliasRefList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLWildcard, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLWildcardList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\UserGroupList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\UserGroupRefList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\UserList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\UserRefList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Version, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\VersionInfo, and eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\VersionList.
Public Member Functions
__construct (UrlHandler $urlHandler)
visit (Visitor $visitor, Generator $generator, $data)
Protected Member Functions
serializeBool ($boolValue)
visitNamesList (Generator $generator, array $names)
visitDescriptionsList (Generator $generator, array $descriptions)
visitTranslatedList (Generator $generator, array $translatedElements, $listName)
visitLimitation (Generator $generator, Limitation $limitation)
serializeSortField ($sortField)
serializeSortOrder ($sortOrder)
Protected Attributes
$urlHandler
Detailed Description
Basic ValueObjectVisitor
Definition at line 19 of file ValueObjectVisitor.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor::__construct (UrlHandler $urlHandler)
Construct from used URL handler
Parameters
\eZ\Publish\Core\REST\Common\UrlHandler $urlHandler
Definition at line 33 of file ValueObjectVisitor.php.
References eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor\$urlHandler.
    {
        $this->urlHandler = $urlHandler;
    }
Member Function Documentation
eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor::serializeBool ($boolValue) protected
Returns a string representation for the given $boolValue
Parameters
boolean $boolValue
Returns
string
Definition at line 54 of file ValueObjectVisitor.php.
    {
        return ( $boolValue ? 'true' : 'false' );
    }
eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor::serializeSortField ($sortField) protected
Serializes the given $sortField to a string representation
Parameters
int $sortField
Returns
string
Definition at line 138 of file ValueObjectVisitor.php.
References eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_CLASS_IDENTIFIER, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_CLASS_NAME, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_CONTENTOBJECT_ID, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_DEPTH, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_MODIFIED, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_MODIFIED_SUBNODE, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_NAME, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_NODE_ID, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_PATH, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_PRIORITY, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_PUBLISHED, and eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_SECTION.
    {
        switch ( $sortField )
        {
            case Location::SORT_FIELD_PATH:
                return 'PATH';
            case Location::SORT_FIELD_PUBLISHED:
                return 'PUBLISHED';
            case Location::SORT_FIELD_MODIFIED:
                return 'MODIFIED';
            case Location::SORT_FIELD_SECTION:
                return 'SECTION';
            case Location::SORT_FIELD_DEPTH:
                return 'DEPTH';
            case Location::SORT_FIELD_CLASS_IDENTIFIER:
                return 'CLASS_IDENTIFIER';
            case Location::SORT_FIELD_CLASS_NAME:
                return 'CLASS_NAME';
            case Location::SORT_FIELD_PRIORITY:
                return 'PRIORITY';
            case Location::SORT_FIELD_NAME:
                return 'NAME';
            case Location::SORT_FIELD_MODIFIED_SUBNODE:
                return 'MODIFIED_SUBNODE';
            case Location::SORT_FIELD_NODE_ID:
                return 'NODE_ID';
            case Location::SORT_FIELD_CONTENTOBJECT_ID:
                return 'CONTENTOBJECT_ID';
        }
        throw new \RuntimeException( "Unknown default sort field: '{$sortField}'." );
    }
eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor::serializeSortOrder ($sortOrder) protected
Serializes the given $sortOrder to a string representation
Parameters
int $sortOrder
Returns
string
Definition at line 178 of file ValueObjectVisitor.php.
References eZ\Publish\API\Repository\Values\Content\Location\SORT_ORDER_ASC, and eZ\Publish\API\Repository\Values\Content\Location\SORT_ORDER_DESC.
    {
        switch ( $sortOrder )
        {
            case Location::SORT_ORDER_ASC:
                return 'ASC';
            case Location::SORT_ORDER_DESC:
                return 'DESC';
        }
        throw new \RuntimeException( "Unknown default sort order: '{$sortOrder}'." );
    }
eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor::visit (Visitor $visitor, Generator $generator, $data) abstract
Visit struct returned by controllers
Parameters
\eZ\Publish\Core\REST\Common\Output\Visitor $visitor
\eZ\Publish\Core\REST\Common\Output\Generator $generator
mixed $data
Reimplemented in eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Exception, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestExecutedView, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestFieldDefinition, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Version, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\LocationCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\LocationUpdateStruct, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentTypeInfoList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentTypeList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ObjectStateList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RelationList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestContent, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestRelation, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestUserGroupRoleAssignment, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestUserRoleAssignment, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\FieldDefinitionList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestContentType, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestUser, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestUserGroup, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RoleAssignmentList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLAlias, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\VersionInfo, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\ContentObjectStates, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\Limitation, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\ObjectStateCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\ObjectStateGroupCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\ObjectStateGroupUpdateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\ObjectStateUpdateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\PolicyCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\PolicyUpdateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\RoleAssignment, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\RoleCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\RoleUpdateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\SectionCreateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\SectionIncludingContentMetadataUpdateStruct, eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\SectionUpdateStruct, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentObjectStates, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentTypeGroup, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentTypeGroupList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ContentTypeGroupRefList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\LocationList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\NoContent, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ObjectStateGroup, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ObjectStateGroupList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\PermanentRedirect, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Policy, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\PolicyList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\ResourceCreated, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestLocation, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestObjectState, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestTrashItem, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Role, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RoleList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Root, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Section, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\SectionList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\TemporaryRedirect, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\Trash, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLAliasList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLAliasRefList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLWildcard, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLWildcardList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\UserGroupList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\UserGroupRefList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\UserList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\UserRefList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\VersionList, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedContent, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedContentType, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedContentTypeGroup, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedFieldDefinition, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedLocation, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedObjectState, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedObjectStateGroup, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedPolicy, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedRelation, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedRole, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedSection, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedURLAlias, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedURLWildcard, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedUser, eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedUserGroup, and eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedVersion.
eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor::visitDescriptionsList (Generator $generator, array $descriptions) protected
Visits the given list of $descriptions
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator $generator
array $descriptions
Definition at line 76 of file ValueObjectVisitor.php.
References eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor\visitTranslatedList().
    {
        $this->visitTranslatedList( $generator, $descriptions, 'descriptions' );
    }
eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor::visitLimitation (Generator $generator, Limitation $limitation) protected
Visits a limitation
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator $generator
\eZ\Publish\API\Repository\Values\User\Limitation $limitation
Definition at line 107 of file ValueObjectVisitor.php.
References eZ\Publish\Core\REST\Common\Output\Generator\endAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\endHashElement(), eZ\Publish\Core\REST\Common\Output\Generator\endList(), eZ\Publish\Core\REST\Common\Output\Generator\endObjectElement(), eZ\Publish\API\Repository\Values\User\Limitation\getIdentifier(), eZ\Publish\Core\REST\Common\Output\Generator\startAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\startHashElement(), eZ\Publish\Core\REST\Common\Output\Generator\startList(), and eZ\Publish\Core\REST\Common\Output\Generator\startObjectElement().
    {
        $generator->startHashElement( 'limitation' );
        $generator->startAttribute( 'identifier', $limitation->getIdentifier() );
        $generator->endAttribute( 'identifier' );
        $generator->startHashElement( 'values' );
        $generator->startList( 'ref' );
        foreach ( $limitation->limitationValues as $limitationValue )
        {
            $generator->startObjectElement( 'ref' );
            $generator->startAttribute( 'href', $limitationValue );
            $generator->endAttribute( 'href' );
            $generator->endObjectElement( 'ref' );
        }
        $generator->endList( 'ref' );
        $generator->endHashElement( 'values' );
        $generator->endHashElement( 'limitation' );
    }
eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor::visitNamesList (Generator $generator, array $names) protected
Visits the given list of $names
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator $generator
array $names
Definition at line 65 of file ValueObjectVisitor.php.
References eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor\visitTranslatedList().
    {
        $this->visitTranslatedList( $generator, $names, 'names' );
    }
eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor::visitTranslatedList (Generator $generator, array $translatedElements, $listName) protected
Visits a list of translated elements
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator $generator
array $translatedElements
mixed $listName
Definition at line 88 of file ValueObjectVisitor.php.
References eZ\Publish\Core\REST\Common\Output\Generator\endHashElement(), eZ\Publish\Core\REST\Common\Output\Generator\endList(), eZ\Publish\Core\REST\Common\Output\Generator\endValueElement(), eZ\Publish\Core\REST\Common\Output\Generator\startHashElement(), eZ\Publish\Core\REST\Common\Output\Generator\startList(), and eZ\Publish\Core\REST\Common\Output\Generator\startValueElement().
    {
        $generator->startHashElement( $listName );
        $generator->startList( 'value' );
        foreach ( $translatedElements as $languageCode => $element )
        {
            $generator->startValueElement( 'value', $element, array( 'languageCode' => $languageCode ) );
            $generator->endValueElement( 'value' );
        }
        $generator->endList( 'value' );
        $generator->endHashElement( $listName );
    }
Member Data Documentation
eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor::$urlHandler protected
Definition at line 26 of file ValueObjectVisitor.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/Output/ValueObjectVisitor.php