ezp-next: eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate Class Reference
eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate Class Reference
Public Member Functions
__construct (array $visitors=array())
addVisitor (FacetBuilderVisitor $visitor)
canMap ($field)
map ($field, array $data)
canVisit (FacetBuilder $facetBuilder)
visit (FacetBuilder $facetBuilder)
Protected Attributes
$visitors = array()
Additional Inherited Members
Protected Member Functions inherited from eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor
mapData (array $data)
Detailed Description
Visits the facet builder tree into a Solr query
Definition at line 19 of file Aggregate.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate::__construct (array $visitors = array())
COnstruct from optional visitor array
Parameters
array $visitors
Returns
void
Definition at line 35 of file Aggregate.php.
References eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate\$visitors, eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate\__construct(), and eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate\addVisitor().
    {
        foreach ( $visitors as $visitor )
        {
            $this->addVisitor( $visitor );
        }
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate::addVisitor (FacetBuilderVisitor $visitor)
Adds visitor
Parameters
FieldValueVisitor $visitor
Returns
void
Definition at line 50 of file Aggregate.php.
References eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate\addVisitor().
    {
        $this->visitors[] = $visitor;
    }
eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate::canMap ($field)
CHeck if visitor is applicable to current facet result
Parameters
string $field
Returns
boolean
Reimplemented from eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor.
Definition at line 62 of file Aggregate.php.
    {
        return true;
    }
eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate::canVisit (FacetBuilder $facetBuilder)
CHeck if visitor is applicable to current facet builder
Parameters
FacetBuilder $facetBuilder
Returns
boolean
Reimplemented from eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor.
Definition at line 95 of file Aggregate.php.
    {
        return true;
    }
eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate::map ($field, array $data)
Map Solr facet result back to facet objects
Parameters
string $field
array $data
Returns
Facet
Reimplemented from eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor.
Definition at line 75 of file Aggregate.php.
    {
        foreach ( $this->visitors as $visitor )
        {
            if ( $visitor->canMap( $field ) )
            {
                return $visitor->map( $field, $data );
            }
        }
        throw new \OutOfRangeException( "No visitor available for: " . $field );
    }
eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate::visit (FacetBuilder $facetBuilder)
Map field value to a proper Solr representation
Parameters
FacetBuilder $facetBuilder
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor.
Definition at line 107 of file Aggregate.php.
    {
        foreach ( $this->visitors as $visitor )
        {
            if ( $visitor->canVisit( $facetBuilder ) )
            {
                return $visitor->visit( $facetBuilder );
            }
        }
        throw new NotImplementedException( "No visitor available for: " . get_class( $facetBuilder ) );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Solr\Content\Search\FacetBuilderVisitor\Aggregate::$visitors = array() protected
Definition at line 26 of file Aggregate.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Solr/Content/Search/FacetBuilderVisitor/Aggregate.php