ezp-next: eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestRelation Class Reference
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestRelation Class Reference
Public Member Functions
visit (Visitor $visitor, Generator $generator, $data)
Public Member Functions inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
__construct (UrlHandler $urlHandler)
Protected Member Functions
getRelationTypeString ($relationType)
Protected Member Functions inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
serializeBool ($boolValue)
visitNamesList (Generator $generator, array $names)
visitDescriptionsList (Generator $generator, array $descriptions)
visitTranslatedList (Generator $generator, array $translatedElements, $listName)
visitLimitation (Generator $generator, Limitation $limitation)
serializeSortField ($sortField)
serializeSortOrder ($sortOrder)
Additional Inherited Members
Protected Attributes inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
$urlHandler
Detailed Description
RestRelation value object visitor
Definition at line 21 of file RestRelation.php.
Member Function Documentation
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestRelation::getRelationTypeString ($relationType) protected
Returns $relationType as a readable string
Parameters
int $relationType
Returns
string
Definition at line 93 of file RestRelation.php.
    {
        switch ( $relationType )
        {
            case RelationValue::COMMON:
                return 'COMMON';
            case RelationValue::EMBED:
                return 'EMBED';
            case RelationValue::LINK:
                return 'LINK';
            case RelationValue::FIELD:
                return 'ATTRIBUTE';
        }
        throw new \Exception( 'Unknown relation type ' . $relationType . '.' );
    }
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestRelation::visit (Visitor $visitor, Generator $generator, $data)
Visit struct returned by controllers
Parameters
\eZ\Publish\Core\REST\Common\Output\Visitor $visitor
\eZ\Publish\Core\REST\Common\Output\Generator $generator
\eZ\Publish\Core\REST\Server\Values\RestRelation $data
Reimplemented from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor.
Reimplemented in eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedRelation.
Definition at line 30 of file RestRelation.php.
References eZ\Publish\Core\REST\Common\Output\Generator\endAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\endObjectElement(), eZ\Publish\Core\REST\Common\Output\Generator\endValueElement(), eZ\Publish\Core\REST\Common\Output\Generator\getMediaType(), eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestRelation\getRelationTypeString(), eZ\Publish\Core\REST\Common\Output\Visitor\setHeader(), eZ\Publish\Core\REST\Common\Output\Generator\startAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\startObjectElement(), and eZ\Publish\Core\REST\Common\Output\Generator\startValueElement().
    {
        $generator->startObjectElement( 'Relation' );
        $visitor->setHeader( 'Content-Type', $generator->getMediaType( 'Relation' ) );
        $generator->startAttribute(
            'href',
            $this->urlHandler->generate(
                'objectVersionRelation',
                array(
                    'object' => $data->contentId,
                    'version' => $data->versionNo,
                    'relation' => $data->relation->id
                )
            )
        );
        $generator->endAttribute( 'href' );
        $generator->startObjectElement( 'SourceContent', 'ContentInfo' );
        $generator->startAttribute(
            'href',
            $this->urlHandler->generate(
                'object',
                array(
                    'object' => $data->contentId,
                )
            )
        );
        $generator->endAttribute( 'href' );
        $generator->endObjectElement( 'SourceContent' );
        $generator->startObjectElement( 'DestinationContent', 'ContentInfo' );
        $generator->startAttribute(
            'href',
            $this->urlHandler->generate(
                'object',
                array(
                    'object' => $data->relation->getDestinationContentInfo()->id,
                )
            )
        );
        $generator->endAttribute( 'href' );
        $generator->endObjectElement( 'DestinationContent' );
        if ( $data->relation->sourceFieldDefinitionIdentifier !== null )
        {
            $generator->startValueElement( 'SourceFieldDefinitionIdentifier', $data->relation->sourceFieldDefinitionIdentifier );
            $generator->endValueElement( 'SourceFieldDefinitionIdentifier' );
        }
        $generator->startValueElement( 'RelationType', $this->getRelationTypeString( $data->relation->type ) );
        $generator->endValueElement( 'RelationType' );
        $generator->endObjectElement( 'Relation' );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestRelation.php