ezp-next: eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage Class Reference
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage Class Reference
Public Member Functions
storeFieldData (VersionInfo $versionInfo, Field $field, array $context)
getFieldData (VersionInfo $versionInfo, Field $field, array $context)
deleteFieldData (VersionInfo $versionInfo, array $fieldIds, array $context)
hasFieldData ()
getIndexData (VersionInfo $versionInfo, Field $field, array $context)
Public Member Functions inherited from eZ\Publish\Core\FieldType\GatewayBasedStorage
__construct (array $gateways)
addGateway ($identifier, StorageGateway $gateway)
Additional Inherited Members
Protected Member Functions inherited from eZ\Publish\Core\FieldType\GatewayBasedStorage
getGateway (array $context)
Protected Attributes inherited from eZ\Publish\Core\FieldType\GatewayBasedStorage
$gateways
Detailed Description
Storage for the MapLocation field type
Definition at line 19 of file MapLocationStorage.php.
Member Function Documentation
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage::deleteFieldData (VersionInfo $versionInfo, array $fieldIds, array $context)
Parameters
VersionInfo $versionInfo
array $fieldId
array $context
Returns
boolean
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 55 of file MapLocationStorage.php.
References eZ\Publish\Core\FieldType\GatewayBasedStorage\getGateway().
    {
        $this->getGateway( $context )->deleteFieldData( $versionInfo, $fieldIds );
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage::getFieldData (VersionInfo $versionInfo, Field $field, array $context)
Populates $field value property based on the external data. $field->value is a eZ object. This value holds the data as a eZ based object, according to the field type (e.g. for TextLine, it will be a eZ object).
Parameters
\eZ\Publish\SPI\Persistence\Content\Field $field
array $context
Returns
void
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 42 of file MapLocationStorage.php.
References eZ\Publish\Core\FieldType\GatewayBasedStorage\getGateway().
    {
        $gateway = $this->getGateway( $context );
        $gateway->getFieldData( $versionInfo, $field );
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage::getIndexData (VersionInfo $versionInfo, Field $field, array $context)
Parameters
\eZ\Publish\SPI\Persistence\Content\Field $field
array $context
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 74 of file MapLocationStorage.php.
    {
        return ( is_array( $field->value->externalData ) ? $field->value->externalData['address'] : null );
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage::hasFieldData ()
Checks if field type has external data to deal with
Returns
boolean
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 65 of file MapLocationStorage.php.
    {
        return true;
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage::storeFieldData (VersionInfo $versionInfo, Field $field, array $context)
See Also
Implements eZ\Publish\SPI\FieldType\FieldStorage.
Definition at line 24 of file MapLocationStorage.php.
References eZ\Publish\Core\FieldType\GatewayBasedStorage\getGateway().
    {
        $gateway = $this->getGateway( $context );
        return $gateway->storeFieldData( $versionInfo, $field );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/MapLocation/MapLocationStorage.php