ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler Class Reference
Public Member Functions
__construct (EzcDbHandler $dbHandler)
accept (SortClause $sortClause)
applySelect (ezcQuerySelect $query, SortClause $sortClause, $number)
applyJoin (ezcQuerySelect $query, SortClause $sortClause, $number)
Protected Member Functions
getSortColumnName ($number)
getSortTableName ($number)
Protected Attributes
$dbHandler
Detailed Description
Handler for a single sort clause
Definition at line 18 of file SortClauseHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler::__construct (EzcDbHandler $dbHandler)
Creates a new criterion handler
Parameters
\eZ\Publish\Core\Persistence\Legacy\EzcDbHandler $dbHandler
Definition at line 32 of file SortClauseHandler.php.
    {
        $this->dbHandler = $dbHandler;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler::accept (SortClause $sortClause) abstract
Check if this sort clause handler accepts to handle the given sort clause.
Parameters
\eZ\Publish\API\Repository\Values\Content\Query\SortClause $sortClause
Returns
boolean
Reimplemented in eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\ContentId, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\ContentName, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\DateModified, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\DatePublished, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\Field, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\LocationDepth, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\LocationPathString, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\LocationPriority, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\SectionIdentifier, and eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\SectionName.
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler::applyJoin (ezcQuerySelect $query, SortClause $sortClause, $number)
Applies joins to the query
Parameters
\ezcQuerySelect $query
\eZ\Publish\API\Repository\Values\Content\Query\SortClause $sortClause
int $number
Returns
void
Reimplemented in eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\Field, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\LocationDepth, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\LocationPathString, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\LocationPriority, and eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\SectionName.
Definition at line 69 of file SortClauseHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\applyJoin().
    {
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler::applySelect (ezcQuerySelect $query, SortClause $sortClause, $number) abstract
Apply selects to the query
Returns the name of the (aliased) column, which information should be used for sorting.
Parameters
\ezcQuerySelect $query
\eZ\Publish\API\Repository\Values\Content\Query\SortClause $sortClause
int $number
Returns
string
Reimplemented in eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\ContentId, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\ContentName, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\DateModified, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\DatePublished, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\Field, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\LocationDepth, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\LocationPathString, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\LocationPriority, eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\SectionIdentifier, and eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\SectionName.
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler::getSortColumnName ($number) protected
Returns the quoted sort column name
Parameters
int $number
Returns
string
Definition at line 80 of file SortClauseHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\getSortColumnName().
    {
        return $this->dbHandler->quoteIdentifier( 'sort_column_' . $number );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler::getSortTableName ($number) protected
Returns the sort table name
Parameters
int $number
Returns
string
Definition at line 92 of file SortClauseHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler\getSortTableName().
    {
        return 'sort_table_' . $number;
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\SortClauseHandler::$dbHandler protected
Definition at line 25 of file SortClauseHandler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Search/Gateway/SortClauseHandler.php