ezp-next: eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\HostElement Class Reference
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\HostElement Class Reference
Public Member Functions
__construct ($elementNumber)
match ()
getName ()
setRequest (SimplifiedRequest $request)
Detailed Description
Definition at line 15 of file HostElement.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\HostElement::__construct ($elementNumber)
Constructor.
Parameters
int $elementNumber Number of elements to take into account.
Definition at line 34 of file HostElement.php.
    {
        $this->elementNumber = (int)$elementNumber;
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\HostElement::getName ()
Returns the matcher's name. This information will be stored in the SiteAccess object itself to quickly be able to identify the matcher type.
Returns
string
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 51 of file HostElement.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\HostElement\getName().
    {
        return 'host:element';
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\HostElement::match ()
Returns matching Siteaccess.
Returns
string|false Siteaccess matched or false.
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 44 of file HostElement.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\HostElement\match().
    {
        $elements = explode( ".", $this->request->host );
        return isset( $elements[$this->elementNumber - 1] ) ? $elements[$this->elementNumber - 1] : false;
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\HostElement::setRequest (SimplifiedRequest $request)
Injects the request object to match against.
Parameters
\eZ\Publish\Core\MVC\Symfony\Routing\SimplifiedRequest $request
Returns
void
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 63 of file HostElement.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\HostElement\setRequest().
    {
        $this->request = $request;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/HostElement.php