ezp-next: eZ\Publish\Core\REST\Common\Output\Generator Class Reference
eZ\Publish\Core\REST\Common\Output\Generator Class Reference
Public Member Functions
reset ()
startDocument ($data)
isEmpty ()
endDocument ($data)
startObjectElement ($name, $mediaTypeName=null)
endObjectElement ($name)
startHashElement ($name)
endHashElement ($name)
startValueElement ($name, $value)
endValueElement ($name)
startList ($name)
endList ($name)
startAttribute ($name, $value)
endAttribute ($name)
getMediaType ($name)
generateFieldTypeHash ($hashElementName, $hashValue)
Protected Member Functions
checkStartDocument ($data)
checkEndDocument ($data)
checkStartObjectElement ($data)
checkEndObjectElement ($data)
checkStartHashElement ($data)
checkEndHashElement ($data)
checkStartValueElement ($data)
checkEndValueElement ($data)
checkStartList ($data)
checkEndList ($data)
checkStartAttribute ($data)
checkEndAttribute ($data)
generateMediaType ($name, $type)
checkStart ($type, $data, array $validParents)
checkEnd ($type, $data)
Protected Attributes
$stack = array()
Detailed Description
Output generator
Definition at line 15 of file Generator.php.
Member Function Documentation
eZ\Publish\Core\REST\Common\Output\Generator::checkEnd ($type, $data) protected
Check close / end operation
Parameters
string $type
mixed $data
Definition at line 360 of file Generator.php.
    {
        $lastTag = array_pop( $this->stack );
        if ( !is_array( $lastTag ) )
        {
            throw new Exceptions\OutputGeneratorException(
                sprintf(
                    "Invalid close: Trying to close on empty stack."
                )
            );
        }
        if ( array( $lastTag[0], $lastTag[1] ) !== array( $type, $data ) )
        {
            throw new Exceptions\OutputGeneratorException(
                sprintf(
                    "Invalid close: Trying to close %s:%s, while last element was %s:%s.",
                    $type,
                    $data,
                    $lastTag[0],
                    $lastTag[1]
                )
            );
        }
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkEndAttribute ($data) protected
Check end attribute
Parameters
mixed $data
Definition at line 282 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEnd().
    {
        $this->checkEnd( 'attribute', $data );
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkEndDocument ($data) protected
Check end document
Parameters
mixed $data
Definition at line 83 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEnd().
    {
        $this->checkEnd( 'document', $data );
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkEndHashElement ($data) protected
Check end hash element
Parameters
mixed $data
Definition at line 178 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEnd().
    {
        $this->checkEnd( 'hashElement', $data );
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkEndList ($data) protected
Check end list
Parameters
mixed $data
Definition at line 247 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEnd().
    {
        $this->checkEnd( 'list', $data );
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkEndObjectElement ($data) protected
Check end object element
Parameters
mixed $data
Definition at line 131 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEnd().
    {
        $this->checkEnd( 'objectElement', $data );
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkEndValueElement ($data) protected
Check end value element
Parameters
mixed $data
Definition at line 213 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEnd().
    {
        $this->checkEnd( 'valueElement', $data );
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkStart ($type, $data, array $validParents) protected
Check close / end operation
Parameters
string $type
mixed $data
array $validParents
Definition at line 326 of file Generator.php.
    {
        $lastTag = end( $this->stack );
        if ( !is_array( $lastTag ) )
        {
            throw new Exceptions\OutputGeneratorException(
                sprintf(
                    "Invalid start: Trying to open outside of a document."
                )
            );
        }
        if ( !in_array( $lastTag[0], $validParents ) )
        {
            throw new Exceptions\OutputGeneratorException(
                sprintf(
                    "Invalid start: Trying to open %s inside %s, valid parent nodes are: %s.",
                    $type,
                    $lastTag[0],
                    implode( ', ', $validParents )
                )
            );
        }
        $this->stack[] = array( $type, $data, array() );
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkStartAttribute ($data) protected
Check start attribute
Parameters
mixed $data
Definition at line 265 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStart().
    {
        $this->checkStart( 'attribute', $data, array( 'objectElement', 'hashElement' ) );
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkStartDocument ($data) protected
Check start document
Parameters
mixed $data
Definition at line 55 of file Generator.php.
    {
        if ( count( $this->stack ) )
        {
            throw new Exceptions\OutputGeneratorException(
                "Starting a document may only be the very first operation."
            );
        }
        $this->stack[] = array( 'document', $data, array() );
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkStartHashElement ($data) protected
Check start hash element
Parameters
mixed $data
Definition at line 148 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStart().
    {
        $this->checkStart( 'hashElement', $data, array( 'document', 'objectElement', 'hashElement', 'list' ) );
        $last = count( $this->stack ) - 2;
        if ( $this->stack[$last][0] !== 'list' )
        {
            // Ensure hash element type only occurs once outside of lists
            if ( isset( $this->stack[$last][2][$data] ) )
            {
                throw new Exceptions\OutputGeneratorException(
                    "Element {$data} may only occur once inside of {$this->stack[$last][0]}."
                );
            }
        }
        $this->stack[$last][2][$data] = true;
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkStartList ($data) protected
Check start list
Parameters
mixed $data
Definition at line 230 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStart().
    {
        $this->checkStart( 'list', $data, array( 'objectElement', 'hashElement' ) );
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkStartObjectElement ($data) protected
Check start object element
Parameters
mixed $data
Definition at line 101 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStart().
    {
        $this->checkStart( 'objectElement', $data, array( 'document', 'objectElement', 'hashElement', 'list' ) );
        $last = count( $this->stack ) - 2;
        if ( $this->stack[$last][0] !== 'list' )
        {
            // Ensure object element type only occurs once outside of lists
            if ( isset( $this->stack[$last][2][$data] ) )
            {
                throw new Exceptions\OutputGeneratorException(
                    "Element {$data} may only occur once inside of {$this->stack[$last][0]}."
                );
            }
        }
        $this->stack[$last][2][$data] = true;
    }
eZ\Publish\Core\REST\Common\Output\Generator::checkStartValueElement ($data) protected
Check start value element
Parameters
mixed $data
Definition at line 196 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStart().
    {
        $this->checkStart( 'valueElement', $data, array( 'objectElement', 'hashElement', 'list' ) );
    }
eZ\Publish\Core\REST\Common\Output\Generator::endAttribute ($name) abstract
End attribute
Parameters
string $name
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::endDocument ($data) abstract
End document
Returns the generated document as a string.
Parameters
mixed $data
Returns
string
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Xml, and eZ\Publish\Core\REST\Common\Output\Generator\Json.
eZ\Publish\Core\REST\Common\Output\Generator::endHashElement ($name) abstract
End hash element
Parameters
string $name
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::endList ($name) abstract
End list
Parameters
string $name
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::endObjectElement ($name) abstract
End object element
Parameters
string $name
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::endValueElement ($name) abstract
End value element
Parameters
string $name
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::generateFieldTypeHash ($hashElementName, $hashValue) abstract
Generates a generic representation of the scalar, hash or list given in $hashValue into the document, using an element of $hashElementName as its parent
Parameters
string $hashElementName
mixed $hashValue
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::generateMediaType ($name, $type) protected
Generates a media type from $name and $type
Parameters
string $name
string $type
Returns
string
Definition at line 304 of file Generator.php.
    {
        return "application/vnd.ez.api.{$name}+{$type}";
    }
eZ\Publish\Core\REST\Common\Output\Generator::getMediaType ($name) abstract
Get media type
Parameters
string $name
Returns
string
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::isEmpty () abstract
Returns if the document is empty or already contains data
Returns
boolean
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Xml, and eZ\Publish\Core\REST\Common\Output\Generator\Json.
eZ\Publish\Core\REST\Common\Output\Generator::reset ()
Reset output visitor to a virgin state
Definition at line 30 of file Generator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\isEmpty().
    {
        $this->stack = array();
        $this->isEmpty = true;
    }
eZ\Publish\Core\REST\Common\Output\Generator::startAttribute ($name, $value) abstract
Start attribute
Parameters
string $name
string $value
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::startDocument ($data) abstract
Start document
Parameters
mixed $data
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::startHashElement ($name) abstract
Start hash element
Parameters
string $name
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::startList ($name) abstract
Start list
Parameters
string $name
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::startObjectElement ($name, $mediaTypeName = null) abstract
Start object element
Parameters
string $name
string $mediaTypeName
Reimplemented in eZ\Publish\Core\REST\Common\Output\Generator\Json, and eZ\Publish\Core\REST\Common\Output\Generator\Xml.
eZ\Publish\Core\REST\Common\Output\Generator::startValueElement ($name, $value) abstract
Start value element
Parameters
string $name
string $value
Member Data Documentation
eZ\Publish\Core\REST\Common\Output\Generator::$stack = array() protected
Definition at line 25 of file Generator.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/Output/Generator.php