ezp-next: eZ\Publish\Core\FieldType\Country\Type Class Reference
eZ\Publish\Core\FieldType\Country\Type Class Reference
Public Member Functions
__construct (array $countriesInfo)
getFieldTypeIdentifier ()
getName ($value)
getEmptyValue ()
validate (FieldDefinition $fieldDefinition, $fieldValue)
fromHash ($hash)
toHash ($value)
isSearchable ()
getIndexData ($value)
validateFieldSettings ($fieldSettings)
Public Member Functions inherited from eZ\Publish\Core\FieldType\FieldType
getSettingsSchema ()
getValidatorConfigurationSchema ()
validateValidatorConfiguration ($validatorConfiguration)
toPersistenceValue ($value)
fromPersistenceValue (FieldValue $fieldValue)
isEmptyValue ($value)
acceptValue ($inputValue)
fieldSettingsToHash ($fieldSettings)
fieldSettingsFromHash ($fieldSettingsHash)
validatorConfigurationToHash ($validatorConfiguration)
validatorConfigurationFromHash ($validatorConfigurationHash)
Protected Member Functions
internalAcceptValue ($inputValue)
getSortInfo ($value)
Protected Attributes
$settingsSchema
$countriesInfo
Protected Attributes inherited from eZ\Publish\Core\FieldType\FieldType
$settingsSchema = array()
$validatorConfigurationSchema = array()
Detailed Description
The Country field type.
This field type represents a simple string.
Definition at line 23 of file Type.php.
Constructor & Destructor Documentation
eZ\Publish\Core\FieldType\Country\Type::__construct (array $countriesInfo)
Parameters
array $countriesInfo Array of countries data
Definition at line 40 of file Type.php.
References eZ\Publish\Core\FieldType\Country\Type\$countriesInfo.
    {
        $this->countriesInfo = $countriesInfo;
    }
Member Function Documentation
eZ\Publish\Core\FieldType\Country\Type::fromHash ($hash)
Converts an $hash to the Value defined by the field type
Parameters
mixed $hash
Returns
$value
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 202 of file Type.php.
    {
        if ( $hash === null )
        {
            return null;
        }
        $countries = array();
        foreach ( $hash as $country )
        {
            foreach ( $this->countriesInfo as $countryInfo )
            {
                switch ( $country )
                {
                    case $countryInfo["Name"]:
                    case $countryInfo["Alpha2"]:
                    case $countryInfo["Alpha3"]:
                    $countries[$countryInfo["Alpha2"]] = $countryInfo;
                        continue 3;
                }
            }
            throw new InvalidValue( $country );
        }
        return new Value( $countries );
    }
eZ\Publish\Core\FieldType\Country\Type::getEmptyValue ()
Returns the fallback default value of field type when no such default value is provided in the field definition in content types.
Returns
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 85 of file Type.php.
    {
        return new Value;
    }
eZ\Publish\Core\FieldType\Country\Type::getFieldTypeIdentifier ()
Returns the field type identifier for this field type
Returns
string
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 50 of file Type.php.
    {
        return "ezcountry";
    }
eZ\Publish\Core\FieldType\Country\Type::getIndexData ($value)
Get index data for field data for search backend
Parameters
mixed $value
Returns
[]
Definition at line 264 of file Type.php.
    {
        throw new \RuntimeException( '@todo: Implement' );
    }
eZ\Publish\Core\FieldType\Country\Type::getName ($value)
Returns the name of the given field value.
It will be used to generate content name and url alias if current field is designated to be used in the content name/urlAlias pattern.
Parameters
mixed $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 65 of file Type.php.
References eZ\Publish\Core\FieldType\Country\Type\$countriesInfo.
    {
        return implode(
            ", ",
            array_map(
                function ( $countryInfo )
                {
                    return $countryInfo["Name"];
                },
                $this->countriesInfo
            )
        );
    }
eZ\Publish\Core\FieldType\Country\Type::getSortInfo ($value) protected
Returns information for FieldValue->$sortKey relevant to the field type.
Returns
array
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 177 of file Type.php.
    {
        if ( $value === null )
        {
            return "";
        }
        $countries = array();
        foreach ( $value->countries as $countryInfo )
        {
            $countries[] = strtolower( $countryInfo["Name"] );
        }
        sort( $countries );
        return implode( ",", $countries );
    }
eZ\Publish\Core\FieldType\Country\Type::internalAcceptValue ($inputValue) protected
Implements the core of {
See Also
acceptValue()}.
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 97 of file Type.php.
References eZ\Publish\Core\FieldType\Country\Type\fromHash(), and eZ\Publish\Core\FieldType\Country\Type\getEmptyValue().
    {
        if ( is_array( $inputValue ) )
        {
            if ( empty( $inputValue ) )
                return $this->getEmptyValue();
            $inputValue = $this->fromHash( $inputValue );
        }
        if ( !$inputValue instanceof Value )
        {
            throw new InvalidArgumentType(
                '$inputValue',
                'eZ\\Publish\\Core\\FieldType\\Country\\Value',
                $inputValue
            );
        }
        if ( !is_array( $inputValue->countries ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->countries',
                'array',
                $inputValue->countries
            );
        }
        return $inputValue;
    }
eZ\Publish\Core\FieldType\Country\Type::isSearchable ()
Returns whether the field type is searchable
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 252 of file Type.php.
    {
        return true;
    }
eZ\Publish\Core\FieldType\Country\Type::toHash ($value)
Converts a $Value to a hash
Parameters
\eZ\Publish\Core\FieldType\Country\Value $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 237 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\isEmptyValue().
    {
        if ( $this->isEmptyValue( $value ) )
        {
            return null;
        }
        return array_keys( $value->countries );
    }
eZ\Publish\Core\FieldType\Country\Type::validate (FieldDefinition $fieldDefinition, $fieldValue)
Validates field value against 'isMultiple' setting.
Does not use validators.
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException
Parameters
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition The field definition of the field
\eZ\Publish\Core\FieldType\Value $fieldValue The field for which an action is performed
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 140 of file Type.php.
    {
        $validationErrors = array();
        $fieldSettings = $fieldDefinition->fieldSettings;
        if ( ( !isset( $fieldSettings["isMultiple"] ) || $fieldSettings["isMultiple"] === false )
            && count( $fieldValue->countries ) > 1 )
        {
            $validationErrors[] = new ValidationError(
                "Field definition does not allow multiple countries to be selected.",
                null,
                array()
            );
        }
        foreach ( $fieldValue->countries as $alpha2 => $countryInfo )
        {
            if ( !isset( $this->countriesInfo[$alpha2] ) )
            {
                $validationErrors[] = new ValidationError(
                    "Country with Alpha2 code '%alpha2%' is not defined in FieldType settings.",
                    null,
                    array(
                        "alpha2" => $alpha2
                    )
                );
            }
        }
        return $validationErrors;
    }
eZ\Publish\Core\FieldType\Country\Type::validateFieldSettings ($fieldSettings)
Validates the fieldSettings of a FieldDefinitionCreateStruct or FieldDefinitionUpdateStruct
Parameters
mixed $fieldSettings
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 276 of file Type.php.
    {
        $validationErrors = array();
        foreach ( (array)$fieldSettings as $name => $value )
        {
            if ( isset( $this->settingsSchema[$name] ) )
            {
                switch ( $name )
                {
                    case "isMultiple":
                        if ( !is_bool( $value ) )
{
                            $validationErrors[] = new ValidationError(
                                "Setting '%setting%' value must be of boolean type",
                                null,
                                array(
                                    "setting" => $name
                                )
                            );
                        }
                        break;
                }
            }
            else
            {
                $validationErrors[] = new ValidationError(
                    "Setting '%setting%' is unknown",
                    null,
                    array(
                        "setting" => $name
                    )
                );
            }
        }
        return $validationErrors;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\Country\Type::$countriesInfo protected
Definition at line 35 of file Type.php.
eZ\Publish\Core\FieldType\Country\Type::$settingsSchema protected
Initial value:
 array(
        "isMultiple" => array(
            "type" => "boolean",
            "default" => false
        )
    )
Definition at line 25 of file Type.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Country/Type.php