ezp-next: eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger Class Reference
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger Class Reference
Public Member Functions
__construct (CacheService $cache, LocationHandlerInterface $locationHandler, LoggerInterface $logger)
all ()
isAllCleared ()
resetAllCleared ()
setIsEnabled ($isEnabled)
isEnabled ()
content ($locationIds=null)
contentType ($id=null)
contentTypeGroup ($id=null)
section ($id=null)
languages ($ids)
user ($id=null)
Protected Attributes
$cache
$locationHandler
$allCleared = false
$isEnabled = true
$logger
Detailed Description
Definition at line 18 of file PersistenceCachePurger.php.
Constructor & Destructor Documentation
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::__construct (CacheService $cache, LocationHandlerInterface $locationHandler, LoggerInterface $logger)
Setups current handler with everything needed
Parameters
\Tedivm\StashBundle\Service\CacheService $cache
\eZ\Publish\SPI\Persistence\Content\Location\Handler $locationHandler
Definition at line 55 of file PersistenceCachePurger.php.
References eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\$cache, eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\$locationHandler, and eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\$logger.
    {
        $this->cache = $cache;
        $this->locationHandler = $locationHandler;
        $this->logger = $logger;
    }
Member Function Documentation
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::all ()
Clear all persistence cache
Sets a internal flag 'allCleared' to avoid clearing cache several times
Definition at line 67 of file PersistenceCachePurger.php.
References eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\isEnabled().
    {
        if ( $this->isEnabled === false )
            return;
        $this->cache->clear();
        $this->allCleared = true;
    }
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::content ($locationIds = null)
Clear all content persistence cache, or by locationIds (legacy content/cache mechanism is location based).
Either way all location and urlAlias cache is cleared as well.
Parameters
int|int[]|null $locationIds Ids of location we need to purge content cache for. Purges all content cache if null
Returns
array|int|[]|null
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentType On invalid $id type
Definition at line 131 of file PersistenceCachePurger.php.
References eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\isEnabled().
    {
        if ( $this->allCleared === true || $this->isEnabled === false )
            return;
        if ( $locationIds === null )
        {
            $this->cache->clear( 'content' );
            goto relatedCache;
        }
        else if ( !is_array( $locationIds ) )
        {
            $locationIds = array( $locationIds );
        }
        foreach ( $locationIds as $id )
        {
            if ( !is_scalar( $id ) )
                throw new InvalidArgumentType( "\$id", "int[]|null", $id );
            try
            {
                $location = $this->locationHandler->load( $id );
                $this->cache->clear( 'content', $location->contentId );
                $this->cache->clear( 'content', 'info', $location->contentId );
            }
            catch ( NotFoundException $e )
            {
                $this->logger->notice(
                    "Unable to load the location with the id '$id' to clear its cache"
                );
            }
        }
        // clear content related cache as well
        relatedCache:
        $this->cache->clear( 'urlAlias' );
        $this->cache->clear( 'location' );
        return $locationIds;
    }
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::contentType ($id = null)
Clear all contentType persistence cache, or by id
Parameters
int | null $id Purges all contentType cache if null
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentType On invalid $id type
Definition at line 179 of file PersistenceCachePurger.php.
References eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\isEnabled().
    {
        if ( $this->allCleared === true || $this->isEnabled === false )
            return;
        if ( $id === null )
        {
            $this->cache->clear( 'contentType' );
        }
        else if ( is_scalar( $id ) )
        {
            $this->cache->clear( 'contentType', $id );
        }
        else
        {
            throw new InvalidArgumentType( "\$id", "int|null", $id );
        }
    }
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::contentTypeGroup ($id = null)
Clear all contentTypeGroup persistence cache, or by id
Either way, contentType cache is also cleared as it contains the relation to contentTypeGroups
Parameters
int | null $id Purges all contentTypeGroup cache if null
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentType On invalid $id type
Definition at line 206 of file PersistenceCachePurger.php.
References eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\isEnabled().
    {
        if ( $this->allCleared === true || $this->isEnabled === false )
            return;
        if ( $id === null )
        {
            $this->cache->clear( 'contentTypeGroup' );
        }
        else if ( is_scalar( $id ) )
        {
            $this->cache->clear( 'contentTypeGroup', $id );
        }
        else
        {
            throw new InvalidArgumentType( "\$id", "int|null", $id );
        }
        // clear content type in case of changes as it contains the relation to groups
        $this->cache->clear( 'contentType' );
    }
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::isAllCleared ()
Returns true if all cache has been cleared already
Returns the internal flag 'allCleared' that avoids clearing cache several times
Returns
bool
Definition at line 83 of file PersistenceCachePurger.php.
References eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\$allCleared.
    {
        return $this->allCleared;
    }
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::isEnabled ()
Checks if cache purger is enabled or not.
Returns
bool
Definition at line 115 of file PersistenceCachePurger.php.
References eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\$isEnabled.
    {
        return $this->isEnabled;
    }
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::languages ($ids)
Clear all language persistence cache, or by id
Parameters
array | int $ids
Definition at line 258 of file PersistenceCachePurger.php.
References eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\isEnabled().
    {
        if ( $this->allCleared === true || $this->isEnabled === false )
            return;
        $ids = (array)$ids;
        foreach ( $ids as $id )
            $this->cache->clear( 'language', $id );
    }
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::resetAllCleared ()
Reset 'allCleared' flag
Resets the internal flag 'allCleared' that avoids clearing cache several times
Definition at line 93 of file PersistenceCachePurger.php.
    {
        $this->allCleared = false;
    }
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::section ($id = null)
Clear all section persistence cache, or by id
Parameters
int | null $id Purges all section cache if null
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentType On invalid $id type
Definition at line 234 of file PersistenceCachePurger.php.
References eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\isEnabled().
    {
        if ( $this->allCleared === true || $this->isEnabled === false )
            return;
        if ( $id === null )
        {
            $this->cache->clear( 'section' );
        }
        else if ( is_scalar( $id ) )
        {
            $this->cache->clear( 'section', $id );
        }
        else
        {
            throw new InvalidArgumentType( "\$id", "int|null", $id );
        }
    }
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::setIsEnabled ($isEnabled)
Enables or disables cache purger. Disabling the cache purger might be useful in certain situations (like setup wizard where legacy cache is cleared but everything is not set yet to correctly clear SPI cache).
Parameters
bool $isEnabled
Definition at line 105 of file PersistenceCachePurger.php.
References eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\$isEnabled, and eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\isEnabled().
    {
        $this->isEnabled = (bool)$isEnabled;
    }
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::user ($id = null)
Clear all user persistence cache
Parameters
int | null $id Purges all users cache if null
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentType On invalid $id type
Definition at line 274 of file PersistenceCachePurger.php.
References eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger\isEnabled().
    {
        if ( $this->allCleared === true || $this->isEnabled === false )
            return;
        if ( $id === null )
        {
            $this->cache->clear( 'user' );
        }
        else if ( is_scalar( $id ) )
        {
            $this->cache->clear( 'user', $id );
        }
        else
        {
            throw new InvalidArgumentType( "\$id", "int|null", $id );
        }
    }
Member Data Documentation
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::$allCleared = false protected
Definition at line 35 of file PersistenceCachePurger.php.
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::$cache protected
Definition at line 23 of file PersistenceCachePurger.php.
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::$isEnabled = true protected
Definition at line 42 of file PersistenceCachePurger.php.
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::$locationHandler protected
Definition at line 28 of file PersistenceCachePurger.php.
eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger::$logger protected
Definition at line 47 of file PersistenceCachePurger.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Bundle/EzPublishLegacyBundle/Cache/PersistenceCachePurger.php