ezp-next: eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage Class Reference
eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage Class Reference
Public Member Functions
setConnection ($dbHandler)
storeFieldData (VersionInfo $versionInfo, Field $field)
getFieldData (Field $field)
deleteFieldData (VersionInfo $versionInfo, array $fieldId, array $context)
Public Attributes
const TABLE = "ezcontentobject_link"
Protected Member Functions
getConnection ()
Protected Attributes
$dbHandler
Detailed Description
Definition at line 20 of file LegacyStorage.php.
Member Function Documentation
eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage::deleteFieldData (VersionInfo $versionInfo, array $fieldId, array $context)
See Also
Reimplemented from eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway.
Definition at line 123 of file LegacyStorage.php.
    {
        // @todo implement when content deleting is fixed in the service
    }
eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage::getConnection () protected
Returns the active connection
Exceptions
\RuntimeException if no connection has been set, yet.
Returns
Definition at line 61 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage\getConnection().
    {
        if ( $this->dbHandler === null )
        {
            throw new \RuntimeException( "Missing database connection." );
        }
        return $this->dbHandler;
    }
eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage::getFieldData (Field $field)
See Also
Reimplemented from eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway.
Definition at line 114 of file LegacyStorage.php.
    {
        // @todo This is a bit ugly but it should do for now. A roundtrip to the DB isn't really needed here.
        $field->value->externalData = $field->value->data;
    }
eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage::setConnection ($dbHandler)
Set database handler for this gateway
Parameters
mixed $dbHandler
Returns
void
Exceptions
\RuntimeException if $dbHandler is not an instance of eZ\Publish\Core\Persistence\Legacy\EzcDbHandler
Reimplemented from eZ\Publish\Core\FieldType\StorageGateway.
Definition at line 40 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage\$dbHandler, and eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage\setConnection().
    {
        // This obviously violates the Liskov substitution Principle, but with
        // the given class design there is no sane other option. Actually the
        // dbHandler *should* be passed to the constructor, and there should
        // not be the need to post-inject it.
        if ( ! ( $dbHandler instanceof \eZ\Publish\Core\Persistence\Legacy\EzcDbHandler ) )
        {
            throw new \RuntimeException( "Invalid dbHandler passed" );
        }
        $this->dbHandler = $dbHandler;
    }
eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage::storeFieldData (VersionInfo $versionInfo, Field $field)
See Also
Reimplemented from eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway.
Reimplemented in eZ\Publish\Core\FieldType\RelationList\RelationListStorage\Gateway\LegacyStorage.
Definition at line 73 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage\$dbHandler, and eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage\getConnection().
    {
        $dbHandler = $this->getConnection();
        if ( empty( $field->value->data['destinationContentId'] ) )
        {
            return false;
        }
        // insert relation to ezcontentobject_link
        $q = $dbHandler->createInsertQuery();
        $q->insertInto(
            $dbHandler->quoteTable( self::TABLE )
        )->set(
            $dbHandler->quoteColumn( "contentclassattribute_id" ),
            $q->bindValue( $field->fieldDefinitionId, null, \PDO::PARAM_INT )
        )->set(
            $dbHandler->quoteColumn( "from_contentobject_id" ),
            $q->bindValue( $versionInfo->contentInfo->id, null, \PDO::PARAM_INT )
        )->set(
            $dbHandler->quoteColumn( "from_contentobject_version" ),
            $q->bindValue( $versionInfo->versionNo, null, \PDO::PARAM_INT )
        )->set(
            $dbHandler->quoteColumn( "op_code" ),
            $q->bindValue( 0, null, \PDO::PARAM_INT )
        )->set(
            $dbHandler->quoteColumn( "relation_type" ),
            $q->bindValue( APIRelationValue::FIELD, null, \PDO::PARAM_INT )
        )->set(
            $dbHandler->quoteColumn( "to_contentobject_id" ),
            $q->bindValue( $field->value->data['destinationContentId'], null, \PDO::PARAM_INT )
        );
        $q->prepare()->execute();
        return false;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage::$dbHandler protected
Definition at line 29 of file LegacyStorage.php.
const eZ\Publish\Core\FieldType\Relation\RelationStorage\Gateway\LegacyStorage::TABLE = "ezcontentobject_link"
Definition at line 22 of file LegacyStorage.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Relation/RelationStorage/Gateway/LegacyStorage.php