ezp-next: eZ\Publish\Core\Base\Configuration Class Reference
eZ\Publish\Core\Base\Configuration Class Reference
Public Member Functions
__construct ($moduleName, array $paths, array $globalConfiguration)
getDirs ($scope=null)
reload ()
load ($hasCache=null, $useCache=null)
get ($section, $key, $fallBackValue=null)
getSection ($section, $fallBackValue=null)
getAll ()
set ($section, $key, $value=null)
has ($section, $key=null)
hasValue ($section, $key)
Public Attributes
const CONFIG_CACHE_DIR = 'var/cache/ini/'
const TEMP_INI_UNSET_VAR = '__UNSET__'
const CONFIG_CACHE_REV = 3
Protected Member Functions
pathsHash ()
setGlobalConfig (array $globalSettings, array &$conf)
createCacheName ($configurationPathsHash)
hasCache ($cacheName)
readCache ($cacheName)
generateRawData ($configurationPathsHash, array $configurationData, array $sourceFiles=array(), array $sourcePaths=array())
parse (array $configurationPaths, array &$sourceFiles)
recursiveArrayClearing (array $iniArray, &$configurationPiece)
storeCache ($cacheName, array $rawData)
Protected Attributes
$moduleName = null
$raw = null
$globalConfiguration
$filePermission = 0644
$dirPermission = 0755
Detailed Description
Configuration instance class
A configuration class with override setting support that uses parsers to deal with files so you can support ini/yaml/xml/json given it is defined when setting up the class.
By default values are cached to a raw php files and files are not read again unless development mode is on and some file has been removed or modified since cache was created.
When generating cache files.
Definition at line 30 of file Configuration.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Base\Configuration::__construct ($moduleName, array $paths, array $globalConfiguration)
Create instance of Configuration
Parameters
string $moduleName The name of the module (and in case of ini files, same as ini filename w/o suffix)
array $paths Paths to look for settings in.
array $globalConfiguration Global settings for module
Definition at line 106 of file Configuration.php.
References eZ\Publish\Core\Base\Configuration\$globalConfiguration, and eZ\Publish\Core\Base\Configuration\$moduleName.
    {
        $this->moduleName = $moduleName;
        $this->paths = $paths;
        $this->globalConfiguration = $globalConfiguration;
        if ( isset( $globalConfiguration['base']['Configuration']['CacheFilePermission'] ) )
            $this->filePermission = $globalConfiguration['base']['Configuration']['CacheFilePermission'];
        if ( isset( $globalConfiguration['base']['Configuration']['CacheDirPermission'] ) )
            $this->dirPermission = $globalConfiguration['base']['Configuration']['CacheDirPermission'];
    }
Member Function Documentation
eZ\Publish\Core\Base\Configuration::createCacheName ($configurationPathsHash) protected
Create cache name.
Parameters
string $configurationPathsHash
Returns
string
Definition at line 240 of file Configuration.php.
    {
        return $this->moduleName . '-' . $configurationPathsHash;
    }
eZ\Publish\Core\Base\Configuration::generateRawData ($configurationPathsHash, array $configurationData, array $sourceFiles = array(), array $sourcePaths = array()) protected
Generate raw data for use in cache
Parameters
string $configurationPathsHash
array $configurationData
array $sourceFiles Optional, stored in cache to be able to check modified time in future devMode
array $sourcePaths Optional, stored in cache to be able to debug it more easily
Returns
array
Definition at line 311 of file Configuration.php.
    {
        return array(
            'hash' => $configurationPathsHash,
            'paths' => $sourcePaths,
            'files' => $sourceFiles,
            'data' => $configurationData,
            'created' => time(),
            'rev' => self::CONFIG_CACHE_REV,
        );
    }
eZ\Publish\Core\Base\Configuration::get ($section, $key, $fallBackValue = null)
Gets a configuration value, or $fallBackValue if undefined Triggers warning if key is not set and $fallBackValue is null
Parameters
string $section The configuration section to get value for
string $key The configuration key to get value for
mixed $fallBackValue value to return if setting is undefined.
Returns
mixed|null (null if key is undefined and no $fallBackValue is provided)
Definition at line 499 of file Configuration.php.
    {
        if ( isset( $this->raw['data'][$section][$key] ) )
        {
            return $this->raw['data'][$section][$key];
        }
        if ( $fallBackValue === null )
        {
            trigger_error( __METHOD__ . " could not find {$this->moduleName}.ini\[{$section}]$key setting", E_USER_WARNING );
        }
        return $fallBackValue;
    }
eZ\Publish\Core\Base\Configuration::getAll ()
Gets all section and configuration value
Returns
array
Definition at line 539 of file Configuration.php.
    {
        return $this->raw['data'];
    }
eZ\Publish\Core\Base\Configuration::getDirs ($scope = null)
Get raw instance override path list data.
Exceptions
InvalidArgumentValue If scope has wrong value
Parameters
string $scope See $globalPaths for scope values (first level keys)
Returns
array
Definition at line 127 of file Configuration.php.
    {
        if ( $scope === null )
            return $this->paths;
        if ( !isset( $this->paths[$scope] ) )
            throw new InvalidArgumentValue( 'scope', $scope, get_class( $this ) );
        return $this->paths[$scope];
    }
eZ\Publish\Core\Base\Configuration::getSection ($section, $fallBackValue = null)
Gets a configuration values for a section or $fallBackValue if undefined Triggers warning if section is not set and $fallBackValue is null
Parameters
string $section The configuration section to get value for
mixed $fallBackValue value to return if section is undefined.
Returns
array|null (null if key is undefined and no $fallBackValue is provided)
Definition at line 521 of file Configuration.php.
    {
        if ( isset( $this->raw['data'][$section] ) )
        {
            return $this->raw['data'][$section];
        }
        if ( $fallBackValue === null )
        {
            trigger_error( __METHOD__ . " could not find {$this->moduleName}.ini\[{$section}]setting", E_USER_WARNING );
        }
        return $fallBackValue;
    }
eZ\Publish\Core\Base\Configuration::has ($section, $key = null)
Checks if a configuration section and optionally key is set.
Parameters
string $section
string $key Optional, only checks if section exists if null
Returns
boolean Return true if setting exist
Definition at line 573 of file Configuration.php.
    {
        if ( $key === null )
            return isset( $this->raw['data'][$section] );
        return isset( $this->raw['data'][$section][$key] );
    }
eZ\Publish\Core\Base\Configuration::hasCache ($cacheName) protected
Check if cache file exists.
Parameters
string $cacheName As generated by createCacheName()
Returns
boolean
Definition at line 252 of file Configuration.php.
    {
        return is_file( self::CONFIG_CACHE_DIR . $cacheName . '.php' );
    }
eZ\Publish\Core\Base\Configuration::hasValue ($section, $key)
Checks if a configuration section & key is set and has a value. (ie. a check using !empty())
Parameters
string $section
string $key
Returns
boolean Return true if setting exist and has value
Definition at line 590 of file Configuration.php.
    {
        return !empty( $this->raw['data'][$section][$key] );
    }
eZ\Publish\Core\Base\Configuration::load ($hasCache = null, $useCache = null)
Loads the configuration from cache or from source (if $useCache is false or there is no cache)
Parameters
boolean | null $hasCache Lets you specify if there is a cache file, will check if null and $useCache is true
boolean $useCache Will skip using cached config files (slow), when null depends on [ini]-cache setting
Definition at line 166 of file Configuration.php.
References eZ\Publish\Core\Base\Configuration\createCacheName(), eZ\Publish\Core\Base\Configuration\generateRawData(), eZ\Publish\Core\Base\Configuration\getDirs(), eZ\Publish\Core\Base\Configuration\hasCache(), eZ\Publish\Core\Base\Configuration\parse(), eZ\Publish\Core\Base\Configuration\pathsHash(), eZ\Publish\Core\Base\Configuration\readCache(), eZ\Publish\Core\Base\Configuration\setGlobalConfig(), and eZ\Publish\Core\Base\Configuration\storeCache().
    {
        $cacheName = $this->createCacheName( $this->pathsHash() );
        if ( $useCache === null )
        {
            $useCache =
                isset( $this->globalConfiguration['base']['Configuration']['UseCache'] )
                ? $this->globalConfiguration['base']['Configuration']['UseCache']
                : false;
        }
        if ( $hasCache === null && $useCache )
        {
            $hasCache = $this->hasCache( $cacheName );
        }
        if ( $hasCache && $useCache )
        {
            $this->raw = $this->readCache( $cacheName );
            $hasCache = $this->raw !== null;
        }
        if ( !$hasCache )
        {
            $sourceFiles = array();
            $configurationData = $this->parse( $this->getDirs(), $sourceFiles );
            $this->raw = $this->generateRawData( $this->pathsHash(), $configurationData, $sourceFiles, $this->getDirs() );
            if ( $useCache )
            {
                $this->storeCache( $cacheName, $this->raw );
            }
        }
        // Merge global settings (not cached as they are runtime settings)
        if ( !isset( $this->globalConfiguration[ $this->moduleName ] ) )
            return;
        foreach ( $this->globalConfiguration[ $this->moduleName ] as $section => $globalSettings )
        {
            if ( !isset( $this->raw['data'][$section] ) )
            {
                $this->raw['data'][$section] = $globalSettings;
                continue;
            }
            $this->setGlobalConfig( $globalSettings, $this->raw['data'][$section] );
        }
    }
eZ\Publish\Core\Base\Configuration::parse (array $configurationPaths, array & $sourceFiles) protected
Parse configuration files
Uses configured parsers to do the file parsing pr file, and then merges the result from them and:
Handles array clearing
Handles section extends ("Section:Base" extends "Base")
Parameters
array $configurationPaths
array $sourceFiles ByRef value or source files that has been/is going to be parsed files you pass in will not be checked if they exists.
Exceptions
\eZ\Publish\Core\Base\Exceptions\BadConfiguration If no parser have been defined
Returns
array Data structure for parsed ini files
Definition at line 337 of file Configuration.php.
References eZ\Publish\Core\Base\Configuration\recursiveArrayClearing().
    {
        if ( empty( $this->globalConfiguration['base']['Configuration']['Parsers'] ) )
        {
            throw new BadConfiguration( 'base\[Configuration]\Parsers', 'Could not parse configuration files' );
        }
        $parsers = $this->globalConfiguration['base']['Configuration']['Parsers'];
        foreach ( $configurationPaths as $scopeArray )
        {
            foreach ( $scopeArray as $settingsDir )
            {
                foreach ( $parsers as $suffix => $parser )
                {
                    $fileName = $settingsDir . $this->moduleName . $suffix;
                    if ( !isset( $sourceFiles[$fileName] ) && is_file( $fileName ) )
                    {
                        $sourceFiles[$fileName] = $suffix;
                    }
                }
            }
        }
        // No source files, no configuration
        if ( empty( $sourceFiles ) )
        {
            return array();
        }
        $configurationData = array();
        $configurationFileData = array();
        foreach ( $sourceFiles as $fileName => $suffix )
        {
            if ( !$parsers[$suffix] instanceof Parser )
                $parsers[$suffix] = new $parsers[$suffix]( $this->globalConfiguration['base']['Configuration'] );
            $configurationFileData[$fileName] = $parsers[$suffix]->parse( $fileName, file_get_contents( $fileName ) );
        }
        // Post processing to unset array self::TEMP_INI_UNSET_VAR values as set by parser to indicate array clearing
        // and to merge configuration data from all configuration files
        $extendedConfigurationFileData = array();
        foreach ( $configurationFileData as $fileName => $data )
        {
            foreach ( $data as $section => $sectionArray )
            {
                // Leave settings that extend others for second pass, key by depth
                if ( ( $count = substr_count( $section, ':' ) ) !== 0 )
                {
                    $extendedConfigurationFileData[$count][$fileName][$section] = $sectionArray;
                    continue;
                }
                if ( !isset( $configurationData[$section] ) )
                    $configurationData[$section] = array();
                $this->recursiveArrayClearing( $sectionArray, $configurationData[$section] );
            }
        }
        // Second pass post processing dealing with settings that extends others
        ksort( $extendedConfigurationFileData, SORT_NUMERIC );
        foreach ( $extendedConfigurationFileData as $configurationFileData )
        {
            foreach ( $configurationFileData as $data )
            {
                foreach ( $data as $section => $sectionArray )
                {
                    if ( !isset( $configurationData[$section] ) )
                    {
                        $parent = substr( $section, stripos( $section, ':' ) + 1 );
                        if ( isset( $configurationData[$parent] ) )
                            $configurationData[$section] = $configurationData[$parent];
                        else
                            $configurationData[$section] = array();
                    }
                    $this->recursiveArrayClearing( $sectionArray, $configurationData[$section] );
                }
            }
        }
        return $configurationData;
    }
eZ\Publish\Core\Base\Configuration::pathsHash () protected
Get cache hash based on override dirs
Returns
string md5 hash
Definition at line 142 of file Configuration.php.
    {
        if ( $this->pathsHash === '' )
        {
            $this->pathsHash = md5( serialize( $this->paths ) );
        }
        return $this->pathsHash;
    }
eZ\Publish\Core\Base\Configuration::readCache ($cacheName) protected
Loads cache file, use hasCache() to make sure it exists first!
Parameters
string $cacheName As generated by createCacheName()
Returns
array|null
Definition at line 264 of file Configuration.php.
    {
        $cacheData = include self::CONFIG_CACHE_DIR . $cacheName . '.php';
        // Check that cache has
        if ( !isset( $cacheData['data'] ) || $cacheData['rev'] !== self::CONFIG_CACHE_REV )
        {
            return null;
        }
        // Check modified time if dev mode
        if ( isset( $this->globalConfiguration['base']['Configuration']['DevelopmentMode'] )
          && $this->globalConfiguration['base']['Configuration']['DevelopmentMode'] )
        {
            $currentTime = time();
            foreach ( $cacheData['files'] as $inputFile )
            {
                $fileTime = is_file( $inputFile ) ? filemtime( $inputFile ) : false;
                // Refresh cache & input files if file is gone
                if ( $fileTime === false )
                {
                    return null;
                }
                if ( $fileTime > $currentTime )
                {
                    trigger_error( __METHOD__ . ': Input file "' . $inputFile . '" has a timestamp higher then current time, ignoring to avoid infinite recursion!', E_USER_WARNING );
                }
                // Refresh cache if file has been changed
                else if ( $fileTime > $cacheData['created'] )
                {
                    return null;
                }
            }
        }
        return $cacheData;
    }
eZ\Publish\Core\Base\Configuration::recursiveArrayClearing (array $iniArray, & $configurationPiece) protected
Recursively clear array values
Parameters
array $iniArray
array | null $configurationPiece
Definition at line 427 of file Configuration.php.
    {
        foreach ( $iniArray as $setting => $settingValue )
        {
            if ( isset( $settingValue[0] ) && $settingValue[0] === self::TEMP_INI_UNSET_VAR )
            {
                array_shift( $settingValue );
                $configurationPiece[$setting] = $settingValue;
            }
            else if ( is_array( $settingValue ) )
            {
                $this->recursiveArrayClearing( $settingValue, $configurationPiece[$setting] );
            }
            else
            {
                $configurationPiece[$setting] = $settingValue;
            }
        }
    }
eZ\Publish\Core\Base\Configuration::reload ()
Reload cache data conditionally if path hash has changed on current instance
Definition at line 154 of file Configuration.php.
References eZ\Publish\Core\Base\Configuration\load(), and eZ\Publish\Core\Base\Configuration\pathsHash().
    {
        if ( !isset( $this->raw['hash'] ) || $this->raw['hash'] !== $this->pathsHash() )
            $this->load();
    }
eZ\Publish\Core\Base\Configuration::set ($section, $key, $value = null)
Gets a configuration value, or null if not set.
Parameters
string $section The configuration section to get value for
string $key The configuration key to get value for
mixed $value value to return if setting is not defined.
Returns
boolean Return true if section existed and was overwritten
Definition at line 553 of file Configuration.php.
    {
        if ( isset( $this->raw['data'][$section] ) )
        {
            $this->raw['data'][$section][$key] = $value;
            return true;
        }
        $this->raw['data'][$section] = array( $key => $value );
        return false;
    }
eZ\Publish\Core\Base\Configuration::setGlobalConfig (array $globalSettings, array & $conf) protected
Recursively set global configuration
Parameters
array $globalSettings
array $conf
Definition at line 222 of file Configuration.php.
    {
        foreach ( $globalSettings as $key => $globalSetting )
        {
            if ( !empty( $conf[$key] ) && !is_numeric( $key ) && is_array( $conf[$key] ) && is_array( $globalSetting ) )
                $this->setGlobalConfig( $globalSetting, $conf[$key] );
            else
                $conf[$key] = $globalSetting;
        }
    }
eZ\Publish\Core\Base\Configuration::storeCache ($cacheName, array $rawData) protected
Store cache file, overwrites any existing file
Parameters
string $cacheName As generated by createCacheName()
array $rawData As generated by generateRawData()
Definition at line 454 of file Configuration.php.
References eZ\Publish\Core\REST\$generator.
    {
        try
        {
            // Create ini dir if it does not exist
            if ( !is_dir( self::CONFIG_CACHE_DIR ) )
            {
                mkdir( self::CONFIG_CACHE_DIR, $this->dirPermission, true );
            }
            // Create cache hash
            $cachedFile = self::CONFIG_CACHE_DIR . $cacheName . '.php';
            // Store cache
            $generator = new ezcPhpGenerator( $cachedFile );
            $generator->appendComment( "This file is auto generated based on configuration files for '{$this->moduleName}' module. Do not edit!" );
            $generator->appendComment( "Time created (server time): " . date( DATE_RFC822, $rawData['created'] ) );
            $generator->appendEmptyLines();
            $generator->appendValueAssignment( 'cacheData', $rawData );
            $generator->appendCustomCode( 'return $cacheData;' );
            $generator->finish();
            // make sure file has correct file permissions
            chmod( $cachedFile, $this->filePermission );
        }
        catch ( Exception $e )
        {
            // constructor     : ezcBaseFileNotFoundException or ezcBaseFilePermissionException
            // all other calls : ezcPhpGeneratorException
            trigger_error( __METHOD__ . ': '. $e->getMessage(), E_USER_WARNING );
        }
    }
Member Data Documentation
eZ\Publish\Core\Base\Configuration::$dirPermission = 0755 protected
Definition at line 97 of file Configuration.php.
eZ\Publish\Core\Base\Configuration::$filePermission = 0644 protected
Definition at line 92 of file Configuration.php.
eZ\Publish\Core\Base\Configuration::$globalConfiguration protected
Definition at line 87 of file Configuration.php.
eZ\Publish\Core\Base\Configuration::$moduleName = null protected
Definition at line 73 of file Configuration.php.
eZ\Publish\Core\Base\Configuration::$raw = null protected
Definition at line 80 of file Configuration.php.
const eZ\Publish\Core\Base\Configuration::CONFIG_CACHE_DIR = 'var/cache/ini/'
Definition at line 37 of file Configuration.php.
const eZ\Publish\Core\Base\Configuration::CONFIG_CACHE_REV = 3
Definition at line 51 of file Configuration.php.
const eZ\Publish\Core\Base\Configuration::TEMP_INI_UNSET_VAR = '__UNSET__'
Definition at line 44 of file Configuration.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Base/Configuration.php