ezp-next: eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage Class Reference
eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage Class Reference
Public Member Functions
setConnection ($dbHandler)
storeFieldData (VersionInfo $versionInfo, Field $field)
getFieldData (Field $field)
Public Attributes
const URL_TABLE = "ezurl"
Protected Member Functions
getConnection ()
Protected Attributes
$dbHandler
Detailed Description
Definition at line 19 of file LegacyStorage.php.
Member Function Documentation
eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage::getConnection () protected
Returns the active connection
Exceptions
\RuntimeException if no connection has been set, yet.
Returns
Definition at line 60 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage\getConnection().
    {
        if ( $this->dbHandler === null )
        {
            throw new \RuntimeException( "Missing database connection." );
        }
        return $this->dbHandler;
    }
eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage::getFieldData (Field $field)
See Also
Reimplemented from eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway.
Definition at line 90 of file LegacyStorage.php.
    {
        $url = $this->fetchById( $field->value->data["urlId"] );
        $field->value->externalData = $url["url"];
    }
eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage::setConnection ($dbHandler)
Set database handler for this gateway
Parameters
mixed $dbHandler
Returns
void
Exceptions
\RuntimeException if $dbHandler is not an instance of eZ\Publish\Core\Persistence\Legacy\EzcDbHandler
Reimplemented from eZ\Publish\Core\FieldType\StorageGateway.
Definition at line 39 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage\$dbHandler, and eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage\setConnection().
    {
        // This obviously violates the Liskov substitution Principle, but with
        // the given class design there is no sane other option. Actually the
        // dbHandler *should* be passed to the constructor, and there should
        // not be the need to post-inject it.
        if ( ! ( $dbHandler instanceof \eZ\Publish\Core\Persistence\Legacy\EzcDbHandler ) )
        {
            throw new \RuntimeException( "Invalid dbHandler passed" );
        }
        $this->dbHandler = $dbHandler;
    }
eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage::storeFieldData (VersionInfo $versionInfo, Field $field)
See Also
Reimplemented from eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway.
Definition at line 72 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage\$dbHandler, and eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage\getConnection().
    {
        $dbHandler = $this->getConnection();
        if ( ( $row = $this->fetchByLink( $field->value->externalData ) ) !== false )
            $urlId = $row["id"];
        else
            $urlId = $this->insert( $versionInfo, $field );
        $field->value->data["urlId"] = $urlId;
        // Signals that the Value has been modified and that an update is to be performed
        return true;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage::$dbHandler protected
Definition at line 28 of file LegacyStorage.php.
const eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage::URL_TABLE = "ezurl"
Definition at line 21 of file LegacyStorage.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/LegacyStorage.php