ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\UrlWildcard\Mapper Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\UrlWildcard\Mapper Class Reference
Public Member Functions
createUrlWildcard ($sourceUrl, $destinationUrl, $forward)
extractUrlWildcardFromRow (array $row)
extractUrlWildcardsFromRows (array $rows)
Protected Member Functions
cleanUrl ($url)
Detailed Description
UrlWildcard Mapper
Definition at line 17 of file Mapper.php.
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\UrlWildcard\Mapper::cleanUrl ($url) protected
Parameters
string $url
Returns
string
Definition at line 63 of file Mapper.php.
    {
        return "/" . trim( $url, "/ " );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlWildcard\Mapper::createUrlWildcard ($sourceUrl, $destinationUrl, $forward)
Creates a UrlWildcard object from given parameters
Parameters
string $sourceUrl
string $destinationUrl
boolean $forward
Returns
Definition at line 28 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlWildcard\Mapper\cleanUrl().
    {
        $urlWildcard = new UrlWildcard();
        $urlWildcard->destinationUrl = $this->cleanUrl( $destinationUrl );
        $urlWildcard->sourceUrl = $this->cleanUrl( $sourceUrl );
        $urlWildcard->forward = $forward;
        return $urlWildcard;
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlWildcard\Mapper::extractUrlWildcardFromRow (array $row)
Extracts UrlWildcard object from given database $row
Parameters
array $row
Returns
Definition at line 46 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlWildcard\Mapper\cleanUrl().
    {
        $urlWildcard = new UrlWildcard();
        $urlWildcard->id = (int)$row["id"];
        $urlWildcard->destinationUrl = $this->cleanUrl( $row["destination_url"] );
        $urlWildcard->sourceUrl = $this->cleanUrl( $row["source_url"] );
        $urlWildcard->forward = (int)$row["type"] === 1 ? true : false;
        return $urlWildcard;
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlWildcard\Mapper::extractUrlWildcardsFromRows (array $rows)
Extracts UrlWildcard objects from database $rows
Parameters
array $rows
Returns
[]
Definition at line 75 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlWildcard\Mapper\extractUrlWildcardFromRow().
    {
        $urlWildcards = array();
        foreach ( $rows as $row )
        {
            $urlWildcards[] = $this->extractUrlWildcardFromRow( $row );
        }
        return $urlWildcards;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Mapper.php