ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase Class Reference
Public Member Functions
__construct (EzcDbHandler $dbHandler)
insertLanguage (Language $language)
updateLanguage (Language $language)
loadLanguageData ($id)
loadLanguageDataByLanguageCode ($languageCode)
loadAllLanguagesData ()
deleteLanguage ($id)
canDeleteLanguage ($id)
Protected Member Functions
setCommonLanguageColumns (ezcQuery $query, Language $language)
createFindQuery ()
Protected Attributes
$dbHandler
Detailed Description
ezcDatabase based Language Gateway
Definition at line 20 of file EzcDatabase.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase::__construct (EzcDbHandler $dbHandler)
Creates a new EzcDatabase Section Gateway
Parameters
\eZ\Publish\Core\Persistence\Legacy\EzcDbHandler $dbHandler
Definition at line 34 of file EzcDatabase.php.
    {
        $this->dbHandler = $dbHandler;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase::canDeleteLanguage ($id)
Check whether a language may be deleted
Parameters
int $id
Returns
boolean
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway.
Definition at line 233 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( "*" ), "count" )
        )->from(
            $this->dbHandler->quoteTable( "ezcobj_state" )
        )->where(
            $query->expr->lOr(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( "default_language_id" ),
                    $query->bindValue( $id, null, \PDO::PARAM_INT )
                ),
                $query->expr->bitAnd(
                    $this->dbHandler->quoteColumn( "language_mask" ),
                    $query->bindValue( $id, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        if ( $statement->fetchColumn() > 0 )
            return false;
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( "*" ), "count" )
        )->from(
            $this->dbHandler->quoteTable( "ezcobj_state_group" )
        )->where(
            $query->expr->lOr(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( "default_language_id" ),
                    $query->bindValue( $id, null, \PDO::PARAM_INT )
                ),
                $query->expr->bitAnd(
                    $this->dbHandler->quoteColumn( "language_mask" ),
                    $query->bindValue( $id, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        if ( $statement->fetchColumn() > 0 )
            return false;
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( "*" ), "count" )
        )->from(
            $this->dbHandler->quoteTable( "ezcobj_state_group_language" )
        )->where(
            $query->expr->bitAnd(
                $this->dbHandler->quoteColumn( "language_id" ),
                $query->bindValue( $id, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        if ( $statement->fetchColumn() > 0 )
            return false;
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( "*" ), "count" )
        )->from(
            $this->dbHandler->quoteTable( "ezcobj_state_language" )
        )->where(
            $query->expr->bitAnd(
                $this->dbHandler->quoteColumn( "language_id" ),
                $query->bindValue( $id, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        if ( $statement->fetchColumn() > 0 )
            return false;
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( "*" ), "count" )
        )->from(
            $this->dbHandler->quoteTable( "ezcontentclass" )
        )->where(
            $query->expr->lOr(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( "initial_language_id" ),
                    $query->bindValue( $id, null, \PDO::PARAM_INT )
                ),
                $query->expr->bitAnd(
                    $this->dbHandler->quoteColumn( "language_mask" ),
                    $query->bindValue( $id, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        if ( $statement->fetchColumn() > 0 )
            return false;
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( "*" ), "count" )
        )->from(
            $this->dbHandler->quoteTable( "ezcontentclass_name" )
        )->where(
            $query->expr->bitAnd(
                $this->dbHandler->quoteColumn( "language_id" ),
                $query->bindValue( $id, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        if ( $statement->fetchColumn() > 0 )
            return false;
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( "*" ), "count" )
        )->from(
            $this->dbHandler->quoteTable( "ezcontentobject" )
        )->where(
            $query->expr->lOr(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( "initial_language_id" ),
                    $query->bindValue( $id, null, \PDO::PARAM_INT )
                ),
                $query->expr->bitAnd(
                    $this->dbHandler->quoteColumn( "language_mask" ),
                    $query->bindValue( $id, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        if ( $statement->fetchColumn() > 0 )
            return false;
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( "*" ), "count" )
        )->from(
            $this->dbHandler->quoteTable( "ezcontentobject_attribute" )
        )->where(
            $query->expr->bitAnd(
                $this->dbHandler->quoteColumn( "language_id" ),
                $query->bindValue( $id, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        if ( $statement->fetchColumn() > 0 )
            return false;
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( "*" ), "count" )
        )->from(
            $this->dbHandler->quoteTable( "ezcontentobject_name" )
        )->where(
            $query->expr->bitAnd(
                $this->dbHandler->quoteColumn( "language_id" ),
                $query->bindValue( $id, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        if ( $statement->fetchColumn() > 0 )
            return false;
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( "*" ), "count" )
        )->from(
            $this->dbHandler->quoteTable( "ezcontentobject_version" )
        )->where(
            $query->expr->lOr(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( "initial_language_id" ),
                    $query->bindValue( $id, null, \PDO::PARAM_INT )
                ),
                $query->expr->bitAnd(
                    $this->dbHandler->quoteColumn( "language_mask" ),
                    $query->bindValue( $id, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        if ( $statement->fetchColumn() > 0 )
            return false;
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( "*" ), "count" )
        )->from(
            $this->dbHandler->quoteTable( "ezurlalias_ml" )
        )->where(
            $query->expr->bitAnd(
                $this->dbHandler->quoteColumn( "lang_mask" ),
                $query->bindValue( $id, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchColumn() == 0;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase::createFindQuery () protected
Creates a Language find query
Returns
Definition at line 175 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase\createFindQuery().
    {
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $this->dbHandler->quoteColumn( 'id' ),
            $this->dbHandler->quoteColumn( 'locale' ),
            $this->dbHandler->quoteColumn( 'name' ),
            $this->dbHandler->quoteColumn( 'disabled' )
        )->from(
            $this->dbHandler->quoteTable( 'ezcontent_language' )
        );
        return $query;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase::deleteLanguage ($id)
Deletes the language with $id
Parameters
int $id
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway.
Definition at line 211 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcontent_language' )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $query->bindValue( $id, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase::insertLanguage (Language $language)
Inserts the given $language
Parameters
Language $language
Returns
int ID of the new language
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway.
Definition at line 46 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase\setCommonLanguageColumns().
    {
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->expr->max( $this->dbHandler->quoteColumn( 'id' ) )
        )->from( $this->dbHandler->quoteTable( 'ezcontent_language' ) );
        $statement = $query->prepare();
        $statement->execute();
        $lastId = (int)$statement->fetchColumn();
        // Next power of 2 for bit masks
        $nextId = ( $lastId !== 0 ? $lastId << 1 : 2 );
        $query = $this->dbHandler->createInsertQuery();
        $query->insertInto(
            $this->dbHandler->quoteTable( 'ezcontent_language' )
        )->set(
            $this->dbHandler->quoteColumn( 'id' ),
            $query->bindValue( $nextId, null, \PDO::PARAM_INT )
        );
        $this->setCommonLanguageColumns( $query, $language );
        $query->prepare()->execute();
        return $nextId;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase::loadAllLanguagesData ()
Loads the data for all languages
Returns
string[][]
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway.
Definition at line 194 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase\createFindQuery().
    {
        $query = $this->createFindQuery();
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase::loadLanguageData ($id)
Loads data for the Language with $id
Parameters
int $id
Returns
string[][]
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway.
Definition at line 131 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase\createFindQuery().
    {
        $query = $this->createFindQuery();
        $query->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $query->bindValue( $id, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase::loadLanguageDataByLanguageCode ($languageCode)
Loads data for the Language with Language Code (eg: eng-GB)
Parameters
string $languageCode
Returns
string[][]
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway.
Definition at line 154 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase\createFindQuery().
    {
        $query = $this->createFindQuery();
        $query->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'locale' ),
                $query->bindValue( $languageCode, null, \PDO::PARAM_STR )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase::setCommonLanguageColumns (ezcQuery $query, Language $language) protected
Sets columns in $query from $language
Parameters
\ezcQuery $query
\eZ\Publish\SPI\Persistence\Content\Language $language
Returns
void
Definition at line 82 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase\setCommonLanguageColumns().
    {
        $query->set(
            $this->dbHandler->quoteColumn( 'locale' ),
            $query->bindValue( $language->languageCode )
        )->set(
            $this->dbHandler->quoteColumn( 'name' ),
            $query->bindValue( $language->name )
        )->set(
            $this->dbHandler->quoteColumn( 'disabled' ),
            $query->bindValue(
                ( (int)( ! $language->isEnabled ) ),
                null,
                \PDO::PARAM_INT
            )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase::updateLanguage (Language $language)
Updates the data of the given $language
Parameters
Language $language
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway.
Definition at line 107 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase\setCommonLanguageColumns().
    {
        $query = $this->dbHandler->createUpdateQuery();
        $query->update( $this->dbHandler->quoteTable( 'ezcontent_language' ) );
        $this->setCommonLanguageColumns( $query, $language );
        $query->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $query->bindValue( $language->id, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\EzcDatabase::$dbHandler protected
Database handler
Parameters
\eZ\Publish\Core\Persistence\Legacy\EzcDbHandler $dbHandler
Definition at line 27 of file EzcDatabase.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway/EzcDatabase.php