ezp-next: eZ\Publish\Core\Persistence\Cache\ContentHandler Class Reference
eZ\Publish\Core\Persistence\Cache\ContentHandler Class Reference
Public Member Functions
create (CreateStruct $struct)
createDraftFromVersion ($contentId, $srcVersion, $userId)
copy ($contentId, $versionNo=null)
load ($contentId, $version, $translations=null)
loadContentInfo ($contentId)
loadVersionInfo ($contentId, $versionNo)
loadDraftsForUser ($userId)
setStatus ($contentId, $status, $version)
updateMetadata ($contentId, MetadataUpdateStruct $struct)
updateContent ($contentId, $versionNo, UpdateStruct $struct)
deleteContent ($contentId)
deleteVersion ($contentId, $versionNo)
listVersions ($contentId)
addRelation (RelationCreateStruct $relation)
removeRelation ($relationId, $type)
loadRelations ($sourceContentId, $sourceContentVersionNo=null, $type=null)
loadReverseRelations ($destinationContentId, $type=null)
publish ($contentId, $versionNo, MetadataUpdateStruct $struct)
Public Member Functions inherited from eZ\Publish\Core\Persistence\Cache\AbstractHandler
__construct (CacheService $cache, PersistenceFactory $persistenceFactory, PersistenceLogger $logger)
Public Member Functions inherited from eZ\Publish\SPI\Persistence\Content\Handler
updateContent ($contentId, $versionNo, UpdateStruct $content)
Public Attributes
const FIELD_VALUE_DOM_DOCUMENT_KEY = 'ยง:DomDocument:ยง'
Protected Member Functions
cloneAndSerializeXMLFields (Content $content)
unSerializeXMLFields (Content $content)
Additional Inherited Members
Protected Attributes inherited from eZ\Publish\Core\Persistence\Cache\AbstractHandler
$cache
$persistenceFactory
$logger
Detailed Description
See Also
eZ
Definition at line 24 of file ContentHandler.php.
Member Function Documentation
eZ\Publish\Core\Persistence\Cache\ContentHandler::addRelation (RelationCreateStruct $relation)
See Also
::addRelation
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 198 of file ContentHandler.php.
    {
        $this->logger->logCall( __METHOD__, array( 'struct' => $relation ) );
        return $this->persistenceFactory->getContentHandler()->addRelation( $relation );
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::cloneAndSerializeXMLFields (Content $content) protected
Custom serializer for Content
Needed for DomDocuments on field values as they can not be serialized directly.
Todo:
Change SPI to document that fieldValue->data and external data *must* be serializable, then remove this.
Parameters
Content $content
Returns
Content A serializable version of Content
Definition at line 268 of file ContentHandler.php.
    {
        $contentClone = clone $content;
        foreach ( $contentClone->fields as $key => $field )
        {
            $contentClone->fields[$key] = $fieldClone = clone $field;
            $fieldClone->value = clone $fieldClone->value;
            // Add 'unique' string in front of xml string version of dom document, used by unSerializeXMLFields()
            if ( $fieldClone->value->data instanceof DOMDocument )
            {
                $fieldClone->value->data =
                    self::FIELD_VALUE_DOM_DOCUMENT_KEY .
                    $fieldClone->value->data->saveXML();
            }
            if ( $fieldClone->value->externalData instanceof DOMDocument )
            {
                $fieldClone->value->externalData =
                    self::FIELD_VALUE_DOM_DOCUMENT_KEY .
                    $fieldClone->value->externalData->saveXML();
            }
        }
        return $contentClone;
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::copy ($contentId, $versionNo = null)
See Also
::copy
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 50 of file ContentHandler.php.
    {
        $this->logger->logCall( __METHOD__, array( 'content' => $contentId, 'version' => $versionNo ) );
        return $this->persistenceFactory->getContentHandler()->copy( $contentId, $versionNo );
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::create (CreateStruct $content)
See Also
::create
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 31 of file ContentHandler.php.
    {
        // Cached on demand when published or loaded
        $this->logger->logCall( __METHOD__, array( 'struct' => $struct ) );
        return $this->persistenceFactory->getContentHandler()->create( $struct );
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::createDraftFromVersion ($contentId, $srcVersion, $userId)
See Also
::createDraftFromVersion
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 41 of file ContentHandler.php.
    {
        $this->logger->logCall( __METHOD__, array( 'content' => $contentId, 'version' => $srcVersion, 'user' => $userId ) );
        return $this->persistenceFactory->getContentHandler()->createDraftFromVersion( $contentId, $srcVersion, $userId );
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::deleteContent ($contentId)
See Also
::deleteContent
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 161 of file ContentHandler.php.
    {
        $this->logger->logCall( __METHOD__, array( 'content' => $contentId ) );
        $return = $this->persistenceFactory->getContentHandler()->deleteContent( $contentId );
        $this->cache->clear( 'content', $contentId );
        $this->cache->clear( 'content', 'info', $contentId );
        return $return;
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::deleteVersion ($contentId, $versionNo)
See Also
::deleteVersion
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 175 of file ContentHandler.php.
    {
        $this->logger->logCall( __METHOD__, array( 'content' => $contentId, 'version' => $versionNo ) );
        $return = $this->persistenceFactory->getContentHandler()->deleteVersion( $contentId, $versionNo );
        $this->cache->clear( 'content', $contentId, $versionNo );
        $this->cache->clear( 'content', 'info', $contentId );
        return $return;
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::listVersions ($contentId)
See Also
::listVersions
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 189 of file ContentHandler.php.
    {
        $this->logger->logCall( __METHOD__, array( 'content' => $contentId ) );
        return $this->persistenceFactory->getContentHandler()->listVersions( $contentId );
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::load ($contentId, $version, $translations = null)
See Also
::load
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 59 of file ContentHandler.php.
References eZ\Publish\Core\Persistence\Cache\AbstractHandler\$cache, eZ\Publish\Core\Persistence\Cache\ContentHandler\cloneAndSerializeXMLFields(), and eZ\Publish\Core\Persistence\Cache\ContentHandler\unSerializeXMLFields().
    {
        if ( null !== $translations )
        {
            $this->logger->logCall( __METHOD__, array( 'content' => $contentId, 'version' => $version, 'translations' => $translations ) );
            return $this->persistenceFactory->getContentHandler()->load( $contentId, $version, $translations );
        }
        $cache = $this->cache->getItem( 'content', $contentId, $version );
        $content = $cache->get();
        if ( $cache->isMiss() )
        {
            $this->logger->logCall( __METHOD__, array( 'content' => $contentId, 'version' => $version ) );
            $content = $this->persistenceFactory->getContentHandler()->load( $contentId, $version );
            $cache->set( $this->cloneAndSerializeXMLFields( $content ) );
        }
        else
        {
            $this->unSerializeXMLFields( $content );
        }
        return $content;
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::loadContentInfo ($contentId)
See Also
::loadContentInfo
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 86 of file ContentHandler.php.
References eZ\Publish\Core\Persistence\Cache\AbstractHandler\$cache.
    {
        $cache = $this->cache->getItem( 'content', 'info', $contentId );
        $contentInfo = $cache->get();
        if ( $cache->isMiss() )
        {
            $this->logger->logCall( __METHOD__, array( 'content' => $contentId ) );
            $cache->set( $contentInfo = $this->persistenceFactory->getContentHandler()->loadContentInfo( $contentId ) );
        }
        return $contentInfo;
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::loadDraftsForUser ($userId)
See Also
::loadDraftsForUser
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 110 of file ContentHandler.php.
    {
        $this->logger->logCall( __METHOD__, array( 'user' => $userId ) );
        return $this->persistenceFactory->getContentHandler()->loadDraftsForUser( $userId );
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::loadRelations ($sourceContentId, $sourceContentVersionNo = null, $type = null)
See Also
::loadRelations
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 216 of file ContentHandler.php.
    {
        $this->logger->logCall(
            __METHOD__,
            array(
                'content' => $sourceContentId,
                'version' => $sourceContentVersionNo,
                'type' => $type
            )
        );
        return $this->persistenceFactory->getContentHandler()->loadRelations( $sourceContentId, $sourceContentVersionNo, $type );
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::loadReverseRelations ($destinationContentId, $type = null)
See Also
::loadReverseRelations
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 232 of file ContentHandler.php.
    {
        $this->logger->logCall( __METHOD__, array( 'content' => $destinationContentId, 'type' => $type ) );
        return $this->persistenceFactory->getContentHandler()->loadReverseRelations( $destinationContentId, $type );
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::loadVersionInfo ($contentId, $versionNo)
See Also
::loadVersionInfo
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 101 of file ContentHandler.php.
    {
        $this->logger->logCall( __METHOD__, array( 'content' => $contentId, 'version' => $versionNo ) );
        return $this->persistenceFactory->getContentHandler()->loadVersionInfo( $contentId, $versionNo );
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::publish ($contentId, $versionNo, MetadataUpdateStruct $struct)
See Also
::publish
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 241 of file ContentHandler.php.
References eZ\Publish\Core\Persistence\Cache\ContentHandler\cloneAndSerializeXMLFields().
    {
        $this->logger->logCall( __METHOD__, array( 'content' => $contentId, 'version' => $versionNo, 'struct' => $struct ) );
        $content = $this->persistenceFactory->getContentHandler()->publish( $contentId, $versionNo, $struct );
        $this->cache->clear( 'content', $contentId );
        // warm up cache
        $contentInfo = $content->versionInfo->contentInfo;
        $this->cache
            ->getItem( 'content', $contentInfo->id, $content->versionInfo->versionNo )
            ->set( $this->cloneAndSerializeXMLFields( $content ) );
        $this->cache->getItem( 'content', 'info', $contentInfo->id )->set( $contentInfo );
        return $content;
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::removeRelation ($relationId, $type)
See Also
::removeRelation
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 207 of file ContentHandler.php.
    {
        $this->logger->logCall( __METHOD__, array( 'relation' => $relationId, 'type' => $type ) );
        $this->persistenceFactory->getContentHandler()->removeRelation( $relationId, $type );
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::setStatus ($contentId, $status, $version)
See Also
::setStatus
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 119 of file ContentHandler.php.
References eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_PUBLISHED.
    {
        $this->logger->logCall( __METHOD__, array( 'content' => $contentId, 'status' => $status, 'version' => $version ) );
        $return = $this->persistenceFactory->getContentHandler()->setStatus( $contentId, $status, $version );
        $this->cache->clear( 'content', $contentId, $version );
        if ( $status === VersionInfo::STATUS_PUBLISHED )
            $this->cache->clear( 'content', 'info', $contentId );
        return $return;
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::unSerializeXMLFields (Content $content) protected
Custom unSerializer for Content
Needed for DomDocuments on field values as they can not be serialized directly.
See Also
cloneAndSerializeXMLFields
Parameters
Content $content
Returns
Content
Definition at line 303 of file ContentHandler.php.
    {
        foreach ( $content->fields as $field )
        {
            // Look for self::FIELD_VALUE_DOM_DOCUMENT_KEY, it indicates a xml string that needs to be DomDocument
            if (
                !empty( $field->value->data ) &&
                is_string( $field->value->data ) &&
                strpos( $field->value->data, self::FIELD_VALUE_DOM_DOCUMENT_KEY ) === 0
            )
            {
                $dom = new DOMDocument( '1.0', 'UTF-8' );
                $dom->loadXML( substr( $field->value->data, strlen( self::FIELD_VALUE_DOM_DOCUMENT_KEY ) ) );
                $field->value->data = $dom;
            }
            if (
                !empty( $field->value->externalData ) &&
                is_string( $field->value->externalData ) &&
                strpos( $field->value->externalData, self::FIELD_VALUE_DOM_DOCUMENT_KEY ) === 0
            )
            {
                $dom = new DOMDocument( '1.0', 'UTF-8' );
                $dom->loadXML( substr( $field->value->externalData, strlen( self::FIELD_VALUE_DOM_DOCUMENT_KEY ) ) );
                $field->value->externalData = $dom;
            }
        }
        return $content;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::updateContent ($contentId, $versionNo, UpdateStruct $updateStruct)
See Also
::updateContent
Definition at line 148 of file ContentHandler.php.
References eZ\Publish\Core\Persistence\Cache\ContentHandler\cloneAndSerializeXMLFields().
    {
        $this->logger->logCall( __METHOD__, array( 'content' => $contentId, 'version' => $versionNo, 'struct' => $struct ) );
        $content = $this->persistenceFactory->getContentHandler()->updateContent( $contentId, $versionNo, $struct );
        $this->cache
            ->getItem( 'content', $contentId, $versionNo )
            ->set( $this->cloneAndSerializeXMLFields( $content ) );
        return $content;
    }
eZ\Publish\Core\Persistence\Cache\ContentHandler::updateMetadata ($contentId, MetadataUpdateStruct $struct)
See Also
::updateMetadata
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 134 of file ContentHandler.php.
    {
        $this->logger->logCall( __METHOD__, array( 'content' => $contentId, 'struct' => $struct ) );
        $this->cache
            ->getItem( 'content', 'info', $contentId )
            ->set( $contentInfo = $this->persistenceFactory->getContentHandler()->updateMetadata( $contentId, $struct ) );
        return $contentInfo;
    }
Member Data Documentation
const eZ\Publish\Core\Persistence\Cache\ContentHandler::FIELD_VALUE_DOM_DOCUMENT_KEY = 'ยง:DomDocument:ยง'
Definition at line 26 of file ContentHandler.php.
The documentation for this class was generated from the following files:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Cache/ContentHandler.php
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/InMemory/ContentHandler.php