ezp-next: eZ\Publish\Core\FieldType\BinaryBase\Type Class Reference
eZ\Publish\Core\FieldType\BinaryBase\Type Class Reference
Public Member Functions
__construct (FileService $fileService, MimeTypeDetector $mimeTypeDetector)
getName ($value)
fromHash ($hash)
toHash ($value)
toPersistenceValue ($value)
fromPersistenceValue (FieldValue $fieldValue)
validate (FieldDefinition $fieldDefinition, $fieldValue)
validateValidatorConfiguration ($validatorConfiguration)
isSearchable ()
Public Member Functions inherited from eZ\Publish\Core\FieldType\FieldType
getSettingsSchema ()
getValidatorConfigurationSchema ()
validateFieldSettings ($fieldSettings)
isEmptyValue ($value)
acceptValue ($inputValue)
fieldSettingsToHash ($fieldSettings)
fieldSettingsFromHash ($fieldSettingsHash)
validatorConfigurationToHash ($validatorConfiguration)
validatorConfigurationFromHash ($validatorConfigurationHash)
Public Member Functions inherited from eZ\Publish\API\Repository\FieldType
getFieldTypeIdentifier ()
getEmptyValue ()
Protected Member Functions
createValue (array $inputValue)
internalAcceptValue ($inputValue)
completeValue ($value)
getSortInfo ($value)
fileExists ($path)
Protected Attributes
$validatorConfigurationSchema
$fileService
$mimeTypeDetector
Protected Attributes inherited from eZ\Publish\Core\FieldType\FieldType
$settingsSchema = array()
$validatorConfigurationSchema = array()
Detailed Description
Base FileType class for Binary field types (i.e. BinaryBase & Media)
Definition at line 22 of file Type.php.
Constructor & Destructor Documentation
eZ\Publish\Core\FieldType\BinaryBase\Type::__construct (FileService $fileService, MimeTypeDetector $mimeTypeDetector)
Creates a new Image FieldType
Parameters
FileService $fileService
MimeTypeDetector $mimeTypeDetector
Definition at line 56 of file Type.php.
References eZ\Publish\Core\FieldType\BinaryBase\Type\$fileService, and eZ\Publish\Core\FieldType\BinaryBase\Type\$mimeTypeDetector.
    {
        $this->fileService = $fileService;
        $this->mimeTypeDetector = $mimeTypeDetector;
    }
Member Function Documentation
eZ\Publish\Core\FieldType\BinaryBase\Type::completeValue ($value) protected
Attempts to complete the data in $value
Parameters
Value $value
Returns
void
Reimplemented in eZ\Publish\Core\FieldType\Media\Type, and eZ\Publish\Core\FieldType\BinaryFile\Type.
Definition at line 160 of file Type.php.
    {
        if ( !isset( $value->fileSize ) )
        {
            $value->fileSize = filesize( $value->path );
        }
        if ( !isset( $value->fileName ) )
        {
            $value->fileName = basename( $value->path );
        }
        if ( !isset( $value->mimeType ) )
        {
            $value->mimeType = $this->mimeTypeDetector->getMimeType( $value->path );
        }
    }
eZ\Publish\Core\FieldType\BinaryBase\Type::createValue (array $inputValue) abstract protected
Creates a specific value of the derived class from $inputValue
Parameters
array $inputValue
Returns
Value
Reimplemented in eZ\Publish\Core\FieldType\Media\Type, and eZ\Publish\Core\FieldType\BinaryFile\Type.
eZ\Publish\Core\FieldType\BinaryBase\Type::fileExists ($path) protected
Returns if the given $path exists on the local disc or in the file storage
Parameters
string $path
Returns
boolean
Definition at line 308 of file Type.php.
    {
        return (
            ( substr( $path, 0, 1 ) === '/' && file_exists( $path ) )
            || $this->fileService->exists( $this->fileService->getStorageIdentifier( $path ) )
        );
    }
eZ\Publish\Core\FieldType\BinaryBase\Type::fromHash ($hash)
Converts an $hash to the Value defined by the field type
Parameters
mixed $hash
Returns
$value
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 195 of file Type.php.
References eZ\Publish\Core\FieldType\BinaryBase\Type\createValue().
    {
        if ( $hash === null )
        {
            // empty value
            return null;
        }
        return $this->createValue( $hash );
    }
eZ\Publish\Core\FieldType\BinaryBase\Type::fromPersistenceValue (FieldValue $fieldValue)
Converts a persistence $fieldValue to a Value
This method builds a field type value from the $data and $externalData properties.
Parameters
\eZ\Publish\SPI\Persistence\Content\FieldValue $fieldValue
Returns
mixed
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Reimplemented in eZ\Publish\Core\FieldType\Media\Type, and eZ\Publish\Core\FieldType\BinaryFile\Type.
Definition at line 271 of file Type.php.
References eZ\Publish\Core\FieldType\BinaryBase\Type\fromHash().
    {
        if ( $fieldValue->externalData === null )
        {
            // empty value
            return null;
        }
        // Restored data comes in $data, since it has already been processed
        // there might be more data in the persistence value than needed here
        $result = $this->fromHash(
            array(
                'path' => ( isset( $fieldValue->externalData['path'] )
                    ? $fieldValue->externalData['path']
                    : null ),
                'fileName' => ( isset( $fieldValue->externalData['fileName'] )
                    ? $fieldValue->externalData['fileName']
                    : null ),
                'fileSize' => ( isset( $fieldValue->externalData['fileSize'] )
                    ? $fieldValue->externalData['fileSize']
                    : null ),
                'mimeType' => ( isset( $fieldValue->externalData['mimeType'] )
                    ? $fieldValue->externalData['mimeType']
                    : null ),
            )
        );
        return $result;
    }
eZ\Publish\Core\FieldType\BinaryBase\Type::getName ($value)
Returns the name of the given field value.
It will be used to generate content name and url alias if current field is designated to be used in the content name/urlAlias pattern.
Parameters
mixed $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 81 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\acceptValue().
    {
        $value = $this->acceptValue( $value );
        return $value->fileName;
    }
eZ\Publish\Core\FieldType\BinaryBase\Type::getSortInfo ($value) protected
BinaryBase does not support sorting
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 183 of file Type.php.
    {
        return false;
    }
eZ\Publish\Core\FieldType\BinaryBase\Type::internalAcceptValue ($inputValue) protected
Implements the core of {
See Also
acceptValue()}.
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Reimplemented in eZ\Publish\Core\FieldType\Media\Type, and eZ\Publish\Core\FieldType\BinaryFile\Type.
Definition at line 95 of file Type.php.
References eZ\Publish\Core\FieldType\BinaryBase\Type\completeValue(), and eZ\Publish\Core\FieldType\BinaryBase\Type\createValue().
    {
        // construction only from path
        if ( is_string( $inputValue ) )
        {
            $inputValue = array( 'path' => $inputValue );
        }
        // default construction from array
        if ( is_array( $inputValue ) )
        {
            $inputValue = $this->createValue( $inputValue );
        }
        if ( !$inputValue instanceof Value )
        {
            throw new InvalidArgumentType(
                '$inputValue',
                'eZ\\Publish\\Core\\FieldType\\BinaryBase\\Value',
                $inputValue
            );
        }
        // Required paramater $path
        if ( !isset( $inputValue->path ) || !$this->fileExists( $inputValue->path ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->path',
                'Existing fileName',
                $inputValue->path
            );
        }
        $this->completeValue( $inputValue );
        // Required parameter $fileName
        if ( !isset( $inputValue->fileName ) || !is_string( $inputValue->fileName ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->fileName',
                'string',
                $inputValue->fileName
            );
        }
        // Required parameter $fileSize
        if ( !isset( $inputValue->fileSize ) || !is_int( $inputValue->fileSize ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->fileSize',
                'int',
                $inputValue->fileSize
            );
        }
        return $inputValue;
    }
eZ\Publish\Core\FieldType\BinaryBase\Type::isSearchable ()
Returns whether the field type is searchable
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 416 of file Type.php.
    {
        return true;
    }
eZ\Publish\Core\FieldType\BinaryBase\Type::toHash ($value)
Converts a $Value to a hash
Parameters
\eZ\Publish\Core\FieldType\BinaryBase\Value $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Reimplemented in eZ\Publish\Core\FieldType\Media\Type, and eZ\Publish\Core\FieldType\BinaryFile\Type.
Definition at line 213 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\isEmptyValue().
    {
        if ( $this->isEmptyValue( $value ) )
        {
            return null;
        }
        return array(
            'fileName' => $value->fileName,
            'fileSize' => $value->fileSize,
            'path' => $value->path,
            'mimeType' => $value->mimeType,
        );
    }
eZ\Publish\Core\FieldType\BinaryBase\Type::toPersistenceValue ($value)
Converts a $value to a persistence value.
In this method the field type puts the data which is stored in the field of content in the repository into the property FieldValue::data. The format of $data is a primitive, an array (map) or an object, which is then canonically converted to e.g. json/xml structures by future storage engines without further conversions. For mapping the $data to the legacy database an appropriate Converter (implementing eZ) has implemented for the field type. Note: $data should only hold data which is actually stored in the field. It must not hold data which is stored externally.
The $externalData property in the FieldValue is used for storing data externally by the FieldStorage interface method storeFieldData.
The FieldValuer::sortKey is build by the field type for using by sort operations.
See Also
Parameters
mixed $value The value of the field type
Returns
the value processed by the storage engine
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 250 of file Type.php.
References eZ\Publish\Core\FieldType\BinaryBase\Type\getSortInfo(), and eZ\Publish\Core\FieldType\BinaryBase\Type\toHash().
    {
        // Store original data as external (to indicate they need to be stored)
        return new FieldValue(
            array(
                "data" => null,
                "externalData" => $this->toHash( $value ),
                "sortKey" => $this->getSortInfo( $value ),
            )
        );
    }
eZ\Publish\Core\FieldType\BinaryBase\Type::validate (FieldDefinition $fieldDefinition, $fieldValue)
Validates a field based on the validators in the field definition
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException
Parameters
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition The field definition of the field
\eZ\Publish\Core\FieldType\Value $fieldValue The field for which an action is performed
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 326 of file Type.php.
References eZ\Publish\API\Repository\Values\ContentType\FieldDefinition\getValidatorConfiguration().
    {
        $errors = array();
        foreach ( (array)$fieldDefinition->getValidatorConfiguration() as $validatorIdentifier => $parameters )
        {
            switch ( $validatorIdentifier )
            {
                case 'FileSizeValidator':
                    if ( !isset( $parameters['maxFileSize'] ) || $parameters['maxFileSize'] == false )
                    {
                        // No file size limit
                        break;
                    }
                    // Database stores maxFileSize in MB
                    if ( $fieldValue !== null && ( $parameters['maxFileSize'] * 1024 * 1024 ) < $fieldValue->fileSize )
                    {
                        $errors[] = new ValidationError(
                            "The file size cannot exceed %size% byte.",
                            "The file size cannot exceed %size% bytes.",
                            array(
                                "size" => $parameters['maxFileSize'],
                            )
                        );
                    }
                    break;
            }
        }
        return $errors;
    }
eZ\Publish\Core\FieldType\BinaryBase\Type::validateValidatorConfiguration ($validatorConfiguration)
Validates the validatorConfiguration of a FieldDefinitionCreateStruct or FieldDefinitionUpdateStruct
Parameters
mixed $validatorConfiguration
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 363 of file Type.php.
    {
        $validationErrors = array();
        foreach ( $validatorConfiguration as $validatorIdentifier => $parameters )
        {
            switch ( $validatorIdentifier )
            {
                case 'FileSizeValidator':
                    if ( !isset( $parameters['maxFileSize'] ) )
                    {
                        $validationErrors[] = new ValidationError(
                            "Validator %validator% expects parameter %parameter% to be set.",
                            null,
                            array(
                                "validator" => $validatorIdentifier,
                                "parameter" => 'maxFileSize',
                            )
                        );
                        break;
                    }
                    if ( !is_int( $parameters['maxFileSize'] ) && !is_bool( $parameters['maxFileSize'] ) )
                    {
                        $validationErrors[] = new ValidationError(
                            "Validator %validator% expects parameter %parameter% to be of %type%.",
                            null,
                            array(
                                "validator" => $validatorIdentifier,
                                "parameter" => 'maxFileSize',
                                "type" => 'integer',
                            )
                        );
                    }
                    break;
                default:
                    $validationErrors[] = new ValidationError(
                        "Validator '%validator%' is unknown",
                        null,
                        array(
                            "validator" => $validatorIdentifier
                        )
                    );
            }
        }
        return $validationErrors;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\BinaryBase\Type::$fileService protected
Definition at line 41 of file Type.php.
eZ\Publish\Core\FieldType\BinaryBase\Type::$mimeTypeDetector protected
Definition at line 48 of file Type.php.
eZ\Publish\Core\FieldType\BinaryBase\Type::$validatorConfigurationSchema protected
Initial value:
 array(
        "FileSizeValidator" => array(
            'maxFileSize' => array(
                'type' => 'int',
                'default' => false,
            )
        )
    )
See Also
eZ::$validatorConfigurationSchema
Definition at line 27 of file Type.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/BinaryBase/Type.php