ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Mapper Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Mapper Class Reference
Public Member Functions
__construct (Registry $converterRegistry, LanguageHandler $languageHandler)
createVersionInfoFromCreateStruct (CreateStruct $struct, $versionNo)
createVersionInfoForContent (Content $content, $versionNo, $userId)
convertToStorageValue (Field $field)
extractContentFromRows (array $rows)
extractContentInfoFromRow (array $row, $prefix= '')
extractVersionInfoListFromRows (array $rows)
extractLanguageIdsFromMask ($languageMask)
createCreateStructFromContent (Content $content)
extractRelationsFromRows (array $rows)
createRelationFromCreateStruct (RelationCreateStruct $struct)
Protected Member Functions
extractFieldFromRow (array $row)
extractFieldValueFromRow (array $row, $type)
extractRelationFromRow (array $row)
Protected Attributes
$converterRegistry
$languageHandler
Detailed Description
Mapper for Content Handler.
Performs mapping of Content objects.
Definition at line 27 of file Mapper.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::__construct (Registry $converterRegistry, LanguageHandler $languageHandler)
Creates a new mapper.
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\ConverterRegistry $converterRegistry
\eZ\Publish\SPI\Persistence\Content\Language\Handler $languageHandler
Definition at line 49 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Mapper\$converterRegistry, and eZ\Publish\Core\Persistence\Legacy\Content\Mapper\$languageHandler.
    {
        $this->converterRegistry = $converterRegistry;
        $this->languageHandler = $languageHandler;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::convertToStorageValue (Field $field)
Converts value of $field to storage value
Parameters
\eZ\Publish\SPI\Persistence\Content\Field $field
Returns
Definition at line 155 of file Mapper.php.
    {
        $converter = $this->converterRegistry->getConverter(
            $field->type
        );
        $storageValue = new StorageFieldValue();
        $converter->toStorageValue(
            $field->value,
            $storageValue
        );
        return $storageValue;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::createCreateStructFromContent (Content $content)
Creates CreateStruct from $content
Parameters
\eZ\Publish\SPI\Persistence\Content $content
Returns
Definition at line 409 of file Mapper.php.
    {
        $struct = new CreateStruct();
        $struct->name = $content->versionInfo->names;
        $struct->typeId = $content->versionInfo->contentInfo->contentTypeId;
        $struct->sectionId = $content->versionInfo->contentInfo->sectionId;
        $struct->ownerId = $content->versionInfo->contentInfo->ownerId;
        $struct->locations = array();
        $struct->alwaysAvailable = $content->versionInfo->contentInfo->alwaysAvailable;
        $struct->remoteId = md5( uniqid( get_class( $this ), true ) );
        $struct->initialLanguageId = $this->languageHandler->loadByLanguageCode( $content->versionInfo->initialLanguageCode )->id;
        $struct->modified = time();
        foreach ( $content->fields as $field )
        {
            $newField = clone $field;
            $newField->id = null;
            $struct->fields[] = $newField;
        }
        return $struct;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::createRelationFromCreateStruct (RelationCreateStruct $struct)
Creates a Content from the given $struct
Parameters
\eZ\Publish\SPI\Persistence\Content\Relation\CreateStruct $struct
Returns
Definition at line 483 of file Mapper.php.
    {
        $relation = new Relation();
        $relation->destinationContentId = $struct->destinationContentId;
        $relation->sourceContentId = $struct->sourceContentId;
        $relation->sourceContentVersionNo = $struct->sourceContentVersionNo;
        $relation->sourceFieldDefinitionId = $struct->sourceFieldDefinitionId;
        $relation->type = $struct->type;
        return $relation;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::createVersionInfoForContent (Content $content, $versionNo, $userId)
Creates a new version for the given $content
Parameters
\eZ\Publish\SPI\Persistence\Content $content
mixed $versionNo
mixed $userId
Returns
Definition at line 131 of file Mapper.php.
References eZ\Publish\SPI\Persistence\Content\$versionInfo, and eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_DRAFT.
    {
        $versionInfo = new VersionInfo;
        $versionInfo->contentInfo = $content->versionInfo->contentInfo;
        $versionInfo->versionNo = $versionNo;
        $versionInfo->creatorId = $userId;
        $versionInfo->status = VersionInfo::STATUS_DRAFT;
        $versionInfo->initialLanguageCode = $content->versionInfo->initialLanguageCode;
        $versionInfo->creationDate = time();
        $versionInfo->modificationDate = $versionInfo->creationDate;
        $versionInfo->names = is_object( $content->versionInfo ) ? $content->versionInfo->names : array();
        $versionInfo->languageIds = $content->versionInfo->languageIds;
        return $versionInfo;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::createVersionInfoFromCreateStruct (CreateStruct $struct, $versionNo)
Creates a new version for the given $struct and $versionNo
Parameters
\eZ\Publish\SPI\Persistence\Content\CreateStruct $struct
mixed $versionNo
Returns
Definition at line 94 of file Mapper.php.
References eZ\Publish\SPI\Persistence\Content\$versionInfo, and eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_DRAFT.
    {
        $versionInfo = new VersionInfo;
        $versionInfo->id = null;
        $versionInfo->contentInfo = $this->createContentInfoFromCreateStruct( $struct, $versionNo );
        $versionInfo->versionNo = $versionNo;
        $versionInfo->creatorId = $struct->ownerId;
        $versionInfo->status = VersionInfo::STATUS_DRAFT;
        $versionInfo->initialLanguageCode = $this->languageHandler->load( $struct->initialLanguageId )->languageCode;
        $versionInfo->creationDate = $struct->modified;
        $versionInfo->modificationDate = $struct->modified;
        $versionInfo->names = $struct->name;
        $languageIds = array();
        foreach ( $struct->fields as $field )
        {
            if ( !isset( $languageIds[$field->languageCode] ) )
            {
                $languageIds[$field->languageCode] =
                    $this->languageHandler->loadByLanguageCode( $field->languageCode )->id;
            }
        }
        $versionInfo->languageIds = array_values( $languageIds );
        return $versionInfo;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::extractContentFromRows (array $rows)
Extracts Content objects (and nested) from database result $rows
Expects database rows to be indexed by keys of the format
 "$tableName_$columnName"
Parameters
array $rows
Returns
[]
Definition at line 179 of file Mapper.php.
References eZ\Publish\SPI\Persistence\Content\$fields, eZ\Publish\SPI\Persistence\Content\$versionInfo, eZ\Publish\Core\Persistence\Legacy\Content\Mapper\extractContentInfoFromRow(), and eZ\Publish\Core\Persistence\Legacy\Content\Mapper\extractFieldFromRow().
    {
        $contentInfos = array();
        $versionInfos = array();
        $fields = array();
        foreach ( $rows as $row )
        {
            $contentId = (int)$row['ezcontentobject_id'];
            if ( !isset( $contentInfos[$contentId] ) )
            {
                $contentInfos[$contentId] = $this->extractContentInfoFromRow( $row, 'ezcontentobject_' );
            }
            if ( !isset( $versionInfos[$contentId] ) )
            {
                $versionInfos[$contentId] = array();
            }
            $versionId = (int)$row['ezcontentobject_version_id'];
            if ( !isset( $versionInfos[$contentId][$versionId] ) )
            {
                $versionInfos[$contentId][$versionId] = $this->extractVersionInfoFromRow( $row );
            }
            if ( !isset( $versionInfos[$contentId][$versionId]->names[$row['ezcontentobject_name_content_translation']] ) )
            {
                $versionInfos[$contentId][$versionId]->names[$row['ezcontentobject_name_content_translation']] = $row['ezcontentobject_name_name'];
            }
            $fieldId = (int)$row['ezcontentobject_attribute_id'];
            if ( !isset( $fields[$contentId][$versionId][$fieldId] ) )
            {
                $fields[$contentId][$versionId][$fieldId] = $this->extractFieldFromRow( $row );
            }
        }
        $results = array();
        foreach ( $contentInfos as $contentId => $contentInfo )
        {
            foreach ( $versionInfos[$contentId] as $versionId => $versionInfo )
            {
                $content = new Content;
                $content->versionInfo = $versionInfo;
                $content->versionInfo->contentInfo = $contentInfo;
                $content->fields = array_values( $fields[$contentId][$versionId] );
                $results[] = $content;
            }
        }
        return $results;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::extractContentInfoFromRow (array $row, $prefix = '')
Extracts a ContentInfo object from $row
Parameters
array $row
string $prefix Prefix for row keys, which are initially mapped by ezcontentobject fields
Returns
Definition at line 238 of file Mapper.php.
References eZ\Publish\SPI\Persistence\Content\ContentInfo\STATUS_PUBLISHED.
    {
        $contentInfo = new ContentInfo;
        $contentInfo->id = (int)$row["{$prefix}id"];
        $contentInfo->name = $row["{$prefix}name"];
        $contentInfo->contentTypeId = (int)$row["{$prefix}contentclass_id"];
        $contentInfo->sectionId = (int)$row["{$prefix}section_id"];
        $contentInfo->currentVersionNo = (int)$row["{$prefix}current_version"];
        $contentInfo->isPublished = (bool)( $row["{$prefix}status"] == ContentInfo::STATUS_PUBLISHED );
        $contentInfo->ownerId = (int)$row["{$prefix}owner_id"];
        $contentInfo->publicationDate = (int)$row["{$prefix}published"];
        $contentInfo->modificationDate = (int)$row["{$prefix}modified"];
        $contentInfo->alwaysAvailable = (int)$row["{$prefix}language_mask"] & 1;
        $contentInfo->mainLanguageCode = $this->languageHandler->load( $row["{$prefix}initial_language_id"] )->languageCode;
        $contentInfo->remoteId = $row["{$prefix}remote_id"];
        $contentInfo->mainLocationId = $row["ezcontentobject_tree_main_node_id"];
        return $contentInfo;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::extractFieldFromRow (array $row) protected
Extracts a Field from $row
Parameters
array $row
Returns
Field
Definition at line 353 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Mapper\extractFieldValueFromRow().
    {
        $field = new Field();
        $field->id = (int)$row['ezcontentobject_attribute_id'];
        $field->fieldDefinitionId = (int)$row['ezcontentobject_attribute_contentclassattribute_id'];
        $field->type = $row['ezcontentobject_attribute_data_type_string'];
        $field->value = $this->extractFieldValueFromRow( $row, $field->type );
        $field->languageCode = $row['ezcontentobject_attribute_language_code'];
        $field->versionNo = (int)$row['ezcontentobject_attribute_version'];
        return $field;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::extractFieldValueFromRow (array $row, $type) protected
Extracts a FieldValue of $type from $row
Parameters
array $row
string $type
Returns
Exceptions
\eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Exception\NotFound if the necessary converter for $type could not be found.
Definition at line 377 of file Mapper.php.
    {
        $storageValue = new StorageFieldValue();
        // Nullable field
        $storageValue->dataFloat = isset( $row['ezcontentobject_attribute_data_float'] )
            ? (float)$row['ezcontentobject_attribute_data_float']
            : null;
        // Nullable field
        $storageValue->dataInt = isset( $row['ezcontentobject_attribute_data_int'] )
            ? (int)$row['ezcontentobject_attribute_data_int']
            : null;
        $storageValue->dataText = $row['ezcontentobject_attribute_data_text'];
        // Not nullable field
        $storageValue->sortKeyInt = (int)$row['ezcontentobject_attribute_sort_key_int'];
        $storageValue->sortKeyString = $row['ezcontentobject_attribute_sort_key_string'];
        $fieldValue = new FieldValue();
        $converter = $this->converterRegistry->getConverter( $type );
        $converter->toFieldValue( $storageValue, $fieldValue );
        return $fieldValue;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::extractLanguageIdsFromMask ($languageMask)
Todo:
use langmask handler for this
Parameters
int $languageMask
Returns
array
Definition at line 329 of file Mapper.php.
    {
        $exp = 2;
        $result = array();
        // Decomposition of $languageMask into its binary components.
        while ( $exp <= $languageMask )
        {
            if ( $languageMask & $exp )
                $result[] = $exp;
            $exp *= 2;
        }
        return $result;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::extractRelationFromRow (array $row) protected
Extracts a Relation object from a $row
Parameters
array $row Associative array representing a relation
Returns
Definition at line 458 of file Mapper.php.
    {
        $relation = new Relation();
        $relation->id = (int)$row['ezcontentobject_link_id'];
        $relation->sourceContentId = (int)$row['ezcontentobject_link_from_contentobject_id'];
        $relation->sourceContentVersionNo = (int)$row['ezcontentobject_link_from_contentobject_version'];
        $relation->destinationContentId = (int)$row['ezcontentobject_link_to_contentobject_id'];
        $relation->type = (int)$row['ezcontentobject_link_relation_type'];
        $contentClassAttributeId = (int)$row['ezcontentobject_link_contentclassattribute_id'];
        if ( $contentClassAttributeId > 0 )
        {
            $relation->sourceFieldDefinitionId = $contentClassAttributeId;
        }
        return $relation;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::extractRelationsFromRows (array $rows)
Extracts relation objects from $rows
Definition at line 435 of file Mapper.php.
References eZ\Publish\SPI\Persistence\Content\$relations, and eZ\Publish\Core\Persistence\Legacy\Content\Mapper\extractRelationFromRow().
    {
        $relations = array();
        foreach ( $rows as $row )
        {
            $id = (int)$row['ezcontentobject_link_id'];
            if ( !isset( $relations[$id] ) )
            {
                $relations[$id] = $this->extractRelationFromRow( $row );
            }
        }
        return $relations;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::extractVersionInfoListFromRows (array $rows)
Extracts a VersionInfo object from $row
Parameters
array $rows
Returns
[]
Definition at line 292 of file Mapper.php.
References eZ\Publish\SPI\Persistence\Content\$versionInfo, eZ\Publish\Core\Persistence\Legacy\Content\Mapper\extractContentInfoFromRow(), and eZ\Publish\Core\Persistence\Legacy\Content\Mapper\extractLanguageIdsFromMask().
    {
        $versionInfoList = array();
        foreach ( $rows as $row )
        {
            $versionId = (int)$row['ezcontentobject_version_id'];
            if ( !isset( $versionInfoList[$versionId] ) )
            {
                $versionInfo = new VersionInfo;
                $versionInfo->id = (int)$row["ezcontentobject_version_id"];
                $versionInfo->contentInfo = $this->extractContentInfoFromRow( $row, "ezcontentobject_" );
                $versionInfo->versionNo = (int)$row["ezcontentobject_version_version"];
                $versionInfo->creatorId = (int)$row["ezcontentobject_version_creator_id"];
                $versionInfo->creationDate = (int)$row["ezcontentobject_version_created"];
                $versionInfo->modificationDate = (int)$row["ezcontentobject_version_modified"];
                $versionInfo->initialLanguageCode = $this->languageHandler->load( $row["ezcontentobject_version_initial_language_id"] )->languageCode;
                $versionInfo->languageIds = $this->extractLanguageIdsFromMask( (int)$row["ezcontentobject_version_language_mask"] );//array();
                $versionInfo->status = (int)$row["ezcontentobject_version_status"];
                $versionInfo->names = array();
                $versionInfoList[$versionId] = $versionInfo;
            }
            if ( !isset( $versionInfoList[$versionId]->names[$row['ezcontentobject_name_content_translation']] ) )
            {
                $versionInfoList[$versionId]->names[$row['ezcontentobject_name_content_translation']] = $row['ezcontentobject_name_name'];
            }
        }
        return array_values( $versionInfoList );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::$converterRegistry protected
Definition at line 34 of file Mapper.php.
eZ\Publish\Core\Persistence\Legacy\Content\Mapper::$languageHandler protected
Definition at line 41 of file Mapper.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php