ezp-next: eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage Class Reference
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage Class Reference
Public Member Functions
setConnection ($dbHandler)
storeFieldData (Field $field, $contentTypeID)
getFieldData (Field $field)
getContentTypeID (Field $field)
Protected Member Functions
getConnection ()
getAssignedKeywords ($fieldId)
loadContentTypeID ($fieldDefinitionId)
getExistingKeywords ($keywordList, $contentTypeID)
insertKeywords (array $keywordsToInsert, $contentTypeID)
deleteOldKeywordAssignements (Field $field)
assignKeywords ($fieldId, $keywordMap)
Protected Attributes
$dbHandler
Detailed Description
Definition at line 8 of file LegacyStorage.php.
Member Function Documentation
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::assignKeywords ($fieldId, $keywordMap) protected
Assigns keywords from $keywordMap to the field with $fieldId
$keywordMap has the format: array('<keyword>' => <id>, // ...);
Parameters
mixed $fieldId
mixed[] $keywordMap
Returns
void
Definition at line 304 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\$dbHandler, eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\assignKeywords(), and eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getConnection().
    {
        $dbHandler = $this->getConnection();
        $keywordId = null;
        $insertQuery = $dbHandler->createInsertQuery();
        $insertQuery->insertInto(
            $dbHandler->quoteTable( "ezkeyword_attribute_link" )
        )->set(
            $dbHandler->quoteColumn( "keyword_id" ),
            $insertQuery->bindParam( $keywordId )
        )->set(
            $dbHandler->quoteColumn( "objectattribute_id" ),
            $insertQuery->bindValue( $fieldId )
        );
        $statement = $insertQuery->prepare();
        foreach ( $keywordMap as $keyword => $keywordId )
        {
            $keywordId = $keywordMap[$keyword];
            $statement->execute();
        }
    }
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::deleteOldKeywordAssignements (Field $field) protected
Definition at line 270 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\$dbHandler, eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\deleteOldKeywordAssignements(), and eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getConnection().
    {
        $dbHandler = $this->getConnection();
        $deleteQuery = $dbHandler->createDeleteQuery();
        $deleteQuery->deleteFrom(
            $dbHandler->quoteTable( "ezkeyword_attribute_link" )
        )->where(
            $deleteQuery->expr->eq(
                $dbHandler->quoteColumn( "objectattribute_id", "ezkeyword_attribute_link" ),
                $deleteQuery->bindValue( $field->id, null, \PDO::PARAM_INT )
            )
        );
        $statement = $deleteQuery->prepare();
        $statement->execute();
    }
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::getAssignedKeywords ($fieldId) protected
Returns a list of keywords assigned to $fieldId
Parameters
mixed $fieldId
Returns
string[]
Definition at line 111 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\$dbHandler, eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getAssignedKeywords(), and eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getConnection().
    {
        $dbHandler = $this->getConnection();
        $query = $dbHandler->createSelectQuery();
        $query->select( "keyword" )
            ->from( $dbHandler->quoteTable( "ezkeyword" ) )
            ->innerJoin(
                $dbHandler->quoteTable( "ezkeyword_attribute_link" ),
                $query->expr->eq(
                    $dbHandler->quoteColumn( "id", "ezkeyword" ),
                    $dbHandler->quoteColumn( "keyword_id", "ezkeyword_attribute_link" )
                )
            )
            ->where(
                $query->expr->eq(
                    $dbHandler->quoteColumn( "objectattribute_id", "ezkeyword_attribute_link" ),
                    $fieldId
                )
            );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_COLUMN, 0 );
    }
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::getConnection () protected
Returns the active connection
Exceptions
\RuntimeException if no connection has been set, yet.
Returns
Definition at line 47 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getConnection().
    {
        if ( $this->dbHandler === null )
        {
            throw new \RuntimeException( "Missing database connection." );
        }
        return $this->dbHandler;
    }
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::getContentTypeID (Field $field)
Retrieve the ContentType ID for the given $field
Parameters
\eZ\Publish\SPI\Persistence\Content\Field $field
Returns
mixed
Reimplemented from eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway.
Definition at line 99 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getContentTypeID(), and eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\loadContentTypeID().
    {
        return $this->loadContentTypeID( $field->fieldDefinitionId );
    }
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::getExistingKeywords ($keywordList, $contentTypeID) protected
Returns already existing keywords from $keywordList as a map
The map has the following format: array('<keyword>' => <id>, // ...);
Parameters
string[] $keywordList
mixed $contentTypeID
Returns
mixed[]
Definition at line 188 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\$dbHandler, eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getExistingKeywords().
    {
        $dbHandler = $this->getConnection();
        // Retrieving potentially existing keywords
        $q = $dbHandler->createSelectQuery();
        $q->select( "id", "keyword" )
            ->from( $dbHandler->quoteTable( "ezkeyword" ) )
            ->where(
                $q->expr->lAnd(
                    $q->expr->in(
                        "keyword",
                        $keywordList
                    ),
                    $q->expr->eq( "class_id", $contentTypeID )
                )
            );
        $statement = $q->prepare();
        $statement->execute();
        $existingKeywordMap = array();
        foreach ( $statement->fetchAll( \PDO::FETCH_ASSOC ) as $row )
        {
            $existingKeywordMap[$row["keyword"]] = $row["id"];
        }
        return $existingKeywordMap;
    }
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::getFieldData (Field $field)
Sets the list of assigned keywords into $field->value->externalData
Parameters
Field $field
Returns
void
Reimplemented from eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway.
Definition at line 87 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getAssignedKeywords().
    {
        $field->value->externalData = $this->getAssignedKeywords( $field->id );
    }
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::insertKeywords (array $keywordsToInsert, $contentTypeID) protected
Inserts $keywordsToInsert for $fieldDefinitionId and returns a map of these keywords to their ID
The returned array has the following format: array('<keyword>' => <id>, // ...);
Parameters
string[] $keywordsToInsert
mixed $fieldDefinitionId
Returns
mixed[]
Definition at line 235 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\$dbHandler, eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\insertKeywords().
    {
        $dbHandler = $this->getConnection();
        $keywordIdMap = array();
        // Inserting keywords not yet registered
        if ( !empty( $keywordsToInsert ) )
        {
            $insertQuery = $dbHandler->createInsertQuery();
            $insertQuery->insertInto(
                $dbHandler->quoteTable( "ezkeyword" )
            )->set(
                $dbHandler->quoteColumn( "class_id" ),
                $insertQuery->bindValue( $contentTypeID, null, \PDO::PARAM_INT )
            )->set(
                $dbHandler->quoteColumn( "keyword" ),
                $insertQuery->bindParam( $keyword )
            );
            $statement = $insertQuery->prepare();
            foreach ( array_keys( $keywordsToInsert ) as $keyword )
            {
                $statement->execute();
                $keywordIdMap[$keyword] = $dbHandler->lastInsertId(
                    $dbHandler->getSequenceName( 'ezkeyword', 'id' )
                );
            }
            unset( $keyword );
        }
        return $keywordIdMap;
    }
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::loadContentTypeID ($fieldDefinitionId) protected
Retrieves the content type ID for the given $fieldDefinitionId
Parameters
mixed $fieldDefinitionId
Returns
mixed
Definition at line 145 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\$dbHandler, eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\loadContentTypeID().
    {
        $dbHandler = $this->getConnection();
        $query = $dbHandler->createSelectQuery();
        $query->select( 'contentclass_id' )
            ->from( $dbHandler->quoteTable( 'ezcontentclass_attribute' ) )
            ->where(
                $query->expr->eq( 'id', $fieldDefinitionId )
            );
        $statement = $query->prepare();
        $statement->execute();
        $row = $statement->fetch( \PDO::FETCH_ASSOC );
        if ( $row === false )
            throw new \RuntimeException(
                sprintf(
                    'Content Type ID cannot be retrieved based on the field definition ID "%s"',
                    $fieldDefinitionId
                )
            );
        return $row['contentclass_id'];
    }
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::setConnection ($dbHandler)
Set database handler for this gateway
Parameters
mixed $dbHandler
Returns
void
Exceptions
\RuntimeException if $dbHandler is not an instance of eZ\Publish\Core\Persistence\Legacy\EzcDbHandler
Reimplemented from eZ\Publish\Core\FieldType\StorageGateway.
Definition at line 26 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\$dbHandler, and eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\setConnection().
    {
        // This obviously violates the Liskov substitution Principle, but with
        // the given class design there is no sane other option. Actually the
        // dbHandler *should* be passed to the constructor, and there should
        // not be the need to post-inject it.
        if ( !$dbHandler instanceof \eZ\Publish\Core\Persistence\Legacy\EzcDbHandler )
        {
            throw new \RuntimeException( "Invalid dbHandler passed" );
        }
        $this->dbHandler = $dbHandler;
    }
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::storeFieldData (Field $field, $contentTypeID)
Stores the keyword list from $field->value->externalData
Parameters
\eZ\Publish\SPI\Persistence\Content\Field
mixed $contentTypeID
Reimplemented from eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway.
Definition at line 62 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\assignKeywords(), eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\deleteOldKeywordAssignements(), and eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage\getExistingKeywords().
    {
        $existingKeywordMap = $this->getExistingKeywords( $field->value->externalData, $contentTypeID );
        $this->deleteOldKeywordAssignements( $field );
        $this->assignKeywords(
            $field->id,
            $this->insertKeywords(
                array_diff_key(
                    array_fill_keys( $field->value->externalData, true ),
                    $existingKeywordMap
                ),
                $contentTypeID
            ) + $existingKeywordMap
        );
    }
Member Data Documentation
eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage::$dbHandler protected
Definition at line 15 of file LegacyStorage.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Keyword/KeywordStorage/Gateway/LegacyStorage.php