ezp-next: eZ\Publish\Core\IO\Handler\Filesystem Class Reference
eZ\Publish\Core\IO\Handler\Filesystem Class Reference
Public Member Functions
__construct ($storageDirectory)
create (BinaryFileCreateStruct $createStruct)
delete ($path)
update ($path, BinaryFileUpdateStruct $updateFileStruct)
exists ($path)
load ($path)
getFileResource ($path)
getFileContents ($path)
getInternalPath ($path)
getExternalPath ($path)
getMetadata (MetadataHandler $metadataHandler, $path)
Public Member Functions inherited from eZ\Publish\Core\IO\Handler
create (BinaryFileCreateStruct $createStruct)
Protected Member Functions
getStoragePath ($path)
removePrefix ($uri)
Detailed Description
Legacy Io/Storage handler, based on eZ Cluster
Due to the legacy API, this handler has a few limitations:
ctime is not really supported, and will always have the same value as mtime
mtime can not be modified, and will always automatically be set depending on the server time upon each write operation
Definition at line 30 of file Filesystem.php.
Constructor & Destructor Documentation
eZ\Publish\Core\IO\Handler\Filesystem::__construct ($storageDirectory)
Parameters
string $storageDirectory
Definition at line 47 of file Filesystem.php.
References eZ\Publish\Core\IO\Handler\Filesystem\__construct().
    {
        if ( !file_exists( $storageDirectory ) || !is_dir( $storageDirectory ) )
        {
            throw new \RuntimeException( "Storage directory $storageDirectory doesn't exist" );
        }
        if ( !is_writeable( $storageDirectory ) )
        {
            throw new \RuntimeException( "Storage directory $storageDirectory can not be written to" );
        }
        $this->storageDirectory = realpath( $storageDirectory );
        if ( $storageDirectory[0] !== DIRECTORY_SEPARATOR )
        {
            $this->prefix = $storageDirectory;
        }
    }
Member Function Documentation
eZ\Publish\Core\IO\Handler\Filesystem::create (BinaryFileCreateStruct $createStruct)
Creates and stores a new BinaryFile based on the BinaryFileCreateStruct $file
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException If the target path already exists
\RuntimeException If the directory in $createStruct->uri exists but is a file
Parameters
\eZ\Publish\SPI\IO\BinaryFileCreateStruct $createStruct
Returns
The newly created BinaryFile object
Definition at line 74 of file Filesystem.php.
References eZ\Publish\Core\IO\Handler\exists(), eZ\Publish\SPI\IO\BinaryFileCreateStruct\getInputStream(), eZ\Publish\Core\IO\Handler\Filesystem\getStoragePath(), and eZ\Publish\Core\IO\Handler\load().
    {
        if ( $this->exists( $createStruct->uri ) )
        {
            throw new InvalidArgumentException(
                "\$createFilestruct->uri",
                "file '{$createStruct->uri}' already exists"
            );
        }
        $storagePath = $this->getStoragePath( $createStruct->uri );
        $outputDirectory = dirname( $createStruct->uri );
        if ( file_exists( $outputDirectory ) && !is_dir( $outputDirectory ) )
        {
            throw new RuntimeException( "Directory $outputDirectory exists but is a file" );
        }
        if ( !file_exists( $outputDirectory ) )
        {
            $this->createFolderStructure( $outputDirectory );
        }
        $outputStream = fopen( $storagePath, 'wb' );
        stream_copy_to_stream( $createStruct->getInputStream(), $outputStream );
        return $this->load( $createStruct->uri );
    }
eZ\Publish\Core\IO\Handler\Filesystem::delete ($path)
Deletes the existing BinaryFile with path $path
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If the file doesn't exist
Parameters
string $path
Implements eZ\Publish\Core\IO\Handler.
Definition at line 129 of file Filesystem.php.
References eZ\Publish\Core\IO\Handler\exists(), and eZ\Publish\Core\IO\Handler\Filesystem\getStoragePath().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        unlink( $this->getStoragePath( $path ) );
    }
eZ\Publish\Core\IO\Handler\Filesystem::exists ($path)
Checks if the BinaryFile with path $path exists
Parameters
string $path
Returns
boolean
Implements eZ\Publish\Core\IO\Handler.
Definition at line 203 of file Filesystem.php.
References eZ\Publish\Core\IO\Handler\Filesystem\getStoragePath().
    {
        return file_exists( $this->getStoragePath( $path ) );
    }
eZ\Publish\Core\IO\Handler\Filesystem::getExternalPath ($path)
Removes the internal storage path from $path
Parameters
string $path
Returns
string
Implements eZ\Publish\Core\IO\Handler.
Definition at line 286 of file Filesystem.php.
References eZ\Publish\Core\IO\Handler\Filesystem\removePrefix().
    {
        return $this->removePrefix( $path );
    }
eZ\Publish\Core\IO\Handler\Filesystem::getFileContents ($path)
Returns the contents of the BinaryFile identified by $path
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException if the file couldn't be found
Parameters
string $path
Returns
string
Implements eZ\Publish\Core\IO\Handler.
Definition at line 259 of file Filesystem.php.
References eZ\Publish\Core\IO\Handler\exists(), and eZ\Publish\Core\IO\Handler\Filesystem\getStoragePath().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        return file_get_contents( $this->getStoragePath( $path ) );
    }
eZ\Publish\Core\IO\Handler\Filesystem::getFileResource ($path)
Returns a file resource to the BinaryFile identified by $path
Parameters
string $path
Returns
resource
Implements eZ\Publish\Core\IO\Handler.
Definition at line 241 of file Filesystem.php.
References eZ\Publish\Core\IO\Handler\exists(), and eZ\Publish\Core\IO\Handler\Filesystem\getStoragePath().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( "BinaryFile", $path );
        }
        return fopen( $this->getStoragePath( $path ), 'rb' );
    }
eZ\Publish\Core\IO\Handler\Filesystem::getInternalPath ($path)
Returns the internal, handler level path to $path
Parameters
string $path
Returns
string
Implements eZ\Publish\Core\IO\Handler.
Definition at line 274 of file Filesystem.php.
    {
        if ( !isset( $this->prefix ) )
        {
            return $path;
        }
        else
        {
            return $this->prefix . DIRECTORY_SEPARATOR . $path;
        }
    }
eZ\Publish\Core\IO\Handler\Filesystem::getMetadata (MetadataHandler $metadataHandler, $path)
Executes $metadataHandler on $path, and returns the metadata array
Parameters
MetadataHandler $metadataHandler
string $path
Returns
array
Implements eZ\Publish\Core\IO\Handler.
Definition at line 299 of file Filesystem.php.
References eZ\Publish\Core\IO\MetadataHandler\extract(), and eZ\Publish\Core\IO\Handler\Filesystem\getStoragePath().
    {
        return $metadataHandler->extract( $this->getStoragePath( $path ) );
    }
eZ\Publish\Core\IO\Handler\Filesystem::getStoragePath ($path) protected
Transforms a path in a storage path using the $storageDirectory
Parameters
string $path
Returns
string
Definition at line 309 of file Filesystem.php.
References eZ\Publish\Core\IO\Handler\Filesystem\getStoragePath().
    {
        if ( $this->storageDirectory )
            $path = $this->storageDirectory . DIRECTORY_SEPARATOR . $path;
        return $path;
    }
eZ\Publish\Core\IO\Handler\Filesystem::load ($path)
Loads the BinaryFile identified by $path
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If no file identified by $path exists
Parameters
string $path
Returns
Implements eZ\Publish\Core\IO\Handler.
Definition at line 217 of file Filesystem.php.
References eZ\Publish\Core\IO\Handler\exists(), and eZ\Publish\Core\IO\Handler\Filesystem\getStoragePath().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        $storagePath = $this->getStoragePath( $path );
        $file = new BinaryFile();
        $file->uri = $path;
        $file->mtime = new DateTime();
        $file->mtime->setTimestamp( filemtime( $storagePath ) );
        $file->size = filesize( $storagePath );
        return $file;
    }
eZ\Publish\Core\IO\Handler\Filesystem::removePrefix ($uri) protected
Definition at line 316 of file Filesystem.php.
References eZ\Publish\Core\IO\Handler\Filesystem\removePrefix().
    {
        if ( !isset( $this->prefix ) )
        {
            return $uri;
        }
        if ( strpos( $uri, $this->prefix . DIRECTORY_SEPARATOR ) !== 0 )
        {
            throw new InvalidArgumentException( '$uri', "Prefix {$this->prefix} not found in {$uri}" );
        }
        return substr( $uri, strlen( $this->prefix ) + 1 );
    }
eZ\Publish\Core\IO\Handler\Filesystem::update ($path, BinaryFileUpdateStruct $updateFileStruct)
Updates the file identified by $path with data from $updateFile
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If the source path doesn't exist
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException If the target path already exists
Parameters
string $path
\eZ\Publish\SPI\IO\BinaryFileUpdateStruct $updateFileStruct
Returns
The updated BinaryFile
Implements eZ\Publish\Core\IO\Handler.
Definition at line 149 of file Filesystem.php.
References eZ\Publish\Core\IO\Handler\exists(), eZ\Publish\SPI\IO\BinaryFileUpdateStruct\getInputStream(), eZ\Publish\Core\IO\Handler\Filesystem\getStoragePath(), and eZ\Publish\Core\IO\Handler\load().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        $sourceStoragePath = $this->getStoragePath( $path );
        if ( !isset( $updateFileStruct->uri ) || $updateFileStruct->uri == $path )
        {
            $destinationStoragePath = $this->getStoragePath( $path );
        }
        else
        {
            if ( $this->exists( $updateFileStruct->uri ) )
            {
                throw new InvalidArgumentException(
                    "\$updateFileStruct->uri",
                    "File '{$updateFileStruct->uri}' already exists"
                );
            }
            $destinationStoragePath = $this->getStoragePath( $updateFileStruct->uri );
        }
        // path
        if ( $destinationStoragePath != $sourceStoragePath )
        {
            $destinationStorageDirectory = dirname( $destinationStoragePath );
            if ( !file_exists( $destinationStorageDirectory ) )
            {
                $this->createFolderStructure( $destinationStorageDirectory );
            }
            rename( $sourceStoragePath, $destinationStoragePath );
        }
        if ( $updateFileStruct->getInputStream() !== null )
        {
            $outputStream = fopen( $sourceStoragePath, 'wb' );
            stream_copy_to_stream( $updateFileStruct->getInputStream(), $outputStream );
            fclose( $outputStream );
        }
        return $this->load( $sourceStoragePath );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/IO/Handler/Filesystem.php