ezp-next: eZ\Bundle\EzPublishRestBundle\EventListener\RestListener Class Reference
eZ\Bundle\EzPublishRestBundle\EventListener\RestListener Class Reference
Public Member Functions
__construct (ContainerInterface $container, RESTRequest $request, CsrfProviderInterface $csrfProvider=null)
onKernelResultView (GetResponseForControllerResultEvent $event)
onKernelExceptionView (GetResponseForExceptionEvent $event)
onKernelRequest (GetResponseEvent $event)
Static Public Member Functions
static getSubscribedEvents ()
Public Attributes
const CSRF_TOKEN_HEADER = "X-CSRF-Token"
Protected Member Functions
isRestRequest (Request $request)
visitResult ($result)
Detailed Description
This class listens, as a service, for the kernel.view event, triggered when a controller method didn't return a Response object.
It converts the RestValue / Value Object to a Response using Visitors
Definition at line 31 of file RestListener.php.
Constructor & Destructor Documentation
eZ\Bundle\EzPublishRestBundle\EventListener\RestListener::__construct (ContainerInterface $container, RESTRequest $request, CsrfProviderInterface $csrfProvider = null)
Parameters
\Symfony\Component\DependencyInjection\ContainerInterface $container
\eZ\Publish\Core\REST\Server\Request $request
\Symfony\Component\Form\Extension\Csrf\CsrfProvider\CsrfProviderInterface $csrfProvider
Definition at line 58 of file RestListener.php.
    {
        $this->container = $container;
        $this->request = $request;
        $this->csrfProvider = $csrfProvider;
    }
Member Function Documentation
static eZ\Bundle\EzPublishRestBundle\EventListener\RestListener::getSubscribedEvents () static
Returns
array
Definition at line 68 of file RestListener.php.
    {
        return array(
            KernelEvents::VIEW => 'onKernelResultView',
            KernelEvents::EXCEPTION => 'onKernelExceptionView',
            KernelEvents::REQUEST => 'onKernelRequest'
        );
    }
eZ\Bundle\EzPublishRestBundle\EventListener\RestListener::isRestRequest (Request $request) protected
Parameters
\Symfony\Component\HttpFoundation\Request $request
Returns
boolean
Definition at line 160 of file RestListener.php.
    {
        return ( strpos( $request->getPathInfo(), '/api/ezp/v2/' ) === 0 );
    }
eZ\Bundle\EzPublishRestBundle\EventListener\RestListener::onKernelExceptionView (GetResponseForExceptionEvent $event)
Parameters
\Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent $event
Exceptions
\Exception
Returns
void
Definition at line 104 of file RestListener.php.
References eZ\Bundle\EzPublishRestBundle\EventListener\RestListener\isRestRequest(), and eZ\Bundle\EzPublishRestBundle\EventListener\RestListener\visitResult().
    {
        if ( $event->getRequestType() !== HttpKernelInterface::MASTER_REQUEST )
            return;
        if ( !$this->isRestRequest( $event->getRequest() ) )
            return;
        $result = $event->getException();
        $event->setResponse( $this->visitResult( $result ) );
        $event->stopPropagation();
    }
eZ\Bundle\EzPublishRestBundle\EventListener\RestListener::onKernelRequest (GetResponseEvent $event)
This method validates CSRF token if CSRF protection is enabled.
Parameters
\Symfony\Component\HttpKernel\Event\GetResponseEvent $event
Exceptions
\eZ\Publish\Core\Base\Exceptions\UnauthorizedException
Definition at line 125 of file RestListener.php.
References eZ\Bundle\EzPublishRestBundle\EventListener\RestListener\isRestRequest().
    {
        if ( !$this->container->getParameter( 'form.type_extension.csrf.enabled' ) )
            return;
        if ( $event->getRequestType() !== HttpKernelInterface::MASTER_REQUEST )
            return;
        if ( !$this->isRestRequest( $event->getRequest() ) )
            return;
        if ( in_array( $event->getRequest()->getMethod(), array( 'GET', 'HEAD' ) ) )
            return;
        // TODO: add CSRF token to protect against force-login attacks
        if ( $event->getRequest()->get( "_route" ) == "ezpublish_rest_createSession" )
            return;
        if (
            !$event->getRequest()->headers->has( self::CSRF_TOKEN_HEADER )
            || !$this->csrfProvider->isCsrfTokenValid( 'rest', $event->getRequest()->headers->get( self::CSRF_TOKEN_HEADER ) )
        )
        {
            throw new UnauthorizedException(
                "Missing or invalid CSRF token",
                $event->getRequest()->getMethod() . " " . $event->getRequest()->getPathInfo()
            );
        }
    }
eZ\Bundle\EzPublishRestBundle\EventListener\RestListener::onKernelResultView (GetResponseForControllerResultEvent $event)
Parameters
\Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent $event
Exceptions
\Exception
Definition at line 83 of file RestListener.php.
References eZ\Bundle\EzPublishRestBundle\EventListener\RestListener\isRestRequest(), and eZ\Bundle\EzPublishRestBundle\EventListener\RestListener\visitResult().
    {
        if ( $event->getRequestType() !== HttpKernelInterface::MASTER_REQUEST )
            return;
        if ( !$this->isRestRequest( $event->getRequest() ) )
            return;
        $result = $event->getControllerResult();
        $event->setResponse( $this->visitResult( $result ) );
        $event->stopPropagation();
    }
eZ\Bundle\EzPublishRestBundle\EventListener\RestListener::visitResult ($result) protected
Parameters
mixed $result
Returns
Definition at line 170 of file RestListener.php.
    {
        // visit response
        $viewDispatcher = $this->container->get( 'ezpublish_rest.response_visitor_dispatcher' );
        $message = $viewDispatcher->dispatch( $this->container->get( 'ezpublish_rest.request' ), $result );
        // @todo It would be even better if visitors would return a Symfony message directly
        return new Response( $message->body, $message->statusCode, $message->headers );
    }
Member Data Documentation
const eZ\Bundle\EzPublishRestBundle\EventListener\RestListener::CSRF_TOKEN_HEADER = "X-CSRF-Token"
Name of the HTTP header containing CSRF token.
Definition at line 36 of file RestListener.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Bundle/EzPublishRestBundle/EventListener/RestListener.php