ezp-next: eZ\Publish\Core\Repository\URLAliasService Class Reference
eZ\Publish\Core\Repository\URLAliasService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, Handler $urlAliasHandler, array $settings=array())
createUrlAlias (Location $location, $path, $languageCode, $forwarding=false, $alwaysAvailable=false)
createGlobalUrlAlias ($resource, $path, $languageCode, $forwarding=false, $alwaysAvailable=false)
listLocationAliases (Location $location, $custom=true, $languageCode=null)
listGlobalAliases ($languageCode=null, $offset=0, $limit=-1)
removeAliases (array $aliasList)
lookup ($url, $languageCode=null)
reverseLookup (Location $location, $languageCode=null)
load ($id)
Protected Member Functions
selectAliasLanguageCode (SPIURLAlias $spiUrlAlias, $languageCode)
extractPath (SPIURLAlias $spiUrlAlias, $languageCode)
choosePrioritizedLanguageCode (array $entries)
matchPath (SPIURLAlias $spiUrlAlias, $path, $languageCode)
matchLanguageCode (array $pathElementData, $pathElement)
isUrlAliasLoadable (SPIURLAlias $spiUrlAlias, $languageCode)
isPathLoadable (array $pathData, array $languageCodes)
buildSPIUrlAlias (URLAlias $urlAlias)
cleanUrl ($url)
buildUrlAliasDomainObject (SPIURLAlias $spiUrlAlias, $path)
Protected Attributes
$repository
$urlAliasHandler
$settings
Detailed Description
Definition at line 31 of file URLAliasService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\URLAliasService::__construct (RepositoryInterface $repository, Handler $urlAliasHandler, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\API\Repository\Repository $repository
\eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler $urlAliasHandler
array $settings
Definition at line 55 of file URLAliasService.php.
References eZ\Publish\Core\Repository\URLAliasService\$repository, eZ\Publish\Core\Repository\URLAliasService\$settings, and eZ\Publish\Core\Repository\URLAliasService\$urlAliasHandler.
    {
        $this->repository = $repository;
        $this->urlAliasHandler = $urlAliasHandler;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            "showAllTranslations" => false
        );
        // Get prioritized languages from language service to not have to call it several times
        $this->settings['prioritizedLanguageList'] = $repository->getContentLanguageService()->getPrioritizedLanguageCodeList();
    }
Member Function Documentation
eZ\Publish\Core\Repository\URLAliasService::buildSPIUrlAlias (URLAlias $urlAlias) protected
Builds persistence domain object.
Parameters
\eZ\Publish\API\Repository\Values\Content\URLAlias $urlAlias
Returns
Definition at line 543 of file URLAliasService.php.
    {
        return new SPIURLAlias(
            array(
                "id" => $urlAlias->id,
                "isCustom" => $urlAlias->isCustom
            )
        );
    }
eZ\Publish\Core\Repository\URLAliasService::buildUrlAliasDomainObject (SPIURLAlias $spiUrlAlias, $path) protected
Builds API UrlAlias object from given SPI UrlAlias object
Parameters
\eZ\Publish\SPI\Persistence\Content\URLAlias $spiUrlAlias
string | null $path
Returns
Definition at line 656 of file URLAliasService.php.
    {
        return new URLAlias(
            array(
                "id" => $spiUrlAlias->id,
                "type" => $spiUrlAlias->type,
                "destination" => $spiUrlAlias->destination,
                "languageCodes" => $spiUrlAlias->languageCodes,
                "alwaysAvailable" => $spiUrlAlias->alwaysAvailable,
                "path" => "/" . $path,
                "isHistory" => $spiUrlAlias->isHistory,
                "isCustom" => $spiUrlAlias->isCustom,
                "forward" => $spiUrlAlias->forward
            )
        );
    }
eZ\Publish\Core\Repository\URLAliasService::choosePrioritizedLanguageCode (array $entries) protected
Returns language code with highest priority.
Will return false if language code could nto be matched with language settings in place.
Parameters
array $entries
Returns
string|boolean
Definition at line 311 of file URLAliasService.php.
    {
        foreach ( $this->settings["prioritizedLanguageList"] as $prioritizedLanguageCode )
        {
            if ( isset( $entries["translations"][$prioritizedLanguageCode] ) )
            {
                return $prioritizedLanguageCode;
            }
        }
        if ( $entries["always-available"] || $this->settings["showAllTranslations"] )
        {
            return key( $entries["translations"] );
        }
        return false;
    }
eZ\Publish\Core\Repository\URLAliasService::cleanUrl ($url) protected
Parameters
string $url
Returns
string
Definition at line 643 of file URLAliasService.php.
    {
        return trim( $url, "/ " );
    }
eZ\Publish\Core\Repository\URLAliasService::createGlobalUrlAlias ($resource, $path, $languageCode, $forwarding = false, $alwaysAvailable = false)
Create a user chosen $alias pointing to a resource in $languageCode.
This method does not handle location resources - if a user enters a location target the createCustomUrlAlias method has to be used. This method runs URL filters and and transformers before storing them. Hence the path returned in the URLAlias Value may differ from the given.
$alwaysAvailable makes the alias available in all languages.
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the path already exists for the given language or if resource is not valid
Parameters
string $resource
string $path
string $languageCode
boolean $forwarding
boolean $alwaysAvailable
Returns
Implements eZ\Publish\API\Repository\URLAliasService.
Definition at line 139 of file URLAliasService.php.
References eZ\Publish\Core\Repository\URLAliasService\buildUrlAliasDomainObject(), eZ\Publish\Core\Repository\URLAliasService\cleanUrl(), and eZ\Publish\Core\Repository\URLAliasService\createUrlAlias().
    {
        if ( !preg_match( "#^([a-zA-Z0-9_]+):(.+)$#", $resource, $matches ) )
        {
            throw new InvalidArgumentException( "\$resource", "argument is not valid" );
        }
        $path = $this->cleanUrl( $path );
        if ( $matches[1] === "eznode" || 0 === strpos( $matches[2], "module:content/view/full/" ) )
        {
            if ( $matches[1] === "eznode" )
            {
                $locationId = $matches[2];
            }
            else
            {
                $resourcePath = explode( "/", $matches[2] );
                $locationId = end( $resourcePath );
            }
            return $this->createUrlAlias(
                $locationId,
                $path,
                $languageCode,
                $forwarding,
                $alwaysAvailable
            );
        }
        $this->repository->beginTransaction();
        try
        {
            $spiUrlAlias = $this->urlAliasHandler->createGlobalUrlAlias(
                $matches[1] . ":" . $this->cleanUrl( $matches[2] ),
                $path,
                $forwarding,
                $languageCode,
                $alwaysAvailable
            );
            $this->repository->commit();
        }
        catch ( ForbiddenException $e )
        {
            $this->repository->rollback();
            throw new InvalidArgumentException( "\$path", $e->getMessage(), $e );
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildUrlAliasDomainObject( $spiUrlAlias, $path );
    }
eZ\Publish\Core\Repository\URLAliasService::createUrlAlias (Location $location, $path, $languageCode, $forwarding = false, $alwaysAvailable = false)
Create a user chosen $alias pointing to $location in $languageCode.
This method runs URL filters and transformers before storing them. Hence the path returned in the URLAlias Value may differ from the given. $alwaysAvailable makes the alias available in all languages.
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location
string $path
boolean $forwarding if true a redirect is performed
string $languageCode the languageCode for which this alias is valid
boolean $alwaysAvailable
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the path already exists for the given language
Returns
Implements eZ\Publish\API\Repository\URLAliasService.
Definition at line 84 of file URLAliasService.php.
References eZ\Publish\Core\Repository\URLAliasService\buildUrlAliasDomainObject(), and eZ\Publish\Core\Repository\URLAliasService\cleanUrl().
    {
        $path = $this->cleanUrl( $path );
        $this->repository->beginTransaction();
        try
        {
            $spiUrlAlias = $this->urlAliasHandler->createCustomUrlAlias(
                $location->id,
                $path,
                $forwarding,
                $languageCode,
                $alwaysAvailable
            );
            $this->repository->commit();
        }
        catch ( ForbiddenException $e )
        {
            $this->repository->rollback();
            throw new InvalidArgumentException(
                "\$path",
                $e->getMessage(),
                $e
            );
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildUrlAliasDomainObject( $spiUrlAlias, $path );
    }
eZ\Publish\Core\Repository\URLAliasService::extractPath (SPIURLAlias $spiUrlAlias, $languageCode) protected
Returns path extracted from normalized path data returned from persistence, using language settings.
Will return false if path could not be determined.
Parameters
\eZ\Publish\SPI\Persistence\Content\URLAlias $spiUrlAlias
string $languageCode
Returns
string|boolean
Definition at line 275 of file URLAliasService.php.
References eZ\Publish\Core\Repository\URLAliasService\choosePrioritizedLanguageCode(), and eZ\Publish\Core\Repository\URLAliasService\selectAliasLanguageCode().
    {
        $pathData = array();
        $pathLevels = count( $spiUrlAlias->pathData );
        foreach ( $spiUrlAlias->pathData as $level => $levelEntries )
        {
            if ( $level === $pathLevels - 1 )
            {
                $prioritizedLanguageCode = $this->selectAliasLanguageCode( $spiUrlAlias, $languageCode );
            }
            else
            {
                $prioritizedLanguageCode = $this->choosePrioritizedLanguageCode( $levelEntries );
            }
            if ( $prioritizedLanguageCode === false )
            {
                return false;
            }
            $pathData[$level] = $levelEntries["translations"][$prioritizedLanguageCode];
        }
        return implode( "/", $pathData );
    }
eZ\Publish\Core\Repository\URLAliasService::isPathLoadable (array $pathData, array $languageCodes) protected
Returns true or false depending if URL alias is loadable or not for language settings in place.
Parameters
array $pathData
array $languageCodes
Returns
boolean
Definition at line 439 of file URLAliasService.php.
    {
        if ( $this->settings["showAllTranslations"] )
        {
            return true;
        }
        foreach ( $pathData as $level => $levelPathData )
        {
            if ( $levelPathData["always-available"] )
            {
                continue;
            }
            if ( in_array( $languageCodes[$level], $this->settings["prioritizedLanguageList"] ) )
            {
                continue;
            }
            return false;
        }
        return true;
    }
eZ\Publish\Core\Repository\URLAliasService::isUrlAliasLoadable (SPIURLAlias $spiUrlAlias, $languageCode) protected
Returns true or false depending if URL alias is loadable or not for language settings in place.
Parameters
\eZ\Publish\SPI\Persistence\Content\URLAlias $spiUrlAlias
string | null $languageCode
Returns
boolean
Definition at line 398 of file URLAliasService.php.
    {
        if ( isset( $languageCode ) && !in_array( $languageCode, $spiUrlAlias->languageCodes ) )
        {
            return false;
        }
        if ( $this->settings["showAllTranslations"] )
        {
            return true;
        }
        foreach ( $spiUrlAlias->pathData as $levelPathData )
        {
            if ( $levelPathData["always-available"] )
            {
                continue;
            }
            foreach ( $levelPathData["translations"] as $translationLanguageCode => $translation )
            {
                if ( in_array( $translationLanguageCode, $this->settings["prioritizedLanguageList"] ) )
                {
                    continue 2;
                }
            }
            return false;
        }
        return true;
    }
eZ\Publish\Core\Repository\URLAliasService::listGlobalAliases ($languageCode = null, $offset = 0, $limit = -1)
List global aliases
Parameters
string $languageCode filters those which are valid for the given language
int $offset
int $limit
Returns
[]
Implements eZ\Publish\API\Repository\URLAliasService.
Definition at line 473 of file URLAliasService.php.
References eZ\Publish\Core\Repository\URLAliasService\buildUrlAliasDomainObject(), and eZ\Publish\Core\Repository\URLAliasService\extractPath().
    {
        $urlAliasList = array();
        $spiUrlAliasList = $this->urlAliasHandler->listGlobalURLAliases(
            $languageCode,
            $offset,
            $limit
        );
        foreach ( $spiUrlAliasList as $spiUrlAlias )
        {
            $path = $this->extractPath( $spiUrlAlias, $languageCode );
            if ( $path === false )
            {
                continue;
            }
            $urlAliasList[] = $this->buildUrlAliasDomainObject( $spiUrlAlias, $path );
        }
        return $urlAliasList;
    }
eZ\Publish\Core\Repository\URLAliasService::listLocationAliases (Location $location, $custom = true, $languageCode = null)
List of url aliases pointing to $location.
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location
boolean $custom if true the user generated aliases are listed otherwise the autogenerated
string $languageCode filters those which are valid for the given language
Returns
[]
Implements eZ\Publish\API\Repository\URLAliasService.
Definition at line 204 of file URLAliasService.php.
References eZ\Publish\Core\Repository\URLAliasService\buildUrlAliasDomainObject(), eZ\Publish\Core\Repository\URLAliasService\extractPath(), and eZ\Publish\Core\Repository\URLAliasService\isUrlAliasLoadable().
    {
        $urlAliasList = array();
        $spiUrlAliasList = $this->urlAliasHandler->listURLAliasesForLocation(
            $location->id,
            $custom
        );
        foreach ( $spiUrlAliasList as $spiUrlAlias )
        {
            if ( !$this->isUrlAliasLoadable( $spiUrlAlias, $languageCode ) )
            {
                continue;
            }
            $path = $this->extractPath( $spiUrlAlias, $languageCode );
            if ( $path === false )
            {
                continue;
            }
            $urlAliasList[] = $this->buildUrlAliasDomainObject( $spiUrlAlias, $path );
        }
        return $urlAliasList;
    }
eZ\Publish\Core\Repository\URLAliasService::load ($id)
Loads URL alias by given $id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException
Parameters
string $id
Returns
Implements eZ\Publish\API\Repository\URLAliasService.
Definition at line 625 of file URLAliasService.php.
References eZ\Publish\Core\Repository\URLAliasService\buildUrlAliasDomainObject(), and eZ\Publish\Core\Repository\URLAliasService\extractPath().
    {
        $spiUrlAlias = $this->urlAliasHandler->loadUrlAlias( $id );
        $path = $this->extractPath( $spiUrlAlias, null );
        if ( $path === false )
        {
            throw new NotFoundException( "URLAlias", $id );
        }
        return $this->buildUrlAliasDomainObject( $spiUrlAlias, $path );
    }
eZ\Publish\Core\Repository\URLAliasService::lookup ($url, $languageCode = null)
looks up the URLAlias for the given url.
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the path does not exist or is not valid for the given language
Parameters
string $url
string $languageCode
Returns
Implements eZ\Publish\API\Repository\URLAliasService.
Definition at line 563 of file URLAliasService.php.
References eZ\Publish\Core\Repository\URLAliasService\buildUrlAliasDomainObject(), eZ\Publish\Core\Repository\URLAliasService\cleanUrl(), eZ\Publish\Core\Repository\URLAliasService\isPathLoadable(), and eZ\Publish\Core\Repository\URLAliasService\matchPath().
    {
        $url = $this->cleanUrl( $url );
        $spiUrlAlias = $this->urlAliasHandler->lookup( $url );
        list( $path, $languageCodes ) = $this->matchPath( $spiUrlAlias, $url, $languageCode );
        if ( $path === false || !$this->isPathLoadable( $spiUrlAlias->pathData, $languageCodes ) )
        {
            throw new NotFoundException( "URLAlias", $url );
        }
        return $this->buildUrlAliasDomainObject( $spiUrlAlias, $path );
    }
eZ\Publish\Core\Repository\URLAliasService::matchLanguageCode (array $pathElementData, $pathElement) protected
Parameters
array $pathElementData
string $pathElement
Returns
string|boolean
Definition at line 377 of file URLAliasService.php.
    {
        foreach ( $pathElementData["translations"] as $languageCode => $translation )
        {
            if ( strtolower( $pathElement ) === strtolower( $translation ) )
            {
                return $languageCode;
            }
        }
        return false;
    }
eZ\Publish\Core\Repository\URLAliasService::matchPath (SPIURLAlias $spiUrlAlias, $path, $languageCode) protected
Matches path string with normalized path data returned from persistence.
Returns matched path string (possibly case corrected) and array of corresponding language codes or false if path could not be matched.
Parameters
\eZ\Publish\SPI\Persistence\Content\URLAlias $spiUrlAlias
string $path
string $languageCode
Returns
array
Definition at line 341 of file URLAliasService.php.
References eZ\Publish\Core\Repository\URLAliasService\matchLanguageCode(), and eZ\Publish\Core\Repository\URLAliasService\selectAliasLanguageCode().
    {
        $matchedPathElements = array();
        $matchedPathLanguageCodes = array();
        $pathElements = explode( "/", $path );
        $pathLevels = count( $spiUrlAlias->pathData );
        foreach ( $pathElements as $level => $pathElement )
        {
            if ( $level === $pathLevels - 1 )
            {
                $matchedLanguageCode = $this->selectAliasLanguageCode( $spiUrlAlias, $languageCode );
            }
            else
            {
                $matchedLanguageCode = $this->matchLanguageCode( $spiUrlAlias->pathData[$level], $pathElement );
            }
            if ( $matchedLanguageCode === false )
            {
                return array( false, false );
            }
            $matchedPathLanguageCodes[] = $matchedLanguageCode;
            $matchedPathElements[] = $spiUrlAlias->pathData[$level]["translations"][$matchedLanguageCode];
        }
        return array( implode( "/", $matchedPathElements ), $matchedPathLanguageCodes );
    }
eZ\Publish\Core\Repository\URLAliasService::removeAliases (array $aliasList)
Removes urls aliases.
This method does not remove autogenerated aliases for locations.
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if alias list contains autogenerated alias
Parameters
\eZ\Publish\API\Repository\Values\Content\URLAlias[] $aliasList
Returns
void
Implements eZ\Publish\API\Repository\URLAliasService.
Definition at line 508 of file URLAliasService.php.
References eZ\Publish\Core\Repository\URLAliasService\buildSPIUrlAlias().
    {
        $spiUrlAliasList = array();
        foreach ( $aliasList as $alias )
        {
            if ( !$alias->isCustom )
            {
                throw new InvalidArgumentException(
                    "\$aliasList",
                    "Alias list contains autogenerated alias"
                );
            }
            $spiUrlAliasList[] = $this->buildSPIUrlAlias( $alias );
        }
        $this->repository->beginTransaction();
        try
        {
            $this->urlAliasHandler->removeURLAliases( $spiUrlAliasList );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\URLAliasService::reverseLookup (Location $location, $languageCode = null)
Returns the URL alias for the given location in the given language.
If $languageCode is null the method returns the url alias in the most prioritized language.
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if no url alias exist for the given language
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location
string $languageCode
Returns
Implements eZ\Publish\API\Repository\URLAliasService.
Definition at line 590 of file URLAliasService.php.
References eZ\Publish\Core\Repository\URLAliasService\listLocationAliases().
    {
        $urlAliases = $this->listLocationAliases( $location, false, $languageCode );
        foreach ( $this->settings["prioritizedLanguageList"] as $prioritizedLanguageCode )
        {
            foreach ( $urlAliases as $urlAlias )
            {
                if ( in_array( $prioritizedLanguageCode, $urlAlias->languageCodes ) )
                {
                    return $urlAlias;
                }
            }
        }
        foreach ( $urlAliases as $urlAlias )
        {
            if ( $urlAlias->alwaysAvailable )
            {
                return $urlAlias;
            }
        }
        throw new NotFoundException( "URLAlias", $location->id );
    }
eZ\Publish\Core\Repository\URLAliasService::selectAliasLanguageCode (SPIURLAlias $spiUrlAlias, $languageCode) protected
Determines alias language code.
Method will return false if language code can't be matched against alias language codes or language settings.
Parameters
\eZ\Publish\SPI\Persistence\Content\URLAlias $spiUrlAlias
string | null $languageCode
Returns
string|boolean
Definition at line 241 of file URLAliasService.php.
    {
        if ( isset( $languageCode ) && !in_array( $languageCode, $spiUrlAlias->languageCodes ) )
        {
            return false;
        }
        foreach ( $this->settings["prioritizedLanguageList"] as $languageCode )
        {
            if ( in_array( $languageCode, $spiUrlAlias->languageCodes ) )
            {
                return $languageCode;
            }
        }
        if ( $spiUrlAlias->alwaysAvailable || $this->settings["showAllTranslations"] )
        {
            $lastLevelData = end( $spiUrlAlias->pathData );
            return key( $lastLevelData["translations"] );
        }
        return false;
    }
Member Data Documentation
eZ\Publish\Core\Repository\URLAliasService::$repository protected
Definition at line 36 of file URLAliasService.php.
eZ\Publish\Core\Repository\URLAliasService::$settings protected
Definition at line 46 of file URLAliasService.php.
eZ\Publish\Core\Repository\URLAliasService::$urlAliasHandler protected
Definition at line 41 of file URLAliasService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/URLAliasService.php