ezp-next: eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage Class Reference
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage Class Reference
Public Member Functions
setConnection ($dbHandler)
storeFieldData (VersionInfo $versionInfo, Field $field)
getFieldData (VersionInfo $versionInfo, Field $field)
deleteFieldData (VersionInfo $versionInfo, array $fieldIds)
Protected Member Functions
getConnection ()
updateFieldData (VersionInfo $versionInfo, Field $field)
storeNewFieldData (VersionInfo $versionInfo, Field $field)
loadFieldData ($fieldId, $versionNo)
hasFieldData ($fieldId, $versionNo)
Protected Attributes
$dbHandler
Detailed Description
Definition at line 15 of file LegacyStorage.php.
Member Function Documentation
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage::deleteFieldData (VersionInfo $versionInfo, array $fieldIds)
Deletes the data for all given $fieldIds
Parameters
VersionInfo $versionInfo
array $fieldIds
Returns
void
Reimplemented from eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway.
Definition at line 251 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\getConnection().
    {
        if ( empty( $fieldIds ) )
        {
            // Nothing to do
            return;
        }
        $connection = $this->getConnection();
        $deleteQuery = $connection->createDeleteQuery();
        $deleteQuery->deleteFrom(
            $connection->quoteTable( 'ezgmaplocation' )
        )->where(
            $deleteQuery->expr->lAnd(
                $deleteQuery->expr->in(
                    $connection->quoteColumn( 'contentobject_attribute_id' ),
                    $fieldIds
                ),
                $deleteQuery->expr->eq(
                    $connection->quoteColumn( 'contentobject_version' ),
                    $deleteQuery->bindValue( $versionInfo->versionNo, null, \PDO::PARAM_INT )
                )
            )
        );
        $deleteQuery->prepare()->execute();
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage::getConnection () protected
Returns the active connection
Exceptions
\RuntimeException if no connection has been set, yet.
Returns
Definition at line 54 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\getConnection().
    {
        if ( $this->dbHandler === null )
        {
            throw new \RuntimeException( "Missing database connection." );
        }
        return $this->dbHandler;
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage::getFieldData (VersionInfo $versionInfo, Field $field)
Sets the loaded field data into $field->externalData.
Parameters
VersionInfo $versionInfo
Field $field
Returns
array
Reimplemented from eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway.
Definition at line 184 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\loadFieldData().
    {
        $field->value->externalData = $this->loadFieldData( $field->id, $versionInfo->versionNo );
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage::hasFieldData ($fieldId, $versionNo) protected
Returns if field data exists for $fieldId
Parameters
int $fieldId
int $versionNo
Returns
boolean
Definition at line 238 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\loadFieldData().
    {
        return ( $this->loadFieldData( $fieldId, $versionNo ) !== null );
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage::loadFieldData ($fieldId, $versionNo) protected
Returns the data for the given $fieldId
If no data is found, null is returned.
Parameters
int $fieldId
Returns
array|null
Definition at line 198 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\loadFieldData().
    {
        $connection = $this->getConnection();
        $selectQuery = $connection->createSelectQuery();
        $selectQuery->select(
            $connection->quoteColumn( 'latitude' ),
            $connection->quoteColumn( 'longitude' ),
            $connection->quoteColumn( 'address' )
        )->from(
            $connection->quoteTable( 'ezgmaplocation' )
        )->where(
            $selectQuery->expr->lAnd(
                $selectQuery->expr->eq(
                    $connection->quoteColumn( 'contentobject_attribute_id' ),
                    $selectQuery->bindValue( $fieldId, null, \PDO::PARAM_INT )
                ),
                $selectQuery->expr->eq(
                    $connection->quoteColumn( 'contentobject_version' ),
                    $selectQuery->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $selectQuery->prepare();
        $statement->execute();
        $rows = $statement->fetchAll( \PDO::FETCH_ASSOC );
        return ( isset( $rows[0] ) ? $rows[0] : null );
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage::setConnection ($dbHandler)
Set database handler for this gateway
Parameters
mixed $dbHandler
Returns
void
Exceptions
\RuntimeException if $dbHandler is not an instance of eZ\Publish\Core\Persistence\Legacy\EzcDbHandler
Reimplemented from eZ\Publish\Core\FieldType\StorageGateway.
Definition at line 33 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\$dbHandler, and eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\setConnection().
    {
        // This obviously violates the Liskov substitution Principle, but with
        // the given class design there is no sane other option. Actually the
        // dbHandler *should* be passed to the constructor, and there should
        // not be the need to post-inject it.
        if ( !$dbHandler instanceof \eZ\Publish\Core\Persistence\Legacy\EzcDbHandler )
        {
            throw new \RuntimeException( "Invalid dbHandler passed" );
        }
        $this->dbHandler = $dbHandler;
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage::storeFieldData (VersionInfo $versionInfo, Field $field)
Stores the data stored in the given $field
Potentially rewrites data in $field and returns true, if the $field needs to be updated in the database.
Parameters
VersionInfo $versionInfo
Field $field
Returns
boolean If restoring of the internal field data is required
Reimplemented from eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway.
Definition at line 74 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\deleteFieldData(), eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\hasFieldData(), eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\storeNewFieldData(), and eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\updateFieldData().
    {
        if ( $field->value->externalData === null )
        {
            // Store empty value and return
            $this->deleteFieldData( $versionInfo, array( $field->id ) );
            $field->value->data = array(
                'sortKey' => null,
                'hasData' => false,
            );
            return;
        }
        if ( $this->hasFieldData( $field->id, $versionInfo->versionNo ) )
        {
            $this->updateFieldData( $versionInfo, $field );
        }
        else
        {
            $this->storeNewFieldData( $versionInfo, $field );
        }
        $field->value->data = array(
            'sortKey' => $field->value->externalData['address'],
            'hasData' => true,
        );
        return true;
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage::storeNewFieldData (VersionInfo $versionInfo, Field $field) protected
Stores new field data
Parameters
VersionInfo $versionInfo
Field $field
Returns
void
Definition at line 150 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\storeNewFieldData().
    {
        $connection = $this->getConnection();
        $insertQuery = $connection->createInsertQuery();
        $insertQuery->insertInto( $connection->quoteTable( 'ezgmaplocation' ) )
            ->set(
                $connection->quoteColumn( 'latitude' ),
                $insertQuery->bindValue( $field->value->externalData['latitude'] )
            )->set(
                $connection->quoteColumn( 'longitude' ),
                $insertQuery->bindValue( $field->value->externalData['longitude'] )
            )->set(
                $connection->quoteColumn( 'address' ),
                $insertQuery->bindValue( $field->value->externalData['address'] )
            )->set(
                $connection->quoteColumn( 'contentobject_attribute_id' ),
                $insertQuery->bindValue( $field->id, null, \PDO::PARAM_INT )
            )->set(
                $connection->quoteColumn( 'contentobject_version' ),
                $insertQuery->bindValue( $versionInfo->versionNo, null, \PDO::PARAM_INT )
            );
        $insertQuery->prepare()->execute();
    }
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage::updateFieldData (VersionInfo $versionInfo, Field $field) protected
Performs an update on the field data
Parameters
VersionInfo $versionInfo
Field $field
Returns
boolean
Definition at line 111 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage\updateFieldData().
    {
        $connection = $this->getConnection();
        $updateQuery = $connection->createUpdateQuery();
        $updateQuery->update( $connection->quoteTable( 'ezgmaplocation' ) )
            ->set(
                $connection->quoteColumn( 'latitude' ),
                $updateQuery->bindValue( $field->value->externalData['latitude'] )
            )->set(
                $connection->quoteColumn( 'longitude' ),
                $updateQuery->bindValue( $field->value->externalData['longitude'] )
            )->set(
                $connection->quoteColumn( 'address' ),
                $updateQuery->bindValue( $field->value->externalData['address'] )
            )->where(
                $updateQuery->expr->lAnd(
                    $updateQuery->expr->eq(
                        $connection->quoteColumn( 'contentobject_attribute_id' ),
                        $updateQuery->bindValue( $field->id, null, \PDO::PARAM_INT )
                    ),
                    $updateQuery->expr->eq(
                        $connection->quoteColumn( 'contentobject_version' ),
                        $updateQuery->bindValue( $versionInfo->versionNo, null, \PDO::PARAM_INT )
                    )
                )
            );
        $updateQuery->prepare()->execute();
    }
Member Data Documentation
eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage::$dbHandler protected
Definition at line 22 of file LegacyStorage.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/MapLocation/MapLocationStorage/Gateway/LegacyStorage.php