ezp-next: eZ\Publish\Core\FieldType\Time\Type Class Reference
eZ\Publish\Core\FieldType\Time\Type Class Reference
Public Member Functions
getFieldTypeIdentifier ()
getName ($value)
getEmptyValue ()
fromHash ($hash)
toHash ($value)
isSearchable ()
validateFieldSettings ($fieldSettings)
Public Member Functions inherited from eZ\Publish\Core\FieldType\FieldType
getSettingsSchema ()
getValidatorConfigurationSchema ()
validate (FieldDefinition $fieldDefinition, $fieldValue)
validateValidatorConfiguration ($validatorConfiguration)
toPersistenceValue ($value)
fromPersistenceValue (FieldValue $fieldValue)
isEmptyValue ($value)
acceptValue ($inputValue)
fieldSettingsToHash ($fieldSettings)
fieldSettingsFromHash ($fieldSettingsHash)
validatorConfigurationToHash ($validatorConfiguration)
validatorConfigurationFromHash ($validatorConfigurationHash)
getRelations ($fieldValue)
Public Attributes
const DEFAULT_EMPTY = 0
const DEFAULT_CURRENT_TIME = 1
Protected Member Functions
internalAcceptValue ($inputValue)
getSortInfo ($value)
Protected Attributes
$settingsSchema
Protected Attributes inherited from eZ\Publish\Core\FieldType\FieldType
$settingsSchema = array()
$validatorConfigurationSchema = array()
Detailed Description
Definition at line 17 of file Type.php.
Member Function Documentation
eZ\Publish\Core\FieldType\Time\Type::fromHash ($hash)
Converts an $hash to the Value defined by the field type
Parameters
int $hash Number of seconds since Unix Epoch
Returns
$value
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 149 of file Type.php.
    {
        if ( $hash === null )
        {
            return null;
        }
        return new Value( $hash );
    }
eZ\Publish\Core\FieldType\Time\Type::getEmptyValue ()
Returns the fallback default value of field type when no such default value is provided in the field definition in content types.
Returns
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 78 of file Type.php.
    {
        return new Value;
    }
eZ\Publish\Core\FieldType\Time\Type::getFieldTypeIdentifier ()
Returns the field type identifier for this field type
Returns
string
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 46 of file Type.php.
    {
        return "eztime";
    }
eZ\Publish\Core\FieldType\Time\Type::getName ($value)
Returns the name of the given field value.
It will be used to generate content name and url alias if current field is designated to be used in the content name/urlAlias pattern.
Parameters
mixed $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 61 of file Type.php.
    {
        if ( $value === null )
        {
            return '';
        }
        $dateTime = new DateTime( "@{$value->time}" );
        return $dateTime->format( 'g:i:s a' );
    }
eZ\Publish\Core\FieldType\Time\Type::getSortInfo ($value) protected
Returns information for FieldValue->$sortKey relevant to the field type.
Parameters
\eZ\Publish\Core\FieldType\Time\Value $value
Returns
array
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 132 of file Type.php.
    {
        if ( $value === null || $value->time === null )
        {
            return null;
        }
        return $value->time;
    }
eZ\Publish\Core\FieldType\Time\Type::internalAcceptValue ($inputValue) protected
Implements the core of {
See Also
acceptValue()}.
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 90 of file Type.php.
References eZ\Publish\Core\FieldType\Time\Value\fromDateTime(), eZ\Publish\Core\FieldType\Time\Value\fromString(), and eZ\Publish\Core\FieldType\Time\Value\fromTimestamp().
    {
        if ( is_string( $inputValue ) )
        {
            $inputValue = Value::fromString( $inputValue );
        }
        if ( is_int( $inputValue ) )
        {
            $inputValue = Value::fromTimestamp( $inputValue );
        }
        if ( $inputValue instanceof DateTime )
        {
            $inputValue = Value::fromDateTime( $inputValue );
        }
        else if ( !$inputValue instanceof Value )
        {
            throw new InvalidArgumentType(
                '$inputValue',
                'eZ\\Publish\\Core\\FieldType\\Time\\Value',
                $inputValue
            );
        }
        if ( isset( $inputValue->time ) && !is_int( $inputValue->time ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->time',
                'DateTime',
                $inputValue->time
            );
        }
        return $inputValue;
    }
eZ\Publish\Core\FieldType\Time\Type::isSearchable ()
Returns whether the field type is searchable
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 181 of file Type.php.
    {
        return true;
    }
eZ\Publish\Core\FieldType\Time\Type::toHash ($value)
Converts a $Value to a hash
Parameters
\eZ\Publish\Core\FieldType\Time\Value $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 166 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\isEmptyValue().
    {
        if ( $this->isEmptyValue( $value ) )
        {
            return null;
        }
        return $value->time;
    }
eZ\Publish\Core\FieldType\Time\Type::validateFieldSettings ($fieldSettings)
Validates the fieldSettings of a FieldDefinitionCreateStruct or FieldDefinitionUpdateStruct
Parameters
mixed $fieldSettings
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 193 of file Type.php.
    {
        $validationErrors = array();
        foreach ( $fieldSettings as $name => $value )
        {
            if ( !isset( $this->settingsSchema[$name] ) )
            {
                $validationErrors[] = new ValidationError(
                    "Setting '%setting%' is unknown",
                    null,
                    array(
                        "setting" => $name
                    )
                );
            }
            switch ( $name )
            {
                case "useSeconds":
                    if ( !is_bool( $value ) )
                    {
                        $validationErrors[] = new ValidationError(
                            "Setting '%setting%' value must be of boolean type",
                            null,
                            array(
                                "setting" => $name
                            )
                        );
                    }
                    break;
                case "defaultType":
                    $definedTypes = array(
                        self::DEFAULT_EMPTY,
                        self::DEFAULT_CURRENT_TIME
                    );
                    if ( !in_array( $value, $definedTypes ) )
                    {
                        $validationErrors[] = new ValidationError(
                            "Setting '%setting%' is of unknown type",
                            null,
                            array(
                                "setting" => $name
                            )
                        );
                    }
                    break;
            }
        }
        return $validationErrors;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\Time\Type::$settingsSchema protected
Initial value:
 array(
        "useSeconds" => array(
            "type" => "bool",
            "default" => false
        ),
        "defaultType" => array(
            "type" => "choice",
            "default" => self::DEFAULT_EMPTY
        )
    )
Definition at line 29 of file Type.php.
const eZ\Publish\Core\FieldType\Time\Type::DEFAULT_CURRENT_TIME = 1
Default value type current date
Definition at line 27 of file Type.php.
const eZ\Publish\Core\FieldType\Time\Type::DEFAULT_EMPTY = 0
Default value type empty
Definition at line 22 of file Type.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Time/Type.php