ezp-next: eZ\Publish\Core\Persistence\Legacy\Handler Class Reference
eZ\Publish\Core\Persistence\Legacy\Handler Class Reference
Public Member Functions
__construct (EzcDbHandler $dbHandler, FieldTypeRegistry $fieldTypeRegistry, ConverterRegistry $converterRegistry, StorageRegistry $storageRegistry, TransformationProcessor $transformationProcessor, array $config=array())
contentHandler ()
getFieldValueConverterRegistry ()
getStorageRegistry ()
getFieldTypeRegistry ()
searchHandler ()
contentTypeHandler ()
contentLanguageHandler ()
locationHandler ()
objectStateHandler ()
userHandler ()
sectionHandler ()
trashHandler ()
urlAliasHandler ()
urlWildcardHandler ()
beginTransaction ()
commit ()
rollback ()
Protected Member Functions
getContentMapper ()
getContentGateway ()
getFieldHandler ()
getLanguageMaskGenerator ()
getStorageHandler ()
getTypeUpdateHandler ()
getContentTypeGateway ()
getLanguageCache ()
getLocationGateway ()
getLocationMapper ()
getObjectStateGateway ()
getObjectStateMapper ()
getUrlAliasGateway ()
getUrlAliasMapper ()
getSlugConverter ()
getUrlWildcardGateway ()
getUrlWildcardMapper ()
Protected Attributes
$contentHandler
$contentMapper
$storageHandler
$fieldHandler
$searchHandler
$contentTypeHandler
$contentTypeGateway
$typeUpdateHandler
$locationHandler
$locationGateway
$locationMapper
$objectStateHandler
$objectStateGateway
$objectStateMapper
$userHandler
$sectionHandler
$trashHandler
$contentGateway
$languageHandler
$languageCache
$languageMaskGenerator
$urlAliasHandler
$urlAliasGateway
$urlAliasMapper
$urlWildcardHandler
$urlWildcardGateway
$urlWildcardMapper
$dbHandler
$converterRegistry
$storageRegistry
$fieldTypeRegistry
$transformationProcessor
$config
Detailed Description
The repository handler for the legacy storage engine
Definition at line 47 of file Handler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Handler::__construct (EzcDbHandler $dbHandler, FieldTypeRegistry $fieldTypeRegistry, ConverterRegistry $converterRegistry, StorageRegistry $storageRegistry, TransformationProcessor $transformationProcessor, array $config = array())
Creates a new repository handler.
Parameters
\eZ\Publish\Core\Persistence\Legacy\EzcDbHandler $dbHandler The database handler
\eZ\Publish\Core\Persistence\FieldTypeRegistry $fieldTypeRegistry Should contain field types
Content\FieldValue\ConverterRegistry $converterRegistry Should contain Field Type converters
Content\StorageRegistry $storageRegistry Should contain Field Type external storage handlers
\eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor $transformationProcessor Search Text Transformation processor
array $config List of optional configuration flags: The flag 'defer_type_update' defines if content types should be published immediately (false), when the eZ\Publish\SPI\Persistence\Content\Type\Handler::publish()methodiscalled,orifabackgroundprocessshouldbetriggered(true),whichisthenexecutedbytheoldeZPublishcore.
Definition at line 293 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\$config.
    {
        $this->dbHandler = $dbHandler;
        $this->fieldTypeRegistry = $fieldTypeRegistry;
        $this->converterRegistry = $converterRegistry;
        $this->storageRegistry = $storageRegistry;
        $this->transformationProcessor = $transformationProcessor;
        $this->config = $config;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Handler::beginTransaction ()
Begin transaction
Begins an transaction, make sure you'll call commit or rollback when done, otherwise work will be lost.
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 896 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\beginTransaction().
    {
        $this->dbHandler->beginTransaction();
    }
eZ\Publish\Core\Persistence\Legacy\Handler::commit ()
Commit transaction
Commit transaction, or throw exceptions if no transactions has been started.
Exceptions
\RuntimeException If no transaction has been started
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 908 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\commit().
    {
        try
        {
            $this->dbHandler->commit();
        }
        catch ( ezcDbTransactionException $e )
        {
            throw new RuntimeException( $e->getMessage() );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Handler::contentHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 315 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\contentHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getContentGateway(), eZ\Publish\Core\Persistence\Legacy\Handler\getContentMapper(), eZ\Publish\Core\Persistence\Legacy\Handler\getFieldHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getLocationGateway(), eZ\Publish\Core\Persistence\Legacy\Handler\getSlugConverter(), eZ\Publish\Core\Persistence\Legacy\Handler\getUrlAliasGateway(), and eZ\Publish\Core\Persistence\Legacy\Handler\locationHandler().
    {
        if ( !isset( $this->contentHandler ) )
        {
            $this->contentHandler = new ContentHandler(
                $this->getContentGateway(),
                $this->getLocationGateway(),
                $this->getContentMapper(),
                $this->getFieldHandler(),
                $this->getSlugConverter(),
                $this->getUrlAliasGateway()
            );
            $this->contentHandler->locationHandler = $this->locationHandler();
        }
        return $this->contentHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::contentLanguageHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 596 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\contentLanguageHandler(), and eZ\Publish\Core\Persistence\Legacy\Handler\getLanguageCache().
    {
        if ( !isset( $this->languageHandler ) )
        {
            $this->languageHandler = new Content\Language\CachingHandler(
                new Content\Language\Handler(
                    new Content\Language\Gateway\ExceptionConversion(
                        new Content\Language\Gateway\EzcDatabase( $this->dbHandler )
                    ),
                    new LanguageMapper()
                ),
                $this->getLanguageCache()
            );
        }
        return $this->languageHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::contentTypeHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 528 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\contentTypeHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getContentTypeGateway(), and eZ\Publish\Core\Persistence\Legacy\Handler\getTypeUpdateHandler().
    {
        if ( !isset( $this->contentTypeHandler ) )
        {
            $this->contentTypeHandler = new Content\Type\MemoryCachingHandler(
                new TypeHandler(
                    $this->getContentTypeGateway(),
                    new TypeMapper( $this->converterRegistry ),
                    $this->getTypeUpdateHandler()
                )
            );
        }
        return $this->contentTypeHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getContentGateway () protected
Returns a content gateway
Returns
Definition at line 354 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\$contentGateway, eZ\Publish\Core\Persistence\Legacy\Handler\contentLanguageHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getContentGateway(), and eZ\Publish\Core\Persistence\Legacy\Handler\getLanguageMaskGenerator().
    {
        if ( !isset( $this->contentGateway ) )
        {
            $this->contentGateway = new Content\Gateway\ExceptionConversion(
                new Content\Gateway\EzcDatabase(
                    $this->dbHandler,
                    new Content\Gateway\EzcDatabase\QueryBuilder( $this->dbHandler ),
                    $this->contentLanguageHandler(),
                    $this->getLanguageMaskGenerator()
                )
            );
        }
        return $this->contentGateway;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getContentMapper () protected
Returns a content mapper
Returns
Definition at line 337 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\contentLanguageHandler(), and eZ\Publish\Core\Persistence\Legacy\Handler\getContentMapper().
    {
        if ( !isset( $this->contentMapper ) )
        {
            $this->contentMapper = new ContentMapper(
                $this->converterRegistry,
                $this->contentLanguageHandler()
            );
        }
        return $this->contentMapper;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getContentTypeGateway () protected
Returns the content type gateway
Returns
Definition at line 579 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getContentTypeGateway(), and eZ\Publish\Core\Persistence\Legacy\Handler\getLanguageMaskGenerator().
    {
        if ( !isset( $this->contentTypeGateway ) )
        {
            $this->contentTypeGateway = new Type\Gateway\ExceptionConversion(
                new Type\Gateway\EzcDatabase(
                    $this->dbHandler,
                    $this->getLanguageMaskGenerator()
                )
            );
        }
        return $this->contentTypeGateway;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getFieldHandler () protected
Returns a field handler
Returns
Definition at line 375 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\$fieldHandler, eZ\Publish\Core\Persistence\Legacy\Handler\contentLanguageHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\contentTypeHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getContentGateway(), eZ\Publish\Core\Persistence\Legacy\Handler\getContentMapper(), eZ\Publish\Core\Persistence\Legacy\Handler\getFieldHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getFieldTypeRegistry(), and eZ\Publish\Core\Persistence\Legacy\Handler\getStorageHandler().
    {
        if ( !isset( $this->fieldHandler ) )
        {
            $this->fieldHandler = new ContentFieldHandler(
                $this->getContentGateway(),
                $this->getContentMapper(),
                $this->getStorageHandler(),
                $this->contentLanguageHandler(),
                $this->getFieldTypeRegistry()
            );
            $this->fieldHandler->typeHandler = $this->contentTypeHandler();
        }
        return $this->fieldHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getFieldTypeRegistry ()
Returns the field type registry
Returns
Definition at line 432 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getFieldTypeRegistry().
    {
        return $this->fieldTypeRegistry;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getFieldValueConverterRegistry ()
Returns the field value converter registry
Returns
Definition at line 412 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getFieldValueConverterRegistry().
    {
        return $this->converterRegistry;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getLanguageCache () protected
Returns a Language cache
Returns
Definition at line 618 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getLanguageCache().
    {
        if ( !isset( $this->languageCache ) )
        {
            $this->languageCache = new Content\Language\Cache();
        }
        return $this->languageCache;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getLanguageMaskGenerator () protected
Returns a language mask generator
Returns
Definition at line 396 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\contentLanguageHandler(), and eZ\Publish\Core\Persistence\Legacy\Handler\getLanguageMaskGenerator().
    {
        if ( !isset( $this->languageMaskGenerator ) )
        {
            $this->languageMaskGenerator = new Content\Language\MaskGenerator(
                $this->contentLanguageHandler()
            );
        }
        return $this->languageMaskGenerator;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getLocationGateway () protected
Returns a location gateway
Returns
Definition at line 649 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\$locationGateway, and eZ\Publish\Core\Persistence\Legacy\Handler\getLocationGateway().
    {
        if ( !isset( $this->locationGateway ) )
        {
            $this->locationGateway = new Content\Location\Gateway\ExceptionConversion(
                new Content\Location\Gateway\EzcDatabase( $this->dbHandler )
            );
        }
        return $this->locationGateway;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getLocationMapper () protected
Returns a location mapper
Returns
Definition at line 665 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getLocationMapper().
    {
        if ( !isset( $this->locationMapper ) )
        {
            $this->locationMapper = new LocationMapper();
        }
        return $this->locationMapper;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getObjectStateGateway () protected
Returns an object state gateway
Returns
Definition at line 694 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getLanguageMaskGenerator(), and eZ\Publish\Core\Persistence\Legacy\Handler\getObjectStateGateway().
    {
        if ( !isset( $this->objectStateGateway ) )
        {
            $this->objectStateGateway = new Content\ObjectState\Gateway\ExceptionConversion(
                new Content\ObjectState\Gateway\EzcDatabase(
                    $this->dbHandler,
                    $this->getLanguageMaskGenerator()
                )
            );
        }
        return $this->objectStateGateway;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getObjectStateMapper () protected
Returns an object state mapper
Returns
Definition at line 713 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\contentLanguageHandler(), and eZ\Publish\Core\Persistence\Legacy\Handler\getObjectStateMapper().
    {
        if ( !isset( $this->objectStateMapper ) )
        {
            $this->objectStateMapper = new ObjectStateMapper(
                $this->contentLanguageHandler()
            );
        }
        return $this->objectStateMapper;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getSlugConverter () protected
Returns a slug converter
Returns
Definition at line 835 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\$slugConverter, and eZ\Publish\Core\Persistence\Legacy\Handler\getSlugConverter().
    {
        if ( !isset( $this->slugConverter ) )
        {
            $this->slugConverter = new SlugConverter(
                $this->transformationProcessor
            );
        }
        return $this->slugConverter;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getStorageHandler () protected
Returns a storage handler
Returns
Definition at line 442 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getContentGateway(), and eZ\Publish\Core\Persistence\Legacy\Handler\getStorageHandler().
    {
        if ( !isset( $this->storageHandler ) )
        {
            $this->storageHandler = new StorageHandler(
                $this->storageRegistry,
                $this->getContentGateway()->getContext()
            );
        }
        return $this->storageHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getStorageRegistry ()
Returns the storage registry
Returns
Content
Definition at line 422 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getStorageRegistry().
    {
        return $this->storageRegistry;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getTypeUpdateHandler () protected
Returns a Content Type update handler
Returns
Definition at line 548 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getContentGateway(), eZ\Publish\Core\Persistence\Legacy\Handler\getContentTypeGateway(), eZ\Publish\Core\Persistence\Legacy\Handler\getStorageHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getTypeUpdateHandler(), and eZ\Publish\Core\Persistence\Legacy\Handler\searchHandler().
    {
        if ( !isset( $this->typeUpdateHandler ) )
        {
            if ( isset( $this->config['defer_type_update'] ) && $this->config['defer_type_update'] )
            {
                $this->typeUpdateHandler = new Type\Update\Handler\DeferredLegacy(
                    $this->getContentGateway()
                );
            }
            else
            {
                $this->typeUpdateHandler = new Type\Update\Handler\EzcDatabase(
                    $this->getContentTypeGateway(),
                    new Type\ContentUpdater(
                        $this->searchHandler(),
                        $this->getContentGateway(),
                        $this->converterRegistry,
                        $this->getStorageHandler()
                    )
                );
            }
        }
        return $this->typeUpdateHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getUrlAliasGateway () protected
Returns a UrlAlias gateway
Returns
Definition at line 800 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\$urlAliasGateway, eZ\Publish\Core\Persistence\Legacy\Handler\getLanguageMaskGenerator(), and eZ\Publish\Core\Persistence\Legacy\Handler\getUrlAliasGateway().
    {
        if ( !isset( $this->urlAliasGateway ) )
        {
            $this->urlAliasGateway = new UrlAliasExceptionConversionGateway(
                new UrlAliasGateway(
                    $this->dbHandler,
                    $this->getLanguageMaskGenerator()
                )
            );
        }
        return $this->urlAliasGateway;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getUrlAliasMapper () protected
Returns a UrlAlias mapper
Returns
Definition at line 819 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getLanguageMaskGenerator(), and eZ\Publish\Core\Persistence\Legacy\Handler\getUrlAliasMapper().
    {
        if ( !isset( $this->urlAliasMapper ) )
        {
            $this->urlAliasMapper = new UrlAliasMapper(
                $this->getLanguageMaskGenerator()
            );
        }
        return $this->urlAliasMapper;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getUrlWildcardGateway () protected
Returns a UrlWildcard gateway
Returns
Definition at line 867 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getUrlWildcardGateway().
    {
        if ( !isset( $this->urlWildcardGateway ) )
        {
            $this->urlWildcardGateway = new UrlWildcardGateway( $this->dbHandler );
        }
        return $this->urlWildcardGateway;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::getUrlWildcardMapper () protected
Returns a UrlWildcard mapper
Returns
Definition at line 881 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getUrlWildcardMapper().
    {
        if ( !isset( $this->urlWildcardMapper ) )
        {
            $this->urlWildcardMapper = new UrlWildcardMapper();
        }
        return $this->urlWildcardMapper;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::locationHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 630 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\$locationHandler, eZ\Publish\Core\Persistence\Legacy\Handler\contentHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getContentMapper(), eZ\Publish\Core\Persistence\Legacy\Handler\getLocationGateway(), eZ\Publish\Core\Persistence\Legacy\Handler\getLocationMapper(), and eZ\Publish\Core\Persistence\Legacy\Handler\locationHandler().
    {
        if ( !isset( $this->locationHandler ) )
        {
            $this->locationHandler = new LocationHandler(
                $this->getLocationGateway(),
                $this->getLocationMapper(),
                $this->contentHandler(),
                $this->getContentMapper()
            );
        }
        return $this->locationHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::objectStateHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 677 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getObjectStateGateway(), eZ\Publish\Core\Persistence\Legacy\Handler\getObjectStateMapper(), and eZ\Publish\Core\Persistence\Legacy\Handler\objectStateHandler().
    {
        if ( !isset( $this->objectStateHandler ) )
        {
            $this->objectStateHandler = new ObjectStateHandler(
                $this->getObjectStateGateway(),
                $this->getObjectStateMapper()
            );
        }
        return $this->objectStateHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::rollback ()
Rollback transaction
Rollback transaction, or throw exceptions if no transactions has been started.
Exceptions
\RuntimeException If no transaction has been started
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 927 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\contentTypeHandler(), and eZ\Publish\Core\Persistence\Legacy\Handler\rollback().
    {
        try
        {
            $this->dbHandler->rollback();
            // Clear all caches after rollback
            if ( isset( $this->contentTypeHandler ) )
                $this->contentTypeHandler->clearCache();
            if ( isset( $this->languageHandler ) )
                $this->languageHandler->clearCache();
        }
        catch ( ezcDbTransactionException $e )
        {
            throw new RuntimeException( $e->getMessage() );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Handler::searchHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 457 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\contentLanguageHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getContentMapper(), eZ\Publish\Core\Persistence\Legacy\Handler\getFieldHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getLanguageMaskGenerator(), and eZ\Publish\Core\Persistence\Legacy\Handler\searchHandler().
    {
        if ( !isset( $this->searchHandler ) )
        {
            $db = $this->dbHandler;
            $this->searchHandler = new Content\Search\Handler(
                new Content\Search\Gateway\ExceptionConversion(
                    new Content\Search\Gateway\EzcDatabase(
                        $db,
                        new Content\Search\Gateway\CriteriaConverter(
                            array(
                                new CriterionHandler\ContentId( $db ),
                                new CriterionHandler\LogicalNot( $db ),
                                new CriterionHandler\LogicalAnd( $db ),
                                new CriterionHandler\LogicalOr( $db ),
                                new CriterionHandler\Subtree( $db ),
                                new CriterionHandler\ContentTypeId( $db ),
                                new CriterionHandler\ContentTypeIdentifier( $db ),
                                new CriterionHandler\ContentTypeGroupId( $db ),
                                new CriterionHandler\DateMetadata( $db ),
                                new CriterionHandler\LocationId( $db ),
                                new CriterionHandler\ParentLocationId( $db ),
                                new CriterionHandler\RemoteId( $db ),
                                new CriterionHandler\LocationRemoteId( $db ),
                                new CriterionHandler\SectionId( $db ),
                                new CriterionHandler\Status( $db ),
                                new CriterionHandler\FullText(
                                    $db,
                                    $this->transformationProcessor
                                ),
                                new CriterionHandler\Field(
                                    $db,
                                    $this->converterRegistry
                                ),
                                new CriterionHandler\ObjectStateId( $db ),
                                new CriterionHandler\LanguageCode(
                                    $db,
                                    $this->getLanguageMaskGenerator()
                                ),
                                new CriterionHandler\Visibility( $db ),
                            )
                        ),
                        new Content\Search\Gateway\SortClauseConverter(
                            array(
                                new SortClauseHandler\LocationPathString( $db ),
                                new SortClauseHandler\LocationDepth( $db ),
                                new SortClauseHandler\LocationPriority( $db ),
                                new SortClauseHandler\DateModified( $db ),
                                new SortClauseHandler\DatePublished( $db ),
                                new SortClauseHandler\SectionIdentifier( $db ),
                                new SortClauseHandler\SectionName( $db ),
                                new SortClauseHandler\ContentName( $db ),
                                new SortClauseHandler\ContentId( $db ),
                                new SortClauseHandler\Field( $db ),
                            )
                        ),
                        new Content\Gateway\EzcDatabase\QueryBuilder( $this->dbHandler ),
                        $this->contentLanguageHandler(),
                        $this->getLanguageMaskGenerator()
                    )
                ),
                $this->getContentMapper(),
                $this->getFieldHandler()
            );
        }
        return $this->searchHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::sectionHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 745 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\sectionHandler().
    {
        if ( !isset( $this->sectionHandler ) )
        {
            $this->sectionHandler = new Content\Section\Handler(
                new Content\Section\Gateway\ExceptionConversion(
                    new Content\Section\Gateway\EzcDatabase( $this->dbHandler )
                )
            );
        }
        return $this->sectionHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::trashHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 761 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\contentHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getLocationGateway(), eZ\Publish\Core\Persistence\Legacy\Handler\getLocationMapper(), eZ\Publish\Core\Persistence\Legacy\Handler\locationHandler(), and eZ\Publish\Core\Persistence\Legacy\Handler\trashHandler().
    {
        if ( !isset( $this->trashHandler ) )
        {
            $this->trashHandler = new TrashHandler(
                $this->locationHandler(),
                $this->getLocationGateway(),
                $this->getLocationMapper(),
                $this->contentHandler()
            );
        }
        return $this->trashHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::urlAliasHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 779 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\contentLanguageHandler(), eZ\Publish\Core\Persistence\Legacy\Handler\getLocationGateway(), eZ\Publish\Core\Persistence\Legacy\Handler\getSlugConverter(), eZ\Publish\Core\Persistence\Legacy\Handler\getUrlAliasGateway(), eZ\Publish\Core\Persistence\Legacy\Handler\getUrlAliasMapper(), and eZ\Publish\Core\Persistence\Legacy\Handler\urlAliasHandler().
    {
        if ( !isset( $this->urlAliasHandler ) )
        {
            $this->urlAliasHandler = new UrlAliasHandler(
                $this->getUrlAliasGateway(),
                $this->getUrlAliasMapper(),
                $this->getLocationGateway(),
                $this->contentLanguageHandler(),
                $this->getSlugConverter()
            );
        }
        return $this->urlAliasHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::urlWildcardHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 849 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\getUrlWildcardGateway(), eZ\Publish\Core\Persistence\Legacy\Handler\getUrlWildcardMapper(), and eZ\Publish\Core\Persistence\Legacy\Handler\urlWildcardHandler().
    {
        if ( !isset( $this->urlWildcardHandler ) )
        {
            $this->urlWildcardHandler = new UrlWildcardHandler(
                $this->getUrlWildcardGateway(),
                $this->getUrlWildcardMapper()
            );
        }
        return $this->urlWildcardHandler;
    }
eZ\Publish\Core\Persistence\Legacy\Handler::userHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 727 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Handler\userHandler().
    {
        if ( !isset( $this->userHandler ) )
        {
            $this->userHandler = new User\Handler(
                new User\Gateway\ExceptionConversion(
                    new User\Gateway\EzcDatabase( $this->dbHandler )
                ),
                new User\Role\Gateway\EzcDatabase( $this->dbHandler ),
                new UserMapper()
            );
        }
        return $this->userHandler;
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Handler::$config protected
Definition at line 276 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$contentGateway protected
Definition at line 173 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$contentHandler protected
Definition at line 54 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$contentMapper protected
Definition at line 61 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$contentTypeGateway protected
Definition at line 96 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$contentTypeHandler protected
Definition at line 89 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$converterRegistry protected
Definition at line 248 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$dbHandler protected
Definition at line 241 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$fieldHandler protected
Definition at line 75 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$fieldTypeRegistry protected
Definition at line 262 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$languageCache protected
Definition at line 187 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$languageHandler protected
Definition at line 180 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$languageMaskGenerator protected
Definition at line 194 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$locationGateway protected
Definition at line 117 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$locationHandler protected
Definition at line 110 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$locationMapper protected
Definition at line 124 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$objectStateGateway protected
Definition at line 138 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$objectStateHandler protected
Definition at line 131 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$objectStateMapper protected
Definition at line 145 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$searchHandler protected
Definition at line 82 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$sectionHandler protected
Definition at line 159 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$storageHandler protected
Definition at line 68 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$storageRegistry protected
Definition at line 255 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$transformationProcessor protected
Definition at line 269 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$trashHandler protected
Definition at line 166 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$typeUpdateHandler protected
Definition at line 103 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$urlAliasGateway protected
Definition at line 208 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$urlAliasHandler protected
Definition at line 201 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$urlAliasMapper protected
Definition at line 215 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$urlWildcardGateway protected
Definition at line 229 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$urlWildcardHandler protected
Definition at line 222 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$urlWildcardMapper protected
Definition at line 236 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Handler::$userHandler protected
Definition at line 152 of file Handler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Handler.php