ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase Class Reference
Public Member Functions
__construct (EzcDbHandler $db, MaskGenerator $languageMaskGenerator)
insertGroup (Group $group)
updateGroup (GroupUpdateStruct $group)
countTypesInGroup ($groupId)
countGroupsForType ($typeId, $status)
deleteGroup ($groupId)
insertType (Type $type, $typeId=null)
insertGroupAssignment ($groupId, $typeId, $status)
deleteGroupAssignment ($groupId, $typeId, $status)
loadGroupData ($groupId)
loadGroupDataByIdentifier ($identifier)
loadAllGroupsData ()
loadTypesDataForGroup ($groupId, $status)
insertFieldDefinition ($typeId, $status, FieldDefinition $fieldDefinition, StorageFieldDefinition $storageFieldDef)
loadFieldDefinition ($id, $status)
deleteFieldDefinition ($typeId, $status, $fieldDefinitionId)
updateFieldDefinition ($typeId, $status, FieldDefinition $fieldDefinition, StorageFieldDefinition $storageFieldDef)
updateType ($typeId, $status, UpdateStruct $updateStruct)
loadTypeData ($typeId, $status)
loadTypeDataByIdentifier ($identifier, $status)
loadTypeDataByRemoteId ($remoteId, $status)
countInstancesOfType ($typeId)
deleteFieldDefinitionsForType ($typeId, $status)
delete ($typeId, $status)
deleteType ($typeId, $status)
deleteGroupAssignmentsForType ($typeId, $status)
publishTypeAndFields ($typeId, $sourceVersion, $targetVersion)
Public Member Functions inherited from eZ\Publish\Core\Persistence\Legacy\Content\Gateway
getContext ()
insertContentObject (CreateStruct $struct, $currentVersionNo=1)
insertVersion (VersionInfo $versionInfo, array $fields)
updateContent ($contentId, MetadataUpdateStruct $struct)
updateVersion ($contentId, $versionNo, UpdateStruct $struct)
updateAlwaysAvailableFlag ($contentId, $newAlwaysAvailable)
setStatus ($contentId, $version, $status)
insertNewField (Content $content, Field $field, StorageFieldValue $value)
insertExistingField (Content $content, Field $field, StorageFieldValue $value)
updateField (Field $field, StorageFieldValue $value)
updateNonTranslatableField (Field $field, StorageFieldValue $value, $contentId)
load ($contentId, $version, $translations=null)
loadContentInfo ($contentId)
loadVersionInfo ($contentId, $versionNo)
listVersionsForUser ($userId, $status=VersionInfo::STATUS_DRAFT)
listVersions ($contentId)
getLastVersionNumber ($contentId)
getAllLocationIds ($contentId)
getFieldIdsByType ($contentId, $versionNo=null)
deleteRelations ($contentId, $versionNo=null)
deleteField ($fieldId, $version)
deleteFields ($contentId, $versionNo=null)
deleteVersions ($contentId, $versionNo=null)
deleteNames ($contentId, $versionNo=null)
setName ($contentId, $version, $name, $language)
deleteContent ($contentId)
loadLatestPublishedData ($contentId)
loadRelations ($contentId, $contentVersionNo=null, $relationType=null)
loadReverseRelations ($contentId, $relationType=null)
deleteRelation ($relationId)
insertRelation (RelationCreateStruct $createStruct)
Protected Member Functions
insertTypeNameData ($typeId, $typeStatus, array $languages)
setCommonTypeColumns (ezcQuery $q, $type)
createGroupLoadQuery ()
setCommonFieldColumns (ezcQuery $q, FieldDefinition $fieldDefinition, StorageFieldDefinition $storageFieldDef)
deleteTypeNameData ($typeId, $typeStatus)
getLoadTypeQuery ()
selectColumns (ezcQuerySelect $q, $tableName)
Protected Attributes
$columns
$dbHandler
$languageMaskGenerator
Detailed Description
Zeta Component Database based content type gateway.
Definition at line 26 of file EzcDatabase.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::__construct (EzcDbHandler $db, MaskGenerator $languageMaskGenerator)
Creates a new gateway based on $db
Parameters
\eZ\Publish\Core\Persistence\Legacy\EzcDbHandler $db
\eZ\Publish\Core\Persistence\Legacy\Content\Language\MaskGenerator $languageMaskGenerator
Definition at line 104 of file EzcDatabase.php.
    {
        $this->dbHandler = $db;
        $this->languageMaskGenerator = $languageMaskGenerator;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::countGroupsForType ($typeId, $status)
Returns the number of Groups the type is assigned to.
Parameters
int $typeId
int $status
Returns
int
Definition at line 219 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\countGroupsForType().
    {
        $q = $this->dbHandler->createSelectQuery();
        $q->select(
            $q->alias(
                $q->expr->count(
                    $this->dbHandler->quoteColumn( 'group_id' )
                ),
                'count'
            )
        )->from(
            $this->dbHandler->quoteTable( 'ezcontentclass_classgroup' )
        )->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_id' ),
                    $q->bindValue( $typeId, null, \PDO::PARAM_INT )
                )
            ),
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_version' ),
                    $q->bindValue( $status, null, \PDO::PARAM_INT )
                )
            )
        );
        $stmt = $q->prepare();
        $stmt->execute();
        return (int)$stmt->fetchColumn();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::countInstancesOfType ($typeId)
Counts the number of instances that exists of the identified type.
Parameters
int $typeId
Returns
int
Definition at line 1071 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\countInstancesOfType().
    {
        $q = $this->dbHandler->createSelectQuery();
        $q->select(
            $q->alias(
                $q->expr->count(
                    $this->dbHandler->quoteColumn( 'id' )
                ),
                'count'
            )
        )->from(
            $this->dbHandler->quoteTable( 'ezcontentobject' )
        )->where(
            $q->expr->eq(
                $this->dbHandler->quoteColumn( 'contentclass_id' ),
                $q->bindValue( $typeId, null, \PDO::PARAM_INT )
            )
        );
        $stmt = $q->prepare();
        $stmt->execute();
        return (int)$stmt->fetchColumn();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::countTypesInGroup ($groupId)
Returns the number of types in a certain group.
Parameters
int $groupId
Returns
int
Definition at line 186 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\countTypesInGroup().
    {
        $q = $this->dbHandler->createSelectQuery();
        $q->select(
            $q->alias(
                $q->expr->count(
                    $this->dbHandler->quoteColumn( 'contentclass_id' )
                ),
                'count'
            )
        )->from(
            $this->dbHandler->quoteTable( 'ezcontentclass_classgroup' )
        )->where(
            $q->expr->eq(
                $this->dbHandler->quoteColumn( 'group_id' ),
                $q->bindValue( $groupId, null, \PDO::PARAM_INT )
            )
        );
        $stmt = $q->prepare();
        $stmt->execute();
        return (int)$stmt->fetchColumn();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::createGroupLoadQuery () protected
Creates the basic query to load Group data.
Returns
ezcQuerySelect
Definition at line 547 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\createGroupLoadQuery().
    {
        $q = $this->dbHandler->createSelectQuery();
        $q->select(
            $this->dbHandler->quoteColumn( 'created' ),
            $this->dbHandler->quoteColumn( 'creator_id' ),
            $this->dbHandler->quoteColumn( 'id' ),
            $this->dbHandler->quoteColumn( 'modified' ),
            $this->dbHandler->quoteColumn( 'modifier_id' ),
            $this->dbHandler->quoteColumn( 'name' )
        )->from(
            $this->dbHandler->quoteTable( 'ezcontentclassgroup' )
        );
        return $q;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::delete ($typeId, $status)
Deletes a Type completely.
Parameters
mixed $typeId
int $status
Returns
void
Definition at line 1132 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteFieldDefinitionsForType(), eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteGroupAssignmentsForType(), eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteType(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteTypeNameData().
    {
        $this->deleteGroupAssignmentsForType(
            $typeId, $status
        );
        $this->deleteFieldDefinitionsForType(
            $typeId, $status
        );
        $this->deleteTypeNameData(
            $typeId, $status
        );
        $this->deleteType(
            $typeId, $status
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::deleteFieldDefinition ($typeId, $status, $fieldDefinitionId)
Deletes a field definition.
Parameters
mixed $typeId
int $status
mixed $fieldDefinitionId
Returns
void
Definition at line 775 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteFieldDefinition().
    {
        $q = $this->dbHandler->createDeleteQuery();
        $q->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcontentclass_attribute' )
        )->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'id' ),
                    $q->bindValue( $fieldDefinitionId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $q->bindValue( $status, null, \PDO::PARAM_INT )
                ),
                // @todo FIXME: Actually not needed
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_id' ),
                    $q->bindValue( $typeId, null, \PDO::PARAM_INT )
                )
            )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::deleteFieldDefinitionsForType ($typeId, $status)
Deletes all field definitions of a Type.
Parameters
mixed $typeId
int $status
Returns
void
Definition at line 1104 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteFieldDefinitionsForType().
    {
        $q = $this->dbHandler->createDeleteQuery();
        $q->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcontentclass_attribute' )
        )->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_id' ),
                    $q->bindValue( $typeId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $q->bindValue( $status, null, \PDO::PARAM_INT )
                )
            )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::deleteGroup ($groupId)
Deletes the Group with the given $groupId.
Parameters
int $groupId
Returns
void
Definition at line 259 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteGroup().
    {
        $q = $this->dbHandler->createDeleteQuery();
        $q->deleteFrom( $this->dbHandler->quoteTable( 'ezcontentclassgroup' ) )
            ->where(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'id' ),
                    $q->bindValue( $groupId, null, \PDO::PARAM_INT )
                )
            );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::deleteGroupAssignment ($groupId, $typeId, $status)
Deletes a group assignments for a Type.
Parameters
mixed $groupId
mixed $typeId
int $status
Returns
void
Definition at line 459 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteGroupAssignment().
    {
        $q = $this->dbHandler->createDeleteQuery();
        $q->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcontentclass_classgroup' )
        )->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_id' ),
                    $q->bindValue( $typeId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_version' ),
                    $q->bindValue( $status, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'group_id' ),
                    $q->bindValue( $groupId, null, \PDO::PARAM_INT )
                )
            )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::deleteGroupAssignmentsForType ($typeId, $status)
Deletes all group assignments for a Type.
Parameters
mixed $typeId
int $status
Returns
void
Definition at line 1186 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteGroupAssignmentsForType().
    {
        $q = $this->dbHandler->createDeleteQuery();
        $q->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcontentclass_classgroup' )
        )->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_id' ),
                    $q->bindValue( $typeId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_version' ),
                    $q->bindValue( $status, null, \PDO::PARAM_INT )
                )
            )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::deleteType ($typeId, $status)
Deletes a the Type.
Does no delete the field definitions!
Parameters
mixed $typeId
int $status
Returns
void
Definition at line 1158 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteType().
    {
        $q = $this->dbHandler->createDeleteQuery();
        $q->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcontentclass' )
        )->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'id' ),
                    $q->bindValue( $typeId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $q->bindValue( $status, null, \PDO::PARAM_INT )
                )
            )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::deleteTypeNameData ($typeId, $typeStatus) protected
Deletes all name data for $typeId in $typeStatus.
Parameters
int $typeId
int $typeStatus
Returns
void
Definition at line 848 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteTypeNameData().
    {
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom( 'ezcontentclass_name' )
            ->where(
                $query->expr->lAnd(
                    $query->expr->eq(
                        $this->dbHandler->quoteColumn( 'contentclass_id' ),
                        $query->bindValue( $typeId, null, \PDO::PARAM_INT )
                    ),
                    $query->expr->eq(
                        $this->dbHandler->quoteColumn( 'contentclass_version' ),
                        $query->bindValue( $typeStatus, null, \PDO::PARAM_INT )
                    )
                )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::getLoadTypeQuery () protected
Returns a basic query to retrieve Type data.
Returns
ezcQuerySelect
Definition at line 996 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\getLoadTypeQuery(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\selectColumns().
    {
        $q = $this->dbHandler->createSelectQuery();
        $this->selectColumns( $q, 'ezcontentclass' );
        $this->selectColumns( $q, 'ezcontentclass_attribute' );
        $q->select(
            $this->dbHandler->aliasedColumn(
                $q,
                'group_id',
                'ezcontentclass_classgroup'
            )
        );
        $q->from(
            $this->dbHandler->quoteTable( 'ezcontentclass' )
        )->leftJoin(
            $this->dbHandler->quoteTable( 'ezcontentclass_attribute' ),
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn(
                        'id',
                        'ezcontentclass'
                    ),
                    $this->dbHandler->quoteColumn(
                        'contentclass_id',
                        'ezcontentclass_attribute'
                    )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn(
                        'version',
                        'ezcontentclass'
                    ),
                    $this->dbHandler->quoteColumn(
                        'version',
                        'ezcontentclass_attribute'
                    )
                )
            )
        )->leftJoin(
            $this->dbHandler->quoteTable( 'ezcontentclass_classgroup' ),
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn(
                        'id',
                        'ezcontentclass'
                    ),
                    $this->dbHandler->quoteColumn(
                        'contentclass_id',
                        'ezcontentclass_classgroup'
                    )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn(
                        'version',
                        'ezcontentclass'
                    ),
                    $this->dbHandler->quoteColumn(
                        'contentclass_version',
                        'ezcontentclass_classgroup'
                    )
                )
            )
        );
        return $q;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::insertFieldDefinition ($typeId, $status, FieldDefinition $fieldDefinition, StorageFieldDefinition $storageFieldDef)
Inserts a $fieldDefinition for $typeId.
Parameters
mixed $typeId
int $status
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageFieldDef
Returns
mixed Field definition ID
Definition at line 609 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\insertFieldDefinition(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\setCommonFieldColumns().
    {
        $q = $this->dbHandler->createInsertQuery();
        $q->insertInto( $this->dbHandler->quoteTable( 'ezcontentclass_attribute' ) );
        $q->set(
            $this->dbHandler->quoteColumn( 'id' ),
            isset( $fieldDefinition->id ) ?
                $q->bindValue( $fieldDefinition->id, null, \PDO::PARAM_INT ) :
                $this->dbHandler->getAutoIncrementValue( 'ezcontentclass_attribute', 'id' )
        )->set(
            $this->dbHandler->quoteColumn( 'contentclass_id' ),
            $q->bindValue( $typeId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'version' ),
            $q->bindValue( $status, null, \PDO::PARAM_INT )
        );
        $this->setCommonFieldColumns( $q, $fieldDefinition, $storageFieldDef );
        $q->prepare()->execute();
        if ( !isset( $fieldDefinition->id ) )
        {
            return $this->dbHandler->lastInsertId(
                $this->dbHandler->getSequenceName( 'ezcontentclass_attribute', 'id' )
            );
        }
        return $fieldDefinition->id;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::insertGroup (Group $group)
Inserts the given $group.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group $group
Returns
mixed Group ID
Definition at line 117 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\insertGroup().
    {
        $q = $this->dbHandler->createInsertQuery();
        $q->insertInto(
            $this->dbHandler->quoteTable( 'ezcontentclassgroup' )
        )->set(
            $this->dbHandler->quoteColumn( 'id' ),
            $this->dbHandler->getAutoIncrementValue( 'ezcontentclassgroup', 'id' )
        )->set(
            $this->dbHandler->quoteColumn( 'created' ),
            $q->bindValue( $group->created, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'creator_id' ),
            $q->bindValue( $group->creatorId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'modified' ),
            $q->bindValue( $group->modified, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'modifier_id' ),
            $q->bindValue( $group->modifierId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'name' ),
            $q->bindValue( $group->identifier )
        );
        $q->prepare()->execute();
        return $this->dbHandler->lastInsertId(
            $this->dbHandler->getSequenceName( 'ezcontentclassgroup', 'id' )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::insertGroupAssignment ($groupId, $typeId, $status)
Insert assignment of $typeId to $groupId.
Parameters
mixed $groupId
mixed $typeId
int $status
Returns
void
Definition at line 425 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\insertGroupAssignment(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\loadGroupData().
    {
        $groups = $this->loadGroupData( $groupId );
        $group = $groups[0];
        $q = $this->dbHandler->createInsertQuery();
        $q->insertInto(
            $this->dbHandler->quoteTable( 'ezcontentclass_classgroup' )
        )->set(
            $this->dbHandler->quoteColumn( 'contentclass_id' ),
            $q->bindValue( $typeId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'contentclass_version' ),
            $q->bindValue( $status, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'group_id' ),
            $q->bindValue( $groupId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'group_name' ),
            $q->bindValue( $group['name'] )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::insertType (Type $type, $typeId = null)
Inserts a new content type.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type $type
mixed | null $typeId
Returns
mixed Type ID
Definition at line 322 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\insertType(), eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\insertTypeNameData(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\setCommonTypeColumns().
    {
        $q = $this->dbHandler->createInsertQuery();
        $q->insertInto( $this->dbHandler->quoteTable( 'ezcontentclass' ) );
        $q->set(
            $this->dbHandler->quoteColumn( 'id' ),
            isset( $typeId ) ?
                $q->bindValue( $typeId, null, \PDO::PARAM_INT ) :
                $this->dbHandler->getAutoIncrementValue( 'ezcontentclass', 'id' )
        )->set(
            $this->dbHandler->quoteColumn( 'version' ),
            $q->bindValue( $type->status, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'created' ),
            $q->bindValue( $type->created, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'creator_id' ),
            $q->bindValue( $type->creatorId, null, \PDO::PARAM_INT )
        );
        $this->setCommonTypeColumns( $q, $type );
        $q->prepare()->execute();
        if ( empty( $typeId ) )
        {
            $typeId = $this->dbHandler->lastInsertId(
                $this->dbHandler->getSequenceName( 'ezcontentclass', 'id' )
            );
        }
        $this->insertTypeNameData( $typeId, $type->status, $type->name );
        return $typeId;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::insertTypeNameData ($typeId, $typeStatus, array $languages) protected
Inserts data into contentclass_name.
Parameters
int $typeId
int $typeStatus
string[] $languages
Returns
void
Definition at line 281 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$name, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\insertTypeNameData().
    {
        $tmpLanguages = $languages;
        if ( isset( $tmpLanguages['always-available'] ) )
        {
            unset( $tmpLanguages['always-available'] );
        }
        foreach ( $tmpLanguages as $language => $name )
        {
            $query = $this->dbHandler->createInsertQuery();
            $query
                ->insertInto( $this->dbHandler->quoteTable( 'ezcontentclass_name' ) )
                ->set( 'contentclass_id', $query->bindValue( $typeId, null, \PDO::PARAM_INT ) )
                ->set( 'contentclass_version', $query->bindValue( $typeStatus, null, \PDO::PARAM_INT ) )
                ->set(
                    'language_id',
                    $query->bindValue(
                        $this->languageMaskGenerator->generateLanguageIndicator(
                            $language,
                            $this->languageMaskGenerator->isLanguageAlwaysAvailable(
                                $language,
                                $languages
                            )
                        ), null, \PDO::PARAM_INT
                    )
                )
                ->set( 'language_locale', $query->bindValue( $language ) )
                ->set( 'name', $query->bindValue( $name ) );
            $query->prepare()->execute();
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::loadAllGroupsData ()
Returns an array with data about all Group objects.
Returns
string[][]
Definition at line 532 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\createGroupLoadQuery(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\loadAllGroupsData().
    {
        $q = $this->createGroupLoadQuery();
        $stmt = $q->prepare();
        $stmt->execute();
        return $stmt->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::loadFieldDefinition ($id, $status)
Loads an array with data about field definition referred $id and $status.
Parameters
mixed $id field definition id
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Returns
array Data rows.
Definition at line 741 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$id, eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\loadFieldDefinition(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\selectColumns().
    {
        $q = $this->dbHandler->createSelectQuery();
        $this->selectColumns( $q, "ezcontentclass_attribute" );
        $q->from(
            $this->dbHandler->quoteTable( "ezcontentclass_attribute" )
        )->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( "id", "ezcontentclass_attribute" ),
                    $q->bindValue( $id, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( "version", "ezcontentclass_attribute" ),
                    $q->bindValue( $status, null, \PDO::PARAM_INT )
                )
            )
        );
        $stmt = $q->prepare();
        $stmt->execute();
        return $stmt->fetch( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::loadGroupData ($groupId)
Loads data about Group with $groupId.
Parameters
mixed $groupId
Returns
string[][]
Definition at line 490 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\createGroupLoadQuery(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\loadGroupData().
    {
        $q = $this->createGroupLoadQuery();
        $q->where(
            $q->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $q->bindValue( $groupId, null, \PDO::PARAM_INT )
            )
        );
        $stmt = $q->prepare();
        $stmt->execute();
        return $stmt->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::loadGroupDataByIdentifier ($identifier)
Loads data about Group with $identifier.
Parameters
mixed $identifier
Returns
string[][]
Definition at line 512 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$identifier, eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\createGroupLoadQuery(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\loadGroupDataByIdentifier().
    {
        $q = $this->createGroupLoadQuery();
        $q->where(
            $q->expr->eq(
                $this->dbHandler->quoteColumn( 'name' ),
                $q->bindValue( $identifier, null, \PDO::PARAM_STR )
            )
        );
        $stmt = $q->prepare();
        $stmt->execute();
        return $stmt->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::loadTypeData ($typeId, $status)
Loads an array with data about $typeId in $status.
Parameters
mixed $typeId
int $status
Returns
array Data rows.
Definition at line 910 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\getLoadTypeQuery(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\loadTypeData().
    {
        $q = $this->getLoadTypeQuery();
        $q->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'id', 'ezcontentclass' ),
                    $q->bindValue( $typeId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version', 'ezcontentclass' ),
                    $q->bindValue( $status, null, \PDO::PARAM_INT )
                )
            )
        );
        $stmt = $q->prepare();
        $stmt->execute();
        return $stmt->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::loadTypeDataByIdentifier ($identifier, $status)
Loads an array with data about the type referred to by $identifier in $status.
Parameters
string $identifier
int $status
Returns
array(int=>array(string=>mixed)) Data rows.
Definition at line 940 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$identifier, eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\getLoadTypeQuery(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\loadTypeDataByIdentifier().
    {
        $q = $this->getLoadTypeQuery();
        $q->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'identifier', 'ezcontentclass' ),
                    $q->bindValue( $identifier )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version', 'ezcontentclass' ),
                    $q->bindValue( $status )
                )
            )
        );
        $stmt = $q->prepare();
        $stmt->execute();
        return $stmt->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::loadTypeDataByRemoteId ($remoteId, $status)
Loads an array with data about the type referred to by $remoteId in $status.
Parameters
mixed $remoteId
int $status
Returns
array(int=>array(string=>mixed)) Data rows.
Definition at line 970 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$remoteId, eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\getLoadTypeQuery(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\loadTypeDataByRemoteId().
    {
        $q = $this->getLoadTypeQuery();
        $q->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'remote_id', 'ezcontentclass' ),
                    $q->bindValue( $remoteId )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version', 'ezcontentclass' ),
                    $q->bindValue( $status )
                )
            )
        );
        $stmt = $q->prepare();
        $stmt->execute();
        return $stmt->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::loadTypesDataForGroup ($groupId, $status)
Loads data for all Types in $status in $groupId.
Parameters
mixed $groupId
int $status
Returns
string[][]
Definition at line 571 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\getLoadTypeQuery(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\loadTypesDataForGroup().
    {
        $q = $this->getLoadTypeQuery();
        $q->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn(
                        'group_id',
                        'ezcontentclass_classgroup'
                    ),
                    $q->bindValue( $groupId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn(
                        'version',
                        'ezcontentclass'
                    ),
                    $q->bindValue( $status, null, \PDO::PARAM_INT )
                )
            )
        );
        $stmt = $q->prepare();
        $stmt->execute();
        return $stmt->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::publishTypeAndFields ($typeId, $sourceVersion, $targetVersion)
Publishes the Type with $typeId from $sourceVersion to $targetVersion, including its fields
Parameters
int $typeId
int $sourceVersion
int $targetVersion
Returns
void
Definition at line 1216 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\publishTypeAndFields().
    {
        $query = $this->dbHandler->createUpdateQuery();
        $query->update(
            $this->dbHandler->quoteTable( 'ezcontentclass' )
        )->set(
            $this->dbHandler->quoteColumn( 'version' ),
            $query->bindValue( $targetVersion, null, \PDO::PARAM_INT )
        )->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'id' ),
                    $query->bindValue( $typeId, null, \PDO::PARAM_INT )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $query->bindValue( $sourceVersion, null, \PDO::PARAM_INT )
                )
            )
        );
        $query->prepare()->execute();
        $query = $this->dbHandler->createUpdateQuery();
        $query->update(
            $this->dbHandler->quoteTable( 'ezcontentclass_classgroup' )
        )->set(
            $this->dbHandler->quoteColumn( 'contentclass_version' ),
            $query->bindValue( $targetVersion, null, \PDO::PARAM_INT )
        )->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_id' ),
                    $query->bindValue( $typeId, null, \PDO::PARAM_INT )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_version' ),
                    $query->bindValue( $sourceVersion, null, \PDO::PARAM_INT )
                )
            )
        );
        $query->prepare()->execute();
        $query = $this->dbHandler->createUpdateQuery();
        $query->update(
            $this->dbHandler->quoteTable( 'ezcontentclass_attribute' )
        )->set(
            $this->dbHandler->quoteColumn( 'version' ),
            $query->bindValue( $targetVersion, null, \PDO::PARAM_INT )
        )->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_id' ),
                    $query->bindValue( $typeId, null, \PDO::PARAM_INT )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $query->bindValue( $sourceVersion, null, \PDO::PARAM_INT )
                )
            )
        );
        $query->prepare()->execute();
        $query = $this->dbHandler->createUpdateQuery();
        $query->update(
            $this->dbHandler->quoteTable( 'ezcontentclass_name' )
        )->set(
            $this->dbHandler->quoteColumn( 'contentclass_version' ),
            $query->bindValue( $targetVersion, null, \PDO::PARAM_INT )
        )->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_id' ),
                    $query->bindValue( $typeId, null, \PDO::PARAM_INT )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_version' ),
                    $query->bindValue( $sourceVersion, null, \PDO::PARAM_INT )
                )
            )
        );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::selectColumns (ezcQuerySelect $q, $tableName) protected
Creates an array of select columns for $tableName.
Parameters
\ezcQuerySelect $q
string $tableName
Definition at line 1309 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\selectColumns().
    {
        foreach ( $this->columns[$tableName] as $col )
        {
            $q->select(
                $this->dbHandler->aliasedColumn( $q, $col, $tableName )
            );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::setCommonFieldColumns (ezcQuery $q, FieldDefinition $fieldDefinition, StorageFieldDefinition $storageFieldDef) protected
Set common columns for insert/update of FieldDefinition.
Parameters
\ezcQuery $q
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageFieldDef
Returns
void
Definition at line 653 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\setCommonFieldColumns().
    {
        $q->set(
            $this->dbHandler->quoteColumn( 'serialized_name_list' ),
            $q->bindValue( serialize( $fieldDefinition->name ) )
        )->set(
            $this->dbHandler->quoteColumn( 'serialized_description_list' ),
            $q->bindValue( serialize( $fieldDefinition->description ) )
        )->set(
            $this->dbHandler->quoteColumn( 'identifier' ),
            $q->bindValue( $fieldDefinition->identifier )
        )->set(
            $this->dbHandler->quoteColumn( 'category' ),
            $q->bindValue( $fieldDefinition->fieldGroup, null, \PDO::PARAM_STR )
        )->set(
            $this->dbHandler->quoteColumn( 'placement' ),
            $q->bindValue( $fieldDefinition->position, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'data_type_string' ),
            $q->bindValue( $fieldDefinition->fieldType )
        )->set(
            $this->dbHandler->quoteColumn( 'can_translate' ),
            $q->bindValue( ( $fieldDefinition->isTranslatable ? 1 : 0 ), null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'is_required' ),
            $q->bindValue( ( $fieldDefinition->isRequired ? 1 : 0 ), null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'is_information_collector' ),
            $q->bindValue( ( $fieldDefinition->isInfoCollector ? 1 : 0 ), null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'data_float1' ),
            $q->bindValue( $storageFieldDef->dataFloat1 )
        )->set(
            $this->dbHandler->quoteColumn( 'data_float2' ),
            $q->bindValue( $storageFieldDef->dataFloat2 )
        )->set(
            $this->dbHandler->quoteColumn( 'data_float3' ),
            $q->bindValue( $storageFieldDef->dataFloat3 )
        )->set(
            $this->dbHandler->quoteColumn( 'data_float4' ),
            $q->bindValue( $storageFieldDef->dataFloat4 )
        )->set(
            $this->dbHandler->quoteColumn( 'data_int1' ),
            $q->bindValue( $storageFieldDef->dataInt1, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'data_int2' ),
            $q->bindValue( $storageFieldDef->dataInt2, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'data_int3' ),
            $q->bindValue( $storageFieldDef->dataInt3, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'data_int4' ),
            $q->bindValue( $storageFieldDef->dataInt4, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'data_text1' ),
            $q->bindValue( $storageFieldDef->dataText1 )
        )->set(
            $this->dbHandler->quoteColumn( 'data_text2' ),
            $q->bindValue( $storageFieldDef->dataText2 )
        )->set(
            $this->dbHandler->quoteColumn( 'data_text3' ),
            $q->bindValue( $storageFieldDef->dataText3 )
        )->set(
            $this->dbHandler->quoteColumn( 'data_text4' ),
            $q->bindValue( $storageFieldDef->dataText4 )
        )->set(
            $this->dbHandler->quoteColumn( 'data_text5' ),
            $q->bindValue( $storageFieldDef->dataText5 )
        )->set(
            $this->dbHandler->quoteColumn( 'serialized_data_text' ),
            $q->bindValue( serialize( $storageFieldDef->serializedDataText ) )
        )->set(
            $this->dbHandler->quoteColumn( 'is_searchable' ),
            $q->bindValue( ( $fieldDefinition->isSearchable ? 1 : 0 ), null, \PDO::PARAM_INT )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::setCommonTypeColumns (ezcQuery $q, $type) protected
Set common columns for insert/update of a Type.
Parameters
\ezcQuery $q
mixed $type
Returns
void
Definition at line 365 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\setCommonTypeColumns().
    {
        $q->set(
            $this->dbHandler->quoteColumn( 'serialized_name_list' ),
            $q->bindValue( serialize( $type->name ) )
        )->set(
            $this->dbHandler->quoteColumn( 'serialized_description_list' ),
            $q->bindValue( serialize( $type->description ) )
        )->set(
            $this->dbHandler->quoteColumn( 'identifier' ),
            $q->bindValue( $type->identifier )
        )->set(
            $this->dbHandler->quoteColumn( 'modified' ),
            $q->bindValue( $type->modified, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'modifier_id' ),
            $q->bindValue( $type->modifierId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'remote_id' ),
            $q->bindValue( $type->remoteId )
        )->set(
            $this->dbHandler->quoteColumn( 'url_alias_name' ),
            $q->bindValue( $type->urlAliasSchema )
        )->set(
            $this->dbHandler->quoteColumn( 'contentobject_name' ),
            $q->bindValue( $type->nameSchema )
        )->set(
            $this->dbHandler->quoteColumn( 'is_container' ),
            $q->bindValue( $type->isContainer ? 1 : 0, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'language_mask' ),
            $q->bindValue(
                $this->languageMaskGenerator->generateLanguageMask( $type->name ),
                null,
                \PDO::PARAM_INT
            )
        )->set(
            $this->dbHandler->quoteColumn( 'initial_language_id' ),
            $q->bindValue( $type->initialLanguageId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'sort_field' ),
            $q->bindValue( $type->sortField, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'sort_order' ),
            $q->bindValue( $type->sortOrder, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'always_available' ),
            $q->bindValue( (int)$type->defaultAlwaysAvailable, null, \PDO::PARAM_INT )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::updateFieldDefinition ($typeId, $status, FieldDefinition $fieldDefinition, StorageFieldDefinition $storageFieldDef)
Updates a $fieldDefinition for $typeId.
Parameters
mixed $typeId
int $status
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageFieldDef
Returns
void
Definition at line 811 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\setCommonFieldColumns(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\updateFieldDefinition().
    {
        $q = $this->dbHandler->createUpdateQuery();
        $q
            ->update(
                $this->dbHandler->quoteTable( 'ezcontentclass_attribute' )
            )->where(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'id' ),
                    $q->bindValue( $fieldDefinition->id, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $q->bindValue( $status, null, \PDO::PARAM_INT )
                ),
                // @todo FIXME: Actually not needed
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentclass_id' ),
                    $q->bindValue( $typeId, null, \PDO::PARAM_INT )
                )
            );
        $this->setCommonFieldColumns( $q, $fieldDefinition, $storageFieldDef );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::updateGroup (GroupUpdateStruct $group)
Updates a group with data in $group.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group\UpdateStruct $group
Returns
void
Definition at line 155 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\updateGroup().
    {
        $q = $this->dbHandler->createUpdateQuery();
        $q->update(
            $this->dbHandler->quoteColumn( 'ezcontentclassgroup' )
        )->set(
            $this->dbHandler->quoteColumn( 'modified' ),
            $q->bindValue( $group->modified, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'modifier_id' ),
            $q->bindValue( $group->modifierId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'name' ),
            $q->bindValue( $group->identifier )
        )->where(
            $q->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $q->bindValue( $group->id, null, \PDO::PARAM_INT )
            )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::updateType ($typeId, $status, UpdateStruct $updateStruct)
Update a type with $updateStruct.
Parameters
mixed $typeId
int $status
\eZ\Publish\SPI\Persistence\Content\Type\UpdateStruct $updateStruct
Returns
void
Definition at line 876 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\deleteTypeNameData(), eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\insertTypeNameData(), eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\setCommonTypeColumns(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase\updateType().
    {
        $q = $this->dbHandler->createUpdateQuery();
        $q->update( $this->dbHandler->quoteTable( 'ezcontentclass' ) );
        $this->setCommonTypeColumns( $q, $updateStruct );
        $q->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'id' ),
                    $q->bindValue( $typeId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->dbHandler->quoteColumn( 'version' ),
                    $q->bindValue( $status, null, \PDO::PARAM_INT )
                )
            )
        );
        $q->prepare()->execute();
        $this->deleteTypeNameData( $typeId, $status );
        $this->insertTypeNameData( $typeId, $status, $updateStruct->name );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::$columns protected
Definition at line 33 of file EzcDatabase.php.
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::$dbHandler protected
Definition at line 89 of file EzcDatabase.php.
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\EzcDatabase::$languageMaskGenerator protected
Definition at line 96 of file EzcDatabase.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/EzcDatabase.php