ezp-next: eZ\Publish\Core\MVC\Symfony\SiteAccess\Router Class Reference
eZ\Publish\Core\MVC\Symfony\SiteAccess\Router Class Reference
Public Member Functions
__construct ($defaultSiteAccess, array $siteAccessesConfiguration, array $siteAccessList, $siteAccessClass=null)
match (SimplifiedRequest $request)
getSiteAccess ()
setSiteAccess (SiteAccess $siteAccess=null)
Protected Attributes
$defaultSiteAccess
$siteAccessesConfiguration
$siteAccessList
$siteAccess
$siteAccessClass
Detailed Description
Definition at line 16 of file Router.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Router::__construct ($defaultSiteAccess, array $siteAccessesConfiguration, array $siteAccessList, $siteAccessClass = null)
Constructor.
Parameters
string $defaultSiteAccess
array $siteAccessesConfiguration
array $siteAccessList
null $siteAccessClass
Definition at line 77 of file Router.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Router\$defaultSiteAccess, and eZ\Publish\Core\MVC\Symfony\SiteAccess\Router\$siteAccessClass.
    {
        $this->defaultSiteAccess = $defaultSiteAccess;
        $this->siteAccessesConfiguration = $siteAccessesConfiguration;
        $this->siteAccessList = array_fill_keys( $siteAccessList, true );
        $this->siteAccessClass = $siteAccessClass;
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Router::getSiteAccess ()
Returns
|null
Definition at line 162 of file Router.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Router\getSiteAccess().
    {
        return $this->siteAccess;
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Router::match (SimplifiedRequest $request)
Performs SiteAccess matching given the $request.
Parameters
\eZ\Publish\Core\MVC\Symfony\Routing\SimplifiedRequest $request
Exceptions
\eZ\Publish\Core\MVC\Exception\InvalidSiteAccessException
Returns
Definition at line 94 of file Router.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\$matcher, eZ\Publish\Core\MVC\Symfony\SiteAccess\Router\$siteAccessClass, and eZ\Publish\Core\MVC\Symfony\SiteAccess\Router\match().
    {
        if ( isset( $this->siteAccess ) )
            return $this->siteAccess;
        $siteAccessClass = $this->siteAccessClass ?: 'eZ\\Publish\\Core\\MVC\\Symfony\\SiteAccess';
        $this->siteAccess = new $siteAccessClass();
        // Request header always have precedence
        if ( isset( $request->headers['X-Siteaccess'] ) )
        {
            $siteaccessName = $request->headers['X-Siteaccess'];
            if ( !isset( $this->siteAccessList[$siteaccessName] ) )
            {
                unset( $this->siteAccess );
                throw new InvalidSiteAccessException( $siteaccessName, array_keys( $this->siteAccessList ), 'X-Siteaccess request header' );
            }
            $this->siteAccess->name = $request->headers['X-Siteaccess'];
            $this->siteAccess->matchingType = 'header';
            return $this->siteAccess;
        }
        // Then check environment variable
        $siteaccessEnvName = getenv( 'EZPUBLISH_SITEACCESS' );
        if ( $siteaccessEnvName !== false )
        {
            if ( !isset( $this->siteAccessList[$siteaccessEnvName] ) )
            {
                unset( $this->siteAccess );
                throw new InvalidSiteAccessException( $siteaccessEnvName, array_keys( $this->siteAccessList ), 'EZPUBLISH_SITEACCESS Environment variable' );
            }
            $this->siteAccess->name = $siteaccessEnvName;
            $this->siteAccess->matchingType = 'env';
            return $this->siteAccess;
        }
        foreach ( $this->siteAccessesConfiguration as $matchingClass => $matchingConfiguration )
        {
            // If class begins with a '\' it means it's a FQ class name,
            // otherwise it is relative to this namespace.
            if ( $matchingClass[0] !== '\\' )
                $matchingClass = __NAMESPACE__ . "\\Matcher\\$matchingClass";
            $matcher = new $matchingClass( $matchingConfiguration );
            $matcher->setRequest( $request );
            if ( ( $siteaccessName = $matcher->match() ) !== false )
            {
                if ( isset( $this->siteAccessList[$siteaccessName] ) )
                {
                    $this->siteAccess->name = $siteaccessName;
                    $this->siteAccess->matchingType = $matcher->getName();
                    $this->siteAccess->matcher = $matcher;
                    return $this->siteAccess;
                }
            }
        }
        $this->siteAccess->name = $this->defaultSiteAccess;
        $this->siteAccess->matchingType = 'default';
        return $this->siteAccess;
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Router::setSiteAccess (SiteAccess $siteAccess = null)
Parameters
\eZ\Publish\Core\MVC\Symfony\SiteAccess $siteAccess private Only for unit tests use
Definition at line 172 of file Router.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Router\$siteAccess, and eZ\Publish\Core\MVC\Symfony\SiteAccess\Router\setSiteAccess().
    {
        $this->siteAccess = $siteAccess;
    }
Member Data Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Router::$defaultSiteAccess protected
Definition at line 23 of file Router.php.
eZ\Publish\Core\MVC\Symfony\SiteAccess\Router::$siteAccess protected
Definition at line 65 of file Router.php.
eZ\Publish\Core\MVC\Symfony\SiteAccess\Router::$siteAccessClass protected
Definition at line 67 of file Router.php.
eZ\Publish\Core\MVC\Symfony\SiteAccess\Router::$siteAccessesConfiguration protected
Definition at line 52 of file Router.php.
eZ\Publish\Core\MVC\Symfony\SiteAccess\Router::$siteAccessList protected
Definition at line 60 of file Router.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/SiteAccess/Router.php