ezp-next: eZ\Publish\Core\Repository\ContentTypeService Class Reference
eZ\Publish\Core\Repository\ContentTypeService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, Handler $contentTypeHandler, array $settings=array())
createContentTypeGroup (ContentTypeGroupCreateStruct $contentTypeGroupCreateStruct)
loadContentTypeGroup ($contentTypeGroupId)
loadContentTypeGroupByIdentifier ($contentTypeGroupIdentifier)
loadContentTypeGroups ()
updateContentTypeGroup (APIContentTypeGroup $contentTypeGroup, ContentTypeGroupUpdateStruct $contentTypeGroupUpdateStruct)
deleteContentTypeGroup (APIContentTypeGroup $contentTypeGroup)
createContentType (APIContentTypeCreateStruct $contentTypeCreateStruct, array $contentTypeGroups)
loadContentType ($contentTypeId)
loadContentTypeByIdentifier ($identifier)
loadContentTypeByRemoteId ($remoteId)
loadContentTypeDraft ($contentTypeId)
loadContentTypes (APIContentTypeGroup $contentTypeGroup)
createContentTypeDraft (APIContentType $contentType)
updateContentTypeDraft (APIContentTypeDraft $contentTypeDraft, ContentTypeUpdateStruct $contentTypeUpdateStruct)
deleteContentType (APIContentType $contentType)
copyContentType (APIContentType $contentType, User $user=null)
assignContentTypeGroup (APIContentType $contentType, APIContentTypeGroup $contentTypeGroup)
unassignContentTypeGroup (APIContentType $contentType, APIContentTypeGroup $contentTypeGroup)
addFieldDefinition (APIContentTypeDraft $contentTypeDraft, FieldDefinitionCreateStruct $fieldDefinitionCreateStruct)
removeFieldDefinition (APIContentTypeDraft $contentTypeDraft, APIFieldDefinition $fieldDefinition)
updateFieldDefinition (APIContentTypeDraft $contentTypeDraft, APIFieldDefinition $fieldDefinition, FieldDefinitionUpdateStruct $fieldDefinitionUpdateStruct)
publishContentTypeDraft (APIContentTypeDraft $contentTypeDraft)
newContentTypeGroupCreateStruct ($identifier)
newContentTypeCreateStruct ($identifier)
newContentTypeUpdateStruct ()
newContentTypeGroupUpdateStruct ()
newFieldDefinitionCreateStruct ($identifier, $fieldTypeIdentifier)
newFieldDefinitionUpdateStruct ()
Public Member Functions inherited from eZ\Publish\API\Repository\ContentTypeService
updateContentTypeGroup (ContentTypeGroup $contentTypeGroup, ContentTypeGroupUpdateStruct $contentTypeGroupUpdateStruct)
deleteContentTypeGroup (ContentTypeGroup $contentTypeGroup)
createContentType (ContentTypeCreateStruct $contentTypeCreateStruct, array $contentTypeGroups)
loadContentTypes (ContentTypeGroup $contentTypeGroup)
createContentTypeDraft (ContentType $contentType)
updateContentTypeDraft (ContentTypeDraft $contentTypeDraft, ContentTypeUpdateStruct $contentTypeUpdateStruct)
deleteContentType (ContentType $contentType)
copyContentType (ContentType $contentType, User $user=null)
assignContentTypeGroup (ContentType $contentType, ContentTypeGroup $contentTypeGroup)
unassignContentTypeGroup (ContentType $contentType, ContentTypeGroup $contentTypeGroup)
addFieldDefinition (ContentTypeDraft $contentTypeDraft, FieldDefinitionCreateStruct $fieldDefinitionCreateStruct)
removeFieldDefinition (ContentTypeDraft $contentTypeDraft, FieldDefinition $fieldDefinition)
updateFieldDefinition (ContentTypeDraft $contentTypeDraft, FieldDefinition $fieldDefinition, FieldDefinitionUpdateStruct $fieldDefinitionUpdateStruct)
publishContentTypeDraft (ContentTypeDraft $contentTypeDraft)
Protected Member Functions
buildContentTypeGroupDomainObject (SPIContentTypeGroup $spiGroup)
getDateTime ($timestamp)
buildContentTypeDomainObject (SPIContentType $spiContentType)
buildContentTypeDraftDomainObject (SPIContentType $spiContentType)
buildSPIContentTypeUpdateStruct (APIContentTypeDraft $contentTypeDraft, ContentTypeUpdateStruct $contentTypeUpdateStruct)
Protected Attributes
$repository
$contentTypeHandler
$settings
Detailed Description
Definition at line 55 of file ContentTypeService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\ContentTypeService::__construct (RepositoryInterface $repository, Handler $contentTypeHandler, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\API\Repository\Repository $repository
\eZ\Publish\SPI\Persistence\Content\Type\Handler $contentTypeHandler
array $settings
Definition at line 79 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\$contentTypeHandler, eZ\Publish\Core\Repository\ContentTypeService\$repository, and eZ\Publish\Core\Repository\ContentTypeService\$settings.
    {
        $this->repository = $repository;
        $this->contentTypeHandler = $contentTypeHandler;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            //'defaultSetting' => array(),
        );
    }
Member Function Documentation
eZ\Publish\Core\Repository\ContentTypeService::addFieldDefinition (APIContentTypeDraft $contentTypeDraft, FieldDefinitionCreateStruct $fieldDefinitionCreateStruct)
Adds a new field definition to an existing content type.
The content type must be in state DRAFT.
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the identifier in already exists in the content type
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to edit a content type
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeDraft $contentTypeDraft
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinitionCreateStruct $fieldDefinitionCreateStruct
Definition at line 1305 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeDraft().
    {
        if ( $this->repository->hasAccess( 'class', 'update' ) !== true )
            throw new UnauthorizedException( 'ContentType', 'update' );
        $loadedContentTypeDraft = $this->loadContentTypeDraft( $contentTypeDraft->id );
        if ( $loadedContentTypeDraft->getFieldDefinition( $fieldDefinitionCreateStruct->identifier ) !== null )
        {
            throw new InvalidArgumentException(
                "\$fieldDefinitionCreateStruct",
                "Another FieldDefinition with identifier '{$fieldDefinitionCreateStruct->identifier}' exists in the ContentType"
            );
        }
        $spiFieldDefinitionCreateStruct = $this->buildSPIFieldDefinitionCreate(
            $fieldDefinitionCreateStruct
        );
        $this->repository->beginTransaction();
        try
        {
            $this->contentTypeHandler->addFieldDefinition(
                $contentTypeDraft->id,
                $contentTypeDraft->status,
                $spiFieldDefinitionCreateStruct
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentTypeService::assignContentTypeGroup (APIContentType $contentType, APIContentTypeGroup $contentTypeGroup)
Assigns a content type to a content type group.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to unlink a content type
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the content type is already assigned the given group
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroup $contentTypeGroup
Definition at line 1205 of file ContentTypeService.php.
    {
        if ( $this->repository->hasAccess( 'class', 'update' ) !== true )
            throw new UnauthorizedException( 'ContentType', 'update' );
        $spiContentType = $this->contentTypeHandler->load(
            $contentType->id,
            $contentType->status
        );
        if ( in_array( $contentTypeGroup->id, $spiContentType->groupIds ) )
        {
            throw new InvalidArgumentException(
                "\$contentTypeGroup",
                "The given ContentType is already assigned to the ContentTypeGroup"
            );
        }
        $this->repository->beginTransaction();
        try
        {
            $this->contentTypeHandler->link(
                $contentTypeGroup->id,
                $contentType->id,
                $contentType->status
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentTypeService::buildContentTypeDomainObject (SPIContentType $spiContentType) protected
Builds a ContentType domain object from value object returned by persistence
Parameters
\eZ\Publish\SPI\Persistence\Content\Type $spiContentType
Returns
Definition at line 702 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\getDateTime(), and eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeGroup().
    {
        $mainLanguageCode = $this->repository->getContentLanguageService()->loadLanguageById(
            $spiContentType->initialLanguageId
        )->languageCode;
        $contentTypeGroups = array();
        foreach ( $spiContentType->groupIds as $groupId )
        {
            $contentTypeGroups[] = $this->loadContentTypeGroup( $groupId );
        }
        $fieldDefinitions = array();
        foreach ( $spiContentType->fieldDefinitions as $spiFieldDefinition )
        {
            $fieldDefinitions[] = $this->buildFieldDefinitionDomainObject( $spiFieldDefinition );
        }
        return new ContentType(
            array(
                "names" => $spiContentType->name,
                "descriptions" => $spiContentType->description,
                "contentTypeGroups" => $contentTypeGroups,
                "fieldDefinitions" => $fieldDefinitions,
                "id" => $spiContentType->id,
                "status" => $spiContentType->status,
                "identifier" => $spiContentType->identifier,
                "creationDate" => $this->getDateTime( $spiContentType->created ),
                "modificationDate" => $this->getDateTime( $spiContentType->modified ),
                "creatorId" => $spiContentType->creatorId,
                "modifierId" => $spiContentType->modifierId,
                "remoteId" => $spiContentType->remoteId,
                "urlAliasSchema" => $spiContentType->urlAliasSchema,
                "nameSchema" => $spiContentType->nameSchema,
                "isContainer" => $spiContentType->isContainer,
                "mainLanguageCode" => $mainLanguageCode,
                "defaultAlwaysAvailable" => $spiContentType->defaultAlwaysAvailable,
                "defaultSortField" => $spiContentType->sortField,
                "defaultSortOrder" => $spiContentType->sortOrder
            )
        );
    }
eZ\Publish\Core\Repository\ContentTypeService::buildContentTypeDraftDomainObject (SPIContentType $spiContentType) protected
Builds a ContentTypeDraft domain object from value object returned by persistence Decorates ContentType
Parameters
\eZ\Publish\SPI\Persistence\Content\Type $spiContentType
Returns
Definition at line 786 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\buildContentTypeDomainObject().
    {
        return new ContentTypeDraft(
            array(
                "innerContentType" => $this->buildContentTypeDomainObject( $spiContentType )
            )
        );
    }
eZ\Publish\Core\Repository\ContentTypeService::buildContentTypeGroupDomainObject (SPIContentTypeGroup $spiGroup) protected
Builds a ContentTypeGroup domain object from value object returned by persistence
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group $spiGroup
Returns
Definition at line 347 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\getDateTime().
    {
        return new ContentTypeGroup(
            array(
                "id" => $spiGroup->id,
                "identifier" => $spiGroup->identifier,
                "creationDate" => $this->getDateTime( $spiGroup->created ),
                "modificationDate" => $this->getDateTime( $spiGroup->modified ),
                "creatorId" => $spiGroup->creatorId,
                "modifierId" => $spiGroup->modifierId,
                "names" => $spiGroup->name,
                "descriptions" => $spiGroup->description
            )
        );
    }
eZ\Publish\Core\Repository\ContentTypeService::buildSPIContentTypeUpdateStruct (APIContentTypeDraft $contentTypeDraft, ContentTypeUpdateStruct $contentTypeUpdateStruct) protected
Builds ContentType update struct for storage layer
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeDraft $contentTypeDraft
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeUpdateStruct $contentTypeUpdateStruct
Returns
Definition at line 1069 of file ContentTypeService.php.
    {
        $updateStruct = new SPIContentTypeUpdateStruct();
        $updateStruct->identifier = $contentTypeUpdateStruct->identifier !== null ?
            $contentTypeUpdateStruct->identifier :
            $contentTypeDraft->identifier;
        $updateStruct->remoteId = $contentTypeUpdateStruct->remoteId !== null ?
            $contentTypeUpdateStruct->remoteId :
            $contentTypeDraft->remoteId;
        $updateStruct->name = $contentTypeUpdateStruct->names !== null ?
            $contentTypeUpdateStruct->names :
            $contentTypeDraft->names;
        $updateStruct->description = $contentTypeUpdateStruct->descriptions !== null ?
            $contentTypeUpdateStruct->descriptions :
            $contentTypeDraft->descriptions;
        $updateStruct->modified = $contentTypeUpdateStruct->modificationDate !== null ?
            $contentTypeUpdateStruct->modificationDate->getTimestamp() :
            time();
        $updateStruct->modifierId = $contentTypeUpdateStruct->modifierId !== null ?
            $contentTypeUpdateStruct->modifierId :
            $this->repository->getCurrentUser()->id;
        $updateStruct->urlAliasSchema = $contentTypeUpdateStruct->urlAliasSchema !== null ?
            $contentTypeUpdateStruct->urlAliasSchema :
            $contentTypeDraft->urlAliasSchema;
        $updateStruct->nameSchema = $contentTypeUpdateStruct->nameSchema !== null ?
            $contentTypeUpdateStruct->nameSchema :
            $contentTypeDraft->nameSchema;
        $updateStruct->isContainer = $contentTypeUpdateStruct->isContainer !== null ?
            $contentTypeUpdateStruct->isContainer :
            $contentTypeDraft->isContainer;
        $updateStruct->sortField = $contentTypeUpdateStruct->defaultSortField !== null ?
            $contentTypeUpdateStruct->defaultSortField :
            $contentTypeDraft->defaultSortField;
        $updateStruct->sortOrder = $contentTypeUpdateStruct->defaultSortOrder !== null ?
            (int)$contentTypeUpdateStruct->defaultSortOrder :
            $contentTypeDraft->defaultSortOrder;
        $updateStruct->defaultAlwaysAvailable = $contentTypeUpdateStruct->defaultAlwaysAvailable !== null ?
            $contentTypeUpdateStruct->defaultAlwaysAvailable :
            $contentTypeDraft->defaultAlwaysAvailable;
        $updateStruct->initialLanguageId = $this->repository->getContentLanguageService()->loadLanguage(
            $contentTypeUpdateStruct->mainLanguageCode !== null ?
                $contentTypeUpdateStruct->mainLanguageCode :
                $contentTypeDraft->mainLanguageCode
        )->id;
        return $updateStruct;
    }
eZ\Publish\Core\Repository\ContentTypeService::copyContentType (APIContentType $contentType, User $user = null)
Copy Type incl fields and groupIds to a new Type object
New Type will have $userId as creator / modifier, created / modified should be updated with current time, updated remoteId and identifier should be appended with '_' + unique string.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to copy a content type
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType
\eZ\Publish\API\Repository\Values\User\User $user if null the current user is used
Returns
Definition at line 1167 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\loadContentType().
    {
        if ( $this->repository->hasAccess( 'class', 'create' ) !== true )
            throw new UnauthorizedException( 'ContentType', 'create' );
        if ( empty( $user ) )
        {
            $user = $this->repository->getCurrentUser();
        }
        $this->repository->beginTransaction();
        try
        {
            $spiContentType = $this->contentTypeHandler->copy(
                $user->id,
                $contentType->id,
                SPIContentType::STATUS_DEFINED
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->loadContentType( $spiContentType->id );
    }
eZ\Publish\Core\Repository\ContentTypeService::createContentType (APIContentTypeCreateStruct $contentTypeCreateStruct, array $contentTypeGroups)
Create a Content Type object.
The content type is created in the state STATUS_DRAFT.
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException In case when
array of content type groups does not contain at least one content type group
identifier or remoteId in the content type create struct already exists
there is a duplicate field identifier in the content type create struct
content type create struct does not contain at least one field definition create struct
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeCreateStruct $contentTypeCreateStruct
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroup[] $contentTypeGroups Required array of ContentTypeGroup to link type with (must contain one)
Returns
Definition at line 391 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\buildContentTypeDraftDomainObject().
    {
        if ( empty( $contentTypeGroups ) )
        {
            throw new InvalidArgumentException(
                "\$contentTypeGroups",
                "Argument must contain at least one ContentTypeGroup"
            );
        }
        try
        {
            $this->contentTypeHandler->loadByIdentifier(
                $contentTypeCreateStruct->identifier
            );
            throw new InvalidArgumentException(
                "\$contentTypeCreateStruct",
                "Another ContentType with identifier '{$contentTypeCreateStruct->identifier}' exists"
            );
        }
        catch ( APINotFoundException $e )
        {
            // Do nothing
        }
        try
        {
            $this->contentTypeHandler->loadByRemoteId(
                $contentTypeCreateStruct->remoteId
            );
            throw new InvalidArgumentException(
                "\$contentTypeCreateStruct",
                "Another ContentType with remoteId '{$contentTypeCreateStruct->remoteId}' exists"
            );
        }
        catch ( APINotFoundException $e )
        {
            // Do nothing
        }
        if ( empty( $contentTypeCreateStruct->fieldDefinitions ) )
        {
            throw new InvalidArgumentException(
                "\$contentTypeCreateStruct",
                "Argument must contain at least one FieldDefinitionCreateStruct"
            );
        }
        $fieldDefinitionIdentifierSet = array();
        $fieldDefinitionPositionSet = array();
        foreach ( $contentTypeCreateStruct->fieldDefinitions as $fieldDefinitionCreateStruct )
        {
            // Check for duplicate identifiers
            if ( !isset( $fieldDefinitionIdentifierSet[$fieldDefinitionCreateStruct->identifier] ) )
            {
                $fieldDefinitionIdentifierSet[$fieldDefinitionCreateStruct->identifier] = true;
            }
            else
            {
                throw new InvalidArgumentException(
                    "\$contentTypeCreateStruct",
                    "Argument contains duplicate field definition identifier '{$fieldDefinitionCreateStruct->identifier}'"
                );
            }
            // Check for duplicate positions
            if ( !isset( $fieldDefinitionPositionSet[$fieldDefinitionCreateStruct->position] ) )
            {
                $fieldDefinitionPositionSet[$fieldDefinitionCreateStruct->position] = true;
            }
            else
            {
                throw new InvalidArgumentException(
                    "\$contentTypeCreateStruct",
                    "Argument contains duplicate field definition position '{$fieldDefinitionCreateStruct->position}'"
                );
            }
        }
        if ( $contentTypeCreateStruct->creatorId === null )
        {
            $userId = $this->repository->getCurrentUser()->id;
        }
        else
        {
            $userId = $contentTypeCreateStruct->creatorId;
        }
        if ( $contentTypeCreateStruct->creationDate === null )
        {
            $timestamp = time();
        }
        else
        {
            $timestamp = $contentTypeCreateStruct->creationDate->getTimestamp();
        }
        if ( $contentTypeCreateStruct->remoteId === null )
        {
            $contentTypeCreateStruct->remoteId = md5( uniqid( get_class( $contentTypeCreateStruct ), true ) );
        }
        $initialLanguageId = $this->repository->getContentLanguageService()->loadLanguage(
            $contentTypeCreateStruct->mainLanguageCode
        )->id;
        $groupIds = array_map(
            function ( $contentTypeGroup )
            {
                return $contentTypeGroup->id;
            },
            $contentTypeGroups
        );
        $fieldDefinitions = array();
        foreach ( $contentTypeCreateStruct->fieldDefinitions as $fieldDefinitionCreateStruct )
        {
            $fieldDefinitions[] = $this->buildSPIFieldDefinitionCreate( $fieldDefinitionCreateStruct );
        }
        $spiContentTypeCreateStruct = new SPIContentTypeCreateStruct(
            array(
                "name" => $contentTypeCreateStruct->names,
                "status" => APIContentType::STATUS_DRAFT,
                "description" => $contentTypeCreateStruct->descriptions,
                "identifier" => $contentTypeCreateStruct->identifier,
                "created" => $timestamp,
                "modified" => $timestamp,
                "creatorId" => $userId,
                "modifierId" => $userId,
                "remoteId" => $contentTypeCreateStruct->remoteId,
                "urlAliasSchema" => $contentTypeCreateStruct->urlAliasSchema,
                "nameSchema" => $contentTypeCreateStruct->nameSchema,
                "isContainer" => $contentTypeCreateStruct->isContainer,
                "initialLanguageId" => $initialLanguageId,
                "sortField" => $contentTypeCreateStruct->defaultSortField,
                "sortOrder" => $contentTypeCreateStruct->defaultSortOrder,
                "groupIds" => $groupIds,
                "fieldDefinitions" => $fieldDefinitions,
                "defaultAlwaysAvailable" => $contentTypeCreateStruct->defaultAlwaysAvailable
            )
        );
        $this->repository->beginTransaction();
        try
        {
            $spiContentType = $this->contentTypeHandler->create(
                $spiContentTypeCreateStruct
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildContentTypeDraftDomainObject( $spiContentType );
    }
eZ\Publish\Core\Repository\ContentTypeService::createContentTypeDraft (APIContentType $contentType)
Creates a draft from an existing content type.
This is a complete copy of the content type which has the state STATUS_DRAFT.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to edit a content type
\eZ\Publish\API\Repository\Exceptions\BadStateException If there is already a draft assigned to another user
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType
Returns
Definition at line 933 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\buildContentTypeDraftDomainObject().
    {
        if ( $this->repository->hasAccess( 'class', 'create' ) !== true )
            throw new UnauthorizedException( 'ContentType', 'create' );
        try
        {
            $this->contentTypeHandler->load(
                $contentType->id,
                SPIContentType::STATUS_DRAFT
            );
            throw new BadStateException(
                "\$contentType",
                "Draft of the ContentType already exists"
            );
        }
        catch ( APINotFoundException $e )
        {
            $this->repository->beginTransaction();
            try
            {
                $spiContentType = $this->contentTypeHandler->createDraft(
                    $this->repository->getCurrentUser()->id,
                    $contentType->id
                );
                $this->repository->commit();
            }
            catch ( Exception $e )
            {
                $this->repository->rollback();
                throw $e;
            }
        }
        return $this->buildContentTypeDraftDomainObject(
            $spiContentType
        );
    }
eZ\Publish\Core\Repository\ContentTypeService::createContentTypeGroup (ContentTypeGroupCreateStruct $contentTypeGroupCreateStruct)
Create a Content Type Group object
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to create a content type group
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If a group with the same identifier already exists
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroupCreateStruct $contentTypeGroupCreateStruct
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 99 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\buildContentTypeGroupDomainObject(), and eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeGroupByIdentifier().
    {
        if ( $this->repository->hasAccess( 'class', 'create' ) !== true )
            throw new UnauthorizedException( 'ContentType', 'create' );
        try
        {
            $this->loadContentTypeGroupByIdentifier( $contentTypeGroupCreateStruct->identifier );
            throw new InvalidArgumentException(
                "\$contentTypeGroupCreateStruct",
                "A group with the identifier '{$contentTypeGroupCreateStruct->identifier}' already exists"
            );
        }
        catch ( APINotFoundException $e )
        {
            // Do nothing
        }
        if ( $contentTypeGroupCreateStruct->creationDate === null )
        {
            $timestamp = time();
        }
        else
        {
            $timestamp = $contentTypeGroupCreateStruct->creationDate->getTimestamp();
        }
        if ( $contentTypeGroupCreateStruct->creatorId === null )
        {
            $userId = $this->repository->getCurrentUser()->id;
        }
        else
        {
            $userId = $contentTypeGroupCreateStruct->creatorId;
        }
        $spiGroupCreateStruct = new SPIContentTypeGroupCreateStruct(
            array(
                "identifier" => $contentTypeGroupCreateStruct->identifier,
                "created" => $timestamp,
                "modified" => $timestamp,
                "creatorId" => $userId,
                "modifierId" => $userId
            )
        );
        $this->repository->beginTransaction();
        try
        {
            $spiContentTypeGroup = $this->contentTypeHandler->createGroup(
                $spiGroupCreateStruct
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildContentTypeGroupDomainObject( $spiContentTypeGroup );
    }
eZ\Publish\Core\Repository\ContentTypeService::deleteContentType (APIContentType $contentType)
Delete a Content Type object.
Deletes a content type if it has no instances
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException If there exist content objects of this type
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to delete a content type
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType
Definition at line 1133 of file ContentTypeService.php.
    {
        if ( $this->repository->hasAccess( 'class', 'delete' ) !== true )
            throw new UnauthorizedException( 'ContentType', 'delete' );
        $this->repository->beginTransaction();
        try
        {
            $this->contentTypeHandler->delete(
                $contentType->id,
                $contentType->status
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentTypeService::deleteContentTypeGroup (APIContentTypeGroup $contentTypeGroup)
Delete a Content Type Group.
This method only deletes an content type group which has content types without any content instances
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to delete a content type group
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If a to be deleted content type has instances
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroup $contentTypeGroup
Definition at line 309 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeGroup().
    {
        if ( $this->repository->hasAccess( 'class', 'delete' ) !== true )
            throw new UnauthorizedException( 'ContentType', 'delete' );
        $loadedContentTypeGroup = $this->loadContentTypeGroup( $contentTypeGroup->id );
        $this->repository->beginTransaction();
        try
        {
            $this->contentTypeHandler->deleteGroup(
                $loadedContentTypeGroup->id
            );
            $this->repository->commit();
        }
        catch ( APIBadStateException $e )
        {
            $this->repository->rollback();
            throw new InvalidArgumentException(
                "\$contentTypeGroup",
                "Content type group has content type instances",
                $e
            );
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentTypeService::getDateTime ($timestamp) protected
Parameters
int | null $timestamp
Returns
|null
Definition at line 368 of file ContentTypeService.php.
    {
        $dateTime = new DateTime();
        $dateTime->setTimestamp( $timestamp );
        return $dateTime;
    }
eZ\Publish\Core\Repository\ContentTypeService::loadContentType ($contentTypeId)
Get a Content Type object by id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If a content type with the given id and status DEFINED can not be found
Parameters
int $contentTypeId
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 804 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\buildContentTypeDomainObject().
    {
        if ( !is_numeric( $contentTypeId ) )
        {
            throw new InvalidArgumentValue( '$contentTypeId', $contentTypeId );
        }
        $spiContentType = $this->contentTypeHandler->load(
            $contentTypeId,
            SPIContentType::STATUS_DEFINED
        );
        return $this->buildContentTypeDomainObject(
            $spiContentType
        );
    }
eZ\Publish\Core\Repository\ContentTypeService::loadContentTypeByIdentifier ($identifier)
Get a Content Type object by identifier
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If content type with the given identifier and status DEFINED can not be found
Parameters
string $identifier
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 830 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\buildContentTypeDomainObject().
    {
        if ( !is_string( $identifier ) )
        {
            throw new InvalidArgumentValue( '$identifier', $identifier );
        }
        $spiContentType = $this->contentTypeHandler->loadByIdentifier(
            $identifier
        );
        return $this->buildContentTypeDomainObject(
            $spiContentType
        );
    }
eZ\Publish\Core\Repository\ContentTypeService::loadContentTypeByRemoteId ($remoteId)
Get a Content Type object by id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If content type with the given remote id and status DEFINED can not be found
Parameters
string $remoteId
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 855 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\buildContentTypeDomainObject().
    {
        $spiContentType = $this->contentTypeHandler->loadByRemoteId( $remoteId );
        return $this->buildContentTypeDomainObject(
            $spiContentType
        );
    }
eZ\Publish\Core\Repository\ContentTypeService::loadContentTypeDraft ($contentTypeId)
Get a Content Type object draft by id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If the content type draft owned by the current user can not be found
Parameters
int $contentTypeId
Todo:
Use another exception when user of draft is someone else
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 875 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\buildContentTypeDraftDomainObject().
    {
        if ( !is_numeric( $contentTypeId ) )
        {
            throw new InvalidArgumentValue( '$contentTypeId', $contentTypeId );
        }
        $spiContentType = $this->contentTypeHandler->load(
            $contentTypeId,
            SPIContentType::STATUS_DRAFT
        );
        if ( $spiContentType->modifierId != $this->repository->getCurrentUser()->id )
        {
            throw new NotFoundException( "ContentType owned by someone else", $contentTypeId );
        }
        return $this->buildContentTypeDraftDomainObject(
            $spiContentType
        );
    }
eZ\Publish\Core\Repository\ContentTypeService::loadContentTypeGroup ($contentTypeGroupId)
Get a Content Type Group object by id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If group can not be found
Parameters
int $contentTypeGroupId
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 172 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\buildContentTypeGroupDomainObject().
    {
        if ( !is_numeric( $contentTypeGroupId ) )
        {
            throw new InvalidArgumentValue( '$contentTypeGroupId', $contentTypeGroupId );
        }
        $spiGroup = $this->contentTypeHandler->loadGroup(
            $contentTypeGroupId
        );
        return $this->buildContentTypeGroupDomainObject( $spiGroup );
    }
eZ\Publish\Core\Repository\ContentTypeService::loadContentTypeGroupByIdentifier ($contentTypeGroupIdentifier)
Get a Content Type Group object by identifier
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If group can not be found
Parameters
string $contentTypeGroupIdentifier
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 195 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeGroups().
    {
        $groups = $this->loadContentTypeGroups();
        foreach ( $groups as $group )
        {
            if ( $group->identifier === $contentTypeGroupIdentifier )
            {
                return $group;
            }
        }
        throw new NotFoundException( 'ContentTypeGroup', $contentTypeGroupIdentifier );
    }
eZ\Publish\Core\Repository\ContentTypeService::loadContentTypeGroups ()
Get all Content Type Groups
Returns
[]
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 215 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\buildContentTypeGroupDomainObject().
    {
        $spiGroups = $this->contentTypeHandler->loadAllGroups();
        $groups = array();
        foreach ( $spiGroups as $spiGroup )
        {
            $groups[] = $this->buildContentTypeGroupDomainObject( $spiGroup );
        }
        return $groups;
    }
eZ\Publish\Core\Repository\ContentTypeService::loadContentTypes (APIContentTypeGroup $contentTypeGroup)
Get Content Type objects which belong to the given content type group
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroup $contentTypeGroup
Returns
[] Which have status DEFINED
Definition at line 904 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\buildContentTypeDomainObject().
    {
        $spiContentTypes = $this->contentTypeHandler->loadContentTypes(
            $contentTypeGroup->id,
            SPIContentType::STATUS_DEFINED
        );
        $contentTypes = array();
        foreach ( $spiContentTypes as $spiContentType )
        {
            $contentTypes[] = $this->buildContentTypeDomainObject( $spiContentType );
        }
        return $contentTypes;
    }
eZ\Publish\Core\Repository\ContentTypeService::newContentTypeCreateStruct ($identifier)
Instantiates a new content type create class
Parameters
string $identifier
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 1547 of file ContentTypeService.php.
    {
        if ( !is_string( $identifier ) )
        {
            throw new InvalidArgumentValue( '$identifier', $identifier );
        }
        return new ContentTypeCreateStruct(
            array(
                "identifier" => $identifier
            )
        );
    }
eZ\Publish\Core\Repository\ContentTypeService::newContentTypeGroupCreateStruct ($identifier)
Instantiates a new content type group create class
Parameters
string $identifier
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 1526 of file ContentTypeService.php.
    {
        if ( !is_string( $identifier ) )
        {
            throw new InvalidArgumentValue( '$identifier', $identifier );
        }
        return new ContentTypeGroupCreateStruct(
            array(
                "identifier" => $identifier
            )
        );
    }
eZ\Publish\Core\Repository\ContentTypeService::newContentTypeGroupUpdateStruct ()
Instantiates a new content type update struct
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 1576 of file ContentTypeService.php.
    {
        return new ContentTypeGroupUpdateStruct;
    }
eZ\Publish\Core\Repository\ContentTypeService::newContentTypeUpdateStruct ()
Instantiates a new content type update struct
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 1566 of file ContentTypeService.php.
    {
        return new ContentTypeUpdateStruct;
    }
eZ\Publish\Core\Repository\ContentTypeService::newFieldDefinitionCreateStruct ($identifier, $fieldTypeIdentifier)
Instantiates a field definition create struct
Parameters
string $fieldTypeIdentifier the required field type identifier
string $identifier the required identifier for the field definition
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 1589 of file ContentTypeService.php.
    {
        if ( !is_string( $identifier ) )
        {
            throw new InvalidArgumentValue( '$identifier', $identifier );
        }
        if ( !is_string( $fieldTypeIdentifier ) )
        {
            throw new InvalidArgumentValue( '$fieldTypeIdentifier', $fieldTypeIdentifier );
        }
        return new FieldDefinitionCreateStruct(
            array(
                "identifier" => $identifier,
                "fieldTypeIdentifier" => $fieldTypeIdentifier
            )
        );
    }
eZ\Publish\Core\Repository\ContentTypeService::newFieldDefinitionUpdateStruct ()
Instantiates a field definition update class
Returns
Implements eZ\Publish\API\Repository\ContentTypeService.
Definition at line 1614 of file ContentTypeService.php.
    {
        return new FieldDefinitionUpdateStruct;
    }
eZ\Publish\Core\Repository\ContentTypeService::publishContentTypeDraft (APIContentTypeDraft $contentTypeDraft)
Publish the content type and update content objects.
This method updates content objects, depending on the changed field definitions.
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException If the content type has no draft
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the content type has no field definitions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to publish a content type
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeDraft $contentTypeDraft
Definition at line 1459 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeDraft().
    {
        if ( $this->repository->hasAccess( 'class', 'update' ) !== true )
        {
            throw new UnauthorizedException( 'ContentType', 'update' );
        }
        try
        {
            $loadedContentTypeDraft = $this->loadContentTypeDraft( $contentTypeDraft->id );
        }
        catch ( APINotFoundException $e )
        {
            throw new BadStateException(
                "\$contentTypeDraft",
                "The content type does not have a draft.",
                $e
            );
        }
        if ( count( $loadedContentTypeDraft->getFieldDefinitions() ) === 0 )
        {
            throw new InvalidArgumentException(
                "\$contentTypeDraft",
                "The content type draft should have at least one field definition."
            );
        }
        $this->repository->beginTransaction();
        try
        {
            if ( empty( $loadedContentTypeDraft->nameSchema ) )
            {
                $fieldDefinitions = $loadedContentTypeDraft->getFieldDefinitions();
                $this->contentTypeHandler->update(
                    $contentTypeDraft->id,
                    $contentTypeDraft->status,
                    $this->buildSPIContentTypeUpdateStruct(
                        $loadedContentTypeDraft,
                        new ContentTypeUpdateStruct(
                            array(
                                "nameSchema" => "<" . $fieldDefinitions[0]->identifier . ">"
                            )
                        )
                    )
                );
            }
            $this->contentTypeHandler->publish(
                $loadedContentTypeDraft->id
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentTypeService::removeFieldDefinition (APIContentTypeDraft $contentTypeDraft, APIFieldDefinition $fieldDefinition)
Remove a field definition from an existing Type.
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the given field definition does not belong to the given type
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to edit a content type
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeDraft $contentTypeDraft
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition
Definition at line 1350 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeDraft().
    {
        if ( $this->repository->hasAccess( 'class', 'update' ) !== true )
            throw new UnauthorizedException( 'ContentType', 'update' );
        $loadedFieldDefinition = $this->loadContentTypeDraft(
            $contentTypeDraft->id
        )->getFieldDefinition(
            $fieldDefinition->identifier
        );
        if ( empty( $loadedFieldDefinition ) || $loadedFieldDefinition->id != $fieldDefinition->id )
        {
            throw new InvalidArgumentException(
                "\$fieldDefinition",
                "The given FieldDefinition does not belong to the ContentType"
            );
        }
        $this->repository->beginTransaction();
        try
        {
            $this->contentTypeHandler->removeFieldDefinition(
                $contentTypeDraft->id,
                SPIContentType::STATUS_DRAFT,
                $fieldDefinition->id
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentTypeService::unassignContentTypeGroup (APIContentType $contentType, APIContentTypeGroup $contentTypeGroup)
Unassign a content type from a group.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to link a content type
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the content type is not assigned this the given group.
\eZ\Publish\API\Repository\Exceptions\BadStateException If $contentTypeGroup is the last group assigned to the content type
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroup $contentTypeGroup
Definition at line 1250 of file ContentTypeService.php.
    {
        if ( $this->repository->hasAccess( 'class', 'update' ) !== true )
            throw new UnauthorizedException( 'ContentType', 'update' );
        $spiContentType = $this->contentTypeHandler->load(
            $contentType->id,
            $contentType->status
        );
        if ( !in_array( $contentTypeGroup->id, $spiContentType->groupIds ) )
        {
            throw new InvalidArgumentException(
                "\$contentTypeGroup",
                "The given ContentType is not assigned the ContentTypeGroup"
            );
        }
        $this->repository->beginTransaction();
        try
        {
            $this->contentTypeHandler->unlink(
                $contentTypeGroup->id,
                $contentType->id,
                $contentType->status
            );
            $this->repository->commit();
        }
        catch ( APIBadStateException $e )
        {
            $this->repository->rollback();
            throw new BadStateException(
                "\$contentType",
                "The given ContentTypeGroup is the last group assigned to the ContentType",
                $e
            );
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentTypeService::updateContentTypeDraft (APIContentTypeDraft $contentTypeDraft, ContentTypeUpdateStruct $contentTypeUpdateStruct)
Update a Content Type object
Does not update fields (fieldDefinitions), use updateFieldDefinition() to update them.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to update a content type
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the given identifier or remoteId already exists or there is no draft assigned to the authenticated user
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeDraft $contentTypeDraft
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeUpdateStruct $contentTypeUpdateStruct
Definition at line 985 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeByIdentifier(), eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeByRemoteId(), and eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeDraft().
    {
        if ( $this->repository->hasAccess( 'class', 'update' ) !== true )
        {
            throw new UnauthorizedException( 'ContentType', 'update' );
        }
        try
        {
            $loadedContentTypeDraft = $this->loadContentTypeDraft( $contentTypeDraft->id );
        }
        catch ( APINotFoundException $e )
        {
            throw new InvalidArgumentException(
                "\$contentTypeDraft",
                "There is no ContentType draft assigned to the authenticated user",
                $e
            );
        }
        if ( $contentTypeUpdateStruct->identifier !== null
            && $contentTypeUpdateStruct->identifier != $loadedContentTypeDraft->identifier )
        {
            try
            {
                $this->loadContentTypeByIdentifier( $contentTypeUpdateStruct->identifier );
                throw new InvalidArgumentException(
                    "\$contentTypeUpdateStruct",
                    "Another ContentType with identifier '{$contentTypeUpdateStruct->identifier}' exists"
                );
            }
            catch ( APINotFoundException $e )
            {
                // Do nothing
            }
        }
        if ( $contentTypeUpdateStruct->remoteId !== null
            && $contentTypeUpdateStruct->remoteId != $loadedContentTypeDraft->remoteId )
        {
            try
            {
                $this->loadContentTypeByRemoteId( $contentTypeUpdateStruct->remoteId );
                throw new InvalidArgumentException(
                    "\$contentTypeUpdateStruct",
                    "Another ContentType with remoteId '{$contentTypeUpdateStruct->remoteId}' exists"
                );
            }
            catch ( APINotFoundException $e )
            {
                // Do nothing
            }
        }
        $this->repository->beginTransaction();
        try
        {
            $this->contentTypeHandler->update(
                $contentTypeDraft->id,
                $contentTypeDraft->status,
                $this->buildSPIContentTypeUpdateStruct(
                    $loadedContentTypeDraft,
                    $contentTypeUpdateStruct
                )
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentTypeService::updateContentTypeGroup (APIContentTypeGroup $contentTypeGroup, ContentTypeGroupUpdateStruct $contentTypeGroupUpdateStruct)
Update a Content Type Group object
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to create a content type group
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the given identifier (if set) already exists
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroup $contentTypeGroup the content type group to be updated
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroupUpdateStruct $contentTypeGroupUpdateStruct
Definition at line 237 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeGroup(), and eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeGroupByIdentifier().
    {
        if ( $this->repository->hasAccess( 'class', 'update' ) !== true )
            throw new UnauthorizedException( 'ContentType', 'update' );
        $loadedContentTypeGroup = $this->loadContentTypeGroup( $contentTypeGroup->id );
        if ( $contentTypeGroupUpdateStruct->identifier !== null
            && $contentTypeGroupUpdateStruct->identifier !== $loadedContentTypeGroup->identifier )
        {
            try
            {
                $this->loadContentTypeGroupByIdentifier( $contentTypeGroupUpdateStruct->identifier );
                throw new InvalidArgumentException(
                    '$contentTypeGroupUpdateStruct->identifier',
                    "given identifier already exists"
                );
            }
            catch ( APINotFoundException $e )
            {
                // Do nothing
            }
        }
        if ( $contentTypeGroupUpdateStruct->modificationDate !== null )
        {
            $modifiedTimestamp = $contentTypeGroupUpdateStruct->modificationDate->getTimestamp();
        }
        else
        {
            $modifiedTimestamp = time();
        }
        $spiGroupUpdateStruct = new SPIContentTypeGroupUpdateStruct(
            array(
                "id" => $loadedContentTypeGroup->id,
                "identifier" => $contentTypeGroupUpdateStruct->identifier === null ?
                    $loadedContentTypeGroup->identifier :
                    $contentTypeGroupUpdateStruct->identifier,
                "modified" => $modifiedTimestamp,
                "modifierId" => $contentTypeGroupUpdateStruct->modifierId === null ?
                    $this->repository->getCurrentUser()->id :
                    $contentTypeGroupUpdateStruct->modifierId
            )
        );
        $this->repository->beginTransaction();
        try
        {
            $this->contentTypeHandler->updateGroup(
                $spiGroupUpdateStruct
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentTypeService::updateFieldDefinition (APIContentTypeDraft $contentTypeDraft, APIFieldDefinition $fieldDefinition, FieldDefinitionUpdateStruct $fieldDefinitionUpdateStruct)
Update a field definition
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the field id in the update struct is not found or does not belong to the content type If the given identifier is used in an existing field of the given content type
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to edit a content type
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentTypeDraft $contentTypeDraft the content type draft
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition the field definition which should be updated
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinitionUpdateStruct $fieldDefinitionUpdateStruct
Definition at line 1397 of file ContentTypeService.php.
References eZ\Publish\Core\Repository\ContentTypeService\loadContentTypeDraft().
    {
        if ( $this->repository->hasAccess( 'class', 'update' ) !== true )
            throw new UnauthorizedException( 'ContentType', 'update' );
        $loadedContentTypeDraft = $this->loadContentTypeDraft( $contentTypeDraft->id );
        $foundFieldId = false;
        foreach ( $loadedContentTypeDraft->fieldDefinitions as $existingFieldDefinition )
        {
            if ( $existingFieldDefinition->id == $fieldDefinition->id )
            {
                $foundFieldId = true;
            }
            else if ( $existingFieldDefinition->identifier == $fieldDefinitionUpdateStruct->identifier )
            {
                throw new InvalidArgumentException(
                    "\$fieldDefinitionUpdateStruct",
                    "Another FieldDefinition with identifier '{$fieldDefinitionUpdateStruct->identifier}' exists in the ContentType"
                );
            }
        }
        if ( !$foundFieldId )
        {
            throw new InvalidArgumentException(
                "\$fieldDefinition",
                "The given FieldDefinition does not belong to the ContentType"
            );
        }
        $spiFieldDefinitionUpdateStruct = $this->buildSPIFieldDefinitionUpdate(
            $fieldDefinitionUpdateStruct,
            $fieldDefinition
        );
        $this->repository->beginTransaction();
        try
        {
            $this->contentTypeHandler->updateFieldDefinition(
                $contentTypeDraft->id,
                SPIContentType::STATUS_DRAFT,
                $spiFieldDefinitionUpdateStruct
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
Member Data Documentation
eZ\Publish\Core\Repository\ContentTypeService::$contentTypeHandler protected
Definition at line 65 of file ContentTypeService.php.
eZ\Publish\Core\Repository\ContentTypeService::$repository protected
Definition at line 60 of file ContentTypeService.php.
eZ\Publish\Core\Repository\ContentTypeService::$settings protected
Definition at line 70 of file ContentTypeService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/ContentTypeService.php