ezp-next: eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestFieldDefinition Class Reference
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestFieldDefinition Class Reference
Public Member Functions
__construct (UrlHandler $urlHandler, FieldTypeSerializer $fieldTypeSerializer)
visit (Visitor $visitor, Generator $generator, $data)
Protected Attributes
$fieldTypeSerializer
Additional Inherited Members
Protected Member Functions inherited from eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestContentTypeBase
getUrlTypeSuffix ($contentTypeStatus)
serializeStatus ($contentTypeStatus)
Detailed Description
RestFieldDefinition value object visitor
Todo:
$fieldSettings & $validatorConfiguration (missing from spec)
Definition at line 24 of file RestFieldDefinition.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestFieldDefinition::__construct (UrlHandler $urlHandler, FieldTypeSerializer $fieldTypeSerializer)
Parameters
\eZ\Publish\Core\REST\Common\UrlHandler $urlHandler
\eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer $fieldTypeSerializer
Definition at line 35 of file RestFieldDefinition.php.
References eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestFieldDefinition\$fieldTypeSerializer.
    {
        parent::__construct( $urlHandler );
        $this->fieldTypeSerializer = $fieldTypeSerializer;
    }
Member Function Documentation
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestFieldDefinition::visit (Visitor $visitor, Generator $generator, $data)
Visit struct returned by controllers
Parameters
\eZ\Publish\Core\REST\Common\Output\Visitor $visitor
\eZ\Publish\Core\REST\Common\Output\Generator $generator
\eZ\Publish\Core\REST\Server\Values\RestFieldDefinition $data
Reimplemented from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor.
Reimplemented in eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedFieldDefinition.
Definition at line 48 of file RestFieldDefinition.php.
References eZ\Publish\Core\REST\Common\Output\Generator\endAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\endObjectElement(), eZ\Publish\Core\REST\Common\Output\Generator\endValueElement(), eZ\Publish\Core\REST\Common\Output\Generator\getMediaType(), eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestContentTypeBase\getUrlTypeSuffix(), eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor\serializeBool(), eZ\Publish\Core\REST\Common\Output\Visitor\setHeader(), eZ\Publish\Core\REST\Common\Output\Generator\startAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\startObjectElement(), eZ\Publish\Core\REST\Common\Output\Generator\startValueElement(), eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor\visitDescriptionsList(), and eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor\visitNamesList().
    {
        $restFieldDefinition = $data;
        $fieldDefinition = $restFieldDefinition->fieldDefinition;
        $contentType = $restFieldDefinition->contentType;
        $urlTypeSuffix = $this->getUrlTypeSuffix( $contentType->status );
        $generator->startObjectElement( 'FieldDefinition' );
        $visitor->setHeader( 'Content-Type', $generator->getMediaType( 'FieldDefinition' ) );
        if ( $contentType->status === APIContentType::STATUS_DRAFT )
        {
            $visitor->setHeader( 'Accept-Patch', $generator->getMediaType( 'FieldDefinitionUpdate' ) );
        }
        $generator->startAttribute(
            'href',
            $this->urlHandler->generate(
                'typeFieldDefinition'  . $urlTypeSuffix,
                array(
                    'type' => $contentType->id,
                    'fieldDefinition' => $fieldDefinition->id,
                )
            )
        );
        $generator->endAttribute( 'href' );
        $generator->startValueElement( 'id', $fieldDefinition->id );
        $generator->endValueElement( 'id' );
        $generator->startValueElement( 'identifier', $fieldDefinition->identifier );
        $generator->endValueElement( 'identifier' );
        $generator->startValueElement( 'fieldType', $fieldDefinition->fieldTypeIdentifier );
        $generator->endValueElement( 'fieldType' );
        $generator->startValueElement( 'fieldGroup', $fieldDefinition->fieldGroup );
        $generator->endValueElement( 'fieldGroup' );
        $generator->startValueElement( 'position', $fieldDefinition->position );
        $generator->endValueElement( 'position' );
        $generator->startValueElement( 'isTranslatable', $this->serializeBool( $fieldDefinition->isTranslatable ) );
        $generator->endValueElement( 'isTranslatable' );
        $generator->startValueElement( 'isRequired', $this->serializeBool( $fieldDefinition->isRequired ) );
        $generator->endValueElement( 'isRequired' );
        $generator->startValueElement( 'isInfoCollector', $this->serializeBool( $fieldDefinition->isInfoCollector ) );
        $generator->endValueElement( 'isInfoCollector' );
        $this->fieldTypeSerializer->serializeFieldDefaultValue(
            $generator,
            $fieldDefinition,
            $fieldDefinition->defaultValue
        );
        $generator->startValueElement( 'isSearchable', $this->serializeBool( $fieldDefinition->isSearchable ) );
        $generator->endValueElement( 'isSearchable' );
        $this->visitNamesList( $generator, $fieldDefinition->getNames() );
        $descriptions = $fieldDefinition->getDescriptions();
        if ( is_array( $descriptions ) )
        {
            $this->visitDescriptionsList( $generator, $descriptions );
        }
        $this->fieldTypeSerializer->serializeFieldSettings(
            $generator,
            $fieldDefinition,
            $fieldDefinition->getFieldSettings()
        );
        $this->fieldTypeSerializer->serializeValidatorConfiguration(
            $generator,
            $fieldDefinition,
            $fieldDefinition->getValidatorConfiguration()
        );
        $generator->endObjectElement( 'FieldDefinition' );
    }
Member Data Documentation
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestFieldDefinition::$fieldTypeSerializer protected
Definition at line 29 of file RestFieldDefinition.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestFieldDefinition.php