ezp-next: eZ\Publish\Core\REST\Common\Input\ParserTools Class Reference
eZ\Publish\Core\REST\Common\Input\ParserTools Class Reference
Public Member Functions
parseObjectElement (array $objectElement, ParsingDispatcher $parsingDispatcher)
isEmbeddedObject (array $objectElement)
parseTranslatableList (array $listElement)
parseBooleanValue ($stringValue)
parseStatus ($contentTypeStatus)
parseDefaultSortField ($defaultSortFieldString)
parseDefaultSortOrder ($defaultSortOrderString)
parseLimitation (array $limitation)
Protected Member Functions
getLimitationByIdentifier ($identifier)
Detailed Description
Tools object to be used in Input Parsers
Definition at line 20 of file ParserTools.php.
Member Function Documentation
eZ\Publish\Core\REST\Common\Input\ParserTools::getLimitationByIdentifier ($identifier) protected
Instantiates Limitation object based on identifier
Parameters
string $identifier
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException
Returns
Todo:
Use dependency injection system
Definition at line 229 of file ParserTools.php.
    {
        switch ( $identifier )
        {
            case Values\User\Limitation::CONTENTTYPE:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\ContentTypeLimitation();
            case Values\User\Limitation::LANGUAGE:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\LanguageLimitation();
            case Values\User\Limitation::LOCATION:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\LocationLimitation();
            case Values\User\Limitation::OWNER:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\OwnerLimitation();
            case Values\User\Limitation::PARENTOWNER:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\ParentOwnerLimitation();
            case Values\User\Limitation::PARENTCONTENTTYPE:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\ParentContentTypeLimitation();
            case Values\User\Limitation::PARENTDEPTH:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\ParentDepthLimitation();
            case Values\User\Limitation::SECTION:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\SectionLimitation();
            case Values\User\Limitation::SITEACCESS:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\SiteaccessLimitation();
            case Values\User\Limitation::STATE:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\StateLimitation();
            case Values\User\Limitation::SUBTREE:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\SubtreeLimitation();
            case Values\User\Limitation::USERGROUP:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\UserGroupLimitation();
            case Values\User\Limitation::PARENTUSERGROUP:
                return new \eZ\Publish\API\Repository\Values\User\Limitation\ParentUserGroupLimitation();
            default:
                throw new \eZ\Publish\Core\Base\Exceptions\NotFoundException( 'Limitation', $identifier );
        }
    }
eZ\Publish\Core\REST\Common\Input\ParserTools::isEmbeddedObject (array $objectElement)
Returns if the given $objectElement has embedded object data or is only a reference
Parameters
array $objectElement
Returns
boolean
Definition at line 50 of file ParserTools.php.
    {
        foreach ( $objectElement as $childKey => $childValue )
        {
            $childKeyIndicator = substr( $childKey, 0, 1 );
            if ( $childKeyIndicator !== '#' && $childKeyIndicator !== '_' )
            {
                return true;
            }
        }
        return false;
    }
eZ\Publish\Core\REST\Common\Input\ParserTools::parseBooleanValue ($stringValue)
Parses a boolean from $stringValue
Parameters
string $stringValue
Returns
boolean
Definition at line 87 of file ParserTools.php.
    {
        switch ( strtolower( $stringValue ) )
        {
            case 'true':
                return true;
            case 'false':
                return false;
        }
        throw new RuntimeException( "Unknown boolean value '{$stringValue}'." );
    }
eZ\Publish\Core\REST\Common\Input\ParserTools::parseDefaultSortField ($defaultSortFieldString)
Parses the default sort field from the given $defaultSortFieldString
Parameters
string $defaultSortFieldString
Returns
int
Definition at line 129 of file ParserTools.php.
    {
        switch ( $defaultSortFieldString )
        {
            case 'PATH':
                return Values\Content\Location::SORT_FIELD_PATH;
            case 'PUBLISHED':
                return Values\Content\Location::SORT_FIELD_PUBLISHED;
            case 'MODIFIED':
                return Values\Content\Location::SORT_FIELD_MODIFIED;
            case 'SECTION':
                return Values\Content\Location::SORT_FIELD_SECTION;
            case 'DEPTH':
                return Values\Content\Location::SORT_FIELD_DEPTH;
            case 'CLASS_IDENTIFIER':
                return Values\Content\Location::SORT_FIELD_CLASS_IDENTIFIER;
            case 'CLASS_NAME':
                return Values\Content\Location::SORT_FIELD_CLASS_NAME;
            case 'PRIORITY':
                return Values\Content\Location::SORT_FIELD_PRIORITY;
            case 'NAME':
                return Values\Content\Location::SORT_FIELD_NAME;
            case 'MODIFIED_SUBNODE':
                return Values\Content\Location::SORT_FIELD_MODIFIED_SUBNODE;
            case 'NODE_ID':
                return Values\Content\Location::SORT_FIELD_NODE_ID;
            case 'CONTENTOBJECT_ID':
                return Values\Content\Location::SORT_FIELD_CONTENTOBJECT_ID;
        }
        throw new \RuntimeException( "Unknown default sort field: '{$defaultSortFieldString}'." );
    }
eZ\Publish\Core\REST\Common\Input\ParserTools::parseDefaultSortOrder ($defaultSortOrderString)
Parses the default sort order from the given $defaultSortOrderString
Parameters
string $defaultSortOrderString
Returns
int
Definition at line 169 of file ParserTools.php.
    {
        switch ( strtoupper( $defaultSortOrderString ) )
        {
            case 'ASC':
                return Values\Content\Location::SORT_ORDER_ASC;
            case 'DESC':
                return Values\Content\Location::SORT_ORDER_DESC;
        }
        throw new \RuntimeException( "Unknown default sort order: '{$defaultSortOrderString}'." );
    }
eZ\Publish\Core\REST\Common\Input\ParserTools::parseLimitation (array $limitation)
Parses the input structure to Limitation object
Parameters
array $limitation
Returns
Definition at line 189 of file ParserTools.php.
References eZ\Publish\Core\REST\Common\Input\ParserTools\getLimitationByIdentifier().
    {
        if ( !array_key_exists( '_identifier', $limitation ) )
        {
            throw new Exceptions\Parser( "Missing '_identifier' attribute for Limitation." );
        }
        $limitationObject = $this->getLimitationByIdentifier( $limitation['_identifier'] );
        if ( !isset( $limitation['values']['ref'] ) || !is_array( $limitation['values']['ref'] ) )
        {
            throw new Exceptions\Parser( "Invalid format for limitation values in Limitation." );
        }
        $limitationValues = array();
        foreach ( $limitation['values']['ref'] as $limitationValue )
        {
            if ( !array_key_exists( '_href', $limitationValue ) )
            {
                throw new Exceptions\Parser( "Invalid format for limitation values in Limitation." );
            }
            $limitationValues[] = $limitationValue['_href'];
        }
        $limitationObject->limitationValues = $limitationValues;
        return $limitationObject;
    }
eZ\Publish\Core\REST\Common\Input\ParserTools::parseObjectElement (array $objectElement, ParsingDispatcher $parsingDispatcher)
Parses the given $objectElement, if it contains embedded data
Parameters
array $objectElement
\eZ\Publish\Core\REST\Common\Input\ParsingDispatcher $parsingDispatcher
Returns
mixed
Definition at line 30 of file ParserTools.php.
References eZ\Publish\Core\REST\Common\Input\ParserTools\isEmbeddedObject(), and eZ\Publish\Core\REST\Common\Input\ParsingDispatcher\parse().
    {
        if ( $this->isEmbeddedObject( $objectElement ) )
        {
            $parsingDispatcher->parse(
                $objectElement,
                $objectElement['_media-type']
            );
        }
        return $objectElement['_href'];
    }
eZ\Publish\Core\REST\Common\Input\ParserTools::parseStatus ($contentTypeStatus)
Parses the content types status from $contentTypeStatus
Parameters
string $contentTypeStatus
Returns
int
Definition at line 107 of file ParserTools.php.
    {
        switch ( strtoupper( $contentTypeStatus ) )
        {
            case 'DEFINED':
                return Values\ContentType\ContentType::STATUS_DEFINED;
            case 'DRAFT':
                return Values\ContentType\ContentType::STATUS_DRAFT;
            case 'MODIFIED':
                return Values\ContentType\ContentType::STATUS_MODIFIED;
        }
        throw new \RuntimeException( "Unknown ContentType status '{$contentTypeStatus}.'" );
    }
eZ\Publish\Core\REST\Common\Input\ParserTools::parseTranslatableList (array $listElement)
Parses a translatable list, like names or descriptions
Parameters
array $listElement
Returns
array
Definition at line 70 of file ParserTools.php.
    {
        $listItems = array();
        foreach ( $listElement['value'] as $valueRow )
        {
            $listItems[$valueRow['_languageCode']] = $valueRow['#text'];
        }
        return $listItems;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/Input/ParserTools.php