ezp-next: eZ\Publish\Core\IO\LegacyHandler Class Reference
eZ\Publish\Core\IO\LegacyHandler Class Reference
Public Member Functions
__construct (LegacyKernel $legacyKernel)
create (BinaryFileCreateStruct $createFilestruct)
delete ($path)
update ($path, BinaryFileUpdateStruct $updateFileStruct)
exists ($path)
load ($path)
getFileResource ($path)
getFileContents ($path)
Protected Member Functions
getMimeTypeFromLocalFile ($path)
Detailed Description
Legacy Io/Storage handler, based on eZ Cluster
Due to the legacy API, this handler has a few limitations:
ctime is not really supported, and will always have the same value as mtime
mtime can not be modified, and will always automatically be set depending on the server time upon each write operation
Definition at line 31 of file LegacyHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\IO\LegacyHandler::__construct (LegacyKernel $legacyKernel)
Created Legacy handler instance
Parameters
\eZ\Publish\Core\MVC\Legacy\Kernel $legacyKernel
Definition at line 55 of file LegacyHandler.php.
    {
        $this->legacyKernel = $legacyKernel;
    }
Member Function Documentation
eZ\Publish\Core\IO\LegacyHandler::create (BinaryFileCreateStruct $createFilestruct)
Creates and stores a new BinaryFile based on the BinaryFileCreateStruct $file
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException If the target path already exists
Parameters
\eZ\Publish\SPI\IO\BinaryFileCreateStruct $createFilestruct
Returns
The newly created BinaryFile object
Implements eZ\Publish\SPI\IO\Handler.
Definition at line 69 of file LegacyHandler.php.
References eZ\Publish\Core\IO\LegacyHandler\exists(), eZ\Publish\SPI\IO\BinaryFileCreateStruct\getInputStream(), and eZ\Publish\Core\IO\LegacyHandler\load().
    {
        if ( $this->exists( $createFilestruct->path ) )
        {
            throw new InvalidArgumentException(
                "\$createFilestruct->path",
                "file '{$createFilestruct->path}' already exists"
            );
        }
        $clusterHandler = $this->getClusterHandler();
        $this->legacyKernel->runCallback(
            function () use ( $createFilestruct, $clusterHandler )
            {
                // @todo Build a path / scope mapper
                $scope = 'todo';
                $clusterHandler->fileStoreContents(
                    $createFilestruct->path,
                    fread( $createFilestruct->getInputStream(), $createFilestruct->size ),
                    $createFilestruct->mimeType,
                    $scope
                );
            },
            false
        );
        return $this->load( $createFilestruct->path );
    }
eZ\Publish\Core\IO\LegacyHandler::delete ($path)
Deletes the existing BinaryFile with path $path
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If the file doesn't exist
Parameters
string $path
Implements eZ\Publish\SPI\IO\Handler.
Definition at line 105 of file LegacyHandler.php.
References eZ\Publish\Core\IO\LegacyHandler\exists().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        $clusterHandler = $this->getClusterHandler();
        $this->legacyKernel->runCallback(
            function () use ( $path, $clusterHandler )
            {
                $clusterHandler->fileDelete( $path );
            },
            false
        );
    }
eZ\Publish\Core\IO\LegacyHandler::exists ($path)
Checks if the BinaryFile with path $path exists
Parameters
string $path
Returns
boolean
Implements eZ\Publish\SPI\IO\Handler.
Definition at line 187 of file LegacyHandler.php.
    {
        $clusterHandler = $this->getClusterHandler();
        return $this->legacyKernel->runCallback(
            function () use ( $clusterHandler, $path )
            {
                return $clusterHandler->fileExists( $path );
            },
            false
        );
    }
eZ\Publish\Core\IO\LegacyHandler::getFileContents ($path)
Returns the contents of the BinaryFile identified by $path
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException if the file couldn't be found
Parameters
string $path
Returns
string
Implements eZ\Publish\SPI\IO\Handler.
Definition at line 272 of file LegacyHandler.php.
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        $clusterHandler = $this->getClusterHandler();
        return $this->legacyKernel->runCallback(
            function () use ( $path, $clusterHandler )
            {
                return $clusterHandler->fileFetchContents( $path );
            },
            false
        );
    }
eZ\Publish\Core\IO\LegacyHandler::getFileResource ($path)
Returns a file resource to the BinaryFile identified by $path
Parameters
string $path
Returns
resource
Implements eZ\Publish\SPI\IO\Handler.
Definition at line 258 of file LegacyHandler.php.
    {
        return $this->getFileResourceProvider()->getResource( $this->load( $path ) );// @todo incorrect object provided to getResource?
    }
eZ\Publish\Core\IO\LegacyHandler::getMimeTypeFromLocalFile ($path) protected
Returns a mimeType from a local file, using fileinfo
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If file does not exist
Todo:
If legacy path is made available then this function can use that to skip executing legacy kernel
Parameters
string $path
Returns
string
Definition at line 344 of file LegacyHandler.php.
    {
        $returnValue = $this->legacyKernel->runCallback(
            function () use ( $path )
            {
                if ( !is_file( $path ) )
                    return null;
                $fileInfo = new finfo( FILEINFO_MIME_TYPE );
                return $fileInfo->file( $path );
            },
            false
        );
        if ( $returnValue === null )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        return $returnValue;
    }
eZ\Publish\Core\IO\LegacyHandler::load ($path)
Loads the BinaryFile identified by $path
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If no file identified by $path exists
Parameters
string $path
Returns
Implements eZ\Publish\SPI\IO\Handler.
Definition at line 208 of file LegacyHandler.php.
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        $metaData = $this->legacyKernel->runCallback(
            function () use ( $path )
            {
                $clusterFile = eZClusterFileHandler::instance( $path );
                return $clusterFile->metaData;
            },
            false
        );
        $file = new BinaryFile();
        $file->path = $path;
        $file->mtime = new DateTime();
        $file->mtime->setTimestamp( $metaData['mtime'] );
        // Setting the same timestamp as mtime, since ctime is not supported in Legacy
        $file->ctime = clone $file->mtime;
        $file->size = $metaData['size'];
        // will only work with some ClusterFileHandlers (DB based ones, not with FS ones)
        if ( isset( $metaData['datatype'] ) )
        {
            $file->mimeType = $metaData['datatype'];
        }
        else
        {
            $file->mimeType = $this->getMimeTypeFromLocalFile( $path );
        }
        $file->uri = $file->path;
        $file->originalFile = basename( $file->path );
        return $file;
    }
eZ\Publish\Core\IO\LegacyHandler::update ($path, BinaryFileUpdateStruct $updateFileStruct)
Updates the file identified by $path with data from $updateFile
Exceptions
\eZ\Publish\Core\Base\Exceptions\NotFoundException If the source path doesn't exist
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException If the target path already exists
Parameters
string $path
\eZ\Publish\SPI\IO\BinaryFileUpdateStruct $updateFileStruct
Returns
The updated BinaryFile
Implements eZ\Publish\SPI\IO\Handler.
Definition at line 133 of file LegacyHandler.php.
References eZ\Publish\Core\IO\LegacyHandler\exists(), and eZ\Publish\SPI\IO\BinaryFileUpdateStruct\getInputStream().
    {
        if ( !$this->exists( $path ) )
        {
            throw new NotFoundException( 'BinaryFile', $path );
        }
        $clusterHandler = $this->getClusterHandler();
        $path = $this->legacyKernel->runCallback(
            function () use ( $path, $updateFileStruct, $clusterHandler )
            {
                // path
                if ( $updateFileStruct->path !== null && $updateFileStruct->path != $path )
                {
                    if ( $clusterHandler->fileExists( $updateFileStruct->path ) )
                    {
                        throw new InvalidArgumentException(
                            "\$updateFileStruct->path",
                            "file '{$updateFileStruct->path}' already exists"
                        );
                    }
                    $clusterHandler->fileMove( $path, $updateFileStruct->path );
                    // update the path we are working on
                    $path = $updateFileStruct->path;
                }
                $resource = $updateFileStruct->getInputStream();
                if ( $resource !== null )
                {
                    $binaryUpdateData = fread( $resource, $updateFileStruct->size );
                    $clusterFile = eZClusterFileHandler::instance( $path );
                    $metaData = $clusterFile->metaData;
                    $scope = isset( $metaData['scope'] ) ? $metaData['scope'] : false;
                    $datatype = isset( $metaData['datatype'] ) ? $metaData['datatype'] : false;
                    $clusterFile->storeContents( $binaryUpdateData, $scope, $datatype );
                }
                // mtime and ctime have no effect as mtime isn't modifiable, and ctime isn't really supported (=mtime)
                return $path;
            },
            false
        );
        return $this->load( $path );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/IO/LegacyHandler.php