ezp-next: eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI Class Reference
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI Class Reference
Public Member Functions
__construct (array $siteAccessesConfiguration)
setRequest (SimplifiedRequest $request)
getName ()
analyseURI ($uri)
analyseLink ($linkUri)
Public Member Functions inherited from eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map
setMapKey ($key)
match ()
Additional Inherited Members
Protected Attributes inherited from eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map
$key
$map
Detailed Description
Definition at line 17 of file URI.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI::__construct (array $siteAccessesConfiguration)
Constructor.
Parameters
array $siteAccessesConfiguration SiteAccesses configuration.
Reimplemented from eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map.
Definition at line 24 of file URI.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\__construct().
    {
        parent::__construct( $siteAccessesConfiguration );
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI::analyseLink ($linkUri)
Analyses $linkUri when generating a link to a route, in order to have the siteaccess part back in the URI.
Parameters
string $linkUri
Returns
string The modified link URI
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\URILexer.
Definition at line 66 of file URI.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI\analyseLink().
    {
        if ( strpos( $linkUri, $this->key ) === false )
        {
            $linkUri = '/' . $this->key . $linkUri;
        }
        return $linkUri;
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI::analyseURI ($uri)
Fixes up $uri to remove the siteaccess part, if needed.
Parameters
string $uri The original URI
Returns
string
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\URILexer.
Definition at line 54 of file URI.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI\analyseURI().
    {
        return str_replace( "/$this->key", '', $uri );
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI::getName ()
Returns the matcher's name. This information will be stored in the SiteAccess object itself to quickly be able to identify the matcher type.
Returns
string
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 42 of file URI.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI\getName().
    {
        return 'uri:map';
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI::setRequest (SimplifiedRequest $request)
Injects the request object to match against.
Parameters
\eZ\Publish\Core\MVC\Symfony\Routing\SimplifiedRequest $request
Returns
void
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 36 of file URI.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\$key, eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\setMapKey(), and eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI\setRequest().
    {
        sscanf( $request->pathinfo, "/%[^/]", $key );
        $this->setMapKey( $key );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Map/URI.php