ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler Class Reference
Public Member Functions
__construct (Gateway $contentTypeGateway, Mapper $mapper, UpdateHandler $updateHandler)
createGroup (GroupCreateStruct $createStruct)
updateGroup (GroupUpdateStruct $struct)
deleteGroup ($groupId)
loadGroup ($groupId)
loadGroupByIdentifier ($identifier)
loadAllGroups ()
loadContentTypes ($groupId, $status=0)
load ($contentTypeId, $status=Type::STATUS_DEFINED)
loadByIdentifier ($identifier)
loadByRemoteId ($remoteId)
create (CreateStruct $createStruct)
update ($typeId, $status, UpdateStruct $contentType)
delete ($contentTypeId, $status)
createDraft ($modifierId, $contentTypeId)
copy ($userId, $contentTypeId, $status)
unlink ($groupId, $contentTypeId, $status)
link ($groupId, $contentTypeId, $status)
getFieldDefinition ($id, $status)
addFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
removeFieldDefinition ($contentTypeId, $status, $fieldDefinitionId)
updateFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
publish ($contentTypeId)
Public Member Functions inherited from eZ\Publish\SPI\Persistence\Content\Type\Handler
create (CreateStruct $contentType)
update ($contentTypeId, $status, UpdateStruct $contentType)
Protected Member Functions
loadFromRows (array $rows, $typeIdentifier, $status)
internalCreate (CreateStruct $createStruct, $contentTypeId=null)
Protected Attributes
$contentTypeGateway
$mapper
$updateHandler
Detailed Description
Definition at line 29 of file Handler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::__construct (Gateway $contentTypeGateway, Mapper $mapper, UpdateHandler $updateHandler)
Creates a new content type handler.
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway $contentTypeGateway
\eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper $mapper
\eZ\Publish\Core\Persistence\Legacy\Content\Type\Update\Handler $updateHandler
Definition at line 57 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\$mapper.
    {
        $this->contentTypeGateway = $contentTypeGateway;
        $this->mapper = $mapper;
        $this->updateHandler = $updateHandler;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::addFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
Adds a new field definition to an existing Type.
This method creates a new status of the Type with the $fieldDefinition added. It does not update existing content objects depending on the field (default) values.
Parameters
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 513 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\addFieldDefinition().
    {
        $storageFieldDef = new StorageFieldDefinition();
        $this->mapper->toStorageFieldDefinition(
            $fieldDefinition, $storageFieldDef
        );
        $fieldDefinition->id = $this->contentTypeGateway->insertFieldDefinition(
            $contentTypeId, $status, $fieldDefinition, $storageFieldDef
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::copy ($userId, $contentTypeId, $status)
Parameters
mixed $userId
mixed $contentTypeId
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Returns
Type
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 404 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Handler\internalCreate(), and eZ\Publish\Core\Persistence\Legacy\Content\Handler\load().
    {
        $createStruct = $this->mapper->createCreateStructFromType(
            $this->load( $contentTypeId, $status )
        );
        $createStruct->modifierId = $userId;
        $createStruct->created = $createStruct->modified = time();
        $createStruct->creatorId = $userId;
        $createStruct->identifier .= '_' . ( $createStruct->remoteId = md5( uniqid( get_class( $createStruct ), true ) ) );
        // Set FieldDefinition ids to null to trigger creating new id
        foreach ( $createStruct->fieldDefinitions as $fieldDefinition )
        {
            $fieldDefinition->id = null;
        }
        return $this->internalCreate( $createStruct );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::create (CreateStruct $createStruct)
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\CreateStruct $createStruct
Returns
Definition at line 257 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\internalCreate().
    {
        return $this->internalCreate( $createStruct );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::createDraft ($modifierId, $contentTypeId)
Creates a draft of existing defined content type
Updates modified date, sets $modifierId and status to Type::STATUS_DRAFT on the new returned draft.
Parameters
mixed $modifierId
mixed $contentTypeId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type with defined status is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 385 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$modifierId, eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\createDraft(), eZ\Publish\Core\Persistence\Legacy\Content\Handler\internalCreate(), eZ\Publish\Core\Persistence\Legacy\Content\Handler\load(), eZ\Publish\SPI\Persistence\Content\Type\STATUS_DEFINED, and eZ\Publish\SPI\Persistence\Content\Type\STATUS_DRAFT.
    {
        $createStruct = $this->mapper->createCreateStructFromType(
            $this->load( $contentTypeId, Type::STATUS_DEFINED )
        );
        $createStruct->status = Type::STATUS_DRAFT;
        $createStruct->modifierId = $modifierId;
        $createStruct->modified = time();
        return $this->internalCreate( $createStruct, $contentTypeId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::createGroup (GroupCreateStruct $createStruct)
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group\CreateStruct $createStruct
Returns
Group
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 72 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\createGroup().
    {
        $group = $this->mapper->createGroupFromCreateStruct(
            $createStruct
        );
        $group->id = $this->contentTypeGateway->insertGroup(
            $group
        );
        return $group;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::delete ($contentTypeId, $status)
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException If type is defined and still has content
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type is not found
Parameters
mixed $contentTypeId
int $status
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 344 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\SPI\Persistence\Content\Type\STATUS_DEFINED.
    {
        if ( !$this->contentTypeGateway->loadTypeData( $contentTypeId, $status ) )
        {
            throw new NotFoundException(
                "ContentType",
                array(
                    "id" => $contentTypeId,
                    "status" => $status
                )
            );
        }
        if ( Type::STATUS_DEFINED === $status && $this->contentTypeGateway->countInstancesOfType( $contentTypeId ) )
        {
            throw new BadStateException(
                "\$contentTypeId",
                "ContentType with given id still has content instances and therefore can't be deleted"
            );
        }
        $this->contentTypeGateway->delete(
            $contentTypeId, $status
        );
        // @todo FIXME: Return true only if deletion happened
        return true;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::deleteGroup ($groupId)
Parameters
mixed $groupId
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException If type group contains types
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type group with id is not found
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 104 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\deleteGroup().
    {
        if ( $this->contentTypeGateway->countTypesInGroup( $groupId ) !== 0 )
        {
            throw new Exception\GroupNotEmpty( $groupId );
        }
        $this->contentTypeGateway->deleteGroup( $groupId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::getFieldDefinition ($id, $status)
Returns field definition for the given field definition id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If field definition is not found
Parameters
mixed $id
int $status One of Type::STATUS_DEFINED|Type::STATUS_DRAFT|Type::STATUS_MODIFIED
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 482 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$id, eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\getFieldDefinition().
    {
        $row = $this->contentTypeGateway->loadFieldDefinition( $id, $status );
        if ( $row === false )
        {
            throw new NotFoundException(
                "FieldDefinition",
                array(
                    "id" => $id,
                    "status" => $status
                )
            );
        }
        return $this->mapper->extractFieldFromRow( $row );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::internalCreate (CreateStruct $createStruct, $contentTypeId = null) protected
Internal method for creating ContentType
Used by self::create(), self::createDraft() and self::copy()
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\CreateStruct $createStruct
mixed | null $contentTypeId Used by self::createDraft() to retain ContentType id in the draft
Returns
Definition at line 272 of file Handler.php.
    {
        foreach ( $createStruct->fieldDefinitions as $fieldDef )
        {
            if ( !is_int( $fieldDef->position ) || $fieldDef->position <= 0 )
                throw new InvalidArgumentException(
                    "position",
                    "'" . var_export( $fieldDef->position, true ) .
                    "' is wrong value in class FieldDefinition, an integer strictly greater than 0 is required."
                );
        }
        $createStruct = clone $createStruct;
        $contentType = $this->mapper->createTypeFromCreateStruct(
            $createStruct
        );
        $contentType->id = $this->contentTypeGateway->insertType(
            $contentType,
            $contentTypeId
        );
        foreach ( $contentType->groupIds as $groupId )
        {
            $this->contentTypeGateway->insertGroupAssignment(
                $groupId,
                $contentType->id,
                $contentType->status
            );
        }
        foreach ( $contentType->fieldDefinitions as $fieldDef )
        {
            $storageFieldDef = new StorageFieldDefinition();
            $this->mapper->toStorageFieldDefinition( $fieldDef, $storageFieldDef );
            $fieldDef->id = $this->contentTypeGateway->insertFieldDefinition(
                $contentType->id,
                $contentType->status,
                $fieldDef,
                $storageFieldDef
            );
        }
        return $contentType;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::link ($groupId, $contentTypeId, $status)
Link a content type group with a content type
Parameters
mixed $groupId
mixed $contentTypeId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If group or type with provided status is not found
\eZ\Publish\API\Repository\Exceptions\BadStateException If type is already part of group
Todo:
Above throws are not implemented
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 463 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\link().
    {
        $this->contentTypeGateway->insertGroupAssignment(
            $groupId, $contentTypeId, $status
        );
        // @todo FIXME: What is to be returned?
        return true;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::load ($contentTypeId, $status = Type::STATUS_DEFINED)
Parameters
int $contentTypeId
int $status
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 184 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\loadFromRows().
    {
        return $this->loadFromRows(
            $this->contentTypeGateway->loadTypeData(
                $contentTypeId, $status
            ),
            $contentTypeId,
            $status
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::loadAllGroups ()
Returns
Group[]
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 158 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\loadAllGroups().
    {
        return $this->mapper->extractGroupsFromRows(
            $this->contentTypeGateway->loadAllGroupsData()
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::loadByIdentifier ($identifier)
Loads a (defined) content type by identifier
Parameters
string $identifier
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If defined type is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 204 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$identifier, eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\loadByIdentifier(), eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\loadFromRows(), and eZ\Publish\SPI\Persistence\Content\Type\STATUS_DEFINED.
    {
        $rows = $this->contentTypeGateway->loadTypeDataByIdentifier(
            $identifier, Type::STATUS_DEFINED
        );
        return $this->loadFromRows( $rows, $identifier, Type::STATUS_DEFINED );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::loadByRemoteId ($remoteId)
Loads a (defined) content type by remote id
Parameters
mixed $remoteId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If defined type is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 221 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$remoteId, eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\loadByRemoteId(), eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\loadFromRows(), and eZ\Publish\SPI\Persistence\Content\Type\STATUS_DEFINED.
    {
        return $this->loadFromRows(
            $this->contentTypeGateway->loadTypeDataByRemoteId(
                $remoteId, Type::STATUS_DEFINED
            ),
            $remoteId,
            Type::STATUS_DEFINED
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::loadContentTypes ($groupId, $status = 0)
Parameters
mixed $groupId
int $status
Returns
Type[]
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 171 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\loadContentTypes().
    {
        return $this->mapper->extractTypesFromRows(
            $this->contentTypeGateway->loadTypesDataForGroup( $groupId, $status )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::loadFromRows (array $rows, $typeIdentifier, $status) protected
Loads a single Type from $rows
Parameters
array $rows
mixed $typeIdentifier
int $status
Returns
Definition at line 241 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\loadFromRows().
    {
        $types = $this->mapper->extractTypesFromRows( $rows );
        if ( count( $types ) !== 1 )
        {
            throw new Exception\TypeNotFound( $typeIdentifier, $status );
        }
        return $types[0];
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::loadGroup ($groupId)
Parameters
mixed $groupId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type group with $groupId is not found
Returns
Group
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 120 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\loadGroup().
    {
        $groups = $this->mapper->extractGroupsFromRows(
            $this->contentTypeGateway->loadGroupData( $groupId )
        );
        if ( count( $groups ) !== 1 )
        {
            throw new Exception\TypeGroupNotFound( $groupId );
        }
        return $groups[0];
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::loadGroupByIdentifier ($identifier)
Parameters
string $identifier
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If type group with $identifier is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 141 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$identifier, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\loadGroupByIdentifier().
    {
        $groups = $this->mapper->extractGroupsFromRows(
            $this->contentTypeGateway->loadGroupDataByIdentifier( $identifier )
        );
        if ( count( $groups ) !== 1 )
        {
            throw new Exception\TypeGroupNotFound( $identifier );
        }
        return $groups[0];
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::publish ($contentTypeId)
Update content objects
Updates content objects, depending on the changed field definitions.
A content type has a state which tells if its content objects yet have been adapted.
Flags the content type as updated.
Parameters
mixed $contentTypeId
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 583 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\load(), eZ\Publish\SPI\Persistence\Content\Type\STATUS_DEFINED, and eZ\Publish\SPI\Persistence\Content\Type\STATUS_DRAFT.
    {
        $toType = $this->load( $contentTypeId, Type::STATUS_DRAFT );
        try
        {
            $fromType = $this->load( $contentTypeId, Type::STATUS_DEFINED );
            $this->updateHandler->updateContentObjects( $fromType, $toType );
            $this->updateHandler->deleteOldType( $fromType );
        }
        // If no old type is found, no updates are necessary to it
        catch ( Exception\TypeNotFound $e )
        {
        }
        $this->updateHandler->publishNewType( $toType, Type::STATUS_DEFINED );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::removeFieldDefinition ($contentTypeId, $status, $fieldDefinitionId)
Removes a field definition from an existing Type.
This method creates a new status of the Type with the field definition referred to by $fieldDefinitionId removed. It does not update existing content objects depending on the field (default) values.
Parameters
mixed $contentTypeId
mixed $fieldDefinitionId
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 536 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\removeFieldDefinition().
    {
        $this->contentTypeGateway->deleteFieldDefinition(
            $contentTypeId, $status, $fieldDefinitionId
        );
        // @todo FIXME: Return true only if deletion happened
        return true;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::unlink ($groupId, $contentTypeId, $status)
Unlink a content type group from a content type
Parameters
mixed $groupId
mixed $contentTypeId
int $status
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If group or type with provided status is not found
\eZ\Publish\API\Repository\Exceptions\BadStateException If $groupId is last group on $contentTypeId or not a group assigned to type
Todo:
Add throws for NotFound and BadState when group is not assigned to type
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 434 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\unlink().
    {
        $groupCount = $this->contentTypeGateway->countGroupsForType(
            $contentTypeId, $status
        );
        if ( $groupCount < 2 )
        {
            throw new Exception\RemoveLastGroupFromType(
                $contentTypeId, $status
            );
        }
        $this->contentTypeGateway->deleteGroupAssignment(
            $groupId, $contentTypeId, $status
        );
        // @todo FIXME: What is to be returned?
        return true;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::update ($typeId, $status, UpdateStruct $contentType)
Parameters
mixed $typeId
int $status
\eZ\Publish\SPI\Persistence\Content\Type\UpdateStruct $contentType
Returns
Type
Definition at line 325 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, eZ\Publish\Core\Persistence\Legacy\Content\Handler\load(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\update().
    {
        $this->contentTypeGateway->updateType(
            $typeId, $status, $contentType
        );
        return $this->load(
            $typeId, $status
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::updateFieldDefinition ($contentTypeId, $status, FieldDefinition $fieldDefinition)
This method updates the given $fieldDefinition on a Type.
This method creates a new status of the Type with the updated $fieldDefinition. It does not update existing content objects depending on the field (default) values.
Parameters
mixed $contentTypeId
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 558 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\updateFieldDefinition().
    {
        $storageFieldDef = new StorageFieldDefinition();
        $this->mapper->toStorageFieldDefinition(
            $fieldDefinition, $storageFieldDef
        );
        $this->contentTypeGateway->updateFieldDefinition(
            $contentTypeId, $status, $fieldDefinition, $storageFieldDef
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::updateGroup (GroupUpdateStruct $struct)
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group\UpdateStruct $struct
Returns
Implements eZ\Publish\SPI\Persistence\Content\Type\Handler.
Definition at line 90 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\loadGroup(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler\updateGroup().
    {
        $this->contentTypeGateway->updateGroup(
            $struct
        );
        return $this->loadGroup( $struct->id );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::$contentTypeGateway protected
Definition at line 34 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::$mapper protected
Definition at line 41 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Type\Handler::$updateHandler protected
Definition at line 48 of file Handler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php