ezp-next: eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore Class Reference
eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore Class Reference
Public Member Functions
setFilesystem (Filesystem $fs)
getFilesystem ()
getPath ($key)
purgeByRequest (Request $request)
purgeAllContent ()
getLocationCacheLockName ($locationId=null)
getLocationCacheDir ($locationId=null)
Public Member Functions inherited from eZ\Publish\Core\MVC\Symfony\Cache\Http\Store
__construct ($root)
cleanup ()
lock (Request $request)
unlock (Request $request)
lookup (Request $request)
write (Request $request, Response $response)
invalidate (Request $request)
purge ($url)
Public Attributes
const LOCATION_CACHE_DIR = 'ezlocation'
const LOCATION_STALE_CACHE_DIR = 'ezlocation_stale'
Protected Member Functions
generateContentDigest (Response $response)
Additional Inherited Members
Protected Attributes inherited from eZ\Publish\Core\MVC\Symfony\Cache\Http\Store
$root
Detailed Description
LocationAwareStore implements all the logic for storing cache metadata regarding locations.
Definition at line 20 of file LocationAwareStore.php.
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore::generateContentDigest (Response $response) protected
Injects eZ Publish specific information in the content digest if needed. X-Location-Id response header is set in the ViewController
See Also
::viewLocation()
Parameters
\Symfony\Component\HttpFoundation\Response $response
Returns
string
Reimplemented from eZ\Publish\Core\MVC\Symfony\Cache\Http\Store.
Definition at line 64 of file LocationAwareStore.php.
    {
        $digest = parent::generateContentDigest( $response );
        if ( !$response->headers->has( 'X-Location-Id' ) )
        {
            return $digest;
        }
        return static::LOCATION_CACHE_DIR . "/{$response->headers->get( 'X-Location-Id' )}/$digest";
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore::getFilesystem ()
Returns
Definition at line 46 of file LocationAwareStore.php.
    {
        if ( !isset( $this->fs ) )
            $this->fs = new Filesystem();
        return $this->fs;
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore::getLocationCacheDir ($locationId = null)
Returns cache dir for $locationId.
This method is public only for unit tests. Use it only if you know what you are doing.
Definition at line 245 of file LocationAwareStore.php.
References eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore\LOCATION_CACHE_DIR.
    {
        $cacheDir = "$this->root/" . static::LOCATION_CACHE_DIR;
        if ( $locationId )
            $cacheDir .= "/$locationId";
        return $cacheDir;
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore::getLocationCacheLockName ($locationId = null)
Returns cache lock name for $locationId.
This method is public only for unit tests. Use it only if you know what you are doing.
Definition at line 227 of file LocationAwareStore.php.
    {
        $locationId = $locationId ?: 'all';
        return "$this->root/_ezloc_$locationId.purging";
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore::getPath ($key)
Returns the right path where cache is being stored. Will detect if $key is eZ Publish specific.
Parameters
string $key
Returns
string
Reimplemented from eZ\Publish\Core\MVC\Symfony\Cache\Http\Store.
Definition at line 83 of file LocationAwareStore.php.
References eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore\getFilesystem(), eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore\getLocationCacheDir(), and eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore\getLocationCacheLockName().
    {
        if ( strpos( $key, static::LOCATION_CACHE_DIR ) === false )
            return parent::getPath( $key );
        $prefix = '';
        if ( ( $pos = strrpos( $key, '/' ) ) !== false )
        {
            $prefix = substr( $key, 0, $pos ) . DIRECTORY_SEPARATOR;
            $key = substr( $key, $pos + 1 );
            list( $locationCacheDir, $locationId ) = explode( '/', $prefix );
            // If cache purge is in progress, serve stale cache instead of regular cache.
            // We first check for a global cache purge, then for the current location.
            foreach ( array( $this->getLocationCacheLockName(), $this->getLocationCacheLockName( $locationId ) ) as $cacheLockFile )
            {
                if ( is_file( $cacheLockFile ) )
                {
                    if ( function_exists( 'posix_kill' ) )
                    {
                        // Check if purge process is still running. If not, remove the lock file to unblock future cache purge
                        if ( !posix_kill( file_get_contents( $cacheLockFile ), 0 ) )
{
                            $fs = $this->getFilesystem();
                            $fs->remove( array( $cacheLockFile, $this->getLocationCacheDir( $locationId ) ) );
                            goto returnCachePath;
                        }
                    }
                    $prefix = str_replace( static::LOCATION_CACHE_DIR, static::LOCATION_STALE_CACHE_DIR, $prefix );
                }
            }
        }
        returnCachePath:
        return $this->root . DIRECTORY_SEPARATOR . $prefix .
           substr( $key, 0, 2 ) . DIRECTORY_SEPARATOR .
           substr( $key, 2, 2 ) . DIRECTORY_SEPARATOR .
           substr( $key, 4, 2 ) . DIRECTORY_SEPARATOR .
           substr( $key, 6 );
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore::purgeAllContent ()
Purges all cached content
Returns
boolean
Implements eZ\Publish\Core\MVC\Symfony\Cache\Http\ContentPurger.
Definition at line 168 of file LocationAwareStore.php.
    {
        return $this->purgeLocation( null );
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore::purgeByRequest (Request $request)
Purges data from $request. If X-Location-Id or X-Group-Location-Id header is present, the store will purge cache for given locationId or group of locationIds. If not, regular purge by URI will occur.
Parameters
\Symfony\Component\HttpFoundation\Request $request
Returns
boolean True if purge was successful. False otherwise
Implements eZ\Publish\Core\MVC\Symfony\Cache\Http\RequestAwarePurger.
Definition at line 134 of file LocationAwareStore.php.
References eZ\Publish\Core\MVC\Symfony\Cache\Http\Store\purge(), and eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore\purgeAllContent().
    {
        if ( !$request->headers->has( 'X-Location-Id' ) && !$request->headers->has( 'X-Group-Location-Id' ) )
        {
            return $this->purge( $request->getUri() );
        }
        // Purge everything
        if ( $request->headers->get( 'X-Location-Id' ) === '*' )
        {
            return $this->purgeAllContent();
        }
        if ( $request->headers->has( 'X-Group-Location-Id' ) )
            $aLocationId = explode( '; ', $request->headers->get( 'X-Group-Location-Id' ) );
        else
            $aLocationId = array( $request->headers->get( 'X-Location-Id' ) );
        if ( empty( $aLocationId ) )
            return false;
        foreach ( $aLocationId as $locationId )
        {
            $this->purgeLocation( $locationId );
        }
        return true;
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore::setFilesystem (Filesystem $fs)
Injects a Filesystem instance For unit tests only.
Definition at line 38 of file LocationAwareStore.php.
    {
        $this->fs = $fs;
    }
Member Data Documentation
const eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore::LOCATION_CACHE_DIR = 'ezlocation'
Definition at line 22 of file LocationAwareStore.php.
const eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore::LOCATION_STALE_CACHE_DIR = 'ezlocation_stale'
Definition at line 23 of file LocationAwareStore.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/Cache/Http/LocationAwareStore.php