ezp-next: eZ\Publish\Core\FieldType\XmlText\Converter\EzLinkToHtml5 Class Reference
eZ\Publish\Core\FieldType\XmlText\Converter\EzLinkToHtml5 Class Reference
Public Member Functions
__construct (Repository $repository, LoggerInterface $logger=null)
convert (DOMDocument $xmlDoc)
Protected Attributes
$locationService
$contentService
$urlAliasService
$logger
Detailed Description
Definition at line 20 of file EzLinkToHtml5.php.
Constructor & Destructor Documentation
eZ\Publish\Core\FieldType\XmlText\Converter\EzLinkToHtml5::__construct (Repository $repository, LoggerInterface $logger = null)
Definition at line 42 of file EzLinkToHtml5.php.
References eZ\Publish\Core\FieldType\XmlText\Converter\EzLinkToHtml5\$logger, eZ\Publish\Core\FieldType\XmlText\Converter\EzLinkToHtml5\__construct(), eZ\Publish\API\Repository\Repository\getContentService(), eZ\Publish\API\Repository\Repository\getLocationService(), and eZ\Publish\API\Repository\Repository\getURLAliasService().
    {
        $this->locationService = $repository->getLocationService();
        $this->contentService = $repository->getContentService();
        $this->urlAliasService = $repository->getURLAliasService();
        $this->logger = $logger;
    }
Member Function Documentation
eZ\Publish\Core\FieldType\XmlText\Converter\EzLinkToHtml5::convert (DOMDocument $xmlDoc)
Converts internal links (eznode:// and ezobject://) to URLs.
Parameters
\DOMDocument $xmlDoc
Returns
string|null
Implements eZ\Publish\Core\FieldType\XmlText\Converter.
Definition at line 57 of file EzLinkToHtml5.php.
    {
        foreach ( $xmlDoc->getElementsByTagName( "link" ) as $link )
        {
            $location = null;
            if ( $link->hasAttribute( 'object_id' ) )
            {
                try
                {
                    $content = $this->contentService->loadContent( $link->getAttribute( 'object_id' ) );
                    $location = $this->locationService->loadLocation( $content->contentInfo->mainLocationId );
                }
                catch ( APINotFoundException $e )
                {
                    if ( $this->logger )
                    {
                        $this->logger->warning(
                            "While generating links for xmltext, could not locate " .
                            "Content object with ID " . $link->getAttribute( 'object_id' )
                        );
                    }
                }
                catch ( APIUnauthorizedException $e )
                {
                    if ( $this->logger )
                    {
                        $this->logger->notice(
                            "While generating links for xmltext, unauthorized to load " .
                            "Content object with ID " . $link->getAttribute( 'object_id' )
                        );
                    }
                }
            }
            if ( $link->hasAttribute( 'node_id' ) )
            {
                try
                {
                    $location = $this->locationService->loadLocation( $link->getAttribute( 'node_id' ) );
                }
                catch ( APINotFoundException $e )
                {
                    if ( $this->logger )
                    {
                        $this->logger->warning(
                            "While generating links for xmltext, could not locate " .
                            "Location with ID " . $link->getAttribute( 'node_id' )
                        );
                    }
                }
                catch ( APIUnauthorizedException $e )
                {
                    if ( $this->logger )
                    {
                        $this->logger->notice(
                            "While generating links for xmltext, unauthorized to load " .
                            "Location with ID " . $link->getAttribute( 'node_id' )
                        );
                    }
                }
            }
            if ( $location !== null )
            {
                $urlAlias = $this->urlAliasService->reverseLookup( $location );
                $link->setAttribute( 'url', $urlAlias->path );
            }
        }
    }
Member Data Documentation
eZ\Publish\Core\FieldType\XmlText\Converter\EzLinkToHtml5::$contentService protected
Definition at line 30 of file EzLinkToHtml5.php.
eZ\Publish\Core\FieldType\XmlText\Converter\EzLinkToHtml5::$locationService protected
Definition at line 25 of file EzLinkToHtml5.php.
eZ\Publish\Core\FieldType\XmlText\Converter\EzLinkToHtml5::$logger protected
Definition at line 40 of file EzLinkToHtml5.php.
eZ\Publish\Core\FieldType\XmlText\Converter\EzLinkToHtml5::$urlAliasService protected
Definition at line 35 of file EzLinkToHtml5.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/XmlText/Converter/EzLinkToHtml5.php