ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\LogicalNot Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\LogicalNot Class Reference
Public Member Functions
accept (Criterion $criterion)
handle (CriteriaConverter $converter, ezcQuerySelect $query, Criterion $criterion)
Public Member Functions inherited from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler
__construct (EzcDbHandler $dbHandler)
Additional Inherited Members
Protected Attributes inherited from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler
$comparatorMap
$dbHandler
Detailed Description
Logical not criterion handler
Definition at line 20 of file LogicalNot.php.
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\LogicalNot::accept (Criterion $criterion)
Check if this criterion handler accepts to handle the given criterion.
Parameters
\eZ\Publish\API\Repository\Values\Content\Query\Criterion$criterion
Returns
boolean
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler.
Definition at line 29 of file LogicalNot.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\LogicalNot\accept().
    {
        return $criterion instanceof Criterion\LogicalNot;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\LogicalNot::handle (CriteriaConverter $converter, ezcQuerySelect $query, Criterion $criterion)
Check if this criterion handler accepts to handle the given criterion.
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriteriaConverter$converter
\ezcQuerySelect $query
\eZ\Publish\API\Repository\Values\Content\Query\Criterion$criterion
Returns
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler.
Definition at line 43 of file LogicalNot.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriteriaConverter\convertCriteria(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\LogicalNot\handle().
    {
        return $query->expr->not(
            $converter->convertCriteria( $query, $criterion->criteria[0] )
        );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Search/Gateway/CriterionHandler/LogicalNot.php