ezp-next: eZ\Publish\Core\MVC\Legacy\Kernel\Loader Class Reference
eZ\Publish\Core\MVC\Legacy\Kernel\Loader Class Reference
Public Member Functions
__construct ($legacyRootDir, $webrootDir, LoggerInterface $logger=null)
buildLegacyKernel ($legacyKernelHandler)
buildLegacyKernelHandlerWeb (ContainerInterface $container, $webHandlerClass, array $defaultLegacyOptions=array())
buildLegacyKernelHandlerCLI (ContainerInterface $container)
buildLegacyKernelHandlerTreeMenu (ContainerInterface $container)
Protected Attributes
$legacyRootDir
$webrootDir
$logger
Detailed Description
Legacy kernel loader
Definition at line 25 of file Loader.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Legacy\Kernel\Loader::__construct ($legacyRootDir, $webrootDir, LoggerInterface $logger = null)
Definition at line 42 of file Loader.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\Loader\$legacyRootDir, eZ\Publish\Core\MVC\Legacy\Kernel\Loader\$logger, and eZ\Publish\Core\MVC\Legacy\Kernel\Loader\$webrootDir.
    {
        $this->legacyRootDir = $legacyRootDir;
        $this->webrootDir = $webrootDir;
        $this->logger = $logger;
    }
Member Function Documentation
eZ\Publish\Core\MVC\Legacy\Kernel\Loader::buildLegacyKernel ($legacyKernelHandler)
Builds up the legacy kernel and encapsulates it inside a closure, allowing lazy loading.
Parameters
\ezpKernelHandler|\Closure A kernel handler instance or a closure returning a kernel handler instance
Returns
Definition at line 56 of file Loader.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\Loader\$legacyRootDir, eZ\Publish\Core\MVC\Legacy\Kernel\Loader\$webrootDir, and eZ\Publish\Core\MVC\Legacy\Kernel\Loader\buildLegacyKernel().
    {
        $legacyRootDir = $this->legacyRootDir;
        $webrootDir = $this->webrootDir;
        return function () use ( $legacyKernelHandler, $legacyRootDir, $webrootDir )
        {
            static $legacyKernel;
            if ( !$legacyKernel instanceof LegacyKernel )
            {
                if ( $legacyKernelHandler instanceof \Closure )
                    $legacyKernelHandler = $legacyKernelHandler();
                $legacyKernel = new LegacyKernel( $legacyKernelHandler, $legacyRootDir, $webrootDir );
            }
            return $legacyKernel;
        };
    }
eZ\Publish\Core\MVC\Legacy\Kernel\Loader::buildLegacyKernelHandlerCLI (ContainerInterface $container)
Builds legacy kernel handler CLI
Parameters
\Symfony\Component\DependencyInjection\ContainerInterface $container
Returns
CLIHandler
Definition at line 139 of file Loader.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\Loader\$legacyRootDir, eZ\Publish\Core\MVC\Legacy\Kernel\Loader\$webrootDir, eZ\Publish\Core\MVC\Legacy\Kernel\Loader\buildLegacyKernelHandlerCLI(), and eZ\Publish\Core\MVC\Legacy\LegacyEvents\PRE_BUILD_LEGACY_KERNEL.
    {
        $legacyRootDir = $this->legacyRootDir;
        $webrootDir = $this->webrootDir;
        return function () use ( $legacyRootDir, $webrootDir, $container )
        {
            static $cliHandler;
            if ( !$cliHandler instanceof ezpKernelHandler )
            {
                chdir( $legacyRootDir );
                $legacyParameters = new ParameterBag( $container->getParameter( 'ezpublish_legacy.kernel_handler.cli.options' ) );
                $eventDispatcher = $container->get( 'event_dispatcher' );
                $eventDispatcher->dispatch( LegacyEvents::PRE_BUILD_LEGACY_KERNEL, new PreBuildKernelEvent( $legacyParameters ) );
                $cliHandler = new CLIHandler( $legacyParameters->all(), $container->get( 'ezpublish.siteaccess' ), $container );
                chdir( $webrootDir );
            }
            return $cliHandler;
        };
    }
eZ\Publish\Core\MVC\Legacy\Kernel\Loader::buildLegacyKernelHandlerTreeMenu (ContainerInterface $container)
Builds the legacy kernel handler for the tree menu in admin interface.
Parameters
\Symfony\Component\DependencyInjection\ContainerInterface $container
Returns
A closure returning an instance.
Definition at line 170 of file Loader.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\Loader\buildLegacyKernelHandlerTreeMenu(), and eZ\Publish\Core\MVC\Legacy\Kernel\Loader\buildLegacyKernelHandlerWeb().
    {
        return $this->buildLegacyKernelHandlerWeb(
            $container,
            $container->getParameter( 'ezpublish_legacy.kernel_handler.treemenu.class' ),
            array(
                'use-cache-headers'    => false,
                'use-exceptions'       => true
            )
        );
    }
eZ\Publish\Core\MVC\Legacy\Kernel\Loader::buildLegacyKernelHandlerWeb (ContainerInterface $container, $webHandlerClass, array $defaultLegacyOptions = array())
Builds up the legacy kernel web handler and encapsulates it inside a closure, allowing lazy loading.
Parameters
\Symfony\Component\DependencyInjection\ContainerInterface $container
string $webHandlerClass The legacy kernel handler class to use
array $defaultLegacyOptions Hash of options to pass to the legacy kernel handler
Exceptions
\InvalidArgumentException
Returns
|void
Definition at line 85 of file Loader.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\Loader\$legacyRootDir, eZ\Publish\Core\MVC\Legacy\Kernel\Loader\$webrootDir, eZ\Publish\Core\MVC\Legacy\Kernel\Loader\buildLegacyKernelHandlerWeb(), eZ\Publish\Core\MVC\Legacy\LegacyEvents\PRE_BUILD_LEGACY_KERNEL, and eZ\Publish\Core\MVC\Legacy\LegacyEvents\PRE_BUILD_LEGACY_KERNEL_WEB.
    {
        $legacyRootDir = $this->legacyRootDir;
        $webrootDir = $this->webrootDir;
        return function () use ( $legacyRootDir, $webrootDir, $container, $defaultLegacyOptions, $webHandlerClass )
        {
            static $webHandler;
            if ( !$webHandler instanceof ezpKernelHandler )
            {
                chdir( $legacyRootDir );
                $legacyParameters = new ParameterBag( $defaultLegacyOptions );
                $legacyParameters->set( 'service-container', $container );
                $request = $container->get( 'request' );
                $eventDispatcher = $container->get( 'event_dispatcher' );
                // PRE_BUILD_LEGACY_KERNEL for non request related stuff (potentially available in CLI context as well
                $eventDispatcher->dispatch( LegacyEvents::PRE_BUILD_LEGACY_KERNEL, new PreBuildKernelEvent( $legacyParameters ) );
                // Pure web stuff
                $buildEventWeb = new PreBuildKernelWebHandlerEvent(
                    $legacyParameters, $request
                );
                $eventDispatcher->dispatch(
                    LegacyEvents::PRE_BUILD_LEGACY_KERNEL_WEB, $buildEventWeb
                );
                $interfaces = class_implements( $webHandlerClass );
                if ( !isset( $interfaces['ezpKernelHandler'] ) )
                    throw new \InvalidArgumentException( 'A legacy kernel handler must be an instance of ezpKernelHandler.' );
                $webHandler = new $webHandlerClass( $legacyParameters->all() );
                $uri = eZURI::instance();
                $uri->setURIString(
                    $request->attributes->get(
                        'semanticPathinfo',
                        $request->getPathinfo()
                    ) . $request->attributes->get( 'viewParametersString' )
                );
                chdir( $webrootDir );
            }
            return $webHandler;
        };
    }
Member Data Documentation
eZ\Publish\Core\MVC\Legacy\Kernel\Loader::$legacyRootDir protected
Definition at line 30 of file Loader.php.
eZ\Publish\Core\MVC\Legacy\Kernel\Loader::$logger protected
Definition at line 40 of file Loader.php.
eZ\Publish\Core\MVC\Legacy\Kernel\Loader::$webrootDir protected
Definition at line 35 of file Loader.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Legacy/Kernel/Loader.php