ezp-next: eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\RoleUpdateStruct Class Reference
eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\RoleUpdateStruct Class Reference
Public Member Functions
visit (Visitor $visitor, Generator $generator, $data)
Public Member Functions inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
__construct (UrlHandler $urlHandler)
Additional Inherited Members
Protected Member Functions inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
serializeBool ($boolValue)
visitNamesList (Generator $generator, array $names)
visitDescriptionsList (Generator $generator, array $descriptions)
visitTranslatedList (Generator $generator, array $translatedElements, $listName)
visitLimitation (Generator $generator, Limitation $limitation)
serializeSortField ($sortField)
serializeSortOrder ($sortOrder)
Protected Attributes inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
$urlHandler
Detailed Description
RoleUpdateStruct value object visitor
Definition at line 19 of file RoleUpdateStruct.php.
Member Function Documentation
eZ\Publish\Core\REST\Client\Output\ValueObjectVisitor\RoleUpdateStruct::visit (Visitor $visitor, Generator $generator, $data)
Visit struct returned by controllers
Parameters
\eZ\Publish\Core\REST\Common\Output\Visitor $visitor
\eZ\Publish\Core\REST\Common\Output\Generator $generator
mixed $data
Reimplemented from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor.
Definition at line 28 of file RoleUpdateStruct.php.
References eZ\Publish\Core\REST\Common\Output\Generator\endObjectElement(), eZ\Publish\Core\REST\Common\Output\Generator\endValueElement(), eZ\Publish\Core\REST\Common\Output\Generator\getMediaType(), eZ\Publish\Core\REST\Common\Output\Visitor\setHeader(), eZ\Publish\Core\REST\Common\Output\Generator\startObjectElement(), and eZ\Publish\Core\REST\Common\Output\Generator\startValueElement().
    {
        $generator->startObjectElement( 'RoleInput' );
        $visitor->setHeader( 'Content-Type', $generator->getMediaType( 'RoleInput' ) );
        $generator->startValueElement( 'identifier', $data->identifier );
        $generator->endValueElement( 'identifier' );
        $generator->endObjectElement( 'RoleInput' );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Client/Output/ValueObjectVisitor/RoleUpdateStruct.php