ezp-next: eZ\Publish\Core\REST\Server\Controller\User Class Reference
eZ\Publish\Core\REST\Server\Controller\User Class Reference
Public Member Functions
__construct (UserService $userService, RoleService $roleService, ContentService $contentService, LocationService $locationService, SectionService $sectionService, Repository $repository)
loadRootUserGroup ()
loadUserGroup ()
loadUser ()
createUserGroup ()
createUser ()
updateUserGroup ()
updateUser ()
deleteUserGroup ()
deleteUser ()
loadUsers ()
loadUserByRemoteId ()
loadUsersAssignedToRole ()
loadUserGroups ()
loadUserGroupByRemoteId ()
loadUserGroupsAssignedToRole ()
loadUserDrafts ()
moveUserGroup ()
loadSubUserGroups ()
loadUserGroupsOfUser ()
loadUsersFromGroup ()
unassignUserFromUserGroup ()
assignUserToUserGroup ()
Public Member Functions inherited from eZ\Publish\Core\REST\Server\Controller
setInputDispatcher (InputDispatcher $inputDispatcher)
setUrlHandler (UrlHandler $urlHandler)
setRequest (HttpRequest $request)
setContainer (Container $container)
Protected Member Functions
getMediaType ()
Protected Attributes
$userService
$roleService
$contentService
$locationService
$sectionService
$repository
Protected Attributes inherited from eZ\Publish\Core\REST\Server\Controller
$request
$inputDispatcher
$urlHandler
$container
Detailed Description
User controller
Definition at line 36 of file User.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Server\Controller\User::__construct (UserService $userService, RoleService $roleService, ContentService $contentService, LocationService $locationService, SectionService $sectionService, Repository $repository)
Construct controller
Parameters
\eZ\Publish\API\Repository\UserService $userService
\eZ\Publish\API\Repository\RoleService $roleService
\eZ\Publish\API\Repository\ContentService $contentService
\eZ\Publish\API\Repository\LocationService $locationService
\eZ\Publish\API\Repository\SectionService $sectionService
\eZ\Publish\API\Repository\Repository $repository
Definition at line 90 of file User.php.
References eZ\Publish\Core\REST\$repository, and eZ\Publish\Core\REST\Server\Controller\User\__construct().
    {
        $this->userService = $userService;
        $this->roleService = $roleService;
        $this->contentService = $contentService;
        $this->locationService = $locationService;
        $this->sectionService = $sectionService;
        $this->repository = $repository;
    }
Member Function Documentation
eZ\Publish\Core\REST\Server\Controller\User::assignUserToUserGroup ()
Assigns the user to a user group
Returns
Definition at line 825 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\assignUserToUserGroup().
    {
        $urlValues = $this->urlHandler->parse( 'userGroupAssign', $this->request->path );
        $user = $this->userService->loadUser( $urlValues['user'] );
        try
        {
            $userGroupLocation = $this->locationService->loadLocation(
                $this->extractLocationIdFromPath( $this->request->variables['group'] )
            );
        }
        catch ( NotFoundException $e )
        {
            throw new Exceptions\ForbiddenException( $e->getMessage() );
        }
        try
        {
            $userGroup = $this->userService->loadUserGroup(
                $userGroupLocation->contentId
            );
        }
        catch ( NotFoundException $e )
        {
            throw new Exceptions\ForbiddenException( $e->getMessage() );
        }
        try
        {
            $this->userService->assignUserToUserGroup( $user, $userGroup );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new Exceptions\ForbiddenException( $e->getMessage() );
        }
        $userGroups = $this->userService->loadUserGroupsOfUser( $user );
        $restUserGroups = array();
        foreach ( $userGroups as $userGroup )
        {
            $userGroupContentInfo = $userGroup->getVersionInfo()->getContentInfo();
            $userGroupLocation = $this->locationService->loadLocation( $userGroupContentInfo->mainLocationId );
            $restUserGroups[] = new Values\RestUserGroup(
                $userGroup,
                $userGroupContentInfo,
                $userGroupLocation,
                $this->contentService->loadRelations( $userGroup->getVersionInfo() )
            );
        }
        return new Values\UserGroupRefList(
            $restUserGroups,
            $this->urlHandler->generate( 'userGroups', array( 'user' => $urlValues['user'] ) ),
            $urlValues['user']
        );
    }
eZ\Publish\Core\REST\Server\Controller\User::createUser ()
Create a new user group in the given group
Returns
Definition at line 230 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\createUser().
    {
        $urlValues = $this->urlHandler->parse( 'groupUsers', $this->request->path );
        $userGroupLocation = $this->locationService->loadLocation(
            $this->extractLocationIdFromPath( $urlValues['group'] )
        );
        $userGroup = $this->userService->loadUserGroup( $userGroupLocation->contentId );
        $userCreateStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        try
        {
            $createdUser = $this->userService->createUser( $userCreateStruct, array( $userGroup ) );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        $createdContentInfo = $createdUser->getVersionInfo()->getContentInfo();
        $createdLocation = $this->locationService->loadLocation( $createdContentInfo->mainLocationId );
        return new Values\CreatedUser(
            array(
                'user' => new Values\RestUser(
                    $createdUser,
                    $createdContentInfo,
                    $createdLocation,
                    $this->contentService->loadRelations( $createdUser->getVersionInfo() )
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\User::createUserGroup ()
Create a new user group under the given parent To create a top level group use /user/groups/subgroups
Returns
Definition at line 174 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\createUserGroup().
    {
        try
        {
            $urlValues = $this->urlHandler->parse( 'groupSubgroups', $this->request->path );
            $userGroupPath = $urlValues['group'];
        }
        catch ( RestInvalidArgumentException $e )
        {
            try
            {
                $this->urlHandler->parse( 'rootUserGroupSubGroups', $this->request->path );
                //@todo Load from settings instead of using hardcoded value
                $userGroupPath = '/1/5';
            }
            catch ( RestInvalidArgumentException $e )
            {
                throw new Exceptions\BadRequestException( 'Unrecognized user group resource' );
            }
        }
        $userGroupLocation = $this->locationService->loadLocation(
            $this->extractLocationIdFromPath( $userGroupPath )
        );
        $createdUserGroup = $this->userService->createUserGroup(
            $this->inputDispatcher->parse(
                new Message(
                    array( 'Content-Type' => $this->request->contentType ),
                    $this->request->body
                )
            ),
            $this->userService->loadUserGroup(
                $userGroupLocation->contentId
            )
        );
        $createdContentInfo = $createdUserGroup->getVersionInfo()->getContentInfo();
        $createdLocation = $this->locationService->loadLocation( $createdContentInfo->mainLocationId );
        return new Values\CreatedUserGroup(
            array(
                'userGroup' => new Values\RestUserGroup(
                    $createdUserGroup,
                    $createdContentInfo,
                    $createdLocation,
                    $this->contentService->loadRelations( $createdUserGroup->getVersionInfo() )
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\User::deleteUser ()
Given user is deleted
Returns
Definition at line 393 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\deleteUser().
    {
        $urlValues = $this->urlHandler->parse( 'user', $this->request->path );
        $user = $this->userService->loadUser(
            $urlValues['user']
        );
        if ( $user->id == $this->repository->getCurrentUser()->id )
        {
            throw new Exceptions\ForbiddenException( "Currently authenticated user cannot be deleted" );
        }
        $this->userService->deleteUser( $user );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\User::deleteUserGroup ()
Given user group is deleted
Returns
Definition at line 364 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\deleteUserGroup().
    {
        $urlValues = $this->urlHandler->parse( 'group', $this->request->path );
        $userGroupLocation = $this->locationService->loadLocation(
            $this->extractLocationIdFromPath( $urlValues['group'] )
        );
        $userGroup = $this->userService->loadUserGroup(
            $userGroupLocation->contentId
        );
        // Load one user to see if user group is empty or not
        $users = $this->userService->loadUsersOfUserGroup( $userGroup, 0, 1 );
        if ( !empty( $users ) )
        {
            throw new Exceptions\ForbiddenException( "Non-empty user groups cannot be deleted" );
        }
        $this->userService->deleteUserGroup( $userGroup );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\User::getMediaType () protected
Extracts the requested media type from $request
Returns
string
Definition at line 901 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\getMediaType().
    {
        foreach ( $this->request->mimetype as $mimeType )
        {
            if ( preg_match( '(^([a-z0-9-/.]+)\+.*$)', $mimeType['value'], $matches ) )
            {
                return $matches[1];
            }
        }
        return 'unknown/unknown';
    }
eZ\Publish\Core\REST\Server\Controller\User::loadRootUserGroup ()
Redirects to the root user group
Returns
Definition at line 111 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\loadRootUserGroup().
    {
        //@todo Replace hardcoded value with one loaded from settings
        return new Values\PermanentRedirect(
            $this->urlHandler->generate( 'group', array( 'group' => '/1/5' ) )
        );
    }
eZ\Publish\Core\REST\Server\Controller\User::loadSubUserGroups ()
Returns a list of the sub groups
Returns
|
Definition at line 658 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\getMediaType(), and eZ\Publish\Core\REST\Server\Controller\User\loadSubUserGroups().
    {
        $urlValues = $this->urlHandler->parse( 'groupSubgroups', $this->request->path );
        $userGroupLocation = $this->locationService->loadLocation(
            $this->extractLocationIdFromPath( $urlValues['group'] )
        );
        $userGroup = $this->userService->loadUserGroup(
            $userGroupLocation->contentId
        );
        $subGroups = $this->userService->loadSubUserGroups( $userGroup );
        $restUserGroups = array();
        foreach ( $subGroups as $subGroup )
        {
            $subGroupContentInfo = $subGroup->getVersionInfo()->getContentInfo();
            $subGroupLocation = $this->locationService->loadLocation( $subGroupContentInfo->mainLocationId );
            $restUserGroups[] = new Values\RestUserGroup(
                $subGroup,
                $subGroupContentInfo,
                $subGroupLocation,
                $this->contentService->loadRelations( $subGroup->getVersionInfo() )
            );
        }
        if ( $this->getMediaType( $this->request ) === 'application/vnd.ez.api.usergrouplist' )
        {
            return new Values\UserGroupList( $restUserGroups, $this->request->path );
        }
        return new Values\UserGroupRefList( $restUserGroups, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\User::loadUser ()
Loads a user for the given ID
Returns
Definition at line 149 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\loadUser().
    {
        $urlValues = $this->urlHandler->parse( 'user', $this->request->path );
        $user = $this->userService->loadUser(
            $urlValues['user']
        );
        $userContentInfo = $user->getVersionInfo()->getContentInfo();
        $userMainLocation = $this->locationService->loadLocation( $userContentInfo->mainLocationId );
        return new Values\RestUser(
            $user,
            $userContentInfo,
            $userMainLocation,
            $this->contentService->loadRelations( $user->getVersionInfo() )
        );
    }
eZ\Publish\Core\REST\Server\Controller\User::loadUserByRemoteId ()
Loads a user by its remote ID
Returns
Definition at line 443 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\loadUserByRemoteId().
    {
        $contentInfo = $this->contentService->loadContentInfoByRemoteId( $this->request->variables['remoteId'] );
        $user = $this->userService->loadUser( $contentInfo->id );
        $userLocation = $this->locationService->loadLocation( $contentInfo->mainLocationId );
        return new Values\RestUser(
            $user,
            $contentInfo,
            $userLocation,
            $this->contentService->loadRelations( $user->getVersionInfo() )
        );
    }
eZ\Publish\Core\REST\Server\Controller\User::loadUserDrafts ()
Loads drafts assigned to user
Returns
Definition at line 591 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\loadUserDrafts().
    {
        $urlValues = $this->urlHandler->parse( 'userDrafts', $this->request->path );
        $contentDrafts = $this->contentService->loadContentDrafts(
            $this->userService->loadUser( $urlValues['user'] )
        );
        return new Values\VersionList( $contentDrafts, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\User::loadUserGroup ()
Loads a user group for the given path
Returns
Definition at line 124 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\loadUserGroup().
    {
        $urlValues = $this->urlHandler->parse( 'group', $this->request->path );
        $userGroupLocation = $this->locationService->loadLocation(
            $this->extractLocationIdFromPath( $urlValues['group'] )
        );
        $userGroup = $this->userService->loadUserGroup(
            $userGroupLocation->contentId
        );
        return new Values\RestUserGroup(
            $userGroup,
            $userGroup->getVersionInfo()->getContentInfo(),
            $userGroupLocation,
            $this->contentService->loadRelations( $userGroup->getVersionInfo() )
        );
    }
eZ\Publish\Core\REST\Server\Controller\User::loadUserGroupByRemoteId ()
Loads a user group by its remote ID
Returns
Definition at line 538 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\loadUserGroupByRemoteId().
    {
        $contentInfo = $this->contentService->loadContentInfoByRemoteId( $this->request->variables['remoteId'] );
        $userGroup = $this->userService->loadUserGroup( $contentInfo->id );
        $userGroupLocation = $this->locationService->loadLocation( $contentInfo->mainLocationId );
        return new Values\RestUserGroup(
            $userGroup,
            $contentInfo,
            $userGroupLocation,
            $this->contentService->loadRelations( $userGroup->getVersionInfo() )
        );
    }
eZ\Publish\Core\REST\Server\Controller\User::loadUserGroups ()
Loads user groups
Returns
|
Definition at line 496 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\getMediaType(), eZ\Publish\Core\REST\Server\Controller\User\loadUserGroupByRemoteId(), eZ\Publish\Core\REST\Server\Controller\User\loadUserGroups(), and eZ\Publish\Core\REST\Server\Controller\User\loadUserGroupsAssignedToRole().
    {
        $restUserGroups = array();
        if ( isset( $this->request->variables['id'] ) )
        {
            $userGroup = $this->userService->loadUserGroup( $this->request->variables['id'] );
            $userGroupContentInfo = $userGroup->getVersionInfo()->getContentInfo();
            $userGroupMainLocation = $this->locationService->loadLocation( $userGroupContentInfo->mainLocationId );
            $restUserGroups = array(
                new Values\RestUserGroup(
                    $userGroup,
                    $userGroupContentInfo,
                    $userGroupMainLocation,
                    $this->contentService->loadRelations( $userGroup->getVersionInfo() )
                )
            );
        }
        else if ( isset( $this->request->variables['roleId'] ) )
        {
             $restUserGroups = $this->loadUserGroupsAssignedToRole();
        }
        else if ( isset( $this->request->variables['remoteId'] ) )
        {
            $restUserGroups = array(
                $this->loadUserGroupByRemoteId()
            );
        }
        if ( $this->getMediaType( $this->request ) === 'application/vnd.ez.api.usergrouplist' )
        {
            return new Values\UserGroupList( $restUserGroups, $this->request->path );
        }
        return new Values\UserGroupRefList( $restUserGroups, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\User::loadUserGroupsAssignedToRole ()
Loads a list of user groups assigned to role
Returns
[]
Definition at line 557 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\loadUserGroupsAssignedToRole().
    {
        $roleValues = $this->urlHandler->parse( 'role', $this->request->variables['roleId'] );
        $role = $this->roleService->loadRole( $roleValues['role'] );
        $roleAssignments = $this->roleService->getRoleAssignments( $role );
        $restUserGroups = array();
        foreach ( $roleAssignments as $roleAssignment )
        {
            if ( $roleAssignment instanceof UserGroupRoleAssignment )
            {
                $userGroup = $roleAssignment->getUserGroup();
                $userGroupContentInfo = $userGroup->getVersionInfo()->getContentInfo();
                $userGroupLocation = $this->locationService->loadLocation( $userGroupContentInfo->mainLocationId );
                $restUserGroups[] = new Values\RestUserGroup(
                    $userGroup,
                    $userGroupContentInfo,
                    $userGroupLocation,
                    $this->contentService->loadRelations( $userGroup->getVersionInfo() )
                );
            }
        }
        return $restUserGroups;
    }
eZ\Publish\Core\REST\Server\Controller\User::loadUserGroupsOfUser ()
Returns a list of user groups the user belongs to. The returned list includes the resources for unassigning a user group if the user is in multiple groups.
Returns
Definition at line 700 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\loadUserGroupsOfUser().
    {
        $urlValues = $this->urlHandler->parse( 'userGroups', $this->request->path );
        $user = $this->userService->loadUser( $urlValues['user'] );
        $userGroups = $this->userService->loadUserGroupsOfUser( $user );
        $restUserGroups = array();
        foreach ( $userGroups as $userGroup )
        {
            $userGroupContentInfo = $userGroup->getVersionInfo()->getContentInfo();
            $userGroupLocation = $this->locationService->loadLocation( $userGroupContentInfo->mainLocationId );
            $restUserGroups[] = new Values\RestUserGroup(
                $userGroup,
                $userGroupContentInfo,
                $userGroupLocation,
                $this->contentService->loadRelations( $userGroup->getVersionInfo() )
            );
        }
        return new Values\UserGroupRefList( $restUserGroups, $this->request->path, $urlValues['user'] );
    }
eZ\Publish\Core\REST\Server\Controller\User::loadUsers ()
Loads users
Returns
|
Definition at line 416 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\getMediaType(), eZ\Publish\Core\REST\Server\Controller\User\loadUserByRemoteId(), eZ\Publish\Core\REST\Server\Controller\User\loadUsers(), and eZ\Publish\Core\REST\Server\Controller\User\loadUsersAssignedToRole().
    {
        $restUsers = array();
        if ( isset( $this->request->variables['roleId'] ) )
        {
             $restUsers = $this->loadUsersAssignedToRole();
        }
        else if ( isset( $this->request->variables['remoteId'] ) )
        {
            $restUsers = array(
                $this->loadUserByRemoteId()
            );
        }
        if ( $this->getMediaType( $this->request ) === 'application/vnd.ez.api.userlist' )
        {
            return new Values\UserList( $restUsers, $this->request->path );
        }
        return new Values\UserRefList( $restUsers, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\User::loadUsersAssignedToRole ()
Loads a list of users assigned to role
Returns
[]
Definition at line 462 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\loadUsersAssignedToRole().
    {
        $roleValues = $this->urlHandler->parse( 'role', $this->request->variables['roleId'] );
        $role = $this->roleService->loadRole( $roleValues['role'] );
        $roleAssignments = $this->roleService->getRoleAssignments( $role );
        $restUsers = array();
        foreach ( $roleAssignments as $roleAssignment )
        {
            if ( $roleAssignment instanceof UserRoleAssignment )
            {
                $user = $roleAssignment->getUser();
                $userContentInfo = $user->getVersionInfo()->getContentInfo();
                $userLocation = $this->locationService->loadLocation( $userContentInfo->mainLocationId );
                $restUsers[] = new Values\RestUser(
                    $user,
                    $userContentInfo,
                    $userLocation,
                    $this->contentService->loadRelations( $user->getVersionInfo() )
                );
            }
        }
        return $restUsers;
    }
eZ\Publish\Core\REST\Server\Controller\User::loadUsersFromGroup ()
Loads the users of the group with the given path
Returns
|
Definition at line 728 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\getMediaType(), and eZ\Publish\Core\REST\Server\Controller\User\loadUsersFromGroup().
    {
        $questionMark = strpos( $this->request->path, '?' );
        $requestPath = $questionMark !== false ? substr( $this->request->path, 0, $questionMark ) : $this->request->path;
        $urlValues = $this->urlHandler->parse( 'groupUsers', $requestPath );
        $userGroupLocation = $this->locationService->loadLocation(
            $this->extractLocationIdFromPath( $urlValues['group'] )
        );
        $userGroup = $this->userService->loadUserGroup(
            $userGroupLocation->contentId
        );
        $offset = isset( $this->request->variables['offset'] ) ? (int)$this->request->variables['offset'] : 0;
        $limit = isset( $this->request->variables['limit'] ) ? (int)$this->request->variables['limit'] : -1;
        $users = $this->userService->loadUsersOfUserGroup(
            $userGroup,
            $offset >= 0 ? $offset : 0,
            $limit >= 0 ? $limit : -1
        );
        $restUsers = array();
        foreach ( $users as $user )
        {
            $userContentInfo = $user->getVersionInfo()->getContentInfo();
            $userLocation = $this->locationService->loadLocation( $userContentInfo->mainLocationId );
            $restUsers[] = new Values\RestUser(
                $user,
                $userContentInfo,
                $userLocation,
                $this->contentService->loadRelations( $user->getVersionInfo() )
            );
        }
        if ( $this->getMediaType( $this->request ) === 'application/vnd.ez.api.userlist' )
        {
            return new Values\UserList( $restUsers, $this->request->path );
        }
        return new Values\UserRefList( $restUsers, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\User::moveUserGroup ()
Moves the user group to another parent
Returns
Definition at line 607 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\moveUserGroup().
    {
        $urlValues = $this->urlHandler->parse( 'group', $this->request->path );
        $userGroupLocation = $this->locationService->loadLocation(
            $this->extractLocationIdFromPath( $urlValues['group'] )
        );
        $userGroup = $this->userService->loadUserGroup(
            $userGroupLocation->contentId
        );
        $destinationParts = $this->urlHandler->parse( 'group', $this->request->destination );
        try
        {
            $destinationGroupLocation = $this->locationService->loadLocation(
                $this->extractLocationIdFromPath( $destinationParts['group'] )
            );
        }
        catch ( NotFoundException $e )
        {
            throw new Exceptions\ForbiddenException( $e->getMessage() );
        }
        try
        {
            $destinationGroup = $this->userService->loadUserGroup( $destinationGroupLocation->contentId );
        }
        catch ( NotFoundException $e )
        {
            throw new Exceptions\ForbiddenException( $e->getMessage() );
        }
        $this->userService->moveUserGroup( $userGroup, $destinationGroup );
        return new Values\ResourceCreated(
            $this->urlHandler->generate(
                'group',
                array(
                    'group' => $destinationGroupLocation->pathString . $userGroupLocation->id
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\User::unassignUserFromUserGroup ()
Unassigns the user from a user group
Returns
Definition at line 778 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\unassignUserFromUserGroup().
    {
        $urlValues = $this->urlHandler->parse( 'userGroup', $this->request->path );
        $user = $this->userService->loadUser( $urlValues['user'] );
        $userGroupLocation = $this->locationService->loadLocation( trim( $urlValues['group'], '/' ) );
        $userGroup = $this->userService->loadUserGroup(
            $userGroupLocation->contentId
        );
        try
        {
            $this->userService->unAssignUserFromUserGroup( $user, $userGroup );
        }
        catch ( InvalidArgumentException $e )
        {
            // User is not in the group
            throw new Exceptions\ForbiddenException( $e->getMessage() );
        }
        $userGroups = $this->userService->loadUserGroupsOfUser( $user );
        $restUserGroups = array();
        foreach ( $userGroups as $userGroup )
        {
            $userGroupContentInfo = $userGroup->getVersionInfo()->getContentInfo();
            $userGroupLocation = $this->locationService->loadLocation( $userGroupContentInfo->mainLocationId );
            $restUserGroups[] = new Values\RestUserGroup(
                $userGroup,
                $userGroupContentInfo,
                $userGroupLocation,
                $this->contentService->loadRelations( $userGroup->getVersionInfo() )
            );
        }
        return new Values\UserGroupRefList(
            $restUserGroups,
            $this->urlHandler->generate( 'userGroups', array( 'user' => $urlValues['user'] ) ),
            $urlValues['user']
        );
    }
eZ\Publish\Core\REST\Server\Controller\User::updateUser ()
Updates a user
Returns
Definition at line 321 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\updateUser().
    {
        $urlValues = $this->urlHandler->parse( 'user', $this->request->path );
        $user = $this->userService->loadUser( $urlValues['user'] );
        $updateStruct = $this->inputDispatcher->parse(
            new Message(
                array(
                    'Content-Type' => $this->request->contentType,
                    // @todo Needs refactoring! Temporary solution so parser has access to URL
                    'Url' => $this->request->path
                ),
                $this->request->body
            )
        );
        if ( $updateStruct->sectionId !== null )
        {
            $section = $this->sectionService->loadSection( $updateStruct->sectionId );
            $this->sectionService->assignSection(
                $user->getVersionInfo()->getContentInfo(),
                $section
            );
        }
        $updatedUser = $this->userService->updateUser( $user, $updateStruct->userUpdateStruct );
        $updatedContentInfo = $updatedUser->getVersionInfo()->getContentInfo();
        $mainLocation = $this->locationService->loadLocation( $updatedContentInfo->mainLocationId );
        return new Values\RestUser(
            $updatedUser,
            $updatedContentInfo,
            $mainLocation,
            $this->contentService->loadRelations( $updatedUser->getVersionInfo() )
        );
    }
eZ\Publish\Core\REST\Server\Controller\User::updateUserGroup ()
Updates a user group
Returns
Definition at line 274 of file User.php.
References eZ\Publish\Core\REST\Server\Controller\User\updateUserGroup().
    {
        $urlValues = $this->urlHandler->parse( 'group', $this->request->path );
        $userGroupLocation = $this->locationService->loadLocation(
            $this->extractLocationIdFromPath( $urlValues['group'] )
        );
        $userGroup = $this->userService->loadUserGroup(
            $userGroupLocation->contentId
        );
        $updateStruct = $this->inputDispatcher->parse(
            new Message(
                array(
                    'Content-Type' => $this->request->contentType,
                    // @todo Needs refactoring! Temporary solution so parser has access to URL
                    'Url' => $this->request->path
                ),
                $this->request->body
            )
        );
        if ( $updateStruct->sectionId !== null )
        {
            $section = $this->sectionService->loadSection( $updateStruct->sectionId );
            $this->sectionService->assignSection(
                $userGroup->getVersionInfo()->getContentInfo(),
                $section
            );
        }
        $updatedGroup = $this->userService->updateUserGroup( $userGroup, $updateStruct->userGroupUpdateStruct );
        return new Values\RestUserGroup(
            $updatedGroup,
            $updatedGroup->getVersionInfo()->getContentInfo(),
            $userGroupLocation,
            $this->contentService->loadRelations( $updatedGroup->getVersionInfo() )
        );
    }
Member Data Documentation
eZ\Publish\Core\REST\Server\Controller\User::$contentService protected
Definition at line 57 of file User.php.
eZ\Publish\Core\REST\Server\Controller\User::$locationService protected
Definition at line 64 of file User.php.
eZ\Publish\Core\REST\Server\Controller\User::$repository protected
Definition at line 78 of file User.php.
eZ\Publish\Core\REST\Server\Controller\User::$roleService protected
Definition at line 50 of file User.php.
eZ\Publish\Core\REST\Server\Controller\User::$sectionService protected
Definition at line 71 of file User.php.
eZ\Publish\Core\REST\Server\Controller\User::$userService protected
Definition at line 43 of file User.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Controller/User.php