ezp-next: eZ\Publish\Core\Persistence\InMemory\Handler Class Reference
eZ\Publish\Core\Persistence\InMemory\Handler Class Reference
Public Member Functions
__construct ()
contentHandler ()
searchHandler ()
contentTypeHandler ()
contentLanguageHandler ()
locationHandler ()
objectStateHandler ()
userHandler ()
sectionHandler ()
trashHandler ()
urlAliasHandler ()
urlWildcardHandler ()
beginTransaction ()
commit ()
rollback ()
Protected Member Functions
serviceHandler ($className)
Protected Attributes
$serviceHandlers = array()
$backend
Detailed Description
The main handler for in memory Storage Engine
Definition at line 17 of file Handler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\InMemory\Handler::__construct ()
Setup instance with an instance of Backend class
Definition at line 36 of file Handler.php.
    {
        $this->backend = new Backend( json_decode( file_get_contents( __DIR__ . '/data.json' ), true ) );
    }
Member Function Documentation
eZ\Publish\Core\Persistence\InMemory\Handler::beginTransaction ()
Begin transaction
Begins an transaction, make sure you'll call commit or rollback when done, otherwise work will be lost.
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 135 of file Handler.php.
    {
        $this->backend->beginTransaction();
    }
eZ\Publish\Core\Persistence\InMemory\Handler::commit ()
Commit transaction
Commit transaction, or throw exceptions if no transactions has been started.
Exceptions
\RuntimeException If no transaction has been started
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 147 of file Handler.php.
    {
        $this->backend->commit();
    }
eZ\Publish\Core\Persistence\InMemory\Handler::contentHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 44 of file Handler.php.
References eZ\Publish\Core\Persistence\InMemory\Handler\serviceHandler().
    {
        return $this->serviceHandler( 'eZ\\Publish\\Core\\Persistence\\InMemory\\ContentHandler' );
    }
eZ\Publish\Core\Persistence\InMemory\Handler::contentLanguageHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 68 of file Handler.php.
References eZ\Publish\Core\Persistence\InMemory\Handler\serviceHandler().
    {
        return $this->serviceHandler( 'eZ\\Publish\\Core\\Persistence\\InMemory\\LanguageHandler' );
    }
eZ\Publish\Core\Persistence\InMemory\Handler::contentTypeHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 60 of file Handler.php.
References eZ\Publish\Core\Persistence\InMemory\Handler\serviceHandler().
    {
        return $this->serviceHandler( 'eZ\\Publish\\Core\\Persistence\\InMemory\\ContentTypeHandler' );
    }
eZ\Publish\Core\Persistence\InMemory\Handler::locationHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 76 of file Handler.php.
References eZ\Publish\Core\Persistence\InMemory\Handler\serviceHandler().
    {
        return $this->serviceHandler( 'eZ\\Publish\\Core\\Persistence\\InMemory\\LocationHandler' );
    }
eZ\Publish\Core\Persistence\InMemory\Handler::objectStateHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 84 of file Handler.php.
References eZ\Publish\Core\Persistence\InMemory\Handler\serviceHandler().
    {
        return $this->serviceHandler( 'eZ\\Publish\\Core\\Persistence\\InMemory\\ObjectStateHandler' );
    }
eZ\Publish\Core\Persistence\InMemory\Handler::rollback ()
Rollback transaction
Rollback transaction, or throw exceptions if no transactions has been started.
Exceptions
\RuntimeException If no transaction has been started
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 159 of file Handler.php.
    {
        $this->backend->rollback();
    }
eZ\Publish\Core\Persistence\InMemory\Handler::searchHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 52 of file Handler.php.
References eZ\Publish\Core\Persistence\InMemory\Handler\serviceHandler().
    {
        return $this->serviceHandler( 'eZ\\Publish\\Core\\Persistence\\InMemory\\SearchHandler' );
    }
eZ\Publish\Core\Persistence\InMemory\Handler::sectionHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 100 of file Handler.php.
References eZ\Publish\Core\Persistence\InMemory\Handler\serviceHandler().
    {
        return $this->serviceHandler( 'eZ\\Publish\\Core\\Persistence\\InMemory\\SectionHandler' );
    }
eZ\Publish\Core\Persistence\InMemory\Handler::serviceHandler ($className) protected
Get/create instance of service handler objects
Parameters
string $className
Exceptions
\eZ\Publish\Core\Base\Exceptions\MissingClass
Returns
object
Definition at line 173 of file Handler.php.
    {
        if ( isset( $this->serviceHandlers[$className] ) )
            return $this->serviceHandlers[$className];
        if ( class_exists( $className ) )
            return $this->serviceHandlers[$className] = new $className( $this, $this->backend );
        throw new MissingClass( $className, 'service handler' );
    }
eZ\Publish\Core\Persistence\InMemory\Handler::trashHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 108 of file Handler.php.
References eZ\Publish\Core\Persistence\InMemory\Handler\serviceHandler().
    {
        return $this->serviceHandler( 'eZ\\Publish\\Core\\Persistence\\InMemory\\TrashHandler' );
    }
eZ\Publish\Core\Persistence\InMemory\Handler::urlAliasHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 116 of file Handler.php.
References eZ\Publish\Core\Persistence\InMemory\Handler\serviceHandler().
    {
        return $this->serviceHandler( 'eZ\\Publish\\Core\\Persistence\\InMemory\\UrlAliasHandler' );
    }
eZ\Publish\Core\Persistence\InMemory\Handler::urlWildcardHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 124 of file Handler.php.
References eZ\Publish\Core\Persistence\InMemory\Handler\serviceHandler().
    {
        return $this->serviceHandler( 'eZ\\Publish\\Core\\Persistence\\InMemory\\UrlWildcardHandler' );
    }
eZ\Publish\Core\Persistence\InMemory\Handler::userHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 92 of file Handler.php.
References eZ\Publish\Core\Persistence\InMemory\Handler\serviceHandler().
    {
        return $this->serviceHandler( 'eZ\\Publish\\Core\\Persistence\\InMemory\\UserHandler' );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\InMemory\Handler::$backend protected
Definition at line 31 of file Handler.php.
eZ\Publish\Core\Persistence\InMemory\Handler::$serviceHandlers = array() protected
Definition at line 24 of file Handler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/InMemory/Handler.php