ezp-next: eZ\Publish\Core\MVC\Symfony\View\Manager Class Reference
eZ\Publish\Core\MVC\Symfony\View\Manager Class Reference
Public Member Functions
__construct (EngineInterface $templateEngine, EventDispatcherInterface $eventDispatcher, Repository $repository, $viewBaseLayout, LoggerInterface $logger=null)
addContentViewProvider (ContentViewProvider $viewProvider, $priority=0)
addLocationViewProvider (LocationViewProvider $viewProvider, $priority=0)
addBlockViewProvider (BlockViewProvider $viewProvider, $priority=0)
getAllContentViewProviders ()
getAllLocationViewProviders ()
getAllBlockViewProviders ()
renderContent (Content $content, $viewType=ViewManagerInterface::VIEW_TYPE_FULL, $parameters=array())
renderLocation (Location $location, $viewType=ViewManagerInterface::VIEW_TYPE_FULL, $parameters=array())
renderBlock (Block $block, $parameters=array())
renderContentView (ContentViewInterface $view, array $defaultParams=array())
Protected Member Functions
sortViewProviders ($property)
Protected Attributes
$templateEngine
$logger
$contentViewProviders = array()
$locationViewProviders = array()
$blockViewProviders = array()
$sortedContentViewProviders
$sortedLocationViewProviders
$sortedBlockViewProviders
$repository
$eventDispatcher
$viewBaseLayout
Additional Inherited Members
Public Attributes inherited from eZ\Publish\Core\MVC\Symfony\View\ViewManagerInterface
const VIEW_TYPE_FULL = 'full'
const VIEW_TYPE_LINE = 'line'
Detailed Description
Definition at line 27 of file Manager.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\View\Manager::__construct (EngineInterface $templateEngine, EventDispatcherInterface $eventDispatcher, Repository $repository, $viewBaseLayout, LoggerInterface $logger = null)
Definition at line 93 of file Manager.php.
References eZ\Publish\Core\MVC\Symfony\View\Manager\$eventDispatcher, eZ\Publish\Core\MVC\Symfony\View\Manager\$logger, eZ\Publish\Core\MVC\Symfony\View\Manager\$repository, eZ\Publish\Core\MVC\Symfony\View\Manager\$templateEngine, and eZ\Publish\Core\MVC\Symfony\View\Manager\$viewBaseLayout.
    {
        $this->templateEngine = $templateEngine;
        $this->eventDispatcher = $eventDispatcher;
        $this->repository = $repository;
        $this->viewBaseLayout = $viewBaseLayout;
        $this->logger = $logger;
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\View\Manager::addBlockViewProvider (BlockViewProvider $viewProvider, $priority = 0)
Registers $viewProvider as a valid location view provider. When this view provider will be called in the chain depends on $priority. The highest $priority is, the earliest the router will be called.
Parameters
\eZ\Publish\Core\MVC\Symfony\View\Provider\Block $viewProvider
int $priority
Definition at line 148 of file Manager.php.
    {
        $this->addViewProvider( $this->blockViewProviders, $viewProvider, $priority );
    }
eZ\Publish\Core\MVC\Symfony\View\Manager::addContentViewProvider (ContentViewProvider $viewProvider, $priority = 0)
Registers $viewProvider as a valid content view provider. When this view provider will be called in the chain depends on $priority. The highest $priority is, the earliest the router will be called.
Parameters
\eZ\Publish\Core\MVC\Symfony\View\Provider\Content $viewProvider
int $priority
Definition at line 124 of file Manager.php.
    {
        $this->addViewProvider( $this->contentViewProviders, $viewProvider, $priority );
    }
eZ\Publish\Core\MVC\Symfony\View\Manager::addLocationViewProvider (LocationViewProvider $viewProvider, $priority = 0)
Registers $viewProvider as a valid location view provider. When this view provider will be called in the chain depends on $priority. The highest $priority is, the earliest the router will be called.
Parameters
\eZ\Publish\Core\MVC\Symfony\View\Provider\Location $viewProvider
int $priority
Definition at line 136 of file Manager.php.
    {
        $this->addViewProvider( $this->locationViewProviders, $viewProvider, $priority );
    }
eZ\Publish\Core\MVC\Symfony\View\Manager::getAllBlockViewProviders ()
Returns
[]
Definition at line 178 of file Manager.php.
References eZ\Publish\Core\MVC\Symfony\View\Manager\$sortedBlockViewProviders, and eZ\Publish\Core\MVC\Symfony\View\Manager\sortViewProviders().
    {
        if ( empty( $this->sortedBlockViewProviders ) )
            $this->sortedBlockViewProviders = $this->sortViewProviders( $this->blockViewProviders );
        return $this->sortedBlockViewProviders;
    }
eZ\Publish\Core\MVC\Symfony\View\Manager::getAllContentViewProviders ()
Returns
[]
Definition at line 156 of file Manager.php.
References eZ\Publish\Core\MVC\Symfony\View\Manager\$sortedContentViewProviders, and eZ\Publish\Core\MVC\Symfony\View\Manager\sortViewProviders().
    {
        if ( empty( $this->sortedContentViewProviders ) )
            $this->sortedContentViewProviders = $this->sortViewProviders( $this->contentViewProviders );
        return $this->sortedContentViewProviders;
    }
eZ\Publish\Core\MVC\Symfony\View\Manager::getAllLocationViewProviders ()
Returns
[]
Definition at line 167 of file Manager.php.
References eZ\Publish\Core\MVC\Symfony\View\Manager\$sortedLocationViewProviders, and eZ\Publish\Core\MVC\Symfony\View\Manager\sortViewProviders().
    {
        if ( empty( $this->sortedLocationViewProviders ) )
            $this->sortedLocationViewProviders = $this->sortViewProviders( $this->locationViewProviders );
        return $this->sortedLocationViewProviders;
    }
eZ\Publish\Core\MVC\Symfony\View\Manager::renderBlock (Block $block, $parameters = array())
Renders $block by selecting the right template. $block will be injected in the selected template.
Parameters
\eZ\Publish\Core\FieldType\Page\Parts\Block $block
array $parameters Parameters to pass to the template called to render the view. By default, it's empty. 'block' entry is reserved for the Block that is viewed.
Exceptions
\RuntimeException
Returns
string
Implements eZ\Publish\Core\MVC\Symfony\View\ViewManagerInterface.
Definition at line 277 of file Manager.php.
References eZ\Publish\Core\MVC\Symfony\View\Manager\getAllBlockViewProviders(), and eZ\Publish\Core\MVC\Symfony\View\Manager\renderContentView().
    {
        foreach ( $this->getAllBlockViewProviders() as $viewProvider )
        {
            $view = $viewProvider->getView( $block );
            if ( $view instanceof ContentViewInterface )
            {
                $parameters['block'] = $block;
                return $this->renderContentView( $view, $parameters );
            }
        }
        throw new RuntimeException( "Unable to find a view for location #$block->id" );
    }
eZ\Publish\Core\MVC\Symfony\View\Manager::renderContent (Content $content, $viewType = ViewManagerInterface::VIEW_TYPE_FULL, $parameters = array())
Renders $content by selecting the right template. $content will be injected in the selected template.
Parameters
\eZ\Publish\API\Repository\Values\Content\Content $content
string $viewType Variation of display for your content. Default is 'full'.
array $parameters Parameters to pass to the template called to render the view. By default, it's empty. 'content' entry is reserved for the Content that is rendered.
Exceptions
\RuntimeException
Returns
string
Implements eZ\Publish\Core\MVC\Symfony\View\ViewManagerInterface.
Definition at line 219 of file Manager.php.
References eZ\Publish\Core\MVC\Symfony\View\Manager\getAllContentViewProviders(), eZ\Publish\API\Repository\Values\Content\Content\getVersionInfo(), and eZ\Publish\Core\MVC\Symfony\View\Manager\renderContentView().
    {
        $contentInfo = $content->getVersionInfo()->getContentInfo();
        foreach ( $this->getAllContentViewProviders() as $viewProvider )
        {
            $view = $viewProvider->getView( $contentInfo, $viewType );
            if ( $view instanceof ContentViewInterface )
            {
                $parameters['content'] = $content;
                return $this->renderContentView( $view, $parameters );
            }
        }
        throw new RuntimeException( "Unable to find a template for #$contentInfo->id" );
    }
eZ\Publish\Core\MVC\Symfony\View\Manager::renderContentView (ContentViewInterface $view, array $defaultParams = array())
Renders passed ContentView object via the template engine. If $view's template identifier is a closure, then it is called directly and the result is returned as is.
Parameters
\eZ\Publish\Core\MVC\Symfony\View\ContentViewInterface $view
array $defaultParams
Returns
string
Implements eZ\Publish\Core\MVC\Symfony\View\ViewManagerInterface.
Definition at line 301 of file Manager.php.
References eZ\Publish\Core\MVC\Symfony\View\Manager\$viewBaseLayout, eZ\Publish\Core\MVC\Symfony\View\ContentViewInterface\addParameters(), eZ\Publish\Core\MVC\Symfony\View\ContentViewInterface\getParameters(), eZ\Publish\Core\MVC\Symfony\View\ContentViewInterface\getTemplateIdentifier(), and eZ\Publish\Core\MVC\Symfony\MVCEvents\PRE_CONTENT_VIEW.
    {
        $defaultParams['viewbaseLayout'] = $this->viewBaseLayout;
        $view->addParameters( $defaultParams );
        $this->eventDispatcher->dispatch(
            MVCEvents::PRE_CONTENT_VIEW,
            new PreContentViewEvent( $view )
        );
        $templateIdentifier = $view->getTemplateIdentifier();
        $params = $view->getParameters();
        if ( $templateIdentifier instanceof \Closure )
            return $templateIdentifier( $params );
        return $this->templateEngine->render( $templateIdentifier, $params );
    }
eZ\Publish\Core\MVC\Symfony\View\Manager::renderLocation (Location $location, $viewType = ViewManagerInterface::VIEW_TYPE_FULL, $parameters = array())
Renders $location by selecting the right template for $viewType. $content and $location will be injected in the selected template.
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location
string $viewType Variation of display for your content. Default is 'full'.
array $parameters Parameters to pass to the template called to render the view. By default, it's empty. 'location' and 'content' entries are reserved for the Location (and its Content) that is viewed.
Exceptions
\RuntimeException
Returns
string
Implements eZ\Publish\Core\MVC\Symfony\View\ViewManagerInterface.
Definition at line 249 of file Manager.php.
References eZ\Publish\Core\MVC\Symfony\View\Manager\getAllLocationViewProviders(), eZ\Publish\API\Repository\Values\Content\Location\getContentInfo(), and eZ\Publish\Core\MVC\Symfony\View\Manager\renderContentView().
    {
        foreach ( $this->getAllLocationViewProviders() as $viewProvider )
        {
            $view = $viewProvider->getView( $location, $viewType );
            if ( $view instanceof ContentViewInterface )
            {
                $parameters['location'] = $location;
                $parameters['content'] = $this->repository->getContentService()->loadContentByContentInfo( $location->getContentInfo() );
                return $this->renderContentView( $view, $parameters );
            }
        }
        throw new RuntimeException( "Unable to find a view for location #$location->id" );
    }
eZ\Publish\Core\MVC\Symfony\View\Manager::sortViewProviders ($property) protected
Sort the registered view providers by priority. The highest priority number is the highest priority (reverse sorting)
Parameters
array $property view providers to sort
Returns
[]|[]|[]
Definition at line 193 of file Manager.php.
    {
        $sortedViewProviders = array();
        krsort( $property );
        foreach ( $property as $viewProvider )
        {
            $sortedViewProviders = array_merge( $sortedViewProviders, $viewProvider );
        }
        return $sortedViewProviders;
    }
Member Data Documentation
eZ\Publish\Core\MVC\Symfony\View\Manager::$blockViewProviders = array() protected
Definition at line 58 of file Manager.php.
eZ\Publish\Core\MVC\Symfony\View\Manager::$contentViewProviders = array() protected
Definition at line 44 of file Manager.php.
eZ\Publish\Core\MVC\Symfony\View\Manager::$eventDispatcher protected
Definition at line 83 of file Manager.php.
eZ\Publish\Core\MVC\Symfony\View\Manager::$locationViewProviders = array() protected
Definition at line 51 of file Manager.php.
eZ\Publish\Core\MVC\Symfony\View\Manager::$logger protected
Definition at line 37 of file Manager.php.
eZ\Publish\Core\MVC\Symfony\View\Manager::$repository protected
Definition at line 78 of file Manager.php.
eZ\Publish\Core\MVC\Symfony\View\Manager::$sortedBlockViewProviders protected
Definition at line 73 of file Manager.php.
eZ\Publish\Core\MVC\Symfony\View\Manager::$sortedContentViewProviders protected
Definition at line 63 of file Manager.php.
eZ\Publish\Core\MVC\Symfony\View\Manager::$sortedLocationViewProviders protected
Definition at line 68 of file Manager.php.
eZ\Publish\Core\MVC\Symfony\View\Manager::$templateEngine protected
Definition at line 32 of file Manager.php.
eZ\Publish\Core\MVC\Symfony\View\Manager::$viewBaseLayout protected
Definition at line 91 of file Manager.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/View/Manager.php