ezp-next: eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Regex\Host Class Reference
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Regex\Host Class Reference
Public Member Functions
__construct (array $siteAccessesConfiguration)
getName ()
setRequest (SimplifiedRequest $request)
Public Member Functions inherited from eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Regex
__construct ($regex, $itemNumber)
match ()
setMatchElement ($element)
Detailed Description
Definition at line 16 of file Host.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Regex\Host::__construct (array $siteAccessesConfiguration)
Constructor.
Parameters
array $siteAccessesConfiguration SiteAccesses configuration.
Definition at line 23 of file Host.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\__construct().
    {
        parent::__construct(
            isset( $siteAccessesConfiguration["regex"] ) ? $siteAccessesConfiguration["regex"] : "",
            isset( $siteAccessesConfiguration["itemNumber"] ) ? (int)$siteAccessesConfiguration["itemNumber"] : 1
        );
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Regex\Host::getName ()
Returns the matcher's name. This information will be stored in the SiteAccess object itself to quickly be able to identify the matcher type.
Returns
string
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 31 of file Host.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Regex\Host\getName().
    {
        return 'host:regexp';
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Regex\Host::setRequest (SimplifiedRequest $request)
Injects the request object to match against.
Parameters
\eZ\Publish\Core\MVC\Symfony\Routing\SimplifiedRequest $request
Returns
void
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 43 of file Host.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Regex\setMatchElement(), and eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Regex\Host\setRequest().
    {
        $this->setMatchElement( $request->host );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Regex/Host.php