ezp-next: eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper\Aggregate Class Reference
eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper\Aggregate Class Reference
Public Member Functions
__construct (array $mappers=array())
addMapper (FieldValueMapper $mapper)
canMap (Field $field)
map (Field $field)
Public Member Functions inherited from eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper
canMap (Field $field)
map (Field $field)
Protected Attributes
$mappers = array()
Detailed Description
Maps raw document field values to something Solr can index.
Definition at line 19 of file Aggregate.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper\Aggregate::__construct (array $mappers = array())
COnstruct from optional mapper array
Parameters
array $mappers
Returns
void
Definition at line 35 of file Aggregate.php.
References eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper\Aggregate\$mappers, eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper\Aggregate\__construct(), and eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper\Aggregate\addMapper().
    {
        foreach ( $mappers as $mapper )
        {
            $this->addMapper( $mapper );
        }
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper\Aggregate::addMapper (FieldValueMapper $mapper)
Adds mapper
Parameters
FieldValueMapper $mapper
Returns
void
Definition at line 50 of file Aggregate.php.
References eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper\Aggregate\addMapper().
    {
        $this->mappers[] = $mapper;
    }
eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper\Aggregate::canMap (Field $field)
Check if field can be mapped
Parameters
Field $field
Returns
void
Definition at line 62 of file Aggregate.php.
    {
        return true;
    }
eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper\Aggregate::map (Field $field)
Map field value to a proper Solr representation
Parameters
Field $field
Returns
void
Definition at line 74 of file Aggregate.php.
    {
        foreach ( $this->mappers as $mapper )
        {
            if ( $mapper->canMap( $field ) )
            {
                return $mapper->map( $field );
            }
        }
        throw new NotImplementedException( "No mapper avialable for: " . get_class( $field->type ) );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Solr\Content\Search\FieldValueMapper\Aggregate::$mappers = array() protected
Definition at line 26 of file Aggregate.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Solr/Content/Search/FieldValueMapper/Aggregate.php