ezp-next: eZ\Publish\Core\FieldType\Page\PageService Class Reference
eZ\Publish\Core\FieldType\Page\PageService Class Reference
Public Member Functions
__construct (array $zoneDefinition=array(), array $blockDefinition=array())
getZoneDefinition ()
getZoneDefinitionByLayout ($layoutIdentifier)
getLayoutTemplate ($layoutIdentifier)
hasZoneLayout ($layoutIdentifier)
getAvailableZoneLayouts ()
getBlockDefinition ()
getBlockDefinitionByIdentifier ($blockIdentifier)
hasBlockDefinition ($blockIdentifier)
setStorageGateway (Gateway $storageGateway)
hasStorageGateway ()
getValidBlockItems (Block $block)
getLastValidBlockItem (Block $block)
getWaitingBlockItems (Block $block)
getArchivedBlockItems (Block $block)
Protected Member Functions
getStorageGateway ()
Protected Attributes
$zoneDefinition
$blockDefinition
$storageGateway
$validBlockItems
$lastValidItems
$waitingBlockItems
$archivedBlockItems
Detailed Description
Definition at line 18 of file PageService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\FieldType\Page\PageService::__construct (array $zoneDefinition = array(), array $blockDefinition = array())
Constructor
Parameters
array $zoneDefinition
array $blockDefinition
Definition at line 73 of file PageService.php.
References eZ\Publish\Core\FieldType\Page\PageService\$blockDefinition, and eZ\Publish\Core\FieldType\Page\PageService\$zoneDefinition.
    {
        $this->zoneDefinition = $zoneDefinition;
        $this->blockDefinition = $blockDefinition;
        $this->validBlockItems = new SplObjectStorage();
        $this->lastValidItems = new SplObjectStorage();
        $this->waitingBlockItems = new SplObjectStorage();
        $this->archivedBlockItems = new SplObjectStorage();
    }
Member Function Documentation
eZ\Publish\Core\FieldType\Page\PageService::getArchivedBlockItems (Block $block)
Returns archived items (that were previously displayed), for a given block.
Parameters
\eZ\Publish\Core\FieldType\Page\Parts\Block $block
Returns
[]
Definition at line 269 of file PageService.php.
References eZ\Publish\Core\FieldType\Page\PageService\getStorageGateway().
    {
        if ( isset( $this->archivedBlockItems[$block] ) )
            return $this->archivedBlockItems[$block];
        return $this->archivedBlockItems[$block] = $this->getStorageGateway()->getArchivedBlockItems( $block );
    }
eZ\Publish\Core\FieldType\Page\PageService::getAvailableZoneLayouts ()
Returns list of available zone layouts
Returns
array
Definition at line 140 of file PageService.php.
    {
        return array_keys( $this->zoneDefinition );
    }
eZ\Publish\Core\FieldType\Page\PageService::getBlockDefinition ()
Returns block definition as an array
Returns
array
Definition at line 150 of file PageService.php.
References eZ\Publish\Core\FieldType\Page\PageService\$blockDefinition.
    {
        return $this->blockDefinition;
    }
eZ\Publish\Core\FieldType\Page\PageService::getBlockDefinitionByIdentifier ($blockIdentifier)
Returns a block definition for a given block identifier.
Parameters
string $blockIdentifier
Returns
array
Exceptions
\OutOfBoundsException If $blockIdentifier is invalid.
Definition at line 164 of file PageService.php.
    {
        if ( !isset( $this->blockDefinition[$blockIdentifier] ) )
            throw new OutOfBoundsException( "Could not find an ezpage block definition for given identifier '$blockIdentifier'" );
        return $this->blockDefinition[$blockIdentifier];
    }
eZ\Publish\Core\FieldType\Page\PageService::getLastValidBlockItem (Block $block)
Returns the last valid item, for a given block.
Parameters
\eZ\Publish\Core\FieldType\Page\Parts\Block $block
Returns
[]|null
Definition at line 239 of file PageService.php.
References eZ\Publish\Core\FieldType\Page\PageService\getStorageGateway().
    {
        if ( isset( $this->lastValidItems[$block] ) )
            return $this->lastValidItems[$block];
        return $this->lastValidItems[$block] = $this->getStorageGateway()->getLastValidBlockItem( $block );
    }
eZ\Publish\Core\FieldType\Page\PageService::getLayoutTemplate ($layoutIdentifier)
Returns the template to use for given layout.
Parameters
string $layoutIdentifier
Returns
string
Reimplemented in eZ\Bundle\EzPublishLegacyBundle\FieldType\Page\PageService.
Definition at line 117 of file PageService.php.
References eZ\Publish\Core\FieldType\Page\PageService\getZoneDefinitionByLayout().
    {
        $def = $this->getZoneDefinitionByLayout( $layoutIdentifier );
        return $def['template'];
    }
eZ\Publish\Core\FieldType\Page\PageService::getStorageGateway () protected
Exceptions
\RuntimeException If storage gateway is not set.
Returns
Definition at line 209 of file PageService.php.
References eZ\Publish\Core\FieldType\Page\PageService\$storageGateway, and eZ\Publish\Core\FieldType\Page\PageService\hasStorageGateway().
    {
        if ( !$this->hasStorageGateway() )
            throw new RuntimeException( 'Missing storage gateway for Page field type.' );
        return $this->storageGateway;
    }
eZ\Publish\Core\FieldType\Page\PageService::getValidBlockItems (Block $block)
Returns valid items (that are to be displayed), for a given block.
Parameters
\eZ\Publish\Core\FieldType\Page\Parts\Block $block
Returns
[]
Definition at line 224 of file PageService.php.
References eZ\Publish\Core\FieldType\Page\PageService\getStorageGateway().
    {
        if ( isset( $this->validBlockItems[$block] ) )
            return $this->validBlockItems[$block];
        return $this->validBlockItems[$block] = $this->getStorageGateway()->getValidBlockItems( $block );
    }
eZ\Publish\Core\FieldType\Page\PageService::getWaitingBlockItems (Block $block)
Returns queued items (the next to be displayed), for a given block.
Parameters
\eZ\Publish\Core\FieldType\Page\Parts\Block $block
Returns
[]
Definition at line 254 of file PageService.php.
References eZ\Publish\Core\FieldType\Page\PageService\getStorageGateway().
    {
        if ( isset( $this->waitingBlockItems[$block] ) )
            return $this->waitingBlockItems[$block];
        return $this->waitingBlockItems[$block] = $this->getStorageGateway()->getWaitingBlockItems( $block );
    }
eZ\Publish\Core\FieldType\Page\PageService::getZoneDefinition ()
Returns zone definition as an array
Returns
array
Definition at line 88 of file PageService.php.
References eZ\Publish\Core\FieldType\Page\PageService\$zoneDefinition.
    {
        return $this->zoneDefinition;
    }
eZ\Publish\Core\FieldType\Page\PageService::getZoneDefinitionByLayout ($layoutIdentifier)
Returns a zone definition for a given layout. It consists of a configuration array for the given layout.
Parameters
string $layoutIdentifier
Returns
array
Exceptions
\OutOfBoundsException If $layoutIdentifier is invalid
Definition at line 103 of file PageService.php.
    {
        if ( !isset( $this->zoneDefinition[$layoutIdentifier] ) )
            throw new OutOfBoundsException( "Could not find an ezpage zone definition block for given layout '$layoutIdentifier'" );
        return $this->zoneDefinition[$layoutIdentifier];
    }
eZ\Publish\Core\FieldType\Page\PageService::hasBlockDefinition ($blockIdentifier)
Checks if block definition contains a block having $blockIdentifier as identifier.
Parameters
string $blockIdentifier
Returns
bool
Definition at line 179 of file PageService.php.
    {
        return isset( $this->blockDefinition[$blockIdentifier] );
    }
eZ\Publish\Core\FieldType\Page\PageService::hasStorageGateway ()
Checks if storage gateway has already been injected or not.
Returns
bool
Definition at line 199 of file PageService.php.
    {
        return isset( $this->storageGateway );
    }
eZ\Publish\Core\FieldType\Page\PageService::hasZoneLayout ($layoutIdentifier)
Checks if zone definition contains a layout having $layoutIdentifier as identifier.
Parameters
string $layoutIdentifier
Returns
bool
Definition at line 130 of file PageService.php.
    {
        return isset( $this->zoneDefinition[$layoutIdentifier] );
    }
eZ\Publish\Core\FieldType\Page\PageService::setStorageGateway (Gateway $storageGateway)
Injects the storage gateway to interact with.
Parameters
\eZ\Publish\Core\FieldType\Page\PageStorage\Gateway $storageGateway
Definition at line 189 of file PageService.php.
References eZ\Publish\Core\FieldType\Page\PageService\$storageGateway.
    {
        $this->storageGateway = $storageGateway;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\Page\PageService::$archivedBlockItems protected
Definition at line 65 of file PageService.php.
eZ\Publish\Core\FieldType\Page\PageService::$blockDefinition protected
Definition at line 32 of file PageService.php.
eZ\Publish\Core\FieldType\Page\PageService::$lastValidItems protected
Definition at line 51 of file PageService.php.
eZ\Publish\Core\FieldType\Page\PageService::$storageGateway protected
Definition at line 37 of file PageService.php.
eZ\Publish\Core\FieldType\Page\PageService::$validBlockItems protected
Definition at line 44 of file PageService.php.
eZ\Publish\Core\FieldType\Page\PageService::$waitingBlockItems protected
Definition at line 58 of file PageService.php.
eZ\Publish\Core\FieldType\Page\PageService::$zoneDefinition protected
Definition at line 25 of file PageService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Page/PageService.php