ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler Class Reference
Public Member Functions
__construct (Gateway $gateway, Mapper $mapper, LocationGateway $locationGateway, LanguageHandler $languageHandler, TransformationProcessor $transformationProcessor, array $configuration=array())
createCustomUrlAlias ($locationId, $path, $forwarding=false, $languageCode=null, $alwaysAvailable=false)
createGlobalUrlAlias ($resource, $path, $forwarding=false, $languageCode=null, $alwaysAvailable=false)
listURLAliasesForLocation ($locationId, $custom=false)
listGlobalURLAliases ($languageCode=null, $offset=0, $limit=-1)
removeURLAliases (array $urlAliases)
lookup ($url)
loadUrlAlias ($id)
locationMoved ($locationId, $oldParentId, $newParentId)
locationCopied ($locationId, $newLocationId, $newParentId)
locationDeleted ($locationId)
Public Member Functions inherited from eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler
publishUrlAliasForLocation ($locationId, $parentLocationId, $name, $languageCode, $alwaysAvailable=false)
Protected Member Functions
createUrlAlias ($action, $path, $forward, $languageCode, $alwaysAvailable)
insertNopEntry ($parentId, $text, $textMD5)
getRealAliasId ($locationId)
copySubtree ($actionMap, $oldParentAliasId, $newParentAliasId)
getCopiedLocationsMap ($oldParentId, $newParentId)
removeSubtree ($parentId, $action)
convertToAlias ($text, $defaultValue="_1", $transformation=null)
getUniqueCounterValue ($text, $parentId)
getHash ($text)
cleanupText ($text, $method)
getWordSeparator ()
Protected Attributes
$configuration
$gateway
$locationGateway
$mapper
$languageHandler
$transformationProcessor
Detailed Description
The UrlAlias Handler provides nice urls management.
Its methods operate on a representation of the url alias data structure held inside a storage engine.
Definition at line 27 of file Handler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::__construct (Gateway $gateway, Mapper $mapper, LocationGateway $locationGateway, LanguageHandler $languageHandler, TransformationProcessor $transformationProcessor, array $configuration = array())
Creates a new UrlAlias Handler
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Gateway $gateway
\eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper $mapper
\eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway $locationGateway
\eZ\Publish\SPI\Persistence\Content\Language\Handler $languageHandler
\eZ\Publish\Core\Persistence\Legacy\Content\Search\TransformationProcessor $transformationProcessor
array $configuration
Definition at line 196 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\$configuration, eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\$gateway, eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\$languageHandler, eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\$locationGateway, eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\$mapper, and eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\$transformationProcessor.
    {
        $this->gateway = $gateway;
        $this->mapper = $mapper;
        $this->locationGateway = $locationGateway;
        $this->languageHandler = $languageHandler;
        $this->transformationProcessor = $transformationProcessor;
        $this->configuration = $configuration + $this->configuration;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::cleanupText ($text, $method) protected
Cleans up
Parameters
string $text
string $method
Returns
string
Definition at line 945 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\getWordSeparator().
    {
        switch ( $method )
        {
            case "url_cleanup":
                $sep = $this->getWordSeparator();
                $sepQ = preg_quote( $sep );
                $text = preg_replace(
                    array(
                        "#[^a-zA-Z0-9_!.-]+#",
                        "#^[.]+|[!.]+$#", # Remove dots at beginning/end
                        "#\.\.+#", # Remove double dots
                        "#[{$sepQ}]+#", # Turn multiple separators into one
                        "#^[{$sepQ}]+|[{$sepQ}]+$#" # Strip separator from beginning/end
                    ),
                    array(
                        $sep,
                        $sep,
                        $sep,
                        $sep,
                        ""
                    ),
                    $text
                );
                break;
            case "url_cleanup_iri":
                // With IRI support we keep all characters except some reserved ones,
                // they are space, ampersand, semi-colon, forward slash, colon, equal sign, question mark,
                //          square brackets, parenthesis, plus.
                //
                // Note: Space is turned into a dash to make it easier for people to
                //       paste urls from the system and have the whole url recognized
                //       instead of being broken off
                $sep = $this->getWordSeparator();
                $sepQ = preg_quote( $sep );
                $prepost = " ." . $sepQ;
                if ( $sep != "-" )
                    $prepost .= "-";
                $text = preg_replace(
                    array(
                        "#[ \\\\%\#&;/:=?\[\]()+]+#",
                        "#^[.]+|[!.]+$#", # Remove dots at beginning/end
                        "#\.\.+#", # Remove double dots
                        "#[{$sepQ}]+#", # Turn multiple separators into one
                        "#^[{$prepost}]+|[{$prepost}]+$#"
                    ),
                    array(
                        $sep,
                        $sep,
                        $sep,
                        $sep,
                        ""
                    ),
                    $text
                );
                break;
            case "url_cleanup_compat":
                // Old style of url alias with lowercase only and underscores for separators
                $text = strtolower( $text );
                $text = preg_replace(
                    array(
                        "#[^a-z0-9]+#",
                        "#^_+|_+$#"
                    ),
                    array(
                        "_",
                        ""
                    ),
                    $text
                );
                break;
            default:
                // Nothing
        }
        return $text;
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::convertToAlias ($text, $defaultValue = "_1", $transformation = null) protected
Converts the path $urlElement into a new alias url which only consists of valid characters in the URL. For non-Unicode setups this means character in the range a-z, numbers and _, for Unicode setups it means all characters except space, &, ;, /, :, =, ?, [, ], (,), -
Invalid characters are converted to -.
Example with a non-Unicode setup
'My car' => 'My-car' 'What is this?' => 'What-is-this' 'This & that' => 'This-that' 'myfile.tpl' => 'Myfile-tpl', 'øæå' => 'oeaeaa'
Parameters
string $text
string $defaultValue
string | null $transformation
Returns
string
Definition at line 865 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\cleanupText().
    {
        if ( !isset( $transformation ) )
        {
            $transformation = $this->configuration["transformation"];
        }
        if ( strlen( $text ) === 0 )
        {
            $text = $defaultValue;
        }
        if ( isset( $this->configuration["transformationGroups"][$transformation]["commands"] )
            && !empty( $this->configuration["transformationGroups"][$transformation]["commands"] )
        )
        {
            $text = $this->transformationProcessor->transform(
                $text,
                $this->configuration["transformationGroups"][$transformation]["commands"]
            );
        }
        return $this->cleanupText(
            $text,
            $this->configuration["transformationGroups"][$transformation]["cleanupMethod"]
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::copySubtree ($actionMap, $oldParentAliasId, $newParentAliasId) protected
Recursively copies aliases from old parent under new parent.
Parameters
array $actionMap
mixed $oldParentAliasId
mixed $newParentAliasId
Returns
void
Definition at line 764 of file Handler.php.
    {
        $rows = $this->gateway->loadAutogeneratedEntries( $oldParentAliasId );
        $newIdsMap = array();
        foreach ( $rows as $row )
        {
            $oldParentAliasId = $row["id"];
            // Ensure that same action entries remain grouped by the same id
            if ( !isset( $newIdsMap[$oldParentAliasId] ) )
            {
                $newIdsMap[$oldParentAliasId] = $this->gateway->getNextId();
            }
            $row["action"] = $actionMap[$row["action"]];
            $row["parent"] = $newParentAliasId;
            $row["id"] = $row["link"] = $newIdsMap[$oldParentAliasId];
            $this->gateway->insertRow( $row );
            $this->copySubtree(
                $actionMap,
                $oldParentAliasId,
                $row["id"]
            );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::createCustomUrlAlias ($locationId, $path, $forwarding = false, $languageCode = null, $alwaysAvailable = false)
Create a user chosen $alias pointing to $locationId in $languageCode.
If $languageCode is null the $alias is created in the system's default language. $alwaysAvailable makes the alias available in all languages.
Parameters
mixed $locationId
string $path
boolean $forwarding
string $languageCode
boolean $alwaysAvailable
Returns
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 370 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\createUrlAlias().
    {
        return $this->createUrlAlias(
            "eznode:" . $locationId,
            $path,
            $forwarding,
            $languageCode,
            $alwaysAvailable
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::createGlobalUrlAlias ($resource, $path, $forwarding = false, $languageCode = null, $alwaysAvailable = false)
Create a user chosen $alias pointing to a resource in $languageCode. This method does not handle location resources - if a user enters a location target the createCustomUrlAlias method has to be used.
If $languageCode is null the $alias is created in the system's default language. $alwaysAvailable makes the alias available in all languages.
Exceptions
\eZ\Publish\API\Repository\Exceptions\ForbiddenException if the path already exists for the given language
Parameters
string $resource
string $path
boolean $forwarding
string $languageCode
boolean $alwaysAvailable
Returns
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 399 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\createUrlAlias().
    {
        return $this->createUrlAlias(
            $resource,
            $path,
            $forwarding,
            $languageCode,
            $alwaysAvailable
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::createUrlAlias ($action, $path, $forward, $languageCode, $alwaysAvailable) protected
Internal method for creating global or custom URL alias (these are handled in the same way)
Exceptions
\eZ\Publish\Core\Base\Exceptions\ForbiddenException if the path already exists for the given language
Parameters
string $action
string $path
boolean $forward
string | null $languageCode
boolean $alwaysAvailable
Returns
Definition at line 423 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\convertToAlias(), eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\getHash(), and eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\insertNopEntry().
    {
        $pathElements = explode( "/", $path );
        $topElement = array_pop( $pathElements );
        $languageId = $this->languageHandler->loadByLanguageCode( $languageCode )->id;
        $parentId = 0;
        // Handle all path elements except topmost one
        $isPathNew = false;
        foreach ( $pathElements as $level => $pathElement )
        {
            $pathElement = $this->convertToAlias( $pathElement, "noname" . $level + 1 );
            $pathElementMD5 = $this->getHash( $pathElement );
            if ( !$isPathNew )
            {
                $row = $this->gateway->loadRow( $parentId, $pathElementMD5 );
                if ( empty( $row ) )
                {
                    $isPathNew = true;
                }
                else
                {
                    $parentId = $row["link"];
                }
            }
            if ( $isPathNew )
            {
                $parentId = $this->insertNopEntry( $parentId, $pathElement, $pathElementMD5 );
            }
        }
        // Handle topmost path element
        $topElement = $this->convertToAlias( $topElement, "noname" . count( $pathElements ) + 1 );
        // If last (next to topmost) entry parent is special root entry we handle topmost entry as first level entry
        // That is why we need to reset $parentId to 0 and empty $createdPath
        if ( $parentId != 0 && $this->gateway->isRootEntry( $parentId ) )
        {
            $parentId = 0;
        }
        $topElementMD5 = $this->getHash( $topElement );
        // Set common values for two cases below
        $data = array(
            "action" => $action,
            "is_alias" => 1,
            "alias_redirects" => $forward ? 1 : 0,
            "parent" => $parentId,
            "text" => $topElement,
            "text_md5" => $topElementMD5,
            "is_original" => 1
        );
        // Try to load topmost element
        if ( !$isPathNew )
        {
            $row = $this->gateway->loadRow( $parentId, $topElementMD5 );
        }
        // If nothing was returned perform insert
        if ( $isPathNew || empty( $row ) )
        {
            $data["lang_mask"] = $languageId | (int)$alwaysAvailable;
            $this->gateway->insertRow( $data );
        }
        // Row exists, check if it is reusable. There are 2 cases when this is possible:
        // 1. NOP entry
        // 2. history entry
        else if ( $row["action"] == "nop:" || $row["is_original"] == 0 )
        {
            $data["lang_mask"] = $languageId | (int)$alwaysAvailable;
            // If history is reused move link to id
            $data["link"] = $row["id"];
            $this->gateway->updateRow(
                $parentId,
                $topElementMD5,
                $data
            );
        }
        else
        {
            throw new ForbiddenException( "Path '$path' already exists for the given language" );
        }
        return $this->mapper->extractUrlAliasFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::getCopiedLocationsMap ($oldParentId, $newParentId) protected
Parameters
mixed $oldParentId
mixed $newParentId
Returns
array
Definition at line 797 of file Handler.php.
    {
        $originalLocations = $this->locationGateway->getSubtreeContent( $oldParentId );
        $copiedLocations = $this->locationGateway->getSubtreeContent( $newParentId );
        $map = array();
        foreach ( $originalLocations as $index => $originalLocation )
        {
            $map["eznode:" . $originalLocation["node_id"]] = "eznode:" . $copiedLocations[$index]["node_id"];
        }
        return $map;
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::getHash ($text) protected
Parameters
string $text
Returns
string
Definition at line 932 of file Handler.php.
    {
        return md5( strtolower( $text ) );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::getRealAliasId ($locationId) protected
Returns possibly corrected alias id for given $locationId.
First level entries must have parent id set to 0 instead of their parent location alias id. There are two cases when alias id needs to be corrected: 1) location is special location without URL alias (location with id=1 in standard installation) 2) location is site root location, having special root entry in the ezurlalias_ml table (location with id=2 in standard installation)
Parameters
mixed $locationId
Returns
int
Definition at line 739 of file Handler.php.
    {
        $data = $this->gateway->loadAutogeneratedEntry( "eznode:" . $locationId );
        if ( empty( $data ) || $data["id"] != 0 && $this->gateway->isRootEntry( $data["id"] ) )
        {
            $id = 0;
        }
        else
        {
            $id = $data["id"];
        }
        return $id;
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::getUniqueCounterValue ($text, $parentId) protected
Returns unique counter number that is appended to the path element in order to make it unique against system reserved names and other entries on the same level.
Comparison is done only if parent element id is 0 (meaning that entry is at first path element). In a case when reserved name is matched method will return 2. When parent element id is not 0 or when there is no match with reserved names this will return 1, which is default value not appended to name. Note: this is used only when publishing URL aliases, when creating global and custom aliases user is allowed to create first level entries that collide with reserved names. Also, in actual creation of the alias name will be further checked against existing elements under the same parent, using unique counter value determined here as starting unique counter value.
Parameters
string $text
int $parentId
Returns
int
Definition at line 911 of file Handler.php.
    {
        if ( $parentId === 0 )
        {
            foreach ( $this->configuration["reservedNames"] as $reservedName )
            {
                if ( strcasecmp( $text, $reservedName ) === 0 )
                {
                    return 2;
                }
            }
        }
        return 1;
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::getWordSeparator () protected
Returns word separator value
Returns
string
Definition at line 1028 of file Handler.php.
    {
        switch ( $this->configuration["wordSeparatorName"] )
        {
            case "dash":
                return "-";
            case "underscore":
                return "_";
            case "space":
                return " ";
        }
        return "-";
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::insertNopEntry ($parentId, $text, $textMD5) protected
Convenience method for inserting nop type row.
Parameters
mixed $parentId
string $text
string $textMD5
Returns
mixed
Definition at line 519 of file Handler.php.
    {
        return $this->gateway->insertRow(
            array(
                "lang_mask" => 1,
                "action" => "nop:",
                "parent" => $parentId,
                "text" => $text,
                "text_md5" => $textMD5
            )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::listGlobalURLAliases ($languageCode = null, $offset = 0, $limit = -1)
List global aliases.
Parameters
string | null $languageCode
int $offset
int $limit
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 560 of file Handler.php.
    {
        $data = $this->gateway->listGlobalEntries( $languageCode, $offset, $limit );
        foreach ( $data as &$entry )
        {
            $entry["raw_path_data"] = $this->gateway->loadPathData( $entry["id"] );
        }
        return $this->mapper->extractUrlAliasListFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::listURLAliasesForLocation ($locationId, $custom = false)
List of user generated or autogenerated url entries, pointing to $locationId.
Parameters
mixed $locationId
boolean $custom if true the user generated aliases are listed otherwise the autogenerated
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 540 of file Handler.php.
    {
        $data = $this->gateway->loadLocationEntries( $locationId, $custom );
        foreach ( $data as &$entry )
        {
            $entry["raw_path_data"] = $this->gateway->loadPathData( $entry["id"] );
        }
        return $this->mapper->extractUrlAliasListFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::loadUrlAlias ($id)
Loads URL alias by given $id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException
Parameters
string $id
Returns
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 653 of file Handler.php.
    {
        list( $parentId, $textMD5 ) = explode( "-", $id );
        $data = $this->gateway->loadRow( $parentId, $textMD5 );
        if ( empty( $data ) )
        {
            throw new NotFoundException( "URLAlias", $id );
        }
        $data["raw_path_data"] = $this->gateway->loadPathData( $data["id"] );
        return $this->mapper->extractUrlAliasFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::locationCopied ($locationId, $newLocationId, $newParentId)
Notifies the underlying engine that a location has moved.
This method triggers the creation of the autogenerated aliases for the copied locations
Parameters
mixed $locationId
mixed $oldParentId
mixed $newParentId
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 711 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\copySubtree(), eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\getCopiedLocationsMap(), and eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\getRealAliasId().
    {
        $newParentAliasId = $this->getRealAliasId( $newLocationId );
        $oldParentAliasId = $this->getRealAliasId( $locationId );
        $actionMap = $this->getCopiedLocationsMap( $locationId, $newLocationId );
        $this->copySubtree(
            $actionMap,
            $oldParentAliasId,
            $newParentAliasId,
            $locationId
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::locationDeleted ($locationId)
Notifies the underlying engine that a location was deleted or moved to trash
Parameters
mixed $locationId
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 816 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\removeSubtree().
    {
        $action = "eznode:" . $locationId;
        $entry = $this->gateway->loadAutogeneratedEntry( $action );
        $this->removeSubtree( $entry["id"], $action );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::locationMoved ($locationId, $oldParentId, $newParentId)
Notifies the underlying engine that a location has moved.
This method triggers the change of the autogenerated aliases.
Parameters
mixed $locationId
mixed $oldParentId
mixed $newParentId
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 679 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\getRealAliasId().
    {
        // @todo optimize: $newLocationAliasId is already available in self::publishUrlAliasForLocation() as $newId
        $newParentLocationAliasId = $this->getRealAliasId( $newParentId );
        $newLocationAlias = $this->gateway->loadAutogeneratedEntry(
            "eznode:" . $locationId,
            $newParentLocationAliasId
        );
        $oldParentLocationAliasId = $this->getRealAliasId( $oldParentId );
        $oldLocationAlias = $this->gateway->loadAutogeneratedEntry(
            "eznode:" . $locationId,
            $oldParentLocationAliasId
        );
        // Historize alias for old location
        $this->gateway->historizeId( $oldLocationAlias["id"], $newLocationAlias["id"] );
        // Reparent subtree of old location to new location
        $this->gateway->reparent( $oldLocationAlias["id"], $newLocationAlias["id"] );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::lookup ($url)
Looks up a url alias for the given url
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException
\RuntimeException
\eZ\Publish\Core\Base\Exceptions\NotFoundException
Parameters
string $url
Returns
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 608 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler\getHash().
    {
        $urlHashes = array();
        foreach ( explode( "/", $url ) as $level => $text )
        {
            $urlHashes[$level] = $this->getHash( $text );
        }
        $data = $this->gateway->loadUrlAliasData( $urlHashes );
        if ( empty( $data ) )
        {
            throw new NotFoundException( "URLAlias", $url );
        }
        $pathDepth = count( $urlHashes );
        $hierarchyData = array();
        $isPathHistory = false;
        for ( $level = 0; $level < $pathDepth; ++$level )
        {
            $prefix = $level === $pathDepth - 1 ? "" : "ezurlalias_ml" . $level . "_";
            $isPathHistory = $isPathHistory ?: ( $data[$prefix . "link"] != $data[$prefix . "id"] );
            $hierarchyData[$level] = array(
                "id" => $data[$prefix . "id"],
                "parent" => $data[$prefix . "parent"],
                "action" => $data[$prefix . "action"]
            );
        }
        $data["is_path_history"] = $isPathHistory;
        $data["raw_path_data"] = ( $data["action_type"] == "eznode" && !$data["is_alias"] )
            ? $this->gateway->loadPathDataByHierarchy( $hierarchyData )
            : $this->gateway->loadPathData( $data["id"] );
        return $this->mapper->extractUrlAliasFromData( $data );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::removeSubtree ($parentId, $action) protected
Recursively removes aliases by given parent id and action
Parameters
mixed $parentId
string $action
Returns
void
Definition at line 832 of file Handler.php.
    {
        $entries = $this->gateway->loadAutogeneratedEntries( $parentId, true );
        foreach ( $entries as $entry )
        {
            $this->removeSubtree( $entry["id"], $entry["action"] );
        }
        $this->gateway->removeByAction( $action );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::removeURLAliases (array $urlAliases)
Removes url aliases.
Autogenerated aliases are not removed by this method.
Parameters
\eZ\Publish\SPI\Persistence\Content\UrlAlias[] $urlAliases
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 580 of file Handler.php.
    {
        foreach ( $urlAliases as $urlAlias )
        {
            if ( $urlAlias->isCustom )
            {
                list( $parentId, $textMD5 ) = explode( "-", $urlAlias->id );
                if ( !$this->gateway->removeCustomAlias( $parentId, $textMD5 ) )
                {
                    return false;
                }
            }
        }
        return true;
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::$configuration protected
Definition at line 29 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::$gateway protected
Definition at line 156 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::$languageHandler protected
Definition at line 177 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::$locationGateway protected
Definition at line 163 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::$mapper protected
Definition at line 170 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::$transformationProcessor protected
Definition at line 184 of file Handler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php