ezp-next: eZ\Publish\Core\REST\Client\Input\Parser\VersionInfo Class Reference
eZ\Publish\Core\REST\Client\Input\Parser\VersionInfo Class Reference
Public Member Functions
__construct (ParserTools $parserTools, ContentService $contentService)
parse (array $data, ParsingDispatcher $parsingDispatcher)
Protected Member Functions
convertVersionStatus ($statusString)
Protected Attributes
$parserTools
$contentService
Detailed Description
Parser for VersionInfo
Definition at line 22 of file VersionInfo.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Client\Input\Parser\VersionInfo::__construct (ParserTools $parserTools, ContentService $contentService)
Parameters
\eZ\Publish\Core\REST\Common\Input\ParserTools $parserTools
\eZ\Publish\Core\REST\Client\ContentService $contentService
Definition at line 40 of file VersionInfo.php.
References eZ\Publish\Core\REST\$parserTools.
    {
        $this->parserTools = $parserTools;
        $this->contentService = $contentService;
    }
Member Function Documentation
eZ\Publish\Core\REST\Client\Input\Parser\VersionInfo::convertVersionStatus ($statusString) protected
Converts the given $statusString to its constant representation
Parameters
string $statusString
Returns
int
Definition at line 84 of file VersionInfo.php.
References eZ\Publish\Core\REST\Client\Input\Parser\VersionInfo\convertVersionStatus(), eZ\Publish\API\Repository\Values\Content\VersionInfo\STATUS_ARCHIVED, eZ\Publish\API\Repository\Values\Content\VersionInfo\STATUS_DRAFT, and eZ\Publish\API\Repository\Values\Content\VersionInfo\STATUS_PUBLISHED.
    {
        switch ( strtoupper( $statusString ) )
        {
            case 'PUBLISHED':
                return Values\Content\VersionInfo::STATUS_PUBLISHED;
            case 'DRAFT':
                return Values\Content\VersionInfo::STATUS_DRAFT;
            case 'ARCHIVED':
                return Values\Content\VersionInfo::STATUS_ARCHIVED;
        }
        throw new \RuntimeException(
            sprintf( 'Unknown version status: "%s"', $statusString )
        );
    }
eZ\Publish\Core\REST\Client\Input\Parser\VersionInfo::parse (array $data, ParsingDispatcher $parsingDispatcher)
Parse input structure
Parameters
array $data
\eZ\Publish\Core\REST\Common\Input\ParsingDispatcher $parsingDispatcher
Todo:
Error handling
Returns
Definition at line 56 of file VersionInfo.php.
References eZ\Publish\Core\REST\Client\Input\Parser\VersionInfo\convertVersionStatus(), and eZ\Publish\Core\REST\Client\Input\Parser\VersionInfo\parse().
    {
        $contentInfoId = $this->parserTools->parseObjectElement( $data['Content'], $parsingDispatcher );
        return new Values\Content\VersionInfo(
            $this->contentService,
            array(
                'id' => $data['id'],
                'versionNo' => $data['versionNo'],
                'status' => $this->convertVersionStatus( $data['status'] ),
                'modificationDate' => new \DateTime( $data['modificationDate'] ),
                'creatorId' => $data['Creator']['_href'],
                'creationDate' => new \DateTime( $data['creationDate'] ),
                'initialLanguageCode' => $data['initialLanguageCode'],
                'languageCodes' => explode( ',', $data['languageCodes'] ),
                'names' => $this->parserTools->parseTranslatableList( $data['names'] ),
                'contentInfoId' => $contentInfoId,
            )
        );
    }
Member Data Documentation
eZ\Publish\Core\REST\Client\Input\Parser\VersionInfo::$contentService protected
Definition at line 34 of file VersionInfo.php.
eZ\Publish\Core\REST\Client\Input\Parser\VersionInfo::$parserTools protected
Definition at line 27 of file VersionInfo.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Client/Input/Parser/VersionInfo.php