ezp-next: eZ\Publish\Core\FieldType\EmailAddress\Type Class Reference
eZ\Publish\Core\FieldType\EmailAddress\Type Class Reference
Public Member Functions
validateValidatorConfiguration ($validatorConfiguration)
validate (FieldDefinition $fieldDefinition, $fieldValue)
getFieldTypeIdentifier ()
getName ($value)
getEmptyValue ()
fromHash ($hash)
toHash ($value)
isSearchable ()
Public Member Functions inherited from eZ\Publish\Core\FieldType\FieldType
getSettingsSchema ()
getValidatorConfigurationSchema ()
validateFieldSettings ($fieldSettings)
toPersistenceValue ($value)
fromPersistenceValue (FieldValue $fieldValue)
isEmptyValue ($value)
acceptValue ($inputValue)
fieldSettingsToHash ($fieldSettings)
fieldSettingsFromHash ($fieldSettingsHash)
validatorConfigurationToHash ($validatorConfiguration)
validatorConfigurationFromHash ($validatorConfigurationHash)
Protected Member Functions
internalAcceptValue ($inputValue)
getSortInfo ($value)
Protected Attributes
$validatorConfigurationSchema
Protected Attributes inherited from eZ\Publish\Core\FieldType\FieldType
$settingsSchema = array()
$validatorConfigurationSchema = array()
Detailed Description
The EMailAddress field type.
This field type represents an email address.
Definition at line 23 of file Type.php.
Member Function Documentation
eZ\Publish\Core\FieldType\EmailAddress\Type::fromHash ($hash)
Converts an $hash to the Value defined by the field type
Parameters
mixed $hash
Returns
$value
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 184 of file Type.php.
    {
        if ( $hash === null )
        {
            return null;
        }
        return new Value( $hash );
    }
eZ\Publish\Core\FieldType\EmailAddress\Type::getEmptyValue ()
Returns the fallback default value of field type when no such default value is provided in the field definition in content types.
Returns
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 122 of file Type.php.
    {
        return new Value;
    }
eZ\Publish\Core\FieldType\EmailAddress\Type::getFieldTypeIdentifier ()
Returns the field type identifier for this field type
Returns
string
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 90 of file Type.php.
    {
        return "ezemail";
    }
eZ\Publish\Core\FieldType\EmailAddress\Type::getName ($value)
Returns the name of the given field value.
It will be used to generate content name and url alias if current field is designated to be used in the content name/urlAlias pattern.
Parameters
mixed $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 105 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\acceptValue().
    {
        if ( $value === null )
        {
            return '';
        }
        $value = $this->acceptValue( $value );
        return (string)$value->email;
    }
eZ\Publish\Core\FieldType\EmailAddress\Type::getSortInfo ($value) protected
Returns information for FieldValue->$sortKey relevant to the field type.
Todo:
String normalization should occur here.
Returns
array
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 168 of file Type.php.
    {
        if ( $value === null )
        {
            return '';
        }
        return $value->email;
    }
eZ\Publish\Core\FieldType\EmailAddress\Type::internalAcceptValue ($inputValue) protected
Implements the core of {
See Also
acceptValue()}.
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 134 of file Type.php.
    {
        if ( is_string( $inputValue ) )
        {
            $inputValue = new Value( $inputValue );
        }
        else if ( !$inputValue instanceof Value )
        {
            throw new InvalidArgumentType(
                '$inputValue',
                'eZ\\Publish\\Core\\FieldType\\EmailAddress\\Value',
                $inputValue
            );
        }
        if ( !is_string( $inputValue->email ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->text',
                'string',
                $inputValue->email
            );
        }
        return $inputValue;
    }
eZ\Publish\Core\FieldType\EmailAddress\Type::isSearchable ()
Returns whether the field type is searchable
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 214 of file Type.php.
    {
        return true;
    }
eZ\Publish\Core\FieldType\EmailAddress\Type::toHash ($value)
Converts a $Value to a hash
Parameters
\eZ\Publish\Core\FieldType\EmailAddress\Value $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 200 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\isEmptyValue().
    {
        if ( $this->isEmptyValue( $value ) )
        {
            return null;
        }
        return $value->email;
    }
eZ\Publish\Core\FieldType\EmailAddress\Type::validate (FieldDefinition $fieldDefinition, $fieldValue)
Validates a field based on the validators in the field definition
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException
Parameters
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition The field definition of the field
\eZ\Publish\Core\FieldType\Value $fieldValue The field for which an action is performed
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 70 of file Type.php.
References eZ\Publish\API\Repository\Values\ContentType\FieldDefinition\getValidatorConfiguration().
    {
        $validatorConfiguration = $fieldDefinition->getValidatorConfiguration();
        $constraints = isset($validatorConfiguration['EmailAddressValidator']) ?
            $validatorConfiguration['EmailAddressValidator'] :
            array();
        $validator = new EmailAddressValidator();
        $validator->initializeWithConstraints( $constraints );
        if ( !$validator->validate( $fieldValue ) )
            return $validator->getMessage();
        return array();
    }
eZ\Publish\Core\FieldType\EmailAddress\Type::validateValidatorConfiguration ($validatorConfiguration)
Validates the validatorConfiguration of a FieldDefinitionCreateStruct or FieldDefinitionUpdateStruct
Parameters
mixed $validatorConfiguration
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 36 of file Type.php.
    {
        $validationErrors = array();
        $validator = new EmailAddressValidator();
        foreach ( (array)$validatorConfiguration as $validatorIdentifier => $constraints )
        {
            if ( $validatorIdentifier !== 'EmailAddressValidator' )
            {
                $validationErrors[] = new ValidationError(
                    "Validator '%validator%' is unknown",
                    null,
                    array(
                        "validator" => $validatorIdentifier
                    )
                );
                continue;
            }
            $validationErrors += $validator->validateConstraints( $constraints );
        }
        return $validationErrors;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\EmailAddress\Type::$validatorConfigurationSchema protected
Initial value:
 array(
        'EmailAddressValidator' => array()
    )
Definition at line 25 of file Type.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/EmailAddress/Type.php