ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler Class Reference
Public Member Functions
__construct (Gateway $contentGateway, Mapper $mapper, StorageHandler $storageHandler, LanguageHandler $languageHandler, FieldTypeRegistry $fieldTypeRegistry)
createNewFields (Content $content)
createExistingFieldsInNewVersion (Content $content)
loadExternalFieldData (Content $content)
updateFields (Content $content, UpdateStruct $updateStruct)
deleteFields ($contentId, VersionInfo $versionInfo)
Public Attributes
$typeHandler
Protected Member Functions
getEmptyField (FieldDefinition $fieldDefinition, $languageCode)
createNewField (Field $field, Content $content)
copyFields (array $fields, Content $content)
copyField (Field $originalField, $languageCode, Content $content)
updateField (Field $field, Content $content)
createExistingFieldInNewVersion (Field $originalField, Content $content, $newLanguageCode=null)
getLanguageCodes (array $languageIds)
getFieldMap (array $fields, &$languageCodes=null)
Protected Attributes
$contentGateway
$languageHandler
$mapper
$storageHandler
$fieldTypeRegistry
$fieldTypes
Detailed Description
Field Handler.
Definition at line 25 of file FieldHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::__construct (Gateway $contentGateway, Mapper $mapper, StorageHandler $storageHandler, LanguageHandler $languageHandler, FieldTypeRegistry $fieldTypeRegistry)
Creates a new Field Handler
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\Gateway $contentGateway
\eZ\Publish\Core\Persistence\Legacy\Content\Mapper $mapper
\eZ\Publish\Core\Persistence\Legacy\Content\StorageHandler $storageHandler
\eZ\Publish\SPI\Persistence\Content\Language\Handler $languageHandler
\eZ\Publish\Core\Persistence\FieldTypeRegistry $fieldTypeRegistry
Definition at line 83 of file FieldHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\$contentGateway, eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\$fieldTypeRegistry, eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\$languageHandler, eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\$mapper, and eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\$storageHandler.
    {
        $this->contentGateway = $contentGateway;
        $this->mapper = $mapper;
        $this->storageHandler = $storageHandler;
        $this->languageHandler = $languageHandler;
        $this->fieldTypeRegistry = $fieldTypeRegistry;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::copyField (Field $originalField, $languageCode, Content $content) protected
Copies existing field to new field for given $languageCode.
Used by self::createNewFields() and self::updateFields()
Parameters
\eZ\Publish\SPI\Persistence\Content\Field $originalField
string $languageCode
\eZ\Publish\SPI\Persistence\Content $content
Returns
void
Definition at line 267 of file FieldHandler.php.
    {
        $originalField->versionNo = $content->versionInfo->versionNo;
        $field = clone $originalField;
        $field->languageCode = $languageCode;
        $field->id = $this->contentGateway->insertNewField(
            $content,
            $field,
            $this->mapper->convertToStorageValue( $field )
        );
        // If the storage handler returns true, it means that $field value has been modified
        // So we need to update it in order to store those modifications
        // Field converter is called once again via the Mapper
        if ( $this->storageHandler->copyFieldData( $content->versionInfo, $field, $originalField ) === true )
        {
            $this->contentGateway->updateField(
                $field,
                $this->mapper->convertToStorageValue( $field )
            );
        }
        $content->fields[] = $field;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::copyFields (array $fields, Content $content) protected
Parameters
array $fields
\eZ\Publish\SPI\Persistence\Content $content
Returns
void
Definition at line 245 of file FieldHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\copyField().
    {
        foreach ( $fields as $languageFields )
        {
            foreach ( $languageFields as $languageCode => $field )
            {
                $this->copyField( $field, $languageCode, $content );
            }
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::createExistingFieldInNewVersion (Field $originalField, Content $content, $newLanguageCode = null) protected
Creates an existing field in a new version, no new ID is generated.
If $newLanguageCode is set field will be created in it. This is used for creating non-translatable fields from field in main language.
External data is being copied here as some FieldTypes require original field external data. By default copying falls back to storing, it is upon external storage implementation to override the behaviour as needed.
Parameters
Field $originalField
Content $content
string | null $newLanguageCode
Returns
Definition at line 338 of file FieldHandler.php.
    {
        $field = clone $originalField;
        if ( $newLanguageCode !== null )
        {
            $field->languageCode = $newLanguageCode;
        }
        $field->versionNo = $content->versionInfo->versionNo;
        $this->contentGateway->insertExistingField(
            $content,
            $field,
            $this->mapper->convertToStorageValue( $field )
        );
        // If the storage handler returns true, it means that $field value has been modified
        // So we need to update it in order to store those modifications
        // Field converter is called once again via the Mapper
        if ( $this->storageHandler->copyFieldData( $content->versionInfo, $field, $originalField ) === true )
        {
            $this->contentGateway->updateField(
                $field,
                $this->mapper->convertToStorageValue( $field )
            );
        }
        return $field;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::createExistingFieldsInNewVersion (Content $content)
Creates existing fields in a new version for $content
Parameters
\eZ\Publish\SPI\Persistence\Content $content
Returns
void
Definition at line 173 of file FieldHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\createExistingFieldInNewVersion(), eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\getFieldMap(), and eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\getLanguageCodes().
    {
        $languageCodes = $this->getLanguageCodes( $content->versionInfo->languageIds );
        $contentFieldMap = $this->getFieldMap( $content->fields );
        $content->fields = array();
        $contentType = $this->typeHandler->load( $content->versionInfo->contentInfo->contentTypeId );
        $mainLanguageCode = $content->versionInfo->contentInfo->mainLanguageCode;
        foreach ( $contentType->fieldDefinitions as $fieldDefinition )
        {
            foreach ( array_keys( $languageCodes ) as $languageCode )
            {
                if ( !$fieldDefinition->isTranslatable && $languageCode != $mainLanguageCode )
                {
                    $createInNewLanguageCode = $languageCode;
                    $field = $contentFieldMap[$fieldDefinition->id][$mainLanguageCode];
                }
                else
                {
                    $createInNewLanguageCode = null;
                    $field = $contentFieldMap[$fieldDefinition->id][$languageCode];
                }
                $content->fields[] = $this->createExistingFieldInNewVersion(
                    $field,
                    $content,
                    $createInNewLanguageCode
                );
            }
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::createNewField (Field $field, Content $content) protected
Creates a new field in the database
Used by self::createNewFields() and self::updateFields()
Parameters
\eZ\Publish\SPI\Persistence\Content\Field $field
\eZ\Publish\SPI\Persistence\Content $content
Returns
void
Definition at line 215 of file FieldHandler.php.
    {
        $field->versionNo = $content->versionInfo->versionNo;
        $field->id = $this->contentGateway->insertNewField(
            $content,
            $field,
            $this->mapper->convertToStorageValue( $field )
        );
        // If the storage handler returns true, it means that $field value has been modified
        // So we need to update it in order to store those modifications
        // Field converter is called once again via the Mapper
        if ( $this->storageHandler->storeFieldData( $content->versionInfo, $field ) === true )
        {
            $this->contentGateway->updateField(
                $field,
                $this->mapper->convertToStorageValue( $field )
            );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::createNewFields (Content $content)
Creates new fields in the database from $content
Parameters
\eZ\Publish\SPI\Persistence\Content $content
Returns
void
Definition at line 104 of file FieldHandler.php.
References eZ\Publish\SPI\Persistence\Content\$fields, eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\copyFields(), eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\createNewField(), eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\getEmptyField(), and eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\getFieldMap().
    {
        $fieldsToCopy = array();
        $languageCodes = array();
        $fields = $this->getFieldMap( $content->fields, $languageCodes );
        $contentType = $this->typeHandler->load( $content->versionInfo->contentInfo->contentTypeId );
        foreach ( $contentType->fieldDefinitions as $fieldDefinition )
        {
            foreach ( array_keys( $languageCodes ) as $languageCode )
            {
                // Create fields passed from struct
                if ( isset( $fields[$fieldDefinition->id][$languageCode] ) )
                {
                    $field = $fields[$fieldDefinition->id][$languageCode];
                    $this->createNewField( $field, $content );
                }
                // Copy only for untranslatable field and when field in main language exists
                // Only register here, process later as field copied should be already stored
                else if ( !$fieldDefinition->isTranslatable
                    && isset( $fields[$fieldDefinition->id][$content->versionInfo->contentInfo->mainLanguageCode] )
                )
                {
                    $fieldsToCopy[$fieldDefinition->id][$languageCode] =
                        $fields[$fieldDefinition->id][$content->versionInfo->contentInfo->mainLanguageCode];
                }
                // In all other cases create empty field
                else
                {
                    $field = $this->getEmptyField( $fieldDefinition, $languageCode );
                    $content->fields[] = $field;
                    $this->createNewField( $field, $content );
                }
            }
        }
        $this->copyFields( $fieldsToCopy, $content );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::deleteFields ($contentId, VersionInfo $versionInfo)
Deletes the fields for $contentId in $versionInfo from the database
Parameters
int $contentId
\eZ\Publish\SPI\Persistence\Content\VersionInfo $versionInfo
Returns
void
Definition at line 499 of file FieldHandler.php.
    {
        foreach ( $this->contentGateway->getFieldIdsByType( $contentId, $versionInfo->versionNo )
            as $fieldType => $ids )
        {
            $this->storageHandler->deleteFieldData( $fieldType, $versionInfo, $ids );
        }
        $this->contentGateway->deleteFields( $contentId, $versionInfo->versionNo );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::getEmptyField (FieldDefinition $fieldDefinition, $languageCode) protected
Returns empty Field object for given field definition and language code.
Uses FieldType to create empty field value.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
string $languageCode
Returns
Definition at line 153 of file FieldHandler.php.
    {
        $fieldType = $this->fieldTypeRegistry->getFieldType( $fieldDefinition->fieldType );
        return new Field(
            array(
                "fieldDefinitionId" => $fieldDefinition->id,
                "type" => $fieldDefinition->fieldType,
                "value" => $fieldType->getEmptyValue(),
                "languageCode" => $languageCode
            )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::getFieldMap (array $fields, & $languageCodes = null) protected
Returns given $fields structured in hash array with field definition ids and language codes as keys.
Parameters
\eZ\Publish\SPI\Persistence\Content\Field[] $fields
array $languageCodes
Returns
[][]
Definition at line 476 of file FieldHandler.php.
    {
        $fieldMap = array();
        foreach ( $fields as $field )
        {
            if ( isset( $languageCodes ) )
            {
                $languageCodes[$field->languageCode] = true;
            }
            $fieldMap[$field->fieldDefinitionId][$field->languageCode] = $field;
        }
        return $fieldMap;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::getLanguageCodes (array $languageIds) protected
For given $languageIds returns array with language codes as keys.
Parameters
array $languageIds
Returns
array
Definition at line 457 of file FieldHandler.php.
    {
        $languageCodes = array();
        foreach ( $languageIds as $languageId )
        {
            $languageCodes[$this->languageHandler->load( $languageId )->languageCode] = true;
        }
        return $languageCodes;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::loadExternalFieldData (Content $content)
Performs external loads for the fields in $content
Parameters
Content $content
Returns
void
Definition at line 374 of file FieldHandler.php.
    {
        foreach ( $content->fields as $field )
        {
            $this->storageHandler->getFieldData( $content->versionInfo, $field );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::updateField (Field $field, Content $content) protected
Updates an existing field in the database.
Used by self::createNewFields() and self::updateFields()
Parameters
\eZ\Publish\SPI\Persistence\Content\Field $field
\eZ\Publish\SPI\Persistence\Content $content
Returns
void
Definition at line 303 of file FieldHandler.php.
    {
        $this->contentGateway->updateField(
            $field,
            $this->mapper->convertToStorageValue( $field )
        );
        // If the storage handler returns true, it means that $field value has been modified
        // So we need to update it in order to store those modifications
        // Field converter is called once again via the Mapper
        if ( $this->storageHandler->storeFieldData( $content->versionInfo, $field ) === true )
        {
            $this->contentGateway->updateField(
                $field,
                $this->mapper->convertToStorageValue( $field )
            );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::updateFields (Content $content, UpdateStruct $updateStruct)
Updates the fields in for content identified by $contentId and $versionNo in the database in respect to $updateStruct
Parameters
\eZ\Publish\SPI\Persistence\Content $content
\eZ\Publish\SPI\Persistence\Content\UpdateStruct $updateStruct
Returns
void
Definition at line 390 of file FieldHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\copyFields(), eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\createNewField(), eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\getEmptyField(), eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\getFieldMap(), eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\getLanguageCodes(), and eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler\updateField().
    {
        $fieldsToCopy = array();
        $mainLanguageCode = $content->versionInfo->contentInfo->mainLanguageCode;
        $languageCodes = $existingLanguageCodes = $this->getLanguageCodes( $content->versionInfo->languageIds );
        $contentFieldMap = $this->getFieldMap( $content->fields );
        $updateFieldMap = $this->getFieldMap( $updateStruct->fields, $languageCodes );
        $contentType = $this->typeHandler->load( $content->versionInfo->contentInfo->contentTypeId );
        foreach ( $contentType->fieldDefinitions as $fieldDefinition )
        {
            foreach ( array_keys( $languageCodes ) as $languageCode )
            {
                if ( isset( $updateFieldMap[$fieldDefinition->id][$languageCode] ) )
                {
                    $field = clone $updateFieldMap[$fieldDefinition->id][$languageCode];
                    $field->versionNo = $content->versionInfo->versionNo;
                    if ( isset( $field->id ) )
                    {
                        $this->updateField( $field, $content );
                    }
                    else
                    {
                        $this->createNewField( $field, $content );
                    }
                }
                // If field is not set for new language
                else if ( !isset( $existingLanguageCodes[$languageCode] ) )
                {
                    if ( $fieldDefinition->isTranslatable )
                    {
                        // Use empty value for translatable field
                        $field = $this->getEmptyField( $fieldDefinition, $languageCode );
                        $this->createNewField( $field, $content );
                    }
                    else
                    {
                        // Use value from main language code for untranslatable field
                        $fieldsToCopy[$fieldDefinition->id][$languageCode] =
                            isset( $updateFieldMap[$fieldDefinition->id][$mainLanguageCode] )
                                ? $updateFieldMap[$fieldDefinition->id][$mainLanguageCode]
                                : $contentFieldMap[$fieldDefinition->id][$mainLanguageCode];
                    }
                }
                // If field is not set for existing language and is untranslatable and main language is updated,
                // also update copied field data
                else if ( !$fieldDefinition->isTranslatable
                    && isset( $updateFieldMap[$fieldDefinition->id][$mainLanguageCode] )
                )
                {
                    // Use value from main language code
                    $fieldsToCopy[$fieldDefinition->id][$languageCode] =
                        $updateFieldMap[$fieldDefinition->id][$mainLanguageCode];
                }
            }
        }
        $this->copyFields( $fieldsToCopy, $content );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::$contentGateway protected
Definition at line 32 of file FieldHandler.php.
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::$fieldTypeRegistry protected
Definition at line 65 of file FieldHandler.php.
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::$fieldTypes protected
Definition at line 72 of file FieldHandler.php.
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::$languageHandler protected
Definition at line 44 of file FieldHandler.php.
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::$mapper protected
Definition at line 51 of file FieldHandler.php.
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::$storageHandler protected
Definition at line 58 of file FieldHandler.php.
eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler::$typeHandler
Definition at line 39 of file FieldHandler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/FieldHandler.php