ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText Class Reference
Public Member Functions
__construct (EzcDbHandler $dbHandler, TransformationProcessor $processor, array $configuration=array())
accept (Criterion $criterion)
handle (CriteriaConverter $converter, ezcQuerySelect $query, Criterion $criterion)
Public Member Functions inherited from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler
__construct (EzcDbHandler $dbHandler)
Protected Member Functions
tokenizeString ($string)
getWordExpression (ezcQuerySelect $query, $token)
getWordIdSubquery ($query, $string)
Protected Attributes
$configuration
$processor
Protected Attributes inherited from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler
$comparatorMap
$dbHandler
Detailed Description
Full text criterion handler
Definition at line 22 of file FullText.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText::__construct (EzcDbHandler $dbHandler, TransformationProcessor $processor, array $configuration = array())
Construct from full text search configuration
Parameters
array $configuration
Returns
void
Definition at line 82 of file FullText.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText\$configuration, and eZ\Publish\API\Repository\Values\ValueObject\__construct().
    {
        parent::__construct( $dbHandler );
        $this->configuration = $configuration + $this->configuration;
        $this->processor = $processor;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText::accept (Criterion $criterion)
Check if this criterion handler accepts to handle the given criterion.
Parameters
\eZ\Publish\API\Repository\Values\Content\Query\Criterion$criterion
Returns
boolean
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler.
Definition at line 97 of file FullText.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText\accept().
    {
        return $criterion instanceof Criterion\FullText;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText::getWordExpression (ezcQuerySelect $query, $token) protected
Get single word query expression
Depending on the configuration of the full text search criterion converter wildcards are either transformed into the respective LIKE queries, or everything is just compared using equal.
Parameters
\ezcQuerySelect $query
string $token
Returns
Definition at line 131 of file FullText.php.
    {
        if ( $this->configuration['enableWildcards'] &&
             $token[0] === '*' )
        {
            return $query->expr->like(
                $this->dbHandler->quoteColumn( 'word' ),
                $query->bindValue( '%' . substr( $token, 1 ) )
            );
        }
        if ( $this->configuration['enableWildcards'] &&
             $token[strlen( $token ) - 1] === '*' )
        {
            return $query->expr->like(
                $this->dbHandler->quoteColumn( 'word' ),
                $query->bindValue( substr( $token, 0, -1 ) . '%' )
            );
        }
        return $query->expr->eq(
            $this->dbHandler->quoteColumn( 'word' ),
            $query->bindValue( $token )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText::getWordIdSubquery ($query, $string) protected
Get subquery to select relevant word IDs
Parameters
string $string
Returns
Definition at line 164 of file FullText.php.
    {
        $subQuery = $query->subSelect();
        $tokens = $this->tokenizeString(
            $this->processor->transform( $string, $this->configuration['commands'] )
        );
        $wordExpressions = array();
        foreach ( $tokens as $token )
        {
            $wordExpressions[] = $this->getWordExpression( $subQuery, $token );
        }
        $subQuery
            ->select( $this->dbHandler->quoteColumn( 'id' ) )
            ->from( $this->dbHandler->quoteTable( 'ezsearch_word' ) )
            ->where(
                $subQuery->expr->lAnd(
                    $subQuery->expr->lOr( $wordExpressions ),
                    $subQuery->expr->lt(
                        $this->dbHandler->quoteColumn( 'object_count' ),
                        $subQuery->bindValue( $this->configuration['searchThresholdValue'] )
                    )
                )
            );
        return $subQuery;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText::handle (CriteriaConverter $converter, ezcQuerySelect $query, Criterion $criterion)
Generate query expression for a Criterion this handler accepts
accept() must be called before calling this method.
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriteriaConverter$converter
\ezcQuerySelect $query
\eZ\Publish\API\Repository\Values\Content\Query\Criterion$criterion
Returns
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler.
Definition at line 202 of file FullText.php.
    {
        $subSelect = $query->subSelect();
        $subSelect
            ->select(
                $this->dbHandler->quoteColumn( 'contentobject_id' )
            )->from(
                $this->dbHandler->quoteTable( 'ezsearch_object_word_link' )
            )->where(
                $query->expr->in(
                    $this->dbHandler->quoteColumn( 'word_id' ),
                    $this->getWordIdSubquery( $subSelect, $criterion->value )
                )
            );
        return $query->expr->in(
            $this->dbHandler->quoteColumn( 'id', 'ezcontentobject' ),
            $subSelect
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText::tokenizeString ($string) protected
Tokenize String
Parameters
string $string
Returns
array
Definition at line 109 of file FullText.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText\tokenizeString().
    {
        return array_filter(
            array_map(
                'trim',
                preg_split( '(\\p{Z})u', strtr( $string, '\'"', '' ) )
            )
        );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText::$configuration protected
Definition at line 29 of file FullText.php.
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\CriterionHandler\FullText::$processor protected
Definition at line 73 of file FullText.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Search/Gateway/CriterionHandler/FullText.php