ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase Class Reference
Public Member Functions
__construct (EzcDbHandler $dbHandler, MaskGenerator $maskGenerator)
loadObjectStateData ($stateId)
loadObjectStateDataByIdentifier ($identifier, $groupId)
loadObjectStateListData ($groupId)
loadObjectStateGroupData ($groupId)
loadObjectStateGroupDataByIdentifier ($identifier)
loadObjectStateGroupListData ($offset, $limit)
insertObjectState (ObjectState $objectState, $groupId)
updateObjectState (ObjectState $objectState)
deleteObjectState ($stateId)
updateObjectStateLinks ($oldStateId, $newStateId)
deleteObjectStateLinks ($stateId)
insertObjectStateGroup (Group $objectStateGroup)
updateObjectStateGroup (Group $objectStateGroup)
deleteObjectStateGroup ($groupId)
setContentState ($contentId, $groupId, $stateId)
loadObjectStateDataForContent ($contentId, $stateGroupId)
getContentCount ($stateId)
updateObjectStatePriority ($stateId, $priority)
Protected Member Functions
createObjectStateFindQuery ()
createObjectStateGroupFindQuery ()
insertObjectStateTranslations (ObjectState $objectState)
deleteObjectStateTranslations ($stateId)
insertObjectStateGroupTranslations (Group $objectStateGroup)
deleteObjectStateGroupTranslations ($groupId)
generateLanguageMask (array $languageCodes)
Protected Attributes
$dbHandler
$maskGenerator
Detailed Description
ObjectState ezcDatabase Gateway
Definition at line 21 of file EzcDatabase.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::__construct (EzcDbHandler $dbHandler, MaskGenerator $maskGenerator)
Creates a new EzcDatabase ObjectState Gateway
Parameters
\eZ\Publish\Core\Persistence\Legacy\EzcDbHandler $dbHandler
\eZ\Publish\Core\Persistence\Legacy\Content\Language\MaskGenerator $maskGenerator
Definition at line 43 of file EzcDatabase.php.
    {
        $this->dbHandler = $dbHandler;
        $this->maskGenerator = $maskGenerator;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::createObjectStateFindQuery () protected
Creates a generalized query for fetching object state(s)
Returns
Definition at line 650 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\createObjectStateFindQuery().
    {
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            // Object state
            $this->dbHandler->aliasedColumn( $query, 'default_language_id', 'ezcobj_state' ),
            $this->dbHandler->aliasedColumn( $query, 'group_id', 'ezcobj_state' ),
            $this->dbHandler->aliasedColumn( $query, 'id', 'ezcobj_state' ),
            $this->dbHandler->aliasedColumn( $query, 'identifier', 'ezcobj_state' ),
            $this->dbHandler->aliasedColumn( $query, 'language_mask', 'ezcobj_state' ),
            $this->dbHandler->aliasedColumn( $query, 'priority', 'ezcobj_state' ),
            // Object state language
            $this->dbHandler->aliasedColumn( $query, 'description', 'ezcobj_state_language' ),
            $this->dbHandler->aliasedColumn( $query, 'language_id', 'ezcobj_state_language' ),
            $this->dbHandler->aliasedColumn( $query, 'name', 'ezcobj_state_language' )
        )->from(
            $this->dbHandler->quoteTable( 'ezcobj_state' )
        )->innerJoin(
            $this->dbHandler->quoteTable( 'ezcobj_state_language' ),
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id', 'ezcobj_state' ),
                $this->dbHandler->quoteColumn( 'contentobject_state_id', 'ezcobj_state_language' )
            )
        );
        return $query;
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::createObjectStateGroupFindQuery () protected
Creates a generalized query for fetching object state group(s)
Returns
Definition at line 683 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\createObjectStateGroupFindQuery().
    {
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            // Object state group
            $this->dbHandler->aliasedColumn( $query, 'default_language_id', 'ezcobj_state_group' ),
            $this->dbHandler->aliasedColumn( $query, 'id', 'ezcobj_state_group' ),
            $this->dbHandler->aliasedColumn( $query, 'identifier', 'ezcobj_state_group' ),
            $this->dbHandler->aliasedColumn( $query, 'language_mask', 'ezcobj_state_group' ),
            // Object state group language
            $this->dbHandler->aliasedColumn( $query, 'description', 'ezcobj_state_group_language' ),
            $this->dbHandler->aliasedColumn( $query, 'language_id', 'ezcobj_state_group_language' ),
            $this->dbHandler->aliasedColumn( $query, 'real_language_id', 'ezcobj_state_group_language' ),
            $this->dbHandler->aliasedColumn( $query, 'name', 'ezcobj_state_group_language' )
        )->from(
            $this->dbHandler->quoteTable( 'ezcobj_state_group' )
        )->innerJoin(
            $this->dbHandler->quoteTable( 'ezcobj_state_group_language' ),
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id', 'ezcobj_state_group' ),
                $this->dbHandler->quoteColumn( 'contentobject_state_group_id', 'ezcobj_state_group_language' )
            )
        );
        return $query;
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::deleteObjectState ($stateId)
Deletes object state identified by $stateId
Parameters
int $stateId
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 318 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\deleteObjectStateTranslations().
    {
        $this->deleteObjectStateTranslations( $stateId );
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcobj_state' )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $query->bindValue( $stateId, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::deleteObjectStateGroup ($groupId)
Deletes the object state group identified by $groupId
Parameters
mixed $groupId
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 458 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\deleteObjectStateGroupTranslations().
    {
        $this->deleteObjectStateGroupTranslations( $groupId );
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcobj_state_group' )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $query->bindValue( $groupId, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::deleteObjectStateGroupTranslations ($groupId) protected
Deletes all translations of the $groupId state group
Parameters
mixed $groupId
Definition at line 807 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\deleteObjectStateGroupTranslations().
    {
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcobj_state_group_language' )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'contentobject_state_group_id' ),
                $query->bindValue( $groupId, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::deleteObjectStateLinks ($stateId)
Deletes object state links identified by $stateId
Parameters
int $stateId
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 364 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcobj_state_link' )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'contentobject_state_id' ),
                $query->bindValue( $stateId, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::deleteObjectStateTranslations ($stateId) protected
Deletes all translations of the $stateId state
Parameters
mixed $stateId
Definition at line 750 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\deleteObjectStateTranslations().
    {
        $query = $this->dbHandler->createDeleteQuery();
        $query->deleteFrom(
            $this->dbHandler->quoteTable( 'ezcobj_state_language' )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'contentobject_state_id' ),
                $query->bindValue( $stateId, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::generateLanguageMask (array $languageCodes) protected
Generates language mask from provided language codes Also sets always available bit
Parameters
array $languageCodes
Returns
int
Definition at line 830 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\generateLanguageMask().
    {
        $maskLanguageCodes = array();
        foreach ( $languageCodes as $languageCode )
        {
            $maskLanguageCodes[$languageCode] = 1;
        }
        $maskLanguageCodes['always-available'] = 1;
        return $this->maskGenerator->generateLanguageMask( $maskLanguageCodes );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::getContentCount ($stateId)
Returns the number of objects which are in this state
Parameters
mixed $stateId
Returns
int
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 599 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->alias( $query->expr->count( '*' ), 'count' )
        )->from(
            $this->dbHandler->quoteTable( 'ezcobj_state_link' )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'contentobject_state_id' ),
                $query->bindValue( $stateId, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        $count = $statement->fetchColumn();
        return $count !== null ? (int)$count : 0;
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::insertObjectState (ObjectState $objectState, $groupId)
Inserts a new object state into database
Parameters
\eZ\Publish\SPI\Persistence\Content\ObjectState $objectState
int $groupId
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 208 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\generateLanguageMask(), and eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\insertObjectStateTranslations().
    {
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $query->expr->max( $this->dbHandler->quoteColumn( 'priority' ) )
        )->from(
            $this->dbHandler->quoteTable( 'ezcobj_state' )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'group_id' ),
                $query->bindValue( $groupId, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        $maxPriority = $statement->fetchColumn();
        $objectState->priority = $maxPriority === null ? 0 : (int)$maxPriority + 1;
        $objectState->groupId = (int)$groupId;
        $query = $this->dbHandler->createInsertQuery();
        $query->insertInto(
            $this->dbHandler->quoteTable( 'ezcobj_state' )
        )->set(
            $this->dbHandler->quoteColumn( 'id' ),
            $this->dbHandler->getAutoIncrementValue( 'ezcobj_state', 'id' )
        )->set(
            $this->dbHandler->quoteColumn( 'group_id' ),
            $query->bindValue( $objectState->groupId, null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'default_language_id' ),
            $query->bindValue(
                $this->maskGenerator->generateLanguageIndicator( $objectState->defaultLanguage, false ),
                null, \PDO::PARAM_INT
            )
        )->set(
            $this->dbHandler->quoteColumn( 'identifier' ),
            $query->bindValue( $objectState->identifier )
        )->set(
            $this->dbHandler->quoteColumn( 'language_mask' ),
            $query->bindValue( $this->generateLanguageMask( $objectState->languageCodes ), null, \PDO::PARAM_INT )
        )->set(
            $this->dbHandler->quoteColumn( 'priority' ),
            $query->bindValue( $objectState->priority, null, \PDO::PARAM_INT )
        );
        $query->prepare()->execute();
        $objectState->id = (int)$this->dbHandler->lastInsertId(
            $this->dbHandler->getSequenceName( 'ezcobj_state', 'id' )
        );
        $this->insertObjectStateTranslations( $objectState );
        // If this is a first state in group, assign it to all content objects
        if ( $maxPriority === null )
        {
            // @todo Hm... How do we perform this with query object?
            $this->dbHandler->query(
                "INSERT INTO ezcobj_state_link (contentobject_id, contentobject_state_id)
                SELECT id, {$objectState->id} FROM ezcontentobject"
            );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::insertObjectStateGroup (Group $objectStateGroup)
Inserts a new object state group into database
Parameters
\eZ\Publish\SPI\Persistence\Content\ObjectState\Group $objectStateGroup
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 384 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\generateLanguageMask(), and eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\insertObjectStateGroupTranslations().
    {
        $query = $this->dbHandler->createInsertQuery();
        $query->insertInto(
            $this->dbHandler->quoteTable( 'ezcobj_state_group' )
        )->set(
            $this->dbHandler->quoteColumn( 'id' ),
            $this->dbHandler->getAutoIncrementValue( 'ezcobj_state_group', 'id' )
        )->set(
            $this->dbHandler->quoteColumn( 'default_language_id' ),
            $query->bindValue(
                $this->maskGenerator->generateLanguageIndicator( $objectStateGroup->defaultLanguage, false ),
                null, \PDO::PARAM_INT
            )
        )->set(
            $this->dbHandler->quoteColumn( 'identifier' ),
            $query->bindValue( $objectStateGroup->identifier )
        )->set(
            $this->dbHandler->quoteColumn( 'language_mask' ),
            $query->bindValue( $this->generateLanguageMask( $objectStateGroup->languageCodes ), null, \PDO::PARAM_INT )
        );
        $query->prepare()->execute();
        $objectStateGroup->id = (int)$this->dbHandler->lastInsertId(
            $this->dbHandler->getSequenceName( 'ezcobj_state_group', 'id' )
        );
        $this->insertObjectStateGroupTranslations( $objectStateGroup );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::insertObjectStateGroupTranslations (Group $objectStateGroup) protected
Inserts object state group translations into database
Parameters
\eZ\Publish\SPI\Persistence\Content\ObjectState\Group $objectStateGroup
Definition at line 770 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\insertObjectStateGroupTranslations().
    {
        foreach ( $objectStateGroup->languageCodes as $languageCode )
        {
            $languageId = $this->maskGenerator->generateLanguageIndicator(
                $languageCode, $languageCode === $objectStateGroup->defaultLanguage
            );
            $query = $this->dbHandler->createInsertQuery();
            $query->insertInto(
                $this->dbHandler->quoteTable( 'ezcobj_state_group_language' )
            )->set(
                $this->dbHandler->quoteColumn( 'contentobject_state_group_id' ),
                $query->bindValue( $objectStateGroup->id, null, \PDO::PARAM_INT )
            )->set(
                $this->dbHandler->quoteColumn( 'description' ),
                $query->bindValue( $objectStateGroup->description[$languageCode] )
            )->set(
                $this->dbHandler->quoteColumn( 'name' ),
                $query->bindValue( $objectStateGroup->name[$languageCode] )
            )->set(
                $this->dbHandler->quoteColumn( 'language_id' ),
                $query->bindValue( $languageId, null, \PDO::PARAM_INT )
            )->set(
                $this->dbHandler->quoteColumn( 'real_language_id' ),
                $query->bindValue( $languageId & ~1, null, \PDO::PARAM_INT )
            );
            $query->prepare()->execute();
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::insertObjectStateTranslations (ObjectState $objectState) protected
Inserts object state group translations into database
Parameters
\eZ\Publish\SPI\Persistence\Content\ObjectState $objectState
Definition at line 715 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\insertObjectStateTranslations().
    {
        foreach ( $objectState->languageCodes as $languageCode )
        {
            $query = $this->dbHandler->createInsertQuery();
            $query->insertInto(
                $this->dbHandler->quoteTable( 'ezcobj_state_language' )
            )->set(
                $this->dbHandler->quoteColumn( 'contentobject_state_id' ),
                $query->bindValue( $objectState->id, null, \PDO::PARAM_INT )
            )->set(
                $this->dbHandler->quoteColumn( 'description' ),
                $query->bindValue( $objectState->description[$languageCode] )
            )->set(
                $this->dbHandler->quoteColumn( 'name' ),
                $query->bindValue( $objectState->name[$languageCode] )
            )->set(
                $this->dbHandler->quoteColumn( 'language_id' ),
                $query->bindValue(
                    $this->maskGenerator->generateLanguageIndicator(
                        $languageCode, $languageCode === $objectState->defaultLanguage
                    ),
                    null, \PDO::PARAM_INT
                )
            );
            $query->prepare()->execute();
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::loadObjectStateData ($stateId)
Loads data for an object state
Parameters
mixed $stateId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 56 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\createObjectStateFindQuery().
    {
        $query = $this->createObjectStateFindQuery();
        $query->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id', 'ezcobj_state' ),
                $query->bindValue( $stateId, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::loadObjectStateDataByIdentifier ($identifier, $groupId)
Loads data for an object state by identifier
Parameters
string $identifier
mixed $groupId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 80 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\createObjectStateFindQuery().
    {
        $query = $this->createObjectStateFindQuery();
        $query->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'identifier', 'ezcobj_state' ),
                    $query->bindValue( $identifier, null, \PDO::PARAM_STR )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'group_id', 'ezcobj_state' ),
                    $query->bindValue( $groupId, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::loadObjectStateDataForContent ($contentId, $stateGroupId)
Loads object state data for $contentId content from $stateGroupId state group
Parameters
int $contentId
int $stateGroupId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 564 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\createObjectStateFindQuery().
    {
        $query = $this->createObjectStateFindQuery();
        $query->innerJoin(
            $this->dbHandler->quoteTable( 'ezcobj_state_link' ),
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id', 'ezcobj_state' ),
                $this->dbHandler->quoteColumn( 'contentobject_state_id', 'ezcobj_state_link' )
            )
        )->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'group_id', 'ezcobj_state' ),
                    $query->bindValue( $stateGroupId, null, \PDO::PARAM_INT )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentobject_id', 'ezcobj_state_link' ),
                    $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::loadObjectStateGroupData ($groupId)
Loads data for an object state group
Parameters
mixed $groupId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 138 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\createObjectStateGroupFindQuery().
    {
        $query = $this->createObjectStateGroupFindQuery();
        $query->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id', 'ezcobj_state_group' ),
                $query->bindValue( $groupId, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::loadObjectStateGroupDataByIdentifier ($identifier)
Loads data for an object state group by identifier
Parameters
string $identifier
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 161 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\createObjectStateGroupFindQuery().
    {
        $query = $this->createObjectStateGroupFindQuery();
        $query->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'identifier', 'ezcobj_state_group' ),
                $query->bindValue( $identifier, null, \PDO::PARAM_STR )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::loadObjectStateGroupListData ($offset, $limit)
Loads data for all object state groups, filtered by $offset and $limit
Parameters
int $offset
int $limit
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 185 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\createObjectStateGroupFindQuery().
    {
        $query = $this->createObjectStateGroupFindQuery();
        $query->limit( $limit > 0 ? $limit : PHP_INT_MAX, $offset );
        $statement = $query->prepare();
        $statement->execute();
        $rows = array();
        while ( $row = $statement->fetch( \PDO::FETCH_ASSOC ) )
        {
            $rows[$row['ezcobj_state_group_id']][] = $row;
        }
        return array_values( $rows );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::loadObjectStateListData ($groupId)
Loads data for all object states belonging to group with $groupId ID
Parameters
mixed $groupId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 109 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\createObjectStateFindQuery().
    {
        $query = $this->createObjectStateFindQuery();
        $query->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'group_id', 'ezcobj_state' ),
                $query->bindValue( $groupId, null, \PDO::PARAM_INT )
            )
        )->orderBy( $this->dbHandler->quoteColumn( 'priority', 'ezcobj_state' ), $query::ASC );
        $statement = $query->prepare();
        $statement->execute();
        $rows = array();
        while ( $row = $statement->fetch( \PDO::FETCH_ASSOC ) )
        {
            $rows[$row['ezcobj_state_id']][] = $row;
        }
        return array_values( $rows );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::setContentState ($contentId, $groupId, $stateId)
Sets the object state $stateId to content with $contentId ID
Parameters
mixed $contentId
mixed $groupId
mixed $stateId
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 482 of file EzcDatabase.php.
    {
        // First find out if $contentId is related to existing states in $groupId
        $query = $this->dbHandler->createSelectQuery();
        $query->select(
            $this->dbHandler->aliasedColumn( $query, 'id', 'ezcobj_state' )
        )->from(
            $this->dbHandler->quoteTable( 'ezcobj_state' )
        )->innerJoin(
            $this->dbHandler->quoteTable( 'ezcobj_state_link' ),
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id', 'ezcobj_state' ),
                $this->dbHandler->quoteColumn( 'contentobject_state_id', 'ezcobj_state_link' )
            )
        )->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'group_id', 'ezcobj_state' ),
                    $query->bindValue( $groupId, null, \PDO::PARAM_INT )
                ),
                $query->expr->eq(
                    $this->dbHandler->quoteColumn( 'contentobject_id', 'ezcobj_state_link' ),
                    $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        $rows = $statement->fetchAll( \PDO::FETCH_ASSOC );
        if ( !empty( $rows ) )
        {
            // We already have a state assigned to $contentId, update to new one
            $query = $this->dbHandler->createUpdateQuery();
            $query->update(
                $this->dbHandler->quoteTable( 'ezcobj_state_link' )
            )->set(
                $this->dbHandler->quoteColumn( 'contentobject_state_id' ),
                $query->bindValue( $stateId, null, \PDO::PARAM_INT )
            )->where(
                $query->expr->lAnd(
                    $query->expr->eq(
                        $this->dbHandler->quoteColumn( 'contentobject_id' ),
                        $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                    ),
                    $query->expr->eq(
                        $this->dbHandler->quoteColumn( 'contentobject_state_id' ),
                        $query->bindValue( $rows[0]['ezcobj_state_id'], null, \PDO::PARAM_INT )
                    )
                )
            );
            $query->prepare()->execute();
        }
        else
        {
            // No state assigned to $contentId from specified group, create assignment
            $query = $this->dbHandler->createInsertQuery();
            $query->insertInto(
                $this->dbHandler->quoteTable( 'ezcobj_state_link' )
            )->set(
                $this->dbHandler->quoteColumn( 'contentobject_id' ),
                $query->bindValue( $contentId, null, \PDO::PARAM_INT )
            )->set(
                $this->dbHandler->quoteColumn( 'contentobject_state_id' ),
                $query->bindValue( $stateId, null, \PDO::PARAM_INT )
            );
            $query->prepare()->execute();
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::updateObjectState (ObjectState $objectState)
Updates the stored object state with provided data
Parameters
\eZ\Publish\SPI\Persistence\Content\ObjectState $objectState
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 280 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\deleteObjectStateTranslations(), eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\generateLanguageMask(), and eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\insertObjectStateTranslations().
    {
        // First update the state
        $query = $this->dbHandler->createUpdateQuery();
        $query->update(
            $this->dbHandler->quoteTable( 'ezcobj_state' )
        )->set(
            $this->dbHandler->quoteColumn( 'default_language_id' ),
            $query->bindValue(
                $this->maskGenerator->generateLanguageIndicator( $objectState->defaultLanguage, false ),
                null, \PDO::PARAM_INT
            )
        )->set(
            $this->dbHandler->quoteColumn( 'identifier' ),
            $query->bindValue( $objectState->identifier )
        )->set(
            $this->dbHandler->quoteColumn( 'language_mask' ),
            $query->bindValue( $this->generateLanguageMask( $objectState->languageCodes ), null, \PDO::PARAM_INT )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $query->bindValue( $objectState->id, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
        // And then refresh object state translations
        // by removing existing ones and adding new ones
        $this->deleteObjectStateTranslations( $objectState->id );
        $this->insertObjectStateTranslations( $objectState );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::updateObjectStateGroup (Group $objectStateGroup)
Updates the stored object state group with provided data
Parameters
\eZ\Publish\SPI\Persistence\Content\ObjectState\Group $objectStateGroup
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 420 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\deleteObjectStateGroupTranslations(), eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\generateLanguageMask(), and eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase\insertObjectStateGroupTranslations().
    {
        // First update the group
        $query = $this->dbHandler->createUpdateQuery();
        $query->update(
            $this->dbHandler->quoteTable( 'ezcobj_state_group' )
        )->set(
            $this->dbHandler->quoteColumn( 'default_language_id' ),
            $query->bindValue(
                $this->maskGenerator->generateLanguageIndicator( $objectStateGroup->defaultLanguage, false ),
                null, \PDO::PARAM_INT
            )
        )->set(
            $this->dbHandler->quoteColumn( 'identifier' ),
            $query->bindValue( $objectStateGroup->identifier )
        )->set(
            $this->dbHandler->quoteColumn( 'language_mask' ),
            $query->bindValue( $this->generateLanguageMask( $objectStateGroup->languageCodes ), null, \PDO::PARAM_INT )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $query->bindValue( $objectStateGroup->id, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
        // And then refresh group translations
        // by removing old ones and adding new ones
        $this->deleteObjectStateGroupTranslations( $objectStateGroup->id );
        $this->insertObjectStateGroupTranslations( $objectStateGroup );
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::updateObjectStateLinks ($oldStateId, $newStateId)
Update object state links to $newStateId
Parameters
int $oldStateId
int $newStateId
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 341 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createUpdateQuery();
        $query->update(
            $this->dbHandler->quoteTable( 'ezcobj_state_link' )
        )->set(
            $this->dbHandler->quoteColumn( 'contentobject_state_id' ),
            $query->bindValue( $newStateId, null, \PDO::PARAM_INT )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'contentobject_state_id' ),
                $query->bindValue( $oldStateId, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::updateObjectStatePriority ($stateId, $priority)
Updates the object state priority to provided value
Parameters
mixed $stateId
int $priority
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway.
Definition at line 627 of file EzcDatabase.php.
    {
        $query = $this->dbHandler->createUpdateQuery();
        $query->update(
            $this->dbHandler->quoteTable( 'ezcobj_state' )
        )->set(
            $this->dbHandler->quoteColumn( 'priority' ),
            $query->bindValue( $priority, null, \PDO::PARAM_INT )
        )->where(
            $query->expr->eq(
                $this->dbHandler->quoteColumn( 'id' ),
                $query->bindValue( $stateId, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::$dbHandler protected
Definition at line 28 of file EzcDatabase.php.
eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\EzcDatabase::$maskGenerator protected
Definition at line 35 of file EzcDatabase.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/ObjectState/Gateway/EzcDatabase.php