ezp-next: eZ\Publish\Core\Repository\Repository Class Reference
eZ\Publish\Core\Repository\Repository Class Reference
Public Member Functions
__construct (PersistenceHandler $persistenceHandler, IoHandler $ioHandler, array $serviceSettings=array(), User $user=null)
getCurrentUser ()
setCurrentUser (User $user)
hasAccess ($module, $function, User $user=null)
getContentService ()
getContentLanguageService ()
getContentTypeService ()
getLocationService ()
getTrashService ()
getSectionService ()
getUserService ()
getURLAliasService ()
getURLWildcardService ()
getObjectStateService ()
getIOService ()
getRoleService ()
getSearchService ()
getFieldTypeService ()
getNameSchemaService ()
beginTransaction ()
commit ()
rollback ()
createDateTime ($timestamp=null)
Public Member Functions inherited from eZ\Publish\API\Repository\Repository
canUser ($module, $function, ValueObject $object, ValueObject $target=null)
Protected Attributes
$persistenceHandler
$ioHandler
$user
$contentService
$sectionService
$roleService
$searchService
$userService
$languageService
$locationService
$trashService
$contentTypeService
$ioService
$objectStateService
$fieldTypeService
$nameSchemaService
$urlAliasService
$urlWildcardService
$serviceSettings
Detailed Description
Definition at line 26 of file Repository.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\Repository::__construct (PersistenceHandler $persistenceHandler, IoHandler $ioHandler, array $serviceSettings = array(), User $user = null)
Constructor
Construct repository object with provided storage engine
Parameters
\eZ\Publish\SPI\Persistence\Handler $persistenceHandler
\eZ\Publish\SPI\IO\Handler $ioHandler
array $serviceSettings
\eZ\Publish\API\Repository\Values\User\User | null $user
Definition at line 171 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$ioHandler, eZ\Publish\Core\Repository\Repository\$persistenceHandler, eZ\Publish\Core\Repository\Repository\$serviceSettings, eZ\Publish\Core\Repository\Repository\$user, and eZ\Publish\Core\Repository\Repository\setCurrentUser().
    {
        $this->persistenceHandler = $persistenceHandler;
        $this->ioHandler = $ioHandler;
        $this->serviceSettings = $serviceSettings + array(
            'content' => array(),
            'contentType' => array(),
            'location' => array(),
            'section' => array(),
            'role' => array(),
            'user' => array(),
            'language' => array(),
            'trash' => array(),
            'io' => array(),
            'objectState' => array(),
            'search' => array(),
            'fieldType' => array(),
            'urlAlias' => array(),
            'urlWildcard' => array(),
            'nameSchema' => array(
                'limit' => 0,
                'sequence' => ''
            ),
            'languages' => array()
        );
        if ( !empty( $this->serviceSettings['languages'] ) )
        {
            $this->serviceSettings['language']['languages'] = $this->serviceSettings['languages'];
        }
        if ( $user !== null )
            $this->setCurrentUser( $user );
    }
Member Function Documentation
eZ\Publish\Core\Repository\Repository::beginTransaction ()
Begin transaction
Begins an transaction, make sure you'll call commit or rollback when done, otherwise work will be lost.
Implements eZ\Publish\API\Repository\Repository.
Definition at line 635 of file Repository.php.
    {
        $this->persistenceHandler->beginTransaction();
    }
eZ\Publish\Core\Repository\Repository::commit ()
Commit transaction
Commit transaction, or throw exceptions if no transactions has been started.
Exceptions
RuntimeException If no transaction has been started
Implements eZ\Publish\API\Repository\Repository.
Definition at line 647 of file Repository.php.
    {
        try
        {
            $this->persistenceHandler->commit();
        }
        catch ( Exception $e )
        {
            throw new RuntimeException( $e->getMessage(), 0, $e );
        }
    }
eZ\Publish\Core\Repository\Repository::createDateTime ($timestamp = null)
Only for internal use.
Creates a object for $timestamp in the current time zone
Parameters
int $timestamp
Returns
Definition at line 687 of file Repository.php.
    {
        $dateTime = new \DateTime();
        if ( $timestamp !== null )
        {
            $dateTime->setTimestamp( $timestamp );
        }
        return $dateTime;
    }
eZ\Publish\Core\Repository\Repository::getContentLanguageService ()
Get Content Language Service
Get service object to perform operations on Content language objects
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 383 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$languageService.
    {
        if ( $this->languageService !== null )
            return $this->languageService;
        $this->languageService = new LanguageService(
            $this,
            $this->persistenceHandler->contentLanguageHandler(),
            $this->serviceSettings['language']
        );
        return $this->languageService;
    }
eZ\Publish\Core\Repository\Repository::getContentService ()
Get Content Service
Get service object to perform operations on Content objects and it's aggregate members.
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 367 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$contentService.
    {
        if ( $this->contentService !== null )
            return $this->contentService;
        $this->contentService = new ContentService( $this, $this->persistenceHandler, $this->serviceSettings['content'] );
        return $this->contentService;
    }
eZ\Publish\Core\Repository\Repository::getContentTypeService ()
Get Content Type Service
Get service object to perform operations on Content Type objects and it's aggregate members. (Group, Field & FieldCategory)
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 404 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$contentTypeService.
    {
        if ( $this->contentTypeService !== null )
            return $this->contentTypeService;
        $this->contentTypeService = new ContentTypeService(
            $this,
            $this->persistenceHandler->contentTypeHandler(),
            $this->serviceSettings['contentType']
        );
        return $this->contentTypeService;
    }
eZ\Publish\Core\Repository\Repository::getCurrentUser ()
Get current user
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 211 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$user, and eZ\Publish\Core\Repository\Repository\getUserService().
    {
        if ( !$this->user instanceof User )
        {
            $this->user = $this->getUserService()->loadAnonymousUser();
        }
        return $this->user;
    }
eZ\Publish\Core\Repository\Repository::getFieldTypeService ()
Get FieldTypeService
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 602 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$fieldTypeService.
    {
        if ( $this->fieldTypeService !== null )
            return $this->fieldTypeService;
        $this->fieldTypeService = new FieldTypeService( $this, $this->persistenceHandler, $this->serviceSettings['fieldType'] );
        return $this->fieldTypeService;
    }
eZ\Publish\Core\Repository\Repository::getIOService ()
Get IO Service
Get service object to perform operations on binary files
Deprecated:
Will be removed in the future!
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 552 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$ioService.
    {
        if ( $this->ioService !== null )
            return $this->ioService;
        $this->ioService = new IOService( $this, $this->ioHandler, $this->serviceSettings['io'] );
        return $this->ioService;
    }
eZ\Publish\Core\Repository\Repository::getLocationService ()
Get Content Location Service
Get service object to perform operations on Location objects and subtrees
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 424 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$locationService.
    {
        if ( $this->locationService !== null )
            return $this->locationService;
        $this->locationService = new LocationService( $this, $this->persistenceHandler, $this->serviceSettings['location'] );
        return $this->locationService;
    }
eZ\Publish\Core\Repository\Repository::getNameSchemaService ()
Get NameSchemaResolverService
private Internal service for the Core Services
Todo:
Move out from this & other repo instances when services becomes proper services in DIC terms using factory.
Returns
Definition at line 620 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$nameSchemaService.
    {
        if ( $this->nameSchemaService !== null )
            return $this->nameSchemaService;
        $this->nameSchemaService = new NameSchemaService( $this, $this->serviceSettings['nameSchema'] );
        return $this->nameSchemaService;
    }
eZ\Publish\Core\Repository\Repository::getObjectStateService ()
Get ObjectStateService
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 531 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$objectStateService.
    {
        if ( $this->objectStateService !== null )
            return $this->objectStateService;
        $this->objectStateService = new ObjectStateService(
            $this, $this->persistenceHandler->objectStateHandler(),
            $this->serviceSettings['objectState']
        );
        return $this->objectStateService;
    }
eZ\Publish\Core\Repository\Repository::getRoleService ()
Get RoleService
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 566 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$roleService.
    {
        if ( $this->roleService !== null )
            return $this->roleService;
        $this->roleService = new RoleService(
            $this,
            $this->persistenceHandler->userHandler(),
            $this->serviceSettings['role']
        );
        return $this->roleService;
    }
eZ\Publish\Core\Repository\Repository::getSearchService ()
Get SearchService
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 584 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$searchService.
    {
        if ( $this->searchService !== null )
            return $this->searchService;
        $this->searchService = new SearchService(
            $this,
            $this->persistenceHandler->searchHandler(),
            $this->serviceSettings['search']
        );
        return $this->searchService;
    }
eZ\Publish\Core\Repository\Repository::getSectionService ()
Get Content Section Service
Get Section service that lets you manipulate section objects
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 457 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$sectionService.
    {
        if ( $this->sectionService !== null )
            return $this->sectionService;
        $this->sectionService = new SectionService(
            $this,
            $this->persistenceHandler->sectionHandler(),
            $this->serviceSettings['section']
        );
        return $this->sectionService;
    }
eZ\Publish\Core\Repository\Repository::getTrashService ()
Get Content Trash service
Trash service allows to perform operations related to location trash (trash/untrash, load/list from trash...)
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 441 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$trashService.
    {
        if ( $this->trashService !== null )
            return $this->trashService;
        $this->trashService = new TrashService( $this, $this->persistenceHandler, $this->serviceSettings['trash'] );
        return $this->trashService;
    }
eZ\Publish\Core\Repository\Repository::getURLAliasService ()
Get URLAliasService
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 495 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$urlAliasService.
    {
        if ( $this->urlAliasService !== null )
            return $this->urlAliasService;
        $this->urlAliasService = new URLAliasService(
            $this,
            $this->persistenceHandler->urlAliasHandler(),
            $this->serviceSettings['urlAlias']
        );
        return $this->urlAliasService;
    }
eZ\Publish\Core\Repository\Repository::getURLWildcardService ()
Get URLWildcardService
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 513 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$urlWildcardService.
    {
        if ( $this->urlWildcardService !== null )
            return $this->urlWildcardService;
        $this->urlWildcardService = new URLWildcardService(
            $this,
            $this->persistenceHandler->urlWildcardHandler(),
            $this->serviceSettings['urlWildcard']
        );
        return $this->urlWildcardService;
    }
eZ\Publish\Core\Repository\Repository::getUserService ()
Get User Service
Get service object to perform operations on Users and UserGroup
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 477 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$userService.
    {
        if ( $this->userService !== null )
            return $this->userService;
        $this->userService = new UserService(
            $this,
            $this->persistenceHandler->userHandler(),
            $this->serviceSettings['user']
        );
        return $this->userService;
    }
eZ\Publish\Core\Repository\Repository::hasAccess ($module, $function, User $user = null)
Check if user has access to a given module / function
Low level function, use canUser instead if you have objects to check against.
Parameters
string $module
string $function
\eZ\Publish\API\Repository\Values\User\User $user
Returns
boolean|array Bool if user has full or no access, array if limitations if not
Implements eZ\Publish\API\Repository\Repository.
Definition at line 247 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$roleService, eZ\Publish\Core\Repository\Repository\$user, eZ\Publish\Core\Repository\Repository\getCurrentUser(), and eZ\Publish\Core\Repository\Repository\getRoleService().
    {
        if ( $user === null )
            $user = $this->getCurrentUser();
        // Uses SPI to avoid triggering permission checks in Role/User service
        $permissionSets = array();
        $roleService = $this->getRoleService();
        $spiRoleAssignments = $this->persistenceHandler->userHandler()->loadRoleAssignmentsByGroupId( $user->id, true );
        foreach ( $spiRoleAssignments as $spiRoleAssignment )
        {
            $permissionSet = array( 'limitation' => null, 'policies' => array() );
            foreach ( $spiRoleAssignment->role->policies as $spiPolicy )
            {
                if ( $spiPolicy->module === '*' && $spiRoleAssignment->limitationIdentifier === null )
                    return true;
                if ( $spiPolicy->module !== $module && $spiPolicy->module !== '*' )
                    continue;
                if ( $spiPolicy->function === '*' && $spiRoleAssignment->limitationIdentifier === null )
                    return true;
                if ( $spiPolicy->function !== $function && $spiPolicy->function !== '*' )
                    continue;
                if ( $spiPolicy->limitations === '*' && $spiRoleAssignment->limitationIdentifier === null )
                    return true;
                $permissionSet['policies'][] = $roleService->buildDomainPolicyObject( $spiPolicy );
            }
            if ( !empty( $permissionSet['policies'] ) )
            {
                if ( $spiRoleAssignment->limitationIdentifier !== null )
                    $permissionSet['limitation'] = $roleService
                        ->getLimitationType( $spiRoleAssignment->limitationIdentifier )
                        ->buildValue( $spiRoleAssignment->values );
                $permissionSets[] = $permissionSet;
            }
        }
        if ( !empty( $permissionSets ) )
            return $permissionSets;
        return false;// No policies matching $module and $function, or they contained limitations
    }
eZ\Publish\Core\Repository\Repository::rollback ()
Rollback transaction
Rollback transaction, or throw exceptions if no transactions has been started.
Exceptions
RuntimeException If no transaction has been started
Implements eZ\Publish\API\Repository\Repository.
Definition at line 666 of file Repository.php.
    {
        try
        {
            $this->persistenceHandler->rollback();
        }
        catch ( Exception $e )
        {
            throw new RuntimeException( $e->getMessage(), 0, $e );
        }
    }
eZ\Publish\Core\Repository\Repository::setCurrentUser (User $user)
Sets the current user to the given $user.
Parameters
\eZ\Publish\API\Repository\Values\User\User $user
Returns
void
Implements eZ\Publish\API\Repository\Repository.
Definition at line 228 of file Repository.php.
References eZ\Publish\Core\Repository\Repository\$user.
    {
        if ( !$user->id )
            throw new InvalidArgumentValue( '$user->id', $user->id );
        $this->user = $user;
    }
Member Data Documentation
eZ\Publish\Core\Repository\Repository::$contentService protected
Definition at line 54 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$contentTypeService protected
Definition at line 110 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$fieldTypeService protected
Definition at line 131 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$ioHandler protected
Definition at line 40 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$ioService protected
Definition at line 117 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$languageService protected
Definition at line 89 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$locationService protected
Definition at line 96 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$nameSchemaService protected
Definition at line 138 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$objectStateService protected
Definition at line 124 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$persistenceHandler protected
Definition at line 33 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$roleService protected
Definition at line 68 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$searchService protected
Definition at line 75 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$sectionService protected
Definition at line 61 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$serviceSettings protected
Definition at line 159 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$trashService protected
Definition at line 103 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$urlAliasService protected
Definition at line 145 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$urlWildcardService protected
Definition at line 152 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$user protected
Definition at line 47 of file Repository.php.
eZ\Publish\Core\Repository\Repository::$userService protected
Definition at line 82 of file Repository.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/Repository.php