ezp-next: eZ\Publish\Core\MVC\Symfony\Security\User\Provider Class Reference
eZ\Publish\Core\MVC\Symfony\Security\User\Provider Class Reference
Public Member Functions
__construct (\Closure $lazyRepository)
loadUserByUsername ($user)
refreshUser (UserInterface $user)
supportsClass ($class)
loadUserByAPIUser (APIUser $apiUser)
Protected Member Functions
getRepository ()
getUserService ()
Protected Attributes
$userService
Detailed Description
Definition at line 19 of file Provider.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\Security\User\Provider::__construct (\Closure $lazyRepository)
Definition at line 31 of file Provider.php.
    {
        $this->lazyRepository = $lazyRepository;
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\Security\User\Provider::getRepository () protected
Returns
Definition at line 39 of file Provider.php.
References eZ\Publish\Core\MVC\Symfony\Security\User\Provider\getRepository().
    {
        $lazyRepository = $this->lazyRepository;
        return $lazyRepository();
    }
eZ\Publish\Core\MVC\Symfony\Security\User\Provider::getUserService () protected
Returns
Definition at line 48 of file Provider.php.
References eZ\Publish\Core\MVC\Symfony\Security\User\Provider\getRepository(), and eZ\Publish\Core\MVC\Symfony\Security\User\Provider\getUserService().
    {
        return $this->getRepository()->getUserService();
    }
eZ\Publish\Core\MVC\Symfony\Security\User\Provider::loadUserByAPIUser (APIUser $apiUser)
Loads a regular user object, usable by Symfony Security component, from a user object returned by Public API
Parameters
\eZ\Publish\API\Repository\Values\User\User $apiUser
Returns
Implements eZ\Publish\Core\MVC\Symfony\Security\User\APIUserProviderInterface.
Definition at line 123 of file Provider.php.
References eZ\Publish\Core\MVC\Symfony\Security\User\Provider\loadUserByAPIUser().
    {
        return new User( $apiUser );
    }
eZ\Publish\Core\MVC\Symfony\Security\User\Provider::loadUserByUsername ($user)
Loads the user for the given user ID. $user can be either the user ID or an instance of (anonymous user we try to check access via SecurityContext::isGranted())
Parameters
string | \eZ\Publish\Core\MVC\Symfony\Security\User $user Either the user ID to load an instance of User object. A value of -1 represents an anonymous user.
Returns
Exceptions
\Symfony\Component\Security\Core\Exception\UsernameNotFoundException if the user is not found
Definition at line 64 of file Provider.php.
References eZ\Publish\Core\MVC\Symfony\Security\User\Provider\getUserService(), and eZ\Publish\Core\MVC\Symfony\Security\User\Provider\loadUserByUsername().
    {
        try
        {
            // SecurityContext always tries to authenticate anonymous users when checking granted access.
            // In that case $user is an instance of \eZ\Publish\Core\MVC\Symfony\Security\User.
            // We don't need to reload the user here.
            if ( $user instanceof User )
                return $user;
            $isLoggedIn = $user != -1;
            $apiUser = $isLoggedIn ? $this->getUserService()->loadUser( $user ) : $this->getUserService()->loadAnonymousUser();
            $roles = $isLoggedIn ? array( 'ROLE_USER' ) : array();
            return new User( $apiUser, $roles );
        }
        catch ( NotFoundException $e )
        {
            throw new UsernameNotFoundException( $e->getMessage(), null, 0, $e );
        }
    }
eZ\Publish\Core\MVC\Symfony\Security\User\Provider::refreshUser (UserInterface $user)
Refreshes the user for the account interface.
It is up to the implementation to decide if the user data should be totally reloaded (e.g. from the database), or if the UserInterface object can just be merged into some internal array of users / identity map.
Parameters
UserInterface $user
Exceptions
\Symfony\Component\Security\Core\Exception\UsernameNotFoundException
Returns
UserInterface
Definition at line 98 of file Provider.php.
References eZ\Publish\Core\MVC\Symfony\Security\User\Provider\refreshUser().
    {
        return $user;
    }
eZ\Publish\Core\MVC\Symfony\Security\User\Provider::supportsClass ($class)
Whether this provider supports the given user class
Parameters
string $class
Returns
Boolean
Definition at line 110 of file Provider.php.
References eZ\Publish\Core\MVC\Symfony\Security\User\Provider\supportsClass().
    {
        $supportedClass = 'eZ\\Publish\\Core\\MVC\\Symfony\\Security\\User';
        return $class === $supportedClass || is_subclass_of( $class, $supportedClass );
    }
Member Data Documentation
eZ\Publish\Core\MVC\Symfony\Security\User\Provider::$userService protected
Definition at line 24 of file Provider.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/Security/User/Provider.php