ezp-next: eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase Class Reference
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase Class Reference
Public Member Functions
__construct (EzcDbHandler $handler)
createRole (Role $role)
loadRole ($roleId)
loadRoleByIdentifier ($identifier)
loadRoles ()
loadRolesForContentObjects ($contentIds)
loadRoleAssignmentsByGroupId ($groupId, $inherited=false)
loadPoliciesByUserId ($userId)
updateRole (RoleUpdateStruct $role)
deleteRole ($roleId)
addPolicy ($roleId, Policy $policy)
addPolicyLimitations ($policyId, array $limitations)
removePolicy ($policyId)
removePolicyLimitations ($policyId)
Public Attributes
const GROUP_TYPE_ID = 3
Protected Member Functions
fetchUserGroups ($userId)
Protected Attributes
$handler
Detailed Description
Base class for content type gateways.
Definition at line 21 of file EzcDatabase.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::__construct (EzcDbHandler $handler)
Construct from database handler
Parameters
\eZ\Publish\Core\Persistence\Legacy\EzcDbHandler $handler
Returns
void
Definition at line 42 of file EzcDatabase.php.
    {
        $this->handler = $handler;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::addPolicy ($roleId, Policy $policy)
Adds a policy to a role
Parameters
mixed $roleId
\eZ\Publish\SPI\Persistence\User\Policy $policy
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 503 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\addPolicyLimitations().
    {
        $query = $this->handler->createInsertQuery();
        $query
            ->insertInto( $this->handler->quoteTable( 'ezpolicy' ) )
            ->set(
                $this->handler->quoteColumn( 'id' ),
                $this->handler->getAutoIncrementValue( 'ezpolicy', 'id' )
            )->set(
                $this->handler->quoteColumn( 'function_name' ),
                $query->bindValue( $policy->function )
            )->set(
                $this->handler->quoteColumn( 'module_name' ),
                $query->bindValue( $policy->module )
            )->set(
                $this->handler->quoteColumn( 'original_id' ),
                0
            )->set(
                $this->handler->quoteColumn( 'role_id' ),
                $query->bindValue( $roleId, null, \PDO::PARAM_INT )
            );
        $query->prepare()->execute();
        $policy->id = $this->handler->lastInsertId(
            $this->handler->getSequenceName( 'ezpolicy', 'id' )
        );
        // Handle the only valid non-array value "*" by not inserting
        // anything. Still has not been documented by eZ Systems. So we
        // assume this is the right way to handle it.
        if ( is_array( $policy->limitations ) )
        {
            $this->addPolicyLimitations( $policy->id, $policy->limitations );
        }
        return $policy;
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::addPolicyLimitations ($policyId, array $limitations)
Adds limitations to an existing policy
Parameters
int $policyId
array $limitations
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 549 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\User\Role\$identifier.
    {
        foreach ( $limitations as $identifier => $values )
        {
            $query = $this->handler->createInsertQuery();
            $query
                ->insertInto( $this->handler->quoteTable( 'ezpolicy_limitation' ) )
                ->set(
                    $this->handler->quoteColumn( 'id' ),
                    $this->handler->getAutoIncrementValue( 'ezpolicy_limitation', 'id' )
                )->set(
                    $this->handler->quoteColumn( 'identifier' ),
                    $query->bindValue( $identifier )
                )->set(
                    $this->handler->quoteColumn( 'policy_id' ),
                    $query->bindValue( $policyId, null, \PDO::PARAM_INT )
                );
            $query->prepare()->execute();
            $limitationId = $this->handler->lastInsertId(
                $this->handler->getSequenceName( 'ezpolicy_limitation', 'id' )
            );
            foreach ( $values as $value )
            {
                $query = $this->handler->createInsertQuery();
                $query
                    ->insertInto( $this->handler->quoteTable( 'ezpolicy_limitation_value' ) )
                    ->set(
                        $this->handler->quoteColumn( 'id' ),
                        $this->handler->getAutoIncrementValue( 'ezpolicy_limitation_value', 'id' )
                    )->set(
                        $this->handler->quoteColumn( 'value' ),
                        $query->bindValue( $value )
                    )->set(
                        $this->handler->quoteColumn( 'limitation_id' ),
                        $query->bindValue( $limitationId, null, \PDO::PARAM_INT )
                    );
                $query->prepare()->execute();
            }
        }
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::createRole (Role $role)
Create new role
Parameters
\eZ\Publish\SPI\Persistence\User\Role $role
Returns
Role
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 54 of file EzcDatabase.php.
    {
        $query = $this->handler->createInsertQuery();
        $query
            ->insertInto( $this->handler->quoteTable( 'ezrole' ) )
            ->set(
                $this->handler->quoteColumn( 'id' ),
                $this->handler->getAutoIncrementValue( 'ezrole', 'id' )
            )->set(
                $this->handler->quoteColumn( 'is_new' ),
                0
            )->set(
                $this->handler->quoteColumn( 'name' ),
                $query->bindValue( $role->identifier )
            )->set(
                $this->handler->quoteColumn( 'value' ),
                0
            )->set(
                $this->handler->quoteColumn( 'version' ),
                0
            );
        $query->prepare()->execute();
        $role->id = $this->handler->lastInsertId(
            $this->handler->getSequenceName( 'ezrole', 'id' )
        );
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::deleteRole ($roleId)
Delete the specified role
Parameters
mixed $roleId
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 481 of file EzcDatabase.php.
    {
        $query = $this->handler->createDeleteQuery();
        $query
            ->deleteFrom( $this->handler->quoteTable( 'ezrole' ) )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'id' ),
                    $query->bindValue( $roleId, null, \PDO::PARAM_INT )
                )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::fetchUserGroups ($userId) protected
Fetch all group IDs the user belongs to
Parameters
int $userId
Returns
array
Definition at line 385 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase\fetchUserGroups().
    {
        $query = $this->handler->createSelectQuery();
        $query->select(
            $this->handler->quoteColumn( 'path_string', 'ezcontentobject_tree' )
        )->from(
            $this->handler->quoteTable( 'ezcontentobject_tree' )
        )->where(
            $query->expr->eq(
                $this->handler->quoteColumn( 'contentobject_id', 'ezcontentobject_tree' ),
                $query->bindValue( $userId )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        $paths = $statement->fetchAll( \PDO::FETCH_COLUMN );
        $nodeIDs = array_unique(
            array_reduce(
                array_map(
                    function ( $pathString )
                    {
                        return array_filter( explode( '/', $pathString ) );
                    },
                    $paths
                ),
                'array_merge_recursive',
                array()
            )
        );
        if ( empty( $nodeIDs ) )
            return array();
        // Limit nodes to groups only
        $query = $this->handler->createSelectQuery();
        $query->select(
            $this->handler->quoteColumn( 'id', 'ezcontentobject' )
        )->from(
            $this->handler->quoteTable( 'ezcontentobject_tree' )
        )->rightJoin(
            $this->handler->quoteTable( 'ezcontentobject' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'id', 'ezcontentobject' ),
                $this->handler->quoteColumn( 'contentobject_id', 'ezcontentobject_tree' )
            )
        )->where(
            $query->expr->lAnd(
                $query->expr->in(
                    $this->handler->quoteColumn( 'node_id', 'ezcontentobject_tree' ),
                    $nodeIDs
                ),
                $query->expr->eq(
                    $this->handler->quoteColumn( 'contentclass_id', 'ezcontentobject' ),
                    // We use the integer type ID here, to minimize joins and
                    // make use of existing keys. One might want to make this
                    // "injectable".
                    $query->bindValue( self::GROUP_TYPE_ID, null, \PDO::PARAM_INT )// @todo: Can not hard code group type id!
                )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_COLUMN );
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::loadPoliciesByUserId ($userId)
Returns the user policies associated with the user
Parameters
mixed $userId
Returns
UserPolicy[]
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 370 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\User\Role\$groupIds, eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase\fetchUserGroups(), and eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\loadRolesForContentObjects().
    {
        $groupIds = $this->fetchUserGroups( $userId );
        $groupIds[] = $userId;
        return $this->loadRolesForContentObjects( $groupIds );
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::loadRole ($roleId)
Loads a specified role by id
Parameters
mixed $roleId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 89 of file EzcDatabase.php.
    {
        $query = $this->handler->createSelectQuery();
        $query->select(
            $this->handler->aliasedColumn( $query, 'id', 'ezrole' ),
            $this->handler->aliasedColumn( $query, 'name', 'ezrole' ),
            $this->handler->aliasedColumn( $query, 'contentobject_id', 'ezuser_role' ),
            $this->handler->aliasedColumn( $query, 'id', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'function_name', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'module_name', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'identifier', 'ezpolicy_limitation' ),
            $this->handler->aliasedColumn( $query, 'value', 'ezpolicy_limitation_value' )
        )->from(
            $this->handler->quoteTable( 'ezrole' )
        )->leftJoin(
            $this->handler->quoteTable( 'ezuser_role' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'role_id', 'ezuser_role' ),
                $this->handler->quoteColumn( 'id', 'ezrole' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'role_id', 'ezpolicy' ),
                $this->handler->quoteColumn( 'id', 'ezrole' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy_limitation' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'policy_id', 'ezpolicy_limitation' ),
                $this->handler->quoteColumn( 'id', 'ezpolicy' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy_limitation_value' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'limitation_id', 'ezpolicy_limitation_value' ),
                $this->handler->quoteColumn( 'id', 'ezpolicy_limitation' )
            )
        )->where(
            $query->expr->eq(
                $this->handler->quoteColumn( 'id', 'ezrole' ),
                $query->bindValue( $roleId, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::loadRoleAssignmentsByGroupId ($groupId, $inherited = false)
Loads role assignments for specified content ID
Parameters
mixed $groupId
boolean $inherited
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 324 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\User\Role\$groupIds, and eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase\fetchUserGroups().
    {
        $query = $this->handler->createSelectQuery();
        $query->select(
            $this->handler->quoteColumn( 'contentobject_id' ),
            $this->handler->quoteColumn( 'limit_identifier' ),
            $this->handler->quoteColumn( 'limit_value' ),
            $this->handler->quoteColumn( 'role_id' )
        )->from(
            $this->handler->quoteTable( 'ezuser_role' )
        );
        if ( $inherited )
        {
            $groupIds = $this->fetchUserGroups( $groupId );
            $groupIds[] = $groupId;
            $query->where(
                $query->expr->in(
                    $this->handler->quoteColumn( 'contentobject_id' ),
                    $groupIds
                )
            );
        }
        else
        {
            $query->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'contentobject_id' ),
                    $query->bindValue( $groupId, null, \PDO::PARAM_INT )
                )
            );
        }
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::loadRoleByIdentifier ($identifier)
Loads a specified role by $identifier
Parameters
string $identifier
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 147 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\User\Role\$identifier.
    {
        $query = $this->handler->createSelectQuery();
        $query->select(
            $this->handler->aliasedColumn( $query, 'id', 'ezrole' ),
            $this->handler->aliasedColumn( $query, 'name', 'ezrole' ),
            $this->handler->aliasedColumn( $query, 'contentobject_id', 'ezuser_role' ),
            $this->handler->aliasedColumn( $query, 'id', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'function_name', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'module_name', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'identifier', 'ezpolicy_limitation' ),
            $this->handler->aliasedColumn( $query, 'value', 'ezpolicy_limitation_value' )
        )->from(
            $this->handler->quoteTable( 'ezrole' )
        )->leftJoin(
            $this->handler->quoteTable( 'ezuser_role' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'role_id', 'ezuser_role' ),
                $this->handler->quoteColumn( 'id', 'ezrole' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'role_id', 'ezpolicy' ),
                $this->handler->quoteColumn( 'id', 'ezrole' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy_limitation' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'policy_id', 'ezpolicy_limitation' ),
                $this->handler->quoteColumn( 'id', 'ezpolicy' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy_limitation_value' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'limitation_id', 'ezpolicy_limitation_value' ),
                $this->handler->quoteColumn( 'id', 'ezpolicy_limitation' )
            )
        )->where(
            $query->expr->eq(
                $this->handler->quoteColumn( 'name', 'ezrole' ),
                $query->bindValue( $identifier, null, \PDO::PARAM_STR )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::loadRoles ()
Loads all roles
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 203 of file EzcDatabase.php.
    {
        $query = $this->handler->createSelectQuery();
        $query->select(
            $this->handler->aliasedColumn( $query, 'id', 'ezrole' ),
            $this->handler->aliasedColumn( $query, 'name', 'ezrole' ),
            $this->handler->aliasedColumn( $query, 'contentobject_id', 'ezuser_role' ),
            $this->handler->aliasedColumn( $query, 'id', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'function_name', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'module_name', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'identifier', 'ezpolicy_limitation' ),
            $this->handler->aliasedColumn( $query, 'value', 'ezpolicy_limitation_value' )
        )->from(
            $this->handler->quoteTable( 'ezrole' )
        )->leftJoin(
            $this->handler->quoteTable( 'ezuser_role' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'role_id', 'ezuser_role' ),
                $this->handler->quoteColumn( 'id', 'ezrole' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'role_id', 'ezpolicy' ),
                $this->handler->quoteColumn( 'id', 'ezrole' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy_limitation' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'policy_id', 'ezpolicy_limitation' ),
                $this->handler->quoteColumn( 'id', 'ezpolicy' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy_limitation_value' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'limitation_id', 'ezpolicy_limitation_value' ),
                $this->handler->quoteColumn( 'id', 'ezpolicy_limitation' )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::loadRolesForContentObjects ($contentIds)
Loads all roles associated with the given content objects
Parameters
array $contentIds
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 256 of file EzcDatabase.php.
    {
        $query = $this->handler->createSelectQuery();
        $query->select(
            $this->handler->aliasedColumn( $query, 'contentobject_id', 'ezuser_role' ),
            $this->handler->aliasedColumn( $query, 'id', 'ezrole' ),
            $this->handler->aliasedColumn( $query, 'name', 'ezrole' ),
            $this->handler->aliasedColumn( $query, 'id', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'function_name', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'module_name', 'ezpolicy' ),
            $this->handler->aliasedColumn( $query, 'identifier', 'ezpolicy_limitation' ),
            $this->handler->aliasedColumn( $query, 'value', 'ezpolicy_limitation_value' )
        )->from(
            $query->alias(
                $this->handler->quoteTable( 'ezuser_role' ),
                $this->handler->quoteIdentifier( 'ezuser_role_search' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezrole' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'id', 'ezrole' ),
                $this->handler->quoteColumn( 'role_id', 'ezuser_role_search' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezuser_role' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'role_id', 'ezuser_role' ),
                $this->handler->quoteColumn( 'id', 'ezrole' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'role_id', 'ezpolicy' ),
                $this->handler->quoteColumn( 'id', 'ezrole' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy_limitation' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'policy_id', 'ezpolicy_limitation' ),
                $this->handler->quoteColumn( 'id', 'ezpolicy' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy_limitation_value' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'limitation_id', 'ezpolicy_limitation_value' ),
                $this->handler->quoteColumn( 'id', 'ezpolicy_limitation' )
            )
        )->where(
            $query->expr->in(
                $this->handler->quoteColumn( 'contentobject_id', 'ezuser_role_search' ),
                $contentIds
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::removePolicy ($policyId)
Removes a policy from a role
Parameters
mixed $policyId
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 599 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\removePolicyLimitations().
    {
        $this->removePolicyLimitations( $policyId );
        $query = $this->handler->createDeleteQuery();
        $query
            ->deleteFrom( $this->handler->quoteTable( 'ezpolicy' ) )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'id' ),
                    $query->bindValue( $policyId, null, \PDO::PARAM_INT )
                )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::removePolicyLimitations ($policyId)
Remove all limitations for a policy
Parameters
mixed $policyId
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 622 of file EzcDatabase.php.
    {
        $query = $this->handler->createSelectQuery();
        $query->select(
            $this->handler->aliasedColumn( $query, 'id', 'ezpolicy_limitation' ),
            $this->handler->aliasedColumn( $query, 'id', 'ezpolicy_limitation_value' )
        )->from(
            $this->handler->quoteTable( 'ezpolicy' )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy_limitation' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'policy_id', 'ezpolicy_limitation' ),
                $this->handler->quoteColumn( 'id', 'ezpolicy' )
            )
        )->leftJoin(
            $this->handler->quoteTable( 'ezpolicy_limitation_value' ),
            $query->expr->eq(
                $this->handler->quoteColumn( 'limitation_id', 'ezpolicy_limitation_value' ),
                $this->handler->quoteColumn( 'id', 'ezpolicy_limitation' )
            )
        )->where(
            $query->expr->eq(
                $this->handler->quoteColumn( 'id', 'ezpolicy' ),
                $query->bindValue( $policyId, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        $limitations = array();
        $values = array();
        while ( $row = $statement->fetch( \PDO::FETCH_ASSOC ) )
        {
            $limitations[] = $row['ezpolicy_limitation_id'];
            $values[] = $row['ezpolicy_limitation_value_id'];
        }
        $query = $this->handler->createDeleteQuery();
        $query
            ->deleteFrom( $this->handler->quoteTable( 'ezpolicy_limitation' ) )
            ->where(
                $query->expr->in( $this->handler->quoteColumn( 'id' ), array_unique( $limitations ) )
            );
        $query->prepare()->execute();
        $query = $this->handler->createDeleteQuery();
        $query
            ->deleteFrom( $this->handler->quoteTable( 'ezpolicy_limitation_value' ) )
            ->where(
                $query->expr->in( $this->handler->quoteColumn( 'id' ), array_unique( $values ) )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::updateRole (RoleUpdateStruct $role)
Update role
Parameters
\eZ\Publish\SPI\Persistence\User\RoleUpdateStruct $role
Reimplemented from eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway.
Definition at line 459 of file EzcDatabase.php.
    {
        $query = $this->handler->createUpdateQuery();
        $query
            ->update( $this->handler->quoteTable( 'ezrole' ) )
            ->set(
                $this->handler->quoteColumn( 'name' ),
                $query->bindValue( $role->identifier )
            )->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'id' ),
                    $query->bindValue( $role->id, null, \PDO::PARAM_INT )
                )
            );
        $query->prepare()->execute();
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::$handler protected
Definition at line 28 of file EzcDatabase.php.
const eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\EzcDatabase::GROUP_TYPE_ID = 3
Internal type ID for user groups
Definition at line 33 of file EzcDatabase.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/EzcDatabase.php