ezp-next: eZ\Publish\Core\FieldType\BinaryBase\MimeTypeDetector\FileInfoDetector Class Reference
eZ\Publish\Core\FieldType\BinaryBase\MimeTypeDetector\FileInfoDetector Class Reference
Public Member Functions
__construct ()
getMimeType ($path)
Protected Member Functions
getFileInfo ()
Protected Attributes
$fileInfo
Detailed Description
Definition at line 14 of file FileInfoDetector.php.
Constructor & Destructor Documentation
eZ\Publish\Core\FieldType\BinaryBase\MimeTypeDetector\FileInfoDetector::__construct ()
Checks for the required ext/fileinfo
Definition at line 26 of file FileInfoDetector.php.
References eZ\Publish\Core\FieldType\BinaryBase\MimeTypeDetector\FileInfoDetector\__construct().
    {
        // Enabled by default since 5.3. Still checking if someone disabled
        // manually.
        if ( !extension_loaded( 'fileinfo' ) )
        {
            throw new \RuntimeException( 'The extension "ext/fileinfo" must be loaded in order for this class to work.' );
        }
    }
Member Function Documentation
eZ\Publish\Core\FieldType\BinaryBase\MimeTypeDetector\FileInfoDetector::getFileInfo () protected
Creates a new (or re-uses) finfo object and returns it
Returns
Definition at line 53 of file FileInfoDetector.php.
References eZ\Publish\Core\FieldType\BinaryBase\MimeTypeDetector\FileInfoDetector\getFileInfo().
    {
        if ( !isset( $this->fileInfo ) )
        {
            $this->fileInfo = new \finfo( FILEINFO_MIME_TYPE );
        }
        return $this->fileInfo;
    }
eZ\Publish\Core\FieldType\BinaryBase\MimeTypeDetector\FileInfoDetector::getMimeType ($path)
Returns the MIME type of the file identified by $path
Parameters
string $path
Returns
string
Implements eZ\Publish\Core\FieldType\BinaryBase\MimeTypeDetector.
Definition at line 43 of file FileInfoDetector.php.
References eZ\Publish\Core\FieldType\BinaryBase\MimeTypeDetector\FileInfoDetector\getFileInfo().
    {
        return $this->getFileInfo()->file( $path );
    }
Member Data Documentation
eZ\Publish\Core\FieldType\BinaryBase\MimeTypeDetector\FileInfoDetector::$fileInfo protected
Definition at line 21 of file FileInfoDetector.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/BinaryBase/MimeTypeDetector/FileInfoDetector.php