ezp-next: eZ\Publish\Core\REST\Common\Output\Generator\Json Class Reference
eZ\Publish\Core\REST\Common\Output\Generator\Json Class Reference
Public Member Functions
__construct (Json\FieldTypeHashGenerator $fieldTypeHashGenerator)
startDocument ($data)
isEmpty ()
endDocument ($data)
startObjectElement ($name, $mediaTypeName=null)
endObjectElement ($name)
startHashElement ($name)
endHashElement ($name)
startValueElement ($name, $value, $attributes=array())
endValueElement ($name)
startList ($name)
endList ($name)
startAttribute ($name, $value)
endAttribute ($name)
getMediaType ($name)
generateFieldTypeHash ($hashElementName, $hashValue)
Public Member Functions inherited from eZ\Publish\Core\REST\Common\Output\Generator
reset ()
startValueElement ($name, $value)
Protected Member Functions
convertArrayObjects ($data)
Protected Member Functions inherited from eZ\Publish\Core\REST\Common\Output\Generator
checkStartDocument ($data)
checkEndDocument ($data)
checkStartObjectElement ($data)
checkEndObjectElement ($data)
checkStartHashElement ($data)
checkEndHashElement ($data)
checkStartValueElement ($data)
checkEndValueElement ($data)
checkStartList ($data)
checkEndList ($data)
checkStartAttribute ($data)
checkEndAttribute ($data)
generateMediaType ($name, $type)
checkStart ($type, $data, array $validParents)
checkEnd ($type, $data)
Protected Attributes
$json
$fieldTypeHashGenerator
$isEmpty = true
Protected Attributes inherited from eZ\Publish\Core\REST\Common\Output\Generator
$stack = array()
Detailed Description
Json generator
Definition at line 17 of file Json.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Common\Output\Generator\Json::__construct (Json\FieldTypeHashGenerator $fieldTypeHashGenerator)
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator $fieldTypeHashGenerator
Definition at line 43 of file Json.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Json\__construct().
    {
        $this->fieldTypeHashGenerator = $fieldTypeHashGenerator;
    }
Member Function Documentation
eZ\Publish\Core\REST\Common\Output\Generator\Json::convertArrayObjects ($data) protected
Convert ArrayObjects to arrays
Recursively convert all ArrayObjects into arrays in the full data structure.
Parameters
mixed $data
Returns
mixed
Definition at line 99 of file Json.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Json\convertArrayObjects().
    {
        if ( $data instanceof Json\ArrayObject )
        {
            // @todo: Check if we need to convert arrays with only one single
            // element into non-arrays /cc cba
            $data = $data->getArrayCopy();
            foreach ( $data as $key => $value )
            {
                $data[$key] = $this->convertArrayObjects( $value );
            }
        }
        else if ( $data instanceof Json\Object )
        {
            foreach ( $data as $key => $value )
            {
                $data->$key = $this->convertArrayObjects( $value );
            }
        }
        return $data;
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::endAttribute ($name)
End attribute
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 294 of file Json.php.
    {
        $this->checkEndAttribute( $name );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::endDocument ($data)
End document
Returns the generated document as a string.
Parameters
mixed $data
Returns
string
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 81 of file Json.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEndDocument(), and eZ\Publish\Core\REST\Common\Output\Generator\Json\convertArrayObjects().
    {
        $this->checkEndDocument( $data );
        $this->json = $this->convertArrayObjects( $this->json );
        return json_encode( $this->json );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::endHashElement ($name)
End hash element
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 195 of file Json.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEndHashElement().
    {
        $this->checkEndHashElement( $name );
        $this->json = $this->json->getParent();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::endList ($name)
End list
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 269 of file Json.php.
    {
        $this->checkEndList( $name );
        $this->json = $this->json->getParent();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::endObjectElement ($name)
End object element
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 158 of file Json.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEndObjectElement().
    {
        $this->checkEndObjectElement( $name );
        $this->json = $this->json->getParent();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::endValueElement ($name)
End value element
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 244 of file Json.php.
    {
        $this->checkEndValueElement( $name );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::generateFieldTypeHash ($hashElementName, $hashValue)
Generates a generic representation of the scalar, hash or list given in $hashValue into the document, using an element of $hashElementName as its parent
Parameters
string $hashElementName
mixed $hashValue
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 319 of file Json.php.
    {
        $this->fieldTypeHashGenerator->generateHashValue(
            $this->json,
            $hashElementName,
            $hashValue
        );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::getMediaType ($name)
Get media type
Parameters
string $name
Returns
string
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 306 of file Json.php.
    {
        return $this->generateMediaType( $name, 'json' );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::isEmpty ()
Returns if the document is empty or already contains data
Returns
boolean
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 67 of file Json.php.
    {
        return $this->isEmpty;
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::startAttribute ($name, $value)
Start attribute
Parameters
string $name
string $value
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 282 of file Json.php.
    {
        $this->checkStartAttribute( $name );
        $this->json->{'_' . $name} = $value;
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::startDocument ($data)
Start document
Parameters
mixed $data
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 53 of file Json.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStartDocument(), and eZ\Publish\Core\REST\Common\Output\Generator\isEmpty().
    {
        $this->checkStartDocument( $data );
        $this->isEmpty = true;
        $this->json = new Json\Object();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::startHashElement ($name)
Start hash element
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 170 of file Json.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStartHashElement(), and eZ\Publish\Core\REST\Common\Output\Generator\isEmpty().
    {
        $this->checkStartHashElement( $name );
        $this->isEmpty = false;
        $object = new Json\Object( $this->json );
        if ( $this->json instanceof Json\ArrayObject )
        {
            $this->json[] = $object;
            $this->json = $object;
        }
        else
        {
            $this->json->$name = $object;
            $this->json = $object;
        }
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::startList ($name)
Start list
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 254 of file Json.php.
    {
        $this->checkStartList( $name );
        $array = new Json\ArrayObject( $this->json );
        $this->json->$name = $array;
        $this->json = $array;
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::startObjectElement ($name, $mediaTypeName = null)
Start object element
Parameters
string $name
string $mediaTypeName
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 128 of file Json.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStartObjectElement(), eZ\Publish\Core\REST\Common\Output\Generator\endAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\getMediaType(), eZ\Publish\Core\REST\Common\Output\Generator\isEmpty(), and eZ\Publish\Core\REST\Common\Output\Generator\startAttribute().
    {
        $this->checkStartObjectElement( $name );
        $this->isEmpty = false;
        $mediaTypeName = $mediaTypeName ?: $name;
        $object = new Json\Object( $this->json );
        if ( $this->json instanceof Json\ArrayObject )
        {
            $this->json[] = $object;
            $this->json = $object;
        }
        else
        {
            $this->json->$name = $object;
            $this->json = $object;
        }
        $this->startAttribute( "media-type", $this->getMediaType( $mediaTypeName ) );
        $this->endAttribute( "media-type" );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json::startValueElement ($name, $value, $attributes = array())
Start value element
Parameters
string $name
string $value
array $attributes
Definition at line 209 of file Json.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStartValueElement().
    {
        $this->checkStartValueElement( $name );
        $jsonValue = null;
        if ( empty( $attributes ) )
        {
            $jsonValue = $value;
        }
        else
        {
            $jsonValue = new Json\Object( $this->json );
            foreach ( $attributes as $attributeName => $attributeValue )
            {
                $jsonValue->{'_' . $attributeName} = $attributeValue;
            }
            $jsonValue->{'#text'} = $value;
        }
        if ( $this->json instanceof Json\ArrayObject )
        {
            $this->json[] = $jsonValue;
        }
        else
        {
            $this->json->$name = $jsonValue;
        }
    }
Member Data Documentation
eZ\Publish\Core\REST\Common\Output\Generator\Json::$fieldTypeHashGenerator protected
Definition at line 31 of file Json.php.
eZ\Publish\Core\REST\Common\Output\Generator\Json::$isEmpty = true protected
Definition at line 38 of file Json.php.
eZ\Publish\Core\REST\Common\Output\Generator\Json::$json protected
Definition at line 24 of file Json.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/Output/Generator/Json.php