ezp-next: eZ\Publish\Core\Repository\UserService Class Reference
eZ\Publish\Core\Repository\UserService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, Handler $userHandler, array $settings=array())
createUserGroup (APIUserGroupCreateStruct $userGroupCreateStruct, APIUserGroup $parentGroup)
loadUserGroup ($id)
loadSubUserGroups (APIUserGroup $userGroup)
deleteUserGroup (APIUserGroup $userGroup)
moveUserGroup (APIUserGroup $userGroup, APIUserGroup $newParent)
updateUserGroup (APIUserGroup $userGroup, UserGroupUpdateStruct $userGroupUpdateStruct)
createUser (APIUserCreateStruct $userCreateStruct, array $parentGroups)
loadAnonymousUser ()
loadUserByCredentials ($login, $password)
deleteUser (APIUser $user)
updateUser (APIUser $user, UserUpdateStruct $userUpdateStruct)
assignUserToUserGroup (APIUser $user, APIUserGroup $userGroup)
unAssignUserFromUserGroup (APIUser $user, APIUserGroup $userGroup)
loadUserGroupsOfUser (APIUser $user)
loadUsersOfUserGroup (APIUserGroup $userGroup, $offset=0, $limit=-1)
newUserCreateStruct ($login, $email, $password, $mainLanguageCode, $contentType=null)
newUserGroupCreateStruct ($mainLanguageCode, $contentType=null)
newUserUpdateStruct ()
newUserGroupUpdateStruct ()
Public Member Functions inherited from eZ\Publish\API\Repository\UserService
createUserGroup (UserGroupCreateStruct $userGroupCreateStruct, UserGroup $parentGroup)
loadSubUserGroups (UserGroup $userGroup)
deleteUserGroup (UserGroup $userGroup)
moveUserGroup (UserGroup $userGroup, UserGroup $newParent)
updateUserGroup (UserGroup $userGroup, UserGroupUpdateStruct $userGroupUpdateStruct)
createUser (UserCreateStruct $userCreateStruct, array $parentGroups)
loadUser ($userId)
deleteUser (User $user)
updateUser (User $user, UserUpdateStruct $userUpdateStruct)
assignUserToUserGroup (User $user, UserGroup $userGroup)
unAssignUserFromUserGroup (User $user, UserGroup $userGroup)
loadUserGroupsOfUser (User $user)
loadUsersOfUserGroup (UserGroup $userGroup, $offset=0, $limit=-1)
Protected Member Functions
searchSubGroups ($locationId, $sortField=null, $sortOrder=Location::SORT_ORDER_ASC, $offset=0, $limit=-1)
buildDomainUserGroupObject (APIContent $content)
buildDomainUserObject (SPIUser $spiUser, APIContent $content=null)
createPasswordHash ($login, $password, $site, $type)
getSortClauseBySortField ($sortField, $sortOrder=Location::SORT_ORDER_ASC)
Protected Attributes
$repository
$userHandler
$settings
Detailed Description
Definition at line 51 of file UserService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\UserService::__construct (RepositoryInterface $repository, Handler $userHandler, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\API\Repository\Repository $repository
\eZ\Publish\SPI\Persistence\User\Handler $userHandler
array $settings
Definition at line 75 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\$repository, eZ\Publish\Core\Repository\UserService\$settings, and eZ\Publish\Core\Repository\UserService\$userHandler.
    {
        $this->repository = $repository;
        $this->userHandler = $userHandler;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            'anonymousUserID' => 10,
            'defaultUserPlacement' => 12,
            'userClassID' => 4,// @todo Rename this settings to swap out "Class" for "Type"
            'userGroupClassID' => 3,
            'hashType' => User::PASSWORD_HASH_MD5_USER,
            'siteName' => 'ez.no'
        );
    }
Member Function Documentation
eZ\Publish\Core\Repository\UserService::assignUserToUserGroup (APIUser $user, APIUserGroup $userGroup)
Assigns a new user group to the user
Parameters
\eZ\Publish\API\Repository\Values\User\User $user
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to assign the user group to the user
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the user is already in the given user group
Definition at line 800 of file UserService.php.
References eZ\Publish\API\Repository\UserService\loadUser(), and eZ\Publish\Core\Repository\UserService\loadUserGroup().
    {
        if ( !is_numeric( $user->id ) )
            throw new InvalidArgumentValue( "id", $user->id, "User" );
        if ( !is_numeric( $userGroup->id ) )
            throw new InvalidArgumentValue( "id", $userGroup->id, "UserGroup" );
        $loadedUser = $this->loadUser( $user->id );
        $loadedGroup = $this->loadUserGroup( $userGroup->id );
        $locationService = $this->repository->getLocationService();
        $existingGroupIds = array();
        $userLocations = $locationService->loadLocations( $loadedUser->getVersionInfo()->getContentInfo() );
        foreach ( $userLocations as $userLocation )
        {
            $existingGroupIds[] = $userLocation->parentLocationId;
        }
        if ( $loadedGroup->getVersionInfo()->getContentInfo()->mainLocationId === null )
        {
            throw new BadStateException( "userGroup", "user group has no main location or no locations" );
        }
        if ( in_array( $loadedGroup->getVersionInfo()->getContentInfo()->mainLocationId, $existingGroupIds ) )
        {
            // user is already assigned to the user group
            throw new InvalidArgumentException( "user", "user is already in the given user group" );
        }
        $locationCreateStruct = $locationService->newLocationCreateStruct(
            $loadedGroup->getVersionInfo()->getContentInfo()->mainLocationId
        );
        $this->repository->beginTransaction();
        try
        {
            $locationService->createLocation(
                $loadedUser->getVersionInfo()->getContentInfo(),
                $locationCreateStruct
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\UserService::buildDomainUserGroupObject (APIContent $content) protected
Builds the domain UserGroup object from provided Content object
Parameters
\eZ\Publish\API\Repository\Values\Content\Content $content
Returns
Definition at line 1089 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\searchSubGroups(), and eZ\Publish\API\Repository\Values\Content\Location\SORT_ORDER_ASC.
    {
        $locationService = $this->repository->getLocationService();
        $subGroupCount = 0;
        if ( $content->getVersionInfo()->getContentInfo()->mainLocationId !== null )
        {
            $mainLocation = $locationService->loadLocation(
                $content->getVersionInfo()->getContentInfo()->mainLocationId
            );
            $parentLocation = $locationService->loadLocation( $mainLocation->parentLocationId );
            $subGroups = $this->searchSubGroups( $mainLocation->id, null, Location::SORT_ORDER_ASC, 0, 0 );
            $subGroupCount = $subGroups->totalCount;
        }
        return new UserGroup(
            array(
                'content' => $content,
                'parentId' => isset( $parentLocation ) ? $parentLocation->contentId : null,
                'subGroupCount' => $subGroupCount
            )
        );
    }
eZ\Publish\Core\Repository\UserService::buildDomainUserObject (SPIUser $spiUser, APIContent $content = null) protected
Builds the domain user object from provided persistence user object
Parameters
\eZ\Publish\SPI\Persistence\User $spiUser
\eZ\Publish\API\Repository\Values\Content\Content | null $content
Returns
Definition at line 1121 of file UserService.php.
    {
        if ( $content === null )
            $content = $this->repository->getContentService()->internalLoadContent( $spiUser->id );
        return new User(
            array(
                'content' => $content,
                'login' => $spiUser->login,
                'email' => $spiUser->email,
                'passwordHash' => $spiUser->passwordHash,
                'hashAlgorithm' => (int)$spiUser->hashAlgorithm,
                'enabled' => $spiUser->isEnabled,
                'maxLogin' => (int)$spiUser->maxLogin,
            )
        );
    }
eZ\Publish\Core\Repository\UserService::createPasswordHash ($login, $password, $site, $type) protected
Returns password hash based on user data and site settings
Parameters
string $login User login
string $password User password
string $site The name of the site
int $type Type of password to generate
Returns
string Generated password hash
Definition at line 1149 of file UserService.php.
    {
        switch ( $type )
        {
            case User::PASSWORD_HASH_MD5_PASSWORD:
                return md5( $password );
            case User::PASSWORD_HASH_MD5_USER:
                return md5( "$login\n$password" );
            case User::PASSWORD_HASH_MD5_SITE:
                return md5( "$login\n$password\n$site" );
            case User::PASSWORD_HASH_PLAINTEXT:
                return $password;
            default:
                return md5( $password );
        }
    }
eZ\Publish\Core\Repository\UserService::createUser (APIUserCreateStruct $userCreateStruct, array $parentGroups)
Create a new user. The created user is published by this method
Parameters
\eZ\Publish\API\Repository\Values\User\UserCreateStruct $userCreateStruct the data used for creating the user
\eZ\Publish\API\Repository\Values\User\UserGroup[] $parentGroups the groups which are assigned to the user after creation
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to move the user group
\eZ\Publish\API\Repository\Exceptions\ContentFieldValidationException if a field in the $userCreateStruct is not valid
\eZ\Publish\API\Repository\Exceptions\ContentValidationException if a required field is missing or set to an empty value
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if a user with provided login already exists
Definition at line 402 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\buildDomainUserObject(), and eZ\Publish\Core\Repository\UserService\loadUserGroup().
    {
        if ( empty( $parentGroups ) )
            throw new InvalidArgumentValue( "parentGroups", $parentGroups );
        if ( !is_string( $userCreateStruct->login ) || empty( $userCreateStruct->login ) )
            throw new InvalidArgumentValue( "login", $userCreateStruct->login, "UserCreateStruct" );
        if ( !is_string( $userCreateStruct->email ) || empty( $userCreateStruct->email ) )
            throw new InvalidArgumentValue( "email", $userCreateStruct->email, "UserCreateStruct" );
        if ( !ezcMailTools::validateEmailAddress( $userCreateStruct->email ) )
            throw new InvalidArgumentValue( "email", $userCreateStruct->email, "UserCreateStruct" );
        if ( !is_string( $userCreateStruct->password ) || empty( $userCreateStruct->password ) )
            throw new InvalidArgumentValue( "password", $userCreateStruct->password, "UserCreateStruct" );
        if ( !is_bool( $userCreateStruct->enabled ) )
            throw new InvalidArgumentValue( "enabled", $userCreateStruct->enabled, "UserCreateStruct" );
        try
        {
            $this->userHandler->loadByLogin( $userCreateStruct->login );
            throw new InvalidArgumentException( "userCreateStruct", "User with provided login already exists" );
        }
        catch ( NotFoundException $e )
        {
            // Do nothing
        }
        $contentService = $this->repository->getContentService();
        $locationService = $this->repository->getLocationService();
        $contentTypeService = $this->repository->getContentTypeService();
        if ( $userCreateStruct->contentType === null )
        {
            $userContentType = $contentTypeService->loadContentType( $this->settings['userClassID'] );
            $userCreateStruct->contentType = $userContentType;
        }
        $locationCreateStructs = array();
        foreach ( $parentGroups as $parentGroup )
        {
            $parentGroup = $this->loadUserGroup( $parentGroup->id );
            if ( $parentGroup->getVersionInfo()->getContentInfo()->mainLocationId !== null )
            {
                $locationCreateStructs[] = $locationService->newLocationCreateStruct(
                    $parentGroup->getVersionInfo()->getContentInfo()->mainLocationId
                );
            }
        }
        // Search for the first ezuser field type in content type
        $userFieldDefinition = null;
        foreach ( $userCreateStruct->contentType->getFieldDefinitions() as $fieldDefinition )
        {
            if ( $fieldDefinition->fieldTypeIdentifier == 'ezuser' )
            {
                $userFieldDefinition = $fieldDefinition;
                break;
            }
        }
        if ( $userFieldDefinition === null )
        {
            throw new ContentValidationException( "Provided content type does not contain ezuser field type" );
        }
        $fixUserFieldType = true;
        foreach ( $userCreateStruct->fields as $index => $field )
        {
            if ( $field->fieldDefIdentifier == $userFieldDefinition->identifier )
            {
                if ( $field->value instanceof UserValue )
                {
                    $userCreateStruct->fields[$index]->value->login = $userCreateStruct->login;
                }
                else
                {
                    $userCreateStruct->fields[$index]->value = new UserValue(
                        array(
                            'login' => $userCreateStruct->login
                        )
                    );
                }
                $fixUserFieldType = false;
            }
        }
        if ( $fixUserFieldType )
        {
            $userCreateStruct->setField(
                $userFieldDefinition->identifier,
                new UserValue(
                    array(
                        'login' => $userCreateStruct->login
                    )
                )
            );
        }
        $this->repository->beginTransaction();
        try
        {
            $contentDraft = $contentService->createContent( $userCreateStruct, $locationCreateStructs );
            $publishedContent = $contentService->publishVersion( $contentDraft->getVersionInfo() );
            $spiUser = $this->userHandler->create(
                new SPIUser(
                    array(
                        'id' => $publishedContent->id,
                        'login' => $userCreateStruct->login,
                        'email' => $userCreateStruct->email,
                        'passwordHash' => $this->createPasswordHash(
                            $userCreateStruct->login,
                            $userCreateStruct->password,
                            $this->settings['siteName'],
                            $this->settings['hashType']
                        ),
                        'hashAlgorithm' => $this->settings['hashType'],
                        'isEnabled' => $userCreateStruct->enabled,
                        'maxLogin' => 0
                    )
                )
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainUserObject(
            $spiUser,
            $contentService->loadContent( $publishedContent->id )// Reload to get with updated user field value
        );
    }
eZ\Publish\Core\Repository\UserService::createUserGroup (APIUserGroupCreateStruct $userGroupCreateStruct, APIUserGroup $parentGroup)
Creates a new user group using the data provided in the ContentCreateStruct parameter
In 4.x in the content type parameter in the profile is ignored
the content type is determined via configuration and can be set to null. The returned version is published.
Parameters
\eZ\Publish\API\Repository\Values\User\UserGroupCreateStruct $userGroupCreateStruct a structure for setting all necessary data to create this user group
\eZ\Publish\API\Repository\Values\User\UserGroup $parentGroup
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to create a user group
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the input structure has invalid data
\eZ\Publish\API\Repository\Exceptions\ContentFieldValidationException if a field in the $userGroupCreateStruct is not valid
\eZ\Publish\API\Repository\Exceptions\ContentValidationException if a required field is missing or set to an empty value
Definition at line 107 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\buildDomainUserGroupObject(), and eZ\Publish\Core\Repository\UserService\loadUserGroup().
    {
        if ( !is_numeric( $parentGroup->id ) )
            throw new InvalidArgumentValue( "id", $parentGroup->id, "UserGroup" );
        $contentService = $this->repository->getContentService();
        $locationService = $this->repository->getLocationService();
        $contentTypeService = $this->repository->getContentTypeService();
        if ( $userGroupCreateStruct->contentType === null )
        {
            $userGroupContentType = $contentTypeService->loadContentType( $this->settings['userGroupClassID'] );
            $userGroupCreateStruct->contentType = $userGroupContentType;
        }
        $loadedParentGroup = $this->loadUserGroup( $parentGroup->id );
        if ( $loadedParentGroup->getVersionInfo()->getContentInfo()->mainLocationId === null )
            throw new InvalidArgumentException( "parentGroup", "parent user group has no main location" );
        $locationCreateStruct = $locationService->newLocationCreateStruct(
            $loadedParentGroup->getVersionInfo()->getContentInfo()->mainLocationId
        );
        $this->repository->beginTransaction();
        try
        {
            $contentDraft = $contentService->createContent( $userGroupCreateStruct, array( $locationCreateStruct ) );
            $publishedContent = $contentService->publishVersion( $contentDraft->getVersionInfo() );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainUserGroupObject( $publishedContent );
    }
eZ\Publish\Core\Repository\UserService::deleteUser (APIUser $user)
This method deletes a user
Parameters
\eZ\Publish\API\Repository\Values\User\User $user
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to delete the user
Definition at line 653 of file UserService.php.
References eZ\Publish\API\Repository\UserService\loadUser().
    {
        if ( !is_numeric( $user->id ) )
            throw new InvalidArgumentValue( "id", $user->id, "User" );
        $loadedUser = $this->loadUser( $user->id );
        $this->repository->beginTransaction();
        try
        {
            $this->repository->getContentService()->deleteContent( $loadedUser->getVersionInfo()->getContentInfo() );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\UserService::deleteUserGroup (APIUserGroup $userGroup)
Removes a user group
the users which are not assigned to other groups will be deleted.
Parameters
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to create a user group
Definition at line 255 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\loadUserGroup().
    {
        if ( !is_numeric( $userGroup->id ) )
            throw new InvalidArgumentValue( "id", $userGroup->id, "UserGroup" );
        $loadedUserGroup = $this->loadUserGroup( $userGroup->id );
        $this->repository->beginTransaction();
        try
        {
            //@todo: what happens to sub user groups and users below sub user groups
            $this->repository->getContentService()->deleteContent( $loadedUserGroup->getVersionInfo()->getContentInfo() );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\UserService::getSortClauseBySortField ($sortField, $sortOrder = Location::SORT_ORDER_ASC) protected
Instantiates a correct sort clause object based on provided location sort field and sort order
Parameters
int $sortField
int $sortOrder
Returns
Definition at line 1178 of file UserService.php.
References eZ\Publish\API\Repository\Values\Content\Query\SORT_ASC, eZ\Publish\API\Repository\Values\Content\Query\SORT_DESC, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_DEPTH, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_MODIFIED, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_NAME, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_PATH, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_PRIORITY, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_PUBLISHED, eZ\Publish\API\Repository\Values\Content\Location\SORT_FIELD_SECTION, and eZ\Publish\API\Repository\Values\Content\Location\SORT_ORDER_DESC.
    {
        $sortOrder = $sortOrder == Location::SORT_ORDER_DESC ? Query::SORT_DESC : Query::SORT_ASC;
        switch ( $sortField )
        {
            case Location::SORT_FIELD_PATH:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\LocationPathString( $sortOrder );
            case Location::SORT_FIELD_PUBLISHED:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\DatePublished( $sortOrder );
            case Location::SORT_FIELD_MODIFIED:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\DateModified( $sortOrder );
            case Location::SORT_FIELD_SECTION:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\SectionIdentifier( $sortOrder );
            case Location::SORT_FIELD_DEPTH:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\LocationDepth( $sortOrder );
            //@todo: enable
            // case APILocation::SORT_FIELD_CLASS_IDENTIFIER:
            //@todo: enable
            // case APILocation::SORT_FIELD_CLASS_NAME:
            case Location::SORT_FIELD_PRIORITY:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\LocationPriority( $sortOrder );
            case Location::SORT_FIELD_NAME:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\ContentName( $sortOrder );
            //@todo: enable
            // case APILocation::SORT_FIELD_MODIFIED_SUBNODE:
            //@todo: enable
            // case APILocation::SORT_FIELD_NODE_ID:
            //@todo: enable
            // case APILocation::SORT_FIELD_CONTENTOBJECT_ID:
            default:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\LocationPathString( $sortOrder );
        }
    }
eZ\Publish\Core\Repository\UserService::loadAnonymousUser ()
Loads anonymous user
loadUser()
Returns
Implements eZ\Publish\API\Repository\UserService.
Definition at line 594 of file UserService.php.
References eZ\Publish\API\Repository\UserService\loadUser().
    {
        return $this->loadUser( $this->settings['anonymousUserID'] );
    }
eZ\Publish\Core\Repository\UserService::loadSubUserGroups (APIUserGroup $userGroup)
Loads the sub groups of a user group
Parameters
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
Returns
[]
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read the user group
Definition at line 176 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\buildDomainUserGroupObject(), eZ\Publish\Core\Repository\UserService\loadUserGroup(), and eZ\Publish\Core\Repository\UserService\searchSubGroups().
    {
        if ( !is_numeric( $userGroup->id ) )
            throw new InvalidArgumentValue( "id", $userGroup->id, "UserGroup" );
        $locationService = $this->repository->getLocationService();
        $loadedUserGroup = $this->loadUserGroup( $userGroup->id );
        if ( !$this->repository->canUser( 'content', 'read', $loadedUserGroup ) )
            throw new UnauthorizedException( 'content', 'read' );
        if ( $loadedUserGroup->getVersionInfo()->getContentInfo()->mainLocationId === null )
            return array();
        $mainGroupLocation = $locationService->loadLocation(
            $loadedUserGroup->getVersionInfo()->getContentInfo()->mainLocationId
        );
        $searchResult = $this->searchSubGroups(
            $mainGroupLocation->id,
            $mainGroupLocation->sortField,
            $mainGroupLocation->sortOrder
        );
        if ( $searchResult->totalCount == 0 )
            return array();
        $subUserGroups = array();
        foreach ( $searchResult->searchHits as $searchHit )
        {
            $subUserGroups[] = $this->buildDomainUserGroupObject( $searchHit->valueObject );
        }
        return $subUserGroups;
    }
eZ\Publish\Core\Repository\UserService::loadUserByCredentials ($login, $password)
Loads a user for the given login and password
Parameters
string $login
string $password the plain password
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if a user with the given credentials was not found
\eZ\Publish\API\Repository\Exceptions\BadStateException if multiple users with same login were found
Implements eZ\Publish\API\Repository\UserService.
Definition at line 610 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\buildDomainUserObject(), and eZ\Publish\Core\Repository\UserService\createPasswordHash().
    {
        if ( !is_string( $login ) || empty( $login ) )
            throw new InvalidArgumentValue( "login", $login );
        if ( !is_string( $password ) || empty( $password ) )
            throw new InvalidArgumentValue( "password", $password );
        // Randomize login time to protect against timing attacks
        usleep( mt_rand( 0, 30000 ) );
        $spiUsers = $this->userHandler->loadByLogin( $login );
        if ( empty( $spiUsers ) )
            throw new NotFoundException( "user", $login );
        if ( count( $spiUsers ) > 1 )
        {
            // something went wrong, we should not have more than one
            // user with the same login
            throw new BadStateException( "login", 'found several users with same login' );
        }
        $passwordHash = $this->createPasswordHash(
            $login,
            $password,
            $this->settings['siteName'],
            $spiUsers[0]->hashAlgorithm
        );
        if ( $spiUsers[0]->passwordHash !== $passwordHash )
            throw new NotFoundException( "user", $login );
        return $this->buildDomainUserObject( $spiUsers[0] );
    }
eZ\Publish\Core\Repository\UserService::loadUserGroup ($id)
Loads a user group for the given id
Parameters
int $id
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to create a user group
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the user group with the given id was not found
Implements eZ\Publish\API\Repository\UserService.
Definition at line 157 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\buildDomainUserGroupObject().
    {
        if ( !is_numeric( $id ) )
            throw new InvalidArgumentValue( "id", $id );
        $content = $this->repository->getContentService()->loadContent( $id );
        return $this->buildDomainUserGroupObject( $content );
    }
eZ\Publish\Core\Repository\UserService::loadUserGroupsOfUser (APIUser $user)
Loads the user groups the user belongs to
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed read the user or user group
Parameters
\eZ\Publish\API\Repository\Values\User\User $user
Returns
[]
Definition at line 909 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\buildDomainUserGroupObject().
    {
        $locationService = $this->repository->getLocationService();
        if ( !$this->repository->canUser( 'content', 'edit', $user ) )
            throw new UnauthorizedException( 'content', 'edit' );
        $userLocations = $locationService->loadLocations(
            $user->getVersionInfo()->getContentInfo()
        );
        $parentLocationIds = array();
        foreach ( $userLocations as $userLocation )
        {
            if ( $userLocation->parentLocationId !== null )
                $parentLocationIds[] = $userLocation->parentLocationId;
        }
        $searchQuery = new Query();
        $searchQuery->offset = 0;
        $searchQuery->limit = null;
        $searchQuery->criterion = new CriterionLogicalAnd(
            array(
                new CriterionContentTypeId( $this->settings['userGroupClassID'] ),
                new CriterionLocationId( $parentLocationIds ),
                new CriterionStatus( CriterionStatus::STATUS_PUBLISHED )
            )
        );
        $searchResult = $this->repository->getSearchService()->findContent( $searchQuery, array() );
        $userGroups = array();
        foreach ( $searchResult->searchHits as $resultItem )
        {
            $userGroups[] = $this->buildDomainUserGroupObject( $resultItem->valueObject );
        }
        return $userGroups;
    }
eZ\Publish\Core\Repository\UserService::loadUsersOfUserGroup (APIUserGroup $userGroup, $offset = 0, $limit = -1)
Loads the users of a user group
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read the users or user group
Parameters
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
int $offset
int $limit
Returns
[]
Definition at line 962 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\buildDomainUserObject(), eZ\Publish\Core\Repository\UserService\getSortClauseBySortField(), and eZ\Publish\Core\Repository\UserService\loadUserGroup().
    {
        $loadedUserGroup = $this->loadUserGroup( $userGroup->id );
        if ( $loadedUserGroup->getVersionInfo()->getContentInfo()->mainLocationId === null )
            return array();
        $mainGroupLocation = $this->repository->getLocationService()->loadLocation(
            $loadedUserGroup->getVersionInfo()->getContentInfo()->mainLocationId
        );
        $searchQuery = new Query();
        $searchQuery->criterion = new CriterionLogicalAnd(
            array(
                new CriterionContentTypeId( $this->settings['userClassID'] ),
                new CriterionParentLocationId( $mainGroupLocation->id ),
                new CriterionStatus( CriterionStatus::STATUS_PUBLISHED )
            )
        );
        $searchQuery->offset = $offset > 0 ? (int)$offset : 0;
        $searchQuery->limit = $limit >= 1 ? (int)$limit : null;
        $searchQuery->sortClauses = array(
            $this->getSortClauseBySortField( $mainGroupLocation->sortField, $mainGroupLocation->sortOrder )
        );
        $searchResult = $this->repository->getSearchService()->findContent( $searchQuery, array() );
        $users = array();
        foreach ( $searchResult->searchHits as $resultItem )
        {
            $spiUser = $this->userHandler->load( $resultItem->valueObject->id );
            $users[] = $this->buildDomainUserObject( $spiUser, $resultItem->valueObject );
        }
        return $users;
    }
eZ\Publish\Core\Repository\UserService::moveUserGroup (APIUserGroup $userGroup, APIUserGroup $newParent)
Moves the user group to another parent
Parameters
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
\eZ\Publish\API\Repository\Values\User\UserGroup $newParent
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to move the user group
Definition at line 284 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\loadUserGroup().
    {
        if ( !is_numeric( $userGroup->id ) )
            throw new InvalidArgumentValue( "id", $userGroup->id, "UserGroup" );
        if ( !is_numeric( $newParent->id ) )
            throw new InvalidArgumentValue( "id", $newParent->id, "UserGroup" );
        $loadedUserGroup = $this->loadUserGroup( $userGroup->id );
        $loadedNewParent = $this->loadUserGroup( $newParent->id );
        $locationService = $this->repository->getLocationService();
        if ( $loadedUserGroup->getVersionInfo()->getContentInfo()->mainLocationId === null )
            throw new BadStateException( "userGroup", 'existing user group is not stored and/or does not have any location yet' );
        if ( $loadedNewParent->getVersionInfo()->getContentInfo()->mainLocationId === null )
            throw new BadStateException( "newParent", 'new user group is not stored and/or does not have any location yet' );
        $userGroupMainLocation = $locationService->loadLocation(
            $loadedUserGroup->getVersionInfo()->getContentInfo()->mainLocationId
        );
        $newParentMainLocation = $locationService->loadLocation(
            $loadedNewParent->getVersionInfo()->getContentInfo()->mainLocationId
        );
        $this->repository->beginTransaction();
        try
        {
            $locationService->moveSubtree( $userGroupMainLocation, $newParentMainLocation );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\UserService::newUserCreateStruct ($login, $email, $password, $mainLanguageCode, $contentType = null)
Instantiate a user create class
Parameters
string $login the login of the new user
string $email the email of the new user
string $password the plain password of the new user
string $mainLanguageCode the main language for the underlying content object
\eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType 5.x the content type for the underlying content object. In 4.x it is ignored and taken from the configuration
Returns
Implements eZ\Publish\API\Repository\UserService.
Definition at line 1014 of file UserService.php.
    {
        if ( $contentType === null )
        {
            $contentType = $this->repository->getContentTypeService()->loadContentType(
                $this->settings['userClassID']
            );
        }
        return new UserCreateStruct(
            array(
                'contentType' => $contentType,
                'mainLanguageCode' => $mainLanguageCode,
                'login' => $login,
                'email' => $email,
                'password' => $password,
                'enabled' => true,
                'fields' => array(),
            )
        );
    }
eZ\Publish\Core\Repository\UserService::newUserGroupCreateStruct ($mainLanguageCode, $contentType = null)
Instantiate a user group create class
Parameters
string $mainLanguageCode The main language for the underlying content object
null | \eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType 5.x the content type for the underlying content object. In 4.x it is ignored and taken from the configuration
Returns
Implements eZ\Publish\API\Repository\UserService.
Definition at line 1044 of file UserService.php.
    {
        if ( $contentType === null )
        {
            $contentType = $this->repository->getContentTypeService()->loadContentType(
                $this->settings['userGroupClassID']
            );
        }
        return new UserGroupCreateStruct(
            array(
                'contentType' => $contentType,
                'mainLanguageCode' => $mainLanguageCode,
                'fields' => array(),
            )
        );
    }
eZ\Publish\Core\Repository\UserService::newUserGroupUpdateStruct ()
Instantiate a new user group update struct
Returns
Implements eZ\Publish\API\Repository\UserService.
Definition at line 1077 of file UserService.php.
    {
        return new UserGroupUpdateStruct();
    }
eZ\Publish\Core\Repository\UserService::newUserUpdateStruct ()
Instantiate a new user update struct
Returns
Implements eZ\Publish\API\Repository\UserService.
Definition at line 1067 of file UserService.php.
    {
        return new UserUpdateStruct();
    }
eZ\Publish\Core\Repository\UserService::searchSubGroups ($locationId, $sortField = null, $sortOrder = Location::SORT_ORDER_ASC, $offset = 0, $limit = -1) protected
Returns (searches) subgroups of a user group described by its main location
Parameters
int $locationId
int | null $sortField
int $sortOrder
int $offset
int $limit
Returns
Definition at line 222 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\getSortClauseBySortField().
    {
        $searchQuery = new Query();
        $searchQuery->offset = $offset >= 0 ? (int)$offset : 0;
        $searchQuery->limit = $limit >= 0 ? (int)$limit  : null;
        $searchQuery->criterion = new CriterionLogicalAnd(
            array(
                new CriterionContentTypeId( $this->settings['userGroupClassID'] ),
                new CriterionParentLocationId( $locationId ),
                new CriterionStatus( CriterionStatus::STATUS_PUBLISHED )
            )
        );
        $sortClause = null;
        if ( $sortField !== null )
            $sortClause = array( $this->getSortClauseBySortField( $sortField, $sortOrder ) );
        $searchQuery->sortClauses = $sortClause;
        return $this->repository->getSearchService()->findContent( $searchQuery, array(), false );
    }
eZ\Publish\Core\Repository\UserService::unAssignUserFromUserGroup (APIUser $user, APIUserGroup $userGroup)
Removes a user group from the user
Parameters
\eZ\Publish\API\Repository\Values\User\User $user
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to remove the user group from the user
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the user is not in the given user group
Definition at line 859 of file UserService.php.
References eZ\Publish\API\Repository\UserService\loadUser(), and eZ\Publish\Core\Repository\UserService\loadUserGroup().
    {
        if ( !is_numeric( $user->id ) )
            throw new InvalidArgumentValue( "id", $user->id, "User" );
        if ( !is_numeric( $userGroup->id ) )
            throw new InvalidArgumentValue( "id", $userGroup->id, "UserGroup" );
        $loadedUser = $this->loadUser( $user->id );
        $loadedGroup = $this->loadUserGroup( $userGroup->id );
        $locationService = $this->repository->getLocationService();
        $userLocations = $locationService->loadLocations( $loadedUser->getVersionInfo()->getContentInfo() );
        if ( empty( $userLocations ) )
            throw new BadStateException( "user", "user has no locations, cannot unassign from group" );
        if ( $loadedGroup->getVersionInfo()->getContentInfo()->mainLocationId === null )
            throw new BadStateException( "userGroup", "user group has no main location or no locations, cannot unassign" );
        foreach ( $userLocations as $userLocation )
        {
            if ( $userLocation->parentLocationId == $loadedGroup->getVersionInfo()->getContentInfo()->mainLocationId )
            {
                $this->repository->beginTransaction();
                try
                {
                    $locationService->deleteLocation( $userLocation );
                    $this->repository->commit();
                    return;
                }
                catch ( \Exception $e )
                {
                    $this->repository->rollback();
                    throw $e;
                }
            }
        }
        throw new InvalidArgumentException( "userGroup", "user is not in the given user group" );
    }
eZ\Publish\Core\Repository\UserService::updateUser (APIUser $user, UserUpdateStruct $userUpdateStruct)
Updates a user
4.x: If the versionUpdateStruct is set in the user update structure, this method internally creates a content draft, updates ts with the provided data and publishes the draft. If a draft is explicitly required, the user group can be updated via the content service methods.
Parameters
\eZ\Publish\API\Repository\Values\User\User $user
\eZ\Publish\API\Repository\Values\User\UserUpdateStruct $userUpdateStruct
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to update the user
\eZ\Publish\API\Repository\Exceptions\ContentFieldValidationException if a field in the $userUpdateStruct is not valid
\eZ\Publish\API\Repository\Exceptions\ContentValidationException if a required field is set empty
Returns
Definition at line 688 of file UserService.php.
References eZ\Publish\API\Repository\UserService\loadUser().
    {
        if ( !is_numeric( $user->id ) )
            throw new InvalidArgumentValue( "id", $user->id, "User" );
        // We need to determine if we have anything to update.
        // UserUpdateStruct is specific as some of the new content is in
        // content update struct and some of it is in additional fields like
        // email, password and so on
        $doUpdate = false;
        foreach ( $userUpdateStruct as $propertyValue )
        {
            if ( $propertyValue !== null )
            {
                $doUpdate = true;
                break;
            }
        }
        if ( !$doUpdate )
        {
            // Nothing to update, so we just quit
            return $user;
        }
        if ( $userUpdateStruct->email !== null )
        {
            if ( !is_string( $userUpdateStruct->email ) || empty( $userUpdateStruct->email ) )
                throw new InvalidArgumentValue( "email", $userUpdateStruct->email, "UserUpdateStruct" );
            if ( !ezcMailTools::validateEmailAddress( $userUpdateStruct->email ) )
                throw new InvalidArgumentValue( "email", $userUpdateStruct->email, "UserUpdateStruct" );
        }
        if ( $userUpdateStruct->password !== null && ( !is_string( $userUpdateStruct->password ) || empty( $userUpdateStruct->password ) ) )
            throw new InvalidArgumentValue( "password", $userUpdateStruct->password, "UserUpdateStruct" );
        if ( $userUpdateStruct->enabled !== null && !is_bool( $userUpdateStruct->enabled ) )
            throw new InvalidArgumentValue( "enabled", $userUpdateStruct->enabled, "UserUpdateStruct" );
        if ( $userUpdateStruct->maxLogin !== null && !is_numeric( $userUpdateStruct->maxLogin ) )
            throw new InvalidArgumentValue( "maxLogin", $userUpdateStruct->maxLogin, "UserUpdateStruct" );
        $contentService = $this->repository->getContentService();
        $loadedUser = $this->loadUser( $user->id );
        if ( !$this->repository->canUser( 'content', 'edit', $loadedUser ) )
            throw new UnauthorizedException( 'content', 'edit' );
        $this->repository->beginTransaction();
        try
        {
            $publishedContent = $loadedUser;
            if ( $userUpdateStruct->contentUpdateStruct !== null )
            {
                $contentDraft = $contentService->createContentDraft( $loadedUser->getVersionInfo()->getContentInfo() );
                $contentDraft = $contentService->updateContent(
                    $contentDraft->getVersionInfo(),
                    $userUpdateStruct->contentUpdateStruct
                );
                $publishedContent = $contentService->publishVersion( $contentDraft->getVersionInfo() );
            }
            if ( $userUpdateStruct->contentMetadataUpdateStruct !== null )
            {
                $contentService->updateContentMetadata(
                    $publishedContent->getVersionInfo()->getContentInfo(),
                    $userUpdateStruct->contentMetadataUpdateStruct
                );
            }
            $this->userHandler->update(
                new SPIUser(
                    array(
                        'id' => $loadedUser->id,
                        'login' => $loadedUser->login,
                        'email' => $userUpdateStruct->email ?: $loadedUser->email,
                        'passwordHash' => $userUpdateStruct->password ?
                            $this->createPasswordHash(
                                $loadedUser->login,
                                $userUpdateStruct->password,
                                $this->settings['siteName'],
                                $this->settings['hashType']
                            ) :
                            $loadedUser->passwordHash,
                        'hashAlgorithm' => $this->settings['hashType'],
                        'isEnabled' => $userUpdateStruct->enabled !== null ? $userUpdateStruct->enabled : $loadedUser->enabled,
                        'maxLogin' => $userUpdateStruct->maxLogin !== null ? (int)$userUpdateStruct->maxLogin : $loadedUser->maxLogin
                    )
                )
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->loadUser( $loadedUser->id );
    }
eZ\Publish\Core\Repository\UserService::updateUserGroup (APIUserGroup $userGroup, UserGroupUpdateStruct $userGroupUpdateStruct)
Updates the group profile with fields and meta data
4.x: If the versionUpdateStruct is set in $userGroupUpdateStruct, this method internally creates a content draft, updates ts with the provided data and publishes the draft. If a draft is explicitly required, the user group can be updated via the content service methods.
Parameters
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
\eZ\Publish\API\Repository\Values\User\UserGroupUpdateStruct $userGroupUpdateStruct
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to update the user group
\eZ\Publish\API\Repository\Exceptions\ContentFieldValidationException if a field in the $userGroupUpdateStruct is not valid
\eZ\Publish\API\Repository\Exceptions\ContentValidationException if a required field is set empty
Definition at line 338 of file UserService.php.
References eZ\Publish\Core\Repository\UserService\buildDomainUserGroupObject(), and eZ\Publish\Core\Repository\UserService\loadUserGroup().
    {
        if ( !is_numeric( $userGroup->id ) )
            throw new InvalidArgumentValue( "id", $userGroup->id, "UserGroup" );
        if ( $userGroupUpdateStruct->contentUpdateStruct === null &&
            $userGroupUpdateStruct->contentMetadataUpdateStruct === null )
        {
            // both update structs are empty, nothing to do
            return $userGroup;
        }
        $contentService = $this->repository->getContentService();
        $loadedUserGroup = $this->loadUserGroup( $userGroup->id );
        $this->repository->beginTransaction();
        try
        {
            $publishedContent = $loadedUserGroup;
            if ( $userGroupUpdateStruct->contentUpdateStruct !== null )
            {
                $contentDraft = $contentService->createContentDraft( $loadedUserGroup->getVersionInfo()->getContentInfo() );
                $contentDraft = $contentService->updateContent(
                    $contentDraft->getVersionInfo(),
                    $userGroupUpdateStruct->contentUpdateStruct
                );
                $publishedContent = $contentService->publishVersion( $contentDraft->getVersionInfo() );
            }
            if ( $userGroupUpdateStruct->contentMetadataUpdateStruct !== null )
            {
                $publishedContent = $contentService->updateContentMetadata(
                    $publishedContent->getVersionInfo()->getContentInfo(),
                    $userGroupUpdateStruct->contentMetadataUpdateStruct
                );
            }
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainUserGroupObject( $publishedContent );
    }
Member Data Documentation
eZ\Publish\Core\Repository\UserService::$repository protected
Definition at line 56 of file UserService.php.
eZ\Publish\Core\Repository\UserService::$settings protected
Definition at line 66 of file UserService.php.
eZ\Publish\Core\Repository\UserService::$userHandler protected
Definition at line 61 of file UserService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/UserService.php