ezp-next: eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser Class Reference
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser Class Reference
Public Member Functions
setBaseKey ($key)
Public Member Functions inherited from eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\Parser
addSemanticConfig (NodeBuilder $nodeBuilder)
registerInternalConfig (array $config, ContainerBuilder $container)
Public Attributes
const UNIQUE = 1
const MERGE_FROM_SECOND_LEVEL = 2
Protected Member Functions
getContainerParameter (ContainerBuilder $container, $id, $default=null)
groupsArraySetting (array $groups, $id, array $config, $options=0)
registerGlobalConfigArray ($id, array $config, ContainerBuilder $container)
registerInternalConfigArray ($id, array $config, ContainerBuilder $container, $options=0)
Protected Attributes
$baseKey = 'system'
Detailed Description
Provides helpers to deal with array settings. This abstract class mainly provides the registerInternalConfigArray() method to properly merge and register array settings defined at in several scopes: $this->registerInternalConfigArray('key', $config, $container); This method will look for the 'key' array in the configuration provided in $config and will merge the arrays from default, group, siteaccess and global scopes in the correct order to compute the value for each siteaccess.
Definition at line 26 of file AbstractParser.php.
Member Function Documentation
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser::getContainerParameter (ContainerBuilder $container, $id, $default = null) protected
Returns the value under the $id in the $container. if the container does not known this $id, returns $default
Parameters
ContainerBuilder $container
string $id
mixed $default
Returns
mixed
Definition at line 70 of file AbstractParser.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser\getContainerParameter().
    {
        if ( $container->hasParameter( $id ) )
        {
            return $container->getParameter( $id );
        }
        return $default;
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser::groupsArraySetting (array $groups, $id, array $config, $options = 0) protected
Merges setting array for a set of groups.
Parameters
array $groups array of group name
string $id id of the setting array under ezpublish.<base_key>.<group_name>
array $config the full configuration array
int $options only self::MERGE_FROM_SECOND_LEVEL or self::UNIQUE are recognized
Returns
array
Definition at line 89 of file AbstractParser.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser\groupsArraySetting().
    {
        $groupsSettings = array();
        sort( $groups );
        foreach ( $groups as $group )
        {
            if ( isset( $config[$this->baseKey][$group][$id] ) )
            {
                if ( $options & self::MERGE_FROM_SECOND_LEVEL )
                {
                    foreach ( array_keys( $config[$this->baseKey][$group][$id] ) as $key )
                    {
                        if ( !isset( $groupsSettings[$key] ) )
{
                            $groupsSettings[$key] = $config[$this->baseKey][$group][$id][$key];
                        }
                        else
{
                            // array_merge() has to be used because we don't
                            // know wether we have a hash or a plain array
                            $groupsSettings[$key] = array_merge(
                                $groupsSettings[$key],
                                $config[$this->baseKey][$group][$id][$key]
                            );
                        }
                    }
                }
                else
                {
                    // array_merge() has to be used because we don't
                    // know wether we have a hash or a plain array
                    $groupsSettings = array_merge(
                        $groupsSettings,
                        $config[$this->baseKey][$group][$id]
                    );
                }
            }
        }
        return $groupsSettings;
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser::registerGlobalConfigArray ($id, array $config, ContainerBuilder $container) protected
Make sure settings array defined in "global" siteaccess are registered in the internal global scope.
Parameters
string $id
array $config
ContainerBuilder $container
Definition at line 138 of file AbstractParser.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser\registerGlobalConfigArray().
    {
        if ( isset( $config[$this->baseKey][ConfigResolver::SCOPE_GLOBAL][$id] )
            && !empty( $config[$this->baseKey][ConfigResolver::SCOPE_GLOBAL][$id] ) )
        {
            $key = 'ezsettings.' . ConfigResolver::SCOPE_GLOBAL . '.' . $id;
            $globalValue = $config[$this->baseKey][ConfigResolver::SCOPE_GLOBAL][$id];
            if ( $container->hasParameter( $key ) )
            {
                $globalValue = array_merge(
                    $container->getParameter( $key ),
                    $globalValue
                );
            }
            $container->setParameter( $key, $globalValue );
        }
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser::registerInternalConfigArray ($id, array $config, ContainerBuilder $container, $options = 0) protected
Registers the internal configuration. For array settings, we merge the arrays defined in scopes default, in the siteaccess groups, in the siteaccess itself and in the global scope. To calculate the precedence of siteaccess group, they are alphabetically sorted.
Parameters
string $id id of the setting array to register
array $config the full configuration as an array
ContainerBuilder $container
int $options bit mask of options (
See Also
constants of this class)
Definition at line 167 of file AbstractParser.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser\getContainerParameter(), eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser\groupsArraySetting(), eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser\registerGlobalConfigArray(), and eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser\registerInternalConfigArray().
    {
        $this->registerGlobalConfigArray( $id, $config, $container );
        $defaultSettings = $this->getContainerParameter(
            $container,
            'ezsettings.' . ConfigResolver::SCOPE_DEFAULT . '.' . $id,
            array()
        );
        $globalSettings = $this->getContainerParameter(
            $container,
            'ezsettings.' . ConfigResolver::SCOPE_GLOBAL . '.' . $id,
            array()
        );
        $groupsBySiteaccess = $this->getContainerParameter(
            $container,
            'ezpublish.siteaccess.groups_by_siteaccess',
            array()
        );
        foreach ( $config['siteaccess']['list'] as $sa )
        {
            // for a siteaccess, we have to merge the default value,
            // the group value(s), the siteaccess value and the global
            // value of the settings.
            $groupsSettings = array();
            if ( isset( $groupsBySiteaccess[$sa] ) && is_array( $groupsBySiteaccess[$sa] ) )
            {
                $groupsSettings = $this->groupsArraySetting(
                    $groupsBySiteaccess[$sa], $id,
                    $config, $options & self::MERGE_FROM_SECOND_LEVEL
                );
            }
            $siteaccessSettings = array();
            if ( isset( $config[$this->baseKey][$sa][$id] ) )
            {
                $siteaccessSettings = $config[$this->baseKey][$sa][$id];
            }
            if ( $options & self::MERGE_FROM_SECOND_LEVEL )
            {
                // array_merge() has to be used because we don't
                // know wether we have a hash or a plain array
                $keys1 = array_unique(
                    array_merge(
                        array_keys( $defaultSettings ),
                        array_keys( $groupsSettings ),
                        array_keys( $siteaccessSettings ),
                        array_keys( $globalSettings )
                    )
                );
                $mergedSettings = array();
                foreach ( $keys1 as $key )
                {
                    $mergedSettings[$key] = array_merge(
                        isset( $defaultSettings[$key] ) ? $defaultSettings[$key] : array(),
                        isset( $groupsSettings[$key] ) ? $groupsSettings[$key] : array(),
                        isset( $siteaccessSettings[$key] ) ? $siteaccessSettings[$key] : array(),
                        isset( $globalSettings[$key] ) ? $globalSettings[$key] : array()
                    );
                }
            }
            else
            {
                $mergedSettings = array_merge(
                    $defaultSettings,
                    $groupsSettings,
                    $siteaccessSettings,
                    $globalSettings
                );
            }
            if ( $options & self::UNIQUE )
            {
                $mergedSettings = array_values(
                    array_unique( $mergedSettings )
                );
            }
            $container->setParameter( "ezsettings.$sa.$id", $mergedSettings );
        }
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser::setBaseKey ($key)
Sets the base key of this parser.
Parameters
string $key
Definition at line 55 of file AbstractParser.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser\setBaseKey().
    {
        $this->baseKey = $key;
    }
Member Data Documentation
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser::$baseKey = 'system' protected
Definition at line 48 of file AbstractParser.php.
const eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser::MERGE_FROM_SECOND_LEVEL = 2
With this option, AbstractParser::registerInternalConfigArray() will merge the hashes from the second level. For instance: array('full' => array(1, 2, 3)) and array('full' => array(4, 5)) will result in array('full' => array(1, 2, 3, 4, 5))
Definition at line 41 of file AbstractParser.php.
const eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\AbstractParser::UNIQUE = 1
With this option, AbstractParser::registerInternalConfigArray() will call array_unique() at the end of the merge process. This will only work with normal arrays (ie not hashes) containing scalar values.
Definition at line 33 of file AbstractParser.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/AbstractParser.php