ezp-next: eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler Class Reference
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler Class Reference
Public Member Functions
__construct (Handler $handler, Backend $backend)
publishUrlAliasForLocation ($locationId, $parentLocationId, $name, $languageCode, $alwaysAvailable=false)
createNewAlias ($linkId, $data, $languageCode, $name, $alwaysAvailable)
createCustomUrlAlias ($locationId, $path, $forwarding=false, $languageCode=null, $alwaysAvailable=false)
createGlobalUrlAlias ($resource, $path, $forwarding=false, $languageCode=null, $alwaysAvailable=false)
listGlobalURLAliases ($languageCode=null, $offset=0, $limit=-1)
listURLAliasesForLocation ($locationId, $custom=false)
removeURLAliases (array $urlAliases)
loadUrlAlias ($id)
locationDeleted ($locationId)
Public Member Functions inherited from eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler
lookup ($url)
locationMoved ($locationId, $oldParentId, $newParentId)
locationCopied ($locationId, $oldParentId, $newParentId)
Protected Member Functions
historizeAndUpdateExistingAlias ($data, $existingAlias, $languageCode, $name, $alwaysAvailable)
getTranslation ($urlAlias, $languageCode)
downgrade ($urlAlias, $languageCode)
historize ($urlAlias, $languageCode)
createUrlAlias ($resource, $path, $forwarding=false, $languageCode=null, $alwaysAvailable=false)
loadAlias ($parentId, $text)
expandAlias ($alias)
loadAutogeneratedAlias ($locationId, $parentId=null)
getHash ($text)
getNextLinkId ()
Protected Attributes
$handler
$backend
Detailed Description
See Also
eZ
Definition at line 20 of file UrlAliasHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::__construct (Handler $handler, Backend $backend)
Setups current handler instance with reference to Handler object that created it.
Parameters
Handler $handler
Backend $backend The storage engine backend
Definition at line 38 of file UrlAliasHandler.php.
References eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\$backend, and eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\$handler.
    {
        $this->handler = $handler;
        $this->backend = $backend;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::createCustomUrlAlias ($locationId, $path, $forwarding = false, $languageCode = null, $alwaysAvailable = false)
Create a user chosen $alias pointing to $locationId in $languageCode.
If $languageCode is null the $alias is created in the system's default language. $alwaysAvailable makes the alias available in all languages.
Parameters
mixed $locationId
string $path
boolean $forwarding
string $languageCode
boolean $alwaysAvailable
Returns
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 279 of file UrlAliasHandler.php.
References eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\createUrlAlias().
    {
        return $this->createUrlAlias(
            "eznode:" . $locationId,
            $path,
            $forwarding,
            $languageCode,
            $alwaysAvailable
        );
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::createGlobalUrlAlias ($resource, $path, $forwarding = false, $languageCode = null, $alwaysAvailable = false)
Create a user chosen $alias pointing to a resource in $languageCode. This method does not handle location resources - if a user enters a location target the createCustomUrlAlias method has to be used.
If $languageCode is null the $alias is created in the system's default language. $alwaysAvailable makes the alias available in all languages.
Exceptions
\eZ\Publish\API\Repository\Exceptions\ForbiddenException if the path already exists for the given language
Parameters
string $resource
string $path
boolean $forwarding
string $languageCode
boolean $alwaysAvailable
Returns
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 308 of file UrlAliasHandler.php.
References eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\createUrlAlias().
    {
        return $this->createUrlAlias(
            $resource,
            $path,
            $forwarding,
            $languageCode,
            $alwaysAvailable
        );
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::createNewAlias ($linkId, $data, $languageCode, $name, $alwaysAvailable)
Creates new alias.
Parameters
mixed $linkId
array $data
string $languageCode
string $name
boolean $alwaysAvailable
Returns
void
Definition at line 147 of file UrlAliasHandler.php.
    {
        $data["link"] = $linkId;
        $data["pathData"][] = array(
            'always-available' => $alwaysAvailable,
            'translations' => array(
                $languageCode => $name
            )
        );
        $this->backend->create( 'Content\\UrlAlias', $data );
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::createUrlAlias ($resource, $path, $forwarding = false, $languageCode = null, $alwaysAvailable = false) protected
Internal method for creating global or custom URL alias (these are handled in the same way)
Exceptions
\eZ\Publish\Core\Base\Exceptions\ForbiddenException if the path already exists for the given language
Parameters
string $resource
string $path
boolean $forwarding
string | null $languageCode
boolean $alwaysAvailable
Returns
With $type = URLAlias::RESOURCE
Definition at line 332 of file UrlAliasHandler.php.
References eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\downgrade(), eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\getHash(), eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\getNextLinkId(), and eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\loadAlias().
    {
        if ( $languageCode === null )
            $languageCode = 'eng-GB';// @todo Reuse settings used in Service layer here
        $pathArray = explode( '/', $path );
        $pathCount = count( $pathArray );
        $pathData = array();
        $parentId = 0;
        foreach ( $pathArray as $index => $pathItem )
        {
            if ( $index + 1 !== $pathCount )
            {
                $existingAlias = $this->loadAlias( $parentId, $pathItem );
                if ( !isset( $existingAlias ) )
                {
                    $pathData[] = array(
                        'always-available' => true,
                        'translations' => array( 'always-available' => $pathItem )
                    );
                    $virtualAlias = $this->backend->create(
                        'Content\\UrlAlias',
                        array(
                            'parent' => $parentId,
                            'link' => $this->getNextLinkId(),
                            'type' => URLAlias::VIRTUAL,
                            'destination' => null,
                            'pathData' => $pathData,
                            'languageCodes' => array(),
                            'alwaysAvailable' => true,
                            'isHistory' => false,
                            'isCustom' => true,
                            'forward' => true,
                        )
                    );
                    $parentId = $virtualAlias->id["link"];
                }
                else
                {
                    $parentId = $existingAlias->id["link"];
                    $pathData = $existingAlias->pathData;
                }
            }
            else
            {
                $pathData[] = array(
                    'always-available' => $alwaysAvailable,
                    'translations' => array( $languageCode => $pathItem )
                );
            }
        }
        preg_match( "#^([a-zA-Z0-9_]+):(.+)?$#", $resource, $matches );
        $data = array(
            'parent' => $parentId,
            'link' => $this->getNextLinkId(),
            'type' => $matches[1] === "eznode" ? URLAlias::LOCATION : URLAlias::RESOURCE,
            'destination' => isset( $matches[2] ) ? $matches[2] : false,
            'pathData' => $pathData,
            'languageCodes' => array( $languageCode ),
            'alwaysAvailable' => $alwaysAvailable,
            'isHistory' => false,
            'isCustom' => true,
            'forward' => $forwarding,
        );
        $reusableAlias = $this->loadAlias( $parentId, $pathItem );
        if ( !isset( $reusableAlias ) )
        {
            $alias = $this->backend->create( 'Content\\UrlAlias', $data );
        }
        else if ( $reusableAlias->type == URLAlias::VIRTUAL || $reusableAlias->isHistory )
        {
            $this->downgrade( $reusableAlias, $languageCode );
            $alias = $this->backend->create( 'Content\\UrlAlias', $data );
        }
        else
        {
            throw new ForbiddenException( "Path '$path' already exists for the given language" );
        }
        $alias->id = $alias->id["parent"] . "-" . $this->getHash( $pathItem );
        return $alias;
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::downgrade ($urlAlias, $languageCode) protected
Remove translation in given $languageCode from alias or delete alias if given translation is the last one.
Parameters
\eZ\Publish\SPI\Persistence\Content\UrlAlias $urlAlias
string $languageCode
Returns
void
Definition at line 220 of file UrlAliasHandler.php.
    {
        $urlAlias = clone $urlAlias;
        $lastIndex = count( $urlAlias->pathData ) - 1;
        unset( $urlAlias->pathData[$lastIndex]["translations"][$languageCode] );
        if ( empty( $urlAlias->pathData[$lastIndex]["translations"] ) )
        {
            $urlAlias->languageCodes = array_diff( $urlAlias->languageCodes, array( $languageCode ) );
            $this->backend->update(
                'Content\\UrlAlias',
                $urlAlias->id["id"],
                array(
                    'pathData' => $urlAlias->pathData,
                    'languageCodes' => $urlAlias->languageCodes
                )
            );
        }
        else
        {
            $this->backend->delete( 'Content\\UrlAlias', $urlAlias->id );
        }
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::expandAlias ($alias) protected
Expands given $alias to array of new aliases for each different translation.
Parameters
\eZ\Publish\SPI\Persistence\Content\UrlAlias $alias
Returns
array
Definition at line 529 of file UrlAliasHandler.php.
References eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\getHash().
    {
        // extract names
        $names = array();
        $pathData = end( $alias->pathData );
        foreach ( $pathData["translations"] as $text )
        {
            $names[$text] = true;
        }
        // expand
        $expanded = array();
        foreach ( $names as $name => $dummy )
        {
            $cloned = clone $alias;
            $cloned->id = $cloned->id["parent"] . "-" . $this->getHash( $name );
            $expanded[] = $cloned;
        }
        return $expanded;
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::getHash ($text) protected
Parameters
string $text
Returns
string
Definition at line 843 of file UrlAliasHandler.php.
    {
        return md5( strtolower( $text ) );
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::getNextLinkId () protected
Returns max found link id incremented by 1
Returns
int
Definition at line 853 of file UrlAliasHandler.php.
    {
        $list = $this->backend->find( 'Content\\UrlAlias' );
        $id = 0;
        foreach ( $list as $alias )
        {
            $id = max( $id, $alias->id["link"] );
        }
        return $id + 1;
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::getTranslation ($urlAlias, $languageCode) protected
Returns translation in given $languageCode or null if it does not exist.
Parameters
\eZ\Publish\SPI\Persistence\Content\UrlAlias $urlAlias
string $languageCode
Returns
string|null
Definition at line 201 of file UrlAliasHandler.php.
    {
        $lastIndex = count( $urlAlias->pathData ) - 1;
        if ( isset( $urlAlias->pathData[$lastIndex]["translations"][$languageCode] ) )
        {
            return $urlAlias->pathData[$lastIndex]["translations"][$languageCode];
        }
        return null;
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::historize ($urlAlias, $languageCode) protected
Creates history for one translation.
Parameters
\eZ\Publish\SPI\Persistence\Content\UrlAlias $urlAlias
string $languageCode
Returns
void
Definition at line 252 of file UrlAliasHandler.php.
    {
        $data = (array)$urlAlias;
        $lastIndex = count( $data["pathData"] ) - 1;
        $data["pathData"][$lastIndex]["translations"] = array(
            $languageCode => $data["pathData"][$lastIndex]["translations"][$languageCode]
        );
        $data["languageCodes"] = array( $languageCode );
        $data["isHistory"] = true;
        $this->backend->update( 'Content\\UrlAlias', $urlAlias->id["id"], $data );
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::historizeAndUpdateExistingAlias ($data, $existingAlias, $languageCode, $name, $alwaysAvailable) protected
Updates existing location alias and creates history if necessary.
Parameters
array $data
\eZ\Publish\SPI\Persistence\Content\UrlAlias $existingAlias
string $languageCode
string $name
boolean $alwaysAvailable
Returns
void
Definition at line 170 of file UrlAliasHandler.php.
References eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\getTranslation(), and eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\historize().
    {
        $existingTranslation = $this->getTranslation( $existingAlias, $languageCode );
        // Do not historize letter case changes
        if ( isset( $existingTranslation ) && strcasecmp( $name, $existingTranslation ) !== 0 )
        {
            $this->historize( $existingAlias, $languageCode );
        }
        $pathData = $existingAlias->pathData;
        $lastPathElementData = end( $pathData );
        $lastPathElementData["always-available"] = $alwaysAvailable;
        $lastPathElementData["translations"][$languageCode] = $name;
        $data["pathData"][] = $lastPathElementData;
        if ( !in_array( $languageCode, $data["languageCodes"] ) )
        {
            $data["languageCodes"][] = $languageCode;
        }
        $data["alwaysAvailable"] = $alwaysAvailable;
        $this->backend->update( 'Content\\UrlAlias', $existingAlias->id["id"], $data );
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::listGlobalURLAliases ($languageCode = null, $offset = 0, $limit = -1)
List global aliases.
Parameters
string | null $languageCode
int $offset
int $limit
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 463 of file UrlAliasHandler.php.
References eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\getHash().
    {
        $filter = array(
            'type' => URLAlias::RESOURCE,
            'isHistory' => false,
            'isCustom' => true
        );
        if ( $languageCode !== null )
            $filter['languageCodes'] = $languageCode;
        $list = $this->backend->find(
            'Content\\UrlAlias',
            $filter
        );
        if ( !empty( $list ) && !( $offset === 0 && $limit === -1 ) )
        {
            $list = array_slice( $list, $offset, ( $limit === -1 ? null : $limit ) );
        }
        foreach ( $list as &$alias )
        {
            $pathData = end( $alias->pathData );
            $alias->id = $alias->id["parent"] . "-" . $this->getHash( reset( $pathData["translations"] ) );
        }
        return $list;
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::listURLAliasesForLocation ($locationId, $custom = false)
List of url entries of $urlType, pointing to $locationId.
Parameters
mixed $locationId
boolean $custom if true the user generated aliases are listed otherwise the autogenerated
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 501 of file UrlAliasHandler.php.
References eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\expandAlias().
    {
        $list = $this->backend->find(
            'Content\\UrlAlias',
            array(
                'destination' => $locationId,
                'type' => URLAlias::LOCATION,
                'isCustom' => $custom,
                'isHistory' => false
            )
        );
        $expanded = array();
        foreach ( $list as $alias )
        {
            $expanded = array_merge( $expanded, $this->expandAlias( $alias ) );
        }
        return $expanded;
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::loadAlias ($parentId, $text) protected
Loads alias by given $parentId and $text.
Parameters
mixed $parentId
string $text
Returns
|null
Definition at line 426 of file UrlAliasHandler.php.
    {
        $list = $this->backend->find( 'Content\\UrlAlias', array( 'parent' => $parentId ) );
        $filteredList = array();
        foreach ( $list as $alias )
        {
            $pathData = end( $alias->pathData );
            foreach ( $pathData["translations"] as $translation )
            {
                if ( strcasecmp( $text, $translation ) === 0 )
                {
                    $filteredList[] = $alias;
                    break;
                }
            }
        }
        if ( isset( $filteredList[1] ) )
        {
            throw new \RuntimeException(
                "Found more then 1 url alias for the parent '{$parentId}' and text '{$text}'"
            );
        }
        return isset( $filteredList[0] ) ? $filteredList[0] : null;
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::loadAutogeneratedAlias ($locationId, $parentId = null) protected
Loads autogenerated location alias for given $locationId, optionally limited by given $parentId.
Exceptions
\RuntimeException
Parameters
mixed $locationId
null $parentId
Returns
|null
Definition at line 732 of file UrlAliasHandler.php.
    {
        $match = array(
            'destination' => $locationId,
            'type' => URLAlias::LOCATION,
            'isHistory' => false,
            'isCustom' => false
        );
        if ( isset( $parentId ) )
        {
            $match["parent"] = $parentId;
        }
        $list = $this->backend->find( 'Content\\UrlAlias', $match );
        if ( isset( $list[1] ) )
        {
            throw new \RuntimeException( 'Found more then 1 url alias pointing to same location: ' . $locationId );
        }
        else if ( empty( $list ) )
        {
            return null;
        }
        return $list[0];
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::loadUrlAlias ($id)
Loads URL alias by given $id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException
Parameters
string $id
Returns
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 635 of file UrlAliasHandler.php.
    {
        return $this->backend->load( 'Content\\UrlAlias', $id );
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::locationDeleted ($locationId)
Notifies the underlying engine that a location was deleted or moved to trash
Parameters
mixed $locationId
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 833 of file UrlAliasHandler.php.
    {
        $this->backend->deleteByMatch( 'Content\\UrlAlias', array( 'destination' => $locationId ) );
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::publishUrlAliasForLocation ($locationId, $parentLocationId, $name, $languageCode, $alwaysAvailable = false)
This method creates or updates an urlalias from a new or changed content name in a language (if published). It also can be used to create an alias for a new location of content. On update the old alias is linked to the new one (i.e. a history alias is generated).
$alwaysAvailable controls whether the url alias is accessible in all languages.
Parameters
mixed $locationId
mixed $parentLocationId In case of empty($parentLocationId), threat as root
string $name the new name computed by the name schema or url alias schema
string $languageCode
boolean $alwaysAvailable
Returns
void Does not return the UrlAlias created / updated with type URLAlias::LOCATION
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 60 of file UrlAliasHandler.php.
References eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\createNewAlias(), eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\downgrade(), eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\getNextLinkId(), eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\historizeAndUpdateExistingAlias(), eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\loadAlias(), and eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler\loadAutogeneratedAlias().
    {
        // Get parent url alias
        $parentLocationAlias = $this->loadAutogeneratedAlias( $parentLocationId );
        if ( !isset( $parentLocationAlias ) )
        {
            throw new \RuntimeException( "Did not find any url alias for location:  {$parentLocationId}" );
        }
        $parentId = $parentLocationAlias->id["link"];
        $pathData = $parentLocationAlias->pathData;
        $data = array(
            'parent' => $parentLocationAlias->id["link"],
            'type' => URLAlias::LOCATION,
            'destination' => $locationId,
            'pathData' => $pathData,
            'languageCodes' => array( $languageCode ),
            'alwaysAvailable' => $alwaysAvailable,
            'isHistory' => false,
            'isCustom' => false,
            'forward' => false,
        );
        $uniqueCounter = 1;
        // Exiting the loop with break;
        while ( true )
        {
            $newText = $name . ( $uniqueCounter > 1 ? $uniqueCounter : "" );
            // Try to load possibly reusable alias
            $reusableAlias = $this->loadAlias( $parentId, $newText );
            if ( !isset( $reusableAlias ) )
            {
                // Check for existing active location entry on this level and reuse it
                $existingAlias = $this->loadAutogeneratedAlias( $locationId, $parentId );
                if ( isset( $existingAlias ) )
                {
                    $this->historizeAndUpdateExistingAlias( $data, $existingAlias, $languageCode, $newText, $alwaysAvailable );
                }
                else
                {
                    $this->createNewAlias( $this->getNextLinkId(), $data, $languageCode, $newText, $alwaysAvailable );
                }
                break;
            }
            // Possibly reusable alias exists, check if it is reusable
            if ( $reusableAlias->type == URLAlias::VIRTUAL
                || ( $reusableAlias->type == URLAlias::LOCATION && $reusableAlias->destination == $locationId )
                || $reusableAlias->isHistory )
            {
                // Check for existing active location entry on this level and reuse it
                $existingAlias = $this->loadAutogeneratedAlias( $locationId, $parentId );
                if ( isset( $existingAlias ) )
                {
                    $this->historizeAndUpdateExistingAlias( $data, $existingAlias, $languageCode, $newText, $alwaysAvailable );
                    if ( $existingAlias->id["link"] != $reusableAlias->id["link"] )
                    {
                        $this->downgrade( $reusableAlias, $languageCode );
                    }
                }
                else
                {
                    $this->downgrade( $reusableAlias, $languageCode );
                    $this->createNewAlias( $reusableAlias->id["link"], $data, $languageCode, $newText, $alwaysAvailable );
                }
                break;
            }
            // If existing row is not reusable, increment $uniqueCounter and try again
            $uniqueCounter += 1;
        }
    }
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::removeURLAliases (array $urlAliases)
Removes url aliases.
Autogenerated aliases are not removed by this method.
Parameters
\eZ\Publish\SPI\Persistence\Content\UrlAlias[] $urlAliases
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\UrlAlias\Handler.
Definition at line 560 of file UrlAliasHandler.php.
    {
        foreach ( $urlAliases as $index => $urlAlias )
        {
            if ( !$urlAlias instanceof UrlAlias )
                throw new \eZ\Publish\Core\Base\Exceptions\InvalidArgumentException( "\$urlAliases[$index]", 'Expected UrlAlias instance' );
            if ( !$urlAlias->isCustom )
                continue;
            $this->backend->delete( 'Content\\UrlAlias', $urlAlias->id );
        }
    }
Member Data Documentation
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::$backend protected
Definition at line 30 of file UrlAliasHandler.php.
eZ\Publish\Core\Persistence\InMemory\UrlAliasHandler::$handler protected
Definition at line 25 of file UrlAliasHandler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/InMemory/UrlAliasHandler.php