ezp-next: eZ\Publish\Core\FieldType\DateAndTime\Type Class Reference
eZ\Publish\Core\FieldType\DateAndTime\Type Class Reference
Public Member Functions
getFieldTypeIdentifier ()
getName ($value)
getEmptyValue ()
fromHash ($hash)
toHash ($value)
isSearchable ()
validateFieldSettings ($fieldSettings)
fieldSettingsToHash ($fieldSettings)
fieldSettingsFromHash ($fieldSettingsHash)
Public Member Functions inherited from eZ\Publish\Core\FieldType\FieldType
getSettingsSchema ()
getValidatorConfigurationSchema ()
validate (FieldDefinition $fieldDefinition, $fieldValue)
validateValidatorConfiguration ($validatorConfiguration)
toPersistenceValue ($value)
fromPersistenceValue (FieldValue $fieldValue)
isEmptyValue ($value)
acceptValue ($inputValue)
validatorConfigurationToHash ($validatorConfiguration)
validatorConfigurationFromHash ($validatorConfigurationHash)
Public Attributes
const DEFAULT_EMPTY = 0
const DEFAULT_CURRENT_DATE = 1
const DEFAULT_CURRENT_DATE_ADJUSTED = 2
Protected Member Functions
internalAcceptValue ($inputValue)
getSortInfo ($value)
Protected Attributes
$settingsSchema
Protected Attributes inherited from eZ\Publish\Core\FieldType\FieldType
$settingsSchema = array()
$validatorConfigurationSchema = array()
Detailed Description
Definition at line 17 of file Type.php.
Member Function Documentation
eZ\Publish\Core\FieldType\DateAndTime\Type::fieldSettingsFromHash ($fieldSettingsHash)
Converts the given $fieldSettingsHash to field settings of the type
This is the reverse operation of fieldSettingsToHash().
This is the default implementation, which just returns the given $fieldSettingsHash, assuming the supported field settings are already in a hash format. Overwrite this in your specific implementation, if necessary.
Parameters
array | hash | scalar | null $fieldSettingsHash
Returns
mixed
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 335 of file Type.php.
    {
        $fieldSettings = parent::fieldSettingsFromHash( $fieldSettingsHash );
        if ( isset( $fieldSettings['dateInterval'] ) )
        {
            $fieldSettings['dateInterval'] = new \DateInterval( $fieldSettings['dateInterval'] );
        }
        return $fieldSettings;
    }
eZ\Publish\Core\FieldType\DateAndTime\Type::fieldSettingsToHash ($fieldSettings)
Converts the given $fieldSettings to a simple hash format
This is the default implementation, which just returns the given $fieldSettings, assuming they are already in a hash format. Overwrite this in your specific implementation, if necessary.
Parameters
mixed $fieldSettings
Returns
array|hash|scalar|null
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 307 of file Type.php.
    {
        $fieldSettingsHash = parent::fieldSettingsToHash( $fieldSettings );
        if ( isset( $fieldSettingsHash['dateInterval'] ) )
        {
            $fieldSettingsHash['dateInterval'] = $fieldSettingsHash['dateInterval']->format(
                'P%r%yY%r%mM%r%dDT%r%hH%iM%r%sS'
            );
        }
        return $fieldSettingsHash;
    }
eZ\Publish\Core\FieldType\DateAndTime\Type::fromHash ($hash)
Converts an $hash to the Value defined by the field type
Parameters
int $hash Number of seconds since Unix Epoch
Returns
$value
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 152 of file Type.php.
References eZ\Publish\Core\FieldType\DateAndTime\Value\fromString(), and eZ\Publish\Core\FieldType\DateAndTime\Value\fromTimestamp().
    {
        if ( $hash === null )
        {
            return null;
        }
        if ( isset( $hash['rfc850'] ) && $hash['rfc850'] )
        {
            return Value::fromString( $hash['rfc850'] );
        }
        return Value::fromTimestamp( (int)$hash['timestamp'] );
    }
eZ\Publish\Core\FieldType\DateAndTime\Type::getEmptyValue ()
Returns the fallback default value of field type when no such default value is provided in the field definition in content types.
Returns
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 82 of file Type.php.
    {
        return new Value;
    }
eZ\Publish\Core\FieldType\DateAndTime\Type::getFieldTypeIdentifier ()
Returns the field type identifier for this field type
Returns
string
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 51 of file Type.php.
    {
        return "ezdatetime";
    }
eZ\Publish\Core\FieldType\DateAndTime\Type::getName ($value)
Returns the name of the given field value.
It will be used to generate content name and url alias if current field is designated to be used in the content name/urlAlias pattern.
Parameters
mixed $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 66 of file Type.php.
    {
        if ( $value === null )
        {
            return '';
        }
        return $value->value->format( 'D Y-d-m H:i:s' );
    }
eZ\Publish\Core\FieldType\DateAndTime\Type::getSortInfo ($value) protected
Returns information for FieldValue->$sortKey relevant to the field type.
Parameters
\eZ\Publish\Core\FieldType\DateAndTime\Value $value
Returns
array
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 136 of file Type.php.
    {
        if ( $value === null || $value->value === null )
        {
            return null;
        }
        return $value->value->getTimestamp();
    }
eZ\Publish\Core\FieldType\DateAndTime\Type::internalAcceptValue ($inputValue) protected
Implements the core of {
See Also
acceptValue()}.
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 94 of file Type.php.
References eZ\Publish\Core\FieldType\DateAndTime\Value\fromString(), and eZ\Publish\Core\FieldType\DateAndTime\Value\fromTimestamp().
    {
        if ( is_string( $inputValue ) )
        {
            $inputValue = Value::fromString( $inputValue );
        }
        if ( is_int( $inputValue ) )
        {
            $inputValue = Value::fromTimestamp( $inputValue );
        }
        if ( $inputValue instanceof \DateTime )
        {
            $inputValue = new Value( $inputValue );
        }
        else if ( !$inputValue instanceof Value )
        {
            throw new InvalidArgumentType(
                '$inputValue',
                'eZ\\Publish\\Core\\FieldType\\DateAndTime\\Value',
                $inputValue
            );
        }
        if ( isset( $inputValue->value ) && !$inputValue->value instanceof DateTime )
        {
            throw new InvalidArgumentType(
                '$inputValue->value',
                'DateTime',
                $inputValue->value
            );
        }
        return $inputValue;
    }
eZ\Publish\Core\FieldType\DateAndTime\Type::isSearchable ()
Returns whether the field type is searchable
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 200 of file Type.php.
    {
        return true;
    }
eZ\Publish\Core\FieldType\DateAndTime\Type::toHash ($value)
Converts a $Value to a hash
Parameters
\eZ\Publish\Core\FieldType\DateAndTime\Value $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 174 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\isEmptyValue().
    {
        if ( $this->isEmptyValue( $value ) )
        {
            return null;
        }
        if ( $value->value instanceof DateTime )
        {
            return array(
                'timestamp' => $value->value->getTimestamp(),
                'rfc850'    => $value->value->format( \DateTime::RFC850  ),
            );
        }
        return array(
            'timestamp' => 0,
            'rfc850'    => null,
        );
    }
eZ\Publish\Core\FieldType\DateAndTime\Type::validateFieldSettings ($fieldSettings)
Validates the fieldSettings of a FieldDefinitionCreateStruct or FieldDefinitionUpdateStruct
Parameters
mixed $fieldSettings
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 212 of file Type.php.
    {
        $validationErrors = array();
        foreach ( $fieldSettings as $name => $value )
        {
            if ( isset( $this->settingsSchema[$name] ) )
            {
                switch ( $name )
                {
                    case "useSeconds":
                        if ( !is_bool( $value ) )
{
                            $validationErrors[] = new ValidationError(
                                "Setting '%setting%' value must be of boolean type",
                                null,
                                array(
                                    "setting" => $name
                                )
                            );
                        }
                        break;
                    case "defaultType":
                        $definedTypes = array(
                            self::DEFAULT_EMPTY,
                            self::DEFAULT_CURRENT_DATE,
                            self::DEFAULT_CURRENT_DATE_ADJUSTED
                        );
                        if ( !in_array( $value, $definedTypes ) )
{
                            $validationErrors[] = new ValidationError(
                                "Setting '%setting%' is of unknown type",
                                null,
                                array(
                                    "setting" => $name
                                )
                            );
                        }
                        break;
                    case "dateInterval":
                        if ( isset( $value ) )
{
                            if ( isset( $fieldSettings["defaultType"] ) &&
                                $fieldSettings["defaultType"] !== self::DEFAULT_CURRENT_DATE_ADJUSTED )
{
                                $validationErrors[] = new ValidationError(
                                    "Setting '%setting%' can be used only when setting '%defaultType%' is set to '%DEFAULT_CURRENT_DATE_ADJUSTED%'",
                                    null,
                                    array(
                                        "setting" => $name,
                                        "defaultType" => "defaultType",
                                        "DEFAULT_CURRENT_DATE_ADJUSTED" => "DEFAULT_CURRENT_DATE_ADJUSTED"
                                    )
                                );
                            }
                            else if ( !( $value instanceof \DateInterval ) )
{
                                $validationErrors[] = new ValidationError(
                                    "Setting '%setting%' value must be an instance of 'DateInterval' class",
                                    null,
                                    array(
                                        "setting" => $name
                                    )
                                );
                            }
                        }
                        break;
                }
            }
            else
            {
                $validationErrors[] = new ValidationError(
                    "Setting '%setting%' is unknown",
                    null,
                    array(
                        "setting" => $name
                    )
                );
            }
        }
        return $validationErrors;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\DateAndTime\Type::$settingsSchema protected
Initial value:
 array(
        "useSeconds" => array(
            "type" => "bool",
            "default" => false
        ),
        "defaultType" => array(
            "type" => "choice",
            "default" => self::DEFAULT_EMPTY
        ),
        "dateInterval" => array(
            "type" => "dateInterval",
            "default" => null
        )
    )
Definition at line 26 of file Type.php.
const eZ\Publish\Core\FieldType\DateAndTime\Type::DEFAULT_CURRENT_DATE = 1
Definition at line 23 of file Type.php.
const eZ\Publish\Core\FieldType\DateAndTime\Type::DEFAULT_CURRENT_DATE_ADJUSTED = 2
Definition at line 24 of file Type.php.
const eZ\Publish\Core\FieldType\DateAndTime\Type::DEFAULT_EMPTY = 0
Default value types
Definition at line 22 of file Type.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/DateAndTime/Type.php