ezp-next: eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage Class Reference
eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage Class Reference
Public Member Functions
setConnection ($dbHandler)
getNodePathString (VersionInfo $versionInfo)
storeImageReference ($path, $fieldId)
getXmlForImages ($versionNo, array $fieldIds)
removeImageReferences ($path, $versionNo, $fieldId)
countImageReferences ($path)
Protected Member Functions
getConnection ()
Protected Attributes
$dbHandler
$fieldNameMap
Detailed Description
Definition at line 15 of file LegacyStorage.php.
Member Function Documentation
eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage::countImageReferences ($path)
Returns the number of recorded references to the given $path
Parameters
string $path
Returns
int
Reimplemented from eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway.
Definition at line 216 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\countImageReferences(), and eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\getConnection().
    {
        $connection = $this->getConnection();
        $selectQuery = $connection->createSelectQuery();
        $selectQuery->select(
            $selectQuery->expr->count(
                $connection->quoteColumn( 'id' )
            )
        )->from(
            $connection->quoteTable( 'ezimagefile' )
        )->where(
            $selectQuery->expr->like(
                $connection->quoteColumn( 'filepath' ),
                $selectQuery->bindValue( $path . '%' )
            )
        );
        $statement = $selectQuery->prepare();
        $statement->execute();
        return (int)$statement->fetchColumn();
    }
eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage::getConnection () protected
Returns the active connection
Exceptions
\RuntimeException if no connection has been set, yet.
Returns
Definition at line 67 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\getConnection().
    {
        if ( $this->dbHandler === null )
        {
            throw new \RuntimeException( "Missing database connection." );
        }
        return $this->dbHandler;
    }
eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage::getNodePathString (VersionInfo $versionInfo)
Returns the node path string of $versionInfo
Parameters
VersionInfo $versionInfo
Returns
string
Reimplemented from eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway.
Definition at line 83 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\getNodePathString().
    {
        $connection = $this->getConnection();
        $selectQuery = $connection->createSelectQuery();
        $selectQuery->select( 'path_identification_string' )
            ->from( $connection->quoteTable( 'ezcontentobject_tree' ) )
            ->where(
                $selectQuery->expr->lAnd(
                    $selectQuery->expr->eq(
                        $connection->quoteColumn( 'contentobject_id' ),
                        $selectQuery->bindValue( $versionInfo->contentInfo->id )
                    ),
                    $selectQuery->expr->eq(
                        $connection->quoteColumn( 'contentobject_version' ),
                        $selectQuery->bindValue( $versionInfo->versionNo )
                    ),
                    $selectQuery->expr->eq(
                        $connection->quoteColumn( 'node_id' ),
                        $connection->quoteColumn( 'main_node_id' )
                    )
                )
            );
        $statement = $selectQuery->prepare();
        $statement->execute();
        return $statement->fetchColumn();
    }
eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage::getXmlForImages ($versionNo, array $fieldIds)
Returns a the XML content stored for the given $fieldIds
Parameters
int $versionNo
array $fieldIds
Returns
array
Reimplemented from eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway.
Definition at line 146 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\getXmlForImages().
    {
        $connection = $this->getConnection();
        $selectQuery = $connection->createSelectQuery();
        $selectQuery->select(
            $connection->quoteColumn( 'id', 'ezcontentobject_attribute' ),
            $connection->quoteColumn( 'data_text', 'ezcontentobject_attribute' )
        )->from(
            $connection->quoteTable( 'ezcontentobject_attribute' )
        )->where(
            $selectQuery->expr->lAnd(
                $selectQuery->expr->in(
                    $connection->quoteColumn( 'id', 'ezcontentobject_attribute' ),
                    $fieldIds
                )
            )
        );
        $statement = $selectQuery->prepare();
        $statement->execute();
        $fieldLookup = array();
        foreach ( $statement->fetchAll( \PDO::FETCH_ASSOC ) as $row )
        {
            $fieldLookup[$row['id']] = $row['data_text'];
        }
        return $fieldLookup;
    }
eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage::removeImageReferences ($path, $versionNo, $fieldId)
Removes all references from $fieldId to a path that starts with $path
Parameters
string $path
mixed $fieldId
Returns
void
Reimplemented from eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway.
Definition at line 185 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\removeImageReferences().
    {
        $connection = $this->getConnection();
        $deleteQuery = $connection->createDeleteQuery();
        $deleteQuery->deleteFrom(
            $connection->quoteTable( 'ezimagefile' )
        )->where(
            $deleteQuery->expr->lAnd(
                $deleteQuery->expr->eq(
                    $connection->quoteColumn( 'contentobject_attribute_id' ),
                    $deleteQuery->bindValue( $fieldId, null, \PDO::PARAM_INT )
                ),
                $deleteQuery->expr->like(
                    $connection->quoteColumn( 'filepath' ),
                    $deleteQuery->bindValue( $path . '%' )
                )
            )
        );
        $statement = $deleteQuery->prepare();
        $statement->execute();
    }
eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage::setConnection ($dbHandler)
Set database handler for this gateway
Parameters
mixed $dbHandler
Returns
void
Exceptions
\RuntimeException if $dbHandler is not an instance of eZ\Publish\Core\Persistence\Legacy\EzcDbHandler
Reimplemented from eZ\Publish\Core\FieldType\StorageGateway.
Definition at line 46 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\$dbHandler, and eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\setConnection().
    {
        // This obviously violates the Liskov substitution Principle, but with
        // the given class design there is no sane other option. Actually the
        // dbHandler *should* be passed to the constructor, and there should
        // not be the need to post-inject it.
        if ( !$dbHandler instanceof \eZ\Publish\Core\Persistence\Legacy\EzcDbHandler )
        {
            throw new \RuntimeException( "Invalid dbHandler passed" );
        }
        $this->dbHandler = $dbHandler;
    }
eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage::storeImageReference ($path, $fieldId)
Stores a reference to the image in $path for $fieldId
Parameters
string $path
mixed $fieldId
Returns
void
Reimplemented from eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway.
Definition at line 120 of file LegacyStorage.php.
References eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\getConnection(), and eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage\storeImageReference().
    {
        $connection = $this->getConnection();
        $insertQuery = $connection->createInsertQuery();
        $insertQuery->insertInto( $connection->quoteTable( 'ezimagefile' ) )
            ->set(
                $connection->quoteColumn( 'contentobject_attribute_id' ),
                $insertQuery->bindValue( $fieldId, null, \PDO::PARAM_INT )
            )->set(
                $connection->quoteColumn( 'filepath' ),
                $insertQuery->bindValue( $path )
            );
        $statement = $insertQuery->prepare();
        $statement->execute();
    }
Member Data Documentation
eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage::$dbHandler protected
Definition at line 22 of file LegacyStorage.php.
eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage::$fieldNameMap protected
Initial value:
 array(
        'id' => 'fieldId',
        'version' => 'versionNo',
        'language_code' => 'languageCode',
        'path_identification_string' => 'nodePathString',
        'data_string' => 'xml',
    )
Definition at line 29 of file LegacyStorage.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway/LegacyStorage.php