ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper Class Reference
Public Member Functions
__construct (LanguageMaskGenerator $languageMaskGenerator)
extractUrlAliasFromData ($data)
extractUrlAliasListFromData (array $rows)
Protected Member Functions
matchTypeAndDestination ($action)
normalizePathData ($pathData)
normalizePathDataRow (array &$pathElementData, array $row)
Protected Attributes
$languageMaskGenerator
Detailed Description
UrlAlias Mapper
Definition at line 18 of file Mapper.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper::__construct (LanguageMaskGenerator $languageMaskGenerator)
Creates a new UrlWildcard Handler
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\Language\MaskGenerator $languageMaskGenerator
Definition at line 32 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper\$languageMaskGenerator.
    {
        $this->languageMaskGenerator = $languageMaskGenerator;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper::extractUrlAliasFromData ($data)
Creates a UrlAlias object from database row data
Parameters
mixed[] $data
Returns
Definition at line 44 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper\matchTypeAndDestination(), and eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper\normalizePathData().
    {
        $urlAlias = new UrlAlias();
        list( $type, $destination ) = $this->matchTypeAndDestination( $data["action"] );
        $urlAlias->id = $data["parent"] . "-" . $data["text_md5"];
        $urlAlias->pathData = isset( $data["raw_path_data"] )
            ? $this->normalizePathData( $data["raw_path_data"] )
            : null;
        $urlAlias->languageCodes = $this->languageMaskGenerator->extractLanguageCodesFromMask( $data["lang_mask"] );
        $urlAlias->alwaysAvailable = $this->languageMaskGenerator->isAlwaysAvailable( $data["lang_mask"] );
        $urlAlias->isHistory = isset( $data["is_path_history"] ) ? $data["is_path_history"] : !$data["is_original"];
        $urlAlias->isCustom = (boolean)$data["is_alias"];
        $urlAlias->forward = $data["is_alias"] && $data["alias_redirects"];
        $urlAlias->destination = $destination;
        $urlAlias->type = $type;
        return $urlAlias;
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper::extractUrlAliasListFromData (array $rows)
Extracts UrlAlias objects from database $rows
Parameters
array $rows
Returns
[]
Definition at line 71 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper\extractUrlAliasFromData().
    {
        $urlAliases = array();
        foreach ( $rows as $row )
        {
            $urlAliases[] = $this->extractUrlAliasFromData( $row );
        }
        return $urlAliases;
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper::matchTypeAndDestination ($action) protected
Exceptions
\RuntimeException
Parameters
string $action
Returns
array
Definition at line 89 of file Mapper.php.
References eZ\Publish\SPI\Persistence\Content\UrlAlias\LOCATION, eZ\Publish\SPI\Persistence\Content\UrlAlias\RESOURCE, and eZ\Publish\SPI\Persistence\Content\UrlAlias\VIRTUAL.
    {
        if ( preg_match( "#^([a-zA-Z0-9_]+):(.+)?$#", $action, $matches ) )
        {
            $actionType = $matches[1];
            $actionValue = isset( $matches[2] ) ? $matches[2] : false;
            switch ( $actionType )
            {
                case "eznode":
                    $type = UrlAlias::LOCATION;
                    $destination = $actionValue;
                    break;
                case "module":
                    $type = UrlAlias::RESOURCE;
                    $destination = $actionValue;
                    break;
                case "nop":
                    $type = UrlAlias::VIRTUAL;
                    $destination = null;
                    break;
                default:
                    // @todo log message
                    throw new \RuntimeException( "Action type '{$actionType}' is unknown" );
            }
        }
        else
        {
            // @todo log message
            throw new \RuntimeException( "Action '{$action}' is not valid" );
        }
        return array( $type, $destination );
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper::normalizePathData ($pathData) protected
Parameters
array $pathData
Returns
array
Definition at line 132 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper\normalizePathDataRow().
    {
        $normalizedPathData = array();
        foreach ( $pathData as $level => $rows )
        {
            $pathElementData = array();
            foreach ( $rows as $row )
            {
                $this->normalizePathDataRow( $pathElementData, $row );
            }
            $normalizedPathData[$level] = $pathElementData;
        }
        return $normalizedPathData;
    }
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper::normalizePathDataRow (array & $pathElementData, array $row) protected
Parameters
array $pathElementData
array $row
Returns
void
Definition at line 155 of file Mapper.php.
    {
        $languageCodes = $this->languageMaskGenerator->extractLanguageCodesFromMask( $row["lang_mask"] );
        $pathElementData["always-available"] = $this->languageMaskGenerator->isAlwaysAvailable( $row["lang_mask"] );
        if ( !empty( $languageCodes ) )
        {
            foreach ( $languageCodes as $languageCode )
            {
                $pathElementData["translations"][$languageCode] = $row["text"];
            }
        }
        else if ( $pathElementData["always-available"] )
        {
            // NOP entry, lang_mask == 1
            $pathElementData["translations"]["always-available"] = $row["text"];
        }
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Mapper::$languageMaskGenerator protected
Definition at line 25 of file Mapper.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Mapper.php