ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase Class Reference
Public Member Functions
__construct (EzcDbHandler $handler, CriteriaConverter $criteriaConverter, SortClauseConverter $sortClauseConverter, QueryBuilder $queryBuilder, LanguageHandler $languageHandler, LanguageMaskGenerator $languageMaskGenerator)
find (Criterion $criterion, $offset=0, $limit=null, array $sort=null, array $translations=null)
Public Attributes
const MAX_LIMIT = 1073741824
Protected Member Functions
getQueryCondition (Criterion $criterion, ezcQuerySelect $query, $translations)
getResultCount (Criterion $criterion, $sort, $translations)
getContentIds (Criterion $criterion, $sort, $offset, $limit, $translations)
loadContent (array $contentIds, $translations)
Protected Attributes
$handler
$criteriaConverter
$sortClauseConverter
$queryBuilder
$languageHandler
$languageMaskGenerator
Detailed Description
Content locator gateway implementation using the zeta handler component.
Definition at line 24 of file EzcDatabase.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::__construct (EzcDbHandler $handler, CriteriaConverter $criteriaConverter, SortClauseConverter $sortClauseConverter, QueryBuilder $queryBuilder, LanguageHandler $languageHandler, LanguageMaskGenerator $languageMaskGenerator)
Construct from handler handler
Parameters
\EzcDbHandler $handler
Returns
void
Definition at line 81 of file EzcDatabase.php.
    {
        $this->handler = $handler;
        $this->criteriaConverter = $criteriaConverter;
        $this->sortClauseConverter = $sortClauseConverter;
        $this->queryBuilder = $queryBuilder;
        $this->languageHandler = $languageHandler;
        $this->languageMaskGenerator = $languageMaskGenerator;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::find (Criterion $criterion, $offset = 0, $limit = null, array $sort = null, array $translations = null)
Returns a list of object satisfying the $criterion.
Todo:
Check Query recreation in this method. Something breaks if we reuse the query, after we have added the applyJoin() stuff here.
Parameters
Criterion $criterion
int $offset
int | null $limit
\eZ\Publish\API\Repository\Values\Content\Query\SortClause[] $sort
string[] $translations
Returns
mixed[][]
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway.
Definition at line 112 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase\getContentIds(), eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase\getResultCount(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase\loadContent().
    {
        $limit = $limit !== null ? $limit : self::MAX_LIMIT;
        $count = $this->getResultCount( $criterion, $sort, $translations );
        if ( $count === 0 || $limit === 0 )
        {
            return array( 'count' => $count, 'rows' => array() );
        }
        $contentIds = $this->getContentIds( $criterion, $sort, $offset, $limit, $translations );
        return array(
            'count' => $count,
            'rows' => $this->loadContent( $contentIds, $translations ),
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::getContentIds (Criterion $criterion, $sort, $offset, $limit, $translations) protected
Get sorted arrays of content IDs, which should be returned
Parameters
Criterion $criterion
array $sort
mixed $offset
mixed $limit
mixed $translations
Returns
int[]
Definition at line 222 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase\getContentIds(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase\getQueryCondition().
    {
        $query = $this->handler->createSelectQuery();
        $query->select(
            $this->handler->quoteColumn( 'id', 'ezcontentobject' )
        );
        if ( $sort !== null )
        {
            $this->sortClauseConverter->applySelect( $query, $sort );
        }
        $query->from(
            $this->handler->quoteTable( 'ezcontentobject' )
        );
        $query->innerJoin(
            'ezcontentobject_version',
            'ezcontentobject.id',
            'ezcontentobject_version.contentobject_id'
        );
        if ( $sort !== null )
        {
            $this->sortClauseConverter->applyJoin( $query, $sort );
        }
        $query->where(
            $this->getQueryCondition( $criterion, $query, $translations )
        );
        if ( $sort !== null )
        {
            $this->sortClauseConverter->applyOrderBy( $query, $sort );
        }
        $query->limit( $limit, $offset );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_COLUMN );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::getQueryCondition (Criterion $criterion, ezcQuerySelect $query, $translations) protected
Get query condition
Parameters
Criterion $criterion
\ezcQuerySelect $query
mixed $translations
Returns
string
Definition at line 139 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase\getQueryCondition(), and eZ\Publish\API\Repository\Values\Content\VersionInfo\STATUS_PUBLISHED.
    {
        $condition = $query->expr->lAnd(
            $this->criteriaConverter->convertCriteria( $query, $criterion ),
            $query->expr->eq(
                'ezcontentobject_version.status',
                VersionInfo::STATUS_PUBLISHED
            )
        );
        if ( $translations === null )
        {
            return $condition;
        }
        $translationQuery = $query->subSelect();
        $translationQuery->select(
            $this->handler->quoteColumn( 'contentobject_id' )
        )->from(
            $this->handler->quoteTable( 'ezcontentobject_attribute' )
        )->where(
            $translationQuery->expr->in(
                $this->handler->quoteColumn( 'language_code' ),
                $translations
            )
        );
        return $query->expr->lAnd(
            $condition,
            $query->expr->in(
                $this->handler->quoteColumn( 'id' ),
                $translationQuery
            )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::getResultCount (Criterion $criterion, $sort, $translations) protected
Get result count
Parameters
Criterion $criterion
array $sort
mixed $translations
Returns
int
Definition at line 183 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase\getQueryCondition(), and eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase\getResultCount().
    {
        $query = $this->handler->createSelectQuery();
        $query
            ->select( 'COUNT( * )' )
            ->from( $this->handler->quoteTable( 'ezcontentobject' ) )
            ->innerJoin(
                'ezcontentobject_version',
                'ezcontentobject.id',
                'ezcontentobject_version.contentobject_id'
            );
        if ( $sort !== null )
        {
            $this->sortClauseConverter->applyJoin( $query, $sort );
        }
        $query->where(
            $this->getQueryCondition( $criterion, $query, $translations )
        );
        $statement = $query->prepare();
        $statement->execute();
        return (int)$statement->fetchColumn();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::loadContent (array $contentIds, $translations) protected
Loads the actual content based on the provided IDs
Parameters
array $contentIds
mixed $translations
Returns
mixed[]
Definition at line 274 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase\loadContent(), and eZ\Publish\API\Repository\Values\Content\VersionInfo\STATUS_PUBLISHED.
    {
        $loadQuery = $this->queryBuilder->createFindQuery( $translations );
        $loadQuery->where(
            $loadQuery->expr->eq(
                'ezcontentobject_version.status',
                VersionInfo::STATUS_PUBLISHED
            ),
            $loadQuery->expr->in(
                $this->handler->quoteColumn( 'id', 'ezcontentobject' ),
                $contentIds
            )
        );
        $statement = $loadQuery->prepare();
        $statement->execute();
        $rows = $statement->fetchAll( \PDO::FETCH_ASSOC );
        // Sort array, as defined in the $contentIds array
        $contentIdOrder = array_flip( $contentIds );
        usort(
            $rows,
            function ( $current, $next ) use ( $contentIdOrder )
            {
                return $contentIdOrder[$current['ezcontentobject_id']] -
                    $contentIdOrder[$next['ezcontentobject_id']];
            }
        );
        foreach ( $rows as &$row )
        {
            $row['ezcontentobject_always_available'] = $this->languageMaskGenerator->isAlwaysAvailable( $row['ezcontentobject_language_mask'] );
            $row['ezcontentobject_main_language_code'] = $this->languageHandler->load( $row['ezcontentobject_initial_language_id'] )->languageCode;
            $row['ezcontentobject_version_languages'] = $this->languageMaskGenerator->extractLanguageIdsFromMask( $row['ezcontentobject_version_language_mask'] );
            $row['ezcontentobject_version_initial_language_code'] = $this->languageHandler->load( $row['ezcontentobject_version_initial_language_id'] )->languageCode;
        }
        return $rows;
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::$criteriaConverter protected
Definition at line 44 of file EzcDatabase.php.
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::$handler protected
Definition at line 37 of file EzcDatabase.php.
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::$languageHandler protected
Definition at line 65 of file EzcDatabase.php.
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::$languageMaskGenerator protected
Definition at line 72 of file EzcDatabase.php.
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::$queryBuilder protected
Definition at line 58 of file EzcDatabase.php.
eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::$sortClauseConverter protected
Definition at line 51 of file EzcDatabase.php.
const eZ\Publish\Core\Persistence\Legacy\Content\Search\Gateway\EzcDatabase::MAX_LIMIT = 1073741824
2^30, since PHP_INT_MAX can cause overflows in DB systems, if PHP is run on 64 bit systems
Definition at line 30 of file EzcDatabase.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Search/Gateway/EzcDatabase.php