ezp-next: eZ\Publish\Core\REST\Client\ContentService Class Reference
eZ\Publish\Core\REST\Client\ContentService Class Reference
Public Member Functions
__construct (HttpClient $client, Dispatcher $inputDispatcher, Visitor $outputVisitor, UrlHandler $urlHandler, ContentTypeService $contentTypeService)
setSession ($id)
loadContentInfo ($contentId)
loadContentInfoByRemoteId ($remoteId)
loadVersionInfo (ContentInfo $contentInfo, $versionNo=null)
loadVersionInfoById ($contentId, $versionNo=null)
loadContentByContentInfo (ContentInfo $contentInfo, array $languages=null, $versionNo=null)
loadContentByVersionInfo (VersionInfo $versionInfo, array $languages=null)
loadContent ($contentId, array $languages=null, $versionNo=null)
loadContentByRemoteId ($remoteId, array $languages=null, $versionNo=null)
createContent (ContentCreateStruct $contentCreateStruct, array $locationCreateStructs=array())
updateContentMetadata (ContentInfo $contentInfo, ContentMetadataUpdateStruct $contentMetadataUpdateStruct)
deleteContent (ContentInfo $contentInfo)
createContentDraft (ContentInfo $contentInfo, VersionInfo $versionInfo=null, User $user=null)
loadContentDrafts (User $user=null)
updateContent (VersionInfo $versionInfo, ContentUpdateStruct $contentUpdateStruct)
publishVersion (VersionInfo $versionInfo)
deleteVersion (VersionInfo $versionInfo)
loadVersions (ContentInfo $contentInfo)
copyContent (ContentInfo $contentInfo, LocationCreateStruct $destinationLocationCreateStruct, VersionInfo $versionInfo=null)
findContent (Query $query, array $fieldFilters, $filterOnUserPermissions=true)
findSingle (Query $query, array $fieldFilters, $filterOnUserPermissions=true)
loadRelations (VersionInfo $versionInfo)
loadRelationsByListId ($relationListId)
loadReverseRelations (ContentInfo $contentInfo)
addRelation (VersionInfo $sourceVersion, ContentInfo $destinationContent)
deleteRelation (VersionInfo $sourceVersion, ContentInfo $destinationContent)
newContentCreateStruct (ContentType $contentType, $mainLanguageCode)
newContentMetadataUpdateStruct ()
newContentUpdateStruct ()
translateVersion (TranslationInfo $translationInfo, TranslationValues $translationValues, User $user=null)
addTranslationInfo (TranslationInfo $translationInfo)
loadTranslationInfos (ContentInfo $contentInfo, array $filter=array())
newTranslationInfo ()
newTranslationValues ()
Protected Member Functions
completeContentInfo (Values\RestContentInfo $restContentInfo)
fetchCurrentVersionUrl ($currentVersionReference)
isErrorResponse (Message $response)
Detailed Description
Definition at line 36 of file ContentService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Client\ContentService::__construct (HttpClient $client, Dispatcher $inputDispatcher, Visitor $outputVisitor, UrlHandler $urlHandler, ContentTypeService $contentTypeService)
Parameters
\eZ\Publish\Core\REST\Client\HttpClient $client
\eZ\Publish\Core\REST\Common\Input\Dispatcher $inputDispatcher
\eZ\Publish\Core\REST\Common\Output\Visitor $outputVisitor
\eZ\Publish\Core\REST\Common\UrlHandler $urlHandler
\eZ\Publish\Core\REST\Client\ContentTypeService $contentTypeService
Definition at line 70 of file ContentService.php.
    {
        $this->client          = $client;
        $this->inputDispatcher = $inputDispatcher;
        $this->outputVisitor   = $outputVisitor;
        $this->urlHandler      = $urlHandler;
        $this->contentTypeService = $contentTypeService;
    }
Member Function Documentation
eZ\Publish\Core\REST\Client\ContentService::addRelation (VersionInfo $sourceVersion, ContentInfo $destinationContent)
Adds a relation of type common.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to edit this version
\eZ\Publish\API\Repository\Exceptions\BadStateException if the version is not a draft
The source of the relation is the content and version referenced by $versionInfo.
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $sourceVersion
\eZ\Publish\API\Repository\Values\Content\ContentInfo $destinationContent the destination of the relation
Returns
the newly created relation
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 646 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::addTranslationInfo (TranslationInfo $translationInfo)
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 738 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::completeContentInfo (Values\RestContentInfo $restContentInfo) protected
Returns a complete ContentInfo based on $restContentInfo
Parameters
\eZ\Publish\Core\REST\Client\Values\RestContentInfo $restContentInfo
Returns
Definition at line 160 of file ContentService.php.
References eZ\Publish\Core\REST\Client\ContentService\fetchCurrentVersionUrl().
    {
        $versionUrlValues = $this->urlHandler->parse(
            'objectVersion',
            $this->fetchCurrentVersionUrl( $restContentInfo->currentVersionReference )
        );
        return new Values\Content\ContentInfo(
            $this->contentTypeService,
            array(
                'id' => $restContentInfo->id,
                'name' => $restContentInfo->name,
                'contentTypeId' => $restContentInfo->contentTypeId,
                'ownerId' => $restContentInfo->ownerId,
                'modificationDate' => $restContentInfo->modificationDate,
                'publishedDate' => $restContentInfo->publishedDate,
                'published' => $restContentInfo->published,
                'alwaysAvailable' => $restContentInfo->alwaysAvailable,
                'remoteId' => $restContentInfo->remoteId,
                'mainLanguageCode' => $restContentInfo->mainLanguageCode,
                'mainLocationId' => $restContentInfo->mainLocationId,
                'sectionId' => $restContentInfo->sectionId,
                'currentVersionNo' => $versionUrlValues['version'],
            )
        );
    }
eZ\Publish\Core\REST\Client\ContentService::copyContent (ContentInfo $contentInfo, LocationCreateStruct $destinationLocationCreateStruct, VersionInfo $versionInfo = null)
Copies the content to a new location. If no version is given, all versions are copied, otherwise only the given version.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to copy the content to the given location
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
\eZ\Publish\API\Repository\Values\Content\LocationCreateStruct $destinationLocationCreateStruct the target location where the content is copied to
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 544 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::createContent (ContentCreateStruct $contentCreateStruct, array $locationCreateStructs = array())
Creates a new content draft assigned to the authenticated user.
If a different userId is given in $contentCreateStruct it is assigned to the given user but this required special rights for the authenticated user (this is useful for content staging where the transfer process does not have to authenticate with the user which created the content object in the source server). The user has to publish the draft if it should be visible. In 4.x at least one location has to be provided in the location creation array.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to create the content in the given location
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if there is a provided remoteId which exists in the system or (4.x) there is no location provided
\eZ\Publish\API\Repository\Exceptions\ContentFieldValidationException if a field in the $contentCreateStruct is not valid
\eZ\Publish\API\Repository\Exceptions\ContentValidationException if a required field is missing
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentCreateStruct $contentCreateStruct
\eZ\Publish\API\Repository\Values\Content\LocationCreateStruct[] $locationCreateStructs For each location parent under which a location should be created for the content
Returns
- the newly created content draft
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 398 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::createContentDraft (ContentInfo $contentInfo, VersionInfo $versionInfo = null, User $user = null)
Creates a draft from a publshed or archived version.
If no version is given, the current published version is used. 4.x: The draft is created with the initialLanguge code of the source version or if not present with the main language. It can be changed on updating the version.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to create the draft
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
\eZ\Publish\API\Repository\Values\User\User $user if set given user is used to create the draft - otherwise the current user is used
Returns
- the newly created content draft
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 448 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::deleteContent (ContentInfo $contentInfo)
Deletes a content object including all its versions and locations including their subtrees.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowd to delete the content (in one of the locations of the given content object)
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 428 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::deleteRelation (VersionInfo $sourceVersion, ContentInfo $destinationContent)
Removes a relation of type COMMON from a draft.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed edit this version
\eZ\Publish\API\Repository\Exceptions\BadStateException if the version is not a draft
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if there is no relation of type COMMON for the given destination
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $sourceVersion
\eZ\Publish\API\Repository\Values\Content\ContentInfo $destinationContent
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 661 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::deleteVersion (VersionInfo $versionInfo)
removes the given version
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException if the version is in state published
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to remove this version
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 513 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::fetchCurrentVersionUrl ($currentVersionReference) protected
Returns the URL of the current version referenced by $currentVersionReference
Parameters
string $currentVersionReference
Returns
string
Definition at line 196 of file ContentService.php.
References eZ\Publish\Core\REST\Client\ContentService\isErrorResponse().
    {
        $versionResponse = $this->client->request(
            'GET',
            $currentVersionReference
        );
        if ( $this->isErrorResponse( $versionResponse ) )
        {
            return $this->inputDispatcher->parse( $versionResponse );
        }
        return $versionResponse->headers['Location'];
    }
eZ\Publish\Core\REST\Client\ContentService::findContent (Query $query, array $fieldFilters, $filterOnUserPermissions = true)
Finds content objects for the given query.
Todo:
define structs for the field filters
Parameters
\eZ\Publish\API\Repository\Values\Content\Query $query
array $fieldFilters - a map of filters for the returned fields. Currently supported: array("languages" => array(<language1>,..)).
boolean $filterOnUserPermissions if true only the objects which is the user allowed to read are returned.
Returns
Definition at line 561 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::findSingle (Query $query, array $fieldFilters, $filterOnUserPermissions = true)
Performs a query for a single content object
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the object was not found by the query or due to permissions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the query would return more than one result
Todo:
define structs for the field filters
Parameters
\eZ\Publish\API\Repository\Values\Content\Query $query
array $fieldFilters - a map of filters for the returned fields. Currently supported: array("languages" => array(<language1>,..)).
boolean $filterOnUserPermissions if true only the objects which is the user allowed to read are returned.
Returns
Definition at line 580 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::isErrorResponse (Message $response) protected
Checks if the given response is an error
Parameters
Message $response
Returns
boolean
Definition at line 218 of file ContentService.php.
    {
        return (
            strpos( $response->headers['Content-Type'], 'application/vnd.ez.api.ErrorMessage' ) === 0
        );
    }
eZ\Publish\Core\REST\Client\ContentService::loadContent ($contentId, array $languages = null, $versionNo = null)
Loads content in a version of the given content object.
If no version number is given, the method returns the current version
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the content or version with the given id does not exist
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
int $contentId
array $languages A language filter for fields. If not given all languages are returned
int $versionNo the version number. If not given the current version is returned.
Returns
Todo:
Handle $versionNo = null
Handle language filters
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 317 of file ContentService.php.
References eZ\Publish\Core\REST\Client\ContentService\fetchCurrentVersionUrl().
    {
        // $contentId should already be a URL!
        $contentIdValues = $this->urlHandler->parse( 'object', $contentId );
        $url = '';
        if ( $versionNo === null )
        {
            $url = $this->fetchCurrentVersionUrl(
                $this->urlHandler->generate(
                    'objectCurrentVersion',
                    array(
                        'object' => $contentIdValues['object'],
                    )
                )
            );
        }
        else
        {
            $url = $this->urlHandler->generate(
                'objectVersion',
                array(
                    'object' => $contentIdValues['object'],
                    'version' => $versionNo,
                )
            );
        }
        $response = $this->client->request(
            'GET',
            $url,
            new Message(
                array( 'Accept' => $this->outputVisitor->getMediaType( 'Version' ) )
            )
        );
        return $this->inputDispatcher->parse( $response );
    }
eZ\Publish\Core\REST\Client\ContentService::loadContentByContentInfo (ContentInfo $contentInfo, array $languages = null, $versionNo = null)
Loads content in a version for the given content info object.
If no version number is given, the method returns the current version
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if version with the given number does not exist
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
array $languages A language filter for fields. If not given all languages are returned
int $versionNo the version number. If not given the current version is returned.
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 275 of file ContentService.php.
References eZ\Publish\Core\REST\Client\ContentService\loadContent().
    {
        return $this->loadContent(
            $contentInfo->id,
            $languages,
            $versionNo
        );
    }
eZ\Publish\Core\REST\Client\ContentService::loadContentByRemoteId ($remoteId, array $languages = null, $versionNo = null)
Loads content in a version for the content object reference by the given remote id.
If no version is given, the method returns the current version
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the content or version with the given remote id does not exist
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
string $remoteId
array $languages A language filter for fields. If not given all languages are returned
int $versionNo the version number. If not given the current version is returned.
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 370 of file ContentService.php.
References eZ\Publish\Core\REST\Client\ContentService\loadContentByContentInfo(), and eZ\Publish\Core\REST\Client\ContentService\loadContentInfoByRemoteId().
    {
        $contentInfo = $this->loadContentInfoByRemoteId( $remoteId );
        return $this->loadContentByContentInfo( $contentInfo, $languages, $versionNo );
    }
eZ\Publish\Core\REST\Client\ContentService::loadContentByVersionInfo (VersionInfo $versionInfo, array $languages = null)
Loads content in the version given by version info.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
array $languages A language filter for fields. If not given all languages are returned
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 294 of file ContentService.php.
References eZ\Publish\API\Repository\Values\Content\VersionInfo\getContentInfo(), and eZ\Publish\Core\REST\Client\ContentService\loadContent().
    {
        $contentInfo = $versionInfo->getContentInfo();
        return $this->loadContent( $contentInfo->id, $languages, $versionInfo->versionNo );
    }
eZ\Publish\Core\REST\Client\ContentService::loadContentDrafts (User $user = null)
Loads drafts for a user.
If no user is given the drafts for the authenticated user a returned
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load the draft list
Parameters
\eZ\Publish\API\Repository\Values\User\User $user
Returns
the drafts (VersionInfo) owned by the given user
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 464 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::loadContentInfo ($contentId)
Loads a content info object.
To load fields use loadContent
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to read the content
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the content with the given id does not exist
Parameters
int $contentId
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 108 of file ContentService.php.
References eZ\Publish\Core\REST\Client\ContentService\completeContentInfo().
    {
        $response = $this->client->request(
            'GET',
            $contentId,
            new Message(
                array( 'Accept' => $this->outputVisitor->getMediaType( 'ContentInfo' ) )
            )
        );
        $restContentInfo = $this->inputDispatcher->parse( $response );
        return $this->completeContentInfo( $restContentInfo );
    }
eZ\Publish\Core\REST\Client\ContentService::loadContentInfoByRemoteId ($remoteId)
Loads a content info object for the given remoteId.
To load fields use loadContent
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowd to create the content in the given location
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the content with the given remote id does not exist
Parameters
string $remoteId
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 134 of file ContentService.php.
References eZ\Publish\Core\REST\Client\ContentService\completeContentInfo().
    {
        $response = $this->client->request(
            'GET',
            $this->urlHandler->generate( 'objectByRemote', array( 'object' => $remoteId ) ),
            new Message(
                array( 'Accept' => $this->outputVisitor->getMediaType( 'ContentList' ) )
            )
        );
        $contentList = $this->inputDispatcher->parse( $response );
        if ( empty( $contentList ) )
        {
            throw new Exceptions\NotFoundException( "@todo: Error message." );
        }
        return $this->completeContentInfo( reset( $contentList ) );
    }
eZ\Publish\Core\REST\Client\ContentService::loadRelations (VersionInfo $versionInfo)
Loads all outgoing relations for the given version
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to read this version
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
Returns
[]
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 594 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::loadRelationsByListId ($relationListId)
Loads relations by their relation list ID
NOTE: This method is not part of the API!
Parameters
string $relationListId protected
Returns
[]
Definition at line 610 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::loadReverseRelations (ContentInfo $contentInfo)
Loads all incoming relations for a content object.
The relations come only from published versions of the source content objects
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to read this version
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
Returns
[]
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 627 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::loadTranslationInfos (ContentInfo $contentInfo, array $filter = array())
lists the translations done on this content object
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed read translation infos
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
array $filter
Todo:
TBD - filter by sourceversion destination version and languages
Returns
[]
Since
5.0
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 757 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::loadVersionInfo (ContentInfo $contentInfo, $versionNo = null)
Loads a version info of the given content object.
If no version number is given, the method returns the current version
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the version with the given number does not exist
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
int $versionNo the version number. If not given the current version is returned.
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 238 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::loadVersionInfoById ($contentId, $versionNo = null)
Loads a version info of the given content object id.
If no version number is given, the method returns the current version
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the version with the given number does not exist
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
int $contentId
int $versionNo the version number. If not given the current version is returned.
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 256 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::loadVersions (ContentInfo $contentInfo)
Loads all versions for the given content
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to list versions
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
Returns
[] Sorted by creation date
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 527 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::newContentCreateStruct (ContentType $contentType, $mainLanguageCode)
Instantiates a new content create struct object
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType
string $mainLanguageCode
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 674 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::newContentMetadataUpdateStruct ()
Instantiates a new content meta data update struct
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 684 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::newContentUpdateStruct ()
Instantiates a new content update struct
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 693 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::newTranslationInfo ()
Instantiates a new TranslationInfo object
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 766 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::newTranslationValues ()
Instantiates a Translation object
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 775 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::publishVersion (VersionInfo $versionInfo)
Publishes a content version
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to publish this version
\eZ\Publish\API\Repository\Exceptions\BadStateException if the version is not a draft
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to publish this version
\eZ\Publish\API\Repository\Exceptions\BadStateException if the version is not a draft
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 500 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::setSession ($id)
Set session ID
Only for testing
Parameters
mixed $id
Implements eZ\Publish\Core\REST\Client\Sessionable.
Definition at line 88 of file ContentService.php.
    {
        if ( $this->outputVisitor instanceof Sessionable )
        {
            $this->outputVisitor->setSession( $id );
        }
    }
eZ\Publish\Core\REST\Client\ContentService::translateVersion (TranslationInfo $translationInfo, TranslationValues $translationValues, User $user = null)
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 722 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::updateContent (VersionInfo $versionInfo, ContentUpdateStruct $contentUpdateStruct)
Updates the fields of a draft.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to update this version
\eZ\Publish\API\Repository\Exceptions\BadStateException if the version is not a draft
\eZ\Publish\API\Repository\Exceptions\ContentFieldValidationException if a field in the $contentUpdateStruct is not valid
\eZ\Publish\API\Repository\Exceptions\ContentValidationException if a required field is set to an empty value
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
\eZ\Publish\API\Repository\Values\Content\ContentUpdateStruct $contentUpdateStruct
Returns
the content draft with the updated fields
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 482 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\ContentService::updateContentMetadata (ContentInfo $contentInfo, ContentMetadataUpdateStruct $contentMetadataUpdateStruct)
Updates the metadata.
(see ContentMetadataUpdateStruct) of a content object - to update fields use updateContent
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowd to update the content meta data
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the remoteId in $contentMetadataUpdateStruct is set but already existis
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
\eZ\Publish\API\Repository\Values\Content\ContentMetadataUpdateStruct $contentMetadataUpdateStruct
Returns
the content with the updated attributes
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 416 of file ContentService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Client/ContentService.php