ezp-next: eZ\Publish\Core\Repository\IOService Class Reference
eZ\Publish\Core\Repository\IOService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, Handler $handler, array $settings=array())
setLegacyKernel (LegacyKernel $legacyKernel)
newBinaryCreateStructFromUploadedFile (array $uploadedFile)
newBinaryCreateStructFromLocalFile ($localFile)
createBinaryFile (BinaryFileCreateStruct $binaryFileCreateStruct)
deleteBinaryFile (BinaryFile $binaryFile)
loadBinaryFile ($binaryFileid)
getFileInputStream (BinaryFile $binaryFile)
getFileContents (BinaryFile $binaryFile)
Public Member Functions inherited from eZ\Publish\Core\MVC\Legacy\LegacyKernelAware
setLegacyKernel (Kernel $legacyKernel)
Protected Member Functions
getLegacyKernel ()
buildSPIBinaryFileCreateStructObject (BinaryFileCreateStruct $binaryFileCreateStruct)
buildDomainBinaryFileObject (SPIBinaryFile $spiBinaryFile)
Protected Attributes
$repository
$ioHandler
$settings
$legacyKernel
Detailed Description
Definition at line 29 of file IOService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\IOService::__construct (RepositoryInterface $repository, Handler $handler, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\API\Repository\Repository $repository
\eZ\Publish\SPI\IO\Handler $handler
array $settings
Definition at line 58 of file IOService.php.
References eZ\Publish\Core\Repository\IOService\$repository, and eZ\Publish\Core\Repository\IOService\$settings.
    {
        $this->repository = $repository;
        $this->ioHandler = $handler;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            //'defaultSetting' => array(),
        );
    }
Member Function Documentation
eZ\Publish\Core\Repository\IOService::buildDomainBinaryFileObject (SPIBinaryFile $spiBinaryFile) protected
Generates API BinaryFile object from provided SPI BinaryFile object
Parameters
\eZ\Publish\SPI\IO\BinaryFile $spiBinaryFile
Returns
Definition at line 276 of file IOService.php.
    {
        return new BinaryFile(
            array(
                //@todo is setting the id of file to path correct?
                'id' => $spiBinaryFile->path,
                'size' => (int)$spiBinaryFile->size,
                'mtime' => $spiBinaryFile->mtime,
                'ctime' => $spiBinaryFile->ctime,
                'mimeType' => $spiBinaryFile->mimeType,
                'uri' => $spiBinaryFile->uri,
                'originalFile' => $spiBinaryFile->originalFile
            )
        );
    }
eZ\Publish\Core\Repository\IOService::buildSPIBinaryFileCreateStructObject (BinaryFileCreateStruct $binaryFileCreateStruct) protected
Generates SPI BinaryFileCreateStruct object from provided API BinaryFileCreateStruct object
Parameters
\eZ\Publish\API\Repository\Values\IO\BinaryFileCreateStruct $binaryFileCreateStruct
Returns
Definition at line 256 of file IOService.php.
    {
        $spiBinaryCreateStruct = new SPIBinaryFileCreateStruct();
        $spiBinaryCreateStruct->path = $binaryFileCreateStruct->uri;
        $spiBinaryCreateStruct->size = $binaryFileCreateStruct->size;
        $spiBinaryCreateStruct->mimeType = $binaryFileCreateStruct->mimeType;
        $spiBinaryCreateStruct->originalFile = $binaryFileCreateStruct->originalFileName;
        $spiBinaryCreateStruct->setInputStream( $binaryFileCreateStruct->inputStream );
        return $spiBinaryCreateStruct;
    }
eZ\Publish\Core\Repository\IOService::createBinaryFile (BinaryFileCreateStruct $binaryFileCreateStruct)
Creates a binary file in the repository
Parameters
\eZ\Publish\API\Repository\Values\IO\BinaryFileCreateStruct $binaryFileCreateStruct
Returns
The created BinaryFile object
Implements eZ\Publish\API\Repository\IOService.
Definition at line 159 of file IOService.php.
References eZ\Publish\Core\Repository\IOService\buildDomainBinaryFileObject(), and eZ\Publish\Core\Repository\IOService\buildSPIBinaryFileCreateStructObject().
    {
        if ( empty( $binaryFileCreateStruct->mimeType ) || !is_string( $binaryFileCreateStruct->mimeType ) )
            throw new InvalidArgumentValue( "mimeType", "invalid mimeType value", "BinaryFileCreateStruct" );
        if ( empty( $binaryFileCreateStruct->uri ) || !is_string( $binaryFileCreateStruct->uri ) )
            throw new InvalidArgumentValue( "uri", $binaryFileCreateStruct->uri, "BinaryFileCreateStruct" );
        if ( empty( $binaryFileCreateStruct->originalFileName ) || !is_string( $binaryFileCreateStruct->originalFileName ) )
            throw new InvalidArgumentValue( "originalFileName", $binaryFileCreateStruct->originalFileName, "BinaryFileCreateStruct" );
        if ( !is_int( $binaryFileCreateStruct->size ) || $binaryFileCreateStruct->size < 0 )
            throw new InvalidArgumentValue( "size", $binaryFileCreateStruct->size, "BinaryFileCreateStruct" );
        if ( !is_resource( $binaryFileCreateStruct->inputStream ) )
            throw new InvalidArgumentValue( "inputStream", "property is not a file resource", "BinaryFileCreateStruct" );
        $spiBinaryCreateStruct = $this->buildSPIBinaryFileCreateStructObject( $binaryFileCreateStruct );
        $spiBinaryFile = $this->ioHandler->create( $spiBinaryCreateStruct );
        return $this->buildDomainBinaryFileObject( $spiBinaryFile );
    }
eZ\Publish\Core\Repository\IOService::deleteBinaryFile (BinaryFile $binaryFile)
Deletes the BinaryFile with $path
Parameters
\eZ\Publish\API\Repository\Values\IO\BinaryFile $binaryFile
Implements eZ\Publish\API\Repository\IOService.
Definition at line 188 of file IOService.php.
    {
        //@todo: is $binaryFile->id equal to file path?
        if ( empty( $binaryFile->id ) || !is_string( $binaryFile->id ) )
            throw new InvalidArgumentValue( "id", $binaryFile->id, "BinaryFile" );
        $this->ioHandler->delete( $binaryFile->id );
    }
eZ\Publish\Core\Repository\IOService::getFileContents (BinaryFile $binaryFile)
Returns the content of the binary file
Parameters
\eZ\Publish\API\Repository\Values\IO\BinaryFile $binaryFile
Returns
string
Implements eZ\Publish\API\Repository\IOService.
Definition at line 240 of file IOService.php.
    {
        if ( empty( $binaryFile->id ) || !is_string( $binaryFile->id ) )
            throw new InvalidArgumentValue( "id", $binaryFile->id, "BinaryFile" );
        //@todo: is binary file ID equal to file path?
        return $this->ioHandler->getFileContents( $binaryFile->id );
    }
eZ\Publish\Core\Repository\IOService::getFileInputStream (BinaryFile $binaryFile)
Returns a read (mode: rb) file resource to the binary file identified by $path
Parameters
\eZ\Publish\API\Repository\Values\IO\BinaryFile $binaryFile
Returns
resource
Implements eZ\Publish\API\Repository\IOService.
Definition at line 224 of file IOService.php.
    {
        if ( empty( $binaryFile->id ) || !is_string( $binaryFile->id ) )
            throw new InvalidArgumentValue( "id", $binaryFile->id, "BinaryFile" );
        //@todo: is binary file ID equal to file path?
        return $this->ioHandler->getFileResource( $binaryFile->id );
    }
eZ\Publish\Core\Repository\IOService::getLegacyKernel () protected
Gets the legacy kernel instance.
Returns
Definition at line 85 of file IOService.php.
References eZ\Publish\Core\Repository\IOService\$legacyKernel.
    {
        return $this->legacyKernel;
    }
eZ\Publish\Core\Repository\IOService::loadBinaryFile ($binaryFileid)
Loads the binary file with $id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException
Parameters
string $binaryFileid
Returns
Implements eZ\Publish\API\Repository\IOService.
Definition at line 206 of file IOService.php.
References eZ\Publish\Core\Repository\IOService\buildDomainBinaryFileObject().
    {
        if ( empty( $binaryFileid ) || !is_string( $binaryFileid ) )
            throw new InvalidArgumentValue( "binaryFileid", $binaryFileid );
        //@todo: is binaryFileid equal to path?
        $spiBinaryFile = $this->ioHandler->load( $binaryFileid );
        return $this->buildDomainBinaryFileObject( $spiBinaryFile );
    }
eZ\Publish\Core\Repository\IOService::newBinaryCreateStructFromLocalFile ($localFile)
Creates a BinaryFileCreateStruct object from $localFile
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException When given a non existing / unreadable file
Parameters
string $localFile Path to local file
Returns
Implements eZ\Publish\API\Repository\IOService.
Definition at line 130 of file IOService.php.
    {
        if ( empty( $localFile ) || !is_string( $localFile ) )
            throw new InvalidArgumentException( "localFile", "localFile has an invalid value" );
        if ( !is_file( $localFile ) || !is_readable( $localFile ) )
            throw new InvalidArgumentException( "localFile", "file does not exist or is unreadable: {$localFile}" );
        $fileHandle = fopen( $localFile, 'rb' );
        if ( $fileHandle === false )
            throw new InvalidArgumentException( "localFile", "failed to get file resource" );
        $binaryCreateStruct = new BinaryFileCreateStruct();
        $binaryCreateStruct->mimeType = mime_content_type( $localFile );
        $binaryCreateStruct->uri = $localFile;
        $binaryCreateStruct->originalFileName = basename( $localFile );
        $binaryCreateStruct->size = filesize( $localFile );
        $binaryCreateStruct->inputStream = $fileHandle;
        return $binaryCreateStruct;
    }
eZ\Publish\Core\Repository\IOService::newBinaryCreateStructFromUploadedFile (array $uploadedFile)
Creates a BinaryFileCreateStruct object from the uploaded file $uploadedFile
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException When given an invalid uploaded file
Parameters
array $uploadedFile The $_POST hash of an uploaded file
Returns
Implements eZ\Publish\API\Repository\IOService.
Definition at line 99 of file IOService.php.
    {
        if ( !is_string( $uploadedFile['tmp_name'] ) || empty( $uploadedFile['tmp_name'] ) )
            throw new InvalidArgumentException( "uploadedFile", "uploadedFile['tmp_name'] does not exist or has invalid value" );
        if ( !is_uploaded_file( $uploadedFile['tmp_name'] ) || !is_readable( $uploadedFile['tmp_name'] ) )
            throw new InvalidArgumentException( "uploadedFile", "file was not uploaded or is unreadable" );
        $fileHandle = fopen( $uploadedFile['tmp_name'], 'rb' );
        if ( $fileHandle === false )
            throw new InvalidArgumentException( "uploadedFile", "failed to get file resource" );
        $binaryCreateStruct = new BinaryFileCreateStruct();
        $binaryCreateStruct->mimeType = $uploadedFile['type'];
        $binaryCreateStruct->uri = $uploadedFile['tmp_name'];
        $binaryCreateStruct->originalFileName = $uploadedFile['name'];
        $binaryCreateStruct->size = $uploadedFile['size'];
        $binaryCreateStruct->inputStream = $fileHandle;
        return $binaryCreateStruct;
    }
eZ\Publish\Core\Repository\IOService::setLegacyKernel (LegacyKernel $legacyKernel)
Injects the legacy kernel instance.
Parameters
\eZ\Publish\Core\MVC\Legacy\Kernel $legacyKernel
Returns
void
Definition at line 75 of file IOService.php.
References eZ\Publish\Core\Repository\IOService\$legacyKernel.
    {
        $this->legacyKernel = $legacyKernel;
    }
Member Data Documentation
eZ\Publish\Core\Repository\IOService::$ioHandler protected
Definition at line 39 of file IOService.php.
eZ\Publish\Core\Repository\IOService::$legacyKernel protected
Definition at line 49 of file IOService.php.
eZ\Publish\Core\Repository\IOService::$repository protected
Definition at line 34 of file IOService.php.
eZ\Publish\Core\Repository\IOService::$settings protected
Definition at line 44 of file IOService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/IOService.php