ezp-next: eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\FieldDefinitionList Class Reference
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\FieldDefinitionList Class Reference
Public Member Functions
visit (Visitor $visitor, Generator $generator, $data)
Additional Inherited Members
Protected Member Functions inherited from eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestContentTypeBase
getUrlTypeSuffix ($contentTypeStatus)
serializeStatus ($contentTypeStatus)
Protected Attributes inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
$urlHandler
Detailed Description
FieldDefinitionList value object visitor
Definition at line 20 of file FieldDefinitionList.php.
Member Function Documentation
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\FieldDefinitionList::visit (Visitor $visitor, Generator $generator, $data)
Visit struct returned by controllers
Parameters
\eZ\Publish\Core\REST\Common\Output\Visitor $visitor
\eZ\Publish\Core\REST\Common\Output\Generator $generator
\eZ\Publish\Core\REST\Server\Values\FieldDefinitionList $data
Reimplemented from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor.
Definition at line 29 of file FieldDefinitionList.php.
References eZ\Publish\Core\REST\Common\Output\Generator\endAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\endList(), eZ\Publish\Core\REST\Common\Output\Generator\endObjectElement(), eZ\Publish\Core\REST\Common\Output\Generator\getMediaType(), eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\RestContentTypeBase\getUrlTypeSuffix(), eZ\Publish\Core\REST\Common\Output\Visitor\setHeader(), eZ\Publish\Core\REST\Common\Output\Generator\startAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\startList(), eZ\Publish\Core\REST\Common\Output\Generator\startObjectElement(), and eZ\Publish\Core\REST\Common\Output\Visitor\visitValueObject().
    {
        $fieldDefinitionList = $data;
        $contentType = $fieldDefinitionList->contentType;
        $urlTypeSuffix = $this->getUrlTypeSuffix( $contentType->status );
        $generator->startObjectElement( 'FieldDefinitions', 'FieldDefinitionList' );
        $visitor->setHeader( 'Content-Type', $generator->getMediaType( 'FieldDefinitionList' ) );
        //@todo Needs refactoring, disabling certain headers should not be done this way
        $visitor->setHeader( 'Accept-Patch', false );
        $generator->startAttribute(
            'href',
            $this->urlHandler->generate(
                'typeFieldDefinitions'  . $urlTypeSuffix,
                array(
                    'type' => $contentType->id
                )
            )
        );
        $generator->endAttribute( 'href' );
        $generator->startList( 'FieldDefinition' );
        foreach ( $fieldDefinitionList->fieldDefinitions as $fieldDefinition )
        {
            $visitor->visitValueObject(
                new ValuesRestFieldDefinition( $contentType, $fieldDefinition )
            );
        }
        $generator->endList( 'FieldDefinition' );
        $generator->endObjectElement( 'FieldDefinitions' );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/FieldDefinitionList.php