ezp-next: eZ\Publish\Core\REST\Client\RoleService Class Reference
eZ\Publish\Core\REST\Client\RoleService Class Reference
Public Member Functions
__construct (UserService $userService, HttpClient $client, Input\Dispatcher $inputDispatcher, Output\Visitor $outputVisitor, UrlHandler $urlHandler)
setSession ($id)
createRole (APIRoleCreateStruct $roleCreateStruct)
updateRole (APIRole $role, RoleUpdateStruct $roleUpdateStruct)
addPolicy (APIRole $role, APIPolicyCreateStruct $policyCreateStruct)
removePolicy (APIRole $role, APIPolicy $policy)
updatePolicy (APIPolicy $policy, APIPolicyUpdateStruct $policyUpdateStruct)
loadRole ($id)
loadRoleByIdentifier ($name)
loadRoles ()
deleteRole (APIRole $role)
loadPoliciesByUserId ($userId)
assignRoleToUserGroup (APIRole $role, UserGroup $userGroup, RoleLimitation $roleLimitation=null)
unassignRoleFromUserGroup (APIRole $role, UserGroup $userGroup)
assignRoleToUser (APIRole $role, User $user, RoleLimitation $roleLimitation=null)
unassignRoleFromUser (APIRole $role, User $user)
getRoleAssignments (APIRole $role)
getRoleAssignmentsForUser (User $user)
getRoleAssignmentsForUserGroup (UserGroup $userGroup)
newRoleCreateStruct ($name)
newPolicyCreateStruct ($module, $function)
newPolicyUpdateStruct ()
newRoleUpdateStruct ()
getLimitationType ($identifier)
getLimitationTypesByModuleFunction ($module, $function)
Public Member Functions inherited from eZ\Publish\API\Repository\RoleService
createRole (RoleCreateStruct $roleCreateStruct)
updateRole (Role $role, RoleUpdateStruct $roleUpdateStruct)
addPolicy (Role $role, PolicyCreateStruct $policyCreateStruct)
removePolicy (Role $role, Policy $policy)
updatePolicy (Policy $policy, PolicyUpdateStruct $policyUpdateStruct)
deleteRole (Role $role)
assignRoleToUserGroup (Role $role, UserGroup $userGroup, RoleLimitation $roleLimitation=null)
unassignRoleFromUserGroup (Role $role, UserGroup $userGroup)
assignRoleToUser (Role $role, User $user, RoleLimitation $roleLimitation=null)
unassignRoleFromUser (Role $role, User $user)
getRoleAssignments (Role $role)
Detailed Description
Implementation of the eZ\Publish\API\Repository\RoleServiceinterface.@see\eZ\Publish\API\Repository\RoleService
Definition at line 42 of file RoleService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Client\RoleService::__construct (UserService $userService, HttpClient $client, Input\Dispatcher $inputDispatcher, Output\Visitor $outputVisitor, UrlHandler $urlHandler)
Parameters
\eZ\Publish\Core\REST\Client\UserService $userService
\eZ\Publish\Core\REST\Client\HttpClient $client
\eZ\Publish\Core\REST\Common\Input\Dispatcher $inputDispatcher
\eZ\Publish\Core\REST\Common\Output\Visitor $outputVisitor
\eZ\Publish\Core\REST\Common\UrlHandler $urlHandler
Definition at line 76 of file RoleService.php.
References eZ\Publish\Core\REST\$urlHandler, and eZ\Publish\Core\REST\Client\RoleService\__construct().
    {
        $this->userService     = $userService;
        $this->client          = $client;
        $this->inputDispatcher = $inputDispatcher;
        $this->outputVisitor   = $outputVisitor;
        $this->urlHandler      = $urlHandler;
    }
Member Function Documentation
eZ\Publish\Core\REST\Client\RoleService::addPolicy (APIRole $role, APIPolicyCreateStruct $policyCreateStruct)
Adds a new policy to the role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to add a policy
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\PolicyCreateStruct $policyCreateStruct
Returns
Definition at line 199 of file RoleService.php.
    {
        $values = $this->urlHandler->parse( 'role', $role->id );
        $inputMessage = $this->outputVisitor->visit( $policyCreateStruct );
        $inputMessage->headers['Accept'] = $this->outputVisitor->getMediaType( 'Policy' );
        $result = $this->client->request(
            'POST',
            $this->urlHandler->generate( 'policies', array( 'role' => $values['role'] ) ),
            $inputMessage
        );
        $createdPolicy = $this->inputDispatcher->parse( $result );
        // @todo Workaround for missing roleId in Policy XSD definition
        $createdPolicyArray = array(
            'id' => $createdPolicy->id,
            'roleId' => $role->id,
            'module' => $createdPolicy->module,
            'function' => $createdPolicy->function
        );
        $createdPolicy = new Policy( $createdPolicyArray );
        $existingPolicies = $role->getPolicies();
        $existingPolicies[] = $createdPolicy;
        return new Role(
            array(
                'id' => $role->id,
                'identifier' => $role->identifier
            ),
            $existingPolicies
        );
    }
eZ\Publish\Core\REST\Client\RoleService::assignRoleToUser (APIRole $role, User $user, RoleLimitation $roleLimitation = null)
Assigns a role to the given user
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to assign a role
Todo:
add limitations
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\User $user
\eZ\Publish\API\Repository\Values\User\Limitation\RoleLimitation $roleLimitation an optional role limitation (which is either a subtree limitation or section limitation)
Definition at line 511 of file RoleService.php.
    {
        $roleAssignment = new RoleAssignment(
            array(
                'role' => $role,
                'limitation' => $roleLimitation
            )
        );
        $inputMessage = $this->outputVisitor->visit( $roleAssignment );
        $inputMessage->headers['Accept'] = $this->outputVisitor->getMediaType( 'RoleAssignmentList' );
        $result = $this->client->request(
            'POST',
            $this->urlHandler->generate( 'userRoleAssignments', array( 'user' => $user->id ) ),
            $inputMessage
        );
        $this->inputDispatcher->parse( $result );
    }
eZ\Publish\Core\REST\Client\RoleService::assignRoleToUserGroup (APIRole $role, UserGroup $userGroup, RoleLimitation $roleLimitation = null)
Assigns a role to the given user group
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to assign a role
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
\eZ\Publish\API\Repository\Values\User\Limitation\RoleLimitation $roleLimitation an optional role limitation (which is either a subtree limitation or section limitation)
Definition at line 446 of file RoleService.php.
    {
        $roleAssignment = new RoleAssignment(
            array(
                'role' => $role,
                'limitation' => $roleLimitation
            )
        );
        $inputMessage = $this->outputVisitor->visit( $roleAssignment );
        $inputMessage->headers['Accept'] = $this->outputVisitor->getMediaType( 'RoleAssignmentList' );
        $result = $this->client->request(
            'POST',
            $this->urlHandler->generate( 'groupRoleAssignments', array( 'group' => $userGroup->id ) ),
            $inputMessage
        );
        $this->inputDispatcher->parse( $result );
    }
eZ\Publish\Core\REST\Client\RoleService::createRole (APIRoleCreateStruct $roleCreateStruct)
Creates a new Role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to create a role
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the name of the role already exists
Parameters
\eZ\Publish\API\Repository\Values\User\RoleCreateStruct $roleCreateStruct
Returns
Definition at line 114 of file RoleService.php.
    {
        $inputMessage = $this->outputVisitor->visit( $roleCreateStruct );
        $inputMessage->headers['Accept'] = $this->outputVisitor->getMediaType( 'Role' );
        $result = $this->client->request(
            'POST',
            $this->urlHandler->generate( 'roles' ),
            $inputMessage
        );
        $createdRole = $this->inputDispatcher->parse( $result );
        $createdRoleValues = $this->urlHandler->parse( 'role', $createdRole->id );
        $createdPolicies = array();
        foreach ( $roleCreateStruct->getPolicies() as $policyCreateStruct )
        {
            $inputMessage = $this->outputVisitor->visit( $policyCreateStruct );
            $inputMessage->headers['Accept'] = $this->outputVisitor->getMediaType( 'Policy' );
            $result = $this->client->request(
                'POST',
                $this->urlHandler->generate( 'policies', array( 'role' => $createdRoleValues['role'] ) ),
                $inputMessage
            );
            $createdPolicy = $this->inputDispatcher->parse( $result );
            // @todo Workaround for missing roleId in Policy XSD definition
            $createdPolicyArray = array(
                'id' => $createdPolicy->id,
                'roleId' => $createdRole->id,
                'module' => $createdPolicy->module,
                'function' => $createdPolicy->function
            );
            $createdPolicy = new Policy( $createdPolicyArray );
            $createdPolicies[] = $createdPolicy;
        }
        return new Role(
            array(
                'id' => $createdRole->id,
                'identifier' => $createdRole->identifier
            ),
            $createdPolicies
        );
    }
eZ\Publish\Core\REST\Client\RoleService::deleteRole (APIRole $role)
Deletes the given role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to delete this role
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
Definition at line 396 of file RoleService.php.
    {
        $response = $this->client->request(
            'DELETE',
            $role->id,
            new Message(
                // @todo: What media-type should we set here? Actually, it should be
                // all expected exceptions + none? Or is "Section" correct,
                // since this is what is to be expected by the resource
                // identified by the URL?
                array( 'Accept' => $this->outputVisitor->getMediaType( 'Role' ) )
            )
        );
        if ( !empty( $response->body ) )
            $this->inputDispatcher->parse( $response );
    }
eZ\Publish\Core\REST\Client\RoleService::getLimitationType ($identifier)
Returns the LimitationType registered with the given identifier
Parameters
string $identifier
Returns
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if there is no LimitationType with $identifier
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 705 of file RoleService.php.
    {
        throw new \eZ\Publish\API\Repository\Exceptions\NotImplementedException( __METHOD__ );
    }
eZ\Publish\Core\REST\Client\RoleService::getLimitationTypesByModuleFunction ($module, $function)
Returns the LimitationType's assigned to a given module/function
Typically used for:
Internal validation limitation value use on Policies
Role admin gui for editing policy limitations incl list limitation options via valueSchema()
Parameters
string $module Legacy name of "controller", it's a unique identifier like "content"
string $function Legacy name of a controller "action", it's a unique within the controller like "read"
Returns
[]
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException If module/function to limitation type mapping refers to a non existing identifier.
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 725 of file RoleService.php.
    {
        throw new \eZ\Publish\API\Repository\Exceptions\NotImplementedException( __METHOD__ );
    }
eZ\Publish\Core\REST\Client\RoleService::getRoleAssignments (APIRole $role)
Returns the assigned user and user groups to this role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read a role
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
Returns
[]
Definition at line 574 of file RoleService.php.
    {
        throw new \Exception( "@todo: Implement." );
    }
eZ\Publish\Core\REST\Client\RoleService::getRoleAssignmentsForUser (User $user)
Returns the roles assigned to the given user
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read a user
Parameters
\eZ\Publish\API\Repository\Values\User\User $user
Returns
[]
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 588 of file RoleService.php.
    {
        $response = $this->client->request(
            'GET',
            $this->urlHandler->generate( 'userRoleAssignments' ),
            new Message(
                array( 'Accept' => $this->outputVisitor->getMediaType( 'RoleAssignmentList' ) )
            )
        );
        $roleAssignments = $this->inputDispatcher->parse( $response );
        $userRoleAssignments = array();
        foreach ( $roleAssignments as $roleAssignment )
        {
            $userRoleAssignments[] = new UserRoleAssignment(
                array(
                    'limitation' => $roleAssignment->getRoleLimitation(),
                    'role' => $roleAssignment->getRole(),
                    'user' => $user
                )
            );
        }
        return $userRoleAssignments;
    }
eZ\Publish\Core\REST\Client\RoleService::getRoleAssignmentsForUserGroup (UserGroup $userGroup)
Returns the roles assigned to the given user group
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read a user group
Parameters
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
Returns
[]
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 624 of file RoleService.php.
    {
        $response = $this->client->request(
            'GET',
            $this->urlHandler->generate( 'groupRoleAssignments' ),
            new Message(
                array( 'Accept' => $this->outputVisitor->getMediaType( 'RoleAssignmentList' ) )
            )
        );
        $roleAssignments = $this->inputDispatcher->parse( $response );
        $userGroupRoleAssignments = array();
        foreach ( $roleAssignments as $roleAssignment )
        {
            $userGroupRoleAssignments[] = new UserGroupRoleAssignment(
                array(
                    'limitation' => $roleAssignment->getRoleLimitation(),
                    'role' => $roleAssignment->getRole(),
                    'userGroup' => $userGroup
                )
            );
        }
        return $userGroupRoleAssignments;
    }
eZ\Publish\Core\REST\Client\RoleService::loadPoliciesByUserId ($userId)
Loads all policies from roles which are assigned to a user or to user groups to which the user belongs
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if a user with the given id was not found
Parameters
mixed $userId
Returns
[]
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 423 of file RoleService.php.
    {
        $values = $this->urlHandler->parse( 'user', $userId );
        $response = $this->client->request(
            'GET',
            $this->urlHandler->generate( 'userPolicies', array( 'user' => $values['user'] ) ),
            new Message(
                array( 'Accept' => $this->outputVisitor->getMediaType( 'PolicyList' ) )
            )
        );
        return $this->inputDispatcher->parse( $response );
    }
eZ\Publish\Core\REST\Client\RoleService::loadRole ($id)
Loads a role for the given id
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read this role
\eZ\Publish\API\Repository\Exceptions\NotFoundException if a role with the given name was not found
Parameters
mixed $id
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 315 of file RoleService.php.
    {
        $response = $this->client->request(
            'GET',
            $id,
            new Message(
                array( 'Accept' => $this->outputVisitor->getMediaType( 'Role' ) )
            )
        );
        $loadedRole = $this->inputDispatcher->parse( $response );
        $loadedRoleValues = $this->urlHandler->parse( 'role', $loadedRole->id );
        $response = $this->client->request(
            'GET',
            $this->urlHandler->generate( 'policies', array( 'role' => $loadedRoleValues['role'] ) ),
            new Message(
                array( 'Accept' => $this->outputVisitor->getMediaType( 'PolicyList' ) )
            )
        );
        $policies = $this->inputDispatcher->parse( $response );
        return new Role(
            array(
                'id' => $loadedRole->id,
                'identifier' => $loadedRole->identifier
            ),
            $policies
        );
    }
eZ\Publish\Core\REST\Client\RoleService::loadRoleByIdentifier ($name)
Loads a role for the given name
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read this role
\eZ\Publish\API\Repository\Exceptions\NotFoundException if a role with the given name was not found
Parameters
string $name
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 355 of file RoleService.php.
    {
        $response = $this->client->request(
            'GET',
            $this->urlHandler->generate( 'roleByIdentifier', array( 'role' => $name ) ),
            new Message(
                array( 'Accept' => $this->outputVisitor->getMediaType( 'RoleList' ) )
            )
        );
        $result = $this->inputDispatcher->parse( $response );
        return reset( $result );
    }
eZ\Publish\Core\REST\Client\RoleService::loadRoles ()
Loads all roles
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to read the roles
Returns
[]
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 376 of file RoleService.php.
    {
        $response = $this->client->request(
            'GET',
            $this->urlHandler->generate( 'roles' ),
            new Message(
                array( 'Accept' => $this->outputVisitor->getMediaType( 'RoleList' ) )
            )
        );
        return $this->inputDispatcher->parse( $response );
    }
eZ\Publish\Core\REST\Client\RoleService::newPolicyCreateStruct ($module, $function)
Instantiates a policy create class
Parameters
string $module
string $function
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 671 of file RoleService.php.
    {
        return new PolicyCreateStruct( $module, $function );
    }
eZ\Publish\Core\REST\Client\RoleService::newPolicyUpdateStruct ()
Instantiates a policy update class
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 681 of file RoleService.php.
    {
        return new PolicyUpdateStruct();
    }
eZ\Publish\Core\REST\Client\RoleService::newRoleCreateStruct ($name)
Instantiates a role create class
Parameters
string $name
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 658 of file RoleService.php.
    {
        return new Values\User\RoleCreateStruct( $name );
    }
eZ\Publish\Core\REST\Client\RoleService::newRoleUpdateStruct ()
Instantiates a policy update class
Returns
Implements eZ\Publish\API\Repository\RoleService.
Definition at line 691 of file RoleService.php.
    {
        return new RoleUpdateStruct();
    }
eZ\Publish\Core\REST\Client\RoleService::removePolicy (APIRole $role, APIPolicy $policy)
removes a policy from the role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to remove a policy
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\Policy $policy the policy to remove from the role
Returns
the updated role
Definition at line 245 of file RoleService.php.
References eZ\Publish\API\Repository\RoleService\loadRole().
    {
        $values = $this->urlHandler->parse( 'role', $role->id );
        $response = $this->client->request(
            'DELETE',
            $this->urlHandler->generate(
                'policy',
                array(
                    'role' => $values['role'],
                    'policy' => $policy->id
                )
            ),
            new Message(
                // @todo: What media-type should we set here? Actually, it should be
                // all expected exceptions + none? Or is "Section" correct,
                // since this is what is to be expected by the resource
                // identified by the URL?
                array( 'Accept' => $this->outputVisitor->getMediaType( 'Policy' ) )
            )
        );
        if ( !empty( $response->body ) )
            $this->inputDispatcher->parse( $response );
        return $this->loadRole( $role->id );
    }
eZ\Publish\Core\REST\Client\RoleService::setSession ($id)
Set session ID
Only for testing
Parameters
mixed $id
Returns
void
Implements eZ\Publish\Core\REST\Client\Sessionable.
Definition at line 96 of file RoleService.php.
References eZ\Publish\Core\REST\Client\RoleService\setSession().
    {
        if ( $this->outputVisitor instanceof Sessionable )
        {
            $this->outputVisitor->setSession( $id );
        }
    }
eZ\Publish\Core\REST\Client\RoleService::unassignRoleFromUser (APIRole $role, User $user)
removes a role from the given user.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to remove a role
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the role is not assigned to the user
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\User $user
Definition at line 541 of file RoleService.php.
    {
        $values = $this->urlHandler->parse( 'user', $user->id );
        $userId = $values['user'];
        $values = $this->urlHandler->parse( 'role', $role->id );
        $roleId = $values['role'];
        $response = $this->client->request(
            'DELETE',
            $this->urlHandler->generate( 'userRoleAssignment', array( 'user' => $userId, 'role' => $roleId ) ),
            new Message(
                // @todo: What media-type should we set here? Actually, it should be
                // all expected exceptions + none? Or is "Section" correct,
                // since this is what is to be expected by the resource
                // identified by the URL?
                array( 'Accept' => $this->outputVisitor->getMediaType( 'RoleAssignmentList' ) )
            )
        );
        if ( !empty( $response->body ) )
            $this->inputDispatcher->parse( $response );
    }
eZ\Publish\Core\REST\Client\RoleService::unassignRoleFromUserGroup (APIRole $role, UserGroup $userGroup)
removes a role from the given user group.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to remove a role
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the role is not assigned to the given user group
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\UserGroup $userGroup
Definition at line 476 of file RoleService.php.
    {
        $values = $this->urlHandler->parse( 'group', $userGroup->id );
        $userGroupId = $values['group'];
        $values = $this->urlHandler->parse( 'role', $role->id );
        $roleId = $values['role'];
        $response = $this->client->request(
            'DELETE',
            $this->urlHandler->generate( 'groupRoleAssignment', array( 'group' => $userGroupId, 'role' => $roleId ) ),
            new Message(
                // @todo: What media-type should we set here? Actually, it should be
                // all expected exceptions + none? Or is "Section" correct,
                // since this is what is to be expected by the resource
                // identified by the URL?
                array( 'Accept' => $this->outputVisitor->getMediaType( 'RoleAssignmentList' ) )
            )
        );
        if ( !empty( $response->body ) )
            $this->inputDispatcher->parse( $response );
    }
eZ\Publish\Core\REST\Client\RoleService::updatePolicy (APIPolicy $policy, APIPolicyUpdateStruct $policyUpdateStruct)
Updates the limitations of a policy. The module and function cannot be changed and the limitations are replaced by the ones in $roleUpdateStruct
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to udate a policy
Parameters
\eZ\Publish\API\Repository\Values\User\PolicyUpdateStruct $policyUpdateStruct
\eZ\Publish\API\Repository\Values\User\Policy $policy
Returns
Definition at line 283 of file RoleService.php.
    {
        $values = $this->urlHandler->parse( 'role', $policy->roleId );
        $inputMessage = $this->outputVisitor->visit( $policyUpdateStruct );
        $inputMessage->headers['Accept'] = $this->outputVisitor->getMediaType( 'Policy' );
        $inputMessage->headers['X-HTTP-Method-Override'] = 'PATCH';
        $result = $this->client->request(
            'POST',
            $this->urlHandler->generate(
                'policy',
                array(
                    'role' => $values['role'],
                    'policy' => $policy->id
                )
            ),
            $inputMessage
        );
        return $this->inputDispatcher->parse( $result );
    }
eZ\Publish\Core\REST\Client\RoleService::updateRole (APIRole $role, RoleUpdateStruct $roleUpdateStruct)
Updates the name of the role
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the authenticated user is not allowed to update a role
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the name of the role already exists
Parameters
\eZ\Publish\API\Repository\Values\User\Role $role
\eZ\Publish\API\Repository\Values\User\RoleUpdateStruct $roleUpdateStruct
Returns
Definition at line 174 of file RoleService.php.
    {
        $inputMessage = $this->outputVisitor->visit( $roleUpdateStruct );
        $inputMessage->headers['Accept'] = $this->outputVisitor->getMediaType( 'Role' );
        $inputMessage->headers['X-HTTP-Method-Override'] = 'PATCH';
        $result = $this->client->request(
            'POST',
            $role->id,
            $inputMessage
        );
        return $this->inputDispatcher->parse( $result );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Client/RoleService.php