ezp-next: eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound Class Reference
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound Class Reference
Public Member Functions
__construct (array $config)
setMatcherBuilder (MatcherBuilderInterface $matcherBuidler)
getSubMatchers ()
setRequest (SimplifiedRequest $request)
analyseURI ($uri)
analyseLink ($linkUri)
getName ()
Protected Attributes
$matchersMapConfig
$matchersMap
$siteaccessName
$matcherBuilder
$request
Detailed Description
Base for Compound siteaccess matchers. All classes extending this one must implement a NAME class constant.
Definition at line 21 of file Compound.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::__construct (array $config)
Definition at line 50 of file Compound.php.
    {
        $this->matchersMapConfig = $config['matchers'];
        $this->matchersMap = array();
        $this->siteaccessName = $config['match'];
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::analyseLink ($linkUri)
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\URILexer.
Definition at line 104 of file Compound.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\$matcher, and eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound\analyseLink().
    {
        foreach ( $this->matchersMap as $matcher )
        {
            if ( $matcher instanceof URILexer )
            {
                $linkUri = $matcher->analyseLink( $linkUri );
            }
        }
        return $linkUri;
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::analyseURI ($uri)
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\URILexer.
Definition at line 88 of file Compound.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\$matcher, and eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound\analyseURI().
    {
        foreach ( $this->matchersMap as $matcher )
        {
            if ( $matcher instanceof URILexer )
            {
                $uri = $matcher->analyseURI( $uri );
            }
        }
        return $uri;
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::getName ()
Returns the matcher's name. This information will be stored in the SiteAccess object itself to quickly be able to identify the matcher type.
Returns
string
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 123 of file Compound.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound\getName().
    {
        return
           'compound:' .
           static::NAME . '(' .
           implode(
               ', ',
               array_keys( $this->matchersMap )
           ) . ')';
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::getSubMatchers ()
Returns
[]
Definition at line 72 of file Compound.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound\getSubMatchers().
    {
        return $this->matchersMap;
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::setMatcherBuilder (MatcherBuilderInterface $matcherBuidler)
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\CompoundInterface.
Definition at line 60 of file Compound.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\MatcherBuilderInterface\buildMatcher(), and eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound\setMatcherBuilder().
    {
        $this->matcherBuilder = $matcherBuidler;
        foreach ( $this->matchersMapConfig as $matcherClass => $matchingConfig )
        {
            $this->matchersMap[$matcherClass] = $matcherBuidler->buildMatcher( $matcherClass, $matchingConfig, $this->request );
        }
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::setRequest (SimplifiedRequest $request)
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 80 of file Compound.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound\setRequest().
    {
        $this->request = $request;
    }
Member Data Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::$matcherBuilder protected
Definition at line 43 of file Compound.php.
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::$matchersMap protected
Definition at line 31 of file Compound.php.
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::$matchersMapConfig protected
Definition at line 26 of file Compound.php.
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::$request protected
Definition at line 48 of file Compound.php.
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Compound::$siteaccessName protected
Definition at line 38 of file Compound.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Compound.php