ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action\AddField Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action\AddField Class Reference
Public Member Functions
__construct (Gateway $contentGateway, FieldDefinition $fieldDef, Converter $converter, StorageHandler $storageHandler)
apply (Content $content)
Public Member Functions inherited from eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action
__construct (ContentGateway $contentGateway)
Protected Member Functions
createField (Content $content)
Protected Attributes
$fieldDefinition
$storageHandler
$fieldValueConverter
Protected Attributes inherited from eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action
$contentGateway
Detailed Description
Action to add a field to content objects
Definition at line 23 of file AddField.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action\AddField::__construct (Gateway $contentGateway, FieldDefinition $fieldDef, Converter $converter, StorageHandler $storageHandler)
Creates a new action
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\Gateway $contentGateway
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDef
\eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter $converter
\eZ\Publish\Core\Persistence\Legacy\Content\StorageHandler $storageHandler
Definition at line 54 of file AddField.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\$contentGateway, and eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\$storageHandler.
    {
        $this->contentGateway = $contentGateway;
        $this->fieldDefinition = $fieldDef;
        $this->fieldValueConverter = $converter;
        $this->storageHandler = $storageHandler;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action\AddField::apply (Content $content)
Applies the action to the given $content
Parameters
Content $content
Todo:
Handle external field data
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action.
Definition at line 75 of file AddField.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action\AddField\apply(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action\AddField\createField().
    {
        $field = $this->createField( $content );
        $storageValue = new StorageFieldValue();
        $this->fieldValueConverter->toStorageValue(
            $field->value,
            $storageValue
        );
        $field->id = $this->contentGateway->insertNewField(
            $content,
            $field,
            $storageValue
        );
        // If the storage handler returns true, it means that $field value has been modified
        // So we need to update it in order to store those modifications
        // Field converter is called once again via the Mapper
        if ( $this->storageHandler->storeFieldData( $content->versionInfo, $field ) === true )
        {
            $storageValue = new StorageFieldValue();
            $this->fieldValueConverter->toStorageValue(
                $field->value,
                $storageValue
            );
            if ( $this->fieldDefinition->isTranslatable )
            {
                $this->contentGateway->updateField(
                    $field,
                    $storageValue
                );
            }
            else
            {
                $this->contentGateway->updateNonTranslatableField(
                    $field,
                    $storageValue,
                    $content->contentInfo->id
                );
            }
        }
        $content->fields[] = $field;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action\AddField::createField (Content $content) protected
Parameters
\eZ\Publish\SPI\Persistence\Content $content
Returns
Todo:
Handle ->languageCode
Definition at line 129 of file AddField.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action\AddField\createField().
    {
        $field = new Content\Field();
        $field->fieldDefinitionId = $this->fieldDefinition->id;
        $field->type = $this->fieldDefinition->fieldType;
        $field->value = clone $this->fieldDefinition->defaultValue;
        $field->versionNo = $content->versionInfo->versionNo;
        //$field->languageCode = $content->initialLanguageId;
        return $field;
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action\AddField::$fieldDefinition protected
Definition at line 30 of file AddField.php.
eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action\AddField::$fieldValueConverter protected
Definition at line 44 of file AddField.php.
eZ\Publish\Core\Persistence\Legacy\Content\Type\ContentUpdater\Action\AddField::$storageHandler protected
Definition at line 37 of file AddField.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater/Action/AddField.php