ezp-next: eZ\Publish\Core\REST\Common\Input\Handler\Xml Class Reference
eZ\Publish\Core\REST\Common\Input\Handler\Xml Class Reference
Public Member Functions
convert ($string)
Protected Member Functions
convertDom (\DOMNode $node)
parseFieldTypeHash (\DOMElement $domElement)
parseFieldTypeValues (\DOMNodeList $valueNodes)
castScalarValue ($stringValue)
Protected Attributes
$forceList
$fieldTypeHashElements
Detailed Description
Input format handler base class
Definition at line 18 of file Xml.php.
Member Function Documentation
eZ\Publish\Core\REST\Common\Input\Handler\Xml::castScalarValue ($stringValue) protected
Attempts to cast the given $stringValue into a sensible scalar type
Parameters
string $stringValue
Returns
mixed
Definition at line 283 of file Xml.php.
References eZ\Publish\Core\REST\Common\Input\Handler\Xml\castScalarValue().
    {
        switch ( true )
        {
            case ( ctype_digit( $stringValue ) ):
                return (int)$stringValue;
            case ( preg_match( '(^[0-9\.]+$)', $stringValue ) === 1 ):
                return (float)$stringValue;
            case ( strtolower( $stringValue ) === 'true' ):
                return true;
            case ( strtolower( $stringValue ) === 'false' ):
                return false;
        }
        return $stringValue;
    }
eZ\Publish\Core\REST\Common\Input\Handler\Xml::convert ($string)
Converts the given string to an array structure
Parameters
string $string
Returns
array
Reimplemented from eZ\Publish\Core\REST\Common\Input\Handler.
Definition at line 78 of file Xml.php.
References eZ\Publish\Core\REST\Common\Input\Handler\Xml\convertDom().
    {
        $oldXmlErrorHandling = libxml_use_internal_errors( true );
        libxml_clear_errors();
        $dom = new \DOMDocument();
        $dom->loadXml( $string );
        $errors = libxml_get_errors();
        libxml_clear_errors();
        libxml_use_internal_errors( $oldXmlErrorHandling );
        if ( $errors )
        {
            $message = "Detected errors in input XML:\n";
            foreach ( $errors as $error )
            {
                $message .= sprintf(
                    " - In line %d character %d: %s\n",
                    $error->line,
                    $error->column,
                    $error->message
                );
            }
            $message .= "\nIn XML: \n\n" . $string;
            throw new Exceptions\Parser( $message );
        }
        return $this->convertDom( $dom );
    }
eZ\Publish\Core\REST\Common\Input\Handler\Xml::convertDom (\DOMNode $node) protected
Converts DOM nodes to array structures
Parameters
\DOMNode $node
Returns
array
Definition at line 118 of file Xml.php.
References eZ\Publish\Core\REST\Common\Input\Handler\Xml\convertDom(), and eZ\Publish\Core\REST\Common\Input\Handler\Xml\parseFieldTypeHash().
    {
        $isArray = false;
        $current = array();
        $text    = '';
        if ( $node instanceof \DOMElement )
        {
            foreach ( $node->attributes as $name => $attribute )
            {
                $current["_{$name}"] = $attribute->value;
            }
        }
        $parentTagName = $node instanceof \DOMElement ? $node->tagName : false;
        foreach ( $node->childNodes as $childNode )
        {
            switch ( $childNode->nodeType )
            {
                case XML_ELEMENT_NODE:
                    $tagName = $childNode->tagName;
                    if ( in_array( $tagName, $this->fieldTypeHashElements ) )
                    {
                        $current[$tagName] = $this->parseFieldTypeHash( $childNode );
                    }
                    else if ( !isset( $current[$tagName]  ) )
                    {
                        if ( isset( $this->forceList[$parentTagName] ) &&
                             in_array( $tagName, $this->forceList[$parentTagName], true ) )
{
                            $isArray = true;
                            $current[$tagName] = array(
                                $this->convertDom( $childNode )
                            );
                        }
                        else
{
                            $current[$tagName] = $this->convertDom( $childNode );
                        }
                    }
                    else if ( !$isArray )
                    {
                        $current[$tagName] = array(
                            $current[$tagName],
                            $this->convertDom( $childNode )
                        );
                        $isArray = true;
                    }
                    else
                    {
                        $current[$tagName][] = $this->convertDom( $childNode );
                    }
                    break;
                case XML_TEXT_NODE:
                    $text .= $childNode->wholeText;
                    break;
                case XML_CDATA_SECTION_NODE:
                    $text .= $childNode->data;
                    break;
            }
        }
        $text = trim( $text );
        if ( $text !== '' && count( $current ) )
        {
            $current["#text"] = $text;
        }
        else if ( $text !== '' )
        {
            $current = $text;
        }
        else if ( !count( $current ) )
        {
            return null;
        }
        return $current;
    }
eZ\Publish\Core\REST\Common\Input\Handler\Xml::parseFieldTypeHash (\DOMElement $domElement) protected
Parameters
\DOMElement $domElement
Returns
array|string|null
Definition at line 207 of file Xml.php.
References eZ\Publish\Core\REST\Common\Input\Handler\Xml\parseFieldTypeHash(), and eZ\Publish\Core\REST\Common\Input\Handler\Xml\parseFieldTypeValues().
    {
        $result = $this->parseFieldTypeValues( $domElement->childNodes );
        if ( is_array( $result ) && empty( $result ) )
        {
            // No child values means null
            return null;
        }
        return $result;
    }
eZ\Publish\Core\REST\Common\Input\Handler\Xml::parseFieldTypeValues (\DOMNodeList $valueNodes) protected
Parses a node list of
elements
Parameters
\DOMNodeList $valueNodes
Returns
array|string
Definition at line 227 of file Xml.php.
References eZ\Publish\Core\REST\Common\Input\Handler\Xml\castScalarValue(), and eZ\Publish\Core\REST\Common\Input\Handler\Xml\parseFieldTypeValues().
    {
        $resultValues = array();
        $resultString = '';
        foreach ( $valueNodes as $valueNode )
        {
            switch ( $valueNode->nodeType )
            {
                case XML_ELEMENT_NODE:
                    if ( $valueNode->tagName !== 'value' )
                    {
                        throw new \RuntimeException(
                            sprintf(
                                'Invalid value tag: <%s>.',
                                $valueNode->tagName
                            )
                        );
                    }
                    $parsedValue = $this->parseFieldTypeValues( $valueNode->childNodes );
                    if ( $valueNode->hasAttribute( 'key' ) )
                    {
                        $resultValues[$valueNode->getAttribute( 'key' )] = $parsedValue;
                    }
                    else
                    {
                        $resultValues[] = $parsedValue;
                    }
                    break;
                case XML_TEXT_NODE:
                    $resultString .= $valueNode->wholeText;
                    break;
                case XML_CDATA_SECTION_NODE:
                    $resultString .= $valueNode->data;
                    break;
            }
        }
        $resultString = trim( $resultString );
        if ( $resultString !== '' )
        {
            return $this->castScalarValue( $resultString );
        }
        return $resultValues;
    }
Member Data Documentation
eZ\Publish\Core\REST\Common\Input\Handler\Xml::$fieldTypeHashElements protected
Initial value:
 array(
        'fieldValue',
    )
Definition at line 67 of file Xml.php.
eZ\Publish\Core\REST\Common\Input\Handler\Xml::$forceList protected
Definition at line 28 of file Xml.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/Input/Handler/Xml.php