ezp-next: eZ\Publish\Core\FieldType\User\Type Class Reference
eZ\Publish\Core\FieldType\User\Type Class Reference
Public Member Functions
getFieldTypeIdentifier ()
getName ($value)
getEmptyValue ()
fromHash ($hash)
toHash ($value)
toPersistenceValue ($value)
fromPersistenceValue (FieldValue $fieldValue)
Public Member Functions inherited from eZ\Publish\Core\FieldType\FieldType
getSettingsSchema ()
getValidatorConfigurationSchema ()
validate (FieldDefinition $fieldDefinition, $fieldValue)
validateValidatorConfiguration ($validatorConfiguration)
validateFieldSettings ($fieldSettings)
isSearchable ()
isEmptyValue ($value)
acceptValue ($inputValue)
fieldSettingsToHash ($fieldSettings)
fieldSettingsFromHash ($fieldSettingsHash)
validatorConfigurationToHash ($validatorConfiguration)
validatorConfigurationFromHash ($validatorConfigurationHash)
getRelations ($fieldValue)
Protected Member Functions
internalAcceptValue ($inputValue)
getSortInfo ($value)
Additional Inherited Members
Protected Attributes inherited from eZ\Publish\Core\FieldType\FieldType
$settingsSchema = array()
$validatorConfigurationSchema = array()
Detailed Description
The User field type.
This field type represents a simple string.
Definition at line 21 of file Type.php.
Member Function Documentation
eZ\Publish\Core\FieldType\User\Type::fromHash ($hash)
Converts an $hash to the Value defined by the field type
Parameters
mixed $hash
Returns
$value
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 103 of file Type.php.
    {
        if ( $hash === null )
        {
            return null;
        }
        return new Value( $hash );
    }
eZ\Publish\Core\FieldType\User\Type::fromPersistenceValue (FieldValue $fieldValue)
Converts a persistence $fieldValue to a Value
This method builds a field type value from the $data and $externalData properties.
Parameters
\eZ\Publish\SPI\Persistence\Content\FieldValue $fieldValue
Returns
mixed
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 170 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\acceptValue().
    {
        return $this->acceptValue( $fieldValue->externalData );
    }
eZ\Publish\Core\FieldType\User\Type::getEmptyValue ()
Returns the fallback default value of field type when no such default value is provided in the field definition in content types.
Returns
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 56 of file Type.php.
    {
        return new Value;
    }
eZ\Publish\Core\FieldType\User\Type::getFieldTypeIdentifier ()
Returns the field type identifier for this field type
Returns
string
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 28 of file Type.php.
    {
        return "ezuser";
    }
eZ\Publish\Core\FieldType\User\Type::getName ($value)
Returns the name of the given field value.
It will be used to generate content name and url alias if current field is designated to be used in the content name/urlAlias pattern.
Parameters
mixed $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 43 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\acceptValue().
    {
        $value = $this->acceptValue( $value );
        return (string)$value->login;
    }
eZ\Publish\Core\FieldType\User\Type::getSortInfo ($value) protected
Returns information for FieldValue->$sortKey relevant to the field type.
Todo:
: Implement.
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 91 of file Type.php.
    {
        return false;
    }
eZ\Publish\Core\FieldType\User\Type::internalAcceptValue ($inputValue) protected
Implements the core of {
See Also
acceptValue()}.
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 68 of file Type.php.
    {
        if ( is_array( $inputValue ) )
        {
            $inputValue = new Value( $inputValue );
        }
        else if ( !$inputValue instanceof Value )
        {
            throw new InvalidArgumentType(
                '$inputValue',
                'eZ\\Publish\\Core\\FieldType\\User\\Value',
                $inputValue
            );
        }
        return $inputValue;
    }
eZ\Publish\Core\FieldType\User\Type::toHash ($value)
Converts a $Value to a hash
Parameters
\eZ\Publish\Core\FieldType\User\Value $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 119 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\isEmptyValue().
    {
        if ( $this->isEmptyValue( $value ) )
        {
            return null;
        }
        return (array)$value;
    }
eZ\Publish\Core\FieldType\User\Type::toPersistenceValue ($value)
Converts a $value to a persistence value.
In this method the field type puts the data which is stored in the field of content in the repository into the property FieldValue::data. The format of $data is a primitive, an array (map) or an object, which is then canonically converted to e.g. json/xml structures by future storage engines without further conversions. For mapping the $data to the legacy database an appropriate Converter (implementing eZ) has implemented for the field type. Note: $data should only hold data which is actually stored in the field. It must not hold data which is stored externally.
The $externalData property in the FieldValue is used for storing data externally by the FieldStorage interface method storeFieldData.
The FieldValuer::sortKey is build by the field type for using by sort operations.
See Also
Parameters
mixed $value The value of the field type
Returns
the value processed by the storage engine
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 150 of file Type.php.
References eZ\Publish\Core\FieldType\User\Type\toHash().
    {
        return new FieldValue(
            array(
                "data" => null,
                "externalData" => $this->toHash( $value ),
                "sortKey" => null,
            )
        );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/User/Type.php