ezp-next: eZ\Publish\Core\MVC\Symfony\Cache\Http\Store Class Reference
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store Class Reference
Public Member Functions
__construct ($root)
cleanup ()
lock (Request $request)
unlock (Request $request)
lookup (Request $request)
write (Request $request, Response $response)
invalidate (Request $request)
purge ($url)
getPath ($key)
Protected Member Functions
generateContentDigest (Response $response)
Protected Attributes
$root
Detailed Description
Store implements all the logic for storing cache metadata (Request and Response headers). This class is a enhanced version of Symfony :
Changes $root visibility from private to protected
Adds generateContentDigest() protected method allowing some control on content digest generation
Author
Fabien Potencier fabie.nosp@m.n@sy.nosp@m.mfony.nosp@m..com
Definition at line 24 of file Store.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store::__construct ($root)
Constructor.
Parameters
string $root The path to the cache directory
Definition at line 35 of file Store.php.
References eZ\Publish\Core\MVC\Symfony\Cache\Http\Store\$root.
    {
        $this->root = $root;
        if ( !is_dir( $this->root ) )
        {
            mkdir( $this->root, 0777, true );
        }
        $this->keyCache = new \SplObjectStorage();
        $this->locks = array();
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store::cleanup ()
Cleanups storage.
Definition at line 49 of file Store.php.
    {
        // unlock everything
        foreach ( $this->locks as $lock )
        {
            @unlink( $lock );
        }
        $error = error_get_last();
        if ( 1 === $error['type'] && false === headers_sent() )
        {
            // send a 503
            header( 'HTTP/1.0 503 Service Unavailable' );
            header( 'Retry-After: 10' );
            echo '503 Service Unavailable';
        }
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store::generateContentDigest (Response $response) protected
Returns content digest for $response
Parameters
Response $response
Returns
string
Reimplemented in eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore.
Definition at line 212 of file Store.php.
    {
        return 'en' . sha1( $response->getContent() );
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store::getPath ($key)
Reimplemented in eZ\Publish\Core\MVC\Symfony\Cache\Http\LocationAwareStore.
Definition at line 381 of file Store.php.
    {
        return $this->root . DIRECTORY_SEPARATOR . substr( $key, 0, 2 ) . DIRECTORY_SEPARATOR . substr( $key, 2, 2 ) . DIRECTORY_SEPARATOR . substr( $key, 4, 2 ) . DIRECTORY_SEPARATOR . substr( $key, 6 );
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store::invalidate (Request $request)
Invalidates all cache entries that match the request.
Parameters
Request $request A Request instance
Definition at line 222 of file Store.php.
    {
        $modified = false;
        $key = $this->getCacheKey( $request );
        $entries = array();
        foreach ( $this->getMetadata( $key ) as $entry )
        {
            $response = $this->restoreResponse( $entry[1] );
            if ( $response->isFresh() )
            {
                $response->expire();
                $modified = true;
                $entries[] = array( $entry[0], $this->persistResponse( $response ) );
            }
            else
            {
                $entries[] = $entry;
            }
        }
        if ( $modified )
        {
            if ( false === $this->save( $key, serialize( $entries ) ) )
            {
                throw new \RuntimeException( 'Unable to store the metadata.' );
            }
        }
        // As per the RFC, invalidate Location and Content-Location URLs if present
        foreach ( array( 'Location', 'Content-Location' ) as $header )
        {
            if ( $uri = $request->headers->get( $header ) )
            {
                $subRequest = Request::create( $uri, 'get', array(), array(), array(), $request->server->all() );
                $this->invalidate( $subRequest );
            }
        }
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store::lock (Request $request)
Locks the cache for a given Request.
Parameters
Request $request A Request instance
Returns
Boolean|string true if the lock is acquired, the path to the current lock otherwise
Definition at line 74 of file Store.php.
References eZ\Publish\Core\MVC\Symfony\Cache\Http\Store\getPath().
    {
        if ( false !== $lock = @fopen( $path = $this->getPath( $this->getCacheKey( $request ) . '.lck' ), 'x' ) )
        {
            fclose( $lock );
            $this->locks[] = $path;
            return true;
        }
        return $path;
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store::lookup (Request $request)
Locates a cached Response for the Request provided.
Parameters
Request $request A Request instance
Returns
Response|null A Response instance, or null if no cache entry was found
Definition at line 105 of file Store.php.
References eZ\Publish\Core\MVC\Symfony\Cache\Http\Store\getPath().
    {
        $key = $this->getCacheKey( $request );
        if ( !$entries = $this->getMetadata( $key ) )
        {
            return null;
        }
        // find a cached entry that matches the request.
        $match = null;
        foreach ( $entries as $entry )
        {
            if ( $this->requestsMatch( isset( $entry[1]['vary'][0] ) ? $entry[1]['vary'][0] : '', $request->headers->all(), $entry[0] ) )
            {
                $match = $entry;
                break;
            }
        }
        if ( null === $match )
        {
            return null;
        }
        list( $req, $headers ) = $match;
        if ( is_file( $body = $this->getPath( $headers['x-content-digest'][0] ) ) )
        {
            return $this->restoreResponse( $headers, $body );
        }
        // @todo the metaStore referenced an entity that doesn't exist in
        // the entityStore. We definitely want to return nil but we should
        // also purge the entry from the meta-store when this is detected.
        return null;
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store::purge ($url)
Purges data for the given URL.
Parameters
string $url A URL
Returns
Boolean true if the URL exists and has been purged, false otherwise
Definition at line 320 of file Store.php.
References eZ\Publish\Core\MVC\Symfony\Cache\Http\Store\getPath().
    {
        if ( is_file( $path = $this->getPath( $this->getCacheKey( Request::create( $url ) ) ) ) )
        {
            unlink( $path );
            return true;
        }
        return false;
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store::unlock (Request $request)
Releases the lock for the given Request.
Parameters
Request $request A Request instance
Definition at line 93 of file Store.php.
References eZ\Publish\Core\MVC\Symfony\Cache\Http\Store\getPath().
    {
        return @unlink( $this->getPath( $this->getCacheKey( $request ) . '.lck' ) );
    }
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store::write (Request $request, Response $response)
Writes a cache entry to the store for the given Request and Response.
Existing entries are read and any that match the response are removed. This method calls write with the new list of cache entries.
Parameters
Request $request A Request instance
Response $response A Response instance
Returns
string The key under which the response is stored
Definition at line 153 of file Store.php.
References eZ\Publish\Core\MVC\Symfony\Cache\Http\Store\generateContentDigest().
    {
        $key = $this->getCacheKey( $request );
        $storedEnv = $this->persistRequest( $request );
        // write the response body to the entity store if this is the original response
        if ( !$response->headers->has( 'X-Content-Digest' ) )
        {
            $digest = $this->generateContentDigest( $response );
            if ( false === $this->save( $digest, $response->getContent() ) )
            {
                throw new \RuntimeException( 'Unable to store the entity.' );
            }
            $response->headers->set( 'X-Content-Digest', $digest );
            if ( !$response->headers->has( 'Transfer-Encoding' ) )
            {
                $response->headers->set( 'Content-Length', strlen( $response->getContent() ) );
            }
        }
        // read existing cache entries, remove non-varying, and add this one to the list
        $entries = array();
        $vary = $response->headers->get( 'vary' );
        foreach ( $this->getMetadata( $key ) as $entry )
        {
            if ( !isset( $entry[1]['vary'][0] ) )
            {
                $entry[1]['vary'] = array( '' );
            }
            if ( $vary != $entry[1]['vary'][0] || !$this->requestsMatch( $vary, $entry[0], $storedEnv ) )
            {
                $entries[] = $entry;
            }
        }
        $headers = $this->persistResponse( $response );
        unset( $headers['age'] );
        array_unshift( $entries, array( $storedEnv, $headers ) );
        if ( false === $this->save( $key, serialize( $entries ) ) )
        {
            throw new \RuntimeException( 'Unable to store the metadata.' );
        }
        return $key;
    }
Member Data Documentation
eZ\Publish\Core\MVC\Symfony\Cache\Http\Store::$root protected
Definition at line 26 of file Store.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/Cache/Http/Store.php