ezp-next: eZ\Publish\Core\FieldType\Float\Type Class Reference
eZ\Publish\Core\FieldType\Float\Type Class Reference
Public Member Functions
validateValidatorConfiguration ($validatorConfiguration)
validate (FieldDefinition $fieldDefinition, $fieldValue)
getFieldTypeIdentifier ()
getName ($value)
getEmptyValue ()
isEmptyValue ($value)
fromHash ($hash)
toHash ($value)
Public Member Functions inherited from eZ\Publish\Core\FieldType\FieldType
getSettingsSchema ()
getValidatorConfigurationSchema ()
validateFieldSettings ($fieldSettings)
toPersistenceValue ($value)
fromPersistenceValue (FieldValue $fieldValue)
isSearchable ()
acceptValue ($inputValue)
fieldSettingsToHash ($fieldSettings)
fieldSettingsFromHash ($fieldSettingsHash)
validatorConfigurationToHash ($validatorConfiguration)
validatorConfigurationFromHash ($validatorConfigurationHash)
Protected Member Functions
internalAcceptValue ($inputValue)
getSortInfo ($value)
Protected Attributes
$validatorConfigurationSchema
Protected Attributes inherited from eZ\Publish\Core\FieldType\FieldType
$settingsSchema = array()
$validatorConfigurationSchema = array()
Detailed Description
Float field types
Represents floats.
Definition at line 22 of file Type.php.
Member Function Documentation
eZ\Publish\Core\FieldType\Float\Type::fromHash ($hash)
Converts an $hash to the Value defined by the field type
Parameters
mixed $hash
Returns
$value
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 248 of file Type.php.
    {
        if ( empty( $hash ) )
        {
            return null;
        }
        return new Value( $hash );
    }
eZ\Publish\Core\FieldType\Float\Type::getEmptyValue ()
Returns the fallback default value of field type when no such default value is provided in the field definition in content types.
Returns
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 174 of file Type.php.
    {
        return new Value;
    }
eZ\Publish\Core\FieldType\Float\Type::getFieldTypeIdentifier ()
Returns the field type identifier for this field type
Returns
string
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 146 of file Type.php.
    {
        return 'ezfloat';
    }
eZ\Publish\Core\FieldType\Float\Type::getName ($value)
Returns the name of the given field value.
It will be used to generate content name and url alias if current field is designated to be used in the content name/urlAlias pattern.
Parameters
mixed $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 161 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\acceptValue().
    {
        $value = $this->acceptValue( $value );
        return (string)$value->value;
    }
eZ\Publish\Core\FieldType\Float\Type::getSortInfo ($value) protected
Returns information for FieldValue->$sortKey relevant to the field type.
Todo:
Sort seems to not be supported by this FieldType, is this handled correctly?
Returns
array
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 236 of file Type.php.
    {
        return false;
    }
eZ\Publish\Core\FieldType\Float\Type::internalAcceptValue ($inputValue) protected
Implements the core of {
See Also
acceptValue()}.
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 198 of file Type.php.
    {
        if ( is_int( $inputValue ) )
        {
            $inputValue = (float)$inputValue;
        }
        if ( is_float( $inputValue ) )
        {
            $inputValue = new Value( $inputValue );
        }
        else if ( !$inputValue instanceof Value )
        {
            throw new InvalidArgumentType(
                '$inputValue',
                'eZ\\Publish\\Core\\FieldType\\Float\\Value',
                $inputValue
            );
        }
        if ( !is_float( $inputValue->value ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->value',
                'float',
                $inputValue->value
            );
        }
        return $inputValue;
    }
eZ\Publish\Core\FieldType\Float\Type::isEmptyValue ($value)
Returns if the given $value is considered empty by the field type
Parameters
mixed $value
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 186 of file Type.php.
    {
        return $value === null || $value->value === null;
    }
eZ\Publish\Core\FieldType\Float\Type::toHash ($value)
Converts a $Value to a hash
Parameters
\eZ\Publish\Core\FieldType\Float\Value $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 264 of file Type.php.
References eZ\Publish\Core\FieldType\Float\Type\isEmptyValue().
    {
        if ( $this->isEmptyValue( $value ) )
        {
            return null;
        }
        return $value->value;
    }
eZ\Publish\Core\FieldType\Float\Type::validate (FieldDefinition $fieldDefinition, $fieldValue)
Validates a field based on the validators in the field definition
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException
Parameters
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition The field definition of the field
\eZ\Publish\Core\FieldType\Value $fieldValue The field for which an action is performed
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 105 of file Type.php.
References eZ\Publish\API\Repository\Values\ContentType\FieldDefinition\getValidatorConfiguration().
    {
        $validatorConfiguration = $fieldDefinition->getValidatorConfiguration();
        $constraints = isset($validatorConfiguration['FloatValueValidator']) ?
            $validatorConfiguration['FloatValueValidator'] :
            array();
        $validationErrors = array();
        if ( isset( $constraints['maxFloatValue'] ) &&
            $constraints['maxFloatValue'] !== false && $fieldValue->value > $constraints['maxFloatValue'] )
        {
            $validationErrors[] = new ValidationError(
                "The value can not be higher than %size%.",
                null,
                array(
                    "size" => $constraints['maxFloatValue']
                )
            );
        }
        if ( isset( $constraints['minFloatValue'] ) &&
            $constraints['minFloatValue'] !== false && $fieldValue->value < $constraints['minFloatValue'] )
        {
            $validationErrors[] = new ValidationError(
                "The value can not be lower than %size%.",
                null,
                array(
                    "size" => $constraints['minFloatValue']
                )
            );
        }
        return $validationErrors;
    }
eZ\Publish\Core\FieldType\Float\Type::validateValidatorConfiguration ($validatorConfiguration)
Validates the validatorConfiguration of a FieldDefinitionCreateStruct or FieldDefinitionUpdateStruct
Parameters
mixed $validatorConfiguration
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 44 of file Type.php.
    {
        $validationErrors = array();
        foreach ( (array)$validatorConfiguration as $validatorIdentifier => $constraints )
        {
            if ( $validatorIdentifier !== 'FloatValueValidator' )
            {
                $validationErrors[] = new ValidationError(
                    "Validator '%validator%' is unknown",
                    null,
                    array(
                        "validator" => $validatorIdentifier
                    )
                );
                continue;
            }
            foreach ( $constraints as $name => $value )
            {
                switch ( $name )
                {
                    case "minFloatValue":
                    case "maxFloatValue":
                        if ( $value !== false && !is_numeric( $value ) )
{
                            $validationErrors[] = new ValidationError(
                                "Validator parameter '%parameter%' value must be of numeric type",
                                null,
                                array(
                                    "parameter" => $name
                                )
                            );
                        }
                        break;
                    default:
                        $validationErrors[] = new ValidationError(
                            "Validator parameter '%parameter%' is unknown",
                            null,
                            array(
                                "parameter" => $name
                            )
                        );
                }
            }
        }
        return $validationErrors;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\Float\Type::$validatorConfigurationSchema protected
Initial value:
 array(
        'FloatValueValidator' => array(
            'minFloatValue' => array(
                'type' => 'float',
                'default' => false
            ),
            'maxFloatValue' => array(
                'type' => 'float',
                'default' => false
            )
        )
    )
Definition at line 24 of file Type.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Float/Type.php