ezp-next: eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver Class Reference
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver Class Reference
Public Member Functions
addResolver (ConfigResolverInterface $resolver, $priority=0)
getAllResolvers ()
getParameter ($paramName, $namespace=null, $scope=null)
hasParameter ($paramName, $namespace=null, $scope=null)
setDefaultNamespace ($defaultNamespace)
getDefaultNamespace ()
Protected Member Functions
sortResolvers ()
Protected Attributes
$resolvers = array()
$sortedResolvers
Detailed Description
Definition at line 15 of file ChainConfigResolver.php.
Member Function Documentation
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver::addResolver (ConfigResolverInterface $resolver, $priority = 0)
Registers $mapper as a valid mapper to be used in the configuration mapping chain. When this mapper will be called in the chain depends on $priority. The highest $priority is, the earliest the router will be called.
Parameters
\eZ\Publish\Core\MVC\ConfigResolverInterface $resolver
int $priority
Definition at line 34 of file ChainConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\addResolver().
    {
        $priority = (int)$priority;
        if ( !isset( $this->resolvers[$priority] ) )
            $this->resolvers[$priority] = array();
        $this->resolvers[$priority][] = $resolver;
        $this->sortedResolvers = array();
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver::getAllResolvers ()
Returns
[]
Definition at line 47 of file ChainConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\getAllResolvers(), and eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\sortResolvers().
    {
        if ( empty( $this->sortedResolvers ) )
            $this->sortedResolvers = $this->sortResolvers();
        return $this->sortedResolvers;
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver::getDefaultNamespace ()
Not supported
Exceptions
\LogicException
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 142 of file ChainConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\getDefaultNamespace().
    {
        throw new \LogicException( 'getDefaultNamespace() is not supported by the ChainConfigResolver' );
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver::getParameter ($paramName, $namespace = null, $scope = null)
Returns value for $paramName, in $namespace.
Parameters
string $paramName The parameter name, without $prefix and the current scope (i.e. siteaccess name).
string $namespace Namespace for the parameter name. If null, the default namespace should be used.
string $scope The scope you need $paramName value for.
Exceptions
\eZ\Publish\Core\MVC\Exception\ParameterNotFoundException
Returns
mixed
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 85 of file ChainConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\getAllResolvers(), and eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\getParameter().
    {
        foreach ( $this->getAllResolvers() as $resolver )
        {
            try
            {
                return $resolver->getParameter( $paramName, $namespace, $scope );
            }
            catch ( ParameterNotFoundException $e )
            {
                // Do nothing, just let the next resolver handle it
            }
        }
        // Finally throw a ParameterNotFoundException since the chain resolver couldn't find any valid resolver for demanded parameter
        throw new ParameterNotFoundException( $paramName, $namespace );
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver::hasParameter ($paramName, $namespace = null, $scope = null)
Checks if $paramName exists in $namespace
Parameters
string $paramName
string $namespace If null, the default namespace should be used.
string $scope The scope you need $paramName value for.
Returns
boolean
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 112 of file ChainConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\getAllResolvers(), and eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\hasParameter().
    {
        foreach ( $this->getAllResolvers() as $resolver )
        {
            $hasParameter = $resolver->hasParameter( $paramName, $namespace, $scope );
            if ( $hasParameter )
                return true;
        }
        return false;
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver::setDefaultNamespace ($defaultNamespace)
Changes the default namespace to look parameter into.
Parameters
string $defaultNamespace
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 129 of file ChainConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\getAllResolvers(), and eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\setDefaultNamespace().
    {
        foreach ( $this->getAllResolvers() as $resolver )
        {
            $resolver->setDefaultNamespace( $defaultNamespace );
        }
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver::sortResolvers () protected
Sort the registered mappers by priority. The highest priority number is the highest priority (reverse sorting)
Returns
[]
Definition at line 61 of file ChainConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\$resolvers, eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\$sortedResolvers, and eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver\sortResolvers().
    {
        $sortedResolvers = array();
        krsort( $this->resolvers );
        foreach ( $this->resolvers as $resolvers )
        {
            $sortedResolvers = array_merge( $sortedResolvers, $resolvers );
        }
        return $sortedResolvers;
    }
Member Data Documentation
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver::$resolvers = array() protected
Definition at line 20 of file ChainConfigResolver.php.
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ChainConfigResolver::$sortedResolvers protected
Definition at line 25 of file ChainConfigResolver.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ChainConfigResolver.php