ezp-next: eZ\Publish\Core\REST\Common\Output\Generator\Xml Class Reference
eZ\Publish\Core\REST\Common\Output\Generator\Xml Class Reference
Public Member Functions
__construct (Xml\FieldTypeHashGenerator $hashGenerator)
startDocument ($data)
isEmpty ()
endDocument ($data)
startObjectElement ($name, $mediaTypeName=null)
endObjectElement ($name)
startHashElement ($name)
endHashElement ($name)
startValueElement ($name, $value, $attributes=array())
endValueElement ($name)
startList ($name)
endList ($name)
startAttribute ($name, $value)
endAttribute ($name)
getMediaType ($name)
generateFieldTypeHash ($hashElementName, $hashValue)
Public Member Functions inherited from eZ\Publish\Core\REST\Common\Output\Generator
reset ()
startValueElement ($name, $value)
Protected Attributes
$xmlWriter
$hashGenerator
$isEmpty = true
Protected Attributes inherited from eZ\Publish\Core\REST\Common\Output\Generator
$stack = array()
Additional Inherited Members
Protected Member Functions inherited from eZ\Publish\Core\REST\Common\Output\Generator
checkStartDocument ($data)
checkEndDocument ($data)
checkStartObjectElement ($data)
checkEndObjectElement ($data)
checkStartHashElement ($data)
checkEndHashElement ($data)
checkStartValueElement ($data)
checkEndValueElement ($data)
checkStartList ($data)
checkEndList ($data)
checkStartAttribute ($data)
checkEndAttribute ($data)
generateMediaType ($name, $type)
checkStart ($type, $data, array $validParents)
checkEnd ($type, $data)
Detailed Description
Xml generator
Definition at line 17 of file Xml.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Common\Output\Generator\Xml::__construct (Xml\FieldTypeHashGenerator $hashGenerator)
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator $hashGenerator
Definition at line 43 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\__construct().
    {
        $this->hashGenerator = $hashGenerator;
    }
Member Function Documentation
eZ\Publish\Core\REST\Common\Output\Generator\Xml::endAttribute ($name)
End attribute
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 224 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEndAttribute().
    {
        $this->checkEndAttribute( $name );
        $this->xmlWriter->endAttribute();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::endDocument ($data)
End document
Returns the generated document as a string.
Parameters
mixed $data
Returns
string
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 84 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEndDocument().
    {
        $this->checkEndDocument( $data );
        $this->xmlWriter->endDocument();
        return $this->xmlWriter->outputMemory();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::endHashElement ($name)
End hash element
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 143 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEndHashElement().
    {
        $this->checkEndHashElement( $name );
        $this->xmlWriter->endElement();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::endList ($name)
End list
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 200 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEndList().
    {
        $this->checkEndList( $name );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::endObjectElement ($name)
End object element
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 117 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEndObjectElement().
    {
        $this->checkEndObjectElement( $name );
        $this->xmlWriter->endElement();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::endValueElement ($name)
End value element
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 178 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkEndValueElement().
    {
        $this->checkEndValueElement( $name );
        $this->xmlWriter->endElement();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::generateFieldTypeHash ($hashElementName, $hashValue)
Generates a generic representation of the scalar, hash or list given in $hashValue into the document, using an element of $hashElementName as its parent
Parameters
string $hashElementName
mixed $hashValue
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 251 of file Xml.php.
    {
        $this->hashGenerator->generateHashValue( $this->xmlWriter, $hashElementName, $hashValue );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::getMediaType ($name)
Get media type
Parameters
string $name
Returns
string
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 238 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\generateMediaType().
    {
        return $this->generateMediaType( $name, 'xml' );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::isEmpty ()
Returns if the document is empty or already contains data
Returns
boolean
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 70 of file Xml.php.
    {
        return $this->isEmpty;
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::startAttribute ($name, $value)
Start attribute
Parameters
string $name
string $value
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 211 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStartAttribute().
    {
        $this->checkStartAttribute( $name );
        $this->xmlWriter->startAttribute( $name );
        $this->xmlWriter->text( $value );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::startDocument ($data)
Start document
Parameters
mixed $data
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 53 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStartDocument(), and eZ\Publish\Core\REST\Common\Output\Generator\isEmpty().
    {
        $this->checkStartDocument( $data );
        $this->isEmpty = true;
        $this->xmlWriter = new \XMLWriter();
        $this->xmlWriter->openMemory();
        $this->xmlWriter->setIndent( true );
        $this->xmlWriter->startDocument( '1.0', 'UTF-8' );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::startHashElement ($name)
Start hash element
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 129 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStartHashElement(), and eZ\Publish\Core\REST\Common\Output\Generator\isEmpty().
    {
        $this->checkStartHashElement( $name );
        $this->isEmpty = false;
        $this->xmlWriter->startElement( $name );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::startList ($name)
Start list
Parameters
string $name
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 190 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStartList().
    {
        $this->checkStartList( $name );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::startObjectElement ($name, $mediaTypeName = null)
Start object element
Parameters
string $name
string $mediaTypeName
Reimplemented from eZ\Publish\Core\REST\Common\Output\Generator.
Definition at line 98 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStartObjectElement(), eZ\Publish\Core\REST\Common\Output\Generator\endAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\getMediaType(), eZ\Publish\Core\REST\Common\Output\Generator\isEmpty(), and eZ\Publish\Core\REST\Common\Output\Generator\startAttribute().
    {
        $this->checkStartObjectElement( $name );
        $this->isEmpty = false;
        $mediaTypeName = $mediaTypeName ?: $name;
        $this->xmlWriter->startElement( $name );
        $this->startAttribute( "media-type", $this->getMediaType( $mediaTypeName ) );
        $this->endAttribute( "media-type" );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml::startValueElement ($name, $value, $attributes = array())
Start value element
Parameters
string $name
string $value
array $attributes
Definition at line 157 of file Xml.php.
References eZ\Publish\Core\REST\Common\Output\Generator\checkStartValueElement().
    {
        $this->checkStartValueElement( $name );
        $this->xmlWriter->startElement( $name );
        foreach ( $attributes as $attributeName => $attributeValue )
        {
            $this->xmlWriter->startAttribute( $attributeName );
            $this->xmlWriter->text( $attributeValue );
            $this->xmlWriter->endAttribute();
        }
        $this->xmlWriter->text( $value );
    }
Member Data Documentation
eZ\Publish\Core\REST\Common\Output\Generator\Xml::$hashGenerator protected
Definition at line 31 of file Xml.php.
eZ\Publish\Core\REST\Common\Output\Generator\Xml::$isEmpty = true protected
Definition at line 38 of file Xml.php.
eZ\Publish\Core\REST\Common\Output\Generator\Xml::$xmlWriter protected
Definition at line 24 of file Xml.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/Output/Generator/Xml.php