ezp-next: eZ\Publish\Core\Repository\LocationService Class Reference
eZ\Publish\Core\Repository\LocationService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, Handler $handler, array $settings=array())
loadLocation ($locationId)
loadLocationByRemoteId ($remoteId)
loadLocations (APIContentInfo $contentInfo, APILocation $rootLocation=null)
loadLocationChildren (APILocation $location, $offset=0, $limit=-1)
getLocationChildCount (APILocation $location)
createLocation (APIContentInfo $contentInfo, LocationCreateStruct $locationCreateStruct)
updateLocation (APILocation $location, LocationUpdateStruct $locationUpdateStruct)
swapLocation (APILocation $location1, APILocation $location2)
hideLocation (APILocation $location)
unhideLocation (APILocation $location)
newLocationCreateStruct ($parentLocationId)
newLocationUpdateStruct ()
Public Member Functions inherited from eZ\Publish\API\Repository\LocationService
copySubtree (Location $subtree, Location $targetParentLocation)
loadLocations (ContentInfo $contentInfo, Location $rootLocation=null)
loadLocationChildren (Location $location, $offset=0, $limit=-1)
getLocationChildCount (Location $location)
createLocation (ContentInfo $contentInfo, LocationCreateStruct $locationCreateStruct)
updateLocation (Location $location, LocationUpdateStruct $locationUpdateStruct)
swapLocation (Location $location1, Location $location2)
hideLocation (Location $location)
unhideLocation (Location $location)
moveSubtree (Location $location, Location $newParentLocation)
deleteLocation (Location $location)
Protected Member Functions
searchChildrenLocations ($parentLocationId, $sortField=null, $sortOrder=APILocation::SORT_ORDER_ASC, $offset=0, $limit=-1)
buildDomainLocationObject (SPILocation $spiLocation)
getDateTime ($timestamp)
getSortClauseBySortField ($sortField, $sortOrder=APILocation::SORT_ORDER_ASC)
Protected Attributes
$repository
$persistenceHandler
$settings
Detailed Description
Definition at line 47 of file LocationService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\LocationService::__construct (RepositoryInterface $repository, Handler $handler, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\API\Repository\Repository $repository
\eZ\Publish\SPI\Persistence\Handler $handler
array $settings
Definition at line 71 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\$repository, and eZ\Publish\Core\Repository\LocationService\$settings.
    {
        $this->repository = $repository;
        $this->persistenceHandler = $handler;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            //'defaultSetting' => array(),
        );
    }
Member Function Documentation
eZ\Publish\Core\Repository\LocationService::buildDomainLocationObject (SPILocation $spiLocation) protected
Builds domain location object from provided persistence location
Parameters
\eZ\Publish\SPI\Persistence\Content\Location $spiLocation
Returns
Definition at line 871 of file LocationService.php.
    {
        if ( $spiLocation->id == 1 )// Workaround for missing ContentInfo on root location
            $contentInfo = new ContentInfo(
                array(
                    'id' => 0,
                    'name' => 'Top Level Nodes',
                    'sectionId' => 1,
                    'mainLocationId' => 1,
                    'contentType' => new ContentType(
                        array(
                            'identifier' => 'folder',
                            'isContainer' => true,
                            'fieldDefinitions' => array()
                        )
                    )
                )
            );
        else // @todo This should not be loaded separately, SPI need to change to fix this.
            $contentInfo = $this->repository->getContentService()->internalLoadContentInfo( $spiLocation->contentId );
        return new Location(
            array(
                'contentInfo' => $contentInfo,
                'id' => (int)$spiLocation->id,
                'priority' => (int)$spiLocation->priority,
                'hidden' => (bool)$spiLocation->hidden,
                'invisible' => (bool)$spiLocation->invisible,
                'remoteId' => $spiLocation->remoteId,
                'parentLocationId' => (int)$spiLocation->parentId,
                'pathString' => $spiLocation->pathString,
                'depth' => (int)$spiLocation->depth,
                'sortField' => (int)$spiLocation->sortField,
                'sortOrder' => (int)$spiLocation->sortOrder,
            )
        );
    }
eZ\Publish\Core\Repository\LocationService::createLocation (APIContentInfo $contentInfo, LocationCreateStruct $locationCreateStruct)
Creates the new $location in the content repository for the given content
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to create this location
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the content is already below the specified parent or the parent is a sub location of the location of the content or if set the remoteId exists already
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
\eZ\Publish\API\Repository\Values\Content\LocationCreateStruct $locationCreateStruct
Returns
the newly created Location
Definition at line 404 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\buildDomainLocationObject(), eZ\Publish\Core\Repository\LocationService\loadLocation(), eZ\Publish\Core\Repository\LocationService\loadLocationByRemoteId(), and eZ\Publish\Core\Repository\LocationService\loadLocations().
    {
        if ( !is_numeric( $contentInfo->id ) )
            throw new InvalidArgumentValue( "id", $contentInfo->id, "ContentInfo" );
        if ( !is_numeric( $contentInfo->currentVersionNo ) )
            throw new InvalidArgumentValue( "currentVersionNo", $contentInfo->currentVersionNo, "ContentInfo" );
        if ( !is_numeric( $locationCreateStruct->parentLocationId ) )
            throw new InvalidArgumentValue( "parentLocationId", $locationCreateStruct->parentLocationId, "LocationCreateStruct" );
        if ( $locationCreateStruct->priority !== null && !is_numeric( $locationCreateStruct->priority ) )
            throw new InvalidArgumentValue( "priority", $locationCreateStruct->priority, "LocationCreateStruct" );
        if ( !is_bool( $locationCreateStruct->hidden ) )
            throw new InvalidArgumentValue( "hidden", $locationCreateStruct->hidden, "LocationCreateStruct" );
        if ( $locationCreateStruct->remoteId !== null && ( !is_string( $locationCreateStruct->remoteId ) || empty( $locationCreateStruct->remoteId ) ) )
            throw new InvalidArgumentValue( "remoteId", $locationCreateStruct->remoteId, "LocationCreateStruct" );
        if ( $locationCreateStruct->sortField !== null && !is_numeric( $locationCreateStruct->sortField ) )
            throw new InvalidArgumentValue( "sortField", $locationCreateStruct->sortField, "LocationCreateStruct" );
        if ( $locationCreateStruct->sortOrder !== null && !is_numeric( $locationCreateStruct->sortOrder ) )
            throw new InvalidArgumentValue( "sortOrder", $locationCreateStruct->sortOrder, "LocationCreateStruct" );
        // check for existence of location with provided remote ID
        if ( $locationCreateStruct->remoteId !== null )
        {
            try
            {
                $existingLocation = $this->loadLocationByRemoteId( $locationCreateStruct->remoteId );
                if ( $existingLocation !== null )
                    throw new InvalidArgumentException( "locationCreateStruct", "location with provided remote ID already exists" );
            }
            catch ( APINotFoundException $e )
            {
            }
        }
        else
        {
            $locationCreateStruct->remoteId = md5( uniqid( get_class( $this ), true ) );
        }
        $loadedParentLocation = $this->loadLocation( $locationCreateStruct->parentLocationId );
        // Check if the parent is a sub location of one of the existing content locations (this also solves the
        // situation where parent location actually one of the content locations),
        // or if the content already has location below given location create struct parent
        $existingContentLocations = $this->loadLocations( $contentInfo );
        if ( !empty( $existingContentLocations ) )
        {
            foreach ( $existingContentLocations as $existingContentLocation )
            {
                if ( stripos( $loadedParentLocation->pathString, $existingContentLocation->pathString ) !== false )
                    throw new InvalidArgumentException( "locationCreateStruct", "specified parent is a sub location of one of the existing content locations" );
                if ( $loadedParentLocation->id == $existingContentLocation->parentLocationId )
                    throw new InvalidArgumentException( "locationCreateStruct", "content is already below the specified parent" );
            }
        }
        if ( !$this->repository->canUser( 'content', 'create', $contentInfo, $loadedParentLocation ) )
            throw new UnauthorizedException( 'content', 'create' );
        $createStruct = new CreateStruct();
        $createStruct->priority = $locationCreateStruct->priority !== null ? (int)$locationCreateStruct->priority : null;
        // if we declare the new location as hidden, it is automatically invisible
        // otherwise, it remains unhidden, and picks up visibility from parent
        if ( $locationCreateStruct->hidden === true )
        {
            $createStruct->hidden = true;
            $createStruct->invisible = true;
        }
        else if ( $loadedParentLocation->hidden || $loadedParentLocation->invisible )
        {
            $createStruct->invisible = true;
        }
        $createStruct->remoteId = trim( $locationCreateStruct->remoteId );
        $createStruct->contentId = (int)$contentInfo->id;
        $createStruct->contentVersion = (int)$contentInfo->currentVersionNo;
        if ( $contentInfo->mainLocationId !== null )
            $createStruct->mainLocationId = $contentInfo->mainLocationId;
        $createStruct->sortField = $locationCreateStruct->sortField !== null ? (int)$locationCreateStruct->sortField : APILocation::SORT_FIELD_NAME;
        $createStruct->sortOrder = $locationCreateStruct->sortOrder !== null ? (int)$locationCreateStruct->sortOrder : APILocation::SORT_ORDER_ASC;
        $createStruct->parentId = $loadedParentLocation->id;
        $this->repository->beginTransaction();
        try
        {
            $newLocation = $this->persistenceHandler->locationHandler()->create( $createStruct );
            $content = $this->repository->getContentService()->loadContent( $newLocation->contentId );
            $urlAliasNames = $this->repository->getNameSchemaService()->resolveUrlAliasSchema( $content );
            foreach ( $urlAliasNames as $languageCode => $name )
            {
                $this->persistenceHandler->urlAliasHandler()->publishUrlAliasForLocation(
                    $newLocation->id,
                    $newLocation->parentId,
                    $name,
                    $languageCode,
                    $content->contentInfo->alwaysAvailable,
                    // @todo: this is legacy storage specific for updating ezcontentobject_tree.path_identification_string, to be removed
                    $languageCode === $content->contentInfo->mainLanguageCode
                );
            }
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainLocationObject( $newLocation );
    }
eZ\Publish\Core\Repository\LocationService::getDateTime ($timestamp) protected
Parameters
int | null $timestamp
Returns
|null
Definition at line 914 of file LocationService.php.
    {
        $dateTime = new DateTime();
        $dateTime->setTimestamp( $timestamp );
        return $dateTime;
    }
eZ\Publish\Core\Repository\LocationService::getLocationChildCount (APILocation $location)
Returns the number of children which are readable by the current user of a location object
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location
Returns
int
Definition at line 339 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\searchChildrenLocations().
    {
        if ( !is_numeric( $location->id ) )
            throw new InvalidArgumentValue( "id", $location->id, "Location" );
        return $this->searchChildrenLocations(
            $location->id,
            null,
            APILocation::SORT_ORDER_ASC,
            0,
            0
        )->totalCount;
    }
eZ\Publish\Core\Repository\LocationService::getSortClauseBySortField ($sortField, $sortOrder = APILocation::SORT_ORDER_ASC) protected
Instantiates a correct sort clause object based on provided location sort field and sort order
Parameters
int $sortField
int $sortOrder
Returns
Definition at line 929 of file LocationService.php.
References eZ\Publish\API\Repository\Values\Content\Query\SORT_ASC, and eZ\Publish\API\Repository\Values\Content\Query\SORT_DESC.
    {
        $sortOrder = $sortOrder == APILocation::SORT_ORDER_DESC ? Query::SORT_DESC : Query::SORT_ASC;
        switch ( $sortField )
        {
            case APILocation::SORT_FIELD_PATH:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\LocationPathString( $sortOrder );
            case APILocation::SORT_FIELD_PUBLISHED:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\DatePublished( $sortOrder );
            case APILocation::SORT_FIELD_MODIFIED:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\DateModified( $sortOrder );
            case APILocation::SORT_FIELD_SECTION:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\SectionIdentifier( $sortOrder );
            case APILocation::SORT_FIELD_DEPTH:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\LocationDepth( $sortOrder );
            //@todo: enable
            // case APILocation::SORT_FIELD_CLASS_IDENTIFIER:
            //@todo: enable
            // case APILocation::SORT_FIELD_CLASS_NAME:
            case APILocation::SORT_FIELD_PRIORITY:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\LocationPriority( $sortOrder );
            case APILocation::SORT_FIELD_NAME:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\ContentName( $sortOrder );
            //@todo: enable
            // case APILocation::SORT_FIELD_MODIFIED_SUBNODE:
            //@todo: enable
            // case APILocation::SORT_FIELD_NODE_ID:
            //@todo: enable
            // case APILocation::SORT_FIELD_CONTENTOBJECT_ID:
            default:
                return new \eZ\Publish\API\Repository\Values\Content\Query\SortClause\LocationPathString( $sortOrder );
        }
    }
eZ\Publish\Core\Repository\LocationService::hideLocation (APILocation $location)
Hides the $location and marks invisible all descendants of $location.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to hide this location
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location
Returns
$location, with updated hidden value
Definition at line 638 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\loadLocation().
    {
        if ( !is_numeric( $location->id ) )
            throw new InvalidArgumentValue( "id", $location->id, "Location" );
        if ( !$this->repository->canUser( 'content', 'hide', $location->getContentInfo(), $location ) )
            throw new UnauthorizedException( 'content', 'hide' );
        $this->repository->beginTransaction();
        try
        {
            $this->persistenceHandler->locationHandler()->hide( $location->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->loadLocation( $location->id );
    }
eZ\Publish\Core\Repository\LocationService::loadLocation ($locationId)
Loads a location object from its $locationId
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to read this location
\eZ\Publish\API\Repository\Exceptions\NotFoundException If the specified location is not found
Parameters
int $locationId
Returns
Implements eZ\Publish\API\Repository\LocationService.
Definition at line 188 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\buildDomainLocationObject().
    {
        if ( !is_numeric( $locationId ) )
            throw new InvalidArgumentValue( "locationId", $locationId );
        $spiLocation = $this->persistenceHandler->locationHandler()->load( $locationId );
        $location = $this->buildDomainLocationObject( $spiLocation );
        if ( !$this->repository->canUser( 'content', 'read', $location->getContentInfo(), $location ) )
            throw new UnauthorizedException( 'content', 'read' );
        return $location;
    }
eZ\Publish\Core\Repository\LocationService::loadLocationByRemoteId ($remoteId)
Loads a location object from its $remoteId
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to read this location
\eZ\Publish\API\Repository\Exceptions\BadStateException If more than one location with same remote ID was found
\eZ\Publish\API\Repository\Exceptions\NotFoundException If the specified location is not found
Parameters
string $remoteId
Returns
Implements eZ\Publish\API\Repository\LocationService.
Definition at line 212 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\buildDomainLocationObject().
    {
        if ( !is_string( $remoteId ) )
            throw new InvalidArgumentValue( "remoteId", $remoteId );
        $spiLocation = $this->persistenceHandler->locationHandler()->loadByRemoteId( $remoteId );
        $location = $this->buildDomainLocationObject( $spiLocation );
        if ( !$this->repository->canUser( 'content', 'read', $location->getContentInfo(), $location ) )
            throw new UnauthorizedException( 'content', 'read' );
        return $location;
    }
eZ\Publish\Core\Repository\LocationService::loadLocationChildren (APILocation $location, $offset = 0, $limit = -1)
Loads children which are readable by the current user of a location object sorted by sortField and sortOrder
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location
int $offset the start offset for paging
int $limit the number of locations returned. If $limit = -1 all children starting at $offset are returned
Returns
Definition at line 279 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\buildDomainLocationObject(), and eZ\Publish\Core\Repository\LocationService\searchChildrenLocations().
    {
        if ( !is_numeric( $location->id ) )
            throw new InvalidArgumentValue( "id", $location->id, "Location" );
        if ( !is_numeric( $location->sortField ) )
            throw new InvalidArgumentValue( "sortField", $location->sortField, "Location" );
        if ( !is_numeric( $location->sortOrder ) )
            throw new InvalidArgumentValue( "sortOrder", $location->sortOrder, "Location" );
        if ( !is_numeric( $offset ) )
            throw new InvalidArgumentValue( "offset", $offset );
        if ( !is_numeric( $limit ) )
            throw new InvalidArgumentValue( "limit", $limit );
        $searchResult = $this->searchChildrenLocations(
            $location->id,
            $location->sortField,
            $location->sortOrder,
            $offset,
            $limit
        );
        $childLocations = array();
        foreach ( $searchResult->searchHits as $spiSearchHit )
        {
            $spiContentLocations = $this->persistenceHandler->locationHandler()->loadLocationsByContent(
                $spiSearchHit->valueObject->versionInfo->contentInfo->id,
                $location->id
            );
            foreach ( $spiContentLocations as $spiLocation )
            {
                if ( $spiLocation->parentId == $location->id )
                {
                    $childLocation = $this->buildDomainLocationObject( $spiLocation );
                    if ( $this->repository->canUser( 'content', 'read', $childLocation->getContentInfo(), $childLocation ) )
                    {
                        $childLocations[] = $childLocation;
                    }
                }
            }
        }
        return new LocationList(
            array(
                "locations" => $childLocations,
                "totalCount" => (int)$searchResult->totalCount
            )
        );
    }
eZ\Publish\Core\Repository\LocationService::loadLocations (APIContentInfo $contentInfo, APILocation $rootLocation = null)
Loads the locations for the given content object.
If a $rootLocation is given, only locations that belong to this location are returned. The location list is also filtered by permissions on reading locations.
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException if there is no published version yet
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
\eZ\Publish\API\Repository\Values\Content\Location $rootLocation
Returns
[] An array of Location
Definition at line 238 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\buildDomainLocationObject().
    {
        if ( !is_numeric( $contentInfo->id ) )
        {
            throw new InvalidArgumentValue( "id", $contentInfo->id, "ContentInfo" );
        }
        if ( $rootLocation !== null && !is_numeric( $rootLocation->id ) )
        {
            throw new InvalidArgumentValue( "pathString", $rootLocation->pathString, "Location" );
        }
        if ( !$contentInfo->published )
        {
            throw new BadStateException( "\$contentInfo", "ContentInfo has no published versions" );
        }
        $spiLocations = $this->persistenceHandler->locationHandler()->loadLocationsByContent(
            $contentInfo->id,
            isset( $rootLocation ) ? $rootLocation->id : null
        );
        $locations = array();
        foreach ( $spiLocations as $spiLocation )
        {
            $locations[] = $this->buildDomainLocationObject( $spiLocation );
        }
        return $locations;
    }
eZ\Publish\Core\Repository\LocationService::newLocationCreateStruct ($parentLocationId)
Instantiates a new location create class
Parameters
mixed $parentLocationId the parent under which the new location should be created
Returns
Implements eZ\Publish\API\Repository\LocationService.
Definition at line 845 of file LocationService.php.
    {
        return new LocationCreateStruct(
            array(
                'parentLocationId' => (int)$parentLocationId
            )
        );
    }
eZ\Publish\Core\Repository\LocationService::newLocationUpdateStruct ()
Instantiates a new location update class
Returns
Implements eZ\Publish\API\Repository\LocationService.
Definition at line 859 of file LocationService.php.
    {
        return new LocationUpdateStruct();
    }
eZ\Publish\Core\Repository\LocationService::searchChildrenLocations ($parentLocationId, $sortField = null, $sortOrder = APILocation::SORT_ORDER_ASC, $offset = 0, $limit = -1) protected
Searches children locations of the provided parent location id
Parameters
int $parentLocationId
int $sortField
int $sortOrder
int $offset
int $limit
Returns
Definition at line 364 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\getSortClauseBySortField().
    {
        $query = new Query(
            array(
                'criterion' => new CriterionLogicalAnd(
                    array(
                        new CriterionParentLocationId( $parentLocationId ),
                        new CriterionStatus( CriterionStatus::STATUS_PUBLISHED ),
                    )
                ),
                'offset' => ( $offset >= 0 ? (int)$offset : 0 ),
                'limit' => ( $limit >= 0 ? (int)$limit  : null )
            )
        );
        if ( $sortField !== null )
            $query->sortClauses = array( $this->getSortClauseBySortField( $sortField, $sortOrder ) );
        if ( !$this->repository->getSearchService()->addPermissionsCriterion( $query->criterion ) )
        {
            return array();
        }
        return $this->persistenceHandler->searchHandler()->findContent( $query );
    }
eZ\Publish\Core\Repository\LocationService::swapLocation (APILocation $location1, APILocation $location2)
Swaps the contents held by $location1 and $location2
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to swap content
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location1
\eZ\Publish\API\Repository\Values\Content\Location $location2
Definition at line 600 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\loadLocation().
    {
        if ( !is_numeric( $location1->id ) )
            throw new InvalidArgumentValue( "id", $location1->id, "Location" );
        if ( !is_numeric( $location2->id ) )
            throw new InvalidArgumentValue( "id", $location2->id, "Location" );
        $loadedLocation1 = $this->loadLocation( $location1->id );
        $loadedLocation2 = $this->loadLocation( $location2->id );
        if ( !$this->repository->canUser( 'content', 'edit', $loadedLocation1->getContentInfo(), $loadedLocation1 ) )
            throw new UnauthorizedException( 'content', 'edit' );
        if ( !$this->repository->canUser( 'content', 'edit', $loadedLocation2->getContentInfo(), $loadedLocation2 ) )
            throw new UnauthorizedException( 'content', 'edit' );
        $this->repository->beginTransaction();
        try
        {
            $this->persistenceHandler->locationHandler()->swap( $loadedLocation1->id, $loadedLocation2->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\LocationService::unhideLocation (APILocation $location)
Unhides the $location.
This method and marks visible all descendants of $locations until a hidden location is found.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to unhide this location
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location
Returns
$location, with updated hidden value
Definition at line 673 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\loadLocation().
    {
        if ( !is_numeric( $location->id ) )
            throw new InvalidArgumentValue( "id", $location->id, "Location" );
        if ( !$this->repository->canUser( 'content', 'hide', $location->getContentInfo(), $location ) )
            throw new UnauthorizedException( 'content', 'hide' );
        $this->repository->beginTransaction();
        try
        {
            $this->persistenceHandler->locationHandler()->unHide( $location->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->loadLocation( $location->id );
    }
eZ\Publish\Core\Repository\LocationService::updateLocation (APILocation $location, LocationUpdateStruct $locationUpdateStruct)
Updates $location in the content repository
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to update this location
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if if set the remoteId exists already
Parameters
\eZ\Publish\API\Repository\Values\Content\Location $location
\eZ\Publish\API\Repository\Values\Content\LocationUpdateStruct $locationUpdateStruct
Returns
the updated Location
Definition at line 536 of file LocationService.php.
References eZ\Publish\Core\Repository\LocationService\loadLocation(), and eZ\Publish\Core\Repository\LocationService\loadLocationByRemoteId().
    {
        if ( !is_numeric( $location->id ) )
            throw new InvalidArgumentValue( "id", $location->id, "Location" );
        if ( $locationUpdateStruct->priority !== null && !is_numeric( $locationUpdateStruct->priority ) )
            throw new InvalidArgumentValue( "priority", $locationUpdateStruct->priority, "LocationUpdateStruct" );
        if ( $locationUpdateStruct->remoteId !== null && ( !is_string( $locationUpdateStruct->remoteId ) || empty( $locationUpdateStruct->remoteId ) ) )
            throw new InvalidArgumentValue( "remoteId", $locationUpdateStruct->remoteId, "LocationUpdateStruct" );
        if ( $locationUpdateStruct->sortField !== null && !is_numeric( $locationUpdateStruct->sortField ) )
            throw new InvalidArgumentValue( "sortField", $locationUpdateStruct->sortField, "LocationUpdateStruct" );
        if ( $locationUpdateStruct->sortOrder !== null && !is_numeric( $locationUpdateStruct->sortOrder ) )
            throw new InvalidArgumentValue( "sortOrder", $locationUpdateStruct->sortOrder, "LocationUpdateStruct" );
        $loadedLocation = $this->loadLocation( $location->id );
        if ( $locationUpdateStruct->remoteId !== null )
        {
            try
            {
                $existingLocation = $this->loadLocationByRemoteId( $locationUpdateStruct->remoteId );
                if ( $existingLocation !== null )
                    throw new InvalidArgumentException( "locationUpdateStruct", "location with provided remote ID already exists" );
            }
            catch ( APINotFoundException $e )
            {
            }
        }
        if ( !$this->repository->canUser( 'content', 'edit', $loadedLocation->getContentInfo(), $loadedLocation ) )
            throw new UnauthorizedException( 'content', 'edit' );
        $updateStruct = new UpdateStruct();
        $updateStruct->priority = $locationUpdateStruct->priority !== null ? (int)$locationUpdateStruct->priority : $loadedLocation->priority;
        $updateStruct->remoteId = $locationUpdateStruct->remoteId !== null ? trim( $locationUpdateStruct->remoteId ) : $loadedLocation->remoteId;
        $updateStruct->sortField = $locationUpdateStruct->sortField !== null ? (int)$locationUpdateStruct->sortField : $loadedLocation->sortField;
        $updateStruct->sortOrder = $locationUpdateStruct->sortOrder !== null ? (int)$locationUpdateStruct->sortOrder : $loadedLocation->sortOrder;
        $this->repository->beginTransaction();
        try
        {
            $this->persistenceHandler->locationHandler()->update( $updateStruct, $loadedLocation->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->loadLocation( $loadedLocation->id );
    }
Member Data Documentation
eZ\Publish\Core\Repository\LocationService::$persistenceHandler protected
Definition at line 57 of file LocationService.php.
eZ\Publish\Core\Repository\LocationService::$repository protected
Definition at line 52 of file LocationService.php.
eZ\Publish\Core\Repository\LocationService::$settings protected
Definition at line 62 of file LocationService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/LocationService.php