ezp-next: eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLAlias Class Reference
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLAlias Class Reference
Public Member Functions
visit (Visitor $visitor, Generator $generator, $data)
Public Member Functions inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
__construct (UrlHandler $urlHandler)
Protected Member Functions
serializeType ($urlAliasType)
Protected Member Functions inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
serializeBool ($boolValue)
visitNamesList (Generator $generator, array $names)
visitDescriptionsList (Generator $generator, array $descriptions)
visitTranslatedList (Generator $generator, array $translatedElements, $listName)
visitLimitation (Generator $generator, Limitation $limitation)
serializeSortField ($sortField)
serializeSortOrder ($sortOrder)
Additional Inherited Members
Protected Attributes inherited from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor
$urlHandler
Detailed Description
URLAlias value object visitor
Definition at line 20 of file URLAlias.php.
Member Function Documentation
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLAlias::serializeType ($urlAliasType) protected
Serializes the given $urlAliasType to a string representation
Parameters
int $urlAliasType
Returns
string
Definition at line 90 of file URLAlias.php.
    {
        switch ( $urlAliasType )
        {
            case Values\Content\URLAlias::LOCATION:
                return 'LOCATION';
            case Values\Content\URLAlias::RESOURCE:
                return 'RESOURCE';
            case Values\Content\URLAlias::VIRTUAL:
                return 'VIRTUAL';
        }
        throw new \RuntimeException( "Unknown URL alias type: '{$urlAliasType}'." );
    }
eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLAlias::visit (Visitor $visitor, Generator $generator, $data)
Visit struct returned by controllers
Parameters
\eZ\Publish\Core\REST\Common\Output\Visitor $visitor
\eZ\Publish\Core\REST\Common\Output\Generator $generator
\eZ\Publish\API\Repository\Values\Content\URLAlias $data
Reimplemented from eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor.
Reimplemented in eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\CreatedURLAlias.
Definition at line 29 of file URLAlias.php.
References eZ\Publish\Core\REST\Common\Output\Generator\endAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\endObjectElement(), eZ\Publish\Core\REST\Common\Output\Generator\endValueElement(), eZ\Publish\Core\REST\Common\Output\Generator\getMediaType(), eZ\Publish\Core\REST\Common\Output\ValueObjectVisitor\serializeBool(), eZ\Publish\Core\REST\Server\Output\ValueObjectVisitor\URLAlias\serializeType(), eZ\Publish\Core\REST\Common\Output\Visitor\setHeader(), eZ\Publish\Core\REST\Common\Output\Generator\startAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\startObjectElement(), and eZ\Publish\Core\REST\Common\Output\Generator\startValueElement().
    {
        $generator->startObjectElement( 'UrlAlias' );
        $visitor->setHeader( 'Content-Type', $generator->getMediaType( 'UrlAlias' ) );
        $generator->startAttribute(
            'href',
            $this->urlHandler->generate( 'urlAlias', array( 'urlalias' => $data->id ) )
        );
        $generator->endAttribute( 'href' );
        $generator->startAttribute( 'id', $data->id );
        $generator->endAttribute( 'id' );
        $generator->startAttribute( 'type', $this->serializeType( $data->type ) );
        $generator->endAttribute( 'type' );
        if ( $data->type === Values\Content\URLAlias::LOCATION )
        {
            $generator->startObjectElement( 'location', 'Location' );
            $generator->startAttribute(
                'href',
                $this->urlHandler->generate( 'locationById', array( 'location' => $data->destination ) )
            );
            $generator->endAttribute( 'href' );
            $generator->endObjectElement( 'location' );
        }
        else
        {
            $generator->startValueElement( 'resource', $data->destination );
            $generator->endValueElement( 'resource' );
        }
        $generator->startValueElement( 'path', $data->path );
        $generator->endValueElement( 'path' );
        $generator->startValueElement( 'languageCodes', implode( ',', $data->languageCodes ) );
        $generator->endValueElement( 'languageCodes' );
        $generator->startValueElement( 'alwaysAvailable', $this->serializeBool( $data->alwaysAvailable ) );
        $generator->endValueElement( 'alwaysAvailable' );
        $generator->startValueElement( 'isHistory', $this->serializeBool( $data->isHistory ) );
        $generator->endValueElement( 'isHistory' );
        $generator->startValueElement( 'forward', $this->serializeBool( $data->forward ) );
        $generator->endValueElement( 'forward' );
        $generator->startValueElement( 'custom', $this->serializeBool( $data->isCustom ) );
        $generator->endValueElement( 'custom' );
        $generator->endObjectElement( 'UrlAlias' );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/URLAlias.php