ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion Class Reference
Public Member Functions
__construct (Gateway $innerGateway)
insertGroup (Group $group)
updateGroup (GroupUpdateStruct $group)
countTypesInGroup ($groupId)
countGroupsForType ($typeId, $status)
deleteGroup ($groupId)
loadGroupData ($groupId)
loadGroupDataByIdentifier ($identifier)
loadAllGroupsData ()
loadTypesDataForGroup ($groupId, $status)
insertType (Type $type, $typeId=null)
insertGroupAssignment ($typeId, $status, $groupId)
deleteGroupAssignment ($groupId, $typeId, $status)
loadFieldDefinition ($id, $status)
insertFieldDefinition ($typeId, $status, FieldDefinition $fieldDefinition, StorageFieldDefinition $storageFieldDef)
deleteFieldDefinition ($typeId, $status, $fieldDefinitionId)
updateFieldDefinition ($typeId, $status, FieldDefinition $fieldDefinition, StorageFieldDefinition $storageFieldDef)
updateType ($typeId, $status, UpdateStruct $updateStruct)
loadTypeData ($typeId, $status)
loadTypeDataByIdentifier ($identifier, $status)
loadTypeDataByRemoteId ($remoteId, $status)
countInstancesOfType ($typeId)
delete ($typeId, $status)
deleteFieldDefinitionsForType ($typeId, $status)
deleteType ($typeId, $status)
deleteGroupAssignmentsForType ($typeId, $status)
publishTypeAndFields ($typeId, $sourceStatus, $targetStatus)
Public Member Functions inherited from eZ\Publish\Core\Persistence\Legacy\Content\Gateway
getContext ()
insertContentObject (CreateStruct $struct, $currentVersionNo=1)
insertVersion (VersionInfo $versionInfo, array $fields)
updateContent ($contentId, MetadataUpdateStruct $struct)
updateVersion ($contentId, $versionNo, UpdateStruct $struct)
updateAlwaysAvailableFlag ($contentId, $newAlwaysAvailable)
setStatus ($contentId, $version, $status)
insertNewField (Content $content, Field $field, StorageFieldValue $value)
insertExistingField (Content $content, Field $field, StorageFieldValue $value)
updateField (Field $field, StorageFieldValue $value)
updateNonTranslatableField (Field $field, StorageFieldValue $value, $contentId)
load ($contentId, $version, $translations=null)
loadContentInfo ($contentId)
loadVersionInfo ($contentId, $versionNo)
listVersionsForUser ($userId, $status=VersionInfo::STATUS_DRAFT)
listVersions ($contentId)
getLastVersionNumber ($contentId)
getAllLocationIds ($contentId)
getFieldIdsByType ($contentId, $versionNo=null)
deleteRelations ($contentId, $versionNo=null)
deleteField ($fieldId, $version)
deleteFields ($contentId, $versionNo=null)
deleteVersions ($contentId, $versionNo=null)
deleteNames ($contentId, $versionNo=null)
setName ($contentId, $version, $name, $language)
deleteContent ($contentId)
loadLatestPublishedData ($contentId)
loadRelations ($contentId, $contentVersionNo=null, $relationType=null)
loadReverseRelations ($contentId, $relationType=null)
deleteRelation ($relationId)
insertRelation (RelationCreateStruct $createStruct)
Protected Attributes
$innerGateway
Detailed Description
Base class for content type gateways.
Definition at line 23 of file ExceptionConversion.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::__construct (Gateway $innerGateway)
Creates a new exception conversion gateway around $innerGateway
Parameters
Gateway $innerGateway
Definition at line 37 of file ExceptionConversion.php.
    {
        $this->innerGateway = $innerGateway;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::countGroupsForType ($typeId, $status)
Returns the number of Groups the type is assigned to.
Parameters
int $typeId
int $status
Returns
int
Definition at line 119 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\countGroupsForType().
    {
        try
        {
            return $this->innerGateway->countGroupsForType( $typeId, $status );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::countInstancesOfType ($typeId)
Counts the number of instances that exists of the identified type.
Parameters
int $typeId
Returns
int
Definition at line 536 of file ExceptionConversion.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\countInstancesOfType().
    {
        try
        {
            return $this->innerGateway->countInstancesOfType( $typeId );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::countTypesInGroup ($groupId)
Returns the number of types in a certain group.
Parameters
int $groupId
Returns
int
Definition at line 95 of file ExceptionConversion.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\countTypesInGroup().
    {
        try
        {
            return $this->innerGateway->countTypesInGroup( $groupId );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::delete ($typeId, $status)
Deletes a Type completely.
Parameters
mixed $typeId
int $status
Returns
void
Definition at line 560 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status.
    {
        try
        {
            return $this->innerGateway->delete( $typeId, $status );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::deleteFieldDefinition ($typeId, $status, $fieldDefinitionId)
Deletes a field definition.
Parameters
mixed $typeId
int $status
mixed $fieldDefinitionId
Returns
void
Definition at line 385 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\deleteFieldDefinition().
    {
        try
        {
            return $this->innerGateway->deleteFieldDefinition( $typeId, $status, $fieldDefinitionId );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::deleteFieldDefinitionsForType ($typeId, $status)
Deletes all field definitions of a Type.
Parameters
mixed $typeId
int $status
Returns
void
Definition at line 584 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\deleteFieldDefinitionsForType().
    {
        try
        {
            return $this->innerGateway->deleteFieldDefinitionsForType( $typeId, $status );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::deleteGroup ($groupId)
Deletes the Group with the given $groupId.
Parameters
int $groupId
Returns
void
Definition at line 142 of file ExceptionConversion.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\deleteGroup().
    {
        try
        {
            return $this->innerGateway->deleteGroup( $groupId );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::deleteGroupAssignment ($groupId, $typeId, $status)
Deletes a group assignments for a Type.
Parameters
mixed $groupId
mixed $typeId
int $status
Returns
void
Definition at line 307 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\deleteGroupAssignment().
    {
        try
        {
            return $this->innerGateway->deleteGroupAssignment( $groupId, $typeId, $status );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::deleteGroupAssignmentsForType ($typeId, $status)
Deletes all group assignments for a Type.
Parameters
mixed $typeId
int $status
Returns
void
Definition at line 634 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\deleteGroupAssignmentsForType().
    {
        try
        {
            return $this->innerGateway->deleteGroupAssignmentsForType( $typeId, $status );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::deleteType ($typeId, $status)
Deletes a the Type.
Does no delete the field definitions!
Parameters
mixed $typeId
int $status
Returns
void
Definition at line 610 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\deleteType().
    {
        try
        {
            return $this->innerGateway->deleteType( $typeId, $status );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::insertFieldDefinition ($typeId, $status, FieldDefinition $fieldDefinition, StorageFieldDefinition $storageFieldDef)
Inserts a $fieldDefinition for $typeId.
Parameters
mixed $typeId
int $status
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageFieldDef
Returns
mixed Field definition ID
Definition at line 357 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\insertFieldDefinition().
    {
        try
        {
            return $this->innerGateway->insertFieldDefinition( $typeId, $status, $fieldDefinition, $storageFieldDef );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::insertGroup (Group $group)
Inserts the given $group.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group $group
Returns
mixed Group ID
Definition at line 49 of file ExceptionConversion.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\insertGroup(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\insertGroup().
    {
        try
        {
            return $this->innerGateway->insertGroup( $group );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::insertGroupAssignment ($typeId, $status, $groupId)
Insert assignment of $typeId to $groupId.
Parameters
mixed $typeId
int $status
mixed $groupId
Returns
void
Definition at line 282 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\insertGroupAssignment().
    {
        try
        {
            return $this->innerGateway->insertGroupAssignment( $typeId, $status, $groupId );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::insertType (Type $type, $typeId = null)
Inserts a new content type.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type $type
mixed | null $typeId
Returns
mixed Type ID
Definition at line 257 of file ExceptionConversion.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\insertType().
    {
        try
        {
            return $this->innerGateway->insertType( $type, $typeId );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::loadAllGroupsData ()
Returns an array with data about all Group objects.
Returns
array
Definition at line 209 of file ExceptionConversion.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\loadAllGroupsData().
    {
        try
        {
            return $this->innerGateway->loadAllGroupsData();
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::loadFieldDefinition ($id, $status)
Loads an array with data about field definition referred $id and $status.
Parameters
mixed $id field definition id
int $status field definition status
Returns
array Data rows.
Definition at line 331 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$id, eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\loadFieldDefinition().
    {
        try
        {
            return $this->innerGateway->loadFieldDefinition( $id, $status );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::loadGroupData ($groupId)
Returns an array with data about the Group with $groupId.
Parameters
int $groupId
Returns
array
Definition at line 165 of file ExceptionConversion.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\loadGroupData().
    {
        try
        {
            return $this->innerGateway->loadGroupData( $groupId );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::loadGroupDataByIdentifier ($identifier)
Returns an array with data about the Group with $identifier.
Parameters
int $identifier
Returns
array
Definition at line 188 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$identifier, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\loadGroupDataByIdentifier().
    {
        try
        {
            return $this->innerGateway->loadGroupDataByIdentifier( $identifier );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::loadTypeData ($typeId, $status)
Loads an array with data about $typeId in $status.
Parameters
mixed $typeId
int $status
Returns
array Data rows.
Definition at line 463 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\loadTypeData().
    {
        try
        {
            return $this->innerGateway->loadTypeData( $typeId, $status );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::loadTypeDataByIdentifier ($identifier, $status)
Loads an array with data about the type referred to by $identifier in $status.
Parameters
string $identifier
int $status
Returns
array(int=>array(string=>mixed)) Data rows.
Definition at line 488 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$identifier, eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\loadTypeDataByIdentifier().
    {
        try
        {
            return $this->innerGateway->loadTypeDataByIdentifier( $identifier, $status );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::loadTypeDataByRemoteId ($remoteId, $status)
Loads an array with data about the type referred to by $remoteId in $status.
Parameters
mixed $remoteId
int $status
Returns
array(int=>array(string=>mixed)) Data rows.
Definition at line 513 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$remoteId, eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\loadTypeDataByRemoteId().
    {
        try
        {
            return $this->innerGateway->loadTypeDataByRemoteId( $remoteId, $status );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::loadTypesDataForGroup ($groupId, $status)
Loads data for all Types in $status in $groupId.
Parameters
mixed $groupId
int $status
Returns
string[][]
Definition at line 233 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\loadTypesDataForGroup().
    {
        try
        {
            return $this->innerGateway->loadTypesDataForGroup( $groupId, $status );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::publishTypeAndFields ($typeId, $sourceStatus, $targetStatus)
Publishes the Type with $typeId from $sourceVersion to $targetVersion, including its fields
Parameters
int $typeId
int $sourceStatus
int $targetStatus
Returns
void
Definition at line 660 of file ExceptionConversion.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\publishTypeAndFields().
    {
        try
        {
            return $this->innerGateway->publishTypeAndFields( $typeId, $sourceStatus, $targetStatus );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::updateFieldDefinition ($typeId, $status, FieldDefinition $fieldDefinition, StorageFieldDefinition $storageFieldDef)
Updates a $fieldDefinition for $typeId.
Parameters
mixed $typeId
int $status
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageFieldDef
Returns
void
Definition at line 411 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\updateFieldDefinition().
    {
        try
        {
            return $this->innerGateway->updateFieldDefinition( $typeId, $status, $fieldDefinition, $storageFieldDef );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::updateGroup (GroupUpdateStruct $group)
Updates a group with data in $group.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group\UpdateStruct $group
Returns
void
Definition at line 72 of file ExceptionConversion.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\updateGroup().
    {
        try
        {
            return $this->innerGateway->updateGroup( $group );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::updateType ($typeId, $status, UpdateStruct $updateStruct)
Update a type with $updateStruct.
Parameters
mixed $typeId
int $status
\eZ\Publish\SPI\Persistence\Content\Type\UpdateStruct $updateStruct
Returns
void
Definition at line 439 of file ExceptionConversion.php.
References eZ\Publish\SPI\Persistence\Content\Type\$status, and eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion\updateType().
    {
        try
        {
            return $this->innerGateway->updateType( $typeId, $status, $updateStruct );
        }
        catch ( \ezcDbException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
        catch ( \PDOException $e )
        {
            throw new \RuntimeException( 'Database error', 0, $e );
        }
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\ExceptionConversion::$innerGateway protected
Definition at line 30 of file ExceptionConversion.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/ExceptionConversion.php