ezp-next: eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter Class Reference
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter Class Reference
Public Member Functions
__construct (LegacyConfigResolver $legacyResolver,\Closure $legacyKernel, array $supportedPackages)
fromLegacy ($sitePackage, $adminSiteaccess)
getGroup ($groupName, $file=null, $siteaccess=null)
getParameter ($groupName, $parameterName, $file=null, $siteaccess=null)
Protected Member Functions
getLanguages (array $siteList, $groupName)
getImageVariations (array $siteList, $groupName)
getImageVariationsForSiteaccess ($siteaccess)
mapDatabaseType ($databaseType)
resolveMatching ()
resolveUriMatching ($siteaccessSettings)
resolveHostMatching ($siteaccessSettings)
resolveTextMatch ($siteaccessSettings, $prefixKey, $suffixKey)
resolveMapMatch ($mapArray)
Protected Attributes
$legacyResolver
$legacyKernel
$supportedPackages
Detailed Description
Handles conversionlegacy eZ Publish 4 parameters from a set of settings to a configuration array suitable for yml dumping
Definition at line 21 of file ConfigurationConverter.php.
Constructor & Destructor Documentation
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::__construct (LegacyConfigResolver $legacyResolver, \Closure $legacyKernel, array $supportedPackages)
Definition at line 38 of file ConfigurationConverter.php.
References eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\$legacyKernel, and eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\$legacyResolver.
    {
        $this->legacyResolver = $legacyResolver;
        $this->legacyKernel = $legacyKernel();
        $this->supportedPackages = array_fill_keys( $supportedPackages, true );
    }
Member Function Documentation
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::fromLegacy ($sitePackage, $adminSiteaccess)
Converts from legacy settings to an array dumpable to ezpublish.yml
Parameters
string $sitePackage Name of the chosen install package
string $adminSiteaccess Name of the admin siteaccess
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException
Returns
array
Definition at line 54 of file ConfigurationConverter.php.
References eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\getGroup(), eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\getImageVariations(), eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\getLanguages(), eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\getParameter(), eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\mapDatabaseType(), and eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\resolveMatching().
    {
        $settings = array();
        $settings['ezpublish'] = array();
        $settings['ezpublish']['siteaccess'] = array();
        $defaultSiteaccess = $this->getParameter( 'SiteSettings', 'DefaultAccess' );
        $settings['ezpublish']['siteaccess']['default_siteaccess'] = $defaultSiteaccess;
        $siteList = $this->getParameter( 'SiteAccessSettings', 'AvailableSiteAccessList' );
        if ( !is_array( $siteList ) || empty( $siteList ) )
            throw new InvalidArgumentException( 'siteList', 'can not be empty' );
        if ( !in_array( $adminSiteaccess, $siteList ) )
            throw new InvalidArgumentException( "adminSiteaccess", "Siteaccess $adminSiteaccess wasn't found in SiteAccessSettings.AvailableSiteAccessList" );
        $settings['ezpublish']['siteaccess']['list'] = $siteList;
        $settings['ezpublish']['siteaccess']['groups'] = array();
        $groupName = $sitePackage . '_group';
        $settings['ezpublish']['siteaccess']['groups'][$groupName] = $siteList;
        $settings['ezpublish']['siteaccess']['match'] = $this->resolveMatching();
        $databaseMapping = array(
            'ezmysqli' => 'mysql',
            'eZMySQLiDB' => 'mysql',
            'ezmysql' => 'mysql',
            'eZMySQLDB' => 'mysql',
        );
        $databaseSettings = $this->getGroup( 'DatabaseSettings', 'site.ini', $defaultSiteaccess );
        $databaseType = $databaseSettings['DatabaseImplementation'];
        if ( isset( $databaseMapping[$databaseType] ) )
            $databaseType = $databaseMapping[$databaseType];
        $settings['ezpublish']['system'] = array();
        $settings['ezpublish']['system'][$groupName] = array();
        $databasePassword = $databaseSettings['Password'] != '' ? $databaseSettings['Password'] : null;
        $settings['ezpublish']['system'][$groupName]['database'] = array(
            'type' => $this->mapDatabaseType( $databaseType ),
            'user' => $databaseSettings['User'],
            'password' => $databasePassword,
            'server' => $databaseSettings['Server'],
            'database_name' => $databaseSettings['Database'],
        );
        $settings['ezpublish']['system'][$defaultSiteaccess] = array();
        $settings['ezpublish']['system'][$adminSiteaccess] = array();
        // If package is not supported, all siteaccesses will have individually legacy_mode to true, forcing legacy fallback
        if ( !isset( $this->supportedPackages[$sitePackage] ) )
        {
            foreach ( $siteList as $siteaccess )
            {
                $settings['ezpublish']['system'][$siteaccess] = array( 'legacy_mode' => true );
            }
        }
        else
        {
            $settings['ezpublish']['system'][$adminSiteaccess] += array( 'legacy_mode' => true );
        }
        $languages = $this->getLanguages( $siteList, $groupName );
        foreach ( $languages as $siteaccess => $langSettings )
        {
            $settings['ezpublish']['system'][$siteaccess]['languages'] = $langSettings;
        }
        // FileSettings
        $settings['ezpublish']['system'][$groupName]['var_dir'] =
            $this->getParameter( 'FileSettings', 'VarDir', 'site.ini', $defaultSiteaccess );
        // we don't map the default FileSettings.StorageDir value
        $storageDir = $this->getParameter( 'FileSettings', 'StorageDir', 'site.ini', $defaultSiteaccess );
        if ( $storageDir !== 'storage' )
            $settings['ezpublish']['system'][$groupName]['storage_dir'] = $storageDir;
        // ImageMagick settings
        $imageMagickEnabled = $this->getParameter( 'ImageMagick', 'IsEnabled', 'image.ini', $defaultSiteaccess );
        if ( $imageMagickEnabled == 'true' )
        {
            $settings['ezpublish']['imagemagick']['enabled'] = true;
            $imageMagickExecutablePath = $this->getParameter( 'ImageMagick', 'ExecutablePath', 'image.ini', $defaultSiteaccess );
            $imageMagickExecutable = $this->getParameter( 'ImageMagick', 'Executable', 'image.ini', $defaultSiteaccess );
            $settings['ezpublish']['imagemagick']['path'] = rtrim( $imageMagickExecutablePath, '/\\' ) . '/' . $imageMagickExecutable;
        }
        else
        {
            $settings['ezpublish']['imagemagick']['enabled'] = false;
        }
        $variations = $this->getImageVariations( $siteList, $groupName );
        foreach ( $variations as $siteaccess => $imgSettings )
        {
            $settings['ezpublish']['system'][$siteaccess]['image_variations'] = $imgSettings;
        }
        // Explicitly set Http cache purge type to "local"
        $settings['ezpublish']['http_cache']['purge_type'] = 'local';
        foreach ( $siteList as $siteaccess )
        {
            if (
                $this->getParameter( "Session", "SessionNameHandler", "site.ini", $siteaccess ) === "custom" &&
                $this->getParameter( "Session", "SessionNamePerSiteAccess", "site.ini", $siteaccess ) !== "enabled"
            )
            {
                $settings['ezpublish']['system'][$siteaccess]['session_name'] = $this->getParameter( "Session", "SessionNamePrefix", "site.ini" );
            }
        }
        return $settings;
    }
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::getGroup ($groupName, $file = null, $siteaccess = null)
Returns the contents of the legacy group $groupName. If $file and $siteaccess are null, the global value is fetched with the legacy resolver.
Parameters
string $groupName
string | null $namespace
string | null $siteaccess
Returns
array
Definition at line 306 of file ConfigurationConverter.php.
    {
        if ( $file === null && $siteaccess === null )
        {
            // in this case we want the "global" value, no need to use the
            // legacy kernel, the legacy resolver is enough
            return $this->legacyResolver->getGroup( $groupName );
        }
        return $this->legacyKernel->runCallback(
            function () use ( $file, $groupName, $siteaccess )
            {
                // @todo: do reset injected settings everytime
                // and make sure to restore the previous injected settings
                eZINI::injectSettings( array() );
                return eZSiteAccess::getIni( $siteaccess, $file )->group( $groupName );
            }
        );
    }
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::getImageVariations (array $siteList, $groupName) protected
Returns the image variations settings for all siteaccess unless it's the same for each one, in this case, it returns the variations settings for the group. This avoids to duplicate the image variations settings
Parameters
array $siteList
string $groupName
Returns
array
Definition at line 209 of file ConfigurationConverter.php.
References eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\getImageVariationsForSiteaccess().
    {
        $result = array();
        $allSame = true;
        $previousSA = null;
        foreach ( $siteList as $siteaccess )
        {
            $result[$siteaccess] = $this->getImageVariationsForSiteaccess( $siteaccess );
            if ( $allSame && $previousSA !== null )
            {
                $allSame = ( $result[$previousSA] === $result[$siteaccess] );
            }
            $previousSA = $siteaccess;
        }
        if ( $allSame )
        {
            return array( $groupName => $result[$previousSA] );
        }
        return $result;
    }
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::getImageVariationsForSiteaccess ($siteaccess) protected
Returns the image variation settings for the siteaccess
Parameters
string $siteaccess
Returns
array
Definition at line 237 of file ConfigurationConverter.php.
References eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\getGroup().
    {
        $variations = array();
        $imageAliasesList = $this->getGroup( 'AliasSettings', 'image.ini', $siteaccess );
        foreach ( $imageAliasesList['AliasList'] as $imageAliasIdentifier )
        {
            $variationSettings = array( 'reference' => null, 'filters' => array() );
            $aliasSettings = $this->getGroup( $imageAliasIdentifier, 'image.ini', $siteaccess );
            if ( isset( $aliasSettings['Reference'] ) && $aliasSettings['Reference'] != '' )
            {
                $variationSettings['reference'] = $aliasSettings['Reference'];
            }
            if ( isset( $aliasSettings['Filters'] ) && is_array( $aliasSettings['Filters'] ) )
            {
                // parse filters. Format: filtername=param1;param2...paramN
                foreach ( $aliasSettings['Filters'] as $filterString )
                {
                    $filteringSettings = array();
                    if ( strstr( $filterString, '=' ) !== false )
                    {
                        list( $filteringSettings['name'], $filterParams) = explode( '=', $filterString );
                        $filterParams = explode( ';', $filterParams );
                        // make sure integers are actually integers, not strings
                        array_walk(
                            $filterParams,
                            function( &$value )
{
                                if ( preg_match( '/^[0-9]+$/', $value ) )
                                    $value = (int)$value;
                            }
                        );
                        $filteringSettings['params'] = $filterParams;
                    }
                    else
                    {
                        $filteringSettings['name'] = $filterString;
                    }
                    $variationSettings['filters'][] = $filteringSettings;
                }
            }
            $variations[$imageAliasIdentifier] = $variationSettings;
        }
        return $variations;
    }
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::getLanguages (array $siteList, $groupName) protected
Returns the languages list for all siteaccess unless it's the same for each one, in this case, it returns the languages list for the group.
Parameters
array $siteList
string $groupName
Returns
array
Definition at line 176 of file ConfigurationConverter.php.
References eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\getParameter().
    {
        $result = array();
        $allSame = true;
        $previousSA = null;
        foreach ( $siteList as $siteaccess )
        {
            $result[$siteaccess] = $this->getParameter(
                'RegionalSettings', 'SiteLanguageList', 'site.ini', $siteaccess
            );
            if ( $allSame && $previousSA !== null )
            {
                $allSame = ( $result[$previousSA] === $result[$siteaccess] );
            }
            $previousSA = $siteaccess;
        }
        if ( $allSame )
        {
            return array( $groupName => $result[$previousSA] );
        }
        return $result;
    }
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::getParameter ($groupName, $parameterName, $file = null, $siteaccess = null)
Returns the value of the legacy parameter $parameterName in $groupName. If $file and $siteaccess are null, the global value is fetched with the legacy resolver.
Parameters
string $groupName
string $parameterName
string | null $file
string | null $siteaccess
Returns
array
Definition at line 337 of file ConfigurationConverter.php.
    {
        if ( $file === null && $siteaccess === null )
        {
            // in this case we want the "global" value, no need to use the
            // legacy kernel, the legacy resolver is enough
            return $this->legacyResolver->getParameter( "$groupName.$parameterName" );
        }
        return $this->legacyKernel->runCallback(
            function () use ( $file, $groupName, $parameterName, $siteaccess )
            {
                // @todo: do reset injected settings everytime
                // and make sure to restore the previous injected settings
                eZINI::injectSettings( array() );
                return eZSiteAccess::getIni( $siteaccess, $file )
                    ->variable( $groupName, $parameterName );
            }
        );
    }
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::mapDatabaseType ($databaseType) protected
Definition at line 286 of file ConfigurationConverter.php.
    {
        $map = array(
            'ezpostgresql' => 'pgsql',
            'postgresql' => 'pgsql'
        );
        return isset( $map[$databaseType] ) ? $map[$databaseType] : $databaseType;
    }
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::resolveHostMatching ($siteaccessSettings) protected
Parses Legacy HostMatching settings to a matching array
Parameters
mixed[] $siteaccessSettings
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException
Returns
array|bool
Definition at line 417 of file ConfigurationConverter.php.
References eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\resolveMapMatch(), and eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\resolveTextMatch().
    {
        switch ( $siteaccessSettings['HostMatchType'] )
        {
            case 'disabled':
                return false;
            case 'map':
                return array( "Map\\Host" => $this->resolveMapMatch( $siteaccessSettings['HostMatchMapItems'] ) );
            case 'element':
                return array( "HostElement" => $siteaccessSettings['HostMatchElement'] );
            case 'text':
                return array( "HostText" => $this->resolveTextMatch( $siteaccessSettings, 'HostMatchSubtextPre', 'HostMatchSubtextPost' ) );
            case 'regexp':
                return array( "Regex\\Host" => array( $siteaccessSettings['HostMatchRegexp'], $siteaccessSettings['HostMatchRegexpItem'] ) );
            default:
                throw new InvalidArgumentException( "HostMatchType", "Invalid value for legacy setting site.ini '{$siteaccessSettings['HostMatchType']}'" );
        }
    }
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::resolveMapMatch ($mapArray) protected
Definition at line 452 of file ConfigurationConverter.php.
    {
        $map = array();
        foreach ( $mapArray as $mapItem )
        {
            $elements = explode( ';', $mapItem );
            $map[$elements[0]] = count( $elements ) > 2 ? array_slice( $elements, 1 ) : $elements[1];
        }
        return $map;
    }
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::resolveMatching () protected
Definition at line 357 of file ConfigurationConverter.php.
References eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\getGroup(), and eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\resolveHostMatching().
    {
        $siteaccessSettings = $this->getGroup( 'SiteAccessSettings' );
        $matching = array(); $match = false;
        foreach ( explode( ';', $siteaccessSettings['MatchOrder'] ) as $matchMethod )
        {
            switch ( $matchMethod )
            {
                case 'uri':
                    $match = $this->resolveURIMatching( $siteaccessSettings );
                    break;
                case 'host':
                    $match = $this->resolveHostMatching( $siteaccessSettings );
                    break;
                case 'host_uri':
                    // @todo Not implemented yet
                    $match = false;
                    break;
                case 'port':
                    $match = array( 'Map\Port' => $this->getGroup( 'PortAccessSettings' ) );
                    break;
            }
            if ( $match !== false )
            {
                $matching = $match + $matching;
            }
        }
        return $matching;
    }
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::resolveTextMatch ($siteaccessSettings, $prefixKey, $suffixKey) protected
Definition at line 441 of file ConfigurationConverter.php.
    {
        $settings = array();
        if ( isset( $siteaccessSettings[$prefixKey] ) )
            $settings['prefix'] = $siteaccessSettings[$prefixKey];
        if ( isset( $siteaccessSettings[$suffixKey] ) )
            $settings['suffix'] = $siteaccessSettings[$suffixKey];
        return $settings;
    }
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::resolveUriMatching ($siteaccessSettings) protected
Definition at line 388 of file ConfigurationConverter.php.
References eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\resolveMapMatch(), and eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter\resolveTextMatch().
    {
        switch ( $siteaccessSettings['URIMatchType'] )
        {
            case 'disabled':
                return false;
            case 'map':
                return array( "Map\\Uri" => $this->resolveMapMatch( $siteaccessSettings['URIMatchMapItems'] ) );
            case 'element':
                return array( "URIElement" => $siteaccessSettings['URIMatchElement'] );
            case 'text':
                return array( "URIText" => $this->resolveTextMatch( $siteaccessSettings, 'URIMatchSubtextPre', 'URIMatchSubtextPost' ) );
            case 'regexp':
                return array( "Regex\\URI" => array( $siteaccessSettings['URIMatchRegexp'], $siteaccessSettings['URIMatchRegexpItem'] ) );
        }
    }
Member Data Documentation
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::$legacyKernel protected
Definition at line 31 of file ConfigurationConverter.php.
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::$legacyResolver protected
Definition at line 26 of file ConfigurationConverter.php.
eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter::$supportedPackages protected
Definition at line 36 of file ConfigurationConverter.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Bundle/EzPublishLegacyBundle/SetupWizard/ConfigurationConverter.php