ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler Class Reference
Public Member Functions
__construct (Gateway $sectionGateway)
create ($name, $identifier)
update ($id, $name, $identifier)
load ($id)
loadAll ()
loadByIdentifier ($identifier)
delete ($id)
assign ($sectionId, $contentId)
assignmentsCount ($sectionId)
Protected Member Functions
createSectionFromArray (array $data)
createSectionsFromArray (array $data)
Protected Attributes
$sectionGateway
Detailed Description
Section Handler
Definition at line 20 of file Handler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::__construct (Gateway $sectionGateway)
Creates a new Section Handler
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\Section\Gateway $sectionGateway
Definition at line 34 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler\$sectionGateway.
    {
        $this->sectionGateway = $sectionGateway;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::assign ($sectionId, $contentId)
Assigns section to single content object
Parameters
mixed $sectionId
mixed $contentId
Implements eZ\Publish\SPI\Persistence\Content\Section\Handler.
Definition at line 194 of file Handler.php.
    {
        $this->sectionGateway->assignSectionToContent( $sectionId, $contentId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::assignmentsCount ($sectionId)
Number of content assignments a Section has
Parameters
mixed $sectionId
Returns
int
Implements eZ\Publish\SPI\Persistence\Content\Section\Handler.
Definition at line 206 of file Handler.php.
    {
        return $this->sectionGateway->countContentObjectsInSection( $sectionId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::create ($name, $identifier)
Create a new section
Parameters
string $name
string $identifier
Returns
Implements eZ\Publish\SPI\Persistence\Content\Section\Handler.
Definition at line 47 of file Handler.php.
    {
        $section = new Section();
        $section->name = $name;
        $section->identifier = $identifier;
        $section->id = $this->sectionGateway->insertSection( $name, $identifier );
        return $section;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::createSectionFromArray (array $data) protected
Creates a Section from the given $data
Parameters
array $data
Returns
Definition at line 138 of file Handler.php.
    {
        $section = new Section();
        $section->id = (int)$data['id'];
        $section->name = $data['name'];
        $section->identifier = $data['identifier'];
        return $section;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::createSectionsFromArray (array $data) protected
Creates a Section from the given $data
Parameters
array $data
Returns
[]
Definition at line 156 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler\createSectionFromArray().
    {
        $sections = array();
        foreach ( $data as $sectionData )
        {
            $sections[] = $this->createSectionFromArray( $sectionData );
        }
        return $sections;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::delete ($id)
Delete a section
Might throw an exception if the section is still associated with some content objects. Make sure that no content objects are associated with the section any more before calling this method.
Parameters
mixed $id
Implements eZ\Publish\SPI\Persistence\Content\Section\Handler.
Definition at line 175 of file Handler.php.
    {
        $contentCount = $this->sectionGateway->countContentObjectsInSection( $id );
        if ( $contentCount > 0 )
        {
            throw new RuntimeException(
                "Section with ID '{$id}' still has content assigned."
            );
        }
        $this->sectionGateway->deleteSection( $id );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::load ($id)
Get section data
Parameters
mixed $id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If section is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Section\Handler.
Definition at line 89 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler\createSectionFromArray().
    {
        $rows = $this->sectionGateway->loadSectionData( $id );
        if ( empty( $rows ) )
        {
            throw new NotFound( "Section", $id );
        }
        return $this->createSectionFromArray( reset( $rows ) );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::loadAll ()
Get all section data
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Section\Handler.
Definition at line 105 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler\createSectionsFromArray().
    {
        $rows = $this->sectionGateway->loadAllSectionData();
        return $this->createSectionsFromArray( $rows );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::loadByIdentifier ($identifier)
Get section data by identifier
Parameters
string $identifier
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If section is not found
Returns
Implements eZ\Publish\SPI\Persistence\Content\Section\Handler.
Definition at line 120 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler\createSectionFromArray().
    {
        $rows = $this->sectionGateway->loadSectionDataByIdentifier( $identifier );
        if ( empty( $rows ) )
        {
            throw new NotFound( "Section", $identifier );
        }
        return $this->createSectionFromArray( reset( $rows ) );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::update ($id, $name, $identifier)
Update name and identifier of a section
Parameters
mixed $id
string $name
string $identifier
Returns
Implements eZ\Publish\SPI\Persistence\Content\Section\Handler.
Definition at line 68 of file Handler.php.
    {
        $this->sectionGateway->updateSection( $id, $name, $identifier );
        $section = new Section();
        $section->id = $id;
        $section->name = $name;
        $section->identifier = $identifier;
        return $section;
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler::$sectionGateway protected
Definition at line 27 of file Handler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Section/Handler.php