ezp-next: eZ\Publish\Core\Persistence\InMemory\ContentHandler Class Reference
eZ\Publish\Core\Persistence\InMemory\ContentHandler Class Reference
Public Member Functions
__construct (Handler $handler, Backend $backend, FieldTypeRegistry $fieldTypeRegistry=null)
copy ($contentId, $versionNo=null)
load ($id, $version, $translations=null)
loadContentInfo ($contentId)
loadVersionInfo ($contentId, $versionNo)
loadDraftsForUser ($userId)
setStatus ($contentId, $status, $version)
updateMetadata ($contentId, MetadataUpdateStruct $content)
deleteContent ($contentId)
deleteVersion ($contentId, $versionNo)
trash ($contentId)
untrash ($contentId)
listVersions ($contentId)
addRelation (RelationCreateStruct $relation)
removeRelation ($relationId, $type)
loadRelations ($sourceContentId, $sourceContentVersionNo=null, $type=null)
loadReverseRelations ($destinationContentId, $type=null)
publish ($contentId, $versionNo, MetadataUpdateStruct $metaDataUpdateStruct)
Public Member Functions inherited from eZ\Publish\SPI\Persistence\Content\Handler
create (CreateStruct $content)
createDraftFromVersion ($contentId, $srcVersion, $userId)
updateContent ($contentId, $versionNo, UpdateStruct $content)
Protected Member Functions
createField ($field, $contentId, $versionNo=1)
getFieldMap (array $fields, array &$languageCodes=null)
createCompleteFields (CreateStruct $contentCreateStruct, array &$languageCodes, $mainLanguageCode)
getEmptyField (FieldDefinition $fieldDefinition, $languageCode, $versionNo=1)
getLanguageCodes (array $languageIds)
Protected Attributes
$handler
$backend
$fieldTypeRegistry
Detailed Description
See Also
eZ
Definition at line 30 of file ContentHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\InMemory\ContentHandler::__construct (Handler $handler, Backend $backend, FieldTypeRegistry $fieldTypeRegistry = null)
Setups current handler instance with reference to Handler object that created it.
Parameters
\eZ\Publish\Core\Persistence\InMemory\Handler $handler
\eZ\Publish\Core\Persistence\InMemory\Backend $backend The storage engine backend
\eZ\Publish\Core\Persistence\FieldTypeRegistry $fieldTypeRegistry
Definition at line 56 of file ContentHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ContentHandler\$backend, eZ\Publish\Core\Persistence\InMemory\ContentHandler\$fieldTypeRegistry, and eZ\Publish\Core\Persistence\InMemory\ContentHandler\$handler.
    {
        $this->handler = $handler;
        $this->backend = $backend;
        $this->fieldTypeRegistry = $fieldTypeRegistry;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\InMemory\ContentHandler::addRelation (RelationCreateStruct $relation)
Creates a relation between $sourceContentId in $sourceContentVersionNo and $destinationContentId with a specific $type.
Parameters
\eZ\Publish\SPI\Persistence\Content\Relation\CreateStruct $relation
Returns
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 776 of file ContentHandler.php.
    {
        // Ensure source content exists
        $sourceContent = $this->backend->find( 'Content\\ContentInfo', array( "id" => $relation->sourceContentId ) );
        if ( empty( $sourceContent ) )
            throw new NotFoundException( 'Content\\ContentInfo', "contentId: {$relation->sourceContentId}" );
        // Ensure source content exists if version is specified
        if ( $relation->sourceContentVersionNo !== null )
        {
            $version = $this->backend->find( "Content\\VersionInfo", array( "_contentId" => $relation->sourceContentId, "versionNo" => $relation->sourceContentVersionNo ) );
            if ( empty( $version ) )
                throw new NotFoundException( "Content\\VersionInfo", "contentId: {$relation->sourceContentId}, versionNo: {$relation->sourceContentVersionNo}" );
        }
        // Ensure destination content exists
        $destinationContent = $this->backend->find( 'Content\\ContentInfo', array( "id" => $relation->destinationContentId ) );
        if ( empty( $destinationContent ) )
            throw new NotFoundException( 'Content\\ContentInfo', "contentId: {$relation->destinationContentId}" );
        return $this->backend->create( "Content\\Relation", (array)$relation );
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::copy ($contentId, $versionNo = null)
Copy Content with Fields and Versions from $contentId in $version.
Copies all fields from $contentId in $version (or all versions if false) to a new object which is returned. Version numbers are maintained.
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If content or version is not found
Parameters
mixed $contentId
mixed | null $versionNo Copy all versions if left null
Todo:
Language support
Returns
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 285 of file ContentHandler.php.
References eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_DRAFT.
    {
        $originalContentInfo = $this->backend->load( 'Content\\ContentInfo', $contentId );
        if ( !$originalContentInfo )
            throw new NotFoundException( 'Content\\ContentInfo', "contentId: $contentId" );
        $time = time();
        $currentVersionNo = isset( $versionNo ) ? $versionNo : $originalContentInfo->currentVersionNo;
        $contentObj = $this->backend->create( 'Content', array( '_currentVersionNo' => $currentVersionNo ) );
        $contentInfo = $this->backend->create(
            'Content\\ContentInfo',
            array(
                "contentTypeId" => $originalContentInfo->contentTypeId,
                "sectionId" => $originalContentInfo->sectionId,
                "ownerId" => $originalContentInfo->ownerId,
                "isPublished" => false,
                "currentVersionNo" => $currentVersionNo,
                "mainLanguageCode" => $originalContentInfo->mainLanguageCode,
                "modificationDate" => 0,
                "publicationDate" => 0,
                "alwaysAvailable" => $originalContentInfo->alwaysAvailable
            )
        );
        // Copy version(s)
        foreach (
            $this->backend->find(
                "Content\\VersionInfo",
                isset( $versionNo ) ?
                    array( "_contentId" => $originalContentInfo->id, "versionNo" => $versionNo ) :
                    array( "_contentId" => $originalContentInfo->id )
            ) as $versionInfo )
        {
            $this->backend->create(
                "Content\\VersionInfo",
                array(
                    "names" => $versionInfo->names,
                    "versionNo" => $versionInfo->versionNo,
                    "modificationDate" => $time,
                    "creatorId" => $versionInfo->creatorId,
                    "creationDate" => $time,
                    "_contentId" => $contentInfo->id,
                    "initialLanguageCode" => $versionInfo->initialLanguageCode,
                    "languageIds" => $versionInfo->languageIds,
                    "status" => $versionInfo->versionNo === $currentVersionNo ?
                        VersionInfo::STATUS_DRAFT :
                        $versionInfo->status
                )
            );
        }
        // Associate last version to content VO
        $aVersion = $this->backend->find(
            'Content\\VersionInfo',
            array(
                '_contentId' => $contentInfo->id,
                'versionNo' => $currentVersionNo
            )
        );
        if ( empty( $aVersion ) )
            throw new NotFoundException( "Version", "contentId: {$contentInfo->id} // versionNo: $currentVersionNo" );
        $contentObj->versionInfo = $aVersion[0];
        $contentObj->versionInfo->contentInfo = $contentInfo;
        // Copy fields
        // @todo: language support
        foreach (
            $this->backend->find(
                "Content\\Field",
                // Using internal _contentId since it's not directly exposed by Persistence
                isset( $versionNo ) ?
                    array( "_contentId" => $originalContentInfo->id, "versionNo" => $versionNo ) :
                    array( "_contentId" => $originalContentInfo->id )
            ) as $field
        )
        {
            $this->backend->create(
                'Content\\Field',
                array( '_contentId' => $contentInfo->id ) + (array)$field
            );
        }
        // Associate last version's fields
        // @todo: Throw NotFound if no fields at all ?
        $contentObj->fields = $this->backend->find(
            "Content\\Field",
            array(
                "_contentId" => $contentInfo->id,
                "versionNo" => $currentVersionNo
            )
        );
        return $contentObj;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::createCompleteFields (CreateStruct $contentCreateStruct, array & $languageCodes, $mainLanguageCode) protected
Returns complete set of fields.
Parameters
\eZ\Publish\SPI\Persistence\Content\CreateStruct $contentCreateStruct
array $languageCodes
string $mainLanguageCode
Returns
[]
Definition at line 184 of file ContentHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ContentHandler\getEmptyField(), and eZ\Publish\Core\Persistence\InMemory\ContentHandler\getFieldMap().
    {
        $fields = $this->getFieldMap( $contentCreateStruct->fields, $languageCodes );
        $contentType = $this->handler->contentTypeHandler()->load( $contentCreateStruct->typeId );
        foreach ( $contentType->fieldDefinitions as $fieldDefinition )
        {
            foreach ( array_keys( $languageCodes ) as $languageCode )
            {
                if ( isset( $fields[$fieldDefinition->id][$languageCode] ) )
                {
                    continue;
                }
                if ( $fieldDefinition->isTranslatable
                    || !isset( $fields[$fieldDefinition->id][$mainLanguageCode] ) )
                {
                    $field = $this->getEmptyField( $fieldDefinition, $languageCode );
                }
                else
                {
                    $field = clone $fields[$fieldDefinition->id][$mainLanguageCode];
                    $field->id = null;
                    $field->languageCode = $languageCode;
                }
                $fields[$fieldDefinition->id][$languageCode] = $field;
            }
        }
        return $fields;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::createField ($field, $contentId, $versionNo = 1) protected
Definition at line 141 of file ContentHandler.php.
    {
        return $this->backend->create(
            'Content\\Field',
            array(
                'versionNo' => $versionNo,
                // Using internal _contentId since it's not directly exposed by Persistence
                '_contentId' => $contentId,
                'value' => $field->value
            ) + (array)$field
        );
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::deleteContent ($contentId)
See Also
Todo:
add deleting of relations
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 659 of file ContentHandler.php.
    {
        $this->backend->delete( 'Content', $contentId );
        $this->backend->delete( 'Content\\ContentInfo', $contentId );
        $versions = $this->backend->find( 'Content\\VersionInfo', array( '_contentId' => $contentId ) );
        foreach ( $versions as $version )
        {
            $fields = $this->backend->find(
                'Content\\Field',
                array(
                    '_contentId' => $contentId,
                    'versionNo' => $version->versionNo
                )
            );
            foreach ( $fields as $field )
                $this->backend->delete( 'Content\\Field', $field->id );
            $this->backend->delete( 'Content\\VersionInfo', $version->id );
        }
        // @todo Deleting Locations by content object id should be possible using handler API?
        $locationHandler = $this->handler->locationHandler();
        $locations = $this->backend->find( 'Content\\Location', array( 'contentId' => $contentId ) );
        foreach ( $locations as $location )
        {
            $locationHandler->removeSubtree( $location->id );
        }
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::deleteVersion ($contentId, $versionNo)
Deletes given version, its fields, node assignment, relations and names.
Removes the relations, but not the related objects.
Parameters
int $contentId
int $versionNo
Returns
boolean
Todo:
add deleting of relations
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 701 of file ContentHandler.php.
    {
        $versions = $this->backend->find(
            'Content\\VersionInfo',
            array(
                "_contentId" => $contentId,
                "versionNo" => $versionNo
            )
        );
        foreach ( $versions as $version )
        {
            $fields = $this->backend->find(
                'Content\\Field',
                array(
                    '_contentId' => $contentId,
                    'versionNo' => $version->versionNo
                )
            );
            foreach ( $fields as $field )
                $this->backend->delete( 'Content\\Field', $field->id );
            $this->backend->delete( 'Content\\VersionInfo', $version->id );
        }
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::getEmptyField (FieldDefinition $fieldDefinition, $languageCode, $versionNo = 1) protected
Returns empty Field object for given field definition and language code.
Uses FieldType to create empty field value.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDefinition
string $languageCode
int $versionNo
Returns
Definition at line 623 of file ContentHandler.php.
    {
        $fieldType = $this->fieldTypeRegistry->getFieldType( $fieldDefinition->fieldType );
        return new Field(
            array(
                "fieldDefinitionId" => $fieldDefinition->id,
                "type" => $fieldDefinition->fieldType,
                "value" => $fieldType->getEmptyValue(),
                "languageCode" => $languageCode,
                "versionNo" => $versionNo
            )
        );
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::getFieldMap (array $fields, array & $languageCodes = null) protected
Parameters
\eZ\Publish\SPI\Persistence\Content\Field[] $fields
array $languageCodes
Returns
array
Definition at line 160 of file ContentHandler.php.
    {
        $mappedFields = array();
        foreach ( $fields as $field )
        {
            if ( isset( $languageCodes ) )
            {
                $languageCodes[$field->languageCode] = true;
            }
            $mappedFields[$field->fieldDefinitionId][$field->languageCode] = $field;
        }
        return $mappedFields;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::getLanguageCodes (array $languageIds) protected
For given $languageIds returns array with language codes as keys.
Parameters
array $languageIds
Returns
array
Definition at line 644 of file ContentHandler.php.
    {
        $languageCodes = array();
        foreach ( $languageIds as $languageId )
        {
            $languageCodes[$this->handler->contentLanguageHandler()->load( $languageId )->languageCode] = true;
        }
        return $languageCodes;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::listVersions ($contentId)
See Also
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If no version found
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 746 of file ContentHandler.php.
    {
        $versions = $this->backend->find(
            'Content\\VersionInfo',
            array(
                '_contentId' => $contentId
            ),
            array(
                'contentInfo' => array(
                    'type' => 'Content\\ContentInfo',
                    'match' => array( 'id' => '_contentId' ),
                    'single' => true
                )
            )
        );
        if ( empty( $versions ) )
            throw new NotFoundException( "Content\\VersionInfo", "contentId: $contentId" );
        return $versions;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::load ($id, $version, $translations = null)
See Also
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 385 of file ContentHandler.php.
    {
        $res = $this->backend->find(
            'Content',
            array( 'id' => $id )
        );
        if ( empty( $res ) )
            throw new NotFoundException( "Content", "contentId:{$id}" );
        $content = $res[0];
        $versions = $this->backend->find(
            'Content\\VersionInfo',
            array(
                '_contentId' => $id,
                'versionNo' => $version
            ),
            array(
                'contentInfo' => array(
                    'type' => 'Content\\ContentInfo',
                    'match' => array( 'id' => '_contentId' ),
                    'single' => true
                )
            )
        );
        if ( !isset( $versions[0] ) )
            throw new NotFoundException( "Version", "contentId:{$id}, versionNo:{$version}" );
        if ( !$versions[0]->contentInfo instanceof ContentInfo )
            throw new NotFoundException( "Content\\ContentInfo", "contentId:{$id}" );
        $fieldMatch = array(
            "_contentId" => $id,
            "versionNo" => $version
        );
        if ( isset( $translations ) )
            $fieldMatch["languageCode"] = $translations;
        $content->fields = $this->backend->find( 'Content\\Field', $fieldMatch );
        $content->versionInfo = $versions[0];
        return $content;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::loadContentInfo ($contentId)
Returns the metadata object for a content identified by $contentId.
Parameters
int | string $contentId
Returns
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 434 of file ContentHandler.php.
    {
        $contentInfo = $this->backend->load( 'Content\\ContentInfo', $contentId );
        return $contentInfo;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::loadDraftsForUser ($userId)
See Also
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 477 of file ContentHandler.php.
References eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_DRAFT.
    {
        $versionInfoList = $this->backend->find(
            'Content\\VersionInfo',
            array(
                "status" => VersionInfo::STATUS_DRAFT,
                "creatorId" => $userId
            ),
            array(
                'contentInfo' => array(
                    'type' => 'Content\\ContentInfo',
                    'match' => array( 'id' => '_contentId' ),
                    'single' => true
                )
            )
        );
        return $versionInfoList;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::loadRelations ($sourceContentId, $sourceContentVersionNo = null, $type = null)
Loads relations from $sourceContentId. Optionally, loads only those with $type and $sourceContentVersionNo.
Parameters
mixed $sourceContentId Source Content ID
mixed | null $sourceContentVersionNo Source Content Version, null if not specified
int | null $type {
See Also
::COMMON, ::EMBED, ::LINK, ::FIELD}
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 835 of file ContentHandler.php.
    {
        $filter = array( "sourceContentId" => $sourceContentId );
        if ( $sourceContentVersionNo !== null )
            $filter["sourceContentVersionNo"] = $sourceContentVersionNo;
        $relations = $this->backend->find( "Content\\Relation", $filter );
        if ( $type === null )
            return $relations;
        foreach ( $relations as $key => $relation )
        {
            // Is there a bit present in $type not appearing in $relation->type?
            if ( ~$relation->type & $type )
            {
                // In such case, remove the result from the array
                unset( $relations[$key] );
            }
        }
        return $relations;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::loadReverseRelations ($destinationContentId, $type = null)
Loads relations from $contentId. Optionally, loads only those with $type.
Only loads relations against published versions.
Parameters
mixed $destinationContentId Destination Content ID
int | null $type {
See Also
::COMMON, ::EMBED, ::LINK, ::FIELD}
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 871 of file ContentHandler.php.
    {
        $filter = array( "destinationContentId" => $destinationContentId );
        $relations = $this->backend->find( "Content\\Relation", $filter );
        if ( $type === null )
            return $relations;
        foreach ( $relations as $key => $relation )
        {
            if ( ~$relation->type & $type )
            {
                unset( $relations[$key] );
            }
        }
        return $relations;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::loadVersionInfo ($contentId, $versionNo)
Returns the version object for a content/version identified by $contentId and $versionNo
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If version is not found
Parameters
int | string $contentId
int $versionNo Version number to load
Returns
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 450 of file ContentHandler.php.
    {
        $versionInfoList = $this->backend->find(
            'Content\\VersionInfo',
            array(
                '_contentId' => $contentId,
                'versionNo' => $versionNo
            ),
            array(
                'contentInfo' => array(
                    'type' => 'Content\\ContentInfo',
                    'match' => array( 'id' => '_contentId' ),
                    'single' => true
                )
            )
        );
        if ( empty( $versionInfoList ) )
            throw new NotFoundException( "Content\\VersionInfo", "contentId: $contentId, versionNo: $versionNo" );
        $versionInfo = reset( $versionInfoList );
        return $versionInfo;
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::publish ($contentId, $versionNo, MetadataUpdateStruct $metaDataUpdateStruct)
Performs the publishing operations required to set the version identified by $updateStruct->versionNo and $updateStruct->id as the published one.
Parameters
int $contentId
int $versionNo
\eZ\Publish\SPI\Persistence\Content\MetadataUpdateStruct $metaDataUpdateStruct
Returns
The published Content
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 899 of file ContentHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ContentHandler\load(), and eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_PUBLISHED.
    {
        // Change Content currentVersionNo to the published version
        $this->backend->update(
            'Content',
            $contentId,
            array(
                '_currentVersionNo' => $versionNo,
            )
        );
        // Update ContentInfo published flag and change the currentVersionNo to the published version
        $contentInfoUpdateData = array(
            "currentVersionNo" => $versionNo,
            "isPublished" => true,
        );
        // Update ContentInfo with set properties in $metaDataUpdateStruct
        foreach ( $metaDataUpdateStruct as $propertyName => $propertyValue )
        {
            if ( isset( $propertyValue ) )
            {
                if ( $propertyName === "alwaysAvailable" )
                {
                    $contentInfoUpdateData["alwaysAvailable"] = $propertyValue;
                }
                else if ( $propertyName === "mainLanguageId" )
                {
                    $contentInfoUpdateData["mainLanguageCode"] =
                        $this->handler->contentLanguageHandler()->load( $propertyValue )->languageCode;
                }
                else $contentInfoUpdateData[$propertyName] = $propertyValue;
            }
        }
        $this->backend->update(
            'Content\\ContentInfo',
            $contentId,
            $contentInfoUpdateData,
            true
        );
        // Update VersionInfo with modified timestamp and published status
        $this->backend->updateByMatch(
            'Content\\VersionInfo',
            array( '_contentId' => $contentId, 'versionNo' => $versionNo ),
            array(
                "modificationDate" => $metaDataUpdateStruct->modificationDate,
                "status" => VersionInfo::STATUS_PUBLISHED,
            )
        );
        return $this->load( $contentId, $versionNo );
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::removeRelation ($relationId, $type)
Removes a relation by relation Id.
Parameters
mixed $relationId
int $type {
See Also
::COMMON, ::EMBED, ::LINK, ::FIELD}
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if relation to be removed is not found.
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 813 of file ContentHandler.php.
    {
        $requestedRelation = $this->backend->find( "Content\\Relation", array( "id" => $relationId ) );
        if ( empty( $requestedRelation ) )
        {
            throw new NotFoundException( "Content\\Relation", "id: " . $relationId );
        }
        $this->backend->delete( "Content\\Relation", $relationId );
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::setStatus ($contentId, $status, $version)
See Also
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 500 of file ContentHandler.php.
    {
        $versions = $this->backend->find( 'Content\\VersionInfo', array( '_contentId' => $contentId, 'versionNo' => $version ) );
        if ( !count( $versions ) )
        {
            throw new NotFoundException( "Version", "contentId: $contentId, versionNo: $version" );
        }
        return $this->backend->update( 'Content\\VersionInfo', $versions[0]->id, array( 'status' => $status ) );
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::trash ($contentId)
See Also
Definition at line 729 of file ContentHandler.php.
    {
        throw new RuntimeException( '@todo: Implement' );
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::untrash ($contentId)
See Also
Definition at line 737 of file ContentHandler.php.
    {
        throw new RuntimeException( '@todo: Implement' );
    }
eZ\Publish\Core\Persistence\InMemory\ContentHandler::updateMetadata ($contentId, MetadataUpdateStruct $content)
See Also
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 514 of file ContentHandler.php.
References eZ\Publish\Core\Persistence\InMemory\ContentHandler\loadContentInfo().
    {
        $updateData = (array)$content;
        $updateData["alwaysAvailable"] = $updateData["alwaysAvailable"];
        $updateData["mainLanguageCode"] = $this->handler->contentLanguageHandler()
            ->load( $content->mainLanguageId )->languageCode;
        $this->backend->update(
            "Content\\ContentInfo",
            $contentId,
            $updateData,
            true
        );
        return $this->loadContentInfo( $contentId );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\InMemory\ContentHandler::$backend protected
Definition at line 40 of file ContentHandler.php.
eZ\Publish\Core\Persistence\InMemory\ContentHandler::$fieldTypeRegistry protected
Definition at line 47 of file ContentHandler.php.
eZ\Publish\Core\Persistence\InMemory\ContentHandler::$handler protected
Definition at line 35 of file ContentHandler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/InMemory/ContentHandler.php