ezp-next: eZ\Publish\Core\REST\Client\Repository Class Reference
eZ\Publish\Core\REST\Client\Repository Class Reference
Public Member Functions
__construct (HttpClient $client, Common\Input\Dispatcher $inputDispatcher, Common\Output\Visitor $outputVisitor, Common\UrlHandler $urlHandler, array $fieldTypes)
getCurrentUser ()
setCurrentUser (User $user)
hasAccess ($module, $function, User $user=null)
canUser ($module, $function, ValueObject $object, ValueObject $target=null)
getContentService ()
getContentLanguageService ()
getContentTypeService ()
getLocationService ()
getTrashService ()
getSectionService ()
getSearchService ()
getUserService ()
getIOService ()
getRoleService ()
getUrlAliasService ()
getURLWildcardService ()
getObjectStateService ()
getFieldTypeService ()
beginTransaction ()
commit ()
rollback ()
Public Member Functions inherited from eZ\Publish\API\Repository\Repository
getURLAliasService ()
Detailed Description
REST Client Repository
See Also
Definition at line 23 of file Repository.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Client\Repository::__construct (HttpClient $client, Common\Input\Dispatcher $inputDispatcher, Common\Output\Visitor $outputVisitor, Common\UrlHandler $urlHandler, array $fieldTypes)
Instantiates the REST Client repository.
Parameters
\eZ\Publish\Core\REST\Client\HttpClient $client
\eZ\Publish\Core\REST\Common\Input\Dispatcher $inputDispatcher
\eZ\Publish\Core\REST\Common\Output\Visitor $outputVisitor
\eZ\Publish\Core\REST\Common\UrlHandler $urlHandler
\eZ\Publish\SPI\FieldType\FieldType[] $fieldTypes
Definition at line 133 of file Repository.php.
    {
        $this->client          = $client;
        $this->inputDispatcher = $inputDispatcher;
        $this->outputVisitor   = $outputVisitor;
        $this->urlHandler      = $urlHandler;
        $this->fieldTypes      = $fieldTypes;
    }
Member Function Documentation
eZ\Publish\Core\REST\Client\Repository::beginTransaction ()
Begin transaction
Begins an transaction, make sure you'll call commit or rollback when done, otherwise work will be lost.
Implements eZ\Publish\API\Repository\Repository.
Definition at line 471 of file Repository.php.
    {
        ++$this->transactionDepth;
    }
eZ\Publish\Core\REST\Client\Repository::canUser ($module, $function, ValueObject $object, ValueObject $target = null)
Indicates if the current user is allowed to perform an action given by the function on the given objects
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If any of the arguments are invalid
\eZ\Publish\API\Repository\Exceptions\BadStateException If value of the LimitationValue is unsupported
Parameters
string $module The module, aka controller identifier to check permissions on
string $function The function, aka the controller action to check permissions on
\eZ\Publish\API\Repository\Values\ValueObject $object The object to check if the user has access to
\eZ\Publish\API\Repository\Values\ValueObject $target The location, parent or "assignment" value object
Returns
boolean
Implements eZ\Publish\API\Repository\Repository.
Definition at line 192 of file Repository.php.
    {
        // @todo: Implement
    }
eZ\Publish\Core\REST\Client\Repository::commit ()
Commit transaction
Commit transaction, or throw exceptions if no transactions has been started.
Exceptions
\RuntimeException If no transaction has been started
Implements eZ\Publish\API\Repository\Repository.
Definition at line 483 of file Repository.php.
    {
        // @todo: Implement / discuss
    }
eZ\Publish\Core\REST\Client\Repository::getContentLanguageService ()
Get Content Language Service
Get service object to perform operations on Content language objects
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 226 of file Repository.php.
References eZ\Publish\Core\REST\Client\Repository\getContentService().
    {
        if ( null === $this->languageService )
        {
            $this->languageService = new LanguageService(
                $this->getContentService(),
                'eng-US',
                $this->client,
                $this->inputDispatcher,
                $this->outputVisitor,
                $this->urlHandler
            );
        }
        return $this->languageService;
    }
eZ\Publish\Core\REST\Client\Repository::getContentService ()
Get Content Service
Get service object to perform operations on Content objects and it's aggregate members.
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 204 of file Repository.php.
References eZ\Publish\Core\REST\Client\Repository\getContentTypeService().
    {
        if ( null === $this->contentService )
        {
            $this->contentService = new ContentService(
                $this->client,
                $this->inputDispatcher,
                $this->outputVisitor,
                $this->urlHandler,
                $this->getContentTypeService()
            );
        }
        return $this->contentService;
    }
eZ\Publish\Core\REST\Client\Repository::getContentTypeService ()
Get Content Type Service
Get service object to perform operations on Content Type objects and it's aggregate members. (Group, Field & FieldCategory)
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 250 of file Repository.php.
    {
        if ( null === $this->contentTypeService )
        {
            $this->contentTypeService = new ContentTypeService(
                $this->client,
                $this->inputDispatcher,
                $this->outputVisitor,
                $this->urlHandler
            );
        }
        return $this->contentTypeService;
    }
eZ\Publish\Core\REST\Client\Repository::getCurrentUser ()
Get current user
Returns
Implements eZ\Publish\API\Repository\Repository.
Reimplemented in eZ\Publish\Core\REST\Client\IntegrationTestRepository.
Definition at line 147 of file Repository.php.
    {
        return null;
    }
eZ\Publish\Core\REST\Client\Repository::getFieldTypeService ()
Get FieldTypeService
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 456 of file Repository.php.
    {
        if ( null === $this->fieldTypeService )
        {
            $this->fieldTypeService = new FieldTypeService( $this->fieldTypes );
        }
        return $this->fieldTypeService;
    }
eZ\Publish\Core\REST\Client\Repository::getIOService ()
Get IO Service
Get service object to perform operations on binary files
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 369 of file Repository.php.
    {
        if ( null === $this->ioService )
        {
            $this->ioService = new IOService(
                $this->client,
                $this->inputDispatcher,
                $this->outputVisitor,
                $this->urlHandler
            );
        }
        return $this->ioService;
    }
eZ\Publish\Core\REST\Client\Repository::getLocationService ()
Get Content Location Service
Get service object to perform operations on Location objects and subtrees
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 271 of file Repository.php.
    {
        if ( null === $this->locationService )
        {
            $this->locationService = new LocationService(
                $this->client,
                $this->inputDispatcher,
                $this->outputVisitor,
                $this->urlHandler
            );
        }
        return $this->locationService;
    }
eZ\Publish\Core\REST\Client\Repository::getObjectStateService ()
Get ObjectStateService
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 437 of file Repository.php.
    {
        if ( null === $this->objectStateService )
        {
            $this->objectStateService = new ObjectStateService(
                $this->client,
                $this->inputDispatcher,
                $this->outputVisitor,
                $this->urlHandler
            );
        }
        return $this->objectStateService;
    }
eZ\Publish\Core\REST\Client\Repository::getRoleService ()
Get RoleService
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 388 of file Repository.php.
References eZ\Publish\Core\REST\Client\Repository\getUserService().
    {
        if ( null === $this->roleService )
        {
            $this->roleService = new RoleService(
                $this->getUserService(),
                $this->client,
                $this->inputDispatcher,
                $this->outputVisitor,
                $this->urlHandler
            );
        }
        return $this->roleService;
    }
eZ\Publish\Core\REST\Client\Repository::getSearchService ()
Get Search Service
Get search service that lets you find content objects
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 336 of file Repository.php.
    {
        throw new \RuntimeException( '@todo: Implememt.' );
    }
eZ\Publish\Core\REST\Client\Repository::getSectionService ()
Get Content Section Service
Get Section service that lets you manipulate section objects
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 315 of file Repository.php.
    {
        if ( null === $this->sectionService )
        {
            $this->sectionService = new SectionService(
                $this->client,
                $this->inputDispatcher,
                $this->outputVisitor,
                $this->urlHandler
            );
        }
        return $this->sectionService;
    }
eZ\Publish\Core\REST\Client\Repository::getTrashService ()
Get Content Trash service
Trash service allows to perform operations related to location trash (trash/untrash, load/list from trash...)
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 293 of file Repository.php.
References eZ\Publish\Core\REST\Client\Repository\getLocationService().
    {
        if ( null === $this->trashService )
        {
            $this->trashService = new TrashService(
                $this->getLocationService(),
                $this->client,
                $this->inputDispatcher,
                $this->outputVisitor,
                $this->urlHandler
            );
        }
        return $this->trashService;
    }
eZ\Publish\Core\REST\Client\Repository::getUrlAliasService ()
Get URLAliasService
Returns
Definition at line 408 of file Repository.php.
    {
        if ( null === $this->urlAliasService )
        {
            $this->urlAliasService = new URLAliasService(
                $this->client,
                $this->inputDispatcher,
                $this->outputVisitor,
                $this->urlHandler
            );
        }
        return $this->urlAliasService;
    }
eZ\Publish\Core\REST\Client\Repository::getURLWildcardService ()
Get URLWildcardService
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 427 of file Repository.php.
    {
        throw new \RuntimeException( '@todo: Implement' );
    }
eZ\Publish\Core\REST\Client\Repository::getUserService ()
Get User Service
Get service object to perform operations on Users and UserGroup
Returns
Implements eZ\Publish\API\Repository\Repository.
Definition at line 348 of file Repository.php.
    {
        if ( null === $this->userService )
        {
            $this->userService = new UserService(
                $this->client,
                $this->inputDispatcher,
                $this->outputVisitor,
                $this->urlHandler
            );
        }
        return $this->userService;
    }
eZ\Publish\Core\REST\Client\Repository::hasAccess ($module, $function, User $user = null)
Parameters
string $module
string $function
\eZ\Publish\API\Repository\Values\User\User $user
Returns
boolean|[] if limitations are on this function an array of limitations is returned
Implements eZ\Publish\API\Repository\Repository.
Definition at line 173 of file Repository.php.
    {
        // @todo: Implement
    }
eZ\Publish\Core\REST\Client\Repository::rollback ()
Rollback transaction
Rollback transaction, or throw exceptions if no transactions has been started.
Exceptions
\RuntimeException If no transaction has been started
Implements eZ\Publish\API\Repository\Repository.
Definition at line 495 of file Repository.php.
    {
        // @todo: Implement / discuss
    }
eZ\Publish\Core\REST\Client\Repository::setCurrentUser (User $user)
Sets the current user to the given $user.
Parameters
\eZ\Publish\API\Repository\Values\User\User $user
Returns
void
Implements eZ\Publish\API\Repository\Repository.
Reimplemented in eZ\Publish\Core\REST\Client\IntegrationTestRepository.
Definition at line 159 of file Repository.php.
    {
        throw new Exceptions\MethodNotAllowedException(
            'It is not allowed to set a current user in this implementation. Please use a corresponding authenticating HttpClient instead.'
        );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Client/Repository.php