ezp-next: eZ\Publish\Core\MVC\Symfony\Controller\Content\ViewController Class Reference
eZ\Publish\Core\MVC\Symfony\Controller\Content\ViewController Class Reference
Public Member Functions
__construct (ViewManager $viewManager)
viewLocation ($locationId, $viewType, $layout=false)
viewContent ($contentId, $viewType, $layout=false)
Public Member Functions inherited from eZ\Publish\Core\MVC\Symfony\Controller\Controller
getParameter ($parameterName, $defaultValue=null)
hasParameter ($parameterName)
getConfigResolver ()
render ($view, array $parameters=array(), Response $response=null)
getTemplateEngine ()
getLogger ()
getRepository ()
getRequest ()
getEventDispatcher ()
isGranted (AuthorizationAttribute $attribute)
Protected Member Functions
buildResponse ($etag, DateTime $lastModified)
Detailed Description
Definition at line 21 of file ViewController.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\Controller\Content\ViewController::__construct (ViewManager $viewManager)
Definition at line 28 of file ViewController.php.
    {
        $this->viewManager = $viewManager;
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\Controller\Content\ViewController::buildResponse ($etag, DateTime $lastModified) protected
Build the response so that depending on settings it's cacheable
Parameters
string $etag
\DateTime $lastModified
Returns
Definition at line 41 of file ViewController.php.
References eZ\Publish\Core\MVC\Symfony\Controller\Controller\getParameter(), and eZ\Publish\Core\MVC\Symfony\Controller\Controller\getRequest().
    {
        $request = $this->getRequest();
        $response = new Response();
        if ( $this->getParameter( 'content.view_cache' ) === true )
        {
            $response->setPublic();
            $response->setEtag( $etag );
            // If-None-Match is the request counterpart of Etag response header
            // Making the response to vary against it ensures that an HTTP
            // reverse proxy caches the different possible variations of the
            // response as it can depend on user role for instance.
            if ( $request->headers->has( 'If-None-Match' )
                && $this->getParameter( 'content.ttl_cache' ) === true )
            {
                $response->setVary( 'If-None-Match' );
                $response->setSharedMaxAge(
                    $this->getParameter( 'content.default_ttl' )
                );
            }
            $response->setLastModified( $lastModified );
        }
        return $response;
    }
eZ\Publish\Core\MVC\Symfony\Controller\Content\ViewController::viewContent ($contentId, $viewType, $layout = false)
Main action for viewing content. Response will be cached with HttpCache validation model (Etag)
Parameters
int $contentId
string $viewType
boolean $layout
Exceptions
\Symfony\Component\Security\Core\Exception\AccessDeniedException
\Exception
Returns
Definition at line 154 of file ViewController.php.
References eZ\Publish\Core\MVC\Symfony\MVCEvents\API_CONTENT_EXCEPTION, eZ\Publish\Core\MVC\Symfony\Controller\Content\ViewController\buildResponse(), eZ\Publish\Core\MVC\Symfony\Controller\Controller\getEventDispatcher(), eZ\Publish\Core\MVC\Symfony\Controller\Controller\getRepository(), and eZ\Publish\Core\MVC\Symfony\Controller\Controller\isGranted().
    {
        if ( !$this->isGranted( new AuthorizationAttribute( 'content', 'read' ) ) )
            throw new AccessDeniedException();
        try
        {
            $content = $this->getRepository()->getContentService()->loadContent( $contentId );
            // @todo: Use a dedicated etag generator, generating a hash
            // instead of plain text
            $response = $this->buildResponse(
                "ezpublish-content-$contentId-$viewType-$layout",
                $content->contentInfo->modificationDate
            );
            if ( $response->isNotModified( $this->getRequest() ) )
            {
                return $response;
            }
            $response->setContent(
                $this->viewManager->renderContent(
                    $content,
                    $viewType,
                    array( 'noLayout' => !$layout )
                )
            );
            return $response;
        }
        catch ( \Exception $e )
        {
            $event = new APIContentExceptionEvent(
                $e,
                array(
                    'contentId'    => $contentId,
                    'locationId'   => null,
                    'viewType'     => $viewType
                )
            );
            $this->getEventDispatcher()->dispatch( MVCEvents::API_CONTENT_EXCEPTION, $event );
            if ( $event->hasContentView() )
            {
                $response->setContent(
                    $this->viewManager->renderContentView(
                        $event->getContentView()
                    )
                );
                return $response;
            }
            throw $e;
        }
    }
eZ\Publish\Core\MVC\Symfony\Controller\Content\ViewController::viewLocation ($locationId, $viewType, $layout = false)
Main action for viewing content through a location in the repository. Response will be cached with HttpCache validation model (Etag)
Parameters
int $locationId
string $viewType
boolean $layout
Exceptions
\Symfony\Component\Security\Core\Exception\AccessDeniedException
\Exception
Returns
Definition at line 81 of file ViewController.php.
References eZ\Publish\Core\MVC\Symfony\MVCEvents\API_CONTENT_EXCEPTION, eZ\Publish\Core\MVC\Symfony\Controller\Content\ViewController\buildResponse(), eZ\Publish\Core\MVC\Symfony\Controller\Controller\getEventDispatcher(), eZ\Publish\Core\MVC\Symfony\Controller\Controller\getRepository(), and eZ\Publish\Core\MVC\Symfony\Controller\Controller\isGranted().
    {
        if ( !$this->isGranted( new AuthorizationAttribute( 'content', 'read' ) ) )
            throw new AccessDeniedException();
        try
        {
            // Assume that location is cached by the repository
            $location = $this->getRepository()->getLocationService()->loadLocation( $locationId );
            $contentInfo = $location->getContentInfo();
            // @todo: Use a dedicated etag generator, generating a hash
            // instead of plain text
            $response = $this->buildResponse(
                "ezpublish-location-$locationId-$contentInfo->currentVersionNo-$viewType-$layout",
                $contentInfo->modificationDate
            );
            $response->headers->set( 'X-Location-Id', $locationId );
            if ( $response->isNotModified( $this->getRequest() ) )
            {
                return $response;
            }
            $response->setContent(
                $this->viewManager->renderLocation(
                    $location,
                    $viewType,
                    array( 'noLayout' => !$layout )
                )
            );
            return $response;
        }
        catch ( \Exception $e )
        {
            $event = new APIContentExceptionEvent(
                $e,
                array(
                    'contentId'    => null,
                    'locationId'   => $locationId,
                    'viewType'     => $viewType
                )
            );
            $this->getEventDispatcher()->dispatch( MVCEvents::API_CONTENT_EXCEPTION, $event );
            if ( $event->hasContentView() )
            {
                $response->setContent(
                    $this->viewManager->renderContentView(
                        $event->getContentView()
                    )
                );
                return $response;
            }
            throw $e;
        }
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php