ezp-next: eZ\Publish\Core\Repository\ContentService Class Reference
eZ\Publish\Core\Repository\ContentService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, Handler $handler, array $settings=array())
loadContentInfo ($contentId)
internalLoadContentInfo ($contentId)
loadContentInfoByRemoteId ($remoteId)
loadVersionInfo (APIContentInfo $contentInfo, $versionNo=null)
loadVersionInfoById ($contentId, $versionNo=null)
loadContentByContentInfo (APIContentInfo $contentInfo, array $languages=null, $versionNo=null)
loadContentByVersionInfo (APIVersionInfo $versionInfo, array $languages=null)
loadContent ($contentId, array $languages=null, $versionNo=null)
internalLoadContent ($contentId, array $languages=null, $versionNo=null)
loadContentByRemoteId ($remoteId, array $languages=null, $versionNo=null)
updateContentMetadata (APIContentInfo $contentInfo, ContentMetadataUpdateStruct $contentMetadataUpdateStruct)
deleteContent (APIContentInfo $contentInfo)
createContentDraft (APIContentInfo $contentInfo, APIVersionInfo $versionInfo=null, User $user=null)
loadContentDrafts (User $user=null)
translateVersion (TranslationInfo $translationInfo, APITranslationValues $translationValues, User $user=null)
publishVersion (APIVersionInfo $versionInfo)
deleteVersion (APIVersionInfo $versionInfo)
loadVersions (APIContentInfo $contentInfo)
copyContent (APIContentInfo $contentInfo, LocationCreateStruct $destinationLocationCreateStruct, APIVersionInfo $versionInfo=null)
loadRelations (APIVersionInfo $versionInfo)
loadReverseRelations (APIContentInfo $contentInfo)
addRelation (APIVersionInfo $sourceVersion, APIContentInfo $destinationContent)
deleteRelation (APIVersionInfo $sourceVersion, APIContentInfo $destinationContent)
addTranslationInfo (TranslationInfo $translationInfo)
loadTranslationInfos (APIContentInfo $contentInfo, array $filter=array())
newContentCreateStruct (ContentType $contentType, $mainLanguageCode)
newContentMetadataUpdateStruct ()
newContentUpdateStruct ()
newTranslationInfo ()
newTranslationValues ()
buildContentDomainObject (SPIContent $spiContent)
buildContentInfoDomainObject (SPIContentInfo $spiContentInfo)
Public Member Functions inherited from eZ\Publish\API\Repository\ContentService
loadVersionInfo (ContentInfo $contentInfo, $versionNo=null)
loadContentByContentInfo (ContentInfo $contentInfo, array $languages=null, $versionNo=null)
loadContentByVersionInfo (VersionInfo $versionInfo, array $languages=null)
createContent (ContentCreateStruct $contentCreateStruct, array $locationCreateStructs=array())
updateContentMetadata (ContentInfo $contentInfo, ContentMetadataUpdateStruct $contentMetadataUpdateStruct)
deleteContent (ContentInfo $contentInfo)
createContentDraft (ContentInfo $contentInfo, VersionInfo $versionInfo=null, User $user=null)
translateVersion (TranslationInfo $translationInfo, TranslationValues $translationValues, User $user=null)
updateContent (VersionInfo $versionInfo, ContentUpdateStruct $contentUpdateStruct)
publishVersion (VersionInfo $versionInfo)
deleteVersion (VersionInfo $versionInfo)
loadVersions (ContentInfo $contentInfo)
copyContent (ContentInfo $contentInfo, LocationCreateStruct $destinationLocationCreateStruct, VersionInfo $versionInfo=null)
loadRelations (VersionInfo $versionInfo)
loadReverseRelations (ContentInfo $contentInfo)
addRelation (VersionInfo $sourceVersion, ContentInfo $destinationContent)
deleteRelation (VersionInfo $sourceVersion, ContentInfo $destinationContent)
loadTranslationInfos (ContentInfo $contentInfo, array $filter=array())
Protected Member Functions
buildSPILocationCreateStructs (array $locationCreateStructs)
publishUrlAliasesForContent (APIContent $content, $onlyMain=false)
internalPublishVersion (APIVersionInfo $versionInfo, $publicationDate=null)
internalLoadRelations (APIVersionInfo $versionInfo)
buildDomainFields (array $spiFields)
buildVersionInfoDomainObject (SPIVersionInfo $spiVersionInfo)
getDomainVersionStatus ($spiStatus)
getDateTime ($timestamp)
buildRelationDomainObject (SPIRelation $spiRelation, APIContentInfo $sourceContentInfo=null, APIContentInfo $destinationContentInfo=null)
Protected Attributes
$repository
$persistenceHandler
$settings
Detailed Description
Definition at line 65 of file ContentService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\ContentService::__construct (RepositoryInterface $repository, Handler $handler, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\API\Repository\Repository $repository
\eZ\Publish\SPI\Persistence\Handler $handler
array $settings
Definition at line 89 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\$repository, and eZ\Publish\Core\Repository\ContentService\$settings.
    {
        $this->repository = $repository;
        $this->persistenceHandler = $handler;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            //'defaultSetting' => array(),
        );
    }
Member Function Documentation
eZ\Publish\Core\Repository\ContentService::addRelation (APIVersionInfo $sourceVersion, APIContentInfo $destinationContent)
Adds a relation of type common.
The source of the relation is the content and version referenced by $versionInfo.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to edit this version
\eZ\Publish\API\Repository\Exceptions\BadStateException if the version is not a draft
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $sourceVersion
\eZ\Publish\API\Repository\Values\Content\ContentInfo $destinationContent the destination of the relation
Returns
the newly created relation
Definition at line 1548 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildRelationDomainObject(), and eZ\Publish\Core\Repository\ContentService\loadVersionInfoById().
    {
        $sourceVersion = $this->loadVersionInfoById(
            $sourceVersion->contentInfo->id,
            $sourceVersion->versionNo
        );
        if ( $sourceVersion->status !== APIVersionInfo::STATUS_DRAFT )
        {
            throw new BadStateException(
                "\$sourceVersion",
                "Relations of type common can only be added to versions of status draft"
            );
        }
        if ( !$this->repository->canUser( 'content', 'edit', $sourceVersion ) )
            throw new UnauthorizedException( 'content', 'edit' );
        $sourceContentInfo = $sourceVersion->getContentInfo();
        $this->repository->beginTransaction();
        try
        {
            $spiRelation = $this->persistenceHandler->contentHandler()->addRelation(
                new SPIRelationCreateStruct(
                    array(
                        'sourceContentId' => $sourceContentInfo->id,
                        'sourceContentVersionNo' => $sourceVersion->versionNo,
                        'sourceFieldDefinitionId' => null,
                        'destinationContentId' => $destinationContent->id,
                        'type' => APIRelation::COMMON
                    )
                )
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildRelationDomainObject( $spiRelation, $sourceContentInfo, $destinationContent );
    }
eZ\Publish\Core\Repository\ContentService::addTranslationInfo (TranslationInfo $translationInfo)
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 1668 of file ContentService.php.
    {
    }
eZ\Publish\Core\Repository\ContentService::buildContentDomainObject (SPIContent $spiContent)
Builds a Content domain object from value object returned from persistence
Todo:
: Made public, since the search service also needs access to this method. Should be refactored into its own class together with the other build* methods.
Parameters
\eZ\Publish\SPI\Persistence\Content $spiContent
Returns
Definition at line 1759 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildDomainFields(), and eZ\Publish\Core\Repository\ContentService\buildVersionInfoDomainObject().
    {
        $versionInfo = $this->buildVersionInfoDomainObject( $spiContent->versionInfo );
        return new Content(
            array(
                "internalFields" => $this->buildDomainFields( $spiContent->fields ),
                "versionInfo" => $versionInfo,
                "relations" => $this->internalLoadRelations( $versionInfo ),
            )
        );
    }
eZ\Publish\Core\Repository\ContentService::buildContentInfoDomainObject (SPIContentInfo $spiContentInfo)
Builds a ContentInfo domain object from value object returned from persistence
Todo:
: Made public, since the search service also needs access to this method. Should be refactored into its own class together with the other build* methods.
Parameters
\eZ\Publish\SPI\Persistence\Content\ContentInfo $spiContentInfo
Returns
Definition at line 1813 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\getDateTime().
    {
        return new ContentInfo(
            array(
                "id" => $spiContentInfo->id,
                "name" => $spiContentInfo->name,
                "sectionId" => $spiContentInfo->sectionId,
                "currentVersionNo" => $spiContentInfo->currentVersionNo,
                "published" => $spiContentInfo->isPublished,
                "ownerId" => $spiContentInfo->ownerId,
                "modificationDate" => $spiContentInfo->modificationDate == 0 ?
                    null :
                    $this->getDateTime( $spiContentInfo->modificationDate ),
                "publishedDate" => $spiContentInfo->publicationDate == 0 ?
                    null :
                    $this->getDateTime( $spiContentInfo->publicationDate ),
                "alwaysAvailable" => $spiContentInfo->alwaysAvailable,
                "remoteId" => $spiContentInfo->remoteId,
                "mainLanguageCode" => $spiContentInfo->mainLanguageCode,
                "mainLocationId" => $spiContentInfo->mainLocationId,
                "contentType" => $this->repository->getContentTypeService()->loadContentType(
                    $spiContentInfo->contentTypeId
                )
            )
        );
    }
eZ\Publish\Core\Repository\ContentService::buildDomainFields (array $spiFields) protected
Returns an array of domain fields created from given array of SPI fields
Parameters
\eZ\Publish\SPI\Persistence\Content\Field[] $spiFields
Returns
array
Definition at line 1778 of file ContentService.php.
References eZ\Publish\API\Repository\Values\ContentType\ContentType\STATUS_DEFINED.
    {
        $fields = array();
        foreach ( $spiFields as $spiField )
        {
            $fields[] = new Field(
                array(
                    "id" => $spiField->id,
                    "value" => $this->repository->getFieldTypeService()->buildFieldType(
                        $spiField->type
                    )->fromPersistenceValue( $spiField->value ),
                    "languageCode" => $spiField->languageCode,
                    "fieldDefIdentifier" => $this->persistenceHandler->contentTypeHandler()->getFieldDefinition(
                        $spiField->fieldDefinitionId,
                        ContentType::STATUS_DEFINED
                    )->identifier
                )
            );
        }
        return $fields;
    }
eZ\Publish\Core\Repository\ContentService::buildRelationDomainObject (SPIRelation $spiRelation, APIContentInfo $sourceContentInfo = null, APIContentInfo $destinationContentInfo = null) protected
Builds API Relation object from provided SPI Relation object
Parameters
\eZ\Publish\SPI\Persistence\Content\Relation $spiRelation
\eZ\Publish\API\Repository\Values\Content\ContentInfo | null $sourceContentInfo
\eZ\Publish\API\Repository\Values\Content\ContentInfo | null $destinationContentInfo
Returns
Definition at line 1917 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\internalLoadContentInfo().
    {
        // @todo Should relations really be loaded w/o checking permissions just because User needs to be accessible??
        if ( $sourceContentInfo === null )
            $sourceContentInfo = $this->internalLoadContentInfo( $spiRelation->sourceContentId );
        if ( $destinationContentInfo === null )
            $destinationContentInfo = $this->internalLoadContentInfo( $spiRelation->destinationContentId );
        $sourceFieldDefinition = null;
        if ( $spiRelation->sourceFieldDefinitionId !== null )
        {
            $sourceFieldDefinition = $sourceContentInfo->getContentType()->getFieldDefinitionById(
                $spiRelation->sourceFieldDefinitionId
            );
        }
        return new Relation(
            array(
                "id" => $spiRelation->id,
                "sourceFieldDefinitionIdentifier" => $sourceFieldDefinition !== null ? $sourceFieldDefinition->identifier : null,
                "type" => $spiRelation->type,
                "sourceContentInfo" => $sourceContentInfo,
                "destinationContentInfo" => $destinationContentInfo
            )
        );
    }
eZ\Publish\Core\Repository\ContentService::buildSPILocationCreateStructs (array $locationCreateStructs) protected
Creates an array of SPI location create structs from given array of API location create structs
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException
Parameters
\eZ\Publish\API\Repository\Values\Content\LocationCreateStruct[] $locationCreateStructs
Returns
[]
Definition at line 628 of file ContentService.php.
    {
        $spiLocationCreateStructs = array();
        $parentLocationIdCache = array();
        foreach ( $locationCreateStructs as $index => $locationCreateStruct )
        {
            $parentLocation = $this->repository->getLocationService()->loadLocation( $locationCreateStruct->parentLocationId );
            if ( in_array( $parentLocation->id, $parentLocationIdCache ) )
            {
                throw new InvalidArgumentException(
                    "\$locationCreateStructs",
                    "Multiple LocationCreateStructs with parent Location '{$parentLocation->id}' exist"
                );
            }
            $parentLocationIdCache[] = $parentLocation->id;
            if ( $locationCreateStruct->priority !== null && !is_numeric( $locationCreateStruct->priority ) )
            {
                throw new InvalidArgumentValue( "priority", $locationCreateStruct->priority, "LocationCreateStruct" );
            }
            if ( !is_bool( $locationCreateStruct->hidden ) )
            {
                throw new InvalidArgumentValue( "hidden", $locationCreateStruct->hidden, "LocationCreateStruct" );
            }
            if ( $locationCreateStruct->remoteId !== null && ( !is_string( $locationCreateStruct->remoteId ) || empty( $locationCreateStruct->remoteId ) ) )
            {
                throw new InvalidArgumentValue( "remoteId", $locationCreateStruct->remoteId, "LocationCreateStruct" );
            }
            if ( $locationCreateStruct->sortField !== null && !is_numeric( $locationCreateStruct->sortField ) )
            {
                throw new InvalidArgumentValue( "sortField", $locationCreateStruct->sortField, "LocationCreateStruct" );
            }
            if ( $locationCreateStruct->sortOrder !== null && !is_numeric( $locationCreateStruct->sortOrder ) )
            {
                throw new InvalidArgumentValue( "sortOrder", $locationCreateStruct->sortOrder, "LocationCreateStruct" );
            }
            if ( null === $locationCreateStruct->remoteId )
            {
                $locationCreateStruct->remoteId = md5( uniqid( get_class( $locationCreateStruct ), true ) );
            }
            else
            {
                try
                {
                    $this->repository->getLocationService()->loadLocationByRemoteId( $locationCreateStruct->remoteId );
                    throw new InvalidArgumentException(
                        "\$locationCreateStructs",
                        "Another Location with remoteId '{$locationCreateStruct->remoteId}' exists"
                    );
                }
                catch ( APINotFoundException $e )
                {
                    // Do nothing
                }
            }
            $spiLocationCreateStructs[] = new SPILocationCreateStruct(
                array(
                    "priority" => $locationCreateStruct->priority,
                    "hidden" => $locationCreateStruct->hidden,
                    "invisible" => ( $locationCreateStruct->hidden === true || $parentLocation->hidden || $parentLocation->invisible ),
                    "remoteId" => $locationCreateStruct->remoteId,
                    // contentId and contentVersion are set in ContentHandler upon draft creation
                    "contentId" => null,
                    "contentVersion" => null,
                    "pathIdentificationString" => null,
                    "mainLocationId" => ( $index === 0 ),
                    "sortField" => $locationCreateStruct->sortField,
                    "sortOrder" => $locationCreateStruct->sortOrder,
                    "parentId" => $locationCreateStruct->parentLocationId
                )
            );
        }
        return $spiLocationCreateStructs;
    }
eZ\Publish\Core\Repository\ContentService::buildVersionInfoDomainObject (SPIVersionInfo $spiVersionInfo) protected
Builds a VersionInfo domain object from value object returned from persistence
Parameters
\eZ\Publish\SPI\Persistence\Content\VersionInfo $spiVersionInfo
Returns
VersionInfo
Definition at line 1847 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildContentInfoDomainObject(), eZ\Publish\Core\Repository\ContentService\getDateTime(), and eZ\Publish\Core\Repository\ContentService\getDomainVersionStatus().
    {
        $languageCodes = array();
        foreach ( $spiVersionInfo->languageIds as $languageId )
        {
            $languageCodes[] = $this->persistenceHandler->contentLanguageHandler()->load(
                $languageId
            )->languageCode;
        }
        return new VersionInfo(
            array(
                "id" => $spiVersionInfo->id,
                "versionNo" => $spiVersionInfo->versionNo,
                "modificationDate" => $this->getDateTime( $spiVersionInfo->modificationDate ),
                "creatorId" => $spiVersionInfo->creatorId,
                "creationDate" => $this->getDateTime( $spiVersionInfo->creationDate ),
                "status" => $this->getDomainVersionStatus( $spiVersionInfo->status ),
                "initialLanguageCode" => $spiVersionInfo->initialLanguageCode,
                "languageCodes" => $languageCodes,
                "names" => $spiVersionInfo->names,
                "contentInfo" => $this->buildContentInfoDomainObject( $spiVersionInfo->contentInfo )
            )
        );
    }
eZ\Publish\Core\Repository\ContentService::copyContent (APIContentInfo $contentInfo, LocationCreateStruct $destinationLocationCreateStruct, APIVersionInfo $versionInfo = null)
Copies the content to a new location. If no version is given, all versions are copied, otherwise only the given version.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to copy the content to the given location
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
\eZ\Publish\API\Repository\Values\Content\LocationCreateStruct $destinationLocationCreateStruct the target location where the content is copied to
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
Returns
Definition at line 1389 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildVersionInfoDomainObject(), and eZ\Publish\Core\Repository\ContentService\internalPublishVersion().
    {
        if ( $destinationLocationCreateStruct->remoteId !== null )
        {
            try
            {
                $this->repository->getLocationService()->loadLocationByRemoteId(
                    $destinationLocationCreateStruct->remoteId
                );
                throw new InvalidArgumentException(
                    "\$destinationLocationCreateStruct",
                    "Location with remoteId '{$destinationLocationCreateStruct->remoteId}' already exists"
                );
            }
            catch ( APINotFoundException $e )
            {
                // Do nothing
            }
        }
        else
        {
            $destinationLocationCreateStruct->remoteId = md5( uniqid( get_class( $this ), true ) );
        }
        if ( !$this->repository->canUser( 'content', 'create', $contentInfo, $destinationLocationCreateStruct ) )
            throw new UnauthorizedException( 'content', 'create' );
        $this->repository->beginTransaction();
        try
        {
            $spiContent = $this->persistenceHandler->contentHandler()->copy(
                $contentInfo->id,
                $versionInfo ? $versionInfo->versionNo : null
            );
            $content = $this->internalPublishVersion(
                $this->buildVersionInfoDomainObject( $spiContent->versionInfo ),
                $spiContent->versionInfo->creationDate
            );
            $this->repository->getLocationService()->createLocation(
                $content->getVersionInfo()->getContentInfo(),
                $destinationLocationCreateStruct
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $content;
    }
eZ\Publish\Core\Repository\ContentService::createContentDraft (APIContentInfo $contentInfo, APIVersionInfo $versionInfo = null, User $user = null)
Creates a draft from a published or archived version.
If no version is given, the current published version is used. 4.x: The draft is created with the initialLanguage code of the source version or if not present with the main language. It can be changed on updating the version.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to create the draft
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
\eZ\Publish\API\Repository\Values\User\User $user if set given user is used to create the draft - otherwise the current user is used
Returns
- the newly created content draft
Definition at line 905 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildContentDomainObject(), eZ\Publish\Core\Repository\ContentService\loadContentInfo(), eZ\Publish\Core\Repository\ContentService\loadVersionInfoById(), eZ\Publish\API\Repository\Values\Content\VersionInfo\STATUS_ARCHIVED, and eZ\Publish\API\Repository\Values\Content\VersionInfo\STATUS_PUBLISHED.
    {
        $contentInfo = $this->loadContentInfo( $contentInfo->id );
        if ( $versionInfo !== null )
        {
            // Check that given $contentInfo and $versionInfo belong to the same content
            if ( $versionInfo->getContentInfo()->id != $contentInfo->id )
            {
                throw new InvalidArgumentException(
                    "\$versionInfo",
                    "VersionInfo does not belong to the same content as given ContentInfo"
                );
            }
            $versionInfo = $this->loadVersionInfoById( $contentInfo->id, $versionInfo->versionNo );
            switch ( $versionInfo->status )
            {
                case VersionInfo::STATUS_PUBLISHED:
                case VersionInfo::STATUS_ARCHIVED:
                    break;
                default:
                    // @todo: throw an exception here, to be defined
                    throw new BadStateException(
                        "\$versionInfo",
                        "Draft can not be created from a draft version"
                    );
            }
            $versionNo = $versionInfo->versionNo;
        }
        else if ( $contentInfo->published )
        {
            $versionNo = $contentInfo->currentVersionNo;
        }
        else
        {
            // @todo: throw an exception here, to be defined
            throw new BadStateException(
                "\$contentInfo",
                "Content is not published, draft can be created only from published or archived version"
            );
        }
        if ( $user === null )
        {
            $user = $this->repository->getCurrentUser();
        }
        else
        {
            $user = $this->repository->getUserService()->loadUser( $user->id );
        }
        if ( !$this->repository->canUser( 'content', 'edit', $contentInfo ) )
            throw new UnauthorizedException( 'content', 'edit', array( 'name' => $contentInfo->name ) );
        $this->repository->beginTransaction();
        try
        {
            $spiContent = $this->persistenceHandler->contentHandler()->createDraftFromVersion(
                $contentInfo->id,
                $versionNo,
                $user->id
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildContentDomainObject( $spiContent );
    }
eZ\Publish\Core\Repository\ContentService::deleteContent (APIContentInfo $contentInfo)
Deletes a content object including all its versions and locations including their subtrees.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to delete the content (in one of the locations of the given content object)
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
Definition at line 872 of file ContentService.php.
    {
        if ( !$this->repository->canUser( 'content', 'remove', $contentInfo ) )
            throw new UnauthorizedException( 'content', 'remove' );
        $this->repository->beginTransaction();
        try
        {
            $this->persistenceHandler->contentHandler()->deleteContent( $contentInfo->id );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentService::deleteRelation (APIVersionInfo $sourceVersion, APIContentInfo $destinationContent)
Removes a relation of type COMMON from a draft.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed edit this version
\eZ\Publish\API\Repository\Exceptions\BadStateException if the version is not a draft
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if there is no relation of type COMMON for the given destination
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $sourceVersion
\eZ\Publish\API\Repository\Values\Content\ContentInfo $destinationContent
Definition at line 1603 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\loadVersionInfoById().
    {
        $sourceVersion = $this->loadVersionInfoById(
            $sourceVersion->contentInfo->id,
            $sourceVersion->versionNo
        );
        if ( $sourceVersion->status !== APIVersionInfo::STATUS_DRAFT )
        {
            throw new BadStateException(
                "\$sourceVersion",
                "Relations of type common can only be removed from versions of status draft"
            );
        }
        if ( !$this->repository->canUser( 'content', 'edit', $sourceVersion ) )
            throw new UnauthorizedException( 'content', 'edit' );
        $spiRelations = $this->persistenceHandler->contentHandler()->loadRelations(
            $sourceVersion->getContentInfo()->id,
            $sourceVersion->versionNo,
            APIRelation::COMMON
        );
        if ( empty( $spiRelations ) )
        {
            throw new InvalidArgumentException(
                "\$sourceVersion",
                "There are no relations of type COMMON for the given destination"
            );
        }
        // there should be only one relation of type COMMON for each destination,
        // but in case there were ever more then one, we will remove them all
        // @todo: alternatively, throw BadStateException?
        $this->repository->beginTransaction();
        try
        {
            foreach ( $spiRelations as $spiRelation )
            {
                if ( $spiRelation->destinationContentId == $destinationContent->id )
                {
                    $this->persistenceHandler->contentHandler()->removeRelation( $spiRelation->id );
                }
            }
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentService::deleteVersion (APIVersionInfo $versionInfo)
removes the given version
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException if the version is in state published
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to remove this version
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
Definition at line 1310 of file ContentService.php.
    {
        if ( $versionInfo->status === APIVersionInfo::STATUS_PUBLISHED )
        {
            throw new BadStateException(
                "\$versionInfo",
                "Version is published and can not be removed"
            );
        }
        if ( !$this->repository->canUser( 'content', 'remove', $versionInfo ) )
            throw new UnauthorizedException( 'content', 'remove' );
        $this->repository->beginTransaction();
        try
        {
            $this->persistenceHandler->contentHandler()->deleteVersion(
                $versionInfo->getContentInfo()->id,
                $versionInfo->versionNo
            );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ContentService::getDateTime ($timestamp) protected
Parameters
int | null $timestamp
Returns
|null
Definition at line 1901 of file ContentService.php.
    {
        $dateTime = new DateTime();
        $dateTime->setTimestamp( $timestamp );
        return $dateTime;
    }
eZ\Publish\Core\Repository\ContentService::getDomainVersionStatus ($spiStatus) protected
Parameters
int $spiStatus
Returns
int|null
Definition at line 1878 of file ContentService.php.
References eZ\Publish\API\Repository\Values\Content\VersionInfo\STATUS_ARCHIVED, eZ\Publish\API\Repository\Values\Content\VersionInfo\STATUS_DRAFT, and eZ\Publish\API\Repository\Values\Content\VersionInfo\STATUS_PUBLISHED.
    {
        $status = null;
        switch ( $spiStatus )
        {
            case SPIVersionInfo::STATUS_DRAFT:
                $status = VersionInfo::STATUS_DRAFT;
                break;
            case SPIVersionInfo::STATUS_PUBLISHED:
                $status = VersionInfo::STATUS_PUBLISHED;
                break;
            case SPIVersionInfo::STATUS_ARCHIVED:
                $status = VersionInfo::STATUS_ARCHIVED;
                break;
        }
        return $status;
    }
eZ\Publish\Core\Repository\ContentService::internalLoadContent ($contentId, array $languages = null, $versionNo = null)
Loads content in a version of the given content object.
If no version number is given, the method returns the current version
private This is only available to services that needs access to Content w/o permissions checks
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the content or version with the given id and languages does not exist
Parameters
int $contentId
array | null $languages A language filter for fields. If not given all languages are returned
int | null $versionNo the version number. If not given the current version is returned.
Returns
Definition at line 316 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildContentDomainObject().
    {
        try
        {
            if ( $versionNo === null )
            {
                $versionNo = $this->persistenceHandler->contentHandler()->loadContentInfo(
                    $contentId
                )->currentVersionNo;
            }
            $spiContent = $this->persistenceHandler->contentHandler()->load(
                $contentId,
                $versionNo,
                $languages
            );
        }
        catch ( APINotFoundException $e )
        {
            throw new NotFoundException(
                "Content",
                array(
                    "id" => $contentId,
                    "languages" => $languages,
                    "versionNo" => $versionNo
                ),
                $e
            );
        }
        if ( !empty( $languages ) )
        {
            foreach ( $languages as $languageCode )
            {
                if (
                    !in_array(
                        $this->persistenceHandler->contentLanguageHandler()->loadByLanguageCode( $languageCode )->id,
                        $spiContent->versionInfo->languageIds
                    )
                )
                {
                    throw new NotFoundException(
                        "Content",
                        array(
                            "id" => $contentId,
                            "languages" => $languages,
                            "versionNo" => $versionNo
                        )
                    );
                }
            }
        }
        return $this->buildContentDomainObject( $spiContent );
    }
eZ\Publish\Core\Repository\ContentService::internalLoadContentInfo ($contentId)
Loads a content info object.
To load fields use loadContent
private This is only available to services that needs access to Content w/o permissions checks
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the content with the given id does not exist
Parameters
int $contentId
Returns
Definition at line 132 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildContentInfoDomainObject().
    {
        try
        {
            $spiContentInfo = $this->persistenceHandler->contentHandler()->loadContentInfo( $contentId );
        }
        catch ( APINotFoundException $e )
        {
            throw new NotFoundException(
                "Content",
                $contentId,
                $e
            );
        }
        return $this->buildContentInfoDomainObject( $spiContentInfo );
    }
eZ\Publish\Core\Repository\ContentService::internalLoadRelations (APIVersionInfo $versionInfo) protected
Loads all outgoing relations for the given version
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
Returns
[]
Definition at line 1476 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildRelationDomainObject().
    {
        $contentInfo = $versionInfo->getContentInfo();
        $spiRelations = $this->persistenceHandler->contentHandler()->loadRelations(
            $contentInfo->id,
            $versionInfo->versionNo
        );
        $returnArray = array();
        foreach ( $spiRelations as $spiRelation )
        {
            $returnArray[] = $this->buildRelationDomainObject(
                $spiRelation,
                $contentInfo
            );
        }
        return $returnArray;
    }
eZ\Publish\Core\Repository\ContentService::internalPublishVersion (APIVersionInfo $versionInfo, $publicationDate = null) protected
Publishes a content version
Exceptions
\eZ\Publish\API\Repository\Exceptions\BadStateException if the version is not a draft
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
int | null $publicationDate
Returns
Definition at line 1279 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildContentDomainObject(), and eZ\Publish\Core\Repository\ContentService\publishUrlAliasesForContent().
    {
        if ( $versionInfo->status !== APIVersionInfo::STATUS_DRAFT )
        {
            throw new BadStateException( "versionInfo", "only versions in draft status can be published" );
        }
        $metadataUpdateStruct = new SPIMetadataUpdateStruct();
        $metadataUpdateStruct->publicationDate = isset( $publicationDate ) ? $publicationDate : time();
        $metadataUpdateStruct->modificationDate = $metadataUpdateStruct->publicationDate;
        $spiContent = $this->persistenceHandler->contentHandler()->publish(
            $versionInfo->getContentInfo()->id,
            $versionInfo->versionNo,
            $metadataUpdateStruct
        );
        $content = $this->buildContentDomainObject( $spiContent );
        $this->publishUrlAliasesForContent( $content );
        return $content;
    }
eZ\Publish\Core\Repository\ContentService::loadContent ($contentId, array $languages = null, $versionNo = null)
Loads content in a version of the given content object.
If no version number is given, the method returns the current version
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the content or version with the given id and languages does not exist
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
int $contentId
array | null $languages A language filter for fields. If not given all languages are returned
int | null $versionNo the version number. If not given the current version is returned.
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 292 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\internalLoadContent().
    {
        $content = $this->internalLoadContent( $contentId, $languages, $versionNo );
        if ( !$this->repository->canUser( 'content', 'read', $content ) )
            throw new UnauthorizedException( 'content', 'read' );
        return $content;
    }
eZ\Publish\Core\Repository\ContentService::loadContentByContentInfo (APIContentInfo $contentInfo, array $languages = null, $versionNo = null)
Loads content in a version for the given content info object.
If no version number is given, the method returns the current version
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if version with the given number does not exist
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
array $languages A language filter for fields. If not given all languages are returned
int $versionNo the version number. If not given the current version is returned.
Returns
Definition at line 250 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\loadContent().
    {
        return $this->loadContent(
            $contentInfo->id,
            $languages,
            $versionNo
        );
    }
eZ\Publish\Core\Repository\ContentService::loadContentByRemoteId ($remoteId, array $languages = null, $versionNo = null)
Loads content in a version for the content object reference by the given remote id.
If no version is given, the method returns the current version
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the content or version with the given remote id does not exist
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
string $remoteId
array $languages A language filter for fields. If not given all languages are returned
int $versionNo the version number. If not given the current version is returned.
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 386 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\internalLoadContent().
    {
        $content = $this->repository->getSearchService()->findSingle( new CriterionRemoteId( $remoteId ), array(), false );
        if ( !empty( $languages ) || $versionNo !== null )
        {
            $content = $this->internalLoadContent( $content->id, $languages, $versionNo );
        }
        if ( !$this->repository->canUser( 'content', 'read', $content ) )
            throw new UnauthorizedException( 'content', 'read' );
        return $content;
    }
eZ\Publish\Core\Repository\ContentService::loadContentByVersionInfo (APIVersionInfo $versionInfo, array $languages = null)
Loads content in the version given by version info.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
array $languages A language filter for fields. If not given all languages are returned
Returns
Definition at line 269 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\loadContent().
    {
        return $this->loadContent(
            $versionInfo->getContentInfo()->id,
            $languages,
            $versionInfo->versionNo
        );
    }
eZ\Publish\Core\Repository\ContentService::loadContentDrafts (User $user = null)
Loads drafts for a user.
If no user is given the drafts for the authenticated user a returned
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load the draft list
Parameters
\eZ\Publish\API\Repository\Values\User\User $user
Returns
the drafts (VersionInfo) owned by the given user
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 993 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildVersionInfoDomainObject().
    {
        if ( $user === null )
        {
            $user = $this->repository->getCurrentUser();
        }
        // throw early if user has absolutely no access to versionread
        if ( $this->repository->hasAccess( 'content', 'versionread' ) === false )
            throw new UnauthorizedException( 'content', 'versionread' );
        $spiVersionInfoList = $this->persistenceHandler->contentHandler()->loadDraftsForUser( $user->id );
        $versionInfoList = array();
        foreach ( $spiVersionInfoList as $spiVersionInfo )
        {
            $versionInfo = $this->buildVersionInfoDomainObject( $spiVersionInfo );
            if ( !$this->repository->canUser( 'content', 'versionread', $versionInfo ) )
                throw new UnauthorizedException( 'content', 'versionread' );
            $versionInfoList[] = $versionInfo;
        }
        return $versionInfoList;
    }
eZ\Publish\Core\Repository\ContentService::loadContentInfo ($contentId)
Loads a content info object.
To load fields use loadContent
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to read the content
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the content with the given id does not exist
Parameters
int $contentId
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 111 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\internalLoadContentInfo().
    {
        $contentInfo = $this->internalLoadContentInfo( $contentId );
        if ( !$this->repository->canUser( 'content', 'read', $contentInfo ) )
            throw new UnauthorizedException( 'content', 'read' );
        return $contentInfo;
    }
eZ\Publish\Core\Repository\ContentService::loadContentInfoByRemoteId ($remoteId)
Loads a content info object for the given remoteId.
To load fields use loadContent
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to read the content
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the content with the given remote id does not exist
Parameters
string $remoteId
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 162 of file ContentService.php.
    {
        $content = $this->repository->getSearchService()->findSingle( new CriterionRemoteId( $remoteId ), array(), false );
        if ( !$this->repository->canUser( 'content', 'read', $content ) )
            throw new UnauthorizedException( 'content', 'read' );
        return $content->contentInfo;
    }
eZ\Publish\Core\Repository\ContentService::loadRelations (APIVersionInfo $versionInfo)
Loads all outgoing relations for the given version
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to read this version
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
Returns
[]
Definition at line 1454 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\internalLoadRelations().
    {
        if ( !$this->repository->canUser( 'content', 'versionread', $versionInfo ) )
            throw new UnauthorizedException( 'content', 'versionread' );
        $relations = $this->internalLoadRelations( $versionInfo );
        foreach ( $relations as $relation )
        {
            if ( !$this->repository->canUser( 'content', 'read', $relation->getDestinationContentInfo() ) )
                throw new UnauthorizedException( 'content', 'read' );
        }
        return $relations;
    }
eZ\Publish\Core\Repository\ContentService::loadReverseRelations (APIContentInfo $contentInfo)
Loads all incoming relations for a content object.
The relations come only from published versions of the source content objects
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to read this version
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
Returns
[]
Definition at line 1508 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildRelationDomainObject().
    {
        if ( $this->repository->hasAccess( 'content', 'reverserelatedlist' ) !== true )
            throw new UnauthorizedException( 'content', 'reverserelatedlist' );
        $spiRelations = $this->persistenceHandler->contentHandler()->loadReverseRelations(
            $contentInfo->id
        );
        $returnArray = array();
        foreach ( $spiRelations as $spiRelation )
        {
            $relation = $this->buildRelationDomainObject(
                $spiRelation,
                null,
                $contentInfo
            );
            if ( !$this->repository->canUser( 'content', 'read', $relation->getSourceContentInfo() ) )
                throw new UnauthorizedException( 'content', 'read' );
            $returnArray[] = $relation;
        }
        return $returnArray;
    }
eZ\Publish\Core\Repository\ContentService::loadTranslationInfos (APIContentInfo $contentInfo, array $filter = array())
lists the translations done on this content object
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed read translation infos
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
array $filter
Todo:
TBD - filter by source version destination version and languages
Returns
[]
Since
5.0
Definition at line 1687 of file ContentService.php.
    {
    }
eZ\Publish\Core\Repository\ContentService::loadVersionInfo (APIContentInfo $contentInfo, $versionNo = null)
Loads a version info of the given content object.
If no version number is given, the method returns the current version
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the version with the given number does not exist
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
int $versionNo the version number. If not given the current version is returned.
Returns
Definition at line 185 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\loadVersionInfoById().
    {
        return $this->loadVersionInfoById( $contentInfo->id, $versionNo );
    }
eZ\Publish\Core\Repository\ContentService::loadVersionInfoById ($contentId, $versionNo = null)
Loads a version info of the given content object id.
If no version number is given, the method returns the current version
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException - if the version with the given number does not exist
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to load this version
Parameters
int $contentId
int $versionNo the version number. If not given the current version is returned.
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 203 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildVersionInfoDomainObject(), and eZ\Publish\Core\Repository\ContentService\loadContentInfo().
    {
        if ( $versionNo === null )
        {
            $versionNo = $this->loadContentInfo( $contentId )->currentVersionNo;
        }
        try
        {
            $spiVersionInfo = $this->persistenceHandler->contentHandler()->loadVersionInfo(
                $contentId,
                $versionNo
            );
        }
        catch ( APINotFoundException $e )
        {
            throw new NotFoundException(
                "VersionInfo",
                array(
                    "contentId" => $contentId,
                    "versionNo" => $versionNo
                ),
                $e
            );
        }
        $versionInfo = $this->buildVersionInfoDomainObject( $spiVersionInfo );
        if ( !$this->repository->canUser( 'content', 'versionread', $versionInfo ) )
            throw new UnauthorizedException( 'content', 'versionread' );
        return $versionInfo;
    }
eZ\Publish\Core\Repository\ContentService::loadVersions (APIContentInfo $contentInfo)
Loads all versions for the given content
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to list versions
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
Returns
[] Sorted by creation date
Definition at line 1348 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\buildVersionInfoDomainObject().
    {
        if ( !$this->repository->canUser( 'content', 'versionread', $contentInfo ) )
            throw new UnauthorizedException( 'content', 'versionread' );
        $spiVersionInfoList = $this->persistenceHandler->contentHandler()->listVersions( $contentInfo->id );
        $versions = array();
        foreach ( $spiVersionInfoList as $spiVersionInfo )
        {
            $versionInfo = $this->buildVersionInfoDomainObject( $spiVersionInfo );
            if ( !$this->repository->canUser( 'content', 'versionread', $versionInfo ) )
                throw new UnauthorizedException( 'content', 'versionread' );
            $versions[] = $versionInfo;
        }
        usort(
            $versions,
            function( $a, $b )
            {
                if ( $a->creationDate->getTimestamp() === $b->creationDate->getTimestamp() ) return 0;
                return ( $a->creationDate->getTimestamp() < $b->creationDate->getTimestamp() ) ? -1 : 1;
            }
        );
        return $versions;
    }
eZ\Publish\Core\Repository\ContentService::newContentCreateStruct (ContentType $contentType, $mainLanguageCode)
Instantiates a new content create struct object
Parameters
\eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType
string $mainLanguageCode
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 1700 of file ContentService.php.
    {
        return new ContentCreateStruct(
            array(
                "contentType" => $contentType,
                "mainLanguageCode" => $mainLanguageCode
            )
        );
    }
eZ\Publish\Core\Repository\ContentService::newContentMetadataUpdateStruct ()
Instantiates a new content meta data update struct
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 1715 of file ContentService.php.
    {
        return new ContentMetadataUpdateStruct();
    }
eZ\Publish\Core\Repository\ContentService::newContentUpdateStruct ()
Instantiates a new content update struct
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 1725 of file ContentService.php.
    {
        return new ContentUpdateStruct();
    }
eZ\Publish\Core\Repository\ContentService::newTranslationInfo ()
Instantiates a new TranslationInfo object
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 1734 of file ContentService.php.
    {
        return new TranslationInfo();
    }
eZ\Publish\Core\Repository\ContentService::newTranslationValues ()
Instantiates a Translation object
Returns
Implements eZ\Publish\API\Repository\ContentService.
Definition at line 1743 of file ContentService.php.
    {
        return new TranslationValues();
    }
eZ\Publish\Core\Repository\ContentService::publishUrlAliasesForContent (APIContent $content, $onlyMain = false) protected
Publishes URL aliases for all locations of a given content.
Parameters
\eZ\Publish\API\Repository\Values\Content\Content $content
boolean $onlyMain
Todo:
: this is legacy storage specific for updating ezcontentobject_tree.path_identification_string, to be removed
Returns
void
Definition at line 837 of file ContentService.php.
    {
        $urlAliasNames = $this->repository->getNameSchemaService()->resolveUrlAliasSchema( $content );
        $locations = $this->repository->getLocationService()->loadLocations(
            $content->getVersionInfo()->getContentInfo()
        );
        foreach ( $locations as $location )
        {
            foreach ( $urlAliasNames as $languageCode => $name )
            {
                if ( $onlyMain && $languageCode != $content->contentInfo->mainLanguageCode )
                {
                    continue;
                }
                $this->persistenceHandler->urlAliasHandler()->publishUrlAliasForLocation(
                    $location->id,
                    $location->parentLocationId,
                    $name,
                    $languageCode,
                    $content->contentInfo->alwaysAvailable,
                    // @todo: this is legacy storage specific for updating ezcontentobject_tree.path_identification_string, to be removed
                    $languageCode === $content->contentInfo->mainLanguageCode
                );
            }
        }
    }
eZ\Publish\Core\Repository\ContentService::publishVersion (APIVersionInfo $versionInfo)
Publishes a content version
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to publish this version
\eZ\Publish\API\Repository\Exceptions\BadStateException if the version is not a draft
Parameters
\eZ\Publish\API\Repository\Values\Content\VersionInfo $versionInfo
Returns
Definition at line 1243 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\internalPublishVersion(), and eZ\Publish\Core\Repository\ContentService\loadContent().
    {
        $content = $this->loadContent(
            $versionInfo->contentInfo->id,
            null,
            $versionInfo->versionNo
        );
        if ( !$this->repository->canUser( 'content', 'edit', $content ) )
            throw new UnauthorizedException( 'content', 'edit' );
        $this->repository->beginTransaction();
        try
        {
            $content = $this->internalPublishVersion( $content->getVersionInfo() );
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $content;
    }
eZ\Publish\Core\Repository\ContentService::translateVersion (TranslationInfo $translationInfo, APITranslationValues $translationValues, User $user = null)
Definition at line 1039 of file ContentService.php.
    {
    }
eZ\Publish\Core\Repository\ContentService::updateContentMetadata (APIContentInfo $contentInfo, ContentMetadataUpdateStruct $contentMetadataUpdateStruct)
Updates the metadata.
(see ContentMetadataUpdateStruct) of a content object - to update fields use updateContent
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to update the content meta data
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the remoteId in $contentMetadataUpdateStruct is set but already exists
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
\eZ\Publish\API\Repository\Values\Content\ContentMetadataUpdateStruct $contentMetadataUpdateStruct
Returns
the content with the updated attributes
Definition at line 724 of file ContentService.php.
References eZ\Publish\Core\Repository\ContentService\loadContent(), eZ\Publish\Core\Repository\ContentService\loadContentInfo(), eZ\Publish\Core\Repository\ContentService\loadContentInfoByRemoteId(), and eZ\Publish\Core\Repository\ContentService\publishUrlAliasesForContent().
    {
        $propertyCount = 0;
        foreach ( $contentMetadataUpdateStruct as $propertyName => $propertyValue )
        {
            if ( isset( $contentMetadataUpdateStruct->$propertyName ) )
            {
                $propertyCount += 1;
            }
        }
        if ( $propertyCount === 0 )
        {
            throw new InvalidArgumentException(
                "\$contentMetadataUpdateStruct",
                "At least one property must be set"
            );
        }
        $loadedContentInfo = $this->loadContentInfo( $contentInfo->id );
        if ( !$this->repository->canUser( 'content', 'edit', $loadedContentInfo ) )
            throw new UnauthorizedException( 'content', 'edit' );
        if ( isset( $contentMetadataUpdateStruct->remoteId ) )
        {
            try
            {
                $existingContentInfo = $this->loadContentInfoByRemoteId( $contentMetadataUpdateStruct->remoteId );
                if ( $existingContentInfo->id !== $loadedContentInfo->id )
                    throw new InvalidArgumentException(
                        "\$contentMetadataUpdateStruct",
                        "Another content with remoteId '{$contentMetadataUpdateStruct->remoteId}' exists"
                    );
            }
            catch ( APINotFoundException $e )
            {
                // Do nothing
            }
        }
        $this->repository->beginTransaction();
        try
        {
            if ( $propertyCount > 1 || !isset( $contentMetadataUpdateStruct->mainLocationId ) )
            {
                $this->persistenceHandler->contentHandler()->updateMetadata(
                    $loadedContentInfo->id,
                    new SPIMetadataUpdateStruct(
                        array(
                            "ownerId" => $contentMetadataUpdateStruct->ownerId,
                            "publicationDate" => isset( $contentMetadataUpdateStruct->publishedDate ) ?
                                $contentMetadataUpdateStruct->publishedDate->getTimestamp() :
                                null,
                            "modificationDate" => isset( $contentMetadataUpdateStruct->modificationDate ) ?
                                $contentMetadataUpdateStruct->modificationDate->getTimestamp() :
                                null,
                            "mainLanguageId" => isset( $contentMetadataUpdateStruct->mainLanguageCode ) ?
                                $this->repository->getContentLanguageService()->loadLanguage(
                                    $contentMetadataUpdateStruct->mainLanguageCode
                                )->id :
                                null,
                            "alwaysAvailable" => $contentMetadataUpdateStruct->alwaysAvailable,
                            "remoteId" => $contentMetadataUpdateStruct->remoteId
                        )
                    )
                );
            }
            // Change main location
            if ( isset( $contentMetadataUpdateStruct->mainLocationId )
                && $loadedContentInfo->mainLocationId !== $contentMetadataUpdateStruct->mainLocationId )
            {
                $this->persistenceHandler->locationHandler()->changeMainLocation(
                    $loadedContentInfo->id,
                    $contentMetadataUpdateStruct->mainLocationId
                );
            }
            // Republish URL aliases to update always-available flag
            if ( isset( $contentMetadataUpdateStruct->alwaysAvailable )
                && $loadedContentInfo->alwaysAvailable !== $contentMetadataUpdateStruct->alwaysAvailable )
            {
                $content = $this->loadContent( $loadedContentInfo->id );
                $this->publishUrlAliasesForContent( $content );
            }
            // @todo: this is legacy storage specific for updating ezcontentobject_tree.path_identification_string, to be removed
            else if ( isset( $contentMetadataUpdateStruct->mainLanguageCode )
                && ( $loadedContentInfo->mainLanguageCode !== $contentMetadataUpdateStruct->mainLanguageCode ) )
            {
                $content = $this->loadContent( $loadedContentInfo->id );
                $this->publishUrlAliasesForContent( $content, true );
            }
            $this->repository->commit();
        }
        catch ( Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return isset( $content ) ? $content : $this->loadContent( $loadedContentInfo->id );
    }
Member Data Documentation
eZ\Publish\Core\Repository\ContentService::$persistenceHandler protected
Definition at line 75 of file ContentService.php.
eZ\Publish\Core\Repository\ContentService::$repository protected
Definition at line 70 of file ContentService.php.
eZ\Publish\Core\Repository\ContentService::$settings protected
Definition at line 80 of file ContentService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/ContentService.php