ezp-next: eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement Class Reference
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement Class Reference
Public Member Functions
__construct ($elementNumber)
match ()
getName ()
setRequest (SimplifiedRequest $request)
analyseURI ($uri)
analyseLink ($linkUri)
Protected Member Functions
getURIElements ()
Detailed Description
Definition at line 16 of file URIElement.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement::__construct ($elementNumber)
Constructor.
Parameters
int $elementNumber Number of elements to take into account.
Definition at line 35 of file URIElement.php.
    {
        $this->elementNumber = (int)$elementNumber;
    }
Member Function Documentation
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement::analyseLink ($linkUri)
Analyses $linkUri when generating a link to a route, in order to have the siteaccess part back in the URI.
Parameters
string $linkUri
Returns
string The modified link URI
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\URILexer.
Definition at line 129 of file URIElement.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement\analyseLink(), and eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement\getURIElements().
    {
        $uriElements = implode( '/', $this->getURIElements() );
        return "/{$uriElements}{$linkUri}";
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement::analyseURI ($uri)
Analyses $uri and removes the siteaccess part, if needed.
Parameters
string $uri The original URI
Returns
string The modified URI
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\URILexer.
Definition at line 108 of file URIElement.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement\analyseURI(), and eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement\getURIElements().
    {
        $uriElements = '/' . implode( '/', $this->getURIElements() );
        if ( $uri == $uriElements )
        {
            $uri = '';
        }
        else if ( strpos( $uri, $uriElements ) === 0 )
        {
            sscanf( $uri, "$uriElements%s", $uri );
        }
        return $uri;
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement::getName ()
Returns the matcher's name. This information will be stored in the SiteAccess object itself to quickly be able to identify the matcher type.
Returns
string
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 84 of file URIElement.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement\getName().
    {
        return 'uri:element';
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement::getURIElements () protected
Returns URI elements as an array.
Exceptions
\LogicException
Returns
array
Definition at line 63 of file URIElement.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement\getURIElements().
    {
        $elements = array_slice(
            explode( "/", $this->request->pathinfo ),
            1,
            $this->elementNumber
        );
        // If one of the elements is empty, we do not match.
        foreach ( $elements as $element )
        {
            if ( $element === "" )
                throw new \LogicException( 'One of the URI elements was empty' );
        }
        if ( count( $elements ) !== $this->elementNumber )
            throw new \LogicException( 'The number of provided elements to consider is different than the number of elements found in the URI' );
        return $elements;
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement::match ()
Returns matching Siteaccess.
Returns
string|false Siteaccess matched or false.
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 45 of file URIElement.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement\getURIElements(), and eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement\match().
    {
        try
        {
            return implode( "_", $this->getURIElements() );
        }
        catch ( \LogicException $e )
        {
            return false;
        }
    }
eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement::setRequest (SimplifiedRequest $request)
Injects the request object to match against.
Parameters
\eZ\Publish\Core\MVC\Symfony\Routing\SimplifiedRequest $request
Returns
void
Implements eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher.
Definition at line 96 of file URIElement.php.
References eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement\setRequest().
    {
        $this->request = $request;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/URIElement.php