ezp-next: eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer Class Reference
eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer Class Reference
Public Member Functions
__construct (FieldTypeService $fieldTypeService, FieldTypeProcessorRegistry $fieldTypeProcessorRegistry)
serializeFieldValue (Generator $generator, ContentType $contentType, Field $field)
serializeFieldDefaultValue (Generator $generator, FieldDefinition $fieldDefinition, $defaultValue)
serializeFieldSettings (Generator $generator, FieldDefinition $fieldDefinition, $settings)
serializeValidatorConfiguration (Generator $generator, FieldDefinition $fieldDefinition, $validatorConfiguration)
Protected Member Functions
getFieldType ($fieldTypeIdentifier)
serializeValue ($elementName, Generator $generator, FieldType $fieldType, $value)
serializeHash ($elementName, Generator $generator, $hash)
Protected Attributes
$fieldTypeService
$fieldTypeProcessorRegistry
Detailed Description
Serializes FieldType related data for REST output.
Definition at line 23 of file FieldTypeSerializer.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer::__construct (FieldTypeService $fieldTypeService, FieldTypeProcessorRegistry $fieldTypeProcessorRegistry)
Parameters
\eZ\Publish\API\Repository\FieldTypeService $fieldTypeService
\eZ\Publish\Core\REST\Common\FieldTypeProcessorRegistry $fieldTypeProcessorRegistry
Definition at line 41 of file FieldTypeSerializer.php.
References eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer\$fieldTypeProcessorRegistry, and eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer\$fieldTypeService.
    {
        $this->fieldTypeService = $fieldTypeService;
        $this->fieldTypeProcessorRegistry = $fieldTypeProcessorRegistry;
    }
Member Function Documentation
eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer::getFieldType ($fieldTypeIdentifier) protected
Returns the field type with $fieldTypeIdentifier
Parameters
string $fieldTypeIdentifier
Returns
Definition at line 127 of file FieldTypeSerializer.php.
    {
        return $this->fieldTypeService->getFieldType(
            $fieldTypeIdentifier
        );
    }
eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer::serializeFieldDefaultValue (Generator $generator, FieldDefinition $fieldDefinition, $defaultValue)
Serializes the $defaultValue for $fieldDefIdentifier through $generator
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator $generator
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition
mixed $defaultValue
Definition at line 73 of file FieldTypeSerializer.php.
References eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer\getFieldType(), and eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer\serializeValue().
    {
        $this->serializeValue(
            'defaultValue',
            $generator,
            $this->getFieldType( $fieldDefinition->fieldTypeIdentifier ),
            $defaultValue
        );
    }
eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer::serializeFieldSettings (Generator $generator, FieldDefinition $fieldDefinition, $settings)
Serializes $settings as fieldSettings for $fieldDefinition using $generator
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator $generator
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition
mixed $settings
Definition at line 91 of file FieldTypeSerializer.php.
References eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer\getFieldType(), and eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer\serializeHash().
    {
        $this->serializeHash(
            'fieldSettings',
            $generator,
            $this->getFieldType(
                $fieldDefinition->fieldTypeIdentifier
            )->fieldSettingsToHash( $settings )
        );
    }
eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer::serializeFieldValue (Generator $generator, ContentType $contentType, Field $field)
Serializes the field value of $field through $generator
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator $generator
\eZ\Publish\API\Repository\Values\ContentType\ContentType $contentType
\eZ\Publish\API\Repository\Values\Content\Field $field
Definition at line 54 of file FieldTypeSerializer.php.
References eZ\Publish\API\Repository\Values\ContentType\ContentType\getFieldDefinition(), and eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer\serializeValue().
    {
        $this->serializeValue(
            'fieldValue',
            $generator,
            $this->fieldTypeService->getFieldType(
                $contentType->getFieldDefinition( $field->fieldDefIdentifier )->fieldTypeIdentifier
            ),
            $field->value
        );
    }
eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer::serializeHash ($elementName, Generator $generator, $hash) protected
Serializes the given $hash with $generator into $elementName
Parameters
string $elementName
\eZ\Publish\Core\REST\Common\Output\Generator $generator
mixed $hash
Definition at line 164 of file FieldTypeSerializer.php.
References eZ\Publish\Core\REST\Common\Output\Generator\generateFieldTypeHash().
    {
        $generator->generateFieldTypeHash( $elementName, $hash );
    }
eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer::serializeValidatorConfiguration (Generator $generator, FieldDefinition $fieldDefinition, $validatorConfiguration)
Serializes $validatorConfiguration for $fieldDefinition using $generator
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator $generator
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition
mixed $validatorConfiguration
Definition at line 109 of file FieldTypeSerializer.php.
References eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer\getFieldType(), and eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer\serializeHash().
    {
        $this->serializeHash(
            'validatorConfiguration',
            $generator,
            $this->getFieldType(
                $fieldDefinition->fieldTypeIdentifier
            )->validatorConfigurationToHash( $validatorConfiguration )
        );
    }
eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer::serializeValue ($elementName, Generator $generator, FieldType $fieldType, $value) protected
Serializes the given $value for $fieldType with $generator into $elementName
Parameters
string $elementName
\eZ\Publish\Core\REST\Common\Output\Generator $generator
\eZ\Publish\API\Repository\FieldType $fieldType
mixed $value
Definition at line 143 of file FieldTypeSerializer.php.
References eZ\Publish\API\Repository\FieldType\getFieldTypeIdentifier(), eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer\serializeHash(), and eZ\Publish\API\Repository\FieldType\toHash().
    {
        $hash = $fieldType->toHash( $value );
        $fieldTypeIdentifier = $fieldType->getFieldTypeIdentifier();
        if ( $this->fieldTypeProcessorRegistry->hasProcessor( $fieldTypeIdentifier ) )
        {
            $processor = $this->fieldTypeProcessorRegistry->getProcessor( $fieldTypeIdentifier );
            $hash = $processor->postProcessHash( $hash );
        }
        $this->serializeHash( $elementName, $generator, $hash );
    }
Member Data Documentation
eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer::$fieldTypeProcessorRegistry protected
Definition at line 35 of file FieldTypeSerializer.php.
eZ\Publish\Core\REST\Common\Output\FieldTypeSerializer::$fieldTypeService protected
Definition at line 30 of file FieldTypeSerializer.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/Output/FieldTypeSerializer.php