ezp-next: eZ\Publish\Core\FieldType\Integer\Type Class Reference
eZ\Publish\Core\FieldType\Integer\Type Class Reference
Public Member Functions
validateValidatorConfiguration ($validatorConfiguration)
validate (FieldDefinition $fieldDefinition, $fieldValue)
getFieldTypeIdentifier ()
getName ($value)
getEmptyValue ()
isEmptyValue ($value)
fromHash ($hash)
toHash ($value)
isSearchable ()
Public Member Functions inherited from eZ\Publish\Core\FieldType\FieldType
getSettingsSchema ()
getValidatorConfigurationSchema ()
validateFieldSettings ($fieldSettings)
toPersistenceValue ($value)
fromPersistenceValue (FieldValue $fieldValue)
acceptValue ($inputValue)
fieldSettingsToHash ($fieldSettings)
fieldSettingsFromHash ($fieldSettingsHash)
validatorConfigurationToHash ($validatorConfiguration)
validatorConfigurationFromHash ($validatorConfigurationHash)
getRelations ($fieldValue)
Protected Member Functions
internalAcceptValue ($inputValue)
getSortInfo ($value)
Protected Attributes
$validatorConfigurationSchema
Protected Attributes inherited from eZ\Publish\Core\FieldType\FieldType
$settingsSchema = array()
$validatorConfigurationSchema = array()
Detailed Description
Integer field types
Represents integers.
Definition at line 22 of file Type.php.
Member Function Documentation
eZ\Publish\Core\FieldType\Integer\Type::fromHash ($hash)
Converts an $hash to the Value defined by the field type
Parameters
mixed $hash
Returns
$value
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 245 of file Type.php.
    {
        if ( $hash === null )
        {
            return null;
        }
        return new Value( $hash );
    }
eZ\Publish\Core\FieldType\Integer\Type::getEmptyValue ()
Returns the fallback default value of field type when no such default value is provided in the field definition in content types.
Returns
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 173 of file Type.php.
    {
        return new Value;
    }
eZ\Publish\Core\FieldType\Integer\Type::getFieldTypeIdentifier ()
Returns the field type identifier for this field type
Returns
string
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 145 of file Type.php.
    {
        return 'ezinteger';
    }
eZ\Publish\Core\FieldType\Integer\Type::getName ($value)
Returns the name of the given field value.
It will be used to generate content name and url alias if current field is designated to be used in the content name/urlAlias pattern.
Parameters
mixed $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 160 of file Type.php.
References eZ\Publish\Core\FieldType\FieldType\acceptValue().
    {
        $value = $this->acceptValue( $value );
        return (string)$value->value;
    }
eZ\Publish\Core\FieldType\Integer\Type::getSortInfo ($value) protected
Returns information for FieldValue->$sortKey relevant to the field type.
Returns
array
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 229 of file Type.php.
    {
        if ( $value === null )
        {
            return null;
        }
        return $value->value;
    }
eZ\Publish\Core\FieldType\Integer\Type::internalAcceptValue ($inputValue) protected
Implements the core of {
See Also
acceptValue()}.
Parameters
mixed $inputValue
Returns
The potentially converted and structurally plausible value.
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 197 of file Type.php.
    {
        if ( is_int( $inputValue ) )
        {
            $inputValue = new Value( $inputValue );
        }
        else if ( !$inputValue instanceof Value )
        {
            throw new InvalidArgumentType(
                '$inputValue',
                'eZ\\Publish\\Core\\FieldType\\Integer\\Value',
                $inputValue
            );
        }
        if ( !is_integer( $inputValue->value ) )
        {
            throw new InvalidArgumentType(
                '$inputValue->value',
                'integer',
                $inputValue->value
            );
        }
        return $inputValue;
    }
eZ\Publish\Core\FieldType\Integer\Type::isEmptyValue ($value)
Returns if the given $value is considered empty by the field type
Parameters
mixed $value
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 185 of file Type.php.
    {
        return $value === null || $value->value === null;
    }
eZ\Publish\Core\FieldType\Integer\Type::isSearchable ()
Returns whether the field type is searchable
Returns
boolean
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 275 of file Type.php.
    {
        return true;
    }
eZ\Publish\Core\FieldType\Integer\Type::toHash ($value)
Converts a $Value to a hash
Parameters
\eZ\Publish\Core\FieldType\Integer\Value $value
Returns
mixed
Implements eZ\Publish\API\Repository\FieldType.
Definition at line 261 of file Type.php.
References eZ\Publish\Core\FieldType\Integer\Type\isEmptyValue().
    {
        if ( $this->isEmptyValue( $value ) )
        {
            return null;
        }
        return $value->value;
    }
eZ\Publish\Core\FieldType\Integer\Type::validate (FieldDefinition $fieldDefinition, $fieldValue)
Validates a field based on the validators in the field definition
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException
Parameters
\eZ\Publish\API\Repository\Values\ContentType\FieldDefinition $fieldDefinition The field definition of the field
\eZ\Publish\Core\FieldType\Value $fieldValue The field value for which an action is performed
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 104 of file Type.php.
References eZ\Publish\API\Repository\Values\ContentType\FieldDefinition\getValidatorConfiguration().
    {
        $validatorConfiguration = $fieldDefinition->getValidatorConfiguration();
        $constraints = isset($validatorConfiguration['IntegerValueValidator']) ?
            $validatorConfiguration['IntegerValueValidator'] :
            array();
        $validationErrors = array();
        if ( isset( $constraints['maxIntegerValue'] ) &&
            $constraints['maxIntegerValue'] !== false && $fieldValue->value > $constraints['maxIntegerValue'] )
        {
            $validationErrors[] = new ValidationError(
                "The value can not be higher than %size%.",
                null,
                array(
                    "size" => $constraints['maxIntegerValue']
                )
            );
        }
        if ( isset( $constraints['minIntegerValue'] ) &&
            $constraints['minIntegerValue'] !== false && $fieldValue->value < $constraints['minIntegerValue'] )
        {
            $validationErrors[] = new ValidationError(
                "The value can not be lower than %size%.",
                null,
                array(
                    "size" => $constraints['minIntegerValue']
                )
            );
        }
        return $validationErrors;
    }
eZ\Publish\Core\FieldType\Integer\Type::validateValidatorConfiguration ($validatorConfiguration)
Validates the validatorConfiguration of a FieldDefinitionCreateStruct or FieldDefinitionUpdateStruct
Parameters
mixed $validatorConfiguration
Returns
[]
Reimplemented from eZ\Publish\Core\FieldType\FieldType.
Definition at line 44 of file Type.php.
    {
        $validationErrors = array();
        foreach ( (array)$validatorConfiguration as $validatorIdentifier => $constraints )
        {
            if ( $validatorIdentifier !== 'IntegerValueValidator' )
            {
                $validationErrors[] = new ValidationError(
                    "Validator '%validator%' is unknown",
                    null,
                    array(
                        "validator" => $validatorIdentifier
                    )
                );
                continue;
            }
            foreach ( $constraints as $name => $value )
            {
                switch ( $name )
                {
                    case "minIntegerValue":
                    case "maxIntegerValue":
                        if ( $value !== false && !is_integer( $value ) )
{
                            $validationErrors[] = new ValidationError(
                                "Validator parameter '%parameter%' value must be of integer type",
                                null,
                                array(
                                    "parameter" => $name
                                )
                            );
                        }
                        break;
                    default:
                        $validationErrors[] = new ValidationError(
                            "Validator parameter '%parameter%' is unknown",
                            null,
                            array(
                                "parameter" => $name
                            )
                        );
                }
            }
        }
        return $validationErrors;
    }
Member Data Documentation
eZ\Publish\Core\FieldType\Integer\Type::$validatorConfigurationSchema protected
Initial value:
 array(
        'IntegerValueValidator' => array(
            'minIntegerValue' => array(
                'type' => 'int',
                'default' => 0
            ),
            'maxIntegerValue' => array(
                'type' => 'int',
                'default' => false
            )
        )
    )
Definition at line 24 of file Type.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/FieldType/Integer/Type.php