ezp-next: eZ\Publish\Core\Repository\SectionService Class Reference
eZ\Publish\Core\Repository\SectionService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, Handler $sectionHandler, array $settings=array())
createSection (SectionCreateStruct $sectionCreateStruct)
updateSection (Section $section, SectionUpdateStruct $sectionUpdateStruct)
loadSection ($sectionId)
loadSections ()
loadSectionByIdentifier ($sectionIdentifier)
countAssignedContents (Section $section)
assignSection (ContentInfo $contentInfo, Section $section)
deleteSection (Section $section)
newSectionCreateStruct ()
newSectionUpdateStruct ()
Protected Member Functions
buildDomainSectionObject (SPISection $spiSection)
Protected Attributes
$repository
$sectionHandler
$settings
Detailed Description
Definition at line 32 of file SectionService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\SectionService::__construct (RepositoryInterface $repository, Handler $sectionHandler, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\API\Repository\Repository $repository
\eZ\Publish\SPI\Persistence\Content\Section\Handler $sectionHandler
array $settings
Definition at line 56 of file SectionService.php.
References eZ\Publish\Core\Repository\SectionService\$repository, eZ\Publish\Core\Repository\SectionService\$sectionHandler, and eZ\Publish\Core\Repository\SectionService\$settings.
    {
        $this->repository = $repository;
        $this->sectionHandler = $sectionHandler;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            //'defaultSetting' => array(),
        );
    }
Member Function Documentation
eZ\Publish\Core\Repository\SectionService::assignSection (ContentInfo $contentInfo, Section $section)
Assigns the content to the given section this method overrides the current assigned section
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If user does not have access to view provided object
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
\eZ\Publish\API\Repository\Values\Content\Section $section
Implements eZ\Publish\API\Repository\SectionService.
Definition at line 267 of file SectionService.php.
References eZ\Publish\Core\Repository\SectionService\loadSection().
    {
        if ( !is_numeric( $contentInfo->id ) )
            throw new InvalidArgumentValue( "id", $contentInfo->id, "ContentInfo" );
        if ( !is_numeric( $section->id ) )
            throw new InvalidArgumentValue( "id", $section->id, "Section" );
        $loadedContentInfo = $this->repository->getContentService()->loadContentInfo( $contentInfo->id );
        $loadedSection = $this->loadSection( $section->id );
        if ( $this->repository->canUser( 'section', 'assign', $loadedContentInfo, $loadedSection ) !== true )
        {
            throw new UnauthorizedException(
                'section', 'assign',
                array(
                    'name' => $loadedSection->name,
                    'content-name' => $loadedContentInfo->name
                )
            );
        }
        $this->repository->beginTransaction();
        try
        {
            $this->sectionHandler->assign(
                $loadedSection->id,
                $loadedContentInfo->id
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\SectionService::buildDomainSectionObject (SPISection $spiSection) protected
Builds API Section object from provided SPI Section object
Parameters
\eZ\Publish\SPI\Persistence\Content\Section $spiSection
Returns
Definition at line 368 of file SectionService.php.
    {
        return new Section(
            array(
                'id' => (int)$spiSection->id,
                'identifier' => $spiSection->identifier,
                'name' => $spiSection->name
            )
        );
    }
eZ\Publish\Core\Repository\SectionService::countAssignedContents (Section $section)
Counts the contents which $section is assigned to
Parameters
\eZ\Publish\API\Repository\Values\Content\Section $section
Returns
int
Implements eZ\Publish\API\Repository\SectionService.
Definition at line 250 of file SectionService.php.
    {
        if ( !is_numeric( $section->id ) )
            throw new InvalidArgumentValue( "id", $section->id, "Section" );
        return $this->sectionHandler->assignmentsCount( $section->id );
    }
eZ\Publish\Core\Repository\SectionService::createSection (SectionCreateStruct $sectionCreateStruct)
Creates a new Section in the content repository
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to create a section
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the new identifier in $sectionCreateStruct already exists
Parameters
\eZ\Publish\API\Repository\Values\Content\SectionCreateStruct $sectionCreateStruct
Returns
The newly created section
Implements eZ\Publish\API\Repository\SectionService.
Definition at line 76 of file SectionService.php.
References eZ\Publish\Core\Repository\SectionService\buildDomainSectionObject(), and eZ\Publish\Core\Repository\SectionService\loadSectionByIdentifier().
    {
        if ( !is_string( $sectionCreateStruct->name ) || empty( $sectionCreateStruct->name ) )
            throw new InvalidArgumentValue( "name", $sectionCreateStruct->name, "SectionCreateStruct" );
        if ( !is_string( $sectionCreateStruct->identifier ) || empty( $sectionCreateStruct->identifier ) )
            throw new InvalidArgumentValue( "identifier", $sectionCreateStruct->identifier, "SectionCreateStruct" );
        if ( $this->repository->hasAccess( 'section', 'edit' ) !== true )
            throw new UnauthorizedException( 'section', 'edit' );
        try
        {
            $existingSection = $this->loadSectionByIdentifier( $sectionCreateStruct->identifier );
            if ( $existingSection !== null )
                throw new InvalidArgumentException( "sectionCreateStruct", "section with specified identifier already exists" );
        }
        catch ( APINotFoundException $e )
        {
            // Do nothing
        }
        $this->repository->beginTransaction();
        try
        {
            $spiSection = $this->sectionHandler->create(
                $sectionCreateStruct->name,
                $sectionCreateStruct->identifier
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainSectionObject( $spiSection );
    }
eZ\Publish\Core\Repository\SectionService::deleteSection (Section $section)
Deletes $section from content repository
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If the specified section is not found
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user is not allowed to delete a section
\eZ\Publish\API\Repository\Exceptions\BadStateException If section can not be deleted because it is still assigned to some contents.
Parameters
\eZ\Publish\API\Repository\Values\Content\Section $section
Implements eZ\Publish\API\Repository\SectionService.
Definition at line 315 of file SectionService.php.
References eZ\Publish\Core\Repository\SectionService\countAssignedContents(), and eZ\Publish\Core\Repository\SectionService\loadSection().
    {
        if ( !is_numeric( $section->id ) )
            throw new InvalidArgumentValue( "id", $section->id, "Section" );
        $loadedSection = $this->loadSection( $section->id );
        if ( $this->repository->canUser( 'section', 'edit', $loadedSection ) !== true )
            throw new UnauthorizedException( 'section', 'edit', array( 'name' => $loadedSection->name ) );
        if ( $this->countAssignedContents( $loadedSection ) > 0 )
            throw new BadStateException( "section", 'section is still assigned to content' );
        $this->repository->beginTransaction();
        try
        {
            $this->sectionHandler->delete( $loadedSection->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\SectionService::loadSection ($sectionId)
Loads a Section from its id ($sectionId)
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if section could not be found
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to read a section
Parameters
int $sectionId
Returns
Implements eZ\Publish\API\Repository\SectionService.
Definition at line 186 of file SectionService.php.
References eZ\Publish\Core\Repository\SectionService\buildDomainSectionObject().
    {
        if ( !is_numeric( $sectionId ) )
            throw new InvalidArgumentValue( "sectionId", $sectionId );
        if ( $this->repository->hasAccess( 'section', 'view' ) !== true )
            throw new UnauthorizedException( 'section', 'view' );
        $spiSection = $this->sectionHandler->load( $sectionId );
        return $this->buildDomainSectionObject( $spiSection );
    }
eZ\Publish\Core\Repository\SectionService::loadSectionByIdentifier ($sectionIdentifier)
Loads a Section from its identifier ($sectionIdentifier)
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if section could not be found
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to read a section
Parameters
string $sectionIdentifier
Returns
Implements eZ\Publish\API\Repository\SectionService.
Definition at line 231 of file SectionService.php.
References eZ\Publish\Core\Repository\SectionService\buildDomainSectionObject().
    {
        if ( !is_string( $sectionIdentifier ) || empty( $sectionIdentifier ) )
            throw new InvalidArgumentValue( "sectionIdentifier", $sectionIdentifier );
        if ( $this->repository->hasAccess( 'section', 'view' ) !== true )
            throw new UnauthorizedException( 'section', 'view' );
        $spiSection = $this->sectionHandler->loadByIdentifier( $sectionIdentifier );
        return $this->buildDomainSectionObject( $spiSection );
    }
eZ\Publish\Core\Repository\SectionService::loadSections ()
Loads all sections
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to read a section
Returns
[]
Implements eZ\Publish\API\Repository\SectionService.
Definition at line 205 of file SectionService.php.
References eZ\Publish\Core\Repository\SectionService\buildDomainSectionObject().
    {
        if ( $this->repository->hasAccess( 'section', 'view' ) !== true )
            throw new UnauthorizedException( 'section', 'view' );
        $spiSections = $this->sectionHandler->loadAll();
        $sections = array();
        foreach ( $spiSections as $spiSection )
        {
            $sections[] = $this->buildDomainSectionObject( $spiSection );
        }
        return $sections;
    }
eZ\Publish\Core\Repository\SectionService::newSectionCreateStruct ()
Instantiates a new SectionCreateStruct
Returns
Implements eZ\Publish\API\Repository\SectionService.
Definition at line 346 of file SectionService.php.
    {
        return new SectionCreateStruct();
    }
eZ\Publish\Core\Repository\SectionService::newSectionUpdateStruct ()
Instantiates a new SectionUpdateStruct
Returns
Implements eZ\Publish\API\Repository\SectionService.
Definition at line 356 of file SectionService.php.
    {
        return new SectionUpdateStruct();
    }
eZ\Publish\Core\Repository\SectionService::updateSection (Section $section, SectionUpdateStruct $sectionUpdateStruct)
Updates the given section in the content repository
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If the current user user is not allowed to create a section
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the new identifier already exists (if set in the update struct)
Parameters
\eZ\Publish\API\Repository\Values\Content\Section $section
\eZ\Publish\API\Repository\Values\Content\SectionUpdateStruct $sectionUpdateStruct
Returns
Implements eZ\Publish\API\Repository\SectionService.
Definition at line 127 of file SectionService.php.
References eZ\Publish\Core\Repository\SectionService\buildDomainSectionObject(), eZ\Publish\Core\Repository\SectionService\loadSection(), and eZ\Publish\Core\Repository\SectionService\loadSectionByIdentifier().
    {
        if ( !is_numeric( $section->id ) )
            throw new InvalidArgumentValue( "id", $section->id, "Section" );
        if ( $sectionUpdateStruct->name !== null && !is_string( $sectionUpdateStruct->name ) )
            throw new InvalidArgumentValue( "name", $section->name, "Section" );
        if ( $sectionUpdateStruct->identifier !== null && !is_string( $sectionUpdateStruct->identifier ) )
            throw new InvalidArgumentValue( "identifier", $section->identifier, "Section" );
        if ( $this->repository->canUser( 'section', 'edit', $section ) !== true )
            throw new UnauthorizedException( 'section', 'edit' );
        if ( $sectionUpdateStruct->identifier !== null )
        {
            try
            {
                $existingSection = $this->loadSectionByIdentifier( $sectionUpdateStruct->identifier );
                if ( $existingSection !== null )
                    throw new InvalidArgumentException( "sectionUpdateStruct", "section with specified identifier already exists" );
            }
            catch ( APINotFoundException $e )
            {
                // Do nothing
            }
        }
        $loadedSection = $this->loadSection( $section->id );
        $this->repository->beginTransaction();
        try
        {
            $spiSection = $this->sectionHandler->update(
                $loadedSection->id,
                $sectionUpdateStruct->name ?: $loadedSection->name,
                $sectionUpdateStruct->identifier ?: $loadedSection->identifier
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainSectionObject( $spiSection );
    }
Member Data Documentation
eZ\Publish\Core\Repository\SectionService::$repository protected
Definition at line 37 of file SectionService.php.
eZ\Publish\Core\Repository\SectionService::$sectionHandler protected
Definition at line 42 of file SectionService.php.
eZ\Publish\Core\Repository\SectionService::$settings protected
Definition at line 47 of file SectionService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/SectionService.php