ezp-next: eZ\Publish\Core\Repository\LanguageService Class Reference
eZ\Publish\Core\Repository\LanguageService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, Handler $languageHandler, array $settings=array())
createLanguage (LanguageCreateStruct $languageCreateStruct)
updateLanguageName (Language $language, $newName)
enableLanguage (Language $language)
disableLanguage (Language $language)
loadLanguage ($languageCode)
loadLanguages ()
loadLanguageById ($languageId)
deleteLanguage (Language $language)
getDefaultLanguageCode ()
getPrioritizedLanguageCodeList ()
newLanguageCreateStruct ()
Protected Member Functions
buildDomainObject (SPILanguage $spiLanguage)
Protected Attributes
$repository
$languageHandler
$settings
Detailed Description
Definition at line 31 of file LanguageService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\LanguageService::__construct (RepositoryInterface $repository, Handler $languageHandler, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\API\Repository\Repository $repository
\eZ\Publish\SPI\Persistence\Content\Language\Handler $languageHandler
array $settings
Definition at line 55 of file LanguageService.php.
References eZ\Publish\Core\Repository\LanguageService\$languageHandler, eZ\Publish\Core\Repository\LanguageService\$repository, and eZ\Publish\Core\Repository\LanguageService\$settings.
    {
        $this->repository = $repository;
        $this->languageHandler = $languageHandler;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            'languages' => array( 'eng-GB' ),
        );
    }
Member Function Documentation
eZ\Publish\Core\Repository\LanguageService::buildDomainObject (SPILanguage $spiLanguage) protected
Builds Language domain object from ValueObject returned by Persistence API
Parameters
\eZ\Publish\SPI\Persistence\Content\Language $spiLanguage
Returns
Definition at line 393 of file LanguageService.php.
    {
        return new Language(
            array(
                'id' => $spiLanguage->id,
                'languageCode' => $spiLanguage->languageCode,
                'name' => $spiLanguage->name,
                'enabled' => $spiLanguage->isEnabled
            )
        );
    }
eZ\Publish\Core\Repository\LanguageService::createLanguage (LanguageCreateStruct $languageCreateStruct)
Creates the a new Language in the content repository
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If user does not have access to content translations
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the languageCode already exists
Parameters
\eZ\Publish\API\Repository\Values\Content\LanguageCreateStruct $languageCreateStruct
Returns
Implements eZ\Publish\API\Repository\LanguageService.
Definition at line 75 of file LanguageService.php.
References eZ\Publish\Core\Repository\LanguageService\buildDomainObject(), and eZ\Publish\Core\Repository\LanguageService\loadLanguage().
    {
        if ( !is_string( $languageCreateStruct->name ) || empty( $languageCreateStruct->name ) )
            throw new InvalidArgumentValue( "name", $languageCreateStruct->name, "LanguageCreateStruct" );
        if ( !is_string( $languageCreateStruct->languageCode ) || empty( $languageCreateStruct->languageCode ) )
            throw new InvalidArgumentValue( "languageCode", $languageCreateStruct->languageCode, "LanguageCreateStruct" );
        if ( !is_bool( $languageCreateStruct->enabled ) )
            throw new InvalidArgumentValue( "enabled", $languageCreateStruct->enabled, "LanguageCreateStruct" );
        if ( $this->repository->hasAccess( 'content', 'translations' ) !== true )
            throw new UnauthorizedException( 'content', 'translations' );
        try
        {
            if ( $this->loadLanguage( $languageCreateStruct->languageCode ) !== null )
                throw new InvalidArgumentException( "languageCreateStruct", "language with specified language code already exists" );
        }
        catch ( APINotFoundException $e )
        {
            // Do nothing
        }
        $createStruct = new CreateStruct(
            array(
                'languageCode' => $languageCreateStruct->languageCode,
                'name' => $languageCreateStruct->name,
                'isEnabled' => $languageCreateStruct->enabled
            )
        );
        $this->repository->beginTransaction();
        try
        {
            $createdLanguage = $this->languageHandler->create( $createStruct );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainObject( $createdLanguage );
    }
eZ\Publish\Core\Repository\LanguageService::deleteLanguage (Language $language)
Deletes a language from content repository
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if language can not be deleted because it is still assigned to some content / type / (...).
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If user does not have access to content translations
Parameters
\eZ\Publish\API\Repository\Values\Content\Language $language
Implements eZ\Publish\API\Repository\LanguageService.
Definition at line 326 of file LanguageService.php.
References eZ\Publish\Core\Repository\LanguageService\loadLanguageById().
    {
        if ( !is_numeric( $language->id ) )
            throw new InvalidArgumentValue( "id", $language->id, "Language" );
        if ( $this->repository->hasAccess( 'content', 'translations' ) !== true )
            throw new UnauthorizedException( 'content', 'translations' );
        $loadedLanguage = $this->loadLanguageById( $language->id );
        $this->repository->beginTransaction();
        try
        {
            $this->languageHandler->delete( $loadedLanguage->id );
            $this->repository->commit();
        }
        catch ( LogicException $e )
        {
            $this->repository->rollback();
            throw new InvalidArgumentException( "language", $e->getMessage(), $e );
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\LanguageService::disableLanguage (Language $language)
Disables a language
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If user does not have access to content translations
Parameters
\eZ\Publish\API\Repository\Values\Content\Language $language
Returns
Implements eZ\Publish\API\Repository\LanguageService.
Definition at line 223 of file LanguageService.php.
References eZ\Publish\Core\Repository\LanguageService\loadLanguageById().
    {
        if ( !is_numeric( $language->id ) )
            throw new InvalidArgumentValue( "id", $language->id );
        if ( $this->repository->hasAccess( 'content', 'translations' ) !== true )
            throw new UnauthorizedException( 'content', 'translations' );
        $loadedLanguage = $this->loadLanguageById( $language->id );
        $updateLanguageStruct = new SPILanguage(
            array(
                'id' => $loadedLanguage->id,
                'languageCode' => $loadedLanguage->languageCode,
                'name' => $loadedLanguage->name,
                'isEnabled' => false
            )
        );
        $this->repository->beginTransaction();
        try
        {
            $this->languageHandler->update( $updateLanguageStruct );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->loadLanguageById( $loadedLanguage->id );
    }
eZ\Publish\Core\Repository\LanguageService::enableLanguage (Language $language)
Enables a language
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If user does not have access to content translations
Parameters
\eZ\Publish\API\Repository\Values\Content\Language $language
Returns
Implements eZ\Publish\API\Repository\LanguageService.
Definition at line 180 of file LanguageService.php.
References eZ\Publish\Core\Repository\LanguageService\loadLanguageById().
    {
        if ( !is_numeric( $language->id ) )
            throw new InvalidArgumentValue( "id", $language->id );
        if ( $this->repository->hasAccess( 'content', 'translations' ) !== true )
            throw new UnauthorizedException( 'content', 'translations' );
        $loadedLanguage = $this->loadLanguageById( $language->id );
        $updateLanguageStruct = new SPILanguage(
            array(
                'id' => $loadedLanguage->id,
                'languageCode' => $loadedLanguage->languageCode,
                'name' => $loadedLanguage->name,
                'isEnabled' => true
            )
        );
        $this->repository->beginTransaction();
        try
        {
            $this->languageHandler->update( $updateLanguageStruct );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->loadLanguageById( $loadedLanguage->id );
    }
eZ\Publish\Core\Repository\LanguageService::getDefaultLanguageCode ()
Returns a configured default language code
Returns
string
Implements eZ\Publish\API\Repository\LanguageService.
Definition at line 359 of file LanguageService.php.
    {
        return $this->settings['languages'][0];
    }
eZ\Publish\Core\Repository\LanguageService::getPrioritizedLanguageCodeList ()
Returns a configured list of prioritized languageCodes
private This is currently only for internal use in Services
Returns
string[]
Definition at line 371 of file LanguageService.php.
    {
        return $this->settings['languages'];
    }
eZ\Publish\Core\Repository\LanguageService::loadLanguage ($languageCode)
Loads a Language from its language code ($languageCode)
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if languageCode argument is not string
\eZ\Publish\API\Repository\Exceptions\NotFoundException if language could not be found
Parameters
string $languageCode
Returns
Implements eZ\Publish\API\Repository\LanguageService.
Definition at line 268 of file LanguageService.php.
References eZ\Publish\Core\Repository\LanguageService\buildDomainObject().
    {
        if ( !is_string( $languageCode ) || empty( $languageCode ) )
            throw new InvalidArgumentException( "languageCode", "language code has an invalid value" );
        $language = $this->languageHandler->loadByLanguageCode( $languageCode );
        return $this->buildDomainObject( $language );
    }
eZ\Publish\Core\Repository\LanguageService::loadLanguageById ($languageId)
Loads a Language by its id ($languageId)
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if languageId argument is not integer
\eZ\Publish\API\Repository\Exceptions\NotFoundException if language could not be found
Parameters
int $languageId
Returns
Implements eZ\Publish\API\Repository\LanguageService.
Definition at line 306 of file LanguageService.php.
References eZ\Publish\Core\Repository\LanguageService\buildDomainObject().
    {
        if ( !is_numeric( $languageId ) )
            throw new InvalidArgumentValue( "languageId", $languageId );
        $language = $this->languageHandler->load( (int)$languageId );
        return $this->buildDomainObject( $language );
    }
eZ\Publish\Core\Repository\LanguageService::loadLanguages ()
Loads all Languages
Returns
[]
Implements eZ\Publish\API\Repository\LanguageService.
Definition at line 282 of file LanguageService.php.
References eZ\Publish\Core\Repository\LanguageService\buildDomainObject().
    {
        $languages = $this->languageHandler->loadAll();
        $returnArray = array();
        foreach ( $languages as $language )
        {
            $returnArray[] = $this->buildDomainObject( $language );
        }
        return $returnArray;
    }
eZ\Publish\Core\Repository\LanguageService::newLanguageCreateStruct ()
Instantiates an object to be used for creating languages
Returns
Implements eZ\Publish\API\Repository\LanguageService.
Definition at line 381 of file LanguageService.php.
    {
        return new LanguageCreateStruct();
    }
eZ\Publish\Core\Repository\LanguageService::updateLanguageName (Language $language, $newName)
Changes the name of the language in the content repository
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if languageCode argument is not string
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException If user does not have access to content translations
Parameters
\eZ\Publish\API\Repository\Values\Content\Language $language
string $newName
Returns
Implements eZ\Publish\API\Repository\LanguageService.
Definition at line 134 of file LanguageService.php.
References eZ\Publish\Core\Repository\LanguageService\loadLanguageById().
    {
        if ( !is_numeric( $language->id ) )
            throw new InvalidArgumentValue( "id", $language->id, "Language" );
        if ( !is_string( $newName ) || empty( $newName ) )
            throw new InvalidArgumentValue( "newName", $newName );
        if ( $this->repository->hasAccess( 'content', 'translations' ) !== true )
            throw new UnauthorizedException( 'content', 'translations' );
        $loadedLanguage = $this->loadLanguageById( $language->id );
        $updateLanguageStruct = new SPILanguage(
            array(
                'id' => $loadedLanguage->id,
                'languageCode' => $loadedLanguage->languageCode,
                'name' => $newName,
                'isEnabled' => $loadedLanguage->enabled
            )
        );
        $this->repository->beginTransaction();
        try
        {
            $this->languageHandler->update( $updateLanguageStruct );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->loadLanguageById( $loadedLanguage->id );
    }
Member Data Documentation
eZ\Publish\Core\Repository\LanguageService::$languageHandler protected
Definition at line 41 of file LanguageService.php.
eZ\Publish\Core\Repository\LanguageService::$repository protected
Definition at line 36 of file LanguageService.php.
eZ\Publish\Core\Repository\LanguageService::$settings protected
Definition at line 46 of file LanguageService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/LanguageService.php