ezp-next: eZ\Publish\Core\Repository\ObjectStateService Class Reference
eZ\Publish\Core\Repository\ObjectStateService Class Reference
Public Member Functions
__construct (RepositoryInterface $repository, Handler $objectStateHandler, array $settings=array())
createObjectStateGroup (ObjectStateGroupCreateStruct $objectStateGroupCreateStruct)
loadObjectStateGroup ($objectStateGroupId)
loadObjectStateGroups ($offset=0, $limit=-1)
loadObjectStates (APIObjectStateGroup $objectStateGroup)
updateObjectStateGroup (APIObjectStateGroup $objectStateGroup, ObjectStateGroupUpdateStruct $objectStateGroupUpdateStruct)
deleteObjectStateGroup (APIObjectStateGroup $objectStateGroup)
createObjectState (APIObjectStateGroup $objectStateGroup, ObjectStateCreateStruct $objectStateCreateStruct)
loadObjectState ($stateId)
updateObjectState (APIObjectState $objectState, ObjectStateUpdateStruct $objectStateUpdateStruct)
setPriorityOfObjectState (APIObjectState $objectState, $priority)
deleteObjectState (APIObjectState $objectState)
setContentState (ContentInfo $contentInfo, APIObjectStateGroup $objectStateGroup, APIObjectState $objectState)
getContentState (ContentInfo $contentInfo, APIObjectStateGroup $objectStateGroup)
getContentCount (APIObjectState $objectState)
newObjectStateGroupCreateStruct ($identifier)
newObjectStateGroupUpdateStruct ()
newObjectStateCreateStruct ($identifier)
newObjectStateUpdateStruct ()
Public Member Functions inherited from eZ\Publish\API\Repository\ObjectStateService
loadObjectStates (ObjectStateGroup $objectStateGroup)
updateObjectStateGroup (ObjectStateGroup $objectStateGroup, ObjectStateGroupUpdateStruct $objectStateGroupUpdateStruct)
deleteObjectStateGroup (ObjectStateGroup $objectStateGroup)
createObjectState (ObjectStateGroup $objectStateGroup, ObjectStateCreateStruct $objectStateCreateStruct)
updateObjectState (ObjectState $objectState, ObjectStateUpdateStruct $objectStateUpdateStruct)
setPriorityOfObjectState (ObjectState $objectState, $priority)
deleteObjectState (ObjectState $objectState)
setContentState (ContentInfo $contentInfo, ObjectStateGroup $objectStateGroup, ObjectState $objectState)
getContentState (ContentInfo $contentInfo, ObjectStateGroup $objectStateGroup)
getContentCount (ObjectState $objectState)
Protected Member Functions
buildDomainObjectStateObject (SPIObjectState $spiObjectState, APIObjectStateGroup $objectStateGroup=null)
buildDomainObjectStateGroupObject (SPIObjectStateGroup $spiObjectStateGroup)
buildCreateInputStruct ($identifier, $defaultLanguageCode, $names, $descriptions)
buildObjectStateUpdateInputStruct (APIObjectState $objectState, $identifier, $defaultLanguageCode, $names, $descriptions)
buildObjectStateGroupUpdateInputStruct (APIObjectStateGroup $objectStateGroup, $identifier, $defaultLanguageCode, $names, $descriptions)
Protected Attributes
$repository
$objectStateHandler
$settings
Detailed Description
Definition at line 41 of file ObjectStateService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Repository\ObjectStateService::__construct (RepositoryInterface $repository, Handler $objectStateHandler, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\API\Repository\Repository $repository
\eZ\Publish\SPI\Persistence\Content\ObjectState\Handler $objectStateHandler
array $settings
Definition at line 65 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\$objectStateHandler, eZ\Publish\Core\Repository\ObjectStateService\$repository, and eZ\Publish\Core\Repository\ObjectStateService\$settings.
    {
        $this->repository = $repository;
        $this->objectStateHandler = $objectStateHandler;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            //'defaultSetting' => array(),
        );
    }
Member Function Documentation
eZ\Publish\Core\Repository\ObjectStateService::buildCreateInputStruct ($identifier, $defaultLanguageCode, $names, $descriptions) protected
Validates input for creating object states/groups and builds the InputStruct object
Parameters
string $identifier
string $defaultLanguageCode
string[] $names
string[] $descriptions
Returns
Definition at line 704 of file ObjectStateService.php.
    {
        if ( !is_string( $identifier ) || empty( $identifier ) )
            throw new InvalidArgumentValue( "identifier", $identifier );
        if ( !is_string( $defaultLanguageCode ) || empty( $defaultLanguageCode ) )
            throw new InvalidArgumentValue( "defaultLanguageCode", $defaultLanguageCode );
        if ( !is_array( $names ) || empty( $names ) )
            throw new InvalidArgumentValue( "names", $names );
        if ( !isset( $names[$defaultLanguageCode] ) )
            throw new InvalidArgumentValue( "names", $names );
        foreach ( $names as $languageCode => $name )
        {
            try
            {
                $this->repository->getContentLanguageService()->loadLanguage( $languageCode );
            }
            catch ( NotFoundException $e )
            {
                throw new InvalidArgumentValue( "names", $names );
            }
            if ( !is_string( $name ) || empty( $name ) )
                throw new InvalidArgumentValue( "names", $names );
        }
        if ( $descriptions !== null && !is_array( $descriptions ) )
            throw new InvalidArgumentValue( "descriptions", $descriptions );
        $descriptions = $descriptions !== null ? $descriptions : array();
        $inputStruct = new InputStruct();
        $inputStruct->identifier = $identifier;
        $inputStruct->defaultLanguage = $defaultLanguageCode;
        $inputStruct->name = $names;
        $inputStruct->description = array();
        foreach ( $names as $languageCode => $name )
        {
            if ( isset( $descriptions[$languageCode] ) && !empty( $descriptions[$languageCode] ) )
                $inputStruct->description[$languageCode] = $descriptions[$languageCode];
            else
                $inputStruct->description[$languageCode] = "";
        }
        return $inputStruct;
    }
eZ\Publish\Core\Repository\ObjectStateService::buildDomainObjectStateGroupObject (SPIObjectStateGroup $spiObjectStateGroup) protected
Converts the object state group SPI value object to API value object
Parameters
\eZ\Publish\SPI\Persistence\Content\ObjectState\Group $spiObjectStateGroup
Returns
Definition at line 680 of file ObjectStateService.php.
    {
        return new ObjectStateGroup(
            array(
                'id' => (int)$spiObjectStateGroup->id,
                'identifier' => $spiObjectStateGroup->identifier,
                'defaultLanguageCode' => $spiObjectStateGroup->defaultLanguage,
                'languageCodes' => $spiObjectStateGroup->languageCodes,
                'names' => $spiObjectStateGroup->name,
                'descriptions' => $spiObjectStateGroup->description
            )
        );
    }
eZ\Publish\Core\Repository\ObjectStateService::buildDomainObjectStateObject (SPIObjectState $spiObjectState, APIObjectStateGroup $objectStateGroup = null) protected
Converts the object state SPI value object to API value object
Parameters
\eZ\Publish\SPI\Persistence\Content\ObjectState $spiObjectState
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroup $objectStateGroup
Returns
Definition at line 655 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\loadObjectStateGroup().
    {
        $objectStateGroup = $objectStateGroup ?: $this->loadObjectStateGroup( $spiObjectState->groupId );
        return new ObjectState(
            array(
                'id' => (int)$spiObjectState->id,
                'identifier' => $spiObjectState->identifier,
                'priority' => (int)$spiObjectState->priority,
                'defaultLanguageCode' => $spiObjectState->defaultLanguage,
                'languageCodes' => $spiObjectState->languageCodes,
                'names' => $spiObjectState->name,
                'descriptions' => $spiObjectState->description,
                'objectStateGroup' => $objectStateGroup
            )
        );
    }
eZ\Publish\Core\Repository\ObjectStateService::buildObjectStateGroupUpdateInputStruct (APIObjectStateGroup $objectStateGroup, $identifier, $defaultLanguageCode, $names, $descriptions) protected
Validates input for updating object state groups and builds the InputStruct object
Parameters
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroup $objectStateGroup
string $identifier
string $defaultLanguageCode
string[] $names
string[] $descriptions
Returns
Definition at line 832 of file ObjectStateService.php.
    {
        $inputStruct = new InputStruct();
        if ( $identifier !== null && ( !is_string( $identifier ) || empty( $identifier ) ) )
            throw new InvalidArgumentValue( "identifier", $identifier );
        $inputStruct->identifier = $identifier !== null ? $identifier : $objectStateGroup->identifier;
        if ( $defaultLanguageCode !== null && ( !is_string( $defaultLanguageCode ) || empty( $defaultLanguageCode ) ) )
            throw new InvalidArgumentValue( "defaultLanguageCode", $defaultLanguageCode );
        $inputStruct->defaultLanguage = $defaultLanguageCode !== null ? $defaultLanguageCode : $objectStateGroup->defaultLanguageCode;
        if ( $names !== null && ( !is_array( $names ) || empty( $names ) ) )
            throw new InvalidArgumentValue( "names", $names );
        $inputStruct->name = $names !== null ? $names : $objectStateGroup->getNames();
        if ( !isset( $inputStruct->name[$inputStruct->defaultLanguage] ) )
            throw new InvalidArgumentValue( "names", $inputStruct->name );
        foreach ( $inputStruct->name as $languageCode => $name )
        {
            try
            {
                $this->repository->getContentLanguageService()->loadLanguage( $languageCode );
            }
            catch ( NotFoundException $e )
            {
                throw new InvalidArgumentValue( "names", $inputStruct->name );
            }
            if ( !is_string( $name ) || empty( $name ) )
                throw new InvalidArgumentValue( "names", $inputStruct->name );
        }
        if ( $descriptions !== null && !is_array( $descriptions ) )
            throw new InvalidArgumentValue( "descriptions", $descriptions );
        $descriptions = $descriptions !== null ? $descriptions : $objectStateGroup->getDescriptions();
        $descriptions = $descriptions !== null ? $descriptions : array();
        $inputStruct->description = array();
        foreach ( $inputStruct->name as $languageCode => $name )
        {
            if ( isset( $descriptions[$languageCode] ) && !empty( $descriptions[$languageCode] ) )
                $inputStruct->description[$languageCode] = $descriptions[$languageCode];
            else
                $inputStruct->description[$languageCode] = "";
        }
        return $inputStruct;
    }
eZ\Publish\Core\Repository\ObjectStateService::buildObjectStateUpdateInputStruct (APIObjectState $objectState, $identifier, $defaultLanguageCode, $names, $descriptions) protected
Validates input for updating object states and builds the InputStruct object
Parameters
\eZ\Publish\API\Repository\Values\ObjectState\ObjectState $objectState
string $identifier
string $defaultLanguageCode
string[] $names
string[] $descriptions
Returns
Definition at line 766 of file ObjectStateService.php.
    {
        $inputStruct = new InputStruct();
        if ( $identifier !== null && ( !is_string( $identifier ) || empty( $identifier ) ) )
            throw new InvalidArgumentValue( "identifier", $identifier );
        $inputStruct->identifier = $identifier !== null ? $identifier : $objectState->identifier;
        if ( $defaultLanguageCode !== null && ( !is_string( $defaultLanguageCode ) || empty( $defaultLanguageCode ) ) )
            throw new InvalidArgumentValue( "defaultLanguageCode", $defaultLanguageCode );
        $inputStruct->defaultLanguage = $defaultLanguageCode !== null ? $defaultLanguageCode : $objectState->defaultLanguageCode;
        if ( $names !== null && ( !is_array( $names ) || empty( $names ) ) )
            throw new InvalidArgumentValue( "names", $names );
        $inputStruct->name = $names !== null ? $names : $objectState->getNames();
        if ( !isset( $inputStruct->name[$inputStruct->defaultLanguage] ) )
            throw new InvalidArgumentValue( "names", $inputStruct->name );
        foreach ( $inputStruct->name as $languageCode => $name )
        {
            try
            {
                $this->repository->getContentLanguageService()->loadLanguage( $languageCode );
            }
            catch ( NotFoundException $e )
            {
                throw new InvalidArgumentValue( "names", $inputStruct->name );
            }
            if ( !is_string( $name ) || empty( $name ) )
                throw new InvalidArgumentValue( "names", $inputStruct->name );
        }
        if ( $descriptions !== null && !is_array( $descriptions ) )
            throw new InvalidArgumentValue( "descriptions", $descriptions );
        $descriptions = $descriptions !== null ? $descriptions : $objectState->getDescriptions();
        $descriptions = $descriptions !== null ? $descriptions : array();
        $inputStruct->description = array();
        foreach ( $inputStruct->name as $languageCode => $name )
        {
            if ( isset( $descriptions[$languageCode] ) && !empty( $descriptions[$languageCode] ) )
                $inputStruct->description[$languageCode] = $descriptions[$languageCode];
            else
                $inputStruct->description[$languageCode] = "";
        }
        return $inputStruct;
    }
eZ\Publish\Core\Repository\ObjectStateService::createObjectState (APIObjectStateGroup $objectStateGroup, ObjectStateCreateStruct $objectStateCreateStruct)
Creates a new object state in the given group.
Note: in current kernel: If it is the first state all content objects will set to this state.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to create an object state
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the object state with provided identifier already exists in the same group
Parameters
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroup $objectStateGroup
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateCreateStruct $objectStateCreateStruct
Returns
Definition at line 298 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\buildCreateInputStruct(), and eZ\Publish\Core\Repository\ObjectStateService\buildDomainObjectStateObject().
    {
        if ( $this->repository->hasAccess( 'state', 'administrate' ) !== true )
            throw new UnauthorizedException( 'state', 'administrate' );
        $inputStruct = $this->buildCreateInputStruct(
            $objectStateCreateStruct->identifier,
            $objectStateCreateStruct->defaultLanguageCode,
            $objectStateCreateStruct->names,
            $objectStateCreateStruct->descriptions
        );
        try
        {
            $this->objectStateHandler->loadByIdentifier( $inputStruct->identifier, $objectStateGroup->id );
            throw new InvalidArgumentException(
                "objectStateCreateStruct",
                "Object state with provided identifier already exists in provided object state group"
            );
        }
        catch ( APINotFoundException $e )
        {
            // Do nothing
        }
        $this->repository->beginTransaction();
        try
        {
            $spiObjectState = $this->objectStateHandler->create( $objectStateGroup->id, $inputStruct );
            if ( is_numeric( $objectStateCreateStruct->priority ) )
            {
                $this->objectStateHandler->setPriority(
                    $spiObjectState->id,
                    (int)$objectStateCreateStruct->priority
                );
                // Reload the object state to have the updated priority,
                // considering that priorities are always incremental within a group
                $spiObjectState = $this->objectStateHandler->load( $spiObjectState->id );
            }
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainObjectStateObject( $spiObjectState );
    }
eZ\Publish\Core\Repository\ObjectStateService::createObjectStateGroup (ObjectStateGroupCreateStruct $objectStateGroupCreateStruct)
Creates a new object state group
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to create an object state group
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the object state group with provided identifier already exists
Parameters
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroupCreateStruct $objectStateGroupCreateStruct
Returns
Implements eZ\Publish\API\Repository\ObjectStateService.
Definition at line 85 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\buildCreateInputStruct(), and eZ\Publish\Core\Repository\ObjectStateService\buildDomainObjectStateGroupObject().
    {
        if ( $this->repository->hasAccess( 'state', 'administrate' ) !== true )
            throw new UnauthorizedException( 'state', 'administrate' );
        $inputStruct = $this->buildCreateInputStruct(
            $objectStateGroupCreateStruct->identifier,
            $objectStateGroupCreateStruct->defaultLanguageCode,
            $objectStateGroupCreateStruct->names,
            $objectStateGroupCreateStruct->descriptions
        );
        try
        {
            $this->objectStateHandler->loadGroupByIdentifier( $inputStruct->identifier );
            throw new InvalidArgumentException(
                "objectStateGroupCreateStruct",
                "Object state group with provided identifier already exists"
            );
        }
        catch ( APINotFoundException $e )
        {
            // Do nothing
        }
        $this->repository->beginTransaction();
        try
        {
            $spiObjectStateGroup = $this->objectStateHandler->createGroup( $inputStruct );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainObjectStateGroupObject( $spiObjectStateGroup );
    }
eZ\Publish\Core\Repository\ObjectStateService::deleteObjectState (APIObjectState $objectState)
Deletes a object state. The state of the content objects is reset to the first object state in the group.
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to delete an object state
Parameters
\eZ\Publish\API\Repository\Values\ObjectState\ObjectState $objectState
Definition at line 485 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\loadObjectState().
    {
        if ( !is_numeric( $objectState->id ) )
            throw new InvalidArgumentValue( "id", $objectState->id, "ObjectState" );
        if ( $this->repository->hasAccess( 'state', 'administrate' ) !== true )
            throw new UnauthorizedException( 'state', 'administrate' );
        $loadedObjectState = $this->loadObjectState( $objectState->id );
        $this->repository->beginTransaction();
        try
        {
            $this->objectStateHandler->delete( $loadedObjectState->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ObjectStateService::deleteObjectStateGroup (APIObjectStateGroup $objectStateGroup)
Deletes a object state group including all states and links to content
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to delete an object state group
Parameters
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroup $objectStateGroup
Definition at line 261 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\loadObjectStateGroup().
    {
        if ( !is_numeric( $objectStateGroup->id ) )
            throw new InvalidArgumentValue( "id", $objectStateGroup->id, "ObjectStateGroup" );
        if ( $this->repository->hasAccess( 'state', 'administrate' ) !== true )
            throw new UnauthorizedException( 'state', 'administrate' );
        $loadedObjectStateGroup = $this->loadObjectStateGroup( $objectStateGroup->id );
        $this->repository->beginTransaction();
        try
        {
            $this->objectStateHandler->deleteGroup( $loadedObjectStateGroup->id );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ObjectStateService::getContentCount (APIObjectState $objectState)
Returns the number of objects which are in this state
Parameters
\eZ\Publish\API\Repository\Values\ObjectState\ObjectState $objectState
Returns
int
Definition at line 587 of file ObjectStateService.php.
    {
        if ( !is_numeric( $objectState->id ) )
            throw new InvalidArgumentValue( "id", $objectState->id, "ObjectState" );
        return $this->objectStateHandler->getContentCount(
            $objectState->id
        );
    }
eZ\Publish\Core\Repository\ObjectStateService::getContentState (ContentInfo $contentInfo, APIObjectStateGroup $objectStateGroup)
Gets the object-state of object identified by $contentId.
The $state is the id of the state within one group.
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroup $objectStateGroup
Returns
Definition at line 564 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\buildDomainObjectStateObject().
    {
        if ( !is_numeric( $contentInfo->id ) )
            throw new InvalidArgumentValue( "id", $contentInfo->id, "ContentInfo" );
        if ( !is_numeric( $objectStateGroup->id ) )
            throw new InvalidArgumentValue( "id", $objectStateGroup->id, "ObjectStateGroup" );
        $spiObjectState = $this->objectStateHandler->getContentState(
            $contentInfo->id,
            $objectStateGroup->id
        );
        return $this->buildDomainObjectStateObject( $spiObjectState );
    }
eZ\Publish\Core\Repository\ObjectStateService::loadObjectState ($stateId)
Loads an object state
Parameters
mixed $stateId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the state was not found
Returns
Implements eZ\Publish\API\Repository\ObjectStateService.
Definition at line 360 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\buildDomainObjectStateObject().
    {
        if ( !is_numeric( $stateId ) )
            throw new InvalidArgumentValue( "stateId", $stateId );
        $spiObjectState = $this->objectStateHandler->load( $stateId );
        return $this->buildDomainObjectStateObject( $spiObjectState );
    }
eZ\Publish\Core\Repository\ObjectStateService::loadObjectStateGroup ($objectStateGroupId)
Loads a object state group
Parameters
mixed $objectStateGroupId
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the group was not found
Returns
Implements eZ\Publish\API\Repository\ObjectStateService.
Definition at line 134 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\buildDomainObjectStateGroupObject().
    {
        if ( !is_numeric( $objectStateGroupId ) )
            throw new InvalidArgumentValue( "objectStateGroupId", $objectStateGroupId );
        $spiObjectStateGroup = $this->objectStateHandler->loadGroup( $objectStateGroupId );
        return $this->buildDomainObjectStateGroupObject( $spiObjectStateGroup );
    }
eZ\Publish\Core\Repository\ObjectStateService::loadObjectStateGroups ($offset = 0, $limit = -1)
Loads all object state groups
Parameters
int $offset
int $limit
Returns
[]
Implements eZ\Publish\API\Repository\ObjectStateService.
Definition at line 152 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\buildDomainObjectStateGroupObject().
    {
        $spiObjectStateGroups = $this->objectStateHandler->loadAllGroups( $offset, $limit );
        $objectStateGroups = array();
        foreach ( $spiObjectStateGroups as $spiObjectStateGroup )
        {
            $objectStateGroups[] = $this->buildDomainObjectStateGroupObject( $spiObjectStateGroup );
        }
        return $objectStateGroups;
    }
eZ\Publish\Core\Repository\ObjectStateService::loadObjectStates (APIObjectStateGroup $objectStateGroup)
This method returns the ordered list of object states of a group
Parameters
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroup $objectStateGroup
Returns
[]
Definition at line 172 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\buildDomainObjectStateObject().
    {
        if ( !is_numeric( $objectStateGroup->id ) )
            throw new InvalidArgumentValue( "id", $objectStateGroup->id, "ObjectStateGroup" );
        $spiObjectStates = $this->objectStateHandler->loadObjectStates( $objectStateGroup->id );
        $objectStates = array();
        foreach ( $spiObjectStates as $spiObjectState )
        {
            $objectStates[] = $this->buildDomainObjectStateObject( $spiObjectState, $objectStateGroup );
        }
        return $objectStates;
    }
eZ\Publish\Core\Repository\ObjectStateService::newObjectStateCreateStruct ($identifier)
Instantiates a new Object State Create Struct and sets $identifier in it.
Parameters
string $identifier
Returns
Implements eZ\Publish\API\Repository\ObjectStateService.
Definition at line 629 of file ObjectStateService.php.
    {
        $objectStateCreateStruct = new ObjectStateCreateStruct();
        $objectStateCreateStruct->identifier = $identifier;
        return $objectStateCreateStruct;
    }
eZ\Publish\Core\Repository\ObjectStateService::newObjectStateGroupCreateStruct ($identifier)
Instantiates a new Object State Group Create Struct and sets $identified in it.
Parameters
string $identifier
Returns
Implements eZ\Publish\API\Repository\ObjectStateService.
Definition at line 604 of file ObjectStateService.php.
    {
        $objectStateGroupCreateStruct = new ObjectStateGroupCreateStruct();
        $objectStateGroupCreateStruct->identifier = $identifier;
        return $objectStateGroupCreateStruct;
    }
eZ\Publish\Core\Repository\ObjectStateService::newObjectStateGroupUpdateStruct ()
Instantiates a new Object State Group Update Struct.
Returns
Implements eZ\Publish\API\Repository\ObjectStateService.
Definition at line 617 of file ObjectStateService.php.
    {
        return new ObjectStateGroupUpdateStruct();
    }
eZ\Publish\Core\Repository\ObjectStateService::newObjectStateUpdateStruct ()
Instantiates a new Object State Update Struct.
Returns
Implements eZ\Publish\API\Repository\ObjectStateService.
Definition at line 642 of file ObjectStateService.php.
    {
        return new ObjectStateUpdateStruct();
    }
eZ\Publish\Core\Repository\ObjectStateService::setContentState (ContentInfo $contentInfo, APIObjectStateGroup $objectStateGroup, APIObjectState $objectState)
Sets the object-state of a state group to $state for the given content.
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the object state does not belong to the given group
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to change the object state
Parameters
\eZ\Publish\API\Repository\Values\Content\ContentInfo $contentInfo
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroup $objectStateGroup
\eZ\Publish\API\Repository\Values\ObjectState\ObjectState $objectState
Definition at line 518 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\loadObjectState().
    {
        if ( !is_numeric( $contentInfo->id ) )
            throw new InvalidArgumentValue( "id", $contentInfo->id, "ContentInfo" );
        if ( !is_numeric( $objectStateGroup->id ) )
            throw new InvalidArgumentValue( "id", $objectStateGroup->id, "ObjectStateGroup" );
        if ( !is_numeric( $objectState->id ) )
            throw new InvalidArgumentValue( "id", $objectState->id, "ObjectState" );
        if ( $this->repository->canUser( 'state', 'assign', $contentInfo, $objectState ) !== true )
            throw new UnauthorizedException( 'state', 'assign' );
        $loadedObjectState = $this->loadObjectState( $objectState->id );
        if ( $loadedObjectState->getObjectStateGroup()->id != $objectStateGroup->id )
            throw new InvalidArgumentException( "objectState", "Object state does not belong to the given group" );
        $this->repository->beginTransaction();
        try
        {
            $this->objectStateHandler->setContentState(
                $contentInfo->id,
                $objectStateGroup->id,
                $loadedObjectState->id
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ObjectStateService::setPriorityOfObjectState (APIObjectState $objectState, $priority)
Changes the priority of the state
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to change priority on an object state
Parameters
\eZ\Publish\API\Repository\Values\ObjectState\ObjectState $objectState
int $priority
Definition at line 448 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\loadObjectState().
    {
        if ( !is_numeric( $objectState->id ) )
            throw new InvalidArgumentValue( "id", $objectState->id, "ObjectState" );
        if ( !is_numeric( $priority ) )
            throw new InvalidArgumentValue( "priority", $priority );
        if ( $this->repository->hasAccess( 'state', 'administrate' ) !== true )
            throw new UnauthorizedException( 'state', 'administrate' );
        $loadedObjectState = $this->loadObjectState( $objectState->id );
        $this->repository->beginTransaction();
        try
        {
            $this->objectStateHandler->setPriority(
                $loadedObjectState->id,
                (int)$priority
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
    }
eZ\Publish\Core\Repository\ObjectStateService::updateObjectState (APIObjectState $objectState, ObjectStateUpdateStruct $objectStateUpdateStruct)
Updates an object state
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to update an object state
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the object state with provided identifier already exists in the same group
Parameters
\eZ\Publish\API\Repository\Values\ObjectState\ObjectState $objectState
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateUpdateStruct $objectStateUpdateStruct
Returns
Definition at line 381 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\buildDomainObjectStateObject(), eZ\Publish\Core\Repository\ObjectStateService\buildObjectStateUpdateInputStruct(), and eZ\Publish\Core\Repository\ObjectStateService\loadObjectState().
    {
        if ( !is_numeric( $objectState->id ) )
            throw new InvalidArgumentValue( "id", $objectState->id, "ObjectState" );
        if ( $this->repository->hasAccess( 'state', 'administrate' ) !== true )
            throw new UnauthorizedException( 'state', 'administrate' );
        $loadedObjectState = $this->loadObjectState( $objectState->id );
        $inputStruct = $this->buildObjectStateUpdateInputStruct(
            $loadedObjectState,
            $objectStateUpdateStruct->identifier,
            $objectStateUpdateStruct->defaultLanguageCode,
            $objectStateUpdateStruct->names,
            $objectStateUpdateStruct->descriptions
        );
        if ( $objectStateUpdateStruct->identifier !== null )
        {
            try
            {
                $existingObjectState = $this->objectStateHandler->loadByIdentifier(
                    $inputStruct->identifier,
                    $loadedObjectState->getObjectStateGroup()->id
                );
                if ( $existingObjectState->id != $objectState->id )
                {
                    throw new InvalidArgumentException(
                        "objectStateUpdateStruct",
                        "Object state with provided identifier already exists in provided object state group"
                    );
                }
            }
            catch ( APINotFoundException $e )
            {
                // Do nothing
            }
        }
        $this->repository->beginTransaction();
        try
        {
            $spiObjectState = $this->objectStateHandler->update(
                $loadedObjectState->id,
                $inputStruct
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainObjectStateObject( $spiObjectState );
    }
eZ\Publish\Core\Repository\ObjectStateService::updateObjectStateGroup (APIObjectStateGroup $objectStateGroup, ObjectStateGroupUpdateStruct $objectStateGroupUpdateStruct)
Updates an object state group
Exceptions
\eZ\Publish\API\Repository\Exceptions\UnauthorizedException if the user is not allowed to update an object state group
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException if the object state group with provided identifier already exists
Parameters
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroup $objectStateGroup
\eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroupUpdateStruct $objectStateGroupUpdateStruct
Returns
Definition at line 199 of file ObjectStateService.php.
References eZ\Publish\Core\Repository\ObjectStateService\buildDomainObjectStateGroupObject(), eZ\Publish\Core\Repository\ObjectStateService\buildObjectStateGroupUpdateInputStruct(), and eZ\Publish\Core\Repository\ObjectStateService\loadObjectStateGroup().
    {
        if ( !is_numeric( $objectStateGroup->id ) )
            throw new InvalidArgumentValue( "id", $objectStateGroup->id, "ObjectStateGroup" );
        if ( $this->repository->hasAccess( 'state', 'administrate' ) !== true )
            throw new UnauthorizedException( 'state', 'administrate' );
        $loadedObjectStateGroup = $this->loadObjectStateGroup( $objectStateGroup->id );
        $inputStruct = $this->buildObjectStateGroupUpdateInputStruct(
            $loadedObjectStateGroup,
            $objectStateGroupUpdateStruct->identifier,
            $objectStateGroupUpdateStruct->defaultLanguageCode,
            $objectStateGroupUpdateStruct->names,
            $objectStateGroupUpdateStruct->descriptions
        );
        if ( $objectStateGroupUpdateStruct->identifier !== null )
        {
            try
            {
                $existingObjectStateGroup = $this->objectStateHandler->loadGroupByIdentifier( $inputStruct->identifier );
                if ( $existingObjectStateGroup->id != $objectStateGroup->id )
                {
                    throw new InvalidArgumentException(
                        "objectStateGroupUpdateStruct",
                        "Object state group with provided identifier already exists"
                    );
                }
            }
            catch ( APINotFoundException $e )
            {
                // Do nothing
            }
        }
        $this->repository->beginTransaction();
        try
        {
            $spiObjectStateGroup = $this->objectStateHandler->updateGroup(
                $loadedObjectStateGroup->id,
                $inputStruct
            );
            $this->repository->commit();
        }
        catch ( \Exception $e )
        {
            $this->repository->rollback();
            throw $e;
        }
        return $this->buildDomainObjectStateGroupObject( $spiObjectStateGroup );
    }
Member Data Documentation
eZ\Publish\Core\Repository\ObjectStateService::$objectStateHandler protected
Definition at line 51 of file ObjectStateService.php.
eZ\Publish\Core\Repository\ObjectStateService::$repository protected
Definition at line 46 of file ObjectStateService.php.
eZ\Publish\Core\Repository\ObjectStateService::$settings protected
Definition at line 56 of file ObjectStateService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Repository/ObjectStateService.php