ezp-next: eZ\Publish\API\Repository\Values\ValueObject Class Reference
eZ\Publish\API\Repository\Values\ValueObject Class Reference
Inherited by eZ\Publish\API\Repository\Values\Content\Content, eZ\Publish\API\Repository\Values\Content\ContentCreateStruct, eZ\Publish\API\Repository\Values\Content\ContentInfo, eZ\Publish\API\Repository\Values\Content\ContentMetadataUpdateStruct, eZ\Publish\API\Repository\Values\Content\ContentUpdateStruct, eZ\Publish\API\Repository\Values\Content\Field, eZ\Publish\API\Repository\Values\Content\Language, eZ\Publish\API\Repository\Values\Content\LanguageCreateStruct, eZ\Publish\API\Repository\Values\Content\Location, eZ\Publish\API\Repository\Values\Content\LocationCreateStruct, eZ\Publish\API\Repository\Values\Content\LocationList, eZ\Publish\API\Repository\Values\Content\LocationUpdateStruct, eZ\Publish\API\Repository\Values\Content\Query, eZ\Publish\API\Repository\Values\Content\Query\FacetBuilder, eZ\Publish\API\Repository\Values\Content\Relation, eZ\Publish\API\Repository\Values\Content\Search\Facet, eZ\Publish\API\Repository\Values\Content\Search\SearchHit, eZ\Publish\API\Repository\Values\Content\Search\SearchResult, eZ\Publish\API\Repository\Values\Content\SearchResult, eZ\Publish\API\Repository\Values\Content\Section, eZ\Publish\API\Repository\Values\Content\SectionCreateStruct, eZ\Publish\API\Repository\Values\Content\SectionUpdateStruct, eZ\Publish\API\Repository\Values\Content\TranslationInfo, eZ\Publish\API\Repository\Values\Content\TranslationValues, eZ\Publish\API\Repository\Values\Content\URLAlias, eZ\Publish\API\Repository\Values\Content\URLWildcard, eZ\Publish\API\Repository\Values\Content\URLWildcardTranslationResult, eZ\Publish\API\Repository\Values\Content\VersionInfo, eZ\Publish\API\Repository\Values\ContentType\ContentType, eZ\Publish\API\Repository\Values\ContentType\ContentTypeCreateStruct, eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroup, eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroupCreateStruct, eZ\Publish\API\Repository\Values\ContentType\ContentTypeGroupUpdateStruct, eZ\Publish\API\Repository\Values\ContentType\ContentTypeUpdateStruct, eZ\Publish\API\Repository\Values\ContentType\FieldDefinition, eZ\Publish\API\Repository\Values\ContentType\FieldDefinitionCreateStruct, eZ\Publish\API\Repository\Values\ContentType\FieldDefinitionUpdateStruct, eZ\Publish\API\Repository\Values\IO\BinaryFile, eZ\Publish\API\Repository\Values\IO\BinaryFileCreateStruct, eZ\Publish\API\Repository\Values\ObjectState\ObjectState, eZ\Publish\API\Repository\Values\ObjectState\ObjectStateCreateStruct, eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroup, eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroupCreateStruct, eZ\Publish\API\Repository\Values\ObjectState\ObjectStateGroupUpdateStruct, eZ\Publish\API\Repository\Values\ObjectState\ObjectStateUpdateStruct, eZ\Publish\API\Repository\Values\Translation, eZ\Publish\API\Repository\Values\User\Limitation, eZ\Publish\API\Repository\Values\User\Policy, eZ\Publish\API\Repository\Values\User\PolicyCreateStruct, eZ\Publish\API\Repository\Values\User\PolicyUpdateStruct, eZ\Publish\API\Repository\Values\User\Role, eZ\Publish\API\Repository\Values\User\RoleAssignment, eZ\Publish\API\Repository\Values\User\RoleCreateStruct, eZ\Publish\API\Repository\Values\User\RoleUpdateStruct, eZ\Publish\API\Repository\Values\User\UserGroupUpdateStruct, eZ\Publish\API\Repository\Values\User\UserUpdateStruct, eZ\Publish\Core\FieldType\Value, eZ\Publish\Core\MVC\Symfony\Routing\SimplifiedRequest, eZ\Publish\Core\REST\Client\Values\RestContentInfo, eZ\Publish\Core\REST\Server\Values\CreatedContent, eZ\Publish\Core\REST\Server\Values\CreatedContentType, eZ\Publish\Core\REST\Server\Values\CreatedContentTypeGroup, eZ\Publish\Core\REST\Server\Values\CreatedFieldDefinition, eZ\Publish\Core\REST\Server\Values\CreatedLocation, eZ\Publish\Core\REST\Server\Values\CreatedObjectState, eZ\Publish\Core\REST\Server\Values\CreatedObjectStateGroup, eZ\Publish\Core\REST\Server\Values\CreatedPolicy, eZ\Publish\Core\REST\Server\Values\CreatedRelation, eZ\Publish\Core\REST\Server\Values\CreatedRole, eZ\Publish\Core\REST\Server\Values\CreatedSection, eZ\Publish\Core\REST\Server\Values\CreatedURLAlias, eZ\Publish\Core\REST\Server\Values\CreatedURLWildcard, eZ\Publish\Core\REST\Server\Values\CreatedUser, eZ\Publish\Core\REST\Server\Values\CreatedUserGroup, eZ\Publish\Core\REST\Server\Values\CreatedVersion, eZ\Publish\Core\REST\Server\Values\RestExecutedView, eZ\Publish\Core\SignalSlot\Signal, eZ\Publish\SPI\Persistence\ValueObject, and eZ\Publish\SPI\Variation\Values\Variation.
Public Member Functions
__construct (array $properties=array())
__set ($property, $value)
__get ($property)
__isset ($property)
__unset ($property)
attribute ($property)
attributes ()
hasAttribute ($property)
Static Public Member Functions
static __set_state (array $array)
Protected Member Functions
getProperties ($dynamicProperties=array())
Detailed Description
Definition at line 26 of file ValueObject.php.
Constructor & Destructor Documentation
eZ\Publish\API\Repository\Values\ValueObject::__construct (array $properties = array())
Construct object optionally with a set of properties
Readonly properties values must be set using $properties as they are not writable anymore after object has been created.
Parameters
array $properties
Reimplemented in eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition, eZ\Publish\Core\Repository\Values\ContentType\ContentType, eZ\Publish\Core\FieldType\Image\Value, eZ\Publish\Core\FieldType\BinaryBase\Value, eZ\Publish\Core\REST\Client\Values\ContentType\FieldDefinition, eZ\Publish\Core\FieldType\MapLocation\Value, eZ\Publish\Core\FieldType\Country\Value, eZ\Publish\Core\Repository\Values\Content\Content, eZ\Publish\Core\FieldType\Author\Value, eZ\Publish\Core\FieldType\RelationList\Value, eZ\Publish\Core\FieldType\Selection\Value, eZ\Publish\Core\REST\Client\Values\ContentType\ContentTypeGroup, and eZ\Publish\Core\REST\Client\Values\ContentType\ContentTypeCreateStruct.
Definition at line 36 of file ValueObject.php.
    {
        foreach ( $properties as $property => $value )
        {
            $this->$property = $value;
        }
    }
Member Function Documentation
eZ\Publish\API\Repository\Values\ValueObject::__get ($property)
Magic get function handling read to non public properties
Returns value for all readonly (protected) properties.
Exceptions
\eZ\Publish\API\Repository\Exceptions\PropertyNotFoundException exception on all reads to undefined properties so typos are not silently accepted.
Parameters
string $property Name of the property
Returns
mixed
Reimplemented in eZ\Publish\Core\Repository\Values\Content\Content, eZ\Publish\Core\REST\Client\Values\ContentType\ContentTypeDraft, eZ\Publish\Core\Repository\Values\User\User, eZ\Publish\Core\Repository\Values\User\UserGroup, eZ\Publish\Core\REST\Client\Values\Content\VersionInfo, eZ\Publish\Core\REST\Client\Values\User\User, eZ\Publish\Core\REST\Client\Values\User\UserGroup, eZ\Publish\Core\Repository\Values\Content\Location, eZ\Publish\Core\REST\Client\Values\Content\ContentInfo, eZ\Publish\Core\Repository\Values\Content\ContentInfo, eZ\Publish\Core\Repository\Values\Content\TrashItem, eZ\Publish\Core\Repository\Values\ContentType\ContentTypeDraft, and eZ\Publish\Core\REST\Client\Values\Content\TrashItem.
Definition at line 97 of file ValueObject.php.
    {
        if ( property_exists( $this, $property ) )
        {
            return $this->$property;
        }
        throw new PropertyNotFoundException( $property, get_class( $this ) );
    }
eZ\Publish\API\Repository\Values\ValueObject::__isset ($property)
Magic isset function handling isset() to non public properties
Returns true for all (public/)protected/private properties.
Parameters
string $property Name of the property
Returns
boolean
Reimplemented in eZ\Publish\Core\Repository\Values\Content\Content, eZ\Publish\Core\Repository\Values\User\User, eZ\Publish\Core\REST\Client\Values\ContentType\ContentTypeDraft, eZ\Publish\Core\Repository\Values\User\UserGroup, eZ\Publish\Core\REST\Client\Values\Content\VersionInfo, eZ\Publish\Core\Repository\Values\Content\Location, eZ\Publish\Core\Repository\Values\Content\TrashItem, eZ\Publish\Core\Repository\Values\Content\ContentInfo, and eZ\Publish\Core\Repository\Values\ContentType\ContentTypeDraft.
Definition at line 115 of file ValueObject.php.
    {
        return property_exists( $this, $property );
    }
eZ\Publish\API\Repository\Values\ValueObject::__set ($property, $value)
Magic set function handling writes to non public properties
Exceptions
\eZ\Publish\API\Repository\Exceptions\PropertyNotFoundException When property does not exist
\eZ\Publish\API\Repository\Exceptions\PropertyReadOnlyException When property is readonly (protected)
Parameters
string $property Name of the property
string $value
Returns
void
Reimplemented in eZ\Publish\Core\REST\Client\Values\ContentType\ContentTypeDraft, and eZ\Publish\Core\Repository\Values\ContentType\ContentTypeDraft.
Definition at line 78 of file ValueObject.php.
    {
        if ( property_exists( $this, $property ) )
        {
            throw new PropertyReadOnlyException( $property, get_class( $this ) );
        }
        throw new PropertyNotFoundException( $property, get_class( $this ) );
    }
static eZ\Publish\API\Repository\Values\ValueObject::__set_state (array $array) static
Returns a new instance of this class with the data specified by $array.
$array contains all the data members of this class in the form: array('member_name'=>value).
__set_state makes this class exportable with var_export. var_export() generates code, that calls this method when it is parsed with PHP.
Parameters
mixed[] $array
Returns
ValueObject
Definition at line 150 of file ValueObject.php.
    {
        return new static( $array );
    }
eZ\Publish\API\Repository\Values\ValueObject::__unset ($property)
Magic unset function handling unset() to non public properties
Exceptions
\eZ\Publish\API\Repository\Exceptions\PropertyNotFoundException exception on all writes to undefined properties so typos are not silently accepted and
\eZ\Publish\API\Repository\Exceptions\PropertyReadOnlyException exception on readonly (protected) properties.
__set()
Parameters
string $property Name of the property
Returns
boolean
Definition at line 131 of file ValueObject.php.
References eZ\Publish\API\Repository\Values\ValueObject\__set().
    {
        $this->__set( $property, null );
    }
eZ\Publish\API\Repository\Values\ValueObject::attribute ($property) final
Internal function for Legacy template engine compatibility to get property value
private
Deprecated:
Since 5.0, available purely for legacy eZTemplate compatibility __get()
Parameters
string $property
Returns
mixed
Definition at line 166 of file ValueObject.php.
References eZ\Publish\API\Repository\Values\ValueObject\__get().
    {
        return $this->__get( $property );
    }
eZ\Publish\API\Repository\Values\ValueObject::attributes () final
Internal function for Legacy template engine compatibility to get properties
private
Deprecated:
Since 5.0, available purely for legacy eZTemplate compatibility __isset()
Returns
array
Definition at line 180 of file ValueObject.php.
References eZ\Publish\API\Repository\Values\ValueObject\getProperties().
    {
        return $this->getProperties();
    }
eZ\Publish\API\Repository\Values\ValueObject::getProperties ($dynamicProperties = array()) protected
Function where list of properties are returned
Used by {
See Also
attributes()}, override to add dynamic properties __isset()
Todo:
Make object traversable and reuse this function there (hence why this is not exposed)
Parameters
array $dynamicProperties Additional dynamic properties exposed on the object
Returns
array
Reimplemented in eZ\Publish\Core\Repository\Values\Content\Content, eZ\Publish\Core\Repository\Values\User\User, eZ\Publish\Core\Repository\Values\User\UserGroup, eZ\Publish\Core\Repository\Values\Content\Location, eZ\Publish\Core\Repository\Values\Content\TrashItem, and eZ\Publish\Core\Repository\Values\ContentType\ContentTypeDraft.
Definition at line 56 of file ValueObject.php.
References eZ\Publish\API\Repository\Values\ValueObject\__isset().
    {
        $properties = $dynamicProperties;
        foreach ( get_object_vars( $this ) as $property => $propertyValue )
        {
            if ( $this->__isset( $property ) )
                $properties[] = $property;
        }
        return $properties;
    }
eZ\Publish\API\Repository\Values\ValueObject::hasAttribute ($property) final
Internal function for Legacy template engine compatibility to check existence of property
private
Deprecated:
Since 5.0, available purely for legacy eZTemplate compatibility __isset()
Parameters
string $property
Returns
boolean
Definition at line 196 of file ValueObject.php.
References eZ\Publish\API\Repository\Values\ValueObject\__isset().
    {
        return $this->__isset( $property );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/API/Repository/Values/ValueObject.php