ezp-next: eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler Class Reference
eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler Class Reference
Public Member Functions
__construct (array $settings=array(), SiteAccess $siteAccess=null, ContainerInterface $container=null)
run ()
runCallback (\Closure $callback, $postReinitialize=true)
setUseExceptions ($useExceptions)
reInitialize ()
hasServiceContainer ()
getServiceContainer ()
Protected Attributes
$script
$container
Detailed Description
Definition at line 19 of file CLIHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler::__construct (array $settings = array(), SiteAccess $siteAccess = null, ContainerInterface $container = null)
Constructor
Parameters
array $settings Settings to pass to constructor.
\eZ\Publish\Core\MVC\Symfony\SiteAccess $siteAccess
\Symfony\Component\DependencyInjection\ContainerInterface $container
Definition at line 38 of file CLIHandler.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler\$container.
    {
        $this->container = $container;
        if ( isset( $settings['injected-settings'] ) )
        {
            $injectedSettings = array();
            foreach ( $settings["injected-settings"] as $keySetting => $injectedSetting )
            {
                list( $file, $section, $setting ) = explode( "/", $keySetting );
                $injectedSettings[$file][$section][$setting] = $injectedSetting;
            }
            // those settings override anything else in local .ini files and
            // their overrides
            eZINI::injectSettings( $injectedSettings );
        }
        $this->script = eZScript::instance( $settings );
        $this->script->startup();
        if ( isset( $siteAccess ) )
            $this->script->setUseSiteAccess( $siteAccess->name );
        $this->script->initialize();
    }
Member Function Documentation
eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler::getServiceContainer ()
Returns the Symfony Dependency Injection container if it has been injected, otherwise returns null.
Returns
|null
Definition at line 130 of file CLIHandler.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler\getServiceContainer().
    {
        return $this->container;
    }
eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler::hasServiceContainer ()
Checks whether the kernel handler has the Symfony Dependency Injection container or not.
Returns
boolean
Definition at line 119 of file CLIHandler.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler\hasServiceContainer().
    {
        return isset( $this->container );
    }
eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler::reInitialize ()
Reinitializes the kernel environment.
Returns
void
Definition at line 108 of file CLIHandler.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler\reInitialize().
    {
        $this->script->setIsInitialized( false );
    }
eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler::run ()
Not supported by CLIHandler
Exceptions
\RuntimeException
Definition at line 67 of file CLIHandler.php.
    {
        throw new RuntimeException( 'run() method is not supported by CLIHandler' );
    }
eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler::runCallback (\Closure $callback, $postReinitialize = true)
Runs a callback function in the legacy kernel environment. This is useful to run eZ Publish 4.x code from a non-related context (like eZ Publish 5)
Parameters
\Closure $callback
boolean $postReinitialize Default is true. If set to false, the kernel environment will not be reinitialized. This can be useful to optimize several calls to the kernel within the same context.
Returns
mixed The result of the callback
Definition at line 82 of file CLIHandler.php.
    {
        $return = $callback();
        $this->script->shutdown();
        if ( !$postReinitialize )
            $this->script->setIsInitialized( true );
        return $return;
    }
eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler::setUseExceptions ($useExceptions)
Not supported by CLIHandler
Parameters
boolean $useExceptions
Exceptions
\RuntimeException
Definition at line 99 of file CLIHandler.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler\setUseExceptions().
    {
    }
Member Data Documentation
eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler::$container protected
Definition at line 29 of file CLIHandler.php.
eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler::$script protected
Definition at line 24 of file CLIHandler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/MVC/Legacy/Kernel/CLIHandler.php