ezp-next: eZ\Publish\Core\IO\IOService Class Reference
eZ\Publish\Core\IO\IOService Class Reference
Public Member Functions
__construct (Handler $handler, MimeTypeDetector $mimeTypeDetector, array $settings=array())
newBinaryCreateStructFromUploadedFile (array $uploadedFile)
newBinaryCreateStructFromLocalFile ($localFile)
createBinaryFile (BinaryFileCreateStruct $binaryFileCreateStruct)
deleteBinaryFile (BinaryFile $binaryFile)
loadBinaryFile ($uri)
getFileInputStream (BinaryFile $binaryFile)
getFileContents (BinaryFile $binaryFile)
getInternalPath ($externalPath)
getExternalPath ($internalPath)
getMetadata (MetadataHandler $metadataHandler, BinaryFile $binaryFile)
Protected Member Functions
buildSPIBinaryFileCreateStructObject (BinaryFileCreateStruct $binaryFileCreateStruct)
buildDomainBinaryFileObject (SPIBinaryFile $spiBinaryFile)
getPrefixedUri ($uri)
removeUriPrefix ($uri)
Protected Attributes
$ioHandler
$settings
$mimeTypeDetector
Detailed Description
Definition at line 28 of file IOService.php.
Constructor & Destructor Documentation
eZ\Publish\Core\IO\IOService::__construct (Handler $handler, MimeTypeDetector $mimeTypeDetector, array $settings = array())
Setups service with reference to repository object that created it & corresponding handler
Parameters
\eZ\Publish\Core\IO\Handler $handler
array $settings
Definition at line 51 of file IOService.php.
References eZ\Publish\Core\IO\IOService\$mimeTypeDetector, and eZ\Publish\Core\IO\IOService\$settings.
    {
        $this->ioHandler = $handler;
        $this->mimeTypeDetector = $mimeTypeDetector;
        // Union makes sure default settings are ignored if provided in argument
        $this->settings = $settings + array(
            //'defaultSetting' => array(),
        );
    }
Member Function Documentation
eZ\Publish\Core\IO\IOService::buildDomainBinaryFileObject (SPIBinaryFile $spiBinaryFile) protected
Generates API BinaryFile object from provided SPI BinaryFile object
Parameters
\eZ\Publish\SPI\IO\BinaryFile $spiBinaryFile
Returns
Definition at line 300 of file IOService.php.
    {
        if ( isset( $spiBinaryFile->mimeType ) )
        {
            $mimeType = $spiBinaryFile->mimeType;
        }
        else
        {
            $mimeType = $this->mimeTypeDetector->getFromBuffer(
                $this->ioHandler->getFileContents( $spiBinaryFile->uri )
            );
        }
        return new BinaryFile(
            array(
                'size' => (int)$spiBinaryFile->size,
                'mtime' => $spiBinaryFile->mtime,
                'uri' => $this->removeUriPrefix( $spiBinaryFile->uri ),
                'mimeType' => $mimeType,
            )
        );
    }
eZ\Publish\Core\IO\IOService::buildSPIBinaryFileCreateStructObject (BinaryFileCreateStruct $binaryFileCreateStruct) protected
Generates SPI BinaryFileCreateStruct object from provided API BinaryFileCreateStruct object
Parameters
\eZ\Publish\Core\IO\Values\BinaryFileCreateStruct $binaryFileCreateStruct
Returns
Definition at line 281 of file IOService.php.
References eZ\Publish\Core\IO\IOService\getPrefixedUri().
    {
        $spiBinaryCreateStruct = new SPIBinaryFileCreateStruct();
        $spiBinaryCreateStruct->uri = $this->getPrefixedUri( $binaryFileCreateStruct->uri );
        $spiBinaryCreateStruct->size = $binaryFileCreateStruct->size;
        $spiBinaryCreateStruct->setInputStream( $binaryFileCreateStruct->inputStream );
        $spiBinaryCreateStruct->mimeType = $binaryFileCreateStruct->mimeType;
        return $spiBinaryCreateStruct;
    }
eZ\Publish\Core\IO\IOService::createBinaryFile (BinaryFileCreateStruct $binaryFileCreateStruct)
Creates a binary file in the repository
Parameters
\eZ\Publish\Core\IO\Values\BinaryFileCreateStruct $binaryFileCreateStruct
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentValue
Returns
The created BinaryFile object
Definition at line 133 of file IOService.php.
References eZ\Publish\Core\IO\IOService\buildDomainBinaryFileObject(), and eZ\Publish\Core\IO\IOService\buildSPIBinaryFileCreateStructObject().
    {
        if ( empty( $binaryFileCreateStruct->uri ) || !is_string( $binaryFileCreateStruct->uri ) )
            throw new InvalidArgumentValue( "uri", $binaryFileCreateStruct->uri, "BinaryFileCreateStruct" );
        if ( !is_int( $binaryFileCreateStruct->size ) || $binaryFileCreateStruct->size < 0 )
            throw new InvalidArgumentValue( "size", $binaryFileCreateStruct->size, "BinaryFileCreateStruct" );
        if ( !is_resource( $binaryFileCreateStruct->inputStream ) )
            throw new InvalidArgumentValue( "inputStream", "property is not a file resource", "BinaryFileCreateStruct" );
        if ( !isset( $binaryFileCreateStruct->mimeType ) )
        {
            $buffer = fread( $binaryFileCreateStruct->inputStream, $binaryFileCreateStruct->size );
            $binaryFileCreateStruct->mimeType = $this->mimeTypeDetector->getFromBuffer( $buffer );
            unset( $buffer );
        }
        $spiBinaryCreateStruct = $this->buildSPIBinaryFileCreateStructObject( $binaryFileCreateStruct );
        $spiBinaryFile = $this->ioHandler->create( $spiBinaryCreateStruct );
        return $this->buildDomainBinaryFileObject( $spiBinaryFile );
    }
eZ\Publish\Core\IO\IOService::deleteBinaryFile (BinaryFile $binaryFile)
Deletes the BinaryFile with $path
Parameters
\eZ\Publish\Core\IO\Values\BinaryFile $binaryFile
Exceptions
InvalidArgumentValue
Definition at line 164 of file IOService.php.
References eZ\Publish\Core\IO\IOService\getPrefixedUri().
    {
        if ( empty( $binaryFile->uri ) || !is_string( $binaryFile->uri ) )
            throw new InvalidArgumentValue( "uri", $binaryFile->uri, "BinaryFile" );
        $this->ioHandler->delete( $this->getPrefixedUri( $binaryFile->uri ) );
    }
eZ\Publish\Core\IO\IOService::getExternalPath ($internalPath)
Returns the external path to $internalPath
Parameters
string $internalPath
Returns
string
Definition at line 255 of file IOService.php.
References eZ\Publish\Core\IO\IOService\removeUriPrefix().
    {
        return $this->removeUriPrefix( $this->ioHandler->getExternalPath( $internalPath ) );
    }
eZ\Publish\Core\IO\IOService::getFileContents (BinaryFile $binaryFile)
Returns the content of the binary file
Parameters
\eZ\Publish\Core\IO\Values\BinaryFile $binaryFile
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentValue
Returns
string
Definition at line 227 of file IOService.php.
References eZ\Publish\Core\IO\IOService\getPrefixedUri().
    {
        if ( empty( $binaryFile->uri ) || !is_string( $binaryFile->uri ) )
            throw new InvalidArgumentValue( "uri", $binaryFile->uri, "BinaryFile" );
        return $this->ioHandler->getFileContents(
            $this->getPrefixedUri( $binaryFile->uri )
        );
    }
eZ\Publish\Core\IO\IOService::getFileInputStream (BinaryFile $binaryFile)
Returns a read (mode: rb) file resource to the binary file identified by $path
Parameters
\eZ\Publish\Core\IO\Values\BinaryFile $binaryFile
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentValue
Returns
resource
Definition at line 208 of file IOService.php.
References eZ\Publish\Core\IO\IOService\getPrefixedUri().
    {
        if ( empty( $binaryFile->uri ) || !is_string( $binaryFile->uri ) )
            throw new InvalidArgumentValue( "uri", $binaryFile->uri, "BinaryFile" );
        return $this->ioHandler->getFileResource(
            $this->getPrefixedUri( $binaryFile->uri )
        );
    }
eZ\Publish\Core\IO\IOService::getInternalPath ($externalPath)
Returns the internal, handler level path to $externalPath
Parameters
string $externalPath
Returns
string
Definition at line 242 of file IOService.php.
References eZ\Publish\Core\IO\IOService\getPrefixedUri().
    {
        $path = $this->ioHandler->getInternalPath(
            $this->getPrefixedUri( $externalPath )
        );
        return $path;
    }
eZ\Publish\Core\IO\IOService::getMetadata (MetadataHandler $metadataHandler, BinaryFile $binaryFile)
Parameters
MetadataHandler $metadataHandler
BinaryFile $binaryFile
Returns
array
Definition at line 266 of file IOService.php.
References eZ\Publish\Core\IO\IOService\getPrefixedUri().
    {
        return $this->ioHandler->getMetadata(
            $metadataHandler,
            $this->getPrefixedUri( $binaryFile->uri )
        );
    }
eZ\Publish\Core\IO\IOService::getPrefixedUri ($uri) protected
Returns $uri prefixed with what is configured in the service
Parameters
string $uri
Returns
string
Definition at line 328 of file IOService.php.
    {
        $prefix = '';
        if ( isset( $this->settings['prefix'] ) )
            $prefix = $this->settings['prefix'] . DIRECTORY_SEPARATOR;
        return $prefix . $uri;
    }
eZ\Publish\Core\IO\IOService::loadBinaryFile ($uri)
Loads the binary file with $id
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentValue If the id is invalid
Parameters
string $uri
Returns
BinaryFile|bool the file, or false if it doesn't exist
Definition at line 178 of file IOService.php.
References eZ\Publish\Core\IO\IOService\buildDomainBinaryFileObject(), and eZ\Publish\Core\IO\IOService\getPrefixedUri().
    {
        if ( empty( $uri ) || !is_string( $uri ) )
            throw new InvalidArgumentValue( "binaryFileId", $uri );
        // @todo An absolute path can in no case be loaded, but throwing an exception is a bit too much at this stage
        if ( $uri[0] === '/' )
            return false;
        try
        {
            $spiBinaryFile = $this->ioHandler->load( $this->getPrefixedUri( $uri ) );
        }
        catch ( NotFoundException $e )
        {
            return false;
        }
        return $this->buildDomainBinaryFileObject( $spiBinaryFile );
    }
eZ\Publish\Core\IO\IOService::newBinaryCreateStructFromLocalFile ($localFile)
Creates a BinaryFileCreateStruct object from $localFile
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException When given a non existing / unreadable file
Parameters
string $localFile Path to local file
Returns
Definition at line 101 of file IOService.php.
    {
        if ( empty( $localFile ) || !is_string( $localFile ) )
            throw new InvalidArgumentException( "localFile", "localFile has an invalid value" );
        if ( !is_file( $localFile ) || !is_readable( $localFile ) )
            throw new InvalidArgumentException( "localFile", "file does not exist or is unreadable: {$localFile}" );
        $fileHandle = fopen( $localFile, 'rb' );
        if ( $fileHandle === false )
            throw new InvalidArgumentException( "localFile", "failed to get file resource" );
        $binaryCreateStruct = new BinaryFileCreateStruct(
            array(
                'size' => filesize( $localFile ),
                'inputStream' => $fileHandle,
                'mimeType' => $this->mimeTypeDetector->getFromPath( $localFile )
            )
        );
        return $binaryCreateStruct;
    }
eZ\Publish\Core\IO\IOService::newBinaryCreateStructFromUploadedFile (array $uploadedFile)
Creates a BinaryFileCreateStruct object from the uploaded file $uploadedFile
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException When given an invalid uploaded file
Parameters
array $uploadedFile The $_POST hash of an uploaded file
Returns
Definition at line 71 of file IOService.php.
    {
        if ( !is_string( $uploadedFile['tmp_name'] ) || empty( $uploadedFile['tmp_name'] ) )
            throw new InvalidArgumentException( "uploadedFile", "uploadedFile['tmp_name'] does not exist or has invalid value" );
        if ( !is_uploaded_file( $uploadedFile['tmp_name'] ) || !is_readable( $uploadedFile['tmp_name'] ) )
            throw new InvalidArgumentException( "uploadedFile", "file was not uploaded or is unreadable" );
        $fileHandle = fopen( $uploadedFile['tmp_name'], 'rb' );
        if ( $fileHandle === false )
            throw new InvalidArgumentException( "uploadedFile", "failed to get file resource" );
        $binaryCreateStruct = new BinaryFileCreateStruct();
        $binaryCreateStruct->uri = $uploadedFile['tmp_name'];
        $binaryCreateStruct->size = $uploadedFile['size'];
        $binaryCreateStruct->inputStream = $fileHandle;
        $binaryCreateStruct->mimeType = $uploadedFile['type'];
        return $binaryCreateStruct;
    }
eZ\Publish\Core\IO\IOService::removeUriPrefix ($uri) protected
Parameters
$uri
Returns
string
Exceptions
\eZ\Publish\Core\Base\Exceptions\InvalidArgumentException
Definition at line 341 of file IOService.php.
    {
        if ( !isset( $this->settings['prefix'] ) )
        {
            return $uri;
        }
        if ( strpos( $uri, $this->settings['prefix'] . DIRECTORY_SEPARATOR ) !== 0 )
        {
            throw new InvalidArgumentException( '$uri', "Prefix {$this->settings['prefix']} not found in {$uri}" );
        }
        $uri = substr( $uri, strlen( $this->settings['prefix'] ) + 1 );
        return $uri;
    }
Member Data Documentation
eZ\Publish\Core\IO\IOService::$ioHandler protected
Definition at line 33 of file IOService.php.
eZ\Publish\Core\IO\IOService::$mimeTypeDetector protected
Definition at line 43 of file IOService.php.
eZ\Publish\Core\IO\IOService::$settings protected
Definition at line 38 of file IOService.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/IO/IOService.php