ezp-next: eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver Class Reference
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver Class Reference
Public Member Functions
__construct (SiteAccess $siteAccess, array $groupsBySiteAccess, ContainerInterface $container, $defaultNamespace, $undefinedStrategy=self::UNDEFINED_STRATEGY_EXCEPTION)
setUndefinedStrategy ($undefinedStrategy)
getUndefinedStrategy ()
hasParameter ($paramName, $namespace=null, $scope=null)
getParameter ($paramName, $namespace=null, $scope=null)
setDefaultNamespace ($defaultNamespace)
getDefaultNamespace ()
Public Attributes
const SCOPE_GLOBAL = 'global'
const SCOPE_DEFAULT = 'default'
const UNDEFINED_STRATEGY_EXCEPTION = 1
const UNDEFINED_STRATEGY_NULL = 2
Protected Attributes
$siteAccess
$groupsBySiteAccess
$container
$defaultNamespace
$undefinedStrategy
Detailed Description
This class will help you get settings for a specific scope. This is useful to get a setting for a specific siteaccess for example.
It will check the different scopes available for a given namespace to find the appropriate parameter. To work, the dynamic setting must comply internally to the following name format : "<namespace>.<scope>.parameter.name".
<namespace> is the namespace for your dynamic setting. Defaults to "ezsettings", but can be anything.
<scope> is basically the siteaccess name you want your parameter value to apply to. Can also be "global" for a global override. Another scope is used internally: "default". This is the generic fallback.
The resolve scope order is the following:
"global"
SiteAccess name
"default"
Definition at line 34 of file ConfigResolver.php.
Constructor & Destructor Documentation
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::__construct (SiteAccess $siteAccess, array $groupsBySiteAccess, ContainerInterface $container, $defaultNamespace, $undefinedStrategy = self::UNDEFINED_STRATEGY_EXCEPTION)
Parameters
\eZ\Publish\Core\MVC\Symfony\SiteAccess $siteAccess
array $groupsBySiteAccess SiteAccess groups, indexed by siteaccess.
\Symfony\Component\DependencyInjection\ContainerInterface $container
string $defaultNamespace The default namespace
int $undefinedStrategy Strategy to use when encountering undefined parameters. Must be one of
ConfigResolver::UNDEFINED_STRATEGY_EXCEPTION (throw an exception)
ConfigResolver::UNDEFINED_STRATEGY_NULL (return null)
Definition at line 77 of file ConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver\$defaultNamespace, and eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver\$undefinedStrategy.
    {
        $this->siteAccess = $siteAccess;
        $this->groupsBySiteAccess = $groupsBySiteAccess;
        $this->container = $container;
        $this->defaultNamespace = $defaultNamespace;
        $this->undefinedStrategy = $undefinedStrategy;
    }
Member Function Documentation
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::getDefaultNamespace ()
Returns
string
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 222 of file ConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver\getDefaultNamespace().
    {
        return $this->defaultNamespace;
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::getParameter ($paramName, $namespace = null, $scope = null)
Returns value for $paramName, in $namespace.
Parameters
string $paramName The parameter name, without $prefix and the current scope (i.e. siteaccess name).
string $namespace Namespace for the parameter name. If null, the default namespace will be used.
string $scope The scope you need $paramName value for. It's typically the siteaccess name. If null, the current siteaccess name will be used.
Exceptions
\eZ\Publish\Core\MVC\Exception\ParameterNotFoundException
Returns
mixed
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 151 of file ConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver\getParameter().
    {
        $namespace = $namespace ?: $this->defaultNamespace;
        $scope = $scope ?: $this->siteAccess->name;
        $triedScopes = array();
        // Global scope
        $globalScopeParamName = "$namespace." . self::SCOPE_GLOBAL . ".$paramName";
        if ( $this->container->hasParameter( $globalScopeParamName ) )
        {
            return $this->container->getParameter( $globalScopeParamName );
        }
        $triedScopes[] = self::SCOPE_GLOBAL;
        unset( $globalScopeParamName );
        // Relative scope, siteaccess wise
        $relativeScopeParamName = "$namespace.$scope.$paramName";
        if ( $this->container->hasParameter( $relativeScopeParamName ) )
        {
            return $this->container->getParameter( $relativeScopeParamName );
        }
        $triedScopes[] = $this->siteAccess->name;
        unset( $relativeScopeParamName );
        // Relative scope, siteacces group wise
        if ( isset( $this->groupsBySiteAccess[$scope] ) )
        {
            foreach ( $this->groupsBySiteAccess[$scope] as $groupName )
            {
                $relativeScopeParamName = "$namespace.$groupName.$paramName";
                if ( $this->container->hasParameter( $relativeScopeParamName ) )
                {
                    return $this->container->getParameter( $relativeScopeParamName );
                }
            }
        }
        // Default scope
        $defaultScopeParamName = "$namespace." . self::SCOPE_DEFAULT . ".$paramName";
        if ( $this->container->hasParameter( $defaultScopeParamName ) )
        {
            return $this->container->getParameter( $defaultScopeParamName );
        }
        $triedScopes[] = $this->defaultNamespace;
        unset( $defaultScopeParamName );
        // Undefined parameter
        switch ( $this->undefinedStrategy )
        {
            case self::UNDEFINED_STRATEGY_NULL:
                return null;
            case self::UNDEFINED_STRATEGY_EXCEPTION:
            default:
                throw new ParameterNotFoundException( $paramName, $namespace, $triedScopes );
        }
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::getUndefinedStrategy ()
Returns
int
Definition at line 110 of file ConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver\getUndefinedStrategy().
    {
        return $this->undefinedStrategy;
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::hasParameter ($paramName, $namespace = null, $scope = null)
Checks if $paramName exists in $namespace
Parameters
string $paramName
string $namespace If null, the default namespace should be used.
string $scope The scope you need $paramName value for. It's typically the siteaccess name. If null, the current siteaccess name will be used.
Returns
boolean
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 125 of file ConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver\hasParameter().
    {
        $namespace = $namespace ?: $this->defaultNamespace;
        $scope = $scope ?: $this->siteAccess->name;
        $defaultScopeParamName = "$namespace." . self::SCOPE_DEFAULT . ".$paramName";
        $globalScopeParamName = "$namespace." . self::SCOPE_GLOBAL . ".$paramName";
        $relativeScopeParamName = "$namespace.$scope.$paramName";
        return
            $this->container->hasParameter( $defaultScopeParamName )
            || $this->container->hasParameter( $relativeScopeParamName )
            || $this->container->hasParameter( $globalScopeParamName );
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::setDefaultNamespace ($defaultNamespace)
Changes the default namespace to look parameter into.
Parameters
string $defaultNamespace
Implements eZ\Publish\Core\MVC\ConfigResolverInterface.
Definition at line 214 of file ConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver\$defaultNamespace, and eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver\setDefaultNamespace().
    {
        $this->defaultNamespace = $defaultNamespace;
    }
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::setUndefinedStrategy ($undefinedStrategy)
Sets the strategy to use if an undefined parameter is being asked. Can be one of:
ConfigResolver::UNDEFINED_STRATEGY_EXCEPTION (throw an exception)
ConfigResolver::UNDEFINED_STRATEGY_NULL (return null)
Defaults to ConfigResolver::UNDEFINED_STRATEGY_EXCEPTION.
Parameters
int $undefinedStrategy
Definition at line 102 of file ConfigResolver.php.
References eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver\$undefinedStrategy, and eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver\setUndefinedStrategy().
    {
        $this->undefinedStrategy = $undefinedStrategy;
    }
Member Data Documentation
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::$container protected
Definition at line 55 of file ConfigResolver.php.
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::$defaultNamespace protected
Definition at line 60 of file ConfigResolver.php.
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::$groupsBySiteAccess protected
Definition at line 50 of file ConfigResolver.php.
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::$siteAccess protected
Definition at line 45 of file ConfigResolver.php.
eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::$undefinedStrategy protected
Definition at line 65 of file ConfigResolver.php.
const eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::SCOPE_DEFAULT = 'default'
Definition at line 37 of file ConfigResolver.php.
const eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::SCOPE_GLOBAL = 'global'
Definition at line 36 of file ConfigResolver.php.
const eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::UNDEFINED_STRATEGY_EXCEPTION = 1
Definition at line 39 of file ConfigResolver.php.
const eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Configuration\ConfigResolver::UNDEFINED_STRATEGY_NULL = 2
Definition at line 40 of file ConfigResolver.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver.php