ezp-next: eZ\Publish\Core\REST\Server\Controller\Section Class Reference
eZ\Publish\Core\REST\Server\Controller\Section Class Reference
Public Member Functions
__construct (SectionService $sectionService)
listSections ()
loadSectionByIdentifier ()
createSection ()
loadSection ()
updateSection ()
deleteSection ()
Public Member Functions inherited from eZ\Publish\Core\REST\Server\Controller
setInputDispatcher (InputDispatcher $inputDispatcher)
setUrlHandler (UrlHandler $urlHandler)
setRequest (HttpRequest $request)
setContainer (Container $container)
Protected Member Functions
mapToUpdateStruct (SectionCreateStruct $createStruct)
Protected Attributes
$sectionService
Protected Attributes inherited from eZ\Publish\Core\REST\Server\Controller
$request
$inputDispatcher
$urlHandler
$container
Detailed Description
Section controller
Definition at line 27 of file Section.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Server\Controller\Section::__construct (SectionService $sectionService)
Construct controller
Parameters
\eZ\Publish\API\Repository\SectionService $sectionService
Definition at line 41 of file Section.php.
References eZ\Publish\Core\REST\Server\Controller\Section\__construct().
    {
        $this->sectionService  = $sectionService;
    }
Member Function Documentation
eZ\Publish\Core\REST\Server\Controller\Section::createSection ()
Create new section
Returns
Definition at line 85 of file Section.php.
References eZ\Publish\Core\REST\Server\Controller\Section\createSection().
    {
        try
        {
            $createdSection = $this->sectionService->createSection(
                $this->inputDispatcher->parse(
                    new Message(
                        array( 'Content-Type' => $this->request->contentType ),
                        $this->request->body
                    )
                )
            );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        return new Values\CreatedSection(
            array(
                'section' => $createdSection
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Section::deleteSection ()
Delete a section by ID
Returns
Definition at line 154 of file Section.php.
References eZ\Publish\Core\REST\Server\Controller\Section\deleteSection().
    {
        $values = $this->urlHandler->parse( 'section', $this->request->path );
        $this->sectionService->deleteSection(
            $this->sectionService->loadSection( $values['section'] )
        );
        return new NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\Section::listSections ()
List sections
Returns
Definition at line 51 of file Section.php.
References eZ\Publish\Core\REST\Server\Controller\Section\listSections(), and eZ\Publish\Core\REST\Server\Controller\Section\loadSectionByIdentifier().
    {
        if ( isset( $this->request->variables['identifier'] ) )
        {
            $sections = array(
                $this->loadSectionByIdentifier()
            );
        }
        else
        {
            $sections = $this->sectionService->loadSections();
        }
        return new Values\SectionList( $sections, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\Section::loadSection ()
Loads a section
Returns
Definition at line 115 of file Section.php.
References eZ\Publish\Core\REST\Server\Controller\Section\loadSection().
    {
        $values = $this->urlHandler->parse( 'section', $this->request->path );
        return $this->sectionService->loadSection( $values['section'] );
    }
eZ\Publish\Core\REST\Server\Controller\Section::loadSectionByIdentifier ()
Loads section by identifier
Returns
Definition at line 72 of file Section.php.
References eZ\Publish\Core\REST\Server\Controller\Section\loadSectionByIdentifier().
    {
        return $this->sectionService->loadSectionByIdentifier(
            // GET variable
            $this->request->variables['identifier']
        );
    }
eZ\Publish\Core\REST\Server\Controller\Section::mapToUpdateStruct (SectionCreateStruct $createStruct) protected
Maps a SectionCreateStruct to a SectionUpdateStruct.
Needed since both structs are encoded into the same media type on input.
Parameters
\eZ\Publish\API\Repository\Values\Content\SectionCreateStruct $createStruct
Returns
Definition at line 173 of file Section.php.
References eZ\Publish\Core\REST\Server\Controller\Section\mapToUpdateStruct().
    {
        return new SectionUpdateStruct(
            array(
                'name'       => $createStruct->name,
                'identifier' => $createStruct->identifier,
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Section::updateSection ()
Updates a section
Returns
Definition at line 126 of file Section.php.
References eZ\Publish\Core\REST\Server\Controller\Section\mapToUpdateStruct(), and eZ\Publish\Core\REST\Server\Controller\Section\updateSection().
    {
        $values = $this->urlHandler->parse( 'section', $this->request->path );
        $createStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        try
        {
            return $this->sectionService->updateSection(
                $this->sectionService->loadSection( $values['section'] ),
                $this->mapToUpdateStruct( $createStruct )
            );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
    }
Member Data Documentation
eZ\Publish\Core\REST\Server\Controller\Section::$sectionService protected
Definition at line 34 of file Section.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Controller/Section.php