ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Handler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Handler Class Reference
Public Member Functions
__construct (Gateway $contentGateway, LocationGateway $locationGateway, Mapper $mapper, FieldHandler $fieldHandler)
create (CreateStruct $struct)
publish ($contentId, $versionNo, MetadataUpdateStruct $metaDataUpdateStruct)
createDraftFromVersion ($contentId, $srcVersion, $userId)
load ($id, $version, $translations=null)
loadContentInfo ($contentId)
loadVersionInfo ($contentId, $versionNo)
loadDraftsForUser ($userId)
setStatus ($contentId, $status, $version)
updateMetadata ($contentId, MetadataUpdateStruct $content)
updateContent ($contentId, $versionNo, UpdateStruct $updateStruct)
deleteContent ($contentId)
removeRawContent ($contentId)
deleteVersion ($contentId, $versionNo)
listVersions ($contentId)
copy ($contentId, $versionNo=null)
addRelation (RelationCreateStruct $createStruct)
removeRelation ($relationId)
loadRelations ($sourceContentId, $sourceContentVersionNo=null, $type=null)
loadReverseRelations ($destinationContentId, $type=null)
Public Member Functions inherited from eZ\Publish\SPI\Persistence\Content\Handler
updateContent ($contentId, $versionNo, UpdateStruct $content)
Public Attributes
$locationHandler
Protected Member Functions
internalCreate (CreateStruct $struct, $versionNo=1)
Protected Attributes
$contentGateway
$locationGateway
$mapper
$fieldHandler
Detailed Description
The Content Handler stores Content and ContentType objects.
Definition at line 25 of file Handler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Handler::__construct (Gateway $contentGateway, LocationGateway $locationGateway, Mapper $mapper, FieldHandler $fieldHandler)
Creates a new content handler.
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\Gateway $contentGateway
\eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway $locationGateway
\eZ\Publish\Core\Persistence\Legacy\Content\Mapper $mapper
\eZ\Publish\Core\Persistence\Legacy\Content\FieldHandler $fieldHandler
Definition at line 70 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\$contentGateway, eZ\Publish\Core\Persistence\Legacy\Content\Handler\$fieldHandler, eZ\Publish\Core\Persistence\Legacy\Content\Handler\$locationGateway, and eZ\Publish\Core\Persistence\Legacy\Content\Handler\$mapper.
    {
        $this->contentGateway = $contentGateway;
        $this->locationGateway = $locationGateway;
        $this->mapper = $mapper;
        $this->fieldHandler = $fieldHandler;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Handler::addRelation (RelationCreateStruct $createStruct)
Creates a relation between $sourceContentId in $sourceContentVersionNo and $destinationContentId with a specific $type.
Todo:
Should the existence verifications happen here or is this supposed to be handled at a higher level?
Parameters
\eZ\Publish\SPI\Persistence\Content\Relation\CreateStruct $createStruct
Returns
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 559 of file Handler.php.
    {
        $relation = $this->mapper->createRelationFromCreateStruct( $createStruct );
        $relation->id = $this->contentGateway->insertRelation( $createStruct );
        return $relation;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::copy ($contentId, $versionNo = null)
Copy Content with Fields and Versions from $contentId in $version.
Copies all fields from $contentId in $versionNo (or all versions if null) to a new object which is returned. Version numbers are maintained.
Todo:
Should relations be copied? Which ones?
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If content or version is not found
Parameters
mixed $contentId
mixed | null $versionNo Copy all versions if left null
Returns
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 499 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\$versionInfo, eZ\Publish\Core\Persistence\Legacy\Content\Handler\internalCreate(), eZ\Publish\Core\Persistence\Legacy\Content\Handler\listVersions(), eZ\Publish\Core\Persistence\Legacy\Content\Handler\load(), and eZ\Publish\Core\Persistence\Legacy\Content\Handler\loadContentInfo().
    {
        $currentVersionNo = isset( $versionNo ) ?
            $versionNo :
            $this->loadContentInfo( $contentId )->currentVersionNo;
        // Copy content in given version or current version
        $createStruct = $this->mapper->createCreateStructFromContent(
            $this->load( $contentId, $currentVersionNo )
        );
        $content = $this->internalCreate( $createStruct, $currentVersionNo );
        // If version was not passed also copy other versions
        if ( !isset( $versionNo ) )
        {
            foreach ( $this->listVersions( $contentId ) as $versionInfo )
            {
                if ( $versionInfo->versionNo === $currentVersionNo )
                {
                    continue;
                }
                $versionContent = $this->load( $contentId, $versionInfo->versionNo );
                $versionContent->versionInfo->contentInfo->id = $content->versionInfo->contentInfo->id;
                $versionContent->versionInfo->modificationDate = $createStruct->modified;
                $versionContent->versionInfo->creationDate = $createStruct->modified;
                $versionContent->versionInfo->id = $this->contentGateway->insertVersion(
                    $versionContent->versionInfo,
                    $versionContent->fields
                );
                $this->fieldHandler->createNewFields( $versionContent );
                // Create names
                foreach ( $versionContent->versionInfo->names as $language => $name )
                {
                    $this->contentGateway->setName(
                        $content->versionInfo->contentInfo->id,
                        $versionInfo->versionNo,
                        $name,
                        $language
                    );
                }
            }
        }
        return $content;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::create (CreateStruct $struct)
Creates a new Content entity in the storage engine.
The values contained inside the $content will form the basis of stored entity.
Will contain always a complete list of fields.
Parameters
\eZ\Publish\SPI\Persistence\Content\CreateStruct $struct Content creation struct.
Returns
Content value object
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 95 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\internalCreate().
    {
        return $this->internalCreate( $struct );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::createDraftFromVersion ($contentId, $srcVersion, $userId)
Creates a new draft version from $contentId in $version.
Copies all fields from $contentId in $srcVersion and creates a new version of the referred Content from it.
Note: When creating a new draft in the old admin interface there will also be an entry in the eznode_assignment created for the draft. This is ignored in this implementation.
Parameters
mixed $contentId
mixed $srcVersion
mixed $userId
Returns
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 215 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\$fields, and eZ\Publish\Core\Persistence\Legacy\Content\Handler\load().
    {
        $content = $this->load( $contentId, $srcVersion );
        // Create new version
        $content->versionInfo = $this->mapper->createVersionInfoForContent(
            $content,
            $this->contentGateway->getLastVersionNumber( $contentId ) + 1,
            $userId
        );
        $content->versionInfo->id = $this->contentGateway->insertVersion(
            $content->versionInfo,
            $content->fields
        );
        // Clone fields from previous version and append them to the new one
        $fields = $content->fields;
        $content->fields = array();
        foreach ( $fields as $field )
        {
            $newField = clone $field;
            $newField->versionNo = $content->versionInfo->versionNo;
            $content->fields[] = $newField;
        }
        $this->fieldHandler->createExistingFieldsInNewVersion( $content );
        // Create name
        foreach ( $content->versionInfo->names as $language => $name )
        {
            $this->contentGateway->setName(
                $contentId,
                $content->versionInfo->versionNo,
                $name,
                $language
            );
        }
        return $content;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::deleteContent ($contentId)
Deletes all versions and fields, all locations (subtree), and all relations.
Removes the relations, but not the related objects. All subtrees of the assigned nodes of this content objects are removed (recursively).
Parameters
int $contentId
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 408 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\removeRawContent().
    {
        $contentLocations = $this->contentGateway->getAllLocationIds( $contentId );
        if ( empty( $contentLocations ) )
        {
            $this->removeRawContent( $contentId );
        }
        else
        {
            foreach ( $contentLocations as $locationId )
            {
                $this->locationHandler->removeSubtree( $locationId );
            }
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::deleteVersion ($contentId, $versionNo)
Deletes given version, its fields, node assignment, relations and names.
Removes the relations, but not the related objects.
Parameters
int $contentId
int $versionNo
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 457 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\$versionInfo, and eZ\Publish\Core\Persistence\Legacy\Content\Handler\loadVersionInfo().
    {
        $versionInfo = $this->loadVersionInfo( $contentId, $versionNo );
        $this->locationGateway->deleteNodeAssignment( $contentId, $versionNo );
        $this->fieldHandler->deleteFields( $contentId, $versionInfo );
        $this->contentGateway->deleteRelations( $contentId, $versionNo );
        $this->contentGateway->deleteVersions( $contentId, $versionNo );
        $this->contentGateway->deleteNames( $contentId, $versionNo );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::internalCreate (CreateStruct $struct, $versionNo = 1) protected
Creates a new Content entity in the storage engine.
The values contained inside the $content will form the basis of stored entity.
Will contain always a complete list of fields.
Parameters
\eZ\Publish\SPI\Persistence\Content\CreateStruct $struct Content creation struct.
mixed $versionNo Used by self::copy() to maintain version numbers
Returns
Content value object
Definition at line 113 of file Handler.php.
    {
        $content = new Content();
        $content->fields = $struct->fields;
        $content->versionInfo = $this->mapper->createVersionInfoFromCreateStruct( $struct, $versionNo );
        $content->versionInfo->contentInfo->id = $this->contentGateway->insertContentObject( $struct, $versionNo );
        $content->versionInfo->id = $this->contentGateway->insertVersion(
            $content->versionInfo,
            $struct->fields
        );
        $this->fieldHandler->createNewFields( $content );
        // Create node assignments
        foreach ( $struct->locations as $location )
        {
            $location->contentId = $content->versionInfo->contentInfo->id;
            $location->contentVersion = $content->versionInfo->versionNo;
            $this->locationGateway->createNodeAssignment(
                $location,
                $location->parentId,
                LocationGateway::NODE_ASSIGNMENT_OP_CODE_CREATE
            );
        }
        // Create names
        foreach ( $content->versionInfo->names as $language => $name )
        {
            $this->contentGateway->setName(
                $content->versionInfo->contentInfo->id,
                $content->versionInfo->versionNo,
                $name,
                $language
            );
        }
        return $content;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::listVersions ($contentId)
Returns the versions for $contentId
Parameters
int $contentId
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 477 of file Handler.php.
    {
        return $this->mapper->extractVersionInfoListFromRows(
            $this->contentGateway->listVersions( $contentId )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::load ($id, $version, $translations = null)
Returns the raw data of a content object identified by $id, in a struct.
A version to load must be specified. If you want to load the current version of a content object use SearchHandler::findSingle() with the ContentId criterion.
Optionally a translation filter may be specified. If specified only the translations with the listed language codes will be retrieved. If not, all translations will be retrieved.
Parameters
int | string $id
int | string $version
string[] $translations
Returns
Content value object
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 272 of file Handler.php.
    {
        $rows = $this->contentGateway->load( $id, $version, $translations );
        if ( empty( $rows ) )
        {
            throw new NotFound( 'content', "contentId: $id, versionNo: $version" );
        }
        $contentObjects = $this->mapper->extractContentFromRows( $rows );
        $content = $contentObjects[0];
        $this->fieldHandler->loadExternalFieldData( $content );
        return $content;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::loadContentInfo ($contentId)
Returns the metadata object for a content identified by $contentId.
Parameters
int | string $contentId
Returns
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 296 of file Handler.php.
    {
        return $this->mapper->extractContentInfoFromRow(
            $this->contentGateway->loadContentInfo( $contentId )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::loadDraftsForUser ($userId)
Returns all versions with draft status created by the given $userId
Parameters
int $userId
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 333 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_DRAFT.
    {
        return $this->mapper->extractVersionInfoListFromRows(
            $this->contentGateway->listVersionsForUser( $userId, VersionInfo::STATUS_DRAFT )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::loadRelations ($sourceContentId, $sourceContentVersionNo = null, $type = null)
Loads relations from $sourceContentId. Optionally, loads only those with $type and $sourceContentVersionNo.
Parameters
mixed $sourceContentId Source Content ID
mixed | null $sourceContentVersionNo Source Content Version, null if not specified
int | null $type {
See Also
::COMMON, ::EMBED, ::LINK, ::FIELD}
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 591 of file Handler.php.
    {
        $rows = $this->contentGateway->loadRelations( $sourceContentId, $sourceContentVersionNo, $type );
        $relationObjects = $this->mapper->extractRelationsFromRows( $rows );
        return $relationObjects;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::loadReverseRelations ($destinationContentId, $type = null)
Loads relations from $contentId. Optionally, loads only those with $type.
Only loads relations against published versions.
Parameters
mixed $destinationContentId Destination Content ID
int | null $type {
See Also
::COMMON, ::EMBED, ::LINK, ::FIELD}
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 611 of file Handler.php.
    {
        $rows = $this->contentGateway->loadReverseRelations( $destinationContentId, $type );
        $relationObjects = $this->mapper->extractRelationsFromRows( $rows );
        return $relationObjects;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::loadVersionInfo ($contentId, $versionNo)
Returns the version object for a content/version identified by $contentId and $versionNo
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If version is not found
Parameters
int | string $contentId
int $versionNo Version number to load
Returns
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 313 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\$versionInfo.
    {
        $rows = $this->contentGateway->loadVersionInfo( $contentId, $versionNo );
        if ( empty( $rows ) )
        {
            throw new NotFound( 'content', $contentId );
        }
        $versionInfo = $this->mapper->extractVersionInfoListFromRows( $rows );
        return reset( $versionInfo );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::publish ($contentId, $versionNo, MetadataUpdateStruct $metaDataUpdateStruct)
Performs the publishing operations required to set the version identified by $updateStruct->versionNo and $updateStruct->id as the published one.
The publish procedure will:
Create location nodes based on the node assignments
Update the content object using the provided metadata update struct
Update the node assignments
Update location nodes of the content with the new published version
Set content and version status to published
Parameters
int $contentId
int $versionNo
\eZ\Publish\SPI\Persistence\Content\MetadataUpdateStruct $metaDataUpdateStruct
Returns
The published Content
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 171 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\$versionInfo, eZ\Publish\Core\Persistence\Legacy\Content\Handler\load(), eZ\Publish\Core\Persistence\Legacy\Content\Handler\loadVersionInfo(), eZ\Publish\Core\Persistence\Legacy\Content\Handler\setStatus(), eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_ARCHIVED, and eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_PUBLISHED.
    {
        // Archive currently published version
        $versionInfo = $this->loadVersionInfo( $contentId, $versionNo );
        if ( $versionInfo->contentInfo->currentVersionNo != $versionNo )
        {
            $this->setStatus(
                $contentId,
                VersionInfo::STATUS_ARCHIVED,
                $versionInfo->contentInfo->currentVersionNo
            );
        }
        // Set always available name for the content
        $metaDataUpdateStruct->name = $versionInfo->names[$versionInfo->contentInfo->mainLanguageCode];
        $this->contentGateway->updateContent( $contentId, $metaDataUpdateStruct );
        $this->locationGateway->createLocationsFromNodeAssignments(
            $contentId,
            $versionNo
        );
        $this->locationGateway->updateLocationsContentVersionNo( $contentId, $versionNo );
        $this->setStatus( $contentId, VersionInfo::STATUS_PUBLISHED, $versionNo );
        return $this->load( $contentId, $versionNo );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::removeRawContent ($contentId)
Deletes raw content data
Parameters
int $contentId
Definition at line 429 of file Handler.php.
References eZ\Publish\SPI\Persistence\Content\$versionInfo, eZ\Publish\Core\Persistence\Legacy\Content\Handler\listVersions(), and eZ\Publish\Core\Persistence\Legacy\Content\Handler\loadContentInfo().
    {
        $contentInfo = $this->loadContentInfo( $contentId );
        $this->locationGateway->removeElementFromTrash(
            $contentInfo->mainLocationId
        );
        $versionInfos = $this->listVersions( $contentId );
        foreach ( $versionInfos as $versionInfo )
        {
            $this->fieldHandler->deleteFields( $contentId, $versionInfo );
        }
        $this->contentGateway->deleteRelations( $contentId );
        $this->contentGateway->deleteVersions( $contentId );
        $this->contentGateway->deleteNames( $contentId );
        $this->contentGateway->deleteContent( $contentId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::removeRelation ($relationId)
Removes a relation by $relationId.
Parameters
mixed $relationId
Returns
void
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 575 of file Handler.php.
    {
        $this->contentGateway->deleteRelation( $relationId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::setStatus ($contentId, $status, $version)
Sets the status of object identified by $contentId and $version to $status.
The $status can be one of VersionInfo::STATUS_DRAFT, VersionInfo::STATUS_PUBLISHED, VersionInfo::STATUS_ARCHIVED When status is set to VersionInfo::STATUS_PUBLISHED content status is updated to ContentInfo::STATUS_PUBLISHED
Parameters
int $contentId
int $status
int $version
Returns
boolean
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 352 of file Handler.php.
    {
        return $this->contentGateway->setStatus( $contentId, $version, $status );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::updateContent ($contentId, $versionNo, UpdateStruct $updateStruct)
Updates a content version, identified by $contentId and $versionNo
Parameters
int $contentId
int $versionNo
\eZ\Publish\SPI\Persistence\Content\UpdateStruct $updateStruct
Returns
Definition at line 380 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\load().
    {
        $content = $this->load( $contentId, $versionNo );
        $this->contentGateway->updateVersion( $contentId, $versionNo, $updateStruct );
        $this->fieldHandler->updateFields( $content, $updateStruct );
        foreach ( $updateStruct->name as $language => $name )
        {
            $this->contentGateway->setName(
                $contentId,
                $versionNo,
                $name,
                $language
            );
        }
        return $this->load( $contentId, $versionNo );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Handler::updateMetadata ($contentId, MetadataUpdateStruct $content)
Updates a content object meta data, identified by $contentId
Parameters
int $contentId
\eZ\Publish\SPI\Persistence\Content\MetadataUpdateStruct $content
Returns
Implements eZ\Publish\SPI\Persistence\Content\Handler.
Definition at line 365 of file Handler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Handler\loadContentInfo().
    {
        $this->contentGateway->updateContent( $contentId, $content );
        return $this->loadContentInfo( $contentId );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Handler::$contentGateway protected
Definition at line 32 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Handler::$fieldHandler protected
Definition at line 60 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Handler::$locationGateway protected
Definition at line 39 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Handler::$locationHandler
Definition at line 46 of file Handler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Handler::$mapper protected
Definition at line 53 of file Handler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Handler.php