ezp-next: eZ\Publish\Core\REST\Server\Controller\Role Class Reference
eZ\Publish\Core\REST\Server\Controller\Role Class Reference
Public Member Functions
__construct (RoleService $roleService, UserService $userService, LocationService $locationService)
createRole ()
listRoles ()
loadRole ()
updateRole ()
deleteRole ()
loadPolicies ()
deletePolicies ()
loadPolicy ()
addPolicy ()
updatePolicy ()
deletePolicy ()
assignRoleToUser ()
assignRoleToUserGroup ()
unassignRoleFromUser ()
unassignRoleFromUserGroup ()
loadRoleAssignmentsForUser ()
loadRoleAssignmentsForUserGroup ()
loadRoleAssignmentForUser ()
loadRoleAssignmentForUserGroup ()
listPoliciesForUser ()
Public Member Functions inherited from eZ\Publish\Core\REST\Server\Controller
setInputDispatcher (InputDispatcher $inputDispatcher)
setUrlHandler (UrlHandler $urlHandler)
setRequest (HttpRequest $request)
setContainer (Container $container)
Protected Member Functions
mapToUpdateStruct (RoleCreateStruct $createStruct)
Protected Attributes
$roleService
$userService
$locationService
Protected Attributes inherited from eZ\Publish\Core\REST\Server\Controller
$request
$inputDispatcher
$urlHandler
$container
Detailed Description
Role controller
Definition at line 28 of file Role.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Server\Controller\Role::__construct (RoleService $roleService, UserService $userService, LocationService $locationService)
Construct controller
Parameters
\eZ\Publish\API\Repository\RoleService $roleService
\eZ\Publish\API\Repository\UserService $userService
\eZ\Publish\API\Repository\LocationService $locationService
Definition at line 58 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\__construct().
    {
        $this->roleService     = $roleService;
        $this->userService     = $userService;
        $this->locationService = $locationService;
    }
Member Function Documentation
eZ\Publish\Core\REST\Server\Controller\Role::addPolicy ()
Adds a policy to role
Returns
Definition at line 225 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\addPolicy().
    {
        $values = $this->urlHandler->parse( 'policies', $this->request->path );
        $createStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $role = $this->roleService->addPolicy(
            $this->roleService->loadRole( $values['role'] ),
            $createStruct
        );
        $policies = $role->getPolicies();
        $policyToReturn = $policies[0];
        for ( $i = 1, $count = count( $policies ); $i < $count; $i++ )
        {
            if ( $policies[$i]->id > $policyToReturn->id )
                $policyToReturn = $policies[$i];
        }
        return new Values\CreatedPolicy(
            array(
                'policy' => $policyToReturn
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Role::assignRoleToUser ()
Assigns role to user
Returns
Definition at line 321 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\assignRoleToUser().
    {
        $values = $this->urlHandler->parse( 'userRoleAssignments', $this->request->path );
        $roleAssignment = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $user = $this->userService->loadUser( $values['user'] );
        $role = $this->roleService->loadRole( $roleAssignment->roleId );
        $this->roleService->assignRoleToUser( $role, $user, $roleAssignment->limitation );
        $roleAssignments = $this->roleService->getRoleAssignmentsForUser( $user );
        return new Values\RoleAssignmentList( $roleAssignments, $user->id );
    }
eZ\Publish\Core\REST\Server\Controller\Role::assignRoleToUserGroup ()
Assigns role to user group
Returns
Definition at line 346 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\assignRoleToUserGroup().
    {
        $values = $this->urlHandler->parse( 'groupRoleAssignments', $this->request->path );
        $roleAssignment = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $groupLocationParts = explode( '/', $values['group'] );
        $groupLocation = $this->locationService->loadLocation( array_pop( $groupLocationParts ) );
        $userGroup = $this->userService->loadUserGroup( $groupLocation->contentId );
        $role = $this->roleService->loadRole( $roleAssignment->roleId );
        $this->roleService->assignRoleToUserGroup( $role, $userGroup, $roleAssignment->limitation );
        $roleAssignments = $this->roleService->getRoleAssignmentsForUserGroup( $userGroup );
        return new Values\RoleAssignmentList( $roleAssignments, $values['group'], true );
    }
eZ\Publish\Core\REST\Server\Controller\Role::createRole ()
Create new role
Returns
Definition at line 71 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\createRole().
    {
        return new Values\CreatedRole(
            array(
                'role' => $this->roleService->createRole(
                    $this->inputDispatcher->parse(
                        new Message(
                            array( 'Content-Type' => $this->request->contentType ),
                            $this->request->body
                        )
                    )
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Role::deletePolicies ()
Deletes all policies from a role
Returns
Definition at line 187 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\deletePolicies().
    {
        $values = $this->urlHandler->parse( 'policies', $this->request->path );
        $loadedRole = $this->roleService->loadRole( $values['role'] );
        foreach ( $loadedRole->getPolicies() as $rolePolicy )
        {
            $this->roleService->removePolicy( $loadedRole, $rolePolicy );
        }
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\Role::deletePolicy ()
Delete a policy from role
Returns
Definition at line 291 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\deletePolicy().
    {
        $values = $this->urlHandler->parse( 'policy', $this->request->path );
        $role = $this->roleService->loadRole( $values['role'] );
        $policy = null;
        foreach ( $role->getPolicies() as $rolePolicy )
        {
            if ( $rolePolicy->id == $values['policy'] )
            {
                $policy = $rolePolicy;
                break;
            }
        }
        if ( $policy !== null )
        {
            $this->roleService->removePolicy( $role, $policy );
            return new Values\NoContent();
        }
        throw new Exceptions\NotFoundException( "Policy not found: '{$this->request->path}'." );
    }
eZ\Publish\Core\REST\Server\Controller\Role::deleteRole ()
Delete a role by ID
Returns
Definition at line 158 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\deleteRole().
    {
        $values = $this->urlHandler->parse( 'role', $this->request->path );
        $this->roleService->deleteRole(
            $this->roleService->loadRole( $values['role'] )
        );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\Role::listPoliciesForUser ()
Search all policies which are applied to a given user
Returns
Definition at line 492 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\listPoliciesForUser().
    {
        return new Values\PolicyList(
            $this->roleService->loadPoliciesByUserId(
                $this->request->variables['userId']
            ),
            $this->request->path
        );
    }
eZ\Publish\Core\REST\Server\Controller\Role::listRoles ()
Loads list of roles
Returns
Definition at line 92 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\listRoles().
    {
        $roles = array();
        if ( isset( $this->request->variables['identifier'] ) )
        {
            try
            {
                $role = $this->roleService->loadRoleByIdentifier( $this->request->variables['identifier'] );
                $roles[] = $role;
            }
            catch ( APINotFoundException $e )
            {
                // Do nothing
            }
        }
        else
        {
            $offset = isset( $this->request->variables['offset'] ) ? (int)$this->request->variables['offset'] : 0;
            $limit = isset( $this->request->variables['limit'] ) ? (int)$this->request->variables['limit'] : -1;
            $roles = array_slice(
                $this->roleService->loadRoles(),
                $offset >= 0 ? $offset : 0,
                $limit >= 0 ? $limit : null
            );
        }
        return new Values\RoleList( $roles, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\Role::loadPolicies ()
Loads the policies for the role
Returns
Definition at line 173 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\loadPolicies().
    {
        $values = $this->urlHandler->parse( 'policies', $this->request->path );
        $loadedRole = $this->roleService->loadRole( $values['role'] );
        return new Values\PolicyList( $loadedRole->getPolicies(), $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\Role::loadPolicy ()
Loads a policy
Returns
Definition at line 206 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\loadPolicy().
    {
        $values = $this->urlHandler->parse( 'policy', $this->request->path );
        $loadedRole = $this->roleService->loadRole( $values['role'] );
        foreach ( $loadedRole->getPolicies() as $policy )
        {
            if ( $policy->id == $values['policy'] )
                return $policy;
        }
        throw new Exceptions\NotFoundException( "Policy not found: '{$this->request->path}'." );
    }
eZ\Publish\Core\REST\Server\Controller\Role::loadRole ()
Loads role
Returns
Definition at line 127 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\loadRole().
    {
        $values = $this->urlHandler->parse( 'role', $this->request->path );
        return $this->roleService->loadRole( $values['role'] );
    }
eZ\Publish\Core\REST\Server\Controller\Role::loadRoleAssignmentForUser ()
Returns a role assignment to the given user
Returns
Definition at line 444 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\loadRoleAssignmentForUser().
    {
        $values = $this->urlHandler->parse( 'userRoleAssignment', $this->request->path );
        $user = $this->userService->loadUser( $values['user'] );
        $roleAssignments = $this->roleService->getRoleAssignmentsForUser( $user );
        foreach ( $roleAssignments as $roleAssignment )
        {
            if ( $roleAssignment->getRole()->id == $values['role'] )
            {
                return new Values\RestUserRoleAssignment( $roleAssignment, $values['user'] );
            }
        }
        throw new Exceptions\NotFoundException( "Role assignment not found: '{$this->request->path}'." );
    }
eZ\Publish\Core\REST\Server\Controller\Role::loadRoleAssignmentForUserGroup ()
Returns a role assignment to the given user group
Returns
Definition at line 467 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\loadRoleAssignmentForUserGroup().
    {
        $values = $this->urlHandler->parse( 'groupRoleAssignment', $this->request->path );
        $groupLocationParts = explode( '/', $values['group'] );
        $groupLocation = $this->locationService->loadLocation( array_pop( $groupLocationParts ) );
        $userGroup = $this->userService->loadUserGroup( $groupLocation->contentId );
        $roleAssignments = $this->roleService->getRoleAssignmentsForUserGroup( $userGroup );
        foreach ( $roleAssignments as $roleAssignment )
        {
            if ( $roleAssignment->getRole()->id == $values['role'] )
            {
                return new Values\RestUserGroupRoleAssignment( $roleAssignment, $values['group'] );
            }
        }
        throw new Exceptions\NotFoundException( "Role assignment not found: '{$this->request->path}'." );
    }
eZ\Publish\Core\REST\Server\Controller\Role::loadRoleAssignmentsForUser ()
Loads role assignments for user
Returns
Definition at line 411 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\loadRoleAssignmentsForUser().
    {
        $values = $this->urlHandler->parse( 'userRoleAssignments', $this->request->path );
        $user = $this->userService->loadUser( $values['user'] );
        $roleAssignments = $this->roleService->getRoleAssignmentsForUser( $user );
        return new Values\RoleAssignmentList( $roleAssignments, $user->id );
    }
eZ\Publish\Core\REST\Server\Controller\Role::loadRoleAssignmentsForUserGroup ()
Loads role assignments for user group
Returns
Definition at line 426 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\loadRoleAssignmentsForUserGroup().
    {
        $values = $this->urlHandler->parse( 'groupRoleAssignments', $this->request->path );
        $groupLocationParts = explode( '/', $values['group'] );
        $groupLocation = $this->locationService->loadLocation( array_pop( $groupLocationParts ) );
        $userGroup = $this->userService->loadUserGroup( $groupLocation->contentId );
        $roleAssignments = $this->roleService->getRoleAssignmentsForUserGroup( $userGroup );
        return new Values\RoleAssignmentList( $roleAssignments, $values['group'], true );
    }
eZ\Publish\Core\REST\Server\Controller\Role::mapToUpdateStruct (RoleCreateStruct $createStruct) protected
Maps a RoleCreateStruct to a RoleUpdateStruct.
Needed since both structs are encoded into the same media type on input.
Parameters
\eZ\Publish\API\Repository\Values\User\RoleCreateStruct $createStruct
Returns
Definition at line 511 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\mapToUpdateStruct().
    {
        return new RoleUpdateStruct(
            array(
                'identifier' => $createStruct->identifier
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Role::unassignRoleFromUser ()
Un-assigns role from user
Returns
Definition at line 373 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\unassignRoleFromUser().
    {
        $values = $this->urlHandler->parse( 'userRoleAssignment', $this->request->path );
        $user = $this->userService->loadUser( $values['user'] );
        $role = $this->roleService->loadRole( $values['role'] );
        $this->roleService->unassignRoleFromUser( $role, $user );
        $roleAssignments = $this->roleService->getRoleAssignmentsForUser( $user );
        return new Values\RoleAssignmentList( $roleAssignments, $user->id );
    }
eZ\Publish\Core\REST\Server\Controller\Role::unassignRoleFromUserGroup ()
Un-assigns role from user group
Returns
Definition at line 391 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\unassignRoleFromUserGroup().
    {
        $values = $this->urlHandler->parse( 'groupRoleAssignment', $this->request->path );
        $groupLocationParts = explode( '/', $values['group'] );
        $groupLocation = $this->locationService->loadLocation( array_pop( $groupLocationParts ) );
        $userGroup = $this->userService->loadUserGroup( $groupLocation->contentId );
        $role = $this->roleService->loadRole( $values['role'] );
        $this->roleService->unassignRoleFromUserGroup( $role, $userGroup );
        $roleAssignments = $this->roleService->getRoleAssignmentsForUserGroup( $userGroup );
        return new Values\RoleAssignmentList( $roleAssignments, $values['group'], true );
    }
eZ\Publish\Core\REST\Server\Controller\Role::updatePolicy ()
Updates a policy
Returns
Definition at line 261 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\updatePolicy().
    {
        $values = $this->urlHandler->parse( 'policy', $this->request->path );
        $updateStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $role = $this->roleService->loadRole( $values['role'] );
        foreach ( $role->getPolicies() as $policy )
        {
            if ( $policy->id == $values['policy'] )
            {
                return $this->roleService->updatePolicy(
                    $policy,
                    $updateStruct
                );
            }
        }
        throw new Exceptions\NotFoundException( "Policy not found: '{$this->request->path}'." );
    }
eZ\Publish\Core\REST\Server\Controller\Role::updateRole ()
Updates a role
Returns
Definition at line 138 of file Role.php.
References eZ\Publish\Core\REST\Server\Controller\Role\mapToUpdateStruct(), and eZ\Publish\Core\REST\Server\Controller\Role\updateRole().
    {
        $values = $this->urlHandler->parse( 'role', $this->request->path );
        $createStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        return $this->roleService->updateRole(
            $this->roleService->loadRole( $values['role'] ),
            $this->mapToUpdateStruct( $createStruct )
        );
    }
Member Data Documentation
eZ\Publish\Core\REST\Server\Controller\Role::$locationService protected
Definition at line 49 of file Role.php.
eZ\Publish\Core\REST\Server\Controller\Role::$roleService protected
Definition at line 35 of file Role.php.
eZ\Publish\Core\REST\Server\Controller\Role::$userService protected
Definition at line 42 of file Role.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Controller/Role.php