ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper Class Reference
Public Member Functions
__construct (ConverterRegistry $converterRegistry)
createGroupFromCreateStruct (GroupCreateStruct $struct)
extractGroupsFromRows (array $rows)
extractTypesFromRows (array $rows)
extractFieldFromRow (array $row)
createTypeFromCreateStruct (CreateStruct $createStruct)
createCreateStructFromType (Type $type)
toStorageFieldDefinition (FieldDefinition $fieldDef, StorageFieldDefinition $storageFieldDef)
toFieldDefinition (StorageFieldDefinition $storageFieldDef, FieldDefinition $fieldDef)
Protected Member Functions
extractTypeFromRow (array $row)
extractStorageFieldFromRow (array $row)
Protected Attributes
$converterRegistry
Detailed Description
Mapper for Content Type Handler.
Performs mapping of Type objects.
Definition at line 25 of file Mapper.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::__construct (ConverterRegistry $converterRegistry)
Creates a new content type mapper
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\ConverterRegistry $converterRegistry
Definition at line 39 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Mapper\$converterRegistry.
    {
        $this->converterRegistry = $converterRegistry;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::createCreateStructFromType (Type $type)
Creates a create struct from an existing $type.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type $type
Returns
Definition at line 300 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\createCreateStructFromType().
    {
        $createStruct = new CreateStruct();
        $createStruct->name = $type->name;
        $createStruct->status = $type->status;
        $createStruct->description = $type->description;
        $createStruct->identifier = $type->identifier;
        $createStruct->created = $type->created;
        $createStruct->modified = $type->modified;
        $createStruct->creatorId = $type->creatorId;
        $createStruct->modifierId = $type->modifierId;
        $createStruct->remoteId = $type->remoteId;
        $createStruct->urlAliasSchema = $type->urlAliasSchema;
        $createStruct->nameSchema = $type->nameSchema;
        $createStruct->isContainer = $type->isContainer;
        $createStruct->initialLanguageId = $type->initialLanguageId;
        $createStruct->groupIds = $type->groupIds;
        $createStruct->fieldDefinitions = $type->fieldDefinitions;
        $createStruct->defaultAlwaysAvailable = $type->defaultAlwaysAvailable;
        $createStruct->sortField = $type->sortField;
        $createStruct->sortOrder = $type->sortOrder;
        return $createStruct;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::createGroupFromCreateStruct (GroupCreateStruct $struct)
Creates a Group from its create struct.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\Group\CreateStruct $struct
Todo:
$description is not supported by database, yet
Returns
Group
Definition at line 53 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\createGroupFromCreateStruct().
    {
        $group = new Group();
        $group->name = $struct->name;
        // Intentionally left out, since DB structure does not support it, yet
        // $group->description = $struct->description;
        $group->identifier = $struct->identifier;
        $group->created = $struct->created;
        $group->modified = $struct->modified;
        $group->creatorId = $struct->creatorId;
        $group->modifierId = $struct->modifierId;
        return $group;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::createTypeFromCreateStruct (CreateStruct $createStruct)
Maps properties from $struct to $type.
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\CreateStruct $createStruct
Returns
Definition at line 267 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\createTypeFromCreateStruct().
    {
        $type = new Type();
        $type->name = $createStruct->name;
        $type->status = $createStruct->status;
        $type->description = $createStruct->description;
        $type->identifier = $createStruct->identifier;
        $type->created = $createStruct->created;
        $type->modified = $createStruct->modified;
        $type->creatorId = $createStruct->creatorId;
        $type->modifierId = $createStruct->modifierId;
        $type->remoteId = $createStruct->remoteId;
        $type->urlAliasSchema = $createStruct->urlAliasSchema;
        $type->nameSchema = $createStruct->nameSchema;
        $type->isContainer = $createStruct->isContainer;
        $type->initialLanguageId = $createStruct->initialLanguageId;
        $type->groupIds = $createStruct->groupIds;
        $type->fieldDefinitions = $createStruct->fieldDefinitions;
        $type->defaultAlwaysAvailable = $createStruct->defaultAlwaysAvailable;
        $type->sortField = $createStruct->sortField;
        $type->sortOrder = $createStruct->sortOrder;
        return $type;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::extractFieldFromRow (array $row)
Creates a FieldDefinition from the data in $row.
Parameters
array $row
Returns
Definition at line 184 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\extractStorageFieldFromRow(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\toFieldDefinition().
    {
        $storageFieldDef = $this->extractStorageFieldFromRow( $row );
        $field = new FieldDefinition();
        $field->id = (int)$row['ezcontentclass_attribute_id'];
        $field->name = unserialize( $row['ezcontentclass_attribute_serialized_name_list'] );
        $field->description = unserialize( $row['ezcontentclass_attribute_serialized_description_list'] );
        // Unset redundant data
        unset(
            $field->name["always-available"],
            $field->name[0],
            $field->description["always-available"],
            $field->description[0]
        );
        $field->identifier = $row['ezcontentclass_attribute_identifier'];
        $field->fieldGroup = $row['ezcontentclass_attribute_category'];
        $field->fieldType = $row['ezcontentclass_attribute_data_type_string'];
        $field->isTranslatable = ( $row['ezcontentclass_attribute_can_translate'] == 1 );
        $field->isRequired = $row['ezcontentclass_attribute_is_required'] == 1;
        $field->isInfoCollector = $row['ezcontentclass_attribute_is_information_collector'] == 1;
        $field->isSearchable = (bool)$row['ezcontentclass_attribute_is_searchable'];
        $field->position = (int)$row['ezcontentclass_attribute_placement'];
        $this->toFieldDefinition( $storageFieldDef, $field );
        return $field;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::extractGroupsFromRows (array $rows)
Extracts Group objects from the given $rows.
Parameters
array $rows
Returns
[]
Definition at line 78 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\extractGroupsFromRows().
    {
        $groups = array();
        foreach ( $rows as $row )
        {
            $group = new Group();
            $group->id = (int)$row['id'];
            $group->created = (int)$row['created'];
            $group->creatorId = (int)$row['creator_id'];
            $group->modified = (int)$row['modified'];
            $group->modifierId = (int)$row['modifier_id'];
            $group->identifier = $row['name'];
            $groups[] = $group;
        }
        return $groups;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::extractStorageFieldFromRow (array $row) protected
Extracts a StorageFieldDefinition from $row
Parameters
array $row
Returns
Definition at line 222 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\extractStorageFieldFromRow().
    {
        $storageFieldDef = new StorageFieldDefinition();
        $storageFieldDef->dataFloat1 = isset( $row['ezcontentclass_attribute_data_float1'] )
            ? (float)$row['ezcontentclass_attribute_data_float1']
            : null;
        $storageFieldDef->dataFloat2 = isset( $row['ezcontentclass_attribute_data_float2'] )
            ? (float)$row['ezcontentclass_attribute_data_float2']
            : null;
        $storageFieldDef->dataFloat3 = isset( $row['ezcontentclass_attribute_data_float3'] )
            ? (float)$row['ezcontentclass_attribute_data_float3']
            : null;
        $storageFieldDef->dataFloat4 = isset( $row['ezcontentclass_attribute_data_float4'] )
            ? (float)$row['ezcontentclass_attribute_data_float4']
            : null;
        $storageFieldDef->dataInt1 = isset( $row['ezcontentclass_attribute_data_int1'] )
            ? (int)$row['ezcontentclass_attribute_data_int1']
            : null;
        $storageFieldDef->dataInt2 = isset( $row['ezcontentclass_attribute_data_int2'] )
            ? (int)$row['ezcontentclass_attribute_data_int2']
            : null;
        $storageFieldDef->dataInt3 = isset( $row['ezcontentclass_attribute_data_int3'] )
            ? (int)$row['ezcontentclass_attribute_data_int3']
            : null;
        $storageFieldDef->dataInt4 = isset( $row['ezcontentclass_attribute_data_int4'] )
            ? (int)$row['ezcontentclass_attribute_data_int4']
            : null;
        $storageFieldDef->dataText1 = $row['ezcontentclass_attribute_data_text1'];
        $storageFieldDef->dataText2 = $row['ezcontentclass_attribute_data_text2'];
        $storageFieldDef->dataText3 = $row['ezcontentclass_attribute_data_text3'];
        $storageFieldDef->dataText4 = $row['ezcontentclass_attribute_data_text4'];
        $storageFieldDef->dataText5 = $row['ezcontentclass_attribute_data_text5'];
        $storageFieldDef->serializedDataText = $row['ezcontentclass_attribute_serialized_data_text'];
        return $storageFieldDef;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::extractTypeFromRow (array $row) protected
Creates a Type from the data in $row.
Parameters
array $row
Returns
Type
Definition at line 142 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\extractTypeFromRow().
    {
        $type = new Type();
        $type->id = (int)$row['ezcontentclass_id'];
        $type->status = (int)$row['ezcontentclass_version'];
        $type->name = unserialize( $row['ezcontentclass_serialized_name_list'] );
        $type->description = unserialize( $row['ezcontentclass_serialized_description_list'] );
        // Unset redundant data
        unset(
            $type->name["always-available"],
            $type->name[0],
            $type->description["always-available"],
            $type->description[0]
        );
        $type->identifier = $row['ezcontentclass_identifier'];
        $type->created = (int)$row['ezcontentclass_created'];
        $type->modified = (int)$row['ezcontentclass_modified'];
        $type->modifierId = (int)$row['ezcontentclass_modifier_id'];
        $type->creatorId = (int)$row['ezcontentclass_creator_id'];
        $type->remoteId = $row['ezcontentclass_remote_id'];
        $type->urlAliasSchema = $row['ezcontentclass_url_alias_name'];
        $type->nameSchema = $row['ezcontentclass_contentobject_name'];
        $type->isContainer = ( $row['ezcontentclass_is_container'] == 1 );
        $type->initialLanguageId = (int)$row['ezcontentclass_initial_language_id'];
        $type->defaultAlwaysAvailable = ( $row['ezcontentclass_always_available'] == 1 );
        $type->sortField = (int)$row['ezcontentclass_sort_field'];
        $type->sortOrder = (int)$row['ezcontentclass_sort_order'];
        $type->groupIds = array();
        $type->fieldDefinitions = array();
        return $type;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::extractTypesFromRows (array $rows)
Extracts types and related data from the given $rows.
Parameters
array $rows
Returns
array(Type)
Definition at line 105 of file Mapper.php.
References eZ\Publish\SPI\Persistence\Content\$fields, eZ\Publish\Core\Persistence\Legacy\Content\Mapper\extractFieldFromRow(), eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\extractTypeFromRow(), and eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\extractTypesFromRows().
    {
        $types = array();
        $fields = array();
        foreach ( $rows as $row )
        {
            $typeId = (int)$row['ezcontentclass_id'];
            if ( !isset( $types[$typeId] ) )
            {
                $types[$typeId] = $this->extractTypeFromRow( $row );
            }
            $fieldId = (int)$row['ezcontentclass_attribute_id'];
            if ( !isset( $fields[$fieldId] ) )
            {
                $types[$typeId]->fieldDefinitions[] = $fields[$fieldId] = $this->extractFieldFromRow( $row );
            }
            $groupId = (int)$row['ezcontentclass_classgroup_group_id'];
            if ( !in_array( $groupId, $types[$typeId]->groupIds ) )
            {
                $types[$typeId]->groupIds[] = $groupId;
            }
        }
        // Re-index $types to avoid people relying on ID keys
        return array_values( $types );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::toFieldDefinition (StorageFieldDefinition $storageFieldDef, FieldDefinition $fieldDef)
Maps a FieldDefinition from the given $storageFieldDef
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageFieldDef
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDef
Returns
void
Definition at line 354 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\toFieldDefinition().
    {
        $converter = $this->converterRegistry->getConverter(
            $fieldDef->fieldType
        );
        $converter->toFieldDefinition(
            $storageFieldDef,
            $fieldDef
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::toStorageFieldDefinition (FieldDefinition $fieldDef, StorageFieldDefinition $storageFieldDef)
Maps $fieldDef to the legacy storage specific StorageFieldDefinition
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDef
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageFieldDef
Returns
void
Definition at line 334 of file Mapper.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper\toStorageFieldDefinition().
    {
        $converter = $this->converterRegistry->getConverter(
            $fieldDef->fieldType
        );
        $converter->toStorageFieldDefinition(
            $fieldDef,
            $storageFieldDef
        );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::$converterRegistry protected
Definition at line 32 of file Mapper.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Type/Mapper.php