ezp-next: eZ\Publish\Core\IO\Handler\InMemory Class Reference
eZ\Publish\Core\IO\Handler\InMemory Class Reference
Public Member Functions
__construct (array $storage=array())
create (BinaryFileCreateStruct $createStruct)
delete ($uri)
update ($uri, BinaryFileUpdateStruct $updateFileStruct)
exists ($uri)
load ($uri)
getFileResource ($uri)
getFileContents ($uri)
getInternalPath ($path)
getExternalPath ($path)
getMetadata (MetadataHandler $metadataHandler, $path)
Public Member Functions inherited from eZ\Publish\Core\IO\Handler
create (BinaryFileCreateStruct $createStruct)
Detailed Description
Backend interface for handling of binary files I/O in memory
Definition at line 24 of file InMemory.php.
Constructor & Destructor Documentation
eZ\Publish\Core\IO\Handler\InMemory::__construct (array $storage = array())
Definition at line 41 of file InMemory.php.
References eZ\Publish\Core\IO\Handler\InMemory\__construct().
    {
        $this->storage = $storage;
    }
Member Function Documentation
eZ\Publish\Core\IO\Handler\InMemory::create (BinaryFileCreateStruct $createStruct)
Creates and stores a new BinaryFile based on the BinaryFileCreateStruct $file
Exceptions
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the target path already exists
Parameters
BinaryFileCreateStruct $createStruct
Returns
BinaryFile The newly created BinaryFile object
Definition at line 55 of file InMemory.php.
References eZ\Publish\SPI\IO\BinaryFileCreateStruct\getInputStream().
    {
        if ( isset( $this->storage[$createStruct->uri] ) )
        {
            throw new InvalidArgumentException(
                "\$createFilestruct->uri",
                "file '{$createStruct->uri}' already exists"
            );
        }
        $this->data[$createStruct->uri] = base64_encode(
            fread( $createStruct->getInputStream(), $createStruct->size )
        );
        $binaryFile = new BinaryFile();
        $binaryFile->uri = $createStruct->uri;
        $binaryFile->mtime = new DateTime;
        $binaryFile->size = $createStruct->size;
        return $this->storage[$binaryFile->uri] = $binaryFile;
    }
eZ\Publish\Core\IO\Handler\InMemory::delete ($uri)
Deletes the existing BinaryFile with path $uri
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If the file doesn't exist
Parameters
string $uri
Implements eZ\Publish\Core\IO\Handler.
Definition at line 84 of file InMemory.php.
    {
        if ( !isset( $this->storage[$uri] ) )
        {
            throw new NotFoundException( 'BinaryFile', $uri );
        }
        unset( $this->storage[$uri] );
        unset( $this->data[$uri] );
    }
eZ\Publish\Core\IO\Handler\InMemory::exists ($uri)
Checks if the BinaryFile with path $path exists
Parameters
string $path
Returns
boolean
Implements eZ\Publish\Core\IO\Handler.
Definition at line 163 of file InMemory.php.
    {
        return isset( $this->storage[$uri] );
    }
eZ\Publish\Core\IO\Handler\InMemory::getExternalPath ($path)
Removes the internal storage path from $path
Parameters
string $path
Returns
string
Implements eZ\Publish\Core\IO\Handler.
Definition at line 229 of file InMemory.php.
    {
        if ( substr( $path, 0, strlen( $this->storagePrefix ) ) != $this->storagePrefix )
        {
            throw new InvalidArgumentException( '$path', "Storage prefix" );
        }
        return substr( $path, strlen( $this->storagePrefix ) + 1 );
    }
eZ\Publish\Core\IO\Handler\InMemory::getFileContents ($uri)
Returns the contents of the BinaryFile identified by $path
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException if the file couldn't be found
Parameters
string $uri
Returns
string
Implements eZ\Publish\Core\IO\Handler.
Definition at line 215 of file InMemory.php.
    {
        if ( !isset( $this->storage[$uri] ) )
        {
            throw new NotFoundException( 'BinaryFile', $uri );
        }
        return base64_decode( $this->data[$uri] );
    }
eZ\Publish\Core\IO\Handler\InMemory::getFileResource ($uri)
Returns a file resource to the BinaryFile identified by $uri
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If no file identified by $path exists
Parameters
string $uri
Returns
resource
Implements eZ\Publish\Core\IO\Handler.
Definition at line 195 of file InMemory.php.
    {
        if ( !isset( $this->storage[$uri] ) )
        {
            throw new NotFoundException( 'BinaryFile', $uri );
        }
        $uri = 'data://' . $this->storage[$uri]->mimeType . ';base64,' . $this->data[$uri];
        return fopen( $uri, 'rb' );
    }
eZ\Publish\Core\IO\Handler\InMemory::getInternalPath ($path)
Returns the internal, handler level path for $path
Parameters
string $path
Returns
string
Implements eZ\Publish\Core\IO\Handler.
Definition at line 224 of file InMemory.php.
    {
        return $this->storagePrefix . $path;
    }
eZ\Publish\Core\IO\Handler\InMemory::getMetadata (MetadataHandler $metadataHandler, $path)
Executes $metadataHandler on $path, and returns the metadata array
Parameters
MetadataHandler $metadataHandler
string $path
Returns
array
Implements eZ\Publish\Core\IO\Handler.
Definition at line 239 of file InMemory.php.
References eZ\Publish\Core\IO\MetadataHandler\extract(), and eZ\Publish\Core\IO\Handler\getInternalPath().
    {
        // @todo This won't work. InternalPath is NOT a path. Need to write it to disk somehow.
        return $metadataHandler->extract( $this->getInternalPath( $path ) );
    }
eZ\Publish\Core\IO\Handler\InMemory::load ($uri)
Loads the BinaryFile identified by $uri
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If no file identified by $path exists
Parameters
string $uri
Returns
Implements eZ\Publish\Core\IO\Handler.
Definition at line 177 of file InMemory.php.
    {
        if ( !isset( $this->storage[$uri] ) )
        {
            throw new NotFoundException( 'BinaryFile', $uri );
        }
        return $this->storage[$uri];
    }
eZ\Publish\Core\IO\Handler\InMemory::update ($uri, BinaryFileUpdateStruct $updateFileStruct)
Updates the file identified by $path with data from $updateFile
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If the source path doesn't exist
\eZ\Publish\API\Repository\Exceptions\InvalidArgumentException If the target path already exists
Parameters
string $path
\eZ\Publish\Core\IO\Values\BinaryFileUpdateStruct $updateFileStruct
Returns
The updated BinaryFile
Implements eZ\Publish\Core\IO\Handler.
Definition at line 106 of file InMemory.php.
References eZ\Publish\SPI\IO\BinaryFileUpdateStruct\getInputStream().
    {
        if ( !isset( $this->storage[$uri] ) )
        {
            throw new NotFoundException( 'BinaryFile', $uri );
        }
        // path
        if ( $updateFileStruct->uri !== null && $updateFileStruct->uri != $uri )
        {
            if ( isset( $this->storage[$updateFileStruct->uri] ) )
            {
                throw new InvalidArgumentException(
                    "\$updateFileStruct->uri",
                    "file '{$updateFileStruct->uri}' already exists"
                );
            }
            $oldUri = $uri;
            $newUri = $updateFileStruct->uri;
            $this->storage[$newUri] = $this->storage[$oldUri];
            $this->data[$newUri] = $this->data[$oldUri];
            $this->storage[$newUri]->uri = $newUri;
            unset( $this->storage[$oldUri] );
            unset( $this->data[$oldUri] );
            $uri = $newUri;
        }
        $resource = $updateFileStruct->getInputStream();
        if ( $resource !== null )
        {
            $this->data[$uri] = base64_encode( fread( $resource, $updateFileStruct->size ) );
            if ( $updateFileStruct->size !== null )
            {
                $this->storage[$uri]->size = $updateFileStruct->size;
            }
        }
        if ( $updateFileStruct->mtime !== null && $updateFileStruct->mtime !== $this->storage[$uri]->mtime )
        {
            $this->storage[$uri]->mtime = $updateFileStruct->mtime;
        }
        return $this->storage[$uri];
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/IO/Handler/InMemory.php