ezp-next: eZ\Publish\Core\REST\Server\Controller\URLWildcard Class Reference
eZ\Publish\Core\REST\Server\Controller\URLWildcard Class Reference
Public Member Functions
__construct (URLWildcardService $urlWildcardService)
loadURLWildcard ()
listURLWildcards ()
createURLWildcard ()
deleteURLWildcard ()
Public Member Functions inherited from eZ\Publish\Core\REST\Server\Controller
setInputDispatcher (InputDispatcher $inputDispatcher)
setUrlHandler (UrlHandler $urlHandler)
setRequest (HttpRequest $request)
setContainer (Container $container)
Protected Attributes
$urlWildcardService
Protected Attributes inherited from eZ\Publish\Core\REST\Server\Controller
$request
$inputDispatcher
$urlHandler
$container
Detailed Description
URLWildcard controller
Definition at line 23 of file URLWildcard.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Server\Controller\URLWildcard::__construct (URLWildcardService $urlWildcardService)
Construct controller
Parameters
\eZ\Publish\API\Repository\URLWildcardService $urlWildcardService
Definition at line 37 of file URLWildcard.php.
References eZ\Publish\Core\REST\Server\Controller\URLWildcard\__construct().
    {
        $this->urlWildcardService = $urlWildcardService;
    }
Member Function Documentation
eZ\Publish\Core\REST\Server\Controller\URLWildcard::createURLWildcard ()
Creates a new URL wildcard
Returns
Definition at line 70 of file URLWildcard.php.
References eZ\Publish\Core\REST\Server\Controller\URLWildcard\createURLWildcard().
    {
        $urlWildcardCreate = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        try
        {
            $createdURLWildcard = $this->urlWildcardService->create(
                $urlWildcardCreate['sourceUrl'],
                $urlWildcardCreate['destinationUrl'],
                $urlWildcardCreate['forward']
            );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        return new Values\CreatedURLWildcard(
            array(
                'urlWildcard' => $createdURLWildcard
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\URLWildcard::deleteURLWildcard ()
The given URL wildcard is deleted
Returns
Definition at line 104 of file URLWildcard.php.
References eZ\Publish\Core\REST\Server\Controller\URLWildcard\deleteURLWildcard().
    {
        $values = $this->urlHandler->parse( 'urlWildcard', $this->request->path );
        $this->urlWildcardService->remove(
            $this->urlWildcardService->load( $values['urlwildcard'] )
        );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\URLWildcard::listURLWildcards ()
Returns the list of URL wildcards
Returns
Definition at line 58 of file URLWildcard.php.
References eZ\Publish\Core\REST\Server\Controller\URLWildcard\listURLWildcards().
    {
        return new Values\URLWildcardList(
            $this->urlWildcardService->loadAll()
        );
    }
eZ\Publish\Core\REST\Server\Controller\URLWildcard::loadURLWildcard ()
Returns the URL wildcard with the given id
Returns
Definition at line 47 of file URLWildcard.php.
References eZ\Publish\API\Repository\URLWildcardService\load(), and eZ\Publish\Core\REST\Server\Controller\URLWildcard\loadURLWildcard().
    {
        $values = $this->urlHandler->parse( 'urlWildcard', $this->request->path );
        return $this->urlWildcardService->load( $values['urlwildcard'] );
    }
Member Data Documentation
eZ\Publish\Core\REST\Server\Controller\URLWildcard::$urlWildcardService protected
Definition at line 30 of file URLWildcard.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Controller/URLWildcard.php