ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image Class Reference
Public Member Functions
toStorageValue (FieldValue $value, StorageFieldValue $storageFieldValue)
toFieldValue (StorageFieldValue $value, FieldValue $fieldValue)
toStorageFieldDefinition (FieldDefinition $fieldDef, StorageFieldDefinition $storageDef)
toFieldDefinition (StorageFieldDefinition $storageDef, FieldDefinition $fieldDef)
getIndexColumn ()
Static Public Member Functions
static create ()
Protected Member Functions
createEmptyLegacyXml ($contentMetaData)
createLegacyXml (array $data)
fillXml ($imageData, $pathInfo, $timestamp)
parseLegacyXml ($xml)
Detailed Description
Definition at line 19 of file Image.php.
Member Function Documentation
static eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image::create () static
Factory for current class
Note
Class should instead be configured as service if it gains dependencies.
Returns
Image
Definition at line 28 of file Image.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image\create().
    {
        return new self;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image::createEmptyLegacyXml ($contentMetaData) protected
Creates an XML considered "empty" by the legacy storage
Parameters
array $contentMetaData
Returns
string
Definition at line 68 of file Image.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image\createEmptyLegacyXml(), and eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image\fillXml().
    {
        return $this->fillXml(
            array_merge(
                array(
                    'path' => '',
                    'width' => '',
                    'height' => '',
                    'mime' => '',
                    'alternativeText' => '',
                ),
                $contentMetaData
            ),
            array(
                'basename' => '',
                'extension' => '',
                'dirname' => '',
                'filename' => '',
            ),
            time()
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image::createLegacyXml (array $data) protected
Returns the XML required by the legacy database
Parameters
array $data
Returns
string
Definition at line 98 of file Image.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image\createLegacyXml(), and eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image\fillXml().
    {
        $pathInfo = pathinfo( $data['path'] );
        return $this->fillXml( $data, $pathInfo, time() );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image::fillXml ($imageData, $pathInfo, $timestamp) protected
Fill the XML template with the data provided
Parameters
array $imageData
array $pathInfo
int $timestamp
Returns
string
Definition at line 113 of file Image.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image\fillXml().
    {
        // <?xml version="1.0" encoding="utf-8"
        // <ezimage serial_number="1" is_valid="1" filename="River-Boat.jpg" suffix="jpg" basename="River-Boat" dirpath="var/ezdemo_site/storage/images/travel/peruvian-amazon/river-boat/322-1-eng-US" url="var/ezdemo_site/storage/images/travel/peruvian-amazon/river-boat/322-1-eng-US/River-Boat.jpg" original_filename="bbbbc2fe.jpg" mime_type="image/jpeg" width="770" height="512" alternative_text="Old River Boat" alias_key="1293033771" timestamp="1342530101">
        //   <original attribute_id="322" attribute_version="1" attribute_language="eng-US"/>
        //   <information Height="512" Width="770" IsColor="1"/>
        // </ezimage>
$xml = <<<EOT
<?xml version="1.0" encoding="utf-8"?>
<ezimage serial_number="1" is_valid="%s" filename="%s"
    suffix="%s" basename="%s" dirpath="%s" url="%s"
    original_filename="%s" mime_type="%s" width="%s"
    height="%s" alternative_text="%s" alias_key="%s" timestamp="%s">
  <original attribute_id="%s" attribute_version="%s" attribute_language="%s"/>
  <information Height="%s" Width="%s" IsColor="%s"/>
</ezimage>
EOT;
        return sprintf(
            $xml,
            // <ezimage>
            ( $pathInfo['basename'] !== '' ? '1' : '' ), // is_valid="%s"
            htmlspecialchars( $pathInfo['basename'] ), // filename="%s"
            htmlspecialchars( $pathInfo['extension'] ), // suffix="%s"
            htmlspecialchars( $pathInfo['filename'] ), // basename="%s"
            htmlspecialchars( $pathInfo['dirname'] ), // dirpath
            htmlspecialchars( $imageData['path'] ), // url
            htmlspecialchars( $pathInfo['basename'] ), // @todo: Needs original file name, for whatever reason?
            htmlspecialchars( $imageData['mime'] ), // mime_type
            htmlspecialchars( $imageData['width'] ), // width
            htmlspecialchars( $imageData['height'] ), // height
            htmlspecialchars( $imageData['alternativeText'] ), // alternative_text
            htmlspecialchars( 1293033771 ), // alias_key, fixed for the original image
            htmlspecialchars( $timestamp ), // timestamp
            // <original>
            $imageData['fieldId'],
            $imageData['versionNo'],
            $imageData['languageCode'],
            // <information>
            $imageData['height'], // Height
            $imageData['width'], // Width
            1 // IsColor @todo Do we need to fix that here?
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image::getIndexColumn ()
Returns the name of the index column in the attribute table
Returns the name of the index column the datatype uses, which is either "sort_key_int" or "sort_key_string". This column is then used for filtering and sorting for this type.
Returns
string
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 263 of file Image.php.
    {
        // @todo: Correct?
        return 'sort_key_string';
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image::parseLegacyXml ($xml) protected
Parses the XML from the legacy database
Returns only the data required by the FieldType, nothing more.
Parameters
string $xml
Returns
array
Definition at line 183 of file Image.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image\parseLegacyXml().
    {
        $extractedData = array();
        $dom = new \DOMDocument();
        $dom->loadXml( $xml );
        $ezimageTag = $dom->documentElement;
        if ( !$ezimageTag->hasAttribute( 'url' ) )
        {
            throw new \RuntimeException( 'Missing attribute "url" in <ezimage/> tag.' );
        }
        if ( ( $url = $ezimageTag->getAttribute( 'url' ) ) === '' )
        {
            // Detected XML considered "empty" by the legacy storage
            return null;
        }
        $extractedData['path'] = $url;
        if ( !$ezimageTag->hasAttribute( 'filename' ) )
        {
            throw new \RuntimeException( 'Missing attribute "filename" in <ezimage/> tag.' );
        }
        $extractedData['fileName'] = $ezimageTag->getAttribute( 'filename' );
        if ( !$ezimageTag->hasAttribute( 'alternative_text' ) )
        {
            throw new \RuntimeException( 'Missing attribute "alternative_text" in <ezimage/> tag.' );
        }
        $extractedData['alternativeText'] = $ezimageTag->getAttribute( 'alternative_text' );
        return $extractedData;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image::toFieldDefinition (StorageFieldDefinition $storageDef, FieldDefinition $fieldDef)
Converts field definition data in $storageDef into $fieldDef
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageDef
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDef
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 239 of file Image.php.
    {
        $fieldDef->fieldTypeConstraints = new FieldTypeConstraints(
            array(
                'validators' => array(
                    'FileSizeValidator' => array(
                        'maxFileSize' => ( $storageDef->dataInt1 != 0
                            ? (int)$storageDef->dataInt1 * 1024 * 1024
                            : false ),
                    )
                )
            )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image::toFieldValue (StorageFieldValue $value, FieldValue $fieldValue)
Converts data from $value to $fieldValue
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldValue $value
\eZ\Publish\SPI\Persistence\Content\FieldValue $fieldValue
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 164 of file Image.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image\parseLegacyXml().
    {
        if ( empty( $value->dataText ) )
        {
            // Special case for anonymous user
            return;
        }
        $fieldValue->data = $this->parseLegacyXml( $value->dataText );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image::toStorageFieldDefinition (FieldDefinition $fieldDef, StorageFieldDefinition $storageDef)
Converts field definition data in $fieldDef into $storageFieldDef
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDef
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageDef
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 226 of file Image.php.
    {
        $storageDef->dataInt1 = ( isset( $fieldDef->fieldTypeConstraints->validators['FileSizeValidator']['maxFileSize'] )
            ? round( $fieldDef->fieldTypeConstraints->validators['FileSizeValidator']['maxFileSize'] / 1024 / 1024 )
            : 0 );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image::toStorageValue (FieldValue $value, StorageFieldValue $storageFieldValue)
Converts data from $value to $storageFieldValue
Parameters
\eZ\Publish\SPI\Persistence\Content\FieldValue $value
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldValue $storageFieldValue
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 39 of file Image.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image\createEmptyLegacyXml(), and eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Image\createLegacyXml().
    {
        if ( isset( $value->data ) )
        {
            // Determine what needs to be stored
            if ( isset( $value->data['mime'] ) )
            {
                // $data['mime'] is only set for real images, which have been
                // stored
                $storageFieldValue->dataText = $this->createLegacyXml( $value->data );
            }
            else if ( isset( $value->data['fieldId'] ) )
            {
                // $fieldId is only set if data is to be stored at all
                $storageFieldValue->dataText = $this->createEmptyLegacyXml( $value->data );
            }
            // otherwise the image is unprocessed and the DB field stays empty
            // there will be a subsequent call to this method, after the image
            // has been stored
        }
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/Image.php