ezp-next: eZ\Publish\API\Repository\Values\Content\Query\Criterion\ObjectStateId Class Reference
eZ\Publish\API\Repository\Values\Content\Query\Criterion\ObjectStateId Class Reference
Public Member Functions
__construct ($value)
getSpecifications ()
Public Member Functions inherited from eZ\Publish\API\Repository\Values\Content\Query\Criterion
__construct ($target, $operator, $value)
Static Public Member Functions
static createFromQueryBuilder ($target, $operator, $value)
Additional Inherited Members
Public Attributes inherited from eZ\Publish\API\Repository\Values\Content\Query\Criterion
$operator
$value
$target
Detailed Description
A criterion that matches content based on its state
Supported operators:
IN: matches against a list of object state IDs
EQ: matches against one object state ID
Definition at line 23 of file ObjectStateId.php.
Constructor & Destructor Documentation
eZ\Publish\API\Repository\Values\Content\Query\Criterion\ObjectStateId::__construct ($value)
Creates a new ObjectStateId criterion
Parameters
int|int[] $value One or more object state IDs that must be matched
Exceptions
\InvalidArgumentException if a non numeric id is given
\InvalidArgumentException if the value type doesn't match the operator
Definition at line 33 of file ObjectStateId.php.
References eZ\Publish\API\Repository\Values\Content\Query\Criterion\$value, and eZ\Publish\API\Repository\Values\ValueObject\__construct().
    {
        parent::__construct( null, null, $value );
    }
Member Function Documentation
static eZ\Publish\API\Repository\Values\Content\Query\Criterion\ObjectStateId::createFromQueryBuilder ($target, $operator, $value) static
Reimplemented from eZ\Publish\API\Repository\Values\Content\Query\Criterion.
Definition at line 54 of file ObjectStateId.php.
References eZ\Publish\API\Repository\Values\Content\Query\Criterion\$value, and eZ\Publish\API\Repository\Values\Content\Query\Criterion\ObjectStateId\createFromQueryBuilder().
    {
        return new self( $value );
    }
eZ\Publish\API\Repository\Values\Content\Query\Criterion\ObjectStateId::getSpecifications ()
Criterion description function.
Returns the combination of the Criterion's supported operator/value, as an array of eZ objects
Operator is one supported Operator, as an Operator::* constant
ValueType is the type of input value this operator requires, either array or single
SupportedTypes is an array of types the operator will accept
ValueCountLimitation is an integer saying how many values are expected.
// IN and EQ are supported return array(// The EQ operator expects a single value, either as an integer or a string new Specifications(Operator::EQ, Specifications::INPUT_TYPE_SINGLE, array(Specifications::INPUT_VALUE_INTEGER, Specifications::INPUT_VALUE_STRING),), // The IN operator expects an array of values, of either integers or strings new Specifications(Operator::IN, Specifications::INPUT_TYPE_ARRAY, array(Specifications::INPUT_VALUE_INTEGER, Specifications::INPUT_VALUE_STRING)))*
Returns
[]
Implements eZ\Publish\API\Repository\Values\Content\Query\CriterionInterface.
Definition at line 38 of file ObjectStateId.php.
References eZ\Publish\API\Repository\Values\Content\Query\Criterion\Operator\EQ, eZ\Publish\API\Repository\Values\Content\Query\Criterion\Operator\Specifications\FORMAT_ARRAY, eZ\Publish\API\Repository\Values\Content\Query\Criterion\Operator\Specifications\FORMAT_SINGLE, eZ\Publish\API\Repository\Values\Content\Query\Criterion\ObjectStateId\getSpecifications(), eZ\Publish\API\Repository\Values\Content\Query\Criterion\Operator\IN, eZ\Publish\API\Repository\Values\Content\Query\Criterion\Operator\Specifications\TYPE_INTEGER, and eZ\Publish\API\Repository\Values\Content\Query\Criterion\Operator\Specifications\TYPE_STRING.
    {
        return array(
            new Specifications(
                Operator::IN,
                Specifications::FORMAT_ARRAY,
                Specifications::TYPE_INTEGER | Specifications::TYPE_STRING
            ),
            new Specifications(
                Operator::EQ,
                Specifications::FORMAT_SINGLE,
                Specifications::TYPE_INTEGER | Specifications::TYPE_STRING
            ),
        );
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/API/Repository/Values/Content/Query/Criterion/ObjectStateId.php