ezp-next: eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator Class Reference
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator Class Reference
Public Member Functions
generateHashValue (\XMLWriter $writer, $hashElementName, $hashValue)
Protected Member Functions
generateValue (\XmlWriter $writer, $value, $key=null, $elementName= 'value')
generateArrayValue (\XmlWriter $writer, $value, $key, $elementName= 'value')
generateHashArray (\XmlWriter $writer, $value, $key=null, $elementName= 'value')
generateListArray (\XmlWriter $writer, $value, $key=null, $elementName= 'value')
isNumericArray (array $value)
generateNullValue (\XmlWriter $writer, $key=null, $elementName= 'value')
generateBooleanValue (\XmlWriter $writer, $value, $key=null, $elementName= 'value')
generateIntegerValue (\XmlWriter $writer, $value, $key=null, $elementName= 'value')
generateFloatValue (\XmlWriter $writer, $value, $key=null, $elementName= 'value')
generateStringValue (\XmlWriter $writer, $value, $key=null, $elementName= 'value')
generateKeyAttribute (\XmlWriter $writer, $key=null)
Detailed Description
Definition at line 14 of file FieldTypeHashGenerator.php.
Member Function Documentation
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::generateArrayValue (\XmlWriter $writer, $value, $key, $elementName = 'value') protected
Generates an array value from $value
Parameters
\XmlWriter $writer
array $value
string | null $key
string $elementName
Definition at line 78 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateArrayValue(), eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateHashArray(), eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateListArray(), and eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\isNumericArray().
    {
        if ( $this->isNumericArray( $value ) )
        {
            $this->generateListArray( $writer, $value, $key, $elementName );
        }
        else
        {
            $this->generateHashArray( $writer, $value, $key, $elementName );
        }
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::generateBooleanValue (\XmlWriter $writer, $value, $key = null, $elementName = 'value') protected
Generates a boolean value
Parameters
\XmlWriter $writer
boolean $value
string | null $key
string $elementName
Definition at line 174 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateBooleanValue(), and eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateKeyAttribute().
    {
        $writer->startElement( $elementName );
        $this->generateKeyAttribute( $writer, $key );
        $writer->text( $value ? 'true' : 'false' );
        $writer->endElement();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::generateFloatValue (\XmlWriter $writer, $value, $key = null, $elementName = 'value') protected
Generates a float value
Parameters
\XmlWriter $writer
float $value
string | null $key
string $elementName
Definition at line 206 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateFloatValue(), and eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateKeyAttribute().
    {
        $writer->startElement( $elementName );
        $this->generateKeyAttribute( $writer, $key );
        $writer->text( sprintf( '%F', $value ) );
        $writer->endElement();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::generateHashArray (\XmlWriter $writer, $value, $key = null, $elementName = 'value') protected
Generates $value as a hash of value items
Parameters
\XmlWriter $writer
array $value
string | null $key
string $elementName
Definition at line 98 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateHashArray(), eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateKeyAttribute(), and eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateValue().
    {
        $writer->startElement( $elementName );
        $this->generateKeyAttribute( $writer, $key );
        foreach ( $value as $hashKey => $hashItemValue )
        {
            $this->generateValue( $writer, $hashItemValue, $hashKey );
        }
        $writer->endElement();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::generateHashValue (\XMLWriter $writer, $hashElementName, $hashValue)
Generates the field type value $hashValue into the $writer creating an element with $hashElementName as its parent
Parameters
\XmlWriter $writer
string $hashElementName
mixed $hashValue
Definition at line 24 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateHashValue(), and eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateValue().
    {
        $this->generateValue( $writer, $hashValue, null, $hashElementName );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::generateIntegerValue (\XmlWriter $writer, $value, $key = null, $elementName = 'value') protected
Generates a integer value
Parameters
\XmlWriter $writer
int $value
string | null $key
string $elementName
Definition at line 190 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateIntegerValue(), and eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateKeyAttribute().
    {
        $writer->startElement( $elementName );
        $this->generateKeyAttribute( $writer, $key );
        $writer->text( $value );
        $writer->endElement();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::generateKeyAttribute (\XmlWriter $writer, $key = null) protected
Generates a key attribute with $key as the value, if $key is not null
Parameters
\XmlWriter $writer
string | null $key
Definition at line 236 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateKeyAttribute().
    {
        if ( $key !== null )
        {
            $writer->startAttribute( 'key' );
            $writer->text( $key );
            $writer->endAttribute();
        }
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::generateListArray (\XmlWriter $writer, $value, $key = null, $elementName = 'value') protected
Generates $value as a list of value items
Parameters
\XmlWriter $writer
array $value
string | null $key
string $elementName
Definition at line 119 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateKeyAttribute(), eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateListArray(), and eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateValue().
    {
        $writer->startElement( $elementName );
        $this->generateKeyAttribute( $writer, $key );
        foreach ( $value as $listItemValue )
        {
            $this->generateValue( $writer, $listItemValue );
        }
        $writer->endElement();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::generateNullValue (\XmlWriter $writer, $key = null, $elementName = 'value') protected
Generates a null value
Parameters
\XmlWriter $writer
string | null $key
string $elementName
Definition at line 158 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateKeyAttribute(), and eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateNullValue().
    {
        $writer->startElement( $elementName );
        $this->generateKeyAttribute( $writer, $key );
        // @todo: xsi:type?
        $writer->endElement();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::generateStringValue (\XmlWriter $writer, $value, $key = null, $elementName = 'value') protected
Generates a string value
Parameters
\XmlWriter $writer
string $value
string | null $key
string $elementName
Definition at line 222 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateKeyAttribute(), and eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateStringValue().
    {
        $writer->startElement( $elementName );
        $this->generateKeyAttribute( $writer, $key );
        $writer->text( $value );
        $writer->endElement();
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::generateValue (\XmlWriter $writer, $value, $key = null, $elementName = 'value') protected
Generates $value into a serialized representation
Parameters
\XmlWriter $writer
mixed $value
string | null $key
string $elementName
Definition at line 37 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateArrayValue(), eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateBooleanValue(), eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateFloatValue(), eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateIntegerValue(), eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateNullValue(), eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateStringValue(), and eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\generateValue().
    {
        switch ( ( $hashValueType = gettype( $value ) ) )
        {
            case 'NULL':
                $this->generateNullValue( $writer, $key, $elementName );
                break;
            case 'boolean':
                $this->generateBooleanValue( $writer, $value, $key, $elementName );
                break;
            case 'integer':
                $this->generateIntegerValue( $writer, $value, $key, $elementName );
                break;
            case 'double':
                $this->generateFloatValue( $writer, $value, $key, $elementName );
                break;
            case 'string':
                $this->generateStringValue( $writer, $value, $key, $elementName );
                break;
            case 'array':
                $this->generateArrayValue( $writer, $value, $key, $elementName );
                break;
            default:
                throw new \Exception( 'Invalid type in field value hash: ' . $hashValueType );
        }
    }
eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator::isNumericArray (array $value) protected
Checks if the given $value is a purely numeric array
Parameters
array $value
Returns
boolean
Definition at line 139 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Xml\FieldTypeHashGenerator\isNumericArray().
    {
        foreach ( array_keys( $value ) as $key )
        {
            if ( is_string( $key ) )
            {
                return false;
            }
        }
        return true;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/Output/Generator/Xml/FieldTypeHashGenerator.php