ezp-next: eZ\Publish\Core\Persistence\Cache\Handler Class Reference
eZ\Publish\Core\Persistence\Cache\Handler Class Reference
Public Member Functions
__construct (PersistenceFactory $persistenceFactory, CacheSectionHandler $sectionHandler, CacheLocationHandler $locationHandler, CacheContentHandler $contentHandler, CacheContentLanguageHandler $contentLanguageHandler, CacheContentTypeHandler $contentTypeHandler, CacheUserHandler $userHandler, CacheSearchHandler $searchHandler, CacheUrlAliasHandler $urlAliasHandler, PersistenceLogger $logger)
contentHandler ()
searchHandler ()
contentTypeHandler ()
contentLanguageHandler ()
locationHandler ()
objectStateHandler ()
userHandler ()
sectionHandler ()
trashHandler ()
urlAliasHandler ()
urlWildcardHandler ()
beginTransaction ()
commit ()
rollback ()
Protected Attributes
$persistenceFactory
$sectionHandler
$contentHandler
$contentLanguageHandler
$contentTypeHandler
$locationHandler
$userHandler
$searchHandler
$urlAliasHandler
$logger
Detailed Description
Persistence Cache Handler class
Definition at line 27 of file Handler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Cache\Handler::__construct (PersistenceFactory $persistenceFactory, CacheSectionHandler $sectionHandler, CacheLocationHandler $locationHandler, CacheContentHandler $contentHandler, CacheContentLanguageHandler $contentLanguageHandler, CacheContentTypeHandler $contentTypeHandler, CacheUserHandler $userHandler, CacheSearchHandler $searchHandler, CacheUrlAliasHandler $urlAliasHandler, PersistenceLogger $logger)
Construct the class
Parameters
\eZ\Publish\Core\Persistence\Factory $persistenceFactory Must be factory for inner persistence, ie: legacy
SectionHandler $sectionHandler
LocationHandler $locationHandler
ContentHandler $contentHandler
ContentLanguageHandler $contentLanguageHandler
ContentTypeHandler $contentTypeHandler
UserHandler $userHandler
SearchHandler $searchHandler
UrlAliasHandler $urlAliasHandler
PersistenceLogger $logger
Definition at line 93 of file Handler.php.
References eZ\Publish\Core\Persistence\Cache\Handler\$contentHandler, eZ\Publish\Core\Persistence\Cache\Handler\$contentLanguageHandler, eZ\Publish\Core\Persistence\Cache\Handler\$contentTypeHandler, eZ\Publish\Core\Persistence\Cache\Handler\$locationHandler, eZ\Publish\Core\Persistence\Cache\Handler\$logger, eZ\Publish\Core\Persistence\Cache\Handler\$persistenceFactory, eZ\Publish\Core\Persistence\Cache\Handler\$searchHandler, eZ\Publish\Core\Persistence\Cache\Handler\$sectionHandler, eZ\Publish\Core\Persistence\Cache\Handler\$urlAliasHandler, eZ\Publish\Core\Persistence\Cache\Handler\$userHandler, eZ\Publish\Core\Persistence\Cache\Handler\contentHandler(), eZ\Publish\Core\Persistence\Cache\Handler\contentLanguageHandler(), eZ\Publish\Core\Persistence\Cache\Handler\contentTypeHandler(), eZ\Publish\Core\Persistence\Cache\Handler\locationHandler(), eZ\Publish\Core\Persistence\Cache\Handler\searchHandler(), eZ\Publish\Core\Persistence\Cache\Handler\sectionHandler(), eZ\Publish\Core\Persistence\Cache\Handler\urlAliasHandler(), and eZ\Publish\Core\Persistence\Cache\Handler\userHandler().
    {
        $this->persistenceFactory = $persistenceFactory;
        $this->sectionHandler = $sectionHandler;
        $this->locationHandler = $locationHandler;
        $this->contentHandler = $contentHandler;
        $this->contentLanguageHandler = $contentLanguageHandler;
        $this->contentTypeHandler = $contentTypeHandler;
        $this->userHandler = $userHandler;
        $this->searchHandler = $searchHandler;
        $this->urlAliasHandler = $urlAliasHandler;
        $this->logger = $logger;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Cache\Handler::beginTransaction ()
Begin transaction
Begins an transaction, make sure you'll call commit or rollback when done, otherwise work will be lost.
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 215 of file Handler.php.
    {
        $this->logger->logCall( __METHOD__ );
        $this->persistenceFactory->getPersistenceHandler()->beginTransaction();
    }
eZ\Publish\Core\Persistence\Cache\Handler::commit ()
Commit transaction
Commit transaction, or throw exceptions if no transactions has been started.
Exceptions
\RuntimeException If no transaction has been started
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 228 of file Handler.php.
    {
        $this->logger->logCall( __METHOD__ );
        $this->persistenceFactory->getPersistenceHandler()->commit();
    }
eZ\Publish\Core\Persistence\Cache\Handler::contentHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 121 of file Handler.php.
References eZ\Publish\Core\Persistence\Cache\Handler\$contentHandler.
    {
        return $this->contentHandler;
    }
eZ\Publish\Core\Persistence\Cache\Handler::contentLanguageHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 145 of file Handler.php.
References eZ\Publish\Core\Persistence\Cache\Handler\$contentLanguageHandler.
    {
        return $this->contentLanguageHandler;
    }
eZ\Publish\Core\Persistence\Cache\Handler::contentTypeHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 137 of file Handler.php.
References eZ\Publish\Core\Persistence\Cache\Handler\$contentTypeHandler.
    {
        return $this->contentTypeHandler;
    }
eZ\Publish\Core\Persistence\Cache\Handler::locationHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 153 of file Handler.php.
References eZ\Publish\Core\Persistence\Cache\Handler\$locationHandler.
    {
        return $this->locationHandler;
    }
eZ\Publish\Core\Persistence\Cache\Handler::objectStateHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 161 of file Handler.php.
    {
        $this->logger->logUnCachedHandler( __METHOD__ );
        return $this->persistenceFactory->getObjectStateHandler();
    }
eZ\Publish\Core\Persistence\Cache\Handler::rollback ()
Rollback transaction
Rollback transaction, or throw exceptions if no transactions has been started.
Exceptions
\RuntimeException If no transaction has been started
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 241 of file Handler.php.
    {
        $this->logger->logCall( __METHOD__ );
        $this->persistenceFactory->getPersistenceHandler()->rollback();
    }
eZ\Publish\Core\Persistence\Cache\Handler::searchHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 129 of file Handler.php.
References eZ\Publish\Core\Persistence\Cache\Handler\$searchHandler.
    {
        return $this->searchHandler;
    }
eZ\Publish\Core\Persistence\Cache\Handler::sectionHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 178 of file Handler.php.
References eZ\Publish\Core\Persistence\Cache\Handler\$sectionHandler.
    {
        return $this->sectionHandler;
    }
eZ\Publish\Core\Persistence\Cache\Handler::trashHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 186 of file Handler.php.
    {
        $this->logger->logUnCachedHandler( __METHOD__ );
        return $this->persistenceFactory->getTrashHandler();
    }
eZ\Publish\Core\Persistence\Cache\Handler::urlAliasHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 195 of file Handler.php.
References eZ\Publish\Core\Persistence\Cache\Handler\$urlAliasHandler.
    {
        return $this->urlAliasHandler;
    }
eZ\Publish\Core\Persistence\Cache\Handler::urlWildcardHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 203 of file Handler.php.
    {
        $this->logger->logUnCachedHandler( __METHOD__ );
        return $this->persistenceFactory->getUrlWildcardHandler();
    }
eZ\Publish\Core\Persistence\Cache\Handler::userHandler ()
Returns
Implements eZ\Publish\SPI\Persistence\Handler.
Definition at line 170 of file Handler.php.
References eZ\Publish\Core\Persistence\Cache\Handler\$userHandler.
    {
        return $this->userHandler;
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Cache\Handler::$contentHandler protected
Definition at line 42 of file Handler.php.
eZ\Publish\Core\Persistence\Cache\Handler::$contentLanguageHandler protected
Definition at line 47 of file Handler.php.
eZ\Publish\Core\Persistence\Cache\Handler::$contentTypeHandler protected
Definition at line 52 of file Handler.php.
eZ\Publish\Core\Persistence\Cache\Handler::$locationHandler protected
Definition at line 57 of file Handler.php.
eZ\Publish\Core\Persistence\Cache\Handler::$logger protected
Definition at line 77 of file Handler.php.
eZ\Publish\Core\Persistence\Cache\Handler::$persistenceFactory protected
Definition at line 32 of file Handler.php.
eZ\Publish\Core\Persistence\Cache\Handler::$searchHandler protected
Definition at line 67 of file Handler.php.
eZ\Publish\Core\Persistence\Cache\Handler::$sectionHandler protected
Definition at line 37 of file Handler.php.
eZ\Publish\Core\Persistence\Cache\Handler::$urlAliasHandler protected
Definition at line 72 of file Handler.php.
eZ\Publish\Core\Persistence\Cache\Handler::$userHandler protected
Definition at line 62 of file Handler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Cache/Handler.php