ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase Class Reference
Public Member Functions
__construct (EzcDbHandler $handler)
getBasicNodeData ($nodeId)
getBasicNodeDataByRemoteId ($remoteId)
loadLocationDataByContent ($contentId, $rootLocationId=null)
getSubtreeContent ($sourceId)
getChildren ($locationId)
updateSubtreeModificationTime ($pathString, $timestamp=null)
hideSubtree ($pathString)
unHideSubtree ($pathString)
swap ($locationId1, $locationId2)
createNodeAssignment (CreateStruct $createStruct, $parentNodeId, $type=self::NODE_ASSIGNMENT_OP_CODE_CREATE_NOP)
deleteNodeAssignment ($contentId, $versionNo=null)
updateNodeAssignment ($contentObjectId, $oldParent, $newParent, $opcode)
createLocationsFromNodeAssignments ($contentId, $versionNo)
updateLocationsContentVersionNo ($contentId, $versionNo)
update (UpdateStruct $location, $locationId)
removeLocation ($locationId)
getFallbackMainNodeData ($contentId, $locationId)
untrashLocation ($locationId, $newParentId=null)
loadTrashByLocation ($locationId)
listTrashed ($offset, $limit, array $sort=null)
cleanupTrash ()
removeElementFromTrash ($id)
setSectionForSubtree ($pathString, $sectionId)
countLocationsByContentId ($contentId)
changeMainLocation ($contentId, $locationId, $versionNo, $parentLocationId)
Public Member Functions inherited from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway
moveSubtreeNodes ($fromPathString, $toPathString)
create (CreateStruct $createStruct, array $parentNode)
updatePathIdentificationString ($locationId, $parentLocationId, $text)
trashLocation ($locationId)
Protected Member Functions
applySubtreeLimitation (\ezcQuery $query, $rootLocationId)
Protected Attributes
$handler
Additional Inherited Members
Public Attributes inherited from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway
const NODE_ASSIGNMENT_OP_CODE_NOP = 0
const NODE_ASSIGNMENT_OP_CODE_EXECUTE = 1
const NODE_ASSIGNMENT_OP_CODE_CREATE_NOP = 2
const NODE_ASSIGNMENT_OP_CODE_CREATE = 3
const NODE_ASSIGNMENT_OP_CODE_MOVE_NOP = 4
const NODE_ASSIGNMENT_OP_CODE_MOVE = 5
const NODE_ASSIGNMENT_OP_CODE_REMOVE_NOP = 6
const NODE_ASSIGNMENT_OP_CODE_REMOVE = 7
const NODE_ASSIGNMENT_OP_CODE_SET_NOP = 8
const NODE_ASSIGNMENT_OP_CODE_SET = 9
Detailed Description
Location gateway implementation using the zeta database component.
Definition at line 26 of file EzcDatabase.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::__construct (EzcDbHandler $handler)
Construct from database handler
Parameters
\eZ\Publish\Core\Persistence\Legacy\EzcDbHandler $handler
Returns
void
Definition at line 42 of file EzcDatabase.php.
    {
        $this->handler = $handler;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::applySubtreeLimitation (\ezcQuery $query, $rootLocationId) protected
Limits the given $query to the subtree starting at $rootLocationId
Parameters
\ezcQuery $query
string $rootLocationId
Returns
void
Definition at line 178 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase\applySubtreeLimitation().
    {
        $query->where(
            $query->expr->like(
                $this->handler->quoteColumn( 'path_string', 'ezcontentobject_tree' ),
                $query->bindValue( '%/' . $rootLocationId . '/%' )
            )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::changeMainLocation ($contentId, $locationId, $versionNo, $parentLocationId)
Changes main location of content identified by given $contentId to location identified by given $locationId
Updates ezcontentobject_tree table for the given $contentId and eznode_assignment table for the given $contentId, $parentLocationId and $versionNo
Parameters
mixed $contentId
mixed $locationId
mixed $versionNo version number, needed to update eznode_assignment table
mixed $parentLocationId parent location of location identified by $locationId, needed to update eznode_assignment table
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 1335 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$contentId.
    {
        // Update ezcontentobject_tree table
        $q = $this->handler->createUpdateQuery();
        $q->update(
            $this->handler->quoteTable( "ezcontentobject_tree" )
        )->set(
            $this->handler->quoteColumn( "main_node_id" ),
            $q->bindValue( $locationId, null, \PDO::PARAM_INT )
        )->where(
            $q->expr->eq(
                $this->handler->quoteColumn( "contentobject_id" ),
                $q->bindValue( $contentId, null, \PDO::PARAM_INT )
            )
        );
        $q->prepare()->execute();
        // Erase is_main in eznode_assignment table
        $q = $this->handler->createUpdateQuery();
        $q->update(
            $this->handler->quoteTable( "eznode_assignment" )
        )->set(
            $this->handler->quoteColumn( "is_main" ),
            $q->bindValue( 0, null, \PDO::PARAM_INT )
        )->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->handler->quoteColumn( "contentobject_id" ),
                    $q->bindValue( $contentId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->handler->quoteColumn( "contentobject_version" ),
                    $q->bindValue( $versionNo, null, \PDO::PARAM_INT )
                ),
                $q->expr->neq(
                    $this->handler->quoteColumn( "parent_node" ),
                    $q->bindValue( $parentLocationId, null, \PDO::PARAM_INT )
                )
            )
        );
        $q->prepare()->execute();
        // Set new is_main in eznode_assignment table
        $q = $this->handler->createUpdateQuery();
        $q->update(
            $this->handler->quoteTable( "eznode_assignment" )
        )->set(
            $this->handler->quoteColumn( "is_main" ),
            $q->bindValue( 1, null, \PDO::PARAM_INT )
        )->where(
            $q->expr->lAnd(
                $q->expr->eq(
                    $this->handler->quoteColumn( "contentobject_id" ),
                    $q->bindValue( $contentId, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->handler->quoteColumn( "contentobject_version" ),
                    $q->bindValue( $versionNo, null, \PDO::PARAM_INT )
                ),
                $q->expr->eq(
                    $this->handler->quoteColumn( "parent_node" ),
                    $q->bindValue( $parentLocationId, null, \PDO::PARAM_INT )
                )
            )
        );
        $q->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::cleanupTrash ()
Removes every entries in the trash. Will NOT remove associated content objects nor attributes.
Basically truncates ezcontentobject_trash table.
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 1227 of file EzcDatabase.php.
    {
        $query = $this->handler->createDeleteQuery();
        $query->deleteFrom( 'ezcontentobject_trash' );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::countLocationsByContentId ($contentId)
Returns how many locations given content object identified by $contentId has
Parameters
int $contentId
Returns
int
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 1301 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$contentId.
    {
        $q = $this->handler->createSelectQuery();
        $q
            ->select(
                $q->alias( $q->expr->count( '*' ), 'count' )
            )
            ->from( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->where(
                $q->expr->eq(
                    $this->handler->quoteColumn( 'contentobject_id' ),
                    $q->bindValue( $contentId, null, \PDO::PARAM_INT )
                )
            );
        $stmt = $q->prepare();
        $stmt->execute();
        $res = $stmt->fetchAll( \PDO::FETCH_ASSOC );
        return (int)$res[0]['count'];
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::createLocationsFromNodeAssignments ($contentId, $versionNo)
Create locations from node assignments
Convert existing node assignments into real locations.
Parameters
mixed $contentId
mixed $versionNo
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 785 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$contentId, eZ\Publish\SPI\Persistence\Content\Location\$mainLocationId, eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\create(), eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\getBasicNodeData(), and eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\updateNodeAssignment().
    {
        // select all node assignments with OP_CODE_CREATE (3) for this content
        $query = $this->handler->createSelectQuery();
        $query
            ->select( '*' )
            ->from( $this->handler->quoteTable( 'eznode_assignment' ) )
            ->where(
                $query->expr->lAnd(
                    $query->expr->like(
                        $this->handler->quoteColumn( 'contentobject_id' ),
                        $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                    ),
                    $query->expr->like(
                        $this->handler->quoteColumn( 'contentobject_version' ),
                        $query->bindValue( $versionNo, null, \PDO::PARAM_INT )
                    ),
                    $query->expr->like(
                        $this->handler->quoteColumn( 'op_code' ),
                        $query->bindValue( self::NODE_ASSIGNMENT_OP_CODE_CREATE, null, \PDO::PARAM_INT )
                    )
                )
            )->orderBy( 'id' );
        $statement = $query->prepare();
        $statement->execute();
        // convert all these assignments to nodes
        while ( $row = $statement->fetch( \PDO::FETCH_ASSOC ) )
        {
            if ( (bool)$row['is_main'] === true )
            {
                $mainLocationId = true;
            }
            else
            {
                $mainLocationId = $this->getMainNodeId( $contentId );
            }
            $this->create(
                new CreateStruct(
                    array(
                        'contentId' => $row['contentobject_id'],
                        'contentVersion' => $row['contentobject_version'],
                        'mainLocationId' => $mainLocationId,
                        'remoteId' => $row['remote_id'],
                        'sortField' => $row['sort_field'],
                        'sortOrder' => $row['sort_order'],
                    )
                ),
                $this->getBasicNodeData( $row['parent_node'] )
            );
            $this->updateNodeAssignment(
                $row['contentobject_id'],
                $row['parent_node'],
                $row['parent_node'],
                self::NODE_ASSIGNMENT_OP_CODE_CREATE_NOP
            );
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::createNodeAssignment (CreateStruct $createStruct, $parentNodeId, $type = self::NODE_ASSIGNMENT_OP_CODE_CREATE_NOP)
Create an entry in the node assignment table
Parameters
\eZ\Publish\SPI\Persistence\Content\Location\CreateStruct $createStruct
mixed $parentNodeId
int $type
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 660 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\SORT_FIELD_PUBLISHED, and eZ\Publish\SPI\Persistence\Content\Location\SORT_ORDER_DESC.
    {
        $isMain = ( $createStruct->mainLocationId === true ? 1 : 0 );
        $query = $this->handler->createInsertQuery();
        $query
            ->insertInto( $this->handler->quoteTable( 'eznode_assignment' ) )
            ->set(
                $this->handler->quoteColumn( 'contentobject_id' ),
                $query->bindValue( $createStruct->contentId, null, \PDO::PARAM_INT )
            )->set(
                $this->handler->quoteColumn( 'contentobject_version' ),
                $query->bindValue( $createStruct->contentVersion, null, \PDO::PARAM_INT )
            )->set(
                $this->handler->quoteColumn( 'from_node_id' ),
                $query->bindValue( 0, null, \PDO::PARAM_INT ) // unused field
            )->set(
                $this->handler->quoteColumn( 'id' ),
                $this->handler->getAutoIncrementValue( 'eznode_assignment', 'id' )
            )->set(
                $this->handler->quoteColumn( 'is_main' ),
                $query->bindValue( $isMain, null, \PDO::PARAM_INT ) // Changed by the business layer, later
            )->set(
                $this->handler->quoteColumn( 'op_code' ),
                $query->bindValue( $type, null, \PDO::PARAM_INT )
            )->set(
                $this->handler->quoteColumn( 'parent_node' ),
                $query->bindValue( $parentNodeId, null, \PDO::PARAM_INT )
            )->set(
                $this->handler->quoteColumn( 'parent_remote_id' ),
                $query->bindValue( '' )
            )->set(
                $this->handler->quoteColumn( 'remote_id' ),
                $query->bindValue( $createStruct->remoteId, null, \PDO::PARAM_STR )
            )->set(
                $this->handler->quoteColumn( 'sort_field' ),
                $query->bindValue( Location::SORT_FIELD_PUBLISHED, null, \PDO::PARAM_INT )
            )->set(
                $this->handler->quoteColumn( 'sort_order' ),
                $query->bindValue( Location::SORT_ORDER_DESC, null, \PDO::PARAM_INT )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::deleteNodeAssignment ($contentId, $versionNo = null)
Deletes node assignment for given $contentId and $versionNo
If $versionNo is not passed all node assignments for given $contentId are deleted
Parameters
int $contentId
int | null $versionNo
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 714 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$contentId.
    {
        $query = $this->handler->createDeleteQuery();
        $query->deleteFrom(
            'eznode_assignment'
        )->where(
            $query->expr->eq(
                $this->handler->quoteColumn( 'contentobject_id' ),
                $query->bindValue( $contentId, null, \PDO::PARAM_INT )
            )
        );
        if ( isset( $versionNo ) )
        {
            $query->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'contentobject_version' ),
                    $query->bindValue( $versionNo, null, \PDO::PARAM_INT )
                )
            );
        }
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::getBasicNodeData ($nodeId)
Returns an array with basic node data
We might want to cache this, since this method is used by about every method in the location handler.
Todo:
optimize
Parameters
mixed $nodeId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 58 of file EzcDatabase.php.
    {
        $query = $this->handler->createSelectQuery();
        $query
            ->select( '*' )
            ->from( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'node_id' ),
                    $query->bindValue( $nodeId )
                )
            );
        $statement = $query->prepare();
        $statement->execute();
        if ( $row = $statement->fetch( \PDO::FETCH_ASSOC ) )
        {
            return $row;
        }
        throw new NotFound( 'location', $nodeId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::getBasicNodeDataByRemoteId ($remoteId)
Returns an array with basic node data
Todo:
optimize
Parameters
mixed $remoteId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 89 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$remoteId.
    {
        $query = $this->handler->createSelectQuery();
        $query
            ->select( '*' )
            ->from( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'remote_id' ),
                    $query->bindValue( $remoteId )
                )
            );
        $statement = $query->prepare();
        $statement->execute();
        if ( $row = $statement->fetch( \PDO::FETCH_ASSOC ) )
        {
            return $row;
        }
        throw new NotFound( 'location', $remoteId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::getChildren ($locationId)
Returns data for the first level children of the location identified by given $locationId
Parameters
mixed $locationId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 195 of file EzcDatabase.php.
    {
        $query = $this->handler->createSelectQuery();
        $query->select( "*" )->from(
            $this->handler->quoteTable( "ezcontentobject_tree" )
        )->where(
            $query->expr->eq(
                $this->handler->quoteColumn( "parent_node_id", "ezcontentobject_tree" ),
                $query->bindValue( $locationId, null, \PDO::PARAM_INT )
            )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::getFallbackMainNodeData ($contentId, $locationId)
Returns id of the next in line node to be set as a new main node
This returns lowest node id for content identified by $contentId, and not of the node identified by given $locationId (current main node). Assumes that content has more than one location.
Parameters
mixed $contentId
mixed $locationId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 1011 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$contentId, and eZ\Publish\API\Repository\Values\Content\Query\SORT_ASC.
    {
        $query = $this->handler->createSelectQuery();
        $query->select(
            $this->handler->quoteColumn( "node_id" ),
            $this->handler->quoteColumn( "contentobject_version" ),
            $this->handler->quoteColumn( "parent_node_id" )
        )->from(
            $this->handler->quoteTable( "ezcontentobject_tree" )
        )->where(
            $query->expr->lAnd(
                $query->expr->eq(
                    $this->handler->quoteColumn( "contentobject_id" ),
                    $query->bindValue( $contentId, null, \PDO::PARAM_INT )
                ),
                $query->expr->neq(
                    $this->handler->quoteColumn( "node_id" ),
                    $query->bindValue( $locationId, null, \PDO::PARAM_INT )
                )
            )
        )->orderBy( "node_id", Query::SORT_ASC )->limit( 1 );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetch( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::getSubtreeContent ($sourceId)
Find all content in the given subtree
Parameters
mixed $sourceId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 152 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase\applySubtreeLimitation().
    {
        $query = $this->handler->createSelectQuery();
        $query->select( '*' )->from(
            $this->handler->quoteTable( 'ezcontentobject_tree' )
        );
        $this->applySubtreeLimitation( $query, $sourceId );
        $query->orderBy(
            $this->handler->quoteColumn( 'depth', 'ezcontentobject_tree' )
        )->orderBy(
            $this->handler->quoteColumn( 'node_id', 'ezcontentobject_tree' )
        );
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::hideSubtree ($pathString)
Sets a location to be hidden, and it self + all children to invisible.
Parameters
string $pathString
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 336 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$pathString.
    {
        $query = $this->handler->createUpdateQuery();
        $query
            ->update( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->set(
                $this->handler->quoteColumn( 'is_invisible' ),
                $query->bindValue( 1 )
            )
            ->set(
                $this->handler->quoteColumn( 'modified_subnode' ),
                $query->bindValue( time() )
            )
            ->where(
                $query->expr->like(
                    $this->handler->quoteColumn( 'path_string' ),
                    $query->bindValue( $pathString . '%' )
                )
            );
        $query->prepare()->execute();
        $query = $this->handler->createUpdateQuery();
        $query
            ->update( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->set(
                $this->handler->quoteColumn( 'is_hidden' ),
                $query->bindValue( 1 )
            )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'path_string' ),
                    $query->bindValue( $pathString )
                )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::listTrashed ($offset, $limit, array $sort = null)
List trashed items
Parameters
int $offset
int $limit
array $sort
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 1168 of file EzcDatabase.php.
References eZ\Publish\API\Repository\Values\Content\Query\SORT_ASC.
    {
        $query = $this->handler->createSelectQuery();
        $query
            ->select( '*' )
            ->from( $this->handler->quoteTable( 'ezcontentobject_trash' ) );
        $sort = $sort ?: array();
        foreach ( $sort as $condition )
        {
            $sortDirection = $condition->direction === Query::SORT_ASC ? \ezcQuerySelect::ASC : \ezcQuerySelect::DESC;
            switch ( true )
            {
                case $condition instanceof SortClause\LocationDepth:
                    $query->orderBy( 'depth', $sortDirection );
                    break;
                case $condition instanceof SortClause\LocationPathString:
                    $query->orderBy( 'path_string', $sortDirection );
                    break;
                case $condition instanceof SortClause\LocationPriority:
                    $query->orderBy( 'priority', $sortDirection );
                    break;
                default:
                    // Only handle location related sort clauses. The others
                    // require data aggregation which is not sensible here.
                    // Since also criteria are yet ignored, because they are
                    // simply not used yet in eZ Publish, we skip that for now.
                    throw new RuntimeException( 'Unhandled sort clause: ' . get_class( $condition ) );
            }
        }
        if ( $limit !== null )
        {
            $query->limit( $limit, $offset );
        }
        $statement = $query->prepare();
        $statement->execute();
        $rows = array();
        while ( $row = $statement->fetch( \PDO::FETCH_ASSOC ) )
        {
            $rows[] = $row;
        }
        return $rows;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::loadLocationDataByContent ($contentId, $rootLocationId = null)
Loads data for all Locations for $contentId, optionally only in the subtree starting at $rootLocationId
Parameters
int $contentId
int $rootLocationId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 121 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$contentId, and eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase\applySubtreeLimitation().
    {
        $query = $this->handler->createSelectQuery();
        $query
            ->select( '*' )
            ->from( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'contentobject_id' ),
                    $query->bindValue( $contentId )
                )
            );
        if ( $rootLocationId !== null )
        {
            $this->applySubtreeLimitation( $query, $rootLocationId );
        }
        $statement = $query->prepare();
        $statement->execute();
        return $statement->fetchAll( \PDO::FETCH_ASSOC );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::loadTrashByLocation ($locationId)
Loads trash data specified by location ID
Parameters
mixed $locationId
Returns
array
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 1136 of file EzcDatabase.php.
    {
        $query = $this->handler->createSelectQuery();
        $query
            ->select( '*' )
            ->from( $this->handler->quoteTable( 'ezcontentobject_trash' ) )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'node_id' ),
                    $query->bindValue( $locationId )
                )
            );
        $statement = $query->prepare();
        $statement->execute();
        if ( $row = $statement->fetch( \PDO::FETCH_ASSOC ) )
        {
            return $row;
        }
        throw new NotFound( 'trash', $locationId );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::removeElementFromTrash ($id)
Removes trashed element identified by $id from trash. Will NOT remove associated content object nor attributes.
Parameters
int $id The trashed location Id
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 1242 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$id.
    {
        $query = $this->handler->createDeleteQuery();
        $query
            ->deleteFrom( 'ezcontentobject_trash' )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'node_id' ),
                    $query->bindValue( $id, null, \PDO::PARAM_INT )
                )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::removeLocation ($locationId)
Deletes ezcontentobject_tree row for given $locationId (node_id)
Parameters
mixed $locationId
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 985 of file EzcDatabase.php.
    {
        $query = $this->handler->createDeleteQuery();
        $query->deleteFrom(
            "ezcontentobject_tree"
        )->where(
            $query->expr->eq(
                $this->handler->quoteColumn( "node_id" ),
                $query->bindValue( $locationId, null, \PDO::PARAM_INT )
            )
        );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::setSectionForSubtree ($pathString, $sectionId)
Set section on all content objects in the subtree
Parameters
mixed $pathString
mixed $sectionId
Returns
boolean
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 1264 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$pathString.
    {
        $query = $this->handler->createUpdateQuery();
        $subSelect = $query->subSelect();
        $subSelect
            ->select( $this->handler->quoteColumn( 'contentobject_id' ) )
            ->from( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->where(
                $subSelect->expr->like(
                    $this->handler->quoteColumn( 'path_string' ),
                    $subSelect->bindValue( $pathString . '%' )
                )
            );
        $query
            ->update( $this->handler->quoteTable( 'ezcontentobject' ) )
            ->set(
                $this->handler->quoteColumn( 'section_id' ),
                $query->bindValue( $sectionId )
            )
            ->where(
                $query->expr->in(
                    $this->handler->quoteColumn( 'id' ),
                    $subSelect
                )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::swap ($locationId1, $locationId2)
Swaps the content object being pointed to by a location object.
Make the location identified by $locationId1 refer to the Content referred to by $locationId2 and vice versa.
Parameters
mixed $locationId1
mixed $locationId2
Returns
boolean
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 499 of file EzcDatabase.php.
    {
        $query = $this->handler->createSelectQuery();
        $query
            ->select(
                $this->handler->quoteColumn( 'node_id' ),
                $this->handler->quoteColumn( 'contentobject_id' ),
                $this->handler->quoteColumn( 'contentobject_version' )
            )
            ->from( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->where(
                $query->expr->in(
                    $this->handler->quoteColumn( 'node_id' ),
                    array( $locationId1, $locationId2 )
                )
            );
        $statement = $query->prepare();
        $statement->execute();
        foreach ( $statement->fetchAll() as $row )
        {
            $contentObjects[$row['node_id']] = $row;
        }
        $query = $this->handler->createUpdateQuery();
        $query
            ->update( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->set(
                $this->handler->quoteColumn( 'contentobject_id' ),
                $query->bindValue( $contentObjects[$locationId2]['contentobject_id'] )
            )
            ->set(
                $this->handler->quoteColumn( 'contentobject_version' ),
                $query->bindValue( $contentObjects[$locationId2]['contentobject_version'] )
            )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'node_id' ),
                    $query->bindValue( $locationId1 )
                )
            );
        $query->prepare()->execute();
        $query = $this->handler->createUpdateQuery();
        $query
            ->update( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->set(
                $this->handler->quoteColumn( 'contentobject_id' ),
                $query->bindValue( $contentObjects[$locationId1]['contentobject_id'] )
            )
            ->set(
                $this->handler->quoteColumn( 'contentobject_version' ),
                $query->bindValue( $contentObjects[$locationId1]['contentobject_version'] )
            )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'node_id' ),
                    $query->bindValue( $locationId2 )
                )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::unHideSubtree ($pathString)
Sets a location to be unhidden, and self + children to visible unless a parent is hidding the tree. If not make sure only children down to first hidden node is marked visible.
Parameters
string $pathString
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 379 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase\$handler, and eZ\Publish\SPI\Persistence\Content\Location\$pathString.
    {
        // Unhide the requested node
        $query = $this->handler->createUpdateQuery();
        $query
            ->update( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->set(
                $this->handler->quoteColumn( 'is_hidden' ),
                $query->bindValue( 0 )
            )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'path_string' ),
                    $query->bindValue( $pathString )
                )
            );
        $query->prepare()->execute();
        // Check if any parent nodes are explicitely hidden
        $query = $this->handler->createSelectQuery();
        $query
            ->select( $this->handler->quoteColumn( 'path_string' ) )
            ->from( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->where(
                $query->expr->lAnd(
                    $query->expr->eq(
                        $this->handler->quoteColumn( 'is_hidden' ),
                        $query->bindValue( 1 )
                    ),
                    $query->expr->in(
                        $this->handler->quoteColumn( 'node_id' ),
                        array_filter( explode( '/', $pathString ) )
                    )
                )
            );
        $statement = $query->prepare();
        $statement->execute();
        if ( count( $statement->fetchAll( \PDO::FETCH_COLUMN ) ) )
        {
            // There are parent nodes set hidden, so that we can skip marking
            // something visible again.
            return;
        }
        // Find nodes of explicitly hidden subtrees in the subtree which
        // should be unhidden
        $query = $this->handler->createSelectQuery();
        $query
            ->select( $this->handler->quoteColumn( 'path_string' ) )
            ->from( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->where(
                $query->expr->lAnd(
                    $query->expr->eq(
                        $this->handler->quoteColumn( 'is_hidden' ),
                        $query->bindValue( 1 )
                    ),
                    $query->expr->like(
                        $this->handler->quoteColumn( 'path_string' ),
                        $query->bindValue( $pathString . '%' )
                    )
                )
            );
        $statement = $query->prepare();
        $statement->execute();
        $hiddenSubtrees = $statement->fetchAll( \PDO::FETCH_COLUMN );
        $query = $this->handler->createUpdateQuery();
        $query
            ->update( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->set(
                $this->handler->quoteColumn( 'is_invisible' ),
                $query->bindValue( 0 )
            )
            ->set(
                $this->handler->quoteColumn( 'modified_subnode' ),
                $query->bindValue( time() )
            );
        // Build where expression selecting the nodes, which should be made
        // visible again
        $where = $query->expr->like(
            $this->handler->quoteColumn( 'path_string' ),
            $query->bindValue( $pathString . '%' )
        );
        if ( count( $hiddenSubtrees ) )
        {
            $handler = $this->handler;
            $where = $query->expr->lAnd(
                $where,
                $query->expr->lAnd(
                    array_map(
                        function ( $pathString ) use ( $query, $handler )
{
                            return $query->expr->not(
                                $query->expr->like(
                                    $handler->quoteColumn( 'path_string' ),
                                    $query->bindValue( $pathString . '%' )
                                )
                            );
                        },
                        $hiddenSubtrees
                    )
                )
            );
        }
        $query->where( $where );
        $statement = $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::untrashLocation ($locationId, $newParentId = null)
Returns a trashed location to normal state.
Recreates the originally trashed location in the new position. If no new position has been specified, it will be tried to re-create the location at the old position. If this is not possible (because the old location does not exist any more) and exception is thrown.
Parameters
mixed $locationId
mixed | null $newParentId
Returns
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 1080 of file EzcDatabase.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\create(), eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\getBasicNodeData(), eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\loadTrashByLocation(), eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\removeElementFromTrash(), and eZ\Publish\SPI\Persistence\Content\ContentInfo\STATUS_PUBLISHED.
    {
        $row = $this->loadTrashByLocation( $locationId );
        $newLocation = $this->create(
            new CreateStruct(
                array(
                    'priority' => $row['priority'],
                    'hidden' => $row['is_hidden'],
                    'invisible' => $row['is_invisible'],
                    'remoteId' => $row['remote_id'],
                    'contentId' => $row['contentobject_id'],
                    'contentVersion' => $row['contentobject_version'],
                    'mainLocationId' => true,// Restored location is always main location
                    'sortField' => $row['sort_field'],
                    'sortOrder' => $row['sort_order'],
                )
            ),
            $this->getBasicNodeData( $newParentId ?: $row['parent_node_id'] )
        );
        $this->removeElementFromTrash( $locationId );
        $this->setContentStatus( $row['contentobject_id'], ContentInfo::STATUS_PUBLISHED );
        return $newLocation;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::update (UpdateStruct $location, $locationId)
Updates an existing location.
Parameters
\eZ\Publish\SPI\Persistence\Content\Location\UpdateStruct $location
int $locationId
Returns
boolean
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 918 of file EzcDatabase.php.
    {
        $query = $this->handler->createUpdateQuery();
        $query
            ->update( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->set(
                $this->handler->quoteColumn( 'priority' ),
                $query->bindValue( $location->priority )
            )
            ->set(
                $this->handler->quoteColumn( 'remote_id' ),
                $query->bindValue( $location->remoteId )
            )
            ->set(
                $this->handler->quoteColumn( 'sort_order' ),
                $query->bindValue( $location->sortOrder )
            )
            ->set(
                $this->handler->quoteColumn( 'sort_field' ),
                $query->bindValue( $location->sortField )
            )
            ->where(
                $query->expr->eq(
                    $this->handler->quoteColumn( 'node_id' ),
                    $locationId
                )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::updateLocationsContentVersionNo ($contentId, $versionNo)
Updates all Locations of content identified with $contentId with $versionNo
Parameters
mixed $contentId
mixed $versionNo
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 854 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$contentId.
    {
        $query = $this->handler->createUpdateQuery();
        $query->update(
            $this->handler->quoteTable( "ezcontentobject_tree" )
        )->set(
            $this->handler->quoteColumn( "contentobject_version" ),
            $query->bindValue( $versionNo, null, \PDO::PARAM_INT )
        )->where(
            $query->expr->eq(
                $this->handler->quoteColumn( "contentobject_id" ),
                $contentId
            )
        );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::updateNodeAssignment ($contentObjectId, $oldParent, $newParent, $opcode)
Update node assignment table
Parameters
int $contentObjectId
int $oldParent
int $newParent
int $opcode
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 747 of file EzcDatabase.php.
    {
        $query = $this->handler->createUpdateQuery();
        $query
            ->update( $this->handler->quoteTable( 'eznode_assignment' ) )
            ->set(
                $this->handler->quoteColumn( 'parent_node' ),
                $query->bindValue( $newParent, null, \PDO::PARAM_INT )
            )
            ->set(
                $this->handler->quoteColumn( 'op_code' ),
                $query->bindValue( $opcode, null, \PDO::PARAM_INT )
            )
            ->where(
                $query->expr->lAnd(
                    $query->expr->eq(
                        $this->handler->quoteColumn( 'contentobject_id' ),
                        $query->bindValue( $contentObjectId, null, \PDO::PARAM_INT )
                    ),
                    $query->expr->eq(
                        $this->handler->quoteColumn( 'parent_node' ),
                        $query->bindValue( $oldParent, null, \PDO::PARAM_INT )
                    )
                )
            );
        $query->prepare()->execute();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::updateSubtreeModificationTime ($pathString, $timestamp = null)
Updated subtree modification time for all nodes on path
Parameters
string $pathString
int | null $timestamp
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway.
Definition at line 310 of file EzcDatabase.php.
References eZ\Publish\SPI\Persistence\Content\Location\$pathString.
    {
        $nodes = array_filter( explode( '/', $pathString ) );
        $query = $this->handler->createUpdateQuery();
        $query
            ->update( $this->handler->quoteTable( 'ezcontentobject_tree' ) )
            ->set(
                $this->handler->quoteColumn( 'modified_subnode' ),
                $query->bindValue(
                    $timestamp ?: time()
                )
            )
            ->where(
                $query->expr->in(
                    $this->handler->quoteColumn( 'node_id' ),
                    $nodes
                )
            );
        $query->prepare()->execute();
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\EzcDatabase::$handler protected
Definition at line 33 of file EzcDatabase.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/EzcDatabase.php