ezp-next: eZ\Publish\Core\REST\Server\Controller\Location Class Reference
eZ\Publish\Core\REST\Server\Controller\Location Class Reference
Public Member Functions
__construct (LocationService $locationService, ContentService $contentService, TrashService $trashService)
redirectLocation ()
createLocation ()
loadLocation ()
deleteSubtree ()
copySubtree ()
moveSubtree ()
swapLocation ()
loadLocationByRemoteId ()
loadLocationsForContent ()
loadLocationChildren ()
updateLocation ()
Public Member Functions inherited from eZ\Publish\Core\REST\Server\Controller
setInputDispatcher (InputDispatcher $inputDispatcher)
setUrlHandler (UrlHandler $urlHandler)
setRequest (HttpRequest $request)
setContainer (Container $container)
Protected Attributes
$locationService
$contentService
$trashService
Protected Attributes inherited from eZ\Publish\Core\REST\Server\Controller
$request
$inputDispatcher
$urlHandler
$container
Detailed Description
Location controller
Definition at line 28 of file Location.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Server\Controller\Location::__construct (LocationService $locationService, ContentService $contentService, TrashService $trashService)
Construct controller
Parameters
\eZ\Publish\API\Repository\LocationService $locationService
\eZ\Publish\API\Repository\ContentService $contentService
\eZ\Publish\API\Repository\TrashService $trashService
Definition at line 58 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\__construct().
    {
        $this->locationService = $locationService;
        $this->contentService  = $contentService;
        $this->trashService    = $trashService;
    }
Member Function Documentation
eZ\Publish\Core\REST\Server\Controller\Location::copySubtree ()
Copies a subtree to a new destination
Returns
Definition at line 161 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\copySubtree().
    {
        $values = $this->urlHandler->parse( 'location', $this->request->path );
        $location = $this->locationService->loadLocation( $this->extractLocationIdFromPath( $values['location'] ) );
        $destinationValues = $this->urlHandler->parse( 'location', $this->request->destination );
        $destinationLocation = $this->locationService->loadLocation( $this->extractLocationIdFromPath( $destinationValues['location'] ) );
        $newLocation = $this->locationService->copySubtree( $location, $destinationLocation );
        return new Values\ResourceCreated(
            $this->urlHandler->generate(
                'location',
                array(
                    'location' => rtrim( $newLocation->pathString, '/' ),
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Location::createLocation ()
Creates a new location for the given content object
Returns
Definition at line 101 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\createLocation().
    {
        $values = $this->urlHandler->parse( 'objectLocations', $this->request->path );
        $locationCreateStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $contentInfo = $this->contentService->loadContentInfo( $values['object'] );
        try
        {
            $createdLocation = $this->locationService->createLocation( $contentInfo, $locationCreateStruct );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        return new Values\CreatedLocation( array( "restLocation" => new Values\RestLocation( $createdLocation, 0 ) ) );
    }
eZ\Publish\Core\REST\Server\Controller\Location::deleteSubtree ()
Deletes a location
Returns
Definition at line 147 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\deleteSubtree().
    {
        $values = $this->urlHandler->parse( 'location', $this->request->path );
        $location = $this->locationService->loadLocation( $this->extractLocationIdFromPath( $values['location'] ) );
        $this->locationService->deleteLocation( $location );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\Location::loadLocation ()
Loads a location
Returns
Definition at line 131 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\loadLocation().
    {
        $values = $this->urlHandler->parse( 'location', $this->request->path );
        return new Values\RestLocation(
            $location = $this->locationService->loadLocation(
                $this->extractLocationIdFromPath( $values['location'] )
            ),
            $this->locationService->getLocationChildCount( $location )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Location::loadLocationByRemoteId ()
Loads a location by remote ID
Returns
Definition at line 268 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\loadLocationByRemoteId().
    {
        return new Values\LocationList(
            array(
                new Values\RestLocation(
                    $location = $this->locationService->loadLocationByRemoteId(
                        $this->request->variables['remoteId']
                    ),
                    $this->locationService->getLocationChildCount( $location )
                )
            ),
            $this->request->path
        );
    }
eZ\Publish\Core\REST\Server\Controller\Location::loadLocationChildren ()
Loads child locations of a location
Returns
Definition at line 312 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\loadLocationChildren().
    {
        $questionMark = strpos( $this->request->path, '?' );
        $requestPath = $questionMark !== false ? substr( $this->request->path, 0, $questionMark ) : $this->request->path;
        $values = $this->urlHandler->parse( 'locationChildren', $requestPath );
        $offset = isset( $this->request->variables['offset'] ) ? (int)$this->request->variables['offset'] : 0;
        $limit = isset( $this->request->variables['limit'] ) ? (int)$this->request->variables['limit'] : -1;
        $restLocations = array();
        foreach (
            $this->locationService->loadLocationChildren(
                $this->locationService->loadLocation(
                    $this->extractLocationIdFromPath( $values['location'] )
                ),
                $offset >= 0 ? $offset : 0,
                $limit >= 0 ? $limit : -1
            )->locations as $location
        )
        {
            $restLocations[] = new Values\RestLocation(
                $location,
                $this->locationService->getLocationChildCount( $location )
            );
        }
        return new Values\LocationList( $restLocations, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\Location::loadLocationsForContent ()
Loads all locations for content object
Returns
Definition at line 288 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\loadLocationsForContent().
    {
        $values = $this->urlHandler->parse( 'objectLocations', $this->request->path );
        $restLocations = array();
        foreach (
            $this->locationService->loadLocations(
                $this->contentService->loadContentInfo( $values['object'] )
            ) as $location
        )
        {
            $restLocations[] = new Values\RestLocation(
                $location,
                $this->locationService->getLocationChildCount( $location )
            );
        }
        return new Values\LocationList( $restLocations, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\Location::moveSubtree ()
Moves a subtree to a new location
Exceptions
\eZ\Publish\Core\REST\Server\Exceptions\BadRequestException if the Destination header cannot be parsed as location or trash
Returns
Definition at line 188 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\moveSubtree().
    {
        $values = $this->urlHandler->parse( 'location', $this->request->path );
        $locationToMove = $this->locationService->loadLocation(
            $this->extractLocationIdFromPath( $values['location'] )
        );
        $destinationLocationId = null;
        try
        {
            // First check to see if the destination is for moving within another subtree
            $destinationValues = $this->urlHandler->parse( 'location', $this->request->destination );
            $destinationLocationId = $this->extractLocationIdFromPath( $destinationValues['location'] );
        }
        catch ( Exceptions\InvalidArgumentException $e )
        {
            try
            {
                // If parsing of destination fails, let's try to see if destination is trash
                $this->urlHandler->parse( 'trashItems', $this->request->destination );
            }
            catch ( Exceptions\InvalidArgumentException $e )
            {
                // If that fails, the Destination header is not formatted right
                // so just throw the BadRequestException
                throw new BadRequestException( "{$this->request->destination} is not formatted correctly" );
            }
        }
        if ( $destinationLocationId !== null )
        {
            // We're moving the subtree
            $destinationLocation = $this->locationService->loadLocation( $destinationLocationId );
            $this->locationService->moveSubtree( $locationToMove, $destinationLocation );
            // Reload the location to get the new position is subtree
            $locationToMove = $this->locationService->loadLocation( $locationToMove->id );
            return new Values\ResourceCreated(
                $this->urlHandler->generate(
                    'location',
                    array(
                        'location' => rtrim( $locationToMove->pathString, '/' ),
                    )
                )
            );
        }
        // We're trashing the subtree
        $trashItem = $this->trashService->trash( $locationToMove );
        return new Values\ResourceCreated(
            $this->urlHandler->generate( 'trash', array( 'trash' => $trashItem->id ) )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Location::redirectLocation ()
Loads the location for a given ID (x)or remote ID
Returns
Definition at line 70 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\redirectLocation().
    {
        if ( !isset( $this->request->variables['id'] ) && !isset( $this->request->variables['remoteId'] ) )
        {
            throw new BadRequestException( "At least one of 'id' or 'remoteId' parameters is required." );
        }
        if ( isset( $this->request->variables['id'] ) )
        {
            $location = $this->locationService->loadLocation( $this->request->variables['id'] );
        }
        else
        {
            $location = $this->locationService->loadLocationByRemoteId( $this->request->variables['remoteId'] );
        }
        return new Values\TemporaryRedirect(
            $this->urlHandler->generate(
                'location',
                array(
                    'location' => rtrim( $location->pathString, '/' )
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Location::swapLocation ()
Swaps a location with another one
Returns
Definition at line 248 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\swapLocation().
    {
        $values = $this->urlHandler->parse( 'location', $this->request->path );
        $locationId = $this->extractLocationIdFromPath( $values['location'] );
        $location = $this->locationService->loadLocation( $locationId );
        $destinationValues = $this->urlHandler->parse( 'location', $this->request->destination );
        $destinationLocation = $this->locationService->loadLocation( $this->extractLocationIdFromPath( $destinationValues['location'] ) );
        $this->locationService->swapLocation( $location, $destinationLocation );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\Location::updateLocation ()
Updates a location
Returns
Definition at line 347 of file Location.php.
References eZ\Publish\Core\REST\Server\Controller\Location\updateLocation().
    {
        $values = $this->urlHandler->parse( 'location', $this->request->path );
        $locationUpdate = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $location = $this->locationService->loadLocation( $this->extractLocationIdFromPath( $values['location'] ) );
        // First handle hiding/unhiding so that updating location afterwards
        // will return updated location with hidden/visible status correctly updated
        // Exact check for true/false is needed as null signals that no hiding/unhiding
        // is to be performed
        if ( $locationUpdate->hidden === true )
        {
            $this->locationService->hideLocation( $location );
        }
        else if ( $locationUpdate->hidden === false )
        {
            $this->locationService->unhideLocation( $location );
        }
        return new Values\RestLocation(
            $location = $this->locationService->updateLocation( $location, $locationUpdate->locationUpdateStruct ),
            $this->locationService->getLocationChildCount( $location )
        );
    }
Member Data Documentation
eZ\Publish\Core\REST\Server\Controller\Location::$contentService protected
Definition at line 42 of file Location.php.
eZ\Publish\Core\REST\Server\Controller\Location::$locationService protected
Definition at line 35 of file Location.php.
eZ\Publish\Core\REST\Server\Controller\Location::$trashService protected
Definition at line 49 of file Location.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Controller/Location.php