ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page Class Reference
Public Member Functions
__construct (Service $pageService)
toStorageValue (FieldValue $value, StorageFieldValue $storageFieldValue)
toFieldValue (StorageFieldValue $value, FieldValue $fieldValue)
toStorageFieldDefinition (FieldDefinition $fieldDef, StorageFieldDefinition $storageDef)
toFieldDefinition (StorageFieldDefinition $storageDef, FieldDefinition $fieldDef)
getIndexColumn ()
generateXmlString ($page)
restoreValueFromXmlString ($xmlString)
Protected Member Functions
generateZoneXmlString ($zone, DOMDocument $dom)
generateBlockXmlString ($block, DOMDocument $dom)
generateItemXmlString ($item, DOMDocument $dom)
restoreZoneFromXml (DOMElement $node)
restoreBlockFromXml (DOMElement $node)
restoreItemFromXml (DOMElement $node)
Protected Attributes
$pageService
Detailed Description
Definition at line 22 of file Page.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::__construct (Service $pageService)
Constructor
Parameters
\eZ\Publish\Core\FieldType\Page\Service $pageService
Definition at line 36 of file Page.php.
    {
        $this->pageService = $pageService;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::generateBlockXmlString ($block, DOMDocument $dom) protected
Generates XML string for a given $block object
Parameters
\eZ\Publish\Core\FieldType\Page\Parts\Block $block
\DOMDocument $dom
Returns
Definition at line 196 of file Page.php.
    {
        $blockNode = $dom->createElement( 'block' );
        foreach ( $block->getProperties() as $attrName => $attrValue )
        {
            switch ( $attrName )
            {
                case 'id':
                    $blockNode->setAttribute( 'id', 'id_' . $attrValue );
                    break;
                case 'action':
                    $blockNode->setAttribute( 'action', $attrValue );
                    break;
                case 'items':
                    foreach ( $block->{$attrName} as $item )
                    {
                        $itemNode = $this->generateItemXmlString( $item, $dom );
                        if ( $itemNode )
{
                            $blockNode->appendChild( $itemNode );
                        }
                    }
                    break;
                case 'rotation':
                case 'custom_attributes':
                    $node = $dom->createElement( $attrName );
                    $blockNode->appendChild( $node );
                    foreach ( $attrValue as $arrayItemKey => $arrayItemValue )
                    {
                        $tmp = $dom->createElement( $arrayItemKey );
                        $tmpValue = $dom->createTextNode( $arrayItemValue );
                        $tmp->appendChild( $tmpValue );
                        $node->appendChild( $tmp );
                    }
                    break;
                default:
                    $node = $dom->createElement( $attrName );
                    $nodeValue = $dom->createTextNode( $attrValue );
                    $node->appendChild( $nodeValue );
                    $blockNode->appendChild( $node );
                    break;
            }
        }
        return $blockNode;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::generateItemXmlString ($item, DOMDocument $dom) protected
Generates XML string for a given $item object
Parameters
\eZ\Publish\Core\FieldType\Page\Parts\Item $item
\DOMDocument $dom
Returns
boolean|
Definition at line 253 of file Page.php.
    {
        if ( !$item->XMLStorable )
        {
            return false;
        }
        $itemNode = $dom->createElement( 'item' );
        foreach ( $item->getProperties() as $attrName => $attrValue )
        {
            switch ( $attrName )
            {
                case 'id':
                    $itemNode->setAttribute( 'id', $attrValue );
                    break;
                case 'action':
                    $itemNode->setAttribute( 'action', $attrValue );
                    break;
                default:
                    $node = $dom->createElement( $attrName );
                    $nodeValue = $dom->createTextNode( $attrValue );
                    $node->appendChild( $nodeValue );
                    $itemNode->appendChild( $node );
                    break;
            }
        }
        return $itemNode;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::generateXmlString ($page)
Generates XML string from $page object to be stored in storage engine
Parameters
\eZ\Publish\Core\FieldType\Page\Parts\Page $page
Returns
string
Definition at line 116 of file Page.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page\generateXmlString(), and eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page\generateZoneXmlString().
    {
        $dom = new DOMDocument( '1.0', 'utf-8' );
        $dom->formatOutput = true;
        $success = $dom->loadXML( '<page />' );
        $pageNode = $dom->documentElement;
        foreach ( $page->getProperties() as $attrName => $attrValue )
        {
            switch ( $attrName )
            {
                case 'id':
                    $pageNode->setAttribute( 'id', $attrValue );
                    break;
                case 'zones':
                    foreach ( $page->{$attrName} as $zone )
                    {
                        $pageNode->appendChild( $this->generateZoneXmlString( $zone, $dom ) );
                    }
                    break;
                default:
                    $node = $dom->createElement( $attrName );
                    $nodeValue = $dom->createTextNode( $attrValue );
                    $node->appendChild( $nodeValue );
                    $pageNode->appendChild( $node );
                    break;
            }
        }
        return $dom->saveXML();
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::generateZoneXmlString ($zone, DOMDocument $dom) protected
Generates XML string for a given $zone object
Parameters
\eZ\Publish\Core\FieldType\Page\Parts\Zone $zone
\DOMDocument $dom
Returns
Definition at line 157 of file Page.php.
    {
        $zoneNode = $dom->createElement( 'zone' );
        foreach ( $zone->getProperties() as $attrName => $attrValue )
        {
            switch ( $attrName )
            {
                case 'id':
                    $zoneNode->setAttribute( 'id', 'id_' . $attrValue );
                    break;
                case 'action':
                    $zoneNode->setAttribute( 'action', $attrValue );
                    break;
                case 'blocks':
                    foreach ( $zone->{$attrName} as $block )
                    {
                        $zoneNode->appendChild( $this->generateBlockXmlString( $block, $dom ) );
                    }
                    break;
                default:
                    $node = $dom->createElement( $attrName );
                    $nodeValue = $dom->createTextNode( $attrValue );
                    $node->appendChild( $nodeValue );
                    $zoneNode->appendChild( $node );
                    break;
            }
        }
        return $zoneNode;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::getIndexColumn ()
Returns the name of the index column in the attribute table
Returns the name of the index column the datatype uses, which is either "sort_key_int" or "sort_key_string". This column is then used for filtering and sorting for this type.
Returns
string
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 104 of file Page.php.
    {
        return false;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::restoreBlockFromXml (DOMElement $node) protected
Restores value for a given Block $node
Parameters
\DOMElement $node
Returns
Definition at line 374 of file Page.php.
    {
        $block = new Parts\Block( $this->pageService );
        if ( $node->hasAttributes() )
        {
            foreach ( $node->attributes as $attr )
            {
                if ( $attr->name == 'id' )
                {
                    $value = explode( '_', $attr->value );
                    $block->{$attr->name} = $value[1];
                }
                else
                {
                    $block->{$attr->name} = $attr->value;
                }
            }
        }
        foreach ( $node->childNodes as $node )
        {
            if ( $node->nodeType == XML_ELEMENT_NODE && $node->nodeName == 'item' )
            {
                $block->addItem( $this->restoreItemFromXml( $node ) );
            }
            else if ( $node->nodeType == XML_ELEMENT_NODE && $node->nodeName == 'rotation' )
            {
                $attrValue = array();
                foreach ( $node->childNodes as $subNode )
                {
                    if ( $subNode->nodeType == XML_ELEMENT_NODE )
                    {
                        $attrValue[$subNode->nodeName] = $subNode->nodeValue;
                    }
                }
                $block->{$node->nodeName} = $attrValue;
            }
            else if ( $node->nodeType == XML_ELEMENT_NODE && $node->nodeName == 'custom_attributes' )
            {
                $attrValue = array();
                foreach ( $node->childNodes as $subNode )
                {
                    if ( $subNode->nodeType == XML_ELEMENT_NODE )
                    {
                        $attrValue[$subNode->nodeName] = $subNode->nodeValue;
                    }
                }
                $block->{$node->nodeName} = $attrValue;
            }
            else
            {
                if ( $node->nodeType == XML_ELEMENT_NODE )
                {
                    $block->{$node->nodeName} = $node->nodeValue;
                }
            }
        }
        return $block;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::restoreItemFromXml (DOMElement $node) protected
Restores value for a given Item $node
Parameters
\DOMElement $node
Returns
Definition at line 447 of file Page.php.
    {
        $item = new Parts\Item( $this->pageService );
        if ( $node->hasAttributes() )
        {
            foreach ( $node->attributes as $attr )
            {
                $item->{$attr->name} = $attr->value;
            }
        }
        foreach ( $node->childNodes as $node )
        {
            if ( $node->nodeType == XML_ELEMENT_NODE )
            {
                $item->{$node->nodeName} = $node->nodeValue;
            }
        }
        return $item;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::restoreValueFromXmlString ($xmlString)
Restores value from XML string
Parameters
string $xmlString
Returns
Definition at line 291 of file Page.php.
    {
        $page = new Parts\Page( $this->pageService );
        if ( $xmlString )
        {
            $dom = new DOMDocument( '1.0', 'utf-8' );
            $success = $dom->loadXML( $xmlString );
            $root = $dom->documentElement;
            foreach ( $root->childNodes as $node )
            {
                if ( $node->nodeType == XML_ELEMENT_NODE && $node->nodeName == 'zone' )
                {
                   $page->addZone( $this->restoreZoneFromXml( $node ) );
                }
                else if ( $node->nodeType == XML_ELEMENT_NODE )
                {
                    $page->{$node->nodeName} = $node->nodeValue;
                }
            }
            if ( $root->hasAttributes() )
            {
                foreach ( $root->attributes as $attr )
                {
                    $page->{$attr->name} = $attr->value;
                }
            }
        }
        return $page;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::restoreZoneFromXml (DOMElement $node) protected
Restores value for a given Zone $node
Parameters
\DOMElement $node
Returns
Definition at line 332 of file Page.php.
    {
        $zone = new Parts\Zone( $this->pageService );
        if ( $node->hasAttributes() )
        {
            foreach ( $node->attributes as $attr )
            {
                if ( $attr->name == 'id' )
                {
                    $value = explode( '_', $attr->value );
                    $zone->{$attr->name} = $value[1];
                }
                else
                {
                    $zone->{$attr->name} = $attr->value;
                }
            }
        }
        foreach ( $node->childNodes as $node )
        {
            if ( $node->nodeType == XML_ELEMENT_NODE && $node->nodeName == 'block' )
            {
                $zone->addBlock( $this->restoreBlockFromXml( $node ) );
            }
            else if ( $node->nodeType == XML_ELEMENT_NODE )
            {
                $zone->{$node->nodeName} = $node->nodeValue;
            }
        }
        return $zone;
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::toFieldDefinition (StorageFieldDefinition $storageDef, FieldDefinition $fieldDef)
Converts field definition data in $storageDef into $fieldDef
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageDef
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDef
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 86 of file Page.php.
    {
        $fieldDef->fieldTypeConstraints->fieldSettings = new FieldSettings(
            array(
                'defaultLayout' => $storageDef->dataText1,
            )
        );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::toFieldValue (StorageFieldValue $value, FieldValue $fieldValue)
Converts data from $value to $fieldValue
Parameters
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldValue $value
\eZ\Publish\SPI\Persistence\Content\FieldValue $fieldValue
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 60 of file Page.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page\restoreValueFromXmlString().
    {
        $fieldValue->data = $value->dataText === null
            ? null
            : $this->restoreValueFromXmlString( $value->dataText );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::toStorageFieldDefinition (FieldDefinition $fieldDef, StorageFieldDefinition $storageDef)
Converts field definition data in $fieldDef into $storageFieldDef
Parameters
\eZ\Publish\SPI\Persistence\Content\Type\FieldDefinition $fieldDef
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldDefinition $storageDef
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 73 of file Page.php.
    {
        $storageDef->dataText1 = ( isset( $fieldDef->fieldTypeConstraints->fieldSettings['defaultLayout'] )
            ? $fieldDef->fieldTypeConstraints->fieldSettings['defaultLayout']
            : '' );
    }
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::toStorageValue (FieldValue $value, StorageFieldValue $storageFieldValue)
Converts data from $value to $storageFieldValue
Parameters
\eZ\Publish\SPI\Persistence\Content\FieldValue $value
\eZ\Publish\Core\Persistence\Legacy\Content\StorageFieldValue $storageFieldValue
Implements eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter.
Definition at line 47 of file Page.php.
References eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page\generateXmlString().
    {
        $storageFieldValue->dataText = $value->data === null
            ? null
            : $this->generateXmlString( $value->data );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page::$pageService protected
Definition at line 29 of file Page.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/Page.php