ezp-next: eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler Class Reference
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler Class Reference
Public Member Functions
__construct (BaseLanguageHandler $innerHandler, Cache $languageCache)
create (CreateStruct $struct)
update (Language $language)
load ($id)
loadByLanguageCode ($languageCode)
loadAll ()
delete ($id)
clearCache ()
Protected Member Functions
initializeCache ()
Protected Attributes
$innerHandler
$languageCache
$isCacheInitialized = false
Detailed Description
Language Handler
Definition at line 19 of file CachingHandler.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::__construct (BaseLanguageHandler $innerHandler, Cache $languageCache)
Creates a caching handler around $innerHandler
Parameters
\eZ\Publish\SPI\Persistence\Content\Language\Handler $innerHandler
Definition at line 47 of file CachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler\$innerHandler, and eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler\$languageCache.
    {
        $this->innerHandler = $innerHandler;
        $this->languageCache = $languageCache;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::clearCache ()
Clear internal cache
Returns
void
Definition at line 156 of file CachingHandler.php.
    {
        $this->isCacheInitialized = false;
        $this->languageCache->clearCache();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::create (CreateStruct $struct)
Create a new language
Parameters
\eZ\Publish\SPI\Persistence\Content\Language\CreateStruct $struct
Returns
Implements eZ\Publish\SPI\Persistence\Content\Language\Handler.
Definition at line 78 of file CachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler\initializeCache().
    {
        $this->initializeCache();
        $language = $this->innerHandler->create( $struct );
        $this->languageCache->store( $language );
        return $language;
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::delete ($id)
Delete a language
Parameters
mixed $id
Implements eZ\Publish\SPI\Persistence\Content\Language\Handler.
Definition at line 144 of file CachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler\initializeCache().
    {
        $this->initializeCache();
        $this->innerHandler->delete( $id );
        $this->languageCache->remove( $id );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::initializeCache () protected
Initializes the cache if necessary
Returns
void
Definition at line 58 of file CachingHandler.php.
    {
        if ( false === $this->isCacheInitialized )
        {
            $languages = $this->innerHandler->loadAll();
            foreach ( $languages as $language )
            {
                $this->languageCache->store( $language );
            }
            $this->isCacheInitialized = true;
        }
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::load ($id)
Get language by id
Parameters
mixed $id
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If language could not be found by $id
Returns
Implements eZ\Publish\SPI\Persistence\Content\Language\Handler.
Definition at line 107 of file CachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler\initializeCache().
    {
        $this->initializeCache();
        return $this->languageCache->getById( $id );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::loadAll ()
Get all languages
Returns
[]
Implements eZ\Publish\SPI\Persistence\Content\Language\Handler.
Definition at line 133 of file CachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler\initializeCache().
    {
        $this->initializeCache();
        return $this->languageCache->getAll();
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::loadByLanguageCode ($languageCode)
Get language by Language Code (eg: eng-GB)
Parameters
string $languageCode
Exceptions
\eZ\Publish\API\Repository\Exceptions\NotFoundException If language could not be found by $languageCode
Returns
Implements eZ\Publish\SPI\Persistence\Content\Language\Handler.
Definition at line 122 of file CachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler\initializeCache().
    {
        $this->initializeCache();
        return $this->languageCache->getByLocale( $languageCode );
    }
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::update (Language $language)
Update language
Parameters
\eZ\Publish\SPI\Persistence\Content\Language $language
Implements eZ\Publish\SPI\Persistence\Content\Language\Handler.
Definition at line 91 of file CachingHandler.php.
References eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler\initializeCache().
    {
        $this->initializeCache();
        $this->innerHandler->update( $language );
        $this->languageCache->store( $language );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::$innerHandler protected
Definition at line 26 of file CachingHandler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::$isCacheInitialized = false protected
Definition at line 40 of file CachingHandler.php.
eZ\Publish\Core\Persistence\Legacy\Content\Language\CachingHandler::$languageCache protected
Definition at line 33 of file CachingHandler.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Legacy/Content/Language/CachingHandler.php