ezp-next: eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator Class Reference
eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator Class Reference
Public Member Functions
generateHashValue ($parent, $hashElementName, $hashValue)
Protected Member Functions
generateValue ($parent, $value)
generateArrayValue ($parent, array $value)
generateListArray ($parent, array $listArray)
generateHashArray ($parent, array $hashArray)
isNumericArray (array $value)
Detailed Description
Definition at line 12 of file FieldTypeHashGenerator.php.
Member Function Documentation
eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator::generateArrayValue ($parent, array $value) protected
Generates and returns a JSON structure (array or object) depending on $value type with $parent
If $type only contains numeric keys, the resulting structure will be an JSON array, otherwise a JSON object
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator\Json\ArrayObject | \eZ\Publish\Core\REST\Common\Output\Generator\Json\Object $parent
array $value
Returns
|
Definition at line 71 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\generateArrayValue(), eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\generateHashArray(), eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\generateListArray(), and eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\isNumericArray().
    {
        if ( $this->isNumericArray( $value ) )
        {
            return $this->generateListArray( $parent, $value );
        }
        else
        {
            return $this->generateHashArray( $parent, $value );
        }
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator::generateHashArray ($parent, array $hashArray) protected
Generates a JSON object from the given $hashArray with $parent
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator\Json\ArrayObject | \eZ\Publish\Core\REST\Common\Output\Generator\Json\Object $parent
array $hashArray
Returns
Definition at line 109 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\generateHashArray(), and eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\generateValue().
    {
        $object = new Object( $parent );
        foreach ( $hashArray as $hashKey => $hashItem )
        {
            $object->$hashKey = $this->generateValue( $object, $hashItem );
        }
        return $object;
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator::generateHashValue ($parent, $hashElementName, $hashValue)
Generates the field type value $hashValue as a child of the given Object using $hashElementName as the property name
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator\Json\ArrayObject | \eZ\Publish\Core\REST\Common\Output\Generator\Json\Object $parent
string $hashElementName
mixed $hashValue
Definition at line 22 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\generateHashValue(), and eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\generateValue().
    {
        $parent->$hashElementName = $this->generateValue( $parent, $hashValue );
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator::generateListArray ($parent, array $listArray) protected
Generates a JSON array from the given $hashArray with $parent
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator\Json\ArrayObject | \eZ\Publish\Core\REST\Common\Output\Generator\Json\Object $parent
array $listArray
Returns
Definition at line 91 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\generateListArray(), and eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\generateValue().
    {
        $arrayObject = new ArrayObject( $parent );
        foreach ( $listArray as $listItem )
        {
            $arrayObject[] = $this->generateValue( $arrayObject, $listItem );
        }
        return $arrayObject;
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator::generateValue ($parent, $value) protected
Generates and returns a value based on $hashValue type, with $parent (if the type of $hashValue supports it)
Parameters
\eZ\Publish\Core\REST\Common\Output\Generator\Json\ArrayObject | \eZ\Publish\Core\REST\Common\Output\Generator\Json\Object $parent
mixed $value
Returns
mixed
Definition at line 36 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\generateArrayValue(), and eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\generateValue().
    {
        switch( ( $hashValueType = gettype( $value ) ) )
        {
            case 'NULL':
            case 'boolean':
            case 'integer':
            case 'double':
            case 'string':
                // Will be handled accordingly on serialization
                return $value;
                break;
            case 'array':
                return $this->generateArrayValue( $parent, $value );
                break;
            default:
                throw new \Exception( 'Invalid type in field value hash: ' . $hashValueType );
        }
    }
eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator::isNumericArray (array $value) protected
Checks if the given $value is a purely numeric array
Parameters
array $value
Returns
boolean
Definition at line 126 of file FieldTypeHashGenerator.php.
References eZ\Publish\Core\REST\Common\Output\Generator\Json\FieldTypeHashGenerator\isNumericArray().
    {
        foreach ( array_keys( $value ) as $key )
        {
            if ( is_string( $key ) )
            {
                return false;
            }
        }
        return true;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Common/Output/Generator/Json/FieldTypeHashGenerator.php