ezp-next: eZ\Bundle\EzPublishLegacyBundle\Controller\LegacyTreeMenuController Class Reference
eZ\Bundle\EzPublishLegacyBundle\Controller\LegacyTreeMenuController Class Reference
Public Member Functions
__construct (\Closure $treeMenuKernelHandler, Loader $legacyKernelFactory, array $options=array())
viewMenu ($nodeId, $modified, $expiry, $perm)
Public Member Functions inherited from eZ\Publish\Core\MVC\Symfony\Controller\Controller
getParameter ($parameterName, $defaultValue=null)
hasParameter ($parameterName)
getConfigResolver ()
render ($view, array $parameters=array(), Response $response=null)
getTemplateEngine ()
getLogger ()
getRepository ()
getRequest ()
getEventDispatcher ()
isGranted (AuthorizationAttribute $attribute)
Protected Attributes
$treeMenuKernel
Detailed Description
Definition at line 18 of file LegacyTreeMenuController.php.
Constructor & Destructor Documentation
eZ\Bundle\EzPublishLegacyBundle\Controller\LegacyTreeMenuController::__construct (\Closure $treeMenuKernelHandler, Loader $legacyKernelFactory, array $options = array())
Definition at line 25 of file LegacyTreeMenuController.php.
References eZ\Publish\Core\MVC\Legacy\Kernel\Loader\buildLegacyKernel().
    {
        $kernelClosure = $legacyKernelFactory->buildLegacyKernel( $treeMenuKernelHandler );
        $this->treeMenuKernel = $kernelClosure();
    }
Member Function Documentation
eZ\Bundle\EzPublishLegacyBundle\Controller\LegacyTreeMenuController::viewMenu ($nodeId, $modified, $expiry, $perm)
Action rendering the tree menu for admin interface. Note that parameters are not used at all since the request is entirely forwarded to the legacy kernel.
Parameters
int $nodeId
int $modified
int $expiry
string $perm
Returns
Definition at line 42 of file LegacyTreeMenuController.php.
References eZ\Publish\Core\MVC\Symfony\Controller\Controller\getParameter(), and eZ\Publish\Core\MVC\Symfony\Controller\Controller\getRequest().
    {
        $response = new Response();
        if ( $this->getParameter( 'treemenu.http_cache' ) )
        {
            $request = $this->getRequest();
            $response->setMaxAge( $this->getParameter( 'treemenu.ttl_cache' ) );
            // Aggressive cache : Always return a 304 response if "If-Modified-Since" request header is present.
            if ( $request->headers->has( 'If-Modified-Since' ) )
            {
                $response->setNotModified();
                return $response;
            }
        }
        $result = $this->treeMenuKernel->run();
        if ( $result->hasAttribute( 'lastModified' ) )
            $response->setLastModified( $result->getAttribute( 'lastModified' ) );
        $response->setContent( $result->getContent() );
        return $response;
    }
Member Data Documentation
eZ\Bundle\EzPublishLegacyBundle\Controller\LegacyTreeMenuController::$treeMenuKernel protected
Definition at line 23 of file LegacyTreeMenuController.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Bundle/EzPublishLegacyBundle/Controller/LegacyTreeMenuController.php