ezp-next: eZ\Bundle\EzPublishCoreBundle\HttpCache Class Reference
eZ\Bundle\EzPublishCoreBundle\HttpCache Class Reference
Protected Member Functions
createStore ()
invalidate (Request $request, $catch=false)
isPurgeRequestAllowed (Request $request)
isPurgeIPAllowed ($ip)
getPurgeAllowedIPs ()
Detailed Description
Definition at line 18 of file HttpCache.php.
Member Function Documentation
eZ\Bundle\EzPublishCoreBundle\HttpCache::createStore () protected
Definition at line 20 of file HttpCache.php.
    {
        return new LocationAwareStore( $this->cacheDir ?: $this->kernel->getCacheDir() . '/http_cache' );
    }
eZ\Bundle\EzPublishCoreBundle\HttpCache::getPurgeAllowedIPs () protected
Returns an array of allowed IPs for Http PURGE requests.
Returns
array
Definition at line 109 of file HttpCache.php.
    {
        return array( '127.0.0.1', '::1' );
    }
eZ\Bundle\EzPublishCoreBundle\HttpCache::invalidate (Request $request, $catch = false) protected
Handle invalidation, including Http PURGE requests. All non-allowed PURGE requests will receive an HTTP 405
Parameters
\Symfony\Component\HttpFoundation\Request $request
boolean $catch
Returns
Definition at line 34 of file HttpCache.php.
References eZ\Bundle\EzPublishCoreBundle\HttpCache\isPurgeRequestAllowed().
    {
        if ( $request->getMethod() !== 'PURGE' )
        {
            return parent::invalidate( $request, $catch );
        }
        // Reject all non-authorized clients
        if ( !$this->isPurgeRequestAllowed( $request ) )
        {
            return new Response( '', 405 );
        }
        $response = new Response();
        $store = $this->getStore();
        if ( $store instanceof RequestAwarePurger )
        {
            $result = $store->purgeByRequest( $request );
        }
        else
        {
            $result = $store->purge( $request->getUri() );
        }
        if ( $result === true )
        {
            $response->setStatusCode( 200, 'Purged' );
        }
        else
        {
            $response->setStatusCode( 404, 'Not purged' );
        }
        return $response;
    }
eZ\Bundle\EzPublishCoreBundle\HttpCache::isPurgeIPAllowed ($ip) protected
Checks if $ip is allowed for Http PURGE requests
Todo:
Check subnets
Parameters
string $ip
Returns
boolean
Definition at line 95 of file HttpCache.php.
References eZ\Bundle\EzPublishCoreBundle\HttpCache\getPurgeAllowedIPs().
    {
        $allowedIps = array_fill_keys( $this->getPurgeAllowedIPs(), true );
        if ( !isset( $allowedIps[$ip] ) )
            return false;
        return true;
    }
eZ\Bundle\EzPublishCoreBundle\HttpCache::isPurgeRequestAllowed (Request $request) protected
Checks if current purge request is allowed. This method can be overridden to extend the allowance test.
Parameters
\Symfony\Component\HttpFoundation\Request $request
Returns
boolean
Definition at line 78 of file HttpCache.php.
References eZ\Bundle\EzPublishCoreBundle\HttpCache\isPurgeIPAllowed().
    {
        if ( !$this->isPurgeIPAllowed( $request->getClientIp() ) )
            return false;
        return true;
    }
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Bundle/EzPublishCoreBundle/HttpCache.php