ezp-next: eZ\Publish\Core\REST\Server\Controller\ObjectState Class Reference
eZ\Publish\Core\REST\Server\Controller\ObjectState Class Reference
Public Member Functions
__construct (ObjectStateService $objectStateService, ContentService $contentService)
createObjectStateGroup ()
createObjectState ()
loadObjectStateGroup ()
loadObjectState ()
loadObjectStateGroups ()
loadObjectStates ()
deleteObjectStateGroup ()
deleteObjectState ()
updateObjectStateGroup ()
updateObjectState ()
getObjectStatesForContent ()
setObjectStatesForContent ()
Public Member Functions inherited from eZ\Publish\Core\REST\Server\Controller
setInputDispatcher (InputDispatcher $inputDispatcher)
setUrlHandler (UrlHandler $urlHandler)
setRequest (HttpRequest $request)
setContainer (Container $container)
Protected Attributes
$objectStateService
$contentService
Protected Attributes inherited from eZ\Publish\Core\REST\Server\Controller
$request
$inputDispatcher
$urlHandler
$container
Detailed Description
ObjectState controller
Definition at line 28 of file ObjectState.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Server\Controller\ObjectState::__construct (ObjectStateService $objectStateService, ContentService $contentService)
Construct controller
Parameters
\eZ\Publish\API\Repository\ObjectStateService $objectStateService
\eZ\Publish\API\Repository\ContentService $contentService
Definition at line 50 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\__construct().
    {
        $this->objectStateService = $objectStateService;
        $this->contentService = $contentService;
    }
Member Function Documentation
eZ\Publish\Core\REST\Server\Controller\ObjectState::createObjectState ()
Creates a new object state
Returns
Definition at line 91 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\createObjectState().
    {
        $values = $this->urlHandler->parse( 'objectstates', $this->request->path );
        $objectStateGroup = $this->objectStateService->loadObjectStateGroup( $values['objectstategroup'] );
        try
        {
            $createdObjectState = $this->objectStateService->createObjectState(
                $objectStateGroup,
                $this->inputDispatcher->parse(
                    new Message(
                        array( 'Content-Type' => $this->request->contentType ),
                        $this->request->body
                    )
                )
            );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        return new Values\CreatedObjectState(
            array(
                'objectState' => new RestObjectState(
                    $createdObjectState,
                    $objectStateGroup->id
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\ObjectState::createObjectStateGroup ()
Creates a new object state group
Returns
Definition at line 61 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\createObjectStateGroup().
    {
        try
        {
            $createdStateGroup = $this->objectStateService->createObjectStateGroup(
                $this->inputDispatcher->parse(
                    new Message(
                        array( 'Content-Type' => $this->request->contentType ),
                        $this->request->body
                    )
                )
            );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        return new Values\CreatedObjectStateGroup(
            array(
                'objectStateGroup' => $createdStateGroup
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\ObjectState::deleteObjectState ()
The given object state is deleted
Returns
Definition at line 197 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\deleteObjectState().
    {
        $values = $this->urlHandler->parse( 'objectstate', $this->request->path );
        $this->objectStateService->deleteObjectState(
            $this->objectStateService->loadObjectState( $values['objectstate'] )
        );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\ObjectState::deleteObjectStateGroup ()
The given object state group including the object states is deleted
Returns
Definition at line 182 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\deleteObjectStateGroup().
    {
        $values = $this->urlHandler->parse( 'objectstategroup', $this->request->path );
        $this->objectStateService->deleteObjectStateGroup(
            $this->objectStateService->loadObjectStateGroup( $values['objectstategroup'] )
        );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\ObjectState::getObjectStatesForContent ()
Returns the object states of content
Returns
Definition at line 268 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\getObjectStatesForContent().
    {
        $values = $this->urlHandler->parse( 'objectObjectStates', $this->request->path );
        $groups = $this->objectStateService->loadObjectStateGroups();
        $contentInfo = $this->contentService->loadContentInfo( $values['object'] );
        $contentObjectStates = array();
        foreach ( $groups as $group )
        {
            try
            {
                $state = $this->objectStateService->getContentState( $contentInfo, $group );
                $contentObjectStates[] = new RestObjectState( $state, $group->id );
            }
            catch ( NotFoundException $e )
            {
                // Do nothing
            }
        }
        return new ContentObjectStates( $contentObjectStates );
    }
eZ\Publish\Core\REST\Server\Controller\ObjectState::loadObjectState ()
Loads an object state
Returns
Definition at line 140 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\loadObjectState().
    {
        $values = $this->urlHandler->parse( 'objectstate', $this->request->path );
        return new RestObjectState(
            $this->objectStateService->loadObjectState( $values['objectstate'] ),
            $values['objectstategroup']
        );
    }
eZ\Publish\Core\REST\Server\Controller\ObjectState::loadObjectStateGroup ()
Loads an object state group
Returns
Definition at line 129 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\loadObjectStateGroup().
    {
        $values = $this->urlHandler->parse( 'objectstategroup', $this->request->path );
        return $this->objectStateService->loadObjectStateGroup( $values['objectstategroup'] );
    }
eZ\Publish\Core\REST\Server\Controller\ObjectState::loadObjectStateGroups ()
Returns a list of all object state groups
Returns
Definition at line 154 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\loadObjectStateGroups().
    {
        return new Values\ObjectStateGroupList(
            $this->objectStateService->loadObjectStateGroups()
        );
    }
eZ\Publish\Core\REST\Server\Controller\ObjectState::loadObjectStates ()
Returns a list of all object states of the given group
Returns
Definition at line 166 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\loadObjectStates().
    {
        $values = $this->urlHandler->parse( 'objectstates', $this->request->path );
        $objectStateGroup = $this->objectStateService->loadObjectStateGroup( $values['objectstategroup'] );
        return new Values\ObjectStateList(
            $this->objectStateService->loadObjectStates( $objectStateGroup ),
            $objectStateGroup->id
        );
    }
eZ\Publish\Core\REST\Server\Controller\ObjectState::setObjectStatesForContent ()
Updates object states of content An object state in the input overrides the state of the object state group
Returns
Definition at line 298 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\setObjectStatesForContent().
    {
        $values = $this->urlHandler->parse( 'objectObjectStates', $this->request->path );
        $newObjectStates = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $countByGroups = array();
        foreach ( $newObjectStates as $newObjectState )
        {
            $groupId = (int)$newObjectState->groupId;
            if ( array_key_exists( $groupId, $countByGroups ) )
            {
                $countByGroups[$groupId]++;
            }
            else
            {
                $countByGroups[$groupId] = 1;
            }
        }
        foreach ( $countByGroups as $groupId => $count )
        {
            if ( $count > 1 )
            {
                throw new ForbiddenException( "Multiple object states provided for group with ID $groupId" );
            }
        }
        $contentInfo = $this->contentService->loadContentInfo( $values['object'] );
        $contentObjectStates = array();
        foreach ( $newObjectStates as $newObjectState )
        {
            $objectStateGroup = $this->objectStateService->loadObjectStateGroup( $newObjectState->groupId );
            $this->objectStateService->setContentState( $contentInfo, $objectStateGroup, $newObjectState->objectState );
            $contentObjectStates[(int)$objectStateGroup->id] = $newObjectState;
        }
        return new ContentObjectStates( $contentObjectStates );
    }
eZ\Publish\Core\REST\Server\Controller\ObjectState::updateObjectState ()
Updates an object state
Returns
Definition at line 240 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\updateObjectState().
    {
        $values = $this->urlHandler->parse( 'objectstate', $this->request->path );
        $updateStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $objectState = $this->objectStateService->loadObjectState( $values['objectstate'] );
        try
        {
            $updatedObjectState = $this->objectStateService->updateObjectState( $objectState, $updateStruct );
            return new RestObjectState( $updatedObjectState, $values['objectstategroup'] );
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
    }
eZ\Publish\Core\REST\Server\Controller\ObjectState::updateObjectStateGroup ()
Updates an object state group
Returns
Definition at line 212 of file ObjectState.php.
References eZ\Publish\Core\REST\Server\Controller\ObjectState\updateObjectStateGroup().
    {
        $values = $this->urlHandler->parse( 'objectstategroup', $this->request->path );
        $updateStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $objectStateGroup = $this->objectStateService->loadObjectStateGroup( $values['objectstategroup'] );
        try
        {
            $updatedStateGroup = $this->objectStateService->updateObjectStateGroup( $objectStateGroup, $updateStruct );
            return $updatedStateGroup;
        }
        catch ( InvalidArgumentException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
    }
Member Data Documentation
eZ\Publish\Core\REST\Server\Controller\ObjectState::$contentService protected
Definition at line 42 of file ObjectState.php.
eZ\Publish\Core\REST\Server\Controller\ObjectState::$objectStateService protected
Definition at line 35 of file ObjectState.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Controller/ObjectState.php