ezp-next: eZ\Publish\Core\REST\Server\Controller\Content Class Reference
eZ\Publish\Core\REST\Server\Controller\Content Class Reference
Public Member Functions
__construct (ContentService $contentService, LocationService $locationService, SectionService $sectionService, SearchService $searchService)
loadContentInfoByRemoteId ()
loadContent ()
updateContentMetadata ()
redirectCurrentVersion ()
loadContentInVersion ()
createContent ()
deleteContent ()
copyContent ()
loadContentVersions ()
deleteContentVersion ()
createDraftFromVersion ()
createDraftFromCurrentVersion ()
updateVersion ()
publishVersion ()
redirectCurrentVersionRelations ()
loadVersionRelations ()
loadVersionRelation ()
removeRelation ()
createRelation ()
createView ()
Public Member Functions inherited from eZ\Publish\Core\REST\Server\Controller
setInputDispatcher (InputDispatcher $inputDispatcher)
setUrlHandler (UrlHandler $urlHandler)
setRequest (HttpRequest $request)
setContainer (Container $container)
Protected Member Functions
getMediaType ()
Protected Attributes
$contentService
$locationService
$sectionService
$searchService
Protected Attributes inherited from eZ\Publish\Core\REST\Server\Controller
$request
$inputDispatcher
$urlHandler
$container
Detailed Description
Content controller
Definition at line 32 of file Content.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Server\Controller\Content::__construct (ContentService $contentService, LocationService $locationService, SectionService $sectionService, SearchService $searchService)
Construct controller
Parameters
\eZ\Publish\API\Repository\ContentService $contentService
\eZ\Publish\API\Repository\LocationService $locationService
\eZ\Publish\API\Repository\SectionService $sectionService
\eZ\Publish\API\Repository\SearchService $searchService
Definition at line 70 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\__construct().
    {
        $this->contentService  = $contentService;
        $this->locationService = $locationService;
        $this->sectionService  = $sectionService;
        $this->searchService   = $searchService;
    }
Member Function Documentation
eZ\Publish\Core\REST\Server\Controller\Content::copyContent ()
Creates a new content object as copy under the given parent location given in the destination header.
Returns
Definition at line 309 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\copyContent().
    {
        $urlValues = $this->urlHandler->parse( 'object', $this->request->path );
        $destinationValues = $this->urlHandler->parse( 'location', $this->request->destination );
        $parentLocationParts = explode( '/', $destinationValues['location'] );
        $copiedContent = $this->contentService->copyContent(
            $this->contentService->loadContentInfo( $urlValues['object'] ),
            $this->locationService->newLocationCreateStruct( array_pop( $parentLocationParts ) )
        );
        return new Values\ResourceCreated(
            $this->urlHandler->generate(
                'object',
                array( 'object' => $copiedContent->id )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::createContent ()
Creates a new content draft assigned to the authenticated user. If a different userId is given in the input it is assigned to the given user but this required special rights for the authenticated user (this is useful for content staging where the transfer process does not have to authenticate with the user which created the content object in the source server). The user has to publish the content if it should be visible.
Returns
Definition at line 253 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\createContent(), and eZ\Publish\Core\REST\Server\Controller\Content\getMediaType().
    {
        $contentCreate = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $content = $this->contentService->createContent(
            $contentCreate->contentCreateStruct,
            array( $contentCreate->locationCreateStruct )
        );
        $contentValue = null;
        $relations = null;
        if ( $this->getMediaType( $this->request ) === 'application/vnd.ez.api.content' )
        {
            $contentValue = $content;
            $relations = $this->contentService->loadRelations( $contentValue->getVersionInfo() );
        }
        return new Values\CreatedContent(
            array(
                'content' => new Values\RestContent(
                    $content->contentInfo,
                    null,
                    $contentValue,
                    $relations
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::createDraftFromCurrentVersion ()
The system creates a new draft version as a copy from the current version
Returns
Definition at line 404 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\createDraftFromCurrentVersion(), and eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_DRAFT.
    {
        $urlValues = $this->urlHandler->parse( 'objectCurrentVersion', $this->request->path );
        $contentInfo = $this->contentService->loadContentInfo( $urlValues['object'] );
        $versionInfo = $this->contentService->loadVersionInfo(
            $contentInfo
        );
        if ( $versionInfo->status === VersionInfo::STATUS_DRAFT )
        {
            throw new ForbiddenException( 'Current version is already in status DRAFT' );
        }
        $contentDraft = $this->contentService->createContentDraft( $contentInfo );
        return new Values\CreatedVersion(
            array(
                'version' => new Values\Version(
                    $contentDraft,
                    $this->contentService->loadRelations( $contentDraft->getVersionInfo() )
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::createDraftFromVersion ()
The system creates a new draft version as a copy from the given version
Returns
Definition at line 377 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\createDraftFromVersion().
    {
        $urlValues = $this->urlHandler->parse( 'objectVersion', $this->request->path );
        $contentInfo = $this->contentService->loadContentInfo( $urlValues['object'] );
        $contentDraft = $this->contentService->createContentDraft(
            $contentInfo,
            $this->contentService->loadVersionInfo(
                $contentInfo, $urlValues['version']
            )
        );
        return new Values\CreatedVersion(
            array(
                'version' => new Values\Version(
                    $contentDraft,
                    $this->contentService->loadRelations( $contentDraft->getVersionInfo() )
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::createRelation ()
Creates a new relation of type COMMON for the given draft.
Returns
Definition at line 637 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\createRelation(), and eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_DRAFT.
    {
        $urlValues = $this->urlHandler->parse( 'objectVersionRelations', $this->request->path );
        $destinationContentId = $updateStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $contentInfo = $this->contentService->loadContentInfo( $urlValues['object'] );
        $versionInfo = $this->contentService->loadVersionInfo( $contentInfo, $urlValues['version'] );
        if ( $versionInfo->status !== VersionInfo::STATUS_DRAFT )
        {
            throw new ForbiddenException( "Relation of type COMMON can only be added to drafts" );
        }
        try
        {
            $destinationContentInfo = $this->contentService->loadContentInfo( $destinationContentId );
        }
        catch ( NotFoundException $e )
        {
            throw new ForbiddenException( $e->getMessage() );
        }
        $existingRelations = $this->contentService->loadRelations( $versionInfo );
        foreach ( $existingRelations as $existingRelation )
        {
            if ( $existingRelation->getDestinationContentInfo()->id == $destinationContentId )
            {
                throw new ForbiddenException( "Relation of type COMMON to selected destination content ID already exists" );
            }
        }
        $relation = $this->contentService->addRelation( $versionInfo, $destinationContentInfo );
        return new Values\CreatedRelation(
            array(
                'relation' => new Values\RestRelation( $relation, $urlValues['object'], $urlValues['version'] )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::createView ()
Creates and executes a content view
Returns
Definition at line 685 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\createView().
    {
        $viewInput = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        return new Values\RestExecutedView(
            array(
                'identifier'    => $viewInput->identifier,
                'searchResults' => $this->searchService->findContent( $viewInput->query ),
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::deleteContent ()
The content is deleted. If the content has locations (which is required in 4.x) on delete all locations assigned the content object are deleted via delete subtree.
Returns
Definition at line 293 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\deleteContent().
    {
        $urlValues = $this->urlHandler->parse( 'object', $this->request->path );
        $this->contentService->deleteContent(
            $this->contentService->loadContentInfo( $urlValues['object'] )
        );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\Content::deleteContentVersion ()
The version is deleted
Returns
Definition at line 351 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\deleteContentVersion(), and eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_PUBLISHED.
    {
        $urlValues = $this->urlHandler->parse( 'objectVersion', $this->request->path );
        $versionInfo = $this->contentService->loadVersionInfo(
            $this->contentService->loadContentInfo( $urlValues['object'] ),
            $urlValues['version']
        );
        if ( $versionInfo->status === VersionInfo::STATUS_PUBLISHED )
        {
            throw new ForbiddenException( 'Version in status PUBLISHED cannot be deleted' );
        }
        $this->contentService->deleteVersion(
            $versionInfo
        );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\Content::getMediaType () protected
Extracts the requested media type from $request
Returns
string
Definition at line 706 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\getMediaType().
    {
        foreach ( $this->request->mimetype as $mimeType )
        {
            if ( preg_match( '(^([a-z0-9-/.]+)\+.*$)', $mimeType['value'], $matches ) )
            {
                return $matches[1];
            }
        }
        return 'unknown/unknown';
    }
eZ\Publish\Core\REST\Server\Controller\Content::loadContent ()
Loads a content info, potentially with the current version embedded
Returns
Definition at line 105 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\getMediaType(), and eZ\Publish\Core\REST\Server\Controller\Content\loadContent().
    {
        $questionMark = strpos( $this->request->path, '?' );
        $requestPath = $questionMark !== false ? substr( $this->request->path, 0, $questionMark ) : $this->request->path;
        $urlValues = $this->urlHandler->parse( 'object', $requestPath );
        $contentInfo = $this->contentService->loadContentInfo( $urlValues['object'] );
        $mainLocation = $this->locationService->loadLocation( $contentInfo->mainLocationId );
        $contentVersion = null;
        $relations = null;
        if ( $this->getMediaType( $this->request ) === 'application/vnd.ez.api.content' )
        {
            $languages = null;
            if ( isset( $this->request->variables['languages'] ) )
            {
                $languages = explode( ',', $this->request->variables['languages'] );
            }
            $contentVersion = $this->contentService->loadContent( $urlValues['object'], $languages );
            $relations = $this->contentService->loadRelations( $contentVersion->getVersionInfo() );
        }
        return new Values\RestContent( $contentInfo, $mainLocation, $contentVersion, $relations, $this->request->path );
    }
eZ\Publish\Core\REST\Server\Controller\Content::loadContentInfoByRemoteId ()
Loads a content info by remote ID
Returns
Definition at line 83 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\loadContentInfoByRemoteId().
    {
        $contentInfo = $this->contentService->loadContentInfoByRemoteId(
            // GET variable
            $this->request->variables['remoteId']
        );
        return new Values\ContentList(
            array(
                new Values\RestContent(
                    $contentInfo,
                    $this->locationService->loadLocation( $contentInfo->mainLocationId )
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::loadContentInVersion ()
Loads a specific version of a given content object
Returns
Definition at line 217 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\loadContentInVersion().
    {
        $questionMark = strpos( $this->request->path, '?' );
        $requestPath = $questionMark !== false ? substr( $this->request->path, 0, $questionMark ) : $this->request->path;
        $urlValues = $this->urlHandler->parse( 'objectVersion', $requestPath );
        $languages = null;
        if ( isset( $this->request->variables['languages'] ) )
        {
            $languages = explode( ',', $this->request->variables['languages'] );
        }
        $content = $this->contentService->loadContent(
            $urlValues['object'],
            $languages,
            $urlValues['version']
        );
        return new Values\Version(
            $content,
            $this->contentService->loadRelations( $content->getVersionInfo() ),
            $this->request->path
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::loadContentVersions ()
Returns a list of all versions of the content. This method does not include fields and relations in the Version elements of the response.
Returns
Definition at line 334 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\loadContentVersions().
    {
        $urlValues = $this->urlHandler->parse( 'objectVersions', $this->request->path );
        return new Values\VersionList(
            $this->contentService->loadVersions(
                $this->contentService->loadContentInfo( $urlValues['object'] )
            ),
            $this->request->path
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::loadVersionRelation ()
Loads a relation for the given content object and version
Returns
Definition at line 573 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\loadVersionRelation().
    {
        $urlValues = $this->urlHandler->parse( 'objectVersionRelation', $this->request->path );
        $relationList = $this->contentService->loadRelations(
            $this->contentService->loadVersionInfo(
                $this->contentService->loadContentInfo( $urlValues['object'] ),
                $urlValues['version']
            )
        );
        foreach ( $relationList as $relation )
        {
            if ( $relation->id == $urlValues['relation'] )
            {
                return new Values\RestRelation( $relation, $urlValues['object'], $urlValues['version'] );
            }
        }
        throw new Exceptions\NotFoundException( "Relation not found: '{$this->request->path}'." );
    }
eZ\Publish\Core\REST\Server\Controller\Content::loadVersionRelations ()
Loads the relations of the given version
Returns
Definition at line 537 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\loadVersionRelations().
    {
        $questionMark = strpos( $this->request->path, '?' );
        $requestPath = $questionMark !== false ? substr( $this->request->path, 0, $questionMark ) : $this->request->path;
        $urlValues = $this->urlHandler->parse( 'objectVersionRelations', $requestPath );
        $offset = isset( $this->request->variables['offset'] ) ? (int)$this->request->variables['offset'] : 0;
        $limit = isset( $this->request->variables['limit'] ) ? (int)$this->request->variables['limit'] : -1;
        $relationList = $this->contentService->loadRelations(
            $this->contentService->loadVersionInfo(
                $this->contentService->loadContentInfo( $urlValues['object'] ),
                $urlValues['version']
            )
        );
        $relationList = array_slice(
            $relationList,
            $offset >= 0 ? $offset : 0,
            $limit >= 0 ? $limit : null
        );
        return new Values\RelationList(
            $relationList,
            $urlValues['object'],
            $urlValues['version'],
            $this->request->path
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::publishVersion ()
The content version is published
Returns
Definition at line 490 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\publishVersion(), and eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_DRAFT.
    {
        $urlValues = $this->urlHandler->parse( 'objectVersion', $this->request->path );
        $versionInfo = $this->contentService->loadVersionInfo(
            $this->contentService->loadContentInfo( $urlValues['object'] ),
            $urlValues['version']
        );
        if ( $versionInfo->status !== VersionInfo::STATUS_DRAFT )
        {
            throw new ForbiddenException( 'Only version in status DRAFT can be published' );
        }
        $this->contentService->publishVersion(
            $versionInfo
        );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\Content::redirectCurrentVersion ()
Loads a specific version of a given content object
Returns
Definition at line 193 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\redirectCurrentVersion().
    {
        $urlValues = $this->urlHandler->parse( 'objectCurrentVersion', $this->request->path );
        $versionInfo = $this->contentService->loadVersionInfo(
            $this->contentService->loadContentInfo( $urlValues['object'] )
        );
        return new Values\TemporaryRedirect(
            $this->urlHandler->generate(
                'objectVersion',
                array(
                    'object' => $urlValues['object'],
                    'version' => $versionInfo->versionNo
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::redirectCurrentVersionRelations ()
Redirects to the relations of the current version
Returns
Definition at line 516 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\redirectCurrentVersionRelations().
    {
        $urlValues = $this->urlHandler->parse( 'objectrelations', $this->request->path );
        $contentInfo = $this->contentService->loadContentInfo( $urlValues['object'] );
        return new Values\TemporaryRedirect(
            $this->urlHandler->generate(
                'objectVersionRelations',
                array(
                    'object' => $urlValues['object'],
                    'version' => $contentInfo->currentVersionNo
                )
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::removeRelation ()
Deletes a relation of the given draft.
Returns
Definition at line 600 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\removeRelation(), and eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_DRAFT.
    {
        $urlValues = $this->urlHandler->parse( 'objectVersionRelation', $this->request->path );
        $versionInfo = $this->contentService->loadVersionInfo(
            $this->contentService->loadContentInfo( $urlValues['object'] ),
            $urlValues['version']
        );
        $versionRelations = $this->contentService->loadRelations( $versionInfo );
        foreach ( $versionRelations as $relation )
        {
            if ( $relation->id == $urlValues['relation'] )
            {
                if ( $relation->type !== Relation::COMMON )
                {
                    throw new ForbiddenException( "Relation is not of type COMMON" );
                }
                if ( $versionInfo->status !== VersionInfo::STATUS_DRAFT )
                {
                    throw new ForbiddenException( "Relation of type COMMON can only be removed from drafts" );
                }
                $this->contentService->deleteRelation( $versionInfo, $relation->getDestinationContentInfo() );
                return new Values\NoContent();
            }
        }
        throw new Exceptions\NotFoundException( "Relation not found: '{$this->request->path}'." );
    }
eZ\Publish\Core\REST\Server\Controller\Content::updateContentMetadata ()
Updates a content's metadata
Returns
Definition at line 137 of file Content.php.
References eZ\Publish\Core\REST\Server\Controller\Content\updateContentMetadata().
    {
        $updateStruct = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        $values = $this->urlHandler->parse( 'object', $this->request->path );
        $contentId = (int)$values['object'];
        $contentInfo = $this->contentService->loadContentInfo( $contentId );
        // update section
        if ( $updateStruct->sectionId !== null )
        {
            $section = $this->sectionService->loadSection( $updateStruct->sectionId );
            $this->sectionService->assignSection( $contentInfo, $section );
            $updateStruct->sectionId = null;
        }
        // @todo Consider refactoring! ContentService::updateContentMetadata throws the same exception
        // in case the updateStruct is empty and if remoteId already exists. Since REST version of update struct
        // includes section ID in addition to other fields, we cannot throw exception if only sectionId property
        // is set, so we must skip updating content in that case instead of allowing propagation of the exception.
        foreach ( $updateStruct as $propertyName => $propertyValue )
        {
            if ( $propertyName !== 'sectionId' && $propertyValue !== null )
            {
                // update content
                $this->contentService->updateContentMetadata( $contentInfo, $updateStruct );
                $contentInfo = $this->contentService->loadContentInfo( $contentId );
                break;
            }
        }
        try
        {
            $locationInfo = $this->locationService->loadLocation( $contentInfo->mainLocationId );
        }
        catch ( NotFoundException $e )
        {
            $locationInfo = null;
        }
        return new Values\RestContent(
            $contentInfo,
            $locationInfo
        );
    }
eZ\Publish\Core\REST\Server\Controller\Content::updateVersion ()
A specific draft is updated.
Returns
Definition at line 435 of file Content.php.
References eZ\Publish\SPI\Persistence\Content\VersionInfo\STATUS_DRAFT, and eZ\Publish\Core\REST\Server\Controller\Content\updateVersion().
    {
        $questionMark = strpos( $this->request->path, '?' );
        $requestPath = $questionMark !== false ? substr( $this->request->path, 0, $questionMark ) : $this->request->path;
        $urlValues = $this->urlHandler->parse( 'objectVersion', $requestPath );
        $contentUpdateStruct = $this->inputDispatcher->parse(
            new Message(
                array(
                    'Content-Type' => $this->request->contentType,
                    // @todo Needs refactoring! Temporary solution so parser has access to URL
                    'Url' => $requestPath
                ),
                $this->request->body
            )
        );
        $versionInfo = $this->contentService->loadVersionInfo(
            $this->contentService->loadContentInfo( $urlValues['object'] ),
            $urlValues['version']
        );
        if ( $versionInfo->status !== VersionInfo::STATUS_DRAFT )
        {
            throw new ForbiddenException( 'Only version in status DRAFT can be updated' );
        }
        $this->contentService->updateContent( $versionInfo, $contentUpdateStruct );
        $languages = null;
        if ( isset( $this->request->variables['languages'] ) )
        {
            $languages = explode( ',', $this->request->variables['languages'] );
        }
        // Reload the content to handle languages GET parameter
        $content = $this->contentService->loadContent(
            $urlValues['object'],
            $languages,
            $versionInfo->versionNo
        );
        return new Values\Version(
            $content,
            $this->contentService->loadRelations( $content->getVersionInfo() ),
            $this->request->path
        );
    }
Member Data Documentation
eZ\Publish\Core\REST\Server\Controller\Content::$contentService protected
Definition at line 39 of file Content.php.
eZ\Publish\Core\REST\Server\Controller\Content::$locationService protected
Definition at line 46 of file Content.php.
eZ\Publish\Core\REST\Server\Controller\Content::$searchService protected
Definition at line 60 of file Content.php.
eZ\Publish\Core\REST\Server\Controller\Content::$sectionService protected
Definition at line 53 of file Content.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Controller/Content.php