ezp-next: eZ\Publish\Core\REST\Server\Controller\URLAlias Class Reference
eZ\Publish\Core\REST\Server\Controller\URLAlias Class Reference
Public Member Functions
__construct (URLAliasService $urlAliasService, LocationService $locationService)
loadURLAlias ()
listGlobalURLAliases ()
listLocationURLAliases ()
createURLAlias ()
deleteURLAlias ()
Public Member Functions inherited from eZ\Publish\Core\REST\Server\Controller
setInputDispatcher (InputDispatcher $inputDispatcher)
setUrlHandler (UrlHandler $urlHandler)
setRequest (HttpRequest $request)
setContainer (Container $container)
Protected Attributes
$urlAliasService
$locationService
Protected Attributes inherited from eZ\Publish\Core\REST\Server\Controller
$request
$inputDispatcher
$urlHandler
$container
Detailed Description
URLAlias controller
Definition at line 24 of file URLAlias.php.
Constructor & Destructor Documentation
eZ\Publish\Core\REST\Server\Controller\URLAlias::__construct (URLAliasService $urlAliasService, LocationService $locationService)
Construct controller
Parameters
\eZ\Publish\API\Repository\URLAliasService $urlAliasService
\eZ\Publish\API\Repository\LocationService $locationService
Definition at line 46 of file URLAlias.php.
References eZ\Publish\Core\REST\Server\Controller\URLAlias\__construct().
    {
        $this->urlAliasService = $urlAliasService;
        $this->locationService = $locationService;
    }
Member Function Documentation
eZ\Publish\Core\REST\Server\Controller\URLAlias::createURLAlias ()
Creates a new URL alias
Returns
Definition at line 106 of file URLAlias.php.
References eZ\Publish\Core\REST\Server\Controller\URLAlias\createURLAlias().
    {
        $urlAliasCreate = $this->inputDispatcher->parse(
            new Message(
                array( 'Content-Type' => $this->request->contentType ),
                $this->request->body
            )
        );
        if ( $urlAliasCreate['_type'] === 'LOCATION' )
        {
            $locationUrlValues = $this->urlHandler->parse( 'location', $urlAliasCreate['location']['_href'] );
            $locationPathParts = explode( '/', $locationUrlValues['location'] );
            $location = $this->locationService->loadLocation(
                array_pop( $locationPathParts )
            );
            try
            {
                $createdURLAlias = $this->urlAliasService->createUrlAlias(
                    $location,
                    $urlAliasCreate['path'],
                    $urlAliasCreate['languageCode'],
                    $urlAliasCreate['forward'],
                    $urlAliasCreate['alwaysAvailable']
                );
            }
            catch ( InvalidArgumentException $e )
            {
                throw new ForbiddenException( $e->getMessage() );
            }
        }
        else
        {
            try
            {
                $createdURLAlias = $this->urlAliasService->createGlobalUrlAlias(
                    $urlAliasCreate['resource'],
                    $urlAliasCreate['path'],
                    $urlAliasCreate['languageCode'],
                    $urlAliasCreate['forward'],
                    $urlAliasCreate['alwaysAvailable']
                );
            }
            catch ( InvalidArgumentException $e )
            {
                throw new ForbiddenException( $e->getMessage() );
            }
        }
        return new Values\CreatedURLAlias(
            array(
                'urlAlias' => $createdURLAlias
            )
        );
    }
eZ\Publish\Core\REST\Server\Controller\URLAlias::deleteURLAlias ()
The given URL alias is deleted
Returns
Definition at line 169 of file URLAlias.php.
References eZ\Publish\Core\REST\Server\Controller\URLAlias\deleteURLAlias().
    {
        $urlValues = $this->urlHandler->parse( 'urlAlias', $this->request->path );
        $this->urlAliasService->removeAliases(
            array(
                $this->urlAliasService->load( $urlValues['urlalias'] )
            )
        );
        return new Values\NoContent();
    }
eZ\Publish\Core\REST\Server\Controller\URLAlias::listGlobalURLAliases ()
Returns the list of global URL aliases
Returns
Definition at line 68 of file URLAlias.php.
References eZ\Publish\Core\REST\Server\Controller\URLAlias\listGlobalURLAliases().
    {
        return new Values\URLAliasRefList(
            $this->urlAliasService->listGlobalAliases(),
            $this->urlHandler->generate( 'urlAliases' )
        );
    }
eZ\Publish\Core\REST\Server\Controller\URLAlias::listLocationURLAliases ()
Returns the list of URL aliases for a location
Returns
Definition at line 81 of file URLAlias.php.
References eZ\Publish\Core\REST\Server\Controller\URLAlias\listLocationURLAliases().
    {
        $questionMark = strpos( $this->request->path, '?' );
        $requestPath = $questionMark !== false ? substr( $this->request->path, 0, $questionMark ) : $this->request->path;
        $urlValues = $this->urlHandler->parse( 'locationUrlAliases', $requestPath );
        $locationPathParts = explode( '/', $urlValues['location'] );
        $location = $this->locationService->loadLocation(
            array_pop( $locationPathParts )
        );
        $custom = isset( $this->request->variables['custom'] ) && $this->request->variables['custom'] === 'false' ? false : true;
        return new Values\URLAliasRefList(
            $this->urlAliasService->listLocationAliases( $location, $custom ),
            $this->request->path
        );
    }
eZ\Publish\Core\REST\Server\Controller\URLAlias::loadURLAlias ()
Returns the URL alias with the given ID
Returns
Definition at line 57 of file URLAlias.php.
References eZ\Publish\Core\REST\Server\Controller\URLAlias\loadURLAlias().
    {
        $urlValues = $this->urlHandler->parse( 'urlAlias', $this->request->path );
        return $this->urlAliasService->load( $urlValues['urlalias'] );
    }
Member Data Documentation
eZ\Publish\Core\REST\Server\Controller\URLAlias::$locationService protected
Definition at line 38 of file URLAlias.php.
eZ\Publish\Core\REST\Server\Controller\URLAlias::$urlAliasService protected
Definition at line 31 of file URLAlias.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/REST/Server/Controller/URLAlias.php