ezp-next: eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native Class Reference
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native Class Reference
Public Member Functions
__construct (HttpClient $client, CriterionVisitor $criterionVisitor, SortClauseVisitor $sortClauseVisitor, FacetBuilderVisitor $facetBuilderVisitor, FieldValueMapper $fieldValueMapper, ContentHandler $contentHandler, FieldNameGenerator $nameGenerator)
findContent (Query $query, array $fieldFilters=array())
indexContent (array $document)
purgeIndex ()
Protected Member Functions
createUpdate (array $document)
Protected Attributes
$client
$criterionVisitor
$sortClauseVisitor
$facetBuilderVisitor
$fieldValueMapper
$contentHandler
$nameGenerator
Detailed Description
The Content Search Gateway provides the implementation for one database to retrieve the desired content objects.
Definition at line 27 of file Native.php.
Constructor & Destructor Documentation
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::__construct (HttpClient $client, CriterionVisitor $criterionVisitor, SortClauseVisitor $sortClauseVisitor, FacetBuilderVisitor $facetBuilderVisitor, FieldValueMapper $fieldValueMapper, ContentHandler $contentHandler, FieldNameGenerator $nameGenerator)
Construct from HTTP client
Parameters
HttpClient $client
CriterionVisitor $criterionVisitor
SortClauseVisitor $sortClauseVisitor
FacetBuilderVisitor $facetBuilderVisitor
FieldValueMapper $fieldValueMapper
ContentHandler $contentHandler
Returns
void
Definition at line 90 of file Native.php.
References eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native\__construct().
    {
        $this->client              = $client;
        $this->criterionVisitor    = $criterionVisitor;
        $this->sortClauseVisitor   = $sortClauseVisitor;
        $this->facetBuilderVisitor = $facetBuilderVisitor;
        $this->fieldValueMapper    = $fieldValueMapper;
        $this->contentHandler      = $contentHandler;
        $this->nameGenerator       = $nameGenerator;
    }
Member Function Documentation
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::createUpdate (array $document) protected
Create document update XML
Parameters
array $document
Returns
string
Definition at line 225 of file Native.php.
References eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native\createUpdate().
    {
        $xml = new \XmlWriter();
        $xml->openMemory();
        $xml->startElement( 'add' );
        $xml->startElement( 'doc' );
        foreach ( $document as $field )
        {
            foreach ( (array)$this->fieldValueMapper->map( $field ) as $value )
            {
                $xml->startElement( 'field' );
                $xml->writeAttribute(
                    'name',
                    $this->nameGenerator->getTypedName( $field->name, $field->type )
                );
                $xml->text( $value );
                $xml->endElement();
            }
        }
        $xml->endElement();
        $xml->endElement();
        return $xml->outputMemory( true );
    }
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::findContent (Query $query, array $fieldFilters = array())
Finds content objects for the given query.
Todo:
define structs for the field filters
Parameters
\eZ\Publish\API\Repository\Values\Content\Query $query
array $fieldFilters - a map of filters for the returned fields. Currently supported: array("languages" => array(<language1>,..)).
Returns
Reimplemented from eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway.
Definition at line 112 of file Native.php.
    {
        // @todo: Extract method
        $response = $this->client->request(
            'GET',
            '/solr/select?' .
            http_build_query(
                array(
                    'q'    => $this->criterionVisitor->visit( $query->criterion ),
                    'sort' => implode(
                        ', ',
                        array_map(
                            array( $this->sortClauseVisitor, 'visit' ),
                            $query->sortClauses
                        )
                    ),
                    'fl'   => '*,score',
                    'wt'   => 'json',
                )
            ) .
            ( count( $query->facetBuilders ) ? '&facet=true&facet.sort=count&' : '' ) .
            implode(
                '&',
                array_map(
                    array( $this->facetBuilderVisitor, 'visit' ),
                    $query->facetBuilders
                )
            )
        );
        // @todo: Error handling?
        $data = json_decode( $response->body );
        // @todo: Extract method
        $result = new SearchResult(
            array(
                'time'       => $data->responseHeader->QTime / 1000,
                'maxScore'   => $data->response->maxScore,
                'totalCount' => $data->response->numFound,
            )
        );
        foreach ( $data->response->docs as $doc )
        {
            $searchHit = new SearchHit(
                array(
                    'score'       => $doc->score,
                    'valueObject' => $this->contentHandler->load( $doc->id, $doc->version_id )
                )
            );
            $result->searchHits[] = $searchHit;
        }
        if ( isset( $data->facet_counts ) )
        {
            foreach ( $data->facet_counts->facet_fields as $field => $facet )
            {
                $result->facets[] = $this->facetBuilderVisitor->map( $field, $facet );
            }
        }
        return $result;
    }
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::indexContent (array $document)
Indexes a content object
Parameters
\eZ\Publish\SPI\Persistence\Content\Search\Field[] $document
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway.
Definition at line 182 of file Native.php.
References eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native\createUpdate().
    {
        $update   = $this->createUpdate( $document );
        $result   = $this->client->request(
            'POST',
            '/solr/update?commit=true&wt=json',
            new Message(
                array(
                    'Content-Type: text/xml',
                ),
                $update
            )
        );
        // @todo: Add error handling
    }
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::purgeIndex ()
Purges all contents from the index
Returns
void
Reimplemented from eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway.
Definition at line 204 of file Native.php.
    {
        $this->client->request(
            'POST',
            '/solr/update?commit=true&wt=json',
            new Message(
                array(
                    'Content-Type: text/xml',
                ),
                '<delete><query>*:*</query></delete>'
            )
        );
    }
Member Data Documentation
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::$client protected
Definition at line 34 of file Native.php.
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::$contentHandler protected
Definition at line 69 of file Native.php.
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::$criterionVisitor protected
Definition at line 41 of file Native.php.
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::$facetBuilderVisitor protected
Definition at line 55 of file Native.php.
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::$fieldValueMapper protected
Definition at line 62 of file Native.php.
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::$nameGenerator protected
Definition at line 76 of file Native.php.
eZ\Publish\Core\Persistence\Solr\Content\Search\Gateway\Native::$sortClauseVisitor protected
Definition at line 48 of file Native.php.
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/PAPI-doxygen-master/workspace/eZ/Publish/Core/Persistence/Solr/Content/Search/Gateway/Native.php